Repository paradigmxyz/reth, pull requests merged in 2022-12, with the labels that each got.

#356 chore(sync): remove timeout from downloader
  crates/interfaces/src/p2p/headers/downloader.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/headers-downloaders/src/linear.rs
Labels: A-staged-sync, C-debt

#354 feat(rpc): add eth_pubsub skeleton
  crates/net/rpc-api/src/eth_pubsub.rs
  crates/net/rpc/src/eth/api/mod.rs
  crates/net/rpc/src/eth/api/server.rs
  crates/net/rpc/src/eth/mod.rs
  crates/net/rpc/src/eth/pubsub.rs
  crates/net/rpc/src/lib.rs
Labels: A-rpc

#361 add github link for book
  book/README.md
Labels: C-docs

#362 fix(interfaces/db): remove unused `$seek:ty` token in table! macro
  crates/interfaces/src/db/tables.rs
Labels: A-db

#359 fix(net): prevent bad loop if no peers available
  crates/net/network/src/fetch/mod.rs
Labels: A-networking

#369 feat(net): integrate TaskExecutor
  Cargo.lock
  crates/net/network/Cargo.toml
  crates/net/network/src/config.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/session/mod.rs
  crates/tasks/src/lib.rs
Labels: A-networking

#379 chore(txpool): deny additional lints
  crates/transaction-pool/src/identifier.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/pool/listener.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/test_util/mock.rs
  crates/transaction-pool/src/test_util/mod.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate.rs
Labels: A-tx-pool

#378 feat(txpool): implement missing remove function
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#376 chore(txpool): update TransactionPool trait bounds
  crates/net/network/src/transactions.rs
  crates/net/rpc/src/eth/api/mod.rs
  crates/net/rpc/src/eth/api/server.rs
  crates/net/rpc/src/eth/pubsub.rs
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#383 fix(tx-pool): expose TransactionOrigin
  crates/transaction-pool/src/lib.rs
Labels: A-tx-pool

#385 feat(disc): support discport query and add display impl
  crates/net/discv4/src/node.rs
Labels: A-networking

#386 feat(net): expose config settings
  crates/net/network/src/peers/manager.rs
Labels: C-enhancement, A-networking

#384 docs: add Installing Documentation
  docs/README.md
  docs/installation/README.md
Labels: C-docs

#363 feat(rpc): net namespace
  Cargo.lock
  crates/net/rpc/Cargo.toml
  crates/net/rpc/src/eth/api/mod.rs
  crates/net/rpc/src/eth/api/server.rs
  crates/net/rpc/src/eth/mod.rs
  crates/net/rpc/src/lib.rs
  crates/net/rpc/src/net/mod.rs
Labels: C-enhancement, A-rpc

#398 fix(net): outgoing requsts
  crates/net/network/src/manager.rs
  crates/net/network/src/peers/manager.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/test_util/mock.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate.rs
Labels: A-networking

#397 feat(p2p): remove p2p crate
  Cargo.lock
  Cargo.toml
  crates/net/p2p/Cargo.toml
  crates/net/p2p/src/anchor.rs
  crates/net/p2p/src/lib.rs
Labels: A-devp2p

#396 fix(eth-wire): remove inaccurate status doc
  crates/net/eth-wire/src/types/status.rs
Labels: C-docs, A-devp2p

#402 chore: fix some typos
  crates/executor/src/executor.rs
  crates/storage/db/src/abstraction/cursor.rs
Labels: C-docs

#401 feat(sync): senders commit threshold
  crates/stages/src/stages/senders.rs
Labels: C-enhancement, A-staged-sync

#395 tests(hex_bytes): add unit tests
  crates/primitives/src/hex_bytes.rs
Labels: C-test

#410 feat(p2p): refactor downloaders and add peer id to the result
  Cargo.lock
  Cargo.toml
  crates/interfaces/src/p2p/bodies/client.rs
  crates/interfaces/src/p2p/downloader.rs
  crates/interfaces/src/p2p/error.rs
  crates/interfaces/src/p2p/headers/client.rs
  crates/interfaces/src/p2p/headers/downloader.rs
  crates/interfaces/src/p2p/mod.rs
  crates/interfaces/src/p2p/traits.rs
  crates/interfaces/src/test_utils/bodies.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/downloaders/Cargo.toml
  crates/net/downloaders/src/bodies/concurrent.rs
  crates/net/downloaders/src/bodies/mod.rs
  crates/net/downloaders/src/headers/linear.rs
  crates/net/downloaders/src/headers/mod.rs
  crates/net/downloaders/src/lib.rs
  crates/net/downloaders/src/test_utils.rs
  crates/net/headers-downloaders/Cargo.toml
  crates/net/headers-downloaders/src/lib.rs
  crates/net/network/src/fetch/client.rs
  crates/net/network/src/fetch/mod.rs
  crates/net/network/tests/it/requests.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/peer.rs
  crates/stages/Cargo.toml
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/headers.rs
Labels: C-enhancement, A-devp2p

#350 feat(eth-wire): fuzzing wire encoding roundtrip
  .github/workflows/ci.yml
  Cargo.lock
  crates/interfaces/Cargo.toml
  crates/net/eth-wire/Cargo.toml
  crates/net/eth-wire/src/builder.rs
  crates/net/eth-wire/src/capability.rs
  crates/net/eth-wire/src/disconnect.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/hello.rs
  crates/net/eth-wire/src/lib.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/eth-wire/src/types/blocks.rs
  crates/net/eth-wire/src/types/broadcast.rs
  crates/net/eth-wire/src/types/receipts.rs
  crates/net/eth-wire/src/types/state.rs
  crates/net/eth-wire/src/types/transactions.rs
  crates/net/eth-wire/tests/fuzz_roundtrip.rs
  crates/storage/db/Cargo.toml
Labels: C-enhancement, A-networking

#406 fix(sync): commit headers upon threshold
  crates/stages/src/stages/headers.rs
Labels: A-staged-sync

#412 fix(net): improve dropped connection handling
  crates/net/network/src/manager.rs
  crates/net/network/src/message.rs
  crates/net/network/src/peers/manager.rs
Labels: A-networking

#377 fix(db): upgrade to libmdbx 0.12.2;
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/CMakeLists.txt
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/ChangeLog.md
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/README.md
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/VERSION.txt
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/cmake/compiler.cmake
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/cmake/profile.cmake
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/cmake/utils.cmake
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/config.h.in
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_chk.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_copy.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_drop.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_dump.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_load.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_stat.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c++
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h++
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_chk.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_copy.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_drop.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_dump.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_load.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_stat.c
Labels: A-db

#414 fix(disc): also emit discovered node when buckets are full
  crates/net/discv4/src/lib.rs
  crates/net/network/src/discovery.rs
Labels: A-networking

#352 feat(network): add geth connection test
  crates/net/network/tests/it/connect.rs
Labels: C-enhancement, A-networking

#421 feat(net): add NetworkBuilder type
  crates/net/network/src/builder.rs
  crates/net/network/src/eth_requests.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/transactions.rs
Labels: A-networking

#422 fix(sync): test db size map
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: A-staged-sync, C-test

#423 refactor(disc): use discv4 as log target
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/mock.rs
Labels: A-networking

#429 fix(net): use adjust correct counters
  crates/net/network/src/peers/manager.rs
Labels: A-networking

#433 fix(download): stream loop
  crates/net/downloaders/src/headers/linear.rs
Labels: C-bug, A-networking

#431 feat(net): make Status and Hello configurable
  crates/net/eth-wire/src/hello.rs
  crates/net/eth-wire/src/types/status.rs
  crates/net/network/src/config.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/tests/it/connect.rs
Labels: A-networking

#435 chore(net): improve session error traces
  crates/net/network/src/session/active.rs
Labels: A-networking

#438 fix(download): header download stream
  crates/interfaces/src/p2p/error.rs
  crates/interfaces/src/p2p/headers/error.rs
  crates/net/downloaders/src/headers/linear.rs
Labels: C-bug, A-networking

#441 test: fix header dl error test
  crates/stages/src/stages/headers.rs
Labels: A-staged-sync, C-test

#442 feat(net): integrate discovery banlist
  Cargo.lock
  Cargo.toml
  crates/net/common/Cargo.toml
  crates/net/common/src/ban_list.rs
  crates/net/common/src/lib.rs
  crates/net/discv4/Cargo.toml
  crates/net/discv4/src/config.rs
  crates/net/discv4/src/lib.rs
  crates/net/network/Cargo.toml
  crates/net/network/src/discovery.rs
  crates/net/network/src/error.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/peers/mod.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
  crates/net/network/tests/it/connect.rs
Labels: A-networking

#448 fix(cli): remove usage of `StageDB` on `DbTool`
  bin/reth/src/db/mod.rs
  crates/primitives/src/chain.rs
  crates/primitives/src/hex_bytes.rs
  crates/stages/src/stages/bodies.rs
  crates/storage/libmdbx-rs/benches/utils.rs
  crates/storage/libmdbx-rs/tests/transaction.rs
Labels: C-enhancement

#436 feat(net): draft for sending status updates through `NetworkHandle`
  Cargo.lock
  bin/reth/src/node/mod.rs
  crates/interfaces/src/p2p/headers/client.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/network/src/fetch/client.rs
  crates/net/network/src/fetch/mod.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
  crates/stages/Cargo.toml
  crates/stages/src/stages/headers.rs
Labels: C-enhancement, A-networking

#451 fix(net): ban useless peers
  crates/net/network/src/error.rs
Labels: A-networking

#427 feat(sync): download peer penalization
  bin/reth/src/node/mod.rs
  crates/interfaces/src/p2p/bodies/client.rs
  crates/interfaces/src/p2p/bodies/downloader.rs
  crates/interfaces/src/p2p/downloader.rs
  crates/interfaces/src/p2p/error.rs
  crates/interfaces/src/p2p/headers/client.rs
  crates/interfaces/src/p2p/headers/downloader.rs
  crates/interfaces/src/p2p/headers/error.rs
  crates/interfaces/src/p2p/headers/mod.rs
  crates/interfaces/src/test_utils/bodies.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/downloaders/src/bodies/concurrent.rs
  crates/net/downloaders/src/headers/linear.rs
  crates/net/downloaders/src/test_utils.rs
  crates/net/network/src/fetch/client.rs
  crates/net/network/src/fetch/mod.rs
  crates/net/network/src/state.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/headers.rs
Labels: C-enhancement, A-staged-sync

#453 feat: don't stop the pipeline on internal stage errs
  crates/stages/src/error.rs
  crates/stages/src/pipeline.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/senders.rs
Labels: C-enhancement, A-staged-sync

#460 Add MacOS installation docs
  book/README.md
  book/SUMMARY.md
  book/installation.md
  docs/README.md
  docs/installation/README.md
Labels: C-docs

#426 test(execution): execution test runner
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/test_eth_chain/mod.rs
  bin/reth/src/test_eth_chain/models.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/executor/Cargo.toml
  crates/executor/src/config.rs
  crates/executor/src/executor.rs
  crates/executor/src/lib.rs
  crates/interfaces/src/executor.rs
  crates/stages/src/error.rs
  crates/stages/src/lib.rs
  crates/stages/src/stages/execution.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: A-evm, C-test

#450 refactor: clean up `reth node`
  bin/reth/Cargo.toml
  bin/reth/res/chainspec/mainnet.json
  bin/reth/src/node/mod.rs
  bin/reth/src/util/chainspec.rs
  bin/reth/src/util/mod.rs
  crates/net/network/src/peers/manager.rs
  crates/primitives/src/account.rs
  crates/primitives/src/lib.rs
Labels: C-debt, A-cli

#464 feat(net): request peer by id through `PeersHandle`
  crates/net/network/src/peers/manager.rs
Labels: C-enhancement, A-networking

#469 feat: add flag for displaying log target
  bin/reth/src/util/mod.rs
Labels: C-enhancement, A-cli

#470 chore: rename StageDB to Transaction
  bin/reth/src/test_eth_chain/runner.rs
  crates/stages/src/db.rs
  crates/stages/src/lib.rs
  crates/stages/src/pipeline.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/senders.rs
  crates/stages/src/test_utils/mod.rs
  crates/stages/src/test_utils/runner.rs
  crates/stages/src/test_utils/test_db.rs
  docs/design/database.md
Labels: C-debt, A-db

#468 feat: request multiple bodies per request
  crates/net/downloaders/src/bodies/concurrent.rs
Labels: C-enhancement, A-staged-sync

#467 fix(sync): headers stage progress
  crates/interfaces/src/p2p/headers/downloader.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/downloaders/src/headers/linear.rs
  crates/stages/src/error.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/senders.rs
  crates/stages/src/test_utils/macros.rs
Labels: C-bug, A-staged-sync

#473 feat(net): add `Status` to session established event
  crates/net/network/src/manager.rs
  crates/net/network/src/swarm.rs
Labels: A-networking

#475 fix(sync): database integrity header error message
  crates/stages/src/error.rs
Labels: C-bug, A-staged-sync

#478 fix(net): use frontier forkid as default
  crates/net/eth-wire/src/types/status.rs
Labels: A-networking

#476 fix(sync): remove redundant error
  crates/stages/src/db.rs
  crates/stages/src/error.rs
  crates/stages/src/stages/headers.rs
Labels: A-staged-sync

#430 feat(doc): Changeid table design
  docs/design/database.md
Labels: C-docs

#480 chore: use later block
  bin/reth/src/node/mod.rs
Labels: C-enhancement

#481 chore: clean up traces
  crates/stages/src/error.rs
  crates/stages/src/pipeline.rs
  crates/stages/src/stages/headers.rs
Labels: C-enhancement, A-observability

#486 fix: set forkfilter correctly
  crates/net/eth-wire/src/ethstream.rs
  crates/net/network/src/config.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/session/mod.rs
  crates/primitives/src/forkid.rs
  crates/primitives/src/hardfork.rs
Labels: C-bug, A-networking

#487 fix: apply reputation
  crates/net/network/src/peers/manager.rs
Labels: A-networking

#449 feat(sync): state transition indexes
  bin/reth/src/node/mod.rs
  crates/executor/src/executor.rs
  crates/interfaces/src/executor.rs
  crates/interfaces/src/p2p/bodies/client.rs
  crates/interfaces/src/p2p/bodies/downloader.rs
  crates/interfaces/src/provider.rs
  crates/interfaces/src/test_utils/bodies.rs
  crates/net/downloaders/src/bodies/concurrent.rs
  crates/net/downloaders/src/test_utils.rs
  crates/net/network/src/fetch/client.rs
  crates/net/network/tests/it/requests.rs
  crates/primitives/src/header.rs
  crates/primitives/src/lib.rs
  crates/stages/src/db.rs
  crates/stages/src/error.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/senders.rs
  crates/stages/src/test_utils/macros.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/db/src/tables/codecs/fuzz/mod.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/db/src/tables/models/accounts.rs
  crates/storage/db/src/tables/models/blocks.rs
  crates/storage/provider/src/block.rs
  crates/storage/provider/src/db_provider/storage.rs
  crates/storage/provider/src/lib.rs
Labels: C-enhancement, A-staged-sync

#491 feat: add more tables to db list
  bin/reth/src/db/mod.rs
Labels: C-enhancement, A-cli

#492 feat(net): temporarily ban bad peers
  crates/net/common/src/ban_list.rs
  crates/net/network/src/fetch/mod.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/peers/reputation.rs
  crates/net/network/src/state.rs
Labels: C-enhancement, A-networking

#474 feat: add prometheus support
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/cli.rs
  crates/net/eth-wire/Cargo.toml
  crates/net/eth-wire/src/p2pstream.rs
Labels: C-enhancement, A-observability

#499 RLP decoding error tracing
  Cargo.lock
  crates/common/rlp/Cargo.toml
  crates/net/eth-wire/src/ethstream.rs
Labels: C-enhancement, A-devp2p

#504 chore: add codeowners
  CODEOWNERS
Labels: C-enhancement

#505 refactor: move metrics endpoint to node cmd
  bin/reth/src/cli.rs
  bin/reth/src/db/mod.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/util/mod.rs
Labels: C-debt, A-cli

#507 chore(deps): bump ethers
  Cargo.lock
Labels: dependencies

#508 perf(net): increase udp channel buffers
  crates/net/discv4/src/config.rs
  crates/net/discv4/src/lib.rs
Labels: C-perf, A-networking

#510 fix(mdbx): properly convert unknown error codes
  crates/storage/libmdbx-rs/src/error.rs
Labels: C-bug, A-db

#516 test(sync): sender recovery single tx
  crates/interfaces/src/test_utils/generators.rs
  crates/stages/src/stages/senders.rs
Labels: A-staged-sync, C-test

#517 test(download): header downloader request attempts & remove duplicates
  crates/interfaces/src/test_utils/headers.rs
  crates/net/downloaders/src/headers/linear.rs
Labels: C-test, A-networking

#519 feat(net): allow disconnect with reason
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
Labels: C-enhancement, A-networking

#520 fix(net): set disconnect status
  crates/net/eth-wire/src/p2pstream.rs
Labels: C-bug, A-networking

#518 refactor(disc): use KBucekt entry API
  Cargo.lock
  crates/net/discv4/Cargo.toml
  crates/net/discv4/src/config.rs
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/mock.rs
Labels: A-networking

#502 fix(eth-wire): fix disconnect reason rlp decoding
  crates/net/eth-wire/src/disconnect.rs
  crates/net/eth-wire/src/error.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/network/tests/it/connect.rs
Labels: C-bug, A-devp2p

#522 fix(net): poll after starting disconnect
  crates/net/network/src/session/active.rs
Labels: C-bug, A-networking

#523 test: decrease test timeout for keep alive
  crates/net/network/src/session/active.rs
Labels: C-test

#524 chore(sync): remove unused timeout from `LinearDownloadBuilder`
  crates/net/downloaders/src/headers/linear.rs
Labels: A-networking

#525 chore: remove unnecessary step
  .github/workflows/ci.yml
Labels: C-debt, C-test

#514 chore(net): improve ecies error for unreadable stream
  crates/net/ecies/src/error.rs
  crates/net/ecies/src/stream.rs
Labels: A-networking

#527 test: run geth tests in serial
  Cargo.lock
  crates/net/network/Cargo.toml
  crates/net/network/tests/it/connect.rs
Labels: C-test

#496 feat: config
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/res/chainspec/goerli.json
  bin/reth/res/chainspec/mainnet.json
  bin/reth/res/chainspec/sepolia.json
  bin/reth/src/cli.rs
  bin/reth/src/config.rs
  bin/reth/src/db/mod.rs
  bin/reth/src/dirs.rs
  bin/reth/src/lib.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/util/chainspec.rs
  crates/consensus/Cargo.toml
  crates/consensus/src/config.rs
  crates/consensus/src/consensus.rs
  crates/consensus/src/lib.rs
  crates/consensus/src/verification.rs
  crates/net/network/src/config.rs
  crates/stages/src/stages/headers.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/transaction-pool/src/config.rs
Labels: C-enhancement, A-cli

#479 fix(net): fix disconnect edge case on remove from discovery
  crates/net/network/src/manager.rs
  crates/net/network/src/peers/manager.rs
Labels: C-bug, A-networking

#529 feat(eth-wire): add timeouts to tests using Geth
  crates/net/network/tests/it/connect.rs
Labels: C-test, A-networking

#530 feat(net): use NodeRecord instead of enode format
  crates/net/discv4/src/node.rs
  crates/net/network/tests/it/connect.rs
Labels: C-test, A-networking

#533 feat(net): create enr to peerid helper
  Cargo.lock
  crates/net/network/Cargo.toml
  crates/net/network/tests/it/connect.rs
Labels: A-utils, A-networking

#532 test: create event stream before interacting with network mngr
  crates/net/network/tests/it/connect.rs
Labels: C-test, A-networking

#534 test: fix `emits_bodies_in_order` test
  bin/reth/src/db/mod.rs
  crates/interfaces/src/test_utils/generators.rs
  crates/net/downloaders/src/bodies/concurrent.rs
  crates/net/downloaders/src/test_utils.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/senders.rs
Labels: C-bug, C-test

#515 chore(db): modify state transition docs
  crates/storage/db/src/tables/mod.rs
  docs/design/database.md
Labels: C-docs, A-db

#455 meta(sync): tracing
  Cargo.lock
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/senders.rs
  crates/storage/db/src/tables/models/blocks.rs
Labels: C-enhancement, A-staged-sync, A-observability

#536 chore(deps): remove discv5 fork dep
  Cargo.lock
  crates/net/discv4/Cargo.toml
Labels: dependencies

#535 feat(eth-wire): RLP encode then compress
  Cargo.lock
  crates/net/eth-wire/Cargo.toml
  crates/net/eth-wire/src/disconnect.rs
  crates/net/eth-wire/src/hello.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/network/src/session/active.rs
Labels: A-networking

#539 chore(disc): unify duration settings and naming
  crates/net/discv4/src/config.rs
  crates/net/discv4/src/lib.rs
Labels: C-debt, A-networking

#540 chore: rm some clippy lints
  crates/primitives/src/forkid.rs
Labels: C-debt

#538 test(net): add e2e test for already connected
  crates/net/network/src/manager.rs
  crates/net/network/src/transactions.rs
  crates/net/network/tests/it/connect.rs
  crates/net/network/tests/it/testnet.rs
Labels: C-test, A-networking

#537 perf(net): put timeout check behind interval
  crates/net/network/src/session/active.rs
Labels: C-perf, A-networking

#543 fix(net): ban peer on fatal error
  crates/net/network/src/error.rs
  crates/net/network/src/peers/manager.rs
Labels: C-bug, A-networking

#541 feat(cli): add implementation for verbose flag
  bin/reth/src/cli.rs
  bin/reth/src/util/mod.rs
Labels: C-enhancement, A-cli

#545 feat(eth-wire): enforce test-fuzz traits pre-fuzz
  crates/net/eth-wire/tests/fuzz_roundtrip.rs
Labels: C-test, A-networking

#544 ci: speed up fuzz tests
  .github/scripts/fuzz.sh
  .github/workflows/ci.yml
Labels: C-test

#548 fix(net): temporarily backoff busy peers
  crates/net/network/src/error.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/peers/reputation.rs
Labels: C-perf, A-networking

#553 chore(deps): bump rustversion
  Cargo.lock
Labels: dependencies

#555 fix(net): encode ping pong as snappy
  crates/net/eth-wire/src/p2pstream.rs
Labels: C-bug, A-networking

#554 chore(sync): rename senders stage
  bin/reth/src/config.rs
  bin/reth/src/node/mod.rs
  book/stages/README.md
  crates/stages/src/stages/mod.rs
  crates/stages/src/stages/sender_recovery.rs
Labels: A-staged-sync, C-debt

#558 fix(net): add capacity check on ping
  crates/net/eth-wire/src/p2pstream.rs
Labels: A-networking

#557 chore(net): add more active session traces
  crates/net/network/src/session/active.rs
Labels: C-enhancement, A-networking

#556 fix(consensus): block reward check
  crates/consensus/src/consensus.rs
Labels: C-bug, A-consensus

#561 feat(rpc): add some bindings for admin namespace
  crates/net/rpc-api/src/admin.rs
  crates/net/rpc-api/src/lib.rs
Labels: C-enhancement, A-rpc

#563 chore(primitives): Update keccak256 implementation
  crates/primitives/src/header.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/util.rs
Labels: C-enhancement, C-debt

#576 chore(docs): update engine api links
  README.md
  crates/net/rpc-api/src/engine.rs
  crates/net/rpc-types/src/eth/engine.rs
Labels: C-docs, A-rpc

#572 refactor: rename `EthConsensus`
  bin/reth/src/node/mod.rs
  crates/consensus/src/consensus.rs
  crates/consensus/src/lib.rs
Labels: C-debt

#551 feat(rpc): basic engine api
  Cargo.lock
  crates/consensus/Cargo.toml
  crates/consensus/src/engine/error.rs
  crates/consensus/src/engine/mod.rs
  crates/consensus/src/lib.rs
  crates/consensus/src/verification.rs
  crates/net/network/tests/it/testnet.rs
  crates/net/rpc-types/Cargo.toml
  crates/net/rpc-types/src/eth/engine.rs
  crates/net/rpc/Cargo.toml
  crates/net/rpc/src/engine/mod.rs
  crates/net/rpc/src/eth/api/mod.rs
  crates/net/rpc/src/eth/api/server.rs
  crates/net/rpc/src/lib.rs
  crates/storage/provider/src/block.rs
  crates/storage/provider/src/db_provider/block.rs
  crates/storage/provider/src/test_utils/api.rs
Labels: C-enhancement, A-rpc

#573 chore: Rename BlockLocked to SealedBlock
  bin/reth/src/test_eth_chain/runner.rs
  book/stages/README.md
  crates/consensus/src/consensus.rs
  crates/consensus/src/verification.rs
  crates/executor/src/executor.rs
  crates/interfaces/src/consensus.rs
  crates/interfaces/src/p2p/bodies/downloader.rs
  crates/interfaces/src/test_utils/generators.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/downloaders/src/bodies/concurrent.rs
  crates/primitives/src/block.rs
  crates/primitives/src/lib.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/storage/provider/src/block.rs
Labels: C-debt

#568 Update the document by adding information on how to install Geth and Lighthouse.
  README.md
  book/installation.md
Labels: C-docs

#498 feat: add stagedsync headers metrics
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/lib.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/prometheus_exporter.rs
  crates/stages/src/lib.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages_metrics.rs
  crates/stages/src/stages_metrics_describer.rs
  docs/design/metrics.md
Labels: C-enhancement, A-staged-sync

#582 docs(txpool): clarify validate_transaction
  crates/transaction-pool/src/validate.rs
Labels: C-docs, A-tx-pool

#585 feat(net): increase session command buffer
  crates/net/network/src/session/config.rs
  crates/net/network/src/session/mod.rs
Labels: C-perf, A-networking

#586 feat(net): validate discovered enr forkid
  crates/net/network/src/session/mod.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
Labels: C-enhancement, A-networking

#588 ci: add sanity check workflow
  .github/SANITY_DEPS_ISSUE_TEMPLATE.md
  .github/workflows/sanity.yml
Labels: C-enhancement, C-test

#591 chore(deps): bump ethers
  Cargo.lock
  crates/primitives/src/chain.rs
Labels: A-dependencies

#590 ci: unused dependencies sanity check
  .github/SANITY_UNUSED_DEPS_ISSUE_TEMPLATE.md
  .github/workflows/sanity.yml
  Cargo.lock
  bin/reth/Cargo.toml
  crates/common/rlp-derive/Cargo.toml
  crates/common/rlp/Cargo.toml
  crates/consensus/Cargo.toml
  crates/executor/Cargo.toml
  crates/interfaces/Cargo.toml
  crates/net/network/Cargo.toml
  crates/primitives/Cargo.toml
  crates/stages/Cargo.toml
  crates/storage/codecs/derive/Cargo.toml
  crates/storage/db/Cargo.toml
  crates/transaction-pool/Cargo.toml
Labels: C-enhancement, C-test

#593 fix: set stage progress metric to absolute value
  crates/stages/src/id.rs
Labels: C-bug, A-observability

#472 test(execution): chain test state check, execution bug fixes/upgrades
  Cargo.lock
  bin/reth/src/test_eth_chain/models.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/executor/Cargo.toml
  crates/executor/src/executor.rs
  crates/executor/src/revm_wrap.rs
  crates/primitives/src/proofs.rs
  crates/primitives/src/receipt.rs
  crates/stages/src/db.rs
  crates/stages/src/stages/execution.rs
  crates/storage/db/src/abstraction/cursor.rs
  crates/storage/db/src/abstraction/mock.rs
  crates/storage/db/src/implementation/mdbx/cursor.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/provider/src/db_provider/storage.rs
Labels: C-test

#595 refactor(net): unify dropped session handling
  Cargo.lock
  crates/net/network/Cargo.toml
  crates/net/network/src/error.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/session/mod.rs
Labels: C-debt, A-networking

#596 fix(net): check for handshake disconnect
  crates/net/eth-wire/src/error.rs
  crates/net/network/src/error.rs
  crates/net/network/src/peers/manager.rs
Labels: C-bug, A-networking

#574 feat: Add PeerEvent to NetworkEvent enum
  crates/net/network/src/manager.rs
  crates/net/network/src/transactions.rs
  crates/net/network/tests/it/connect.rs
  crates/net/network/tests/it/testnet.rs
Labels: C-enhancement, A-networking

#600 refactor(net): unify closed incoming session handling
  crates/net/common/src/ban_list.rs
  crates/net/network/src/error.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
Labels: C-debt, A-networking

#594 fix(db): Dont compress DupSort SubKey
  bin/reth/src/node/mod.rs
  crates/primitives/src/storage.rs
  crates/stages/src/stages/execution.rs
  crates/storage/db/src/tables/models/accounts.rs
Labels: C-bug, A-db

#602 feat(net): Make PeerManager emit peerevents for admin rpc
  crates/net/network/src/manager.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
  crates/net/network/tests/it/connect.rs
Labels: C-enhancement, A-networking

#605 feat(net): add nat external ip crate
  Cargo.lock
  Cargo.toml
  crates/net/nat/Cargo.toml
  crates/net/nat/src/lib.rs
Labels: C-enhancement, A-networking

#606 fix: do not lowercase table arg in `db list`
  bin/reth/src/db/mod.rs
Labels: C-bug, A-cli

#610 fix(net): add no response to backoff check
  crates/net/network/src/error.rs
Labels: C-bug, A-networking

#613 test(net): add test for dropped pending no response
  crates/net/network/src/error.rs
  crates/net/network/src/peers/manager.rs
Labels: C-test, A-networking

#614 refactor(net): rename and restructure wire error types
  crates/net/eth-wire/src/errors/eth.rs
  crates/net/eth-wire/src/errors/mod.rs
  crates/net/eth-wire/src/errors/p2p.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/lib.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/eth-wire/src/pinger.rs
  crates/net/network/src/error.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/handle.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/swarm.rs
Labels: C-debt, A-networking

#444 docs(book): `db` chapter.
  book/db/README.md
Labels: C-docs

#618 perf: allocate responses capacity
  crates/net/downloaders/src/bodies/concurrent.rs
Labels: C-debt, C-perf

#621 ci: add eth chain test. Set prevrandao after merge
  .github/workflows/ci.yml
  bin/reth/src/test_eth_chain/mod.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/executor/src/config.rs
  crates/executor/src/executor.rs
  crates/executor/src/revm_wrap.rs
Labels: A-execution, C-test

#592 feat(metrics): `Metrics` derive macro
  Cargo.lock
  Cargo.toml
  bin/reth/src/node/mod.rs
  crates/metrics/metrics-derive/Cargo.toml
  crates/metrics/metrics-derive/src/expand.rs
  crates/metrics/metrics-derive/src/lib.rs
  crates/metrics/metrics-derive/src/metric.rs
  crates/metrics/metrics-derive/src/with_attrs.rs
  crates/metrics/metrics-derive/tests/compile-fail/metric_attr.rs
  crates/metrics/metrics-derive/tests/compile-fail/metric_attr.stderr
  crates/metrics/metrics-derive/tests/compile-fail/metrics_attr.rs
  crates/metrics/metrics-derive/tests/compile-fail/metrics_attr.stderr
  crates/metrics/metrics-derive/tests/compile-fail/metrics_scope.rs
  crates/metrics/metrics-derive/tests/compile-fail/metrics_scope.stderr
  crates/metrics/metrics-derive/tests/metrics.rs
  crates/metrics/metrics-derive/tests/trybuild.rs
  crates/stages/Cargo.toml
  crates/stages/src/lib.rs
  crates/stages/src/metrics.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages_metrics.rs
  crates/stages/src/stages_metrics_describer.rs
Labels: C-enhancement, A-observability

#619 refactor(net): deduplicate error variants
  crates/net/eth-wire/src/errors/eth.rs
Labels: C-debt, A-networking

#625 fix(metrics): metrics derive separator
  Cargo.lock
  crates/metrics/metrics-derive/Cargo.toml
  crates/metrics/metrics-derive/src/expand.rs
  crates/metrics/metrics-derive/src/lib.rs
  crates/metrics/metrics-derive/src/metric.rs
  crates/metrics/metrics-derive/tests/compile-fail/metric_attr.rs
  crates/metrics/metrics-derive/tests/compile-fail/metric_attr.stderr
  crates/metrics/metrics-derive/tests/compile-fail/metrics_attr.rs
  crates/metrics/metrics-derive/tests/compile-fail/metrics_attr.stderr
  crates/metrics/metrics-derive/tests/compile-fail/metrics_scope.rs
  crates/metrics/metrics-derive/tests/compile-fail/metrics_scope.stderr
  crates/metrics/metrics-derive/tests/metrics.rs
  crates/stages/src/id.rs
  crates/stages/src/lib.rs
  crates/stages/src/metrics.rs
  docs/design/metrics.md
Labels: C-bug, A-observability

#626 docs: fix indentation
  crates/transaction-pool/src/validate.rs
Labels: C-docs

#584 feat: add txpool metrics
  Cargo.lock
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/metrics.rs
  crates/transaction-pool/src/pool/txpool.rs
  docs/design/metrics.md
Labels: C-enhancement, A-observability

#617 Add serde support for NodeRecord primitive type
  Cargo.lock
  crates/net/discv4/Cargo.toml
  crates/net/discv4/src/bootnodes.rs
  crates/net/discv4/src/config.rs
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/mock.rs
  crates/net/discv4/src/node.rs
  crates/net/discv4/src/proto.rs
  crates/net/network/src/config.rs
  crates/net/network/src/discovery.rs
  crates/net/network/tests/it/connect.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/lib.rs
  crates/primitives/src/net.rs
Labels: C-debt, A-networking

#445 docs(book): start book chapter for `network` crate
  bin/reth/src/node/mod.rs
  book/SUMMARY.md
  book/networking/network.md
  book/networking/p2p/README.md
  book/networking/p2p/network/README.md
  crates/net/downloaders/src/bodies/concurrent.rs
  crates/net/downloaders/src/headers/linear.rs
  crates/net/eth-wire/src/types/blocks.rs
  crates/net/network/src/config.rs
  crates/net/network/src/eth_requests.rs
  crates/net/network/src/fetch/client.rs
  crates/net/network/src/fetch/mod.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
  crates/net/network/src/transactions.rs
  crates/transaction-pool/src/pool/mod.rs
Labels: C-docs

#629 Moves code walkthrough book chapters to `docs`
  bin/reth/src/node/mod.rs
  book/README.md
  book/SUMMARY.md
  book/networking/network.md
  book/networking/p2p/README.md
  book/networking/p2p/network/README.md
  crates/interfaces/src/p2p/headers/downloader.rs
  crates/net/downloaders/src/bodies/concurrent.rs
  crates/net/downloaders/src/headers/linear.rs
  crates/net/eth-wire/src/types/blocks.rs
  crates/net/network/src/config.rs
  crates/net/network/src/eth_requests.rs
  crates/net/network/src/fetch/client.rs
  crates/net/network/src/fetch/mod.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
  crates/net/network/src/transactions.rs
  crates/primitives/src/block.rs
  crates/primitives/src/header.rs
  crates/primitives/src/transaction/signature.rs
  crates/stages/src/pipeline.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/execution.rs
  docs/design/goals.md
  docs/repo/crates/db.md
  docs/repo/crates/network.md
  docs/repo/crates/stages.md
Labels: C-docs

#633 perf(net): backoff on IO error
  crates/net/eth-wire/src/errors/eth.rs
  crates/net/network/src/error.rs
Labels: C-perf, A-networking

#635 feat(rpc): add rpc builder support
  Cargo.lock
  Cargo.toml
  crates/net/ipc/src/server/mod.rs
  crates/net/rpc-builder/Cargo.toml
  crates/net/rpc-builder/src/config.rs
  crates/net/rpc-builder/src/lib.rs
Labels: C-enhancement, A-rpc

#632 feat(net): integrate external public ip auto discovery
  Cargo.lock
  crates/net/discv4/Cargo.toml
  crates/net/discv4/src/config.rs
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/mock.rs
  crates/net/nat/Cargo.toml
  crates/net/nat/src/lib.rs
Labels: C-enhancement, A-networking

#630 docs: add outgoing request diagram
  crates/net/network/src/fetch/client.rs
Labels: C-docs

#609 fix(sync): return control from `HeaderStage` back to pipeline
  crates/stages/src/stages/headers.rs
Labels: A-staged-sync
