Repository paradigmxyz/reth, pull requests merged in 2023-01, with the labels that each got.

#660 feat(net): enforce trusted_nodes_only setting
  crates/net/network/src/peers/manager.rs
Labels: C-enhancement, A-networking

#668 feat: raise fd limit of the binary
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/node/mod.rs
Labels: C-enhancement, A-cli

#670 docs(net): update best_unconnected docs
  crates/net/network/src/peers/manager.rs
Labels: C-docs, A-networking

#666 Reth book for user
  book/README.md
  book/SUMMARY.md
  book/faq/README.md
  book/fundamentals/command-line_options.md
  book/fundamentals/logs.md
  book/fundamentals/node.md
  book/getting_started/installation.md
  book/getting_started/introduction.md
  book/getting_started/system_requirements.md
  book/monitoring/matrics.md
Labels: C-docs

#653 chore: add serde feature to network crate
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/config.rs
  crates/net/network/Cargo.toml
  crates/net/network/src/lib.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/peers/reputation.rs
Labels: C-enhancement, A-networking

#673 feat(net): add eth66 to default caps
  crates/net/eth-wire/src/hello.rs
Labels: C-enhancement, A-networking

#665 feat(sync): total difficulty stage
  bin/reth/src/config.rs
  bin/reth/src/node/mod.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/mod.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/test_utils/test_db.rs
Labels: C-enhancement, A-staged-sync

#677 Change terminal_block_number type to U64
  crates/consensus/src/engine/mod.rs
  crates/net/rpc-types/src/eth/engine.rs
Labels: C-bug, A-rpc

#678 Add admin_(add|remove)TrustedPeer on admin rpc
  crates/net/rpc-api/src/admin.rs
Labels: C-enhancement, A-rpc

#682 style: rm redundant Pipeline::new
  bin/reth/src/node/mod.rs
  crates/stages/src/pipeline.rs
Labels: C-debt

#687 feat: test trusted peers functionality
  crates/net/network/src/peers/manager.rs
Labels: C-test, A-networking

#691 feat(download): body downloader tracing
  crates/net/downloaders/src/bodies/concurrent.rs
  crates/net/downloaders/src/headers/linear.rs
Labels: C-enhancement, A-observability, A-networking

#693 feat: add SyncState traits
  crates/interfaces/src/lib.rs
  crates/interfaces/src/sync.rs
  crates/net/network/src/network.rs
Labels: C-enhancement, A-staged-sync, A-networking

#685 RPC Admin namespace implementation
  crates/net/network/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/peers/mod.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
  crates/net/rpc-api/src/admin.rs
  crates/net/rpc-api/src/lib.rs
  crates/net/rpc/src/admin/mod.rs
  crates/net/rpc/src/lib.rs
Labels: C-enhancement, A-rpc, A-networking

#694 chore: move metrics dep to dev-dep
  crates/metrics/metrics-derive/Cargo.toml
  crates/metrics/metrics-derive/tests/metrics.rs
Labels: A-dependencies

#695 fix: bump request timeout
  crates/net/network/src/session/config.rs
Labels: C-perf, A-networking

#696 feat(disc): add set_lookup_interval function
  crates/net/discv4/src/lib.rs
Labels: C-enhancement, A-networking

#699 test: test server ack decoding
  crates/net/ecies/src/algorithm.rs
Labels: C-test, A-networking

#700 test(chain): add shanghai forkspec
  bin/reth/src/test_eth_chain/models.rs
  bin/reth/src/test_eth_chain/runner.rs
Labels: C-test

#697 feat(sync): update sync state within pipeline
  bin/reth/src/node/mod.rs
  crates/stages/src/id.rs
  crates/stages/src/pipeline.rs
  crates/stages/src/pipeline/ctrl.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/headers.rs
Labels: C-enhancement, A-staged-sync

#705 feat(net): ignore transactions during sync
  crates/net/network/src/transactions.rs
Labels: C-enhancement, A-networking

#712 feat(net): penalize peers that send same transactions
  crates/net/network/src/transactions.rs
Labels: C-perf, A-networking

#715 trace(download): failed requests
  bin/reth/src/config.rs
  crates/net/downloaders/src/bodies/concurrent.rs
  crates/net/downloaders/src/headers/linear.rs
Labels: A-observability, A-networking

#681 feat(sync): standardize stage control flow checks
  bin/reth/src/config.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
Labels: C-enhancement, A-staged-sync

#718 feat(download): dynamically adjust body request
  crates/net/downloaders/src/bodies/concurrent.rs
Labels: C-enhancement, A-networking

#698 feat(cli): p2p header & body download
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/cli.rs
  bin/reth/src/lib.rs
  bin/reth/src/main.rs
  bin/reth/src/p2p/mod.rs
  bin/reth/src/util/mod.rs
Labels: C-enhancement, A-cli

#720 ci: add project workflow
  .github/workflows/project.yml
Labels: C-enhancement

#723 feat: Stage Tool Execution Stage
  bin/reth/src/cli.rs
  bin/reth/src/stage/mod.rs
Labels: C-enhancement, A-staged-sync

#729 feat(net): add granular backoff durations
  crates/net/network/src/error.rs
  crates/net/network/src/peers/manager.rs
Labels: C-enhancement, A-networking

#731 fix(disc): mark node as queried before ping
  crates/net/discv4/src/lib.rs
Labels: C-bug, A-networking

#735 ci: don't add PRs to project
  .github/workflows/project.yml
Labels: C-enhancement

#734 chore(deps): rm unused tracing dep
  crates/common/rlp/Cargo.toml
Labels: C-debt, A-dependencies

#733 perf(disc): only initiate another auto lookup when previous finished
  crates/net/discv4/src/lib.rs
Labels: C-perf, A-networking

#737 refactor(discv4): use event buffer
  Cargo.lock
  crates/net/discv4/src/lib.rs
Labels: C-debt, C-perf, A-networking

#739 fix: apply correct reputation dmg on bad msg
  crates/net/network/src/manager.rs
Labels: C-bug, A-networking

#738 refactor: clean up `StateFetcher::next_peer`
  crates/net/network/src/fetch/mod.rs
Labels: C-debt, A-networking

#742 fix(disc): use lookup target for distance
  crates/net/discv4/src/lib.rs
Labels: C-bug, C-perf, A-networking

#748 feat(disc): add another self entry check
  crates/net/discv4/src/lib.rs
Labels: C-enhancement, A-networking

#749 Fix: typos
  docs/repo/crates/network.md
Labels: C-docs

#750 log(sync): unwind tracing
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
Labels: C-enhancement, A-staged-sync, A-observability

#753 fix(disc): use remote addr for NodeRecord on ping
  crates/net/discv4/src/lib.rs
Labels: C-bug, A-networking

#754 fix(disc): convert mapped ip address
  crates/net/discv4/src/lib.rs
Labels: C-bug, A-networking

#707 feat(net): Bandwidth monitoring
  Cargo.lock
  crates/net/common/Cargo.toml
  crates/net/common/src/bandwidth_meter.rs
  crates/net/common/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/handle.rs
  crates/net/network/src/session/mod.rs
Labels: C-enhancement, A-observability, A-networking

#757 feat(cli): add more convenient SocketAddr argument parsing
  bin/reth/src/node/mod.rs
  bin/reth/src/util/mod.rs
Labels: A-cli

#760 chore(deps): remove unused ether-core
  Cargo.lock
  crates/storage/codecs/Cargo.toml
Labels: C-debt, A-dependencies

#761 fix(net): use mapped v4 when inserting records
  crates/net/discv4/src/lib.rs
  crates/primitives/src/net.rs
Labels: C-bug, A-networking

#765 feat: misc config files
  docs/design/metrics.md
  etc/README.md
  etc/grafana/overview.json
  etc/prometheus/prometheus.yml
Labels: C-docs, C-enhancement, A-observability

#766 docs: add release checklist
  CONTRIBUTING.md
  docs/README.md
  docs/release.md
Labels: C-docs

#732 chore: add missing match arms in mdbx Error::to_err_code
  crates/storage/libmdbx-rs/src/error.rs
Labels: C-bug, A-db

#767 eth/api: fix typo "the"
  crates/net/rpc/src/eth/api/server.rs
Labels: C-docs

#769 feat(net) Add TransactionsManager Metrics
  crates/net/network/src/metrics.rs
  crates/net/network/src/transactions.rs
  docs/design/metrics.md
Labels: C-enhancement, A-observability, A-networking

#773 fix: Fix typos
  bin/reth/src/test_eth_chain/models.rs
  crates/consensus/src/verification.rs
  crates/executor/src/executor.rs
  crates/interfaces/src/consensus.rs
  crates/interfaces/src/db.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/metrics/metrics-derive/src/lib.rs
  crates/metrics/metrics-derive/tests/metrics.rs
  crates/net/common/Cargo.toml
  crates/net/ecies/src/error.rs
  crates/net/eth-wire/Cargo.toml
  crates/net/network/src/fetch/mod.rs
  crates/net/network/src/network.rs
  crates/net/network/src/session/config.rs
  crates/net/rpc-types/src/eth/transaction/mod.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/test_utils/runner.rs
  crates/storage/db/src/abstraction/mod.rs
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/GNUmakefile
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c++
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h++
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_chk.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_copy.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_drop.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_dump.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_load.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_stat.c
  crates/tasks/Cargo.toml
  crates/transaction-pool/src/pool/txpool.rs
  deny.toml
Labels: C-docs

#774 test: add unknown fork spec to blockchain test
  bin/reth/src/test_eth_chain/models.rs
  bin/reth/src/test_eth_chain/runner.rs
Labels: C-enhancement, C-test

#777 refactor: clean up `SocketAddr` value parser
  bin/reth/src/node/mod.rs
  bin/reth/src/util/mod.rs
Labels: C-debt, A-cli

#778 chore(deps): bump tokio 1.24
  Cargo.lock
Labels: A-dependencies

#768 feat(dns): add dns discovery service
  Cargo.lock
  Cargo.toml
  crates/net/dns/Cargo.toml
  crates/net/dns/src/config.rs
  crates/net/dns/src/lib.rs
  crates/net/dns/src/resolver.rs
  crates/net/dns/src/sync.rs
  crates/net/dns/src/tree.rs
Labels: C-enhancement, A-networking

#780 feat(txpool): add gas limit check when inserting new transactions
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/validate.rs
Labels: C-enhancement, A-tx-pool

#790 refactor: move cli utils to new `reth-cli-utils` crate
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  bin/reth/src/cli.rs
  bin/reth/src/dirs.rs
  bin/reth/src/lib.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/p2p/mod.rs
  bin/reth/src/stage/mod.rs
  bin/reth/src/test_eth_chain/mod.rs
  crates/cli/utils/Cargo.toml
  crates/cli/utils/src/chainspec.rs
  crates/cli/utils/src/init.rs
  crates/cli/utils/src/lib.rs
Labels: C-debt, A-cli

#793 fix(execution): Increase cache scope, and apply block reward to cache
  Cargo.lock
  crates/common/rlp/Cargo.toml
  crates/consensus/src/engine/mod.rs
  crates/executor/Cargo.toml
  crates/executor/src/executor.rs
  crates/metrics/metrics-derive/Cargo.toml
  crates/net/downloaders/Cargo.toml
  crates/primitives/Cargo.toml
  crates/stages/src/stages/execution.rs
  crates/storage/codecs/Cargo.toml
Labels: C-bug, A-execution

#787 refactor: rename cursor functions
  bin/reth/src/db/mod.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/cli/utils/src/init.rs
  crates/stages/src/db.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/db/src/abstraction/mock.rs
  crates/storage/db/src/abstraction/transaction.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/provider/src/db_provider/storage.rs
  docs/repo/crates/db.md
Labels: C-debt, A-db

#798 fix(net): handle outgoing connection error correctly
  Cargo.lock
  crates/net/network/src/error.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/peers/manager.rs
Labels: C-bug, A-networking

#803 chore(codecs): add `proptest` roundtrip to all `main_codec`
  Cargo.lock
  crates/cli/utils/src/lib.rs
  crates/executor/src/executor.rs
  crates/executor/src/revm_wrap.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/bloom.rs
  crates/primitives/src/log.rs
  crates/primitives/src/proofs.rs
  crates/primitives/src/receipt.rs
  crates/primitives/src/transaction/tx_type.rs
  crates/storage/codecs/Cargo.toml
  crates/storage/codecs/derive/src/lib.rs
  crates/storage/db/Cargo.toml
Labels: C-test

#795 Point at the book for run instructions
  README.md
Labels: C-docs

#784 feat(cli): more reasonable log output
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/cli.rs
  bin/reth/src/db/mod.rs
  bin/reth/src/dirs.rs
  bin/reth/src/lib.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/p2p/mod.rs
  bin/reth/src/stage/mod.rs
  bin/reth/src/test_eth_chain/mod.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/cli/utils/Cargo.toml
  crates/cli/utils/src/lib.rs
Labels: C-enhancement, C-debt, A-cli

#811 fix: make config serialize as toml
  Cargo.lock
  bin/reth/src/config.rs
  bin/reth/src/node/mod.rs
  crates/net/network/Cargo.toml
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/peers/reputation.rs
Labels: C-bug, A-cli

#814 fix: allow partial configs
  bin/reth/src/config.rs
Labels: C-bug, A-cli

#821 fix: remove outdated & extra `release.md`
  docs/repo/README.md
  docs/repo/release.md
Labels: C-docs

#820 refactor: move cli trace helpers to `reth-tracing`
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/cli.rs
  crates/cli/utils/Cargo.toml
  crates/cli/utils/src/lib.rs
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/test_utils.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/nat/src/lib.rs
  crates/net/network/src/transactions.rs
  crates/net/network/tests/it/connect.rs
  crates/net/network/tests/it/requests.rs
  crates/tracing/Cargo.toml
  crates/tracing/src/lib.rs
Labels: C-debt, A-cli

#823 Downloaders: remove backoff logic
  crates/net/downloaders/src/bodies/concurrent.rs
Labels: A-staged-sync, C-debt

#824 mx - readme.md fix - fix broken image with reth repo official banner
  book/README.md
Labels: C-bug, C-docs

#825 chore: docker improvements
  .dockerignore
  Dockerfile
Labels: C-enhancement

#789 feat(net): adaptable request timeouts
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/config.rs
Labels: C-enhancement, A-networking

#794 feat(disc): add DnsDiscovery service
  Cargo.lock
  crates/net/dns/Cargo.toml
  crates/net/dns/src/config.rs
  crates/net/dns/src/error.rs
  crates/net/dns/src/lib.rs
  crates/net/dns/src/query.rs
  crates/net/dns/src/resolver.rs
  crates/net/dns/src/sync.rs
  crates/net/dns/src/tree.rs
  crates/primitives/src/chain.rs
Labels: C-enhancement, A-networking

#833 chore: Enable arbitrary in db tests
  crates/storage/codecs/Cargo.toml
  crates/storage/db/Cargo.toml
Labels: C-test

#834 feat(nat): add None Natresolver
  Cargo.lock
  crates/net/nat/Cargo.toml
  crates/net/nat/src/lib.rs
Labels: C-enhancement, A-networking

#836 feat: Add neighbours_max_ipv4 test
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/proto.rs
Labels: C-test, A-discv4

#822 feat(doc): Bootstrap MacOS runbook
  book/SUMMARY.md
  book/getting_started/running.md
Labels: C-docs

#838 refactor: add network-api crate
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  bin/reth/src/node/mod.rs
  crates/net/network-api/Cargo.toml
  crates/net/network-api/src/lib.rs
  crates/net/network/Cargo.toml
  crates/net/network/src/eth_requests.rs
  crates/net/network/src/network.rs
  crates/net/network/tests/it/connect.rs
  crates/net/network/tests/it/requests.rs
Labels: C-debt

#832 feat: integrate DNS discovery service
  Cargo.lock
  crates/net/dns/Cargo.toml
  crates/net/dns/src/config.rs
  crates/net/dns/src/lib.rs
  crates/net/dns/src/resolver.rs
  crates/net/network/Cargo.toml
  crates/net/network/src/config.rs
  crates/net/network/src/discovery.rs
  crates/net/network/src/error.rs
  crates/net/network/src/manager.rs
Labels: C-enhancement, A-networking, A-dnsdisc

#831 feat: add shutdown signal to TaskManager
  crates/tasks/Cargo.toml
  crates/tasks/src/lib.rs
  crates/tasks/src/shutdown.rs
Labels: C-enhancement

#846 fix: clippy warnings, or_fun_call and unnecessary_lazy_evaluations
  bin/reth/src/node/mod.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/interfaces/src/test_utils/generators.rs
  crates/metrics/metrics-derive/src/expand.rs
  crates/net/ecies/src/stream.rs
  crates/net/eth-wire/src/disconnect.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/primitives/src/hardfork.rs
Labels: C-debt

#861 chore(deps): bump ethers
  Cargo.lock
Labels: C-debt, A-dependencies

#862 chore: convert warn,err to debug
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/p2pstream.rs
Labels: A-networking, A-cli

#860 feat(net): introduce PeersInfo trait
  Cargo.lock
  crates/net/network-api/src/lib.rs
  crates/net/network/src/network.rs
  crates/net/network/tests/it/connect.rs
  crates/net/rpc/Cargo.toml
  crates/net/rpc/src/net/mod.rs
Labels: C-enhancement, A-networking

#804 feat: add `PoolTransaction` struct
  crates/transaction-pool/src/traits.rs
Labels: C-enhancement, A-tx-pool

#840 docs: use nightly clippy in vscode
  CONTRIBUTING.md
Labels: C-docs

#863 feat: include optional ForkId in Discovery
  crates/net/network/src/discovery.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/state.rs
Labels: C-enhancement, A-discv4

#865 test: rm multi_thread flavor for tests
  crates/net/discv4/Cargo.toml
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/test_utils.rs
Labels: C-debt, C-test

#868 feat: improve eth test runner
  .github/workflows/ci.yml
  bin/reth/src/cli.rs
  bin/reth/src/test_eth_chain/mod.rs
  bin/reth/src/test_eth_chain/models.rs
  bin/reth/src/test_eth_chain/runner.rs
Labels: C-debt, C-test

#872 feat: show possible values for `reth stage`
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/stage/mod.rs
Labels: C-enhancement, A-cli

#870 fix: use correct boolean conversion for direction
  crates/net/downloaders/src/headers/linear.rs
  crates/net/eth-wire/src/types/blocks.rs
  crates/net/eth-wire/src/types/message.rs
  crates/net/network/tests/it/connect.rs
  crates/net/network/tests/it/requests.rs
  crates/primitives/src/header.rs
Labels: C-bug, A-networking

#875 `net`: Add way to get the `NodeRecord` of the local node
  Cargo.lock
  crates/net/network-api/Cargo.toml
  crates/net/network-api/src/lib.rs
  crates/net/network/src/network.rs
Labels: C-enhancement, A-networking

#835 feat(net): prioritize requesting peers with low latency
  crates/net/network/src/fetch/mod.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
Labels: C-enhancement, A-networking

#871 fix: validate fork_id before adding peer from discovery
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
Labels: C-bug, A-networking, A-discv4

#883 test(sync): add test with partial run of total difficulty stage
  crates/stages/src/stages/total_difficulty.rs
Labels: A-staged-sync, C-test

#818 docs: create eth-wire chapter
  docs/repo/crates/eth-wire.md
Labels: C-docs

#843 test: add test for header stage two step download
  crates/interfaces/src/test_utils/headers.rs
  crates/stages/src/stages/headers.rs
Labels: C-test, A-networking

#884 feat: Add DAOFORK irregular state change
  crates/consensus/src/config.rs
  crates/executor/src/config.rs
  crates/executor/src/eth_dao_fork.rs
  crates/executor/src/executor.rs
  crates/executor/src/lib.rs
Labels: C-enhancement, A-execution

#828 feat(net) Increase the timeout for peers that are to be backed off repeatedly
  crates/net/network/src/peers/manager.rs
Labels: C-enhancement, C-perf, A-networking

#785 feat(metrics): derive with dynamic scope
  crates/metrics/metrics-derive/src/expand.rs
  crates/metrics/metrics-derive/src/lib.rs
  crates/metrics/metrics-derive/src/metric.rs
  crates/metrics/metrics-derive/tests/compile-fail/metrics_attr.rs
  crates/metrics/metrics-derive/tests/compile-fail/metrics_attr.stderr
Labels: C-enhancement, A-observability

#890 feat(rpc): integrate network traits in rpc builder
  Cargo.lock
  crates/net/rpc-builder/Cargo.toml
  crates/net/rpc-builder/src/config.rs
  crates/net/rpc-builder/src/lib.rs
Labels: C-enhancement, A-rpc

#885 refactor: remove db file on db drop command.
  bin/reth/src/db/mod.rs
Labels: C-debt, A-cli

#829 chore(net): Add `proptest` roundtrip to `rlp` types
  Cargo.lock
  crates/common/rlp/src/decode.rs
  crates/common/rlp/src/encode.rs
  crates/net/eth-wire/Cargo.toml
  crates/net/eth-wire/src/capability.rs
  crates/net/eth-wire/src/disconnect.rs
  crates/net/eth-wire/src/hello.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/eth-wire/src/types/blocks.rs
  crates/net/eth-wire/src/types/broadcast.rs
  crates/net/eth-wire/src/types/receipts.rs
  crates/net/eth-wire/src/types/state.rs
  crates/net/eth-wire/src/types/status.rs
  crates/net/eth-wire/src/types/transactions.rs
  crates/net/eth-wire/tests/fuzz_roundtrip.rs
  crates/net/network/src/message.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/bits.rs
  crates/primitives/src/block.rs
  crates/primitives/src/bloom.rs
  crates/primitives/src/chain.rs
  crates/primitives/src/forkid.rs
  crates/primitives/src/header.rs
  crates/primitives/src/hex_bytes.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/log.rs
  crates/primitives/src/peer.rs
  crates/primitives/src/receipt.rs
  crates/primitives/src/transaction/access_list.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/tx_type.rs
  crates/storage/codecs/derive/src/arbitrary.rs
  crates/storage/codecs/derive/src/lib.rs
  crates/storage/db/Cargo.toml
Labels: C-test, A-networking

#841 feat: add a reverse db walker
  bin/reth/src/db/mod.rs
  crates/storage/db/src/abstraction/cursor.rs
  crates/storage/db/src/implementation/mdbx/cursor.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: C-enhancement, A-db

#867 Add a --bootnodes flag for reth node
  bin/reth/src/config.rs
  bin/reth/src/node/mod.rs
Labels: C-enhancement, A-cli

#898 refactor: use mod.rs style
  crates/stages/src/pipeline/mod.rs
Labels: C-debt

#899 Fix build
  bin/reth/src/config.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/p2p/mod.rs
  bin/reth/src/stage/mod.rs
Labels: C-debt, A-cli

#900 feat(net): integrate num active peers in downloader
  crates/interfaces/src/p2p/downloader.rs
  crates/interfaces/src/test_utils/bodies.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/downloaders/src/test_utils.rs
  crates/net/network/src/fetch/client.rs
  crates/net/network/src/fetch/mod.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/state.rs
  crates/stages/src/stages/bodies.rs
Labels: A-networking

#901 feat(network): move test helpers to test-utils mod
  Cargo.lock
  crates/net/network/Cargo.toml
  crates/net/network/src/lib.rs
  crates/net/network/src/test_utils/init.rs
  crates/net/network/src/test_utils/mod.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/tests/it/connect.rs
  crates/net/network/tests/it/main.rs
  crates/net/network/tests/it/requests.rs
Labels: C-test, A-networking

#747 refactor: unify all chains confs
  Cargo.lock
  bin/reth/src/config.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/p2p/mod.rs
  bin/reth/src/stage/mod.rs
  bin/reth/src/test_eth_chain/models.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/cli/utils/src/chainspec.rs
  crates/cli/utils/src/init.rs
  crates/consensus/src/config.rs
  crates/consensus/src/consensus.rs
  crates/consensus/src/constants.rs
  crates/consensus/src/engine/error.rs
  crates/consensus/src/engine/mod.rs
  crates/consensus/src/lib.rs
  crates/consensus/src/verification.rs
  crates/executor/src/config.rs
  crates/executor/src/executor.rs
  crates/executor/src/lib.rs
  crates/net/dns/src/lib.rs
  crates/net/eth-wire/src/types/status.rs
  crates/net/network/src/config.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/session/active.rs
  crates/primitives/Cargo.toml
  crates/primitives/res/genesis/goerli.json
  crates/primitives/res/genesis/mainnet.json
  crates/primitives/res/genesis/sepolia.json
  crates/primitives/src/chain_spec.rs
  crates/primitives/src/genesis.rs
  crates/primitives/src/hardfork.rs
  crates/primitives/src/lib.rs
  crates/stages/src/stages/execution.rs
Labels: C-enhancement, A-execution, A-networking, A-cli

#906 feat(docs): Mention idle peer selection when downloading headers/bodies
  docs/repo/crates/network.md
Labels: C-docs, A-networking

#907 chore(primitives): test all mainnet forkids
  crates/primitives/src/chain_spec.rs
Labels: A-utils, C-test

#909 fix(node): insert genesis on node startup
  bin/reth/src/node/mod.rs
  crates/primitives/src/chain_spec.rs
Labels: C-bug

#910 chore(eth-wire): trace handshake messages
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/p2pstream.rs
Labels: C-debt, A-devp2p

#904 feat(primitives): impl genesis state root helper
  crates/primitives/src/genesis.rs
  crates/primitives/src/proofs.rs
Labels: C-enhancement, A-utils

#894 feat: BlockTransition remove hash from NumHash db index
  crates/cli/utils/src/init.rs
  crates/interfaces/src/provider.rs
  crates/stages/src/db.rs
  crates/stages/src/error.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/provider/src/block.rs
  crates/storage/provider/src/db_provider/storage.rs
  crates/storage/provider/src/lib.rs
Labels: C-enhancement, A-staged-sync, A-db

#880 feat(rpc): Add `admin_nodeInfo` to get the local node record
  crates/net/rpc-api/src/admin.rs
  crates/net/rpc-types/src/admin.rs
  crates/net/rpc-types/src/eth/syncing.rs
  crates/net/rpc-types/src/lib.rs
  crates/net/rpc/src/admin.rs
Labels: C-enhancement, A-rpc

#888 feat: add --nat flag to reth node
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/config.rs
  bin/reth/src/node/mod.rs
Labels: A-networking, A-cli

#897 Ability to (de)serialize NetworkConfigBuilder
  Cargo.lock
  bin/reth/src/config.rs
  crates/net/discv4/Cargo.toml
  crates/net/discv4/src/config.rs
  crates/net/dns/Cargo.toml
  crates/net/dns/src/config.rs
  crates/net/dns/src/tree.rs
  crates/net/nat/Cargo.toml
  crates/net/nat/src/lib.rs
  crates/net/network/Cargo.toml
  crates/net/network/src/config.rs
  crates/net/network/src/session/config.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/src/transactions.rs
  crates/net/network/tests/it/connect.rs
  crates/primitives/src/forkid.rs
Labels: C-enhancement, A-networking

#916 perf: tighten reputation change units
  crates/net/network/src/peers/reputation.rs
Labels: C-perf, A-networking

#917 docs: additional response handling docs
  crates/net/network/src/fetch/mod.rs
  crates/net/network/src/state.rs
Labels: C-docs

#918 fix(net): reset backoff counter on graceful disconnect
  crates/net/network/src/peers/manager.rs
Labels: A-networking

#915 chore(deps): rm unused deps
  Cargo.lock
  crates/cli/utils/Cargo.toml
  crates/cli/utils/src/lib.rs
Labels: C-debt, A-dependencies

#667 feat(bin): Format `db list` & `db status` subcommands
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/db/mod.rs
  bin/reth/src/db/tui.rs
  crates/primitives/src/storage.rs
  crates/storage/db/src/abstraction/database.rs
  crates/storage/db/src/abstraction/table.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/db/src/tables/models/accounts.rs
  crates/storage/db/src/tables/models/blocks.rs
  crates/storage/db/src/tables/models/sharded_key.rs
  docs/repo/crates/db.md
Labels: C-enhancement, A-cli

#921 feat(primitives): impl From<Genesis> for ChainSpec
  crates/primitives/src/chain_spec.rs
  crates/primitives/src/hardfork.rs
  crates/primitives/src/header.rs
Labels: C-enhancement, A-utils

#759 Docs Chapter - Discv4
  docs/repo/crates/discv4.md
Labels: C-docs, A-networking

#931 Send pings in P2PStream.poll_ready
  crates/net/eth-wire/src/p2pstream.rs
Labels: C-debt, A-networking

#933 chore(clippy): make clippy happy
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
Labels: C-debt

#934 test: add stage name to test suite functions
  Cargo.lock
  crates/stages/Cargo.toml
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/test_utils/macros.rs
Labels: C-test

#893 feat(metrics-derive): ability to specify labels during instantiation
  crates/metrics/metrics-derive/src/expand.rs
  crates/metrics/metrics-derive/tests/metrics.rs
Labels: A-observability

#939 fix(net): set status, forkfilter from chainspec
  crates/net/eth-wire/src/types/status.rs
  crates/net/network/Cargo.toml
  crates/net/network/src/config.rs
Labels: C-bug, A-networking

#891 feat: concurrent headers downloader
  Cargo.lock
  bin/reth/src/node/mod.rs
  crates/interfaces/src/p2p/downloader.rs
  crates/interfaces/src/p2p/error.rs
  crates/interfaces/src/p2p/headers/downloader.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/interfaces/src/test_utils/mod.rs
  crates/net/downloaders/Cargo.toml
  crates/net/downloaders/src/headers/linear.rs
  crates/primitives/src/block.rs
  crates/stages/src/stages/headers.rs
Labels: A-staged-sync, C-perf, A-networking

#935 Extend HeadersClient, BodiesClient with a priority argument
  crates/interfaces/src/p2p/bodies/client.rs
  crates/interfaces/src/p2p/headers/client.rs
  crates/interfaces/src/p2p/mod.rs
  crates/interfaces/src/p2p/priority.rs
  crates/interfaces/src/test_utils/bodies.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/downloaders/src/test_utils.rs
  crates/net/network/src/fetch/client.rs
  crates/net/network/src/fetch/mod.rs
  crates/stages/src/stages/bodies.rs
Labels: C-enhancement, A-networking

#943 refactor: remove legacy headermetrics describe
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/mod.rs
Labels: A-observability

#941 chore(net): reduce log level for outgoing conn errors
  crates/net/network/src/manager.rs
  crates/net/network/src/session/mod.rs
Labels: A-observability

#945 docs: document rlp derive macros
  crates/common/rlp-derive/src/de.rs
  crates/common/rlp-derive/src/en.rs
  crates/common/rlp-derive/src/lib.rs
Labels: C-docs, C-debt

#947 chore: prevent redundant hash initialization
  crates/primitives/src/transaction/mod.rs
Labels: C-debt

#930 build: bump the CRC crate from 1.x to 3.x
  crates/primitives/Cargo.toml
  crates/primitives/src/forkid.rs
Labels: A-dependencies

#948 chore: add help text for `--bootnodes`
  bin/reth/src/lib.rs
  bin/reth/src/node/mod.rs
Labels: C-debt, A-cli

#952 bug(stages): ExecutionStage incremented TranstionId to often
  Cargo.lock
  crates/stages/src/stages/execution.rs
Labels: C-bug, A-execution

#955 perf: send request retries with high priority
  crates/net/downloaders/src/headers/linear.rs
Labels: C-perf, A-networking

#960 chore: make update_head fn sync
  crates/stages/src/stages/headers.rs
Labels: A-staged-sync, C-debt

#965 fix(staged-sync): write genesis EIP1559 base fee
  bin/reth/src/node/mod.rs
  crates/staged-sync/src/utils/init.rs
Labels: C-enhancement, A-utils

#954 feat(rpc): add missing parts for rpc builder pipeline
  crates/net/rpc-builder/Cargo.toml
  crates/net/rpc-builder/src/lib.rs
Labels: A-rpc

#946 Prevent follow-up requests if a response is likely bad
  crates/interfaces/src/p2p/error.rs
  crates/net/network/src/fetch/mod.rs
Labels: C-enhancement, A-networking

#967 chore: rm unused HeaderClient in Header Stage
  bin/reth/src/node/mod.rs
  crates/stages/src/stages/headers.rs
Labels: C-debt

#966 fix: mark response correctly
  crates/interfaces/src/p2p/error.rs
  crates/net/network/src/fetch/mod.rs
Labels: C-bug, A-networking

#950 Create Network variant in reth_interfaces::Error
  Cargo.lock
  crates/interfaces/Cargo.toml
  crates/net/network-api/Cargo.toml
  crates/net/network-api/src/error.rs
  crates/net/network-api/src/lib.rs
  crates/net/network/src/network.rs
  crates/net/rpc/src/admin.rs
  crates/net/rpc/src/result.rs
Labels: C-enhancement, A-networking

#970 chore: make FetchClient Cloneable
  bin/reth/src/p2p/mod.rs
  crates/net/network/src/fetch/client.rs
Labels: C-debt

#928 chore(primitives): revise signature interface and transaction encode
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/signature.rs
Labels: C-debt, A-utils
