Repository paradigmxyz/reth, pull requests merged in 2023-12, with the labels that each got.

#5648 chore(txpool): query header on txpool maintenance bootup
  crates/transaction-pool/src/maintain.rs
Labels: A-tx-pool

#5646 feat: add Default for RpcServerArgs
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/args/types.rs
Labels: C-enhancement, A-cli

#5621 reth-ethereum-forks crate
  Cargo.lock
  Cargo.toml
  crates/ethereum-forks/Cargo.toml
  crates/ethereum-forks/src/forkid.rs
  crates/ethereum-forks/src/hardfork.rs
  crates/ethereum-forks/src/head.rs
  crates/ethereum-forks/src/lib.rs
  crates/net/dns/src/lib.rs
  crates/net/eth-wire/src/builder.rs
  crates/net/eth-wire/src/types/status.rs
  crates/net/network/src/session/active.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/header.rs
  crates/primitives/src/lib.rs
  examples/manual-p2p/src/main.rs
Labels: C-debt

#5650 chore: cleanup codecs deps
  Cargo.lock
  crates/primitives/Cargo.toml
  crates/storage/codecs/Cargo.toml
  crates/storage/codecs/src/lib.rs
  crates/storage/db/Cargo.toml
Labels: A-dependencies

#5651 chore: remove unused deps in primitives
  Cargo.lock
  crates/primitives/Cargo.toml
Labels: A-dependencies

#5652 chore: group optimism reexports
  crates/primitives/src/lib.rs
Labels: C-debt

#5454 Granular canonicalization metrics dashboard update
  etc/grafana/dashboards/overview.json
Labels: A-observability

#5657 fix: invert is error check
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: C-bug, A-rpc

#5658 feat: add Default for NetworkArgs and DiscoveryArgs
  bin/reth/src/args/network_args.rs
Labels: C-enhancement, A-cli

#5659 chore: simplify `Consensus::validate_header_range` with let-else
  crates/interfaces/src/consensus.rs
Labels: C-debt

#5663 chore: use StageConfig for more reth node methods
  bin/reth/src/node/mod.rs
Labels: C-enhancement, A-cli

#5664 feat(cli): eth state cache args
  bin/reth/src/args/mod.rs
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/args/rpc_state_cache_args.rs
  bin/reth/src/cli/config.rs
Labels: C-enhancement, A-cli

#5674 chore: clippy
  crates/consensus/auto-seal/src/lib.rs
  crates/payload/builder/src/payload.rs
  crates/rpc/rpc-types/src/eth/filter.rs
  crates/storage/nippy-jar/src/lib.rs
Labels: C-debt

#5672 chore: make trace builder ctrs public
  crates/revm/revm-inspectors/src/tracing/builder/geth.rs
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
Labels: C-debt

#5676 release: v0.1.0-alpha.13
  Cargo.lock
  Cargo.toml
Labels: A-meta

#5678 add troubleshooting section on concurrency with containers
  book/run/troubleshooting.md
Labels: C-docs, A-db

#5666 Fix eth message ID length bug
  crates/net/eth-wire/src/capability.rs
  crates/net/eth-wire/src/protocol.rs
  crates/net/eth-wire/src/types/message.rs
Labels: C-bug

#5686 fix: invoke enter,exit only for non root calls
  crates/revm/revm-inspectors/src/tracing/js/mod.rs
Labels: A-rpc

#5688 fix: use correct error if fault fn missing
  crates/revm/revm-inspectors/src/tracing/js/mod.rs
Labels: C-bug, A-rpc

#5700 test(tree): consecutive reorgs
  Cargo.lock
  crates/blockchain-tree/Cargo.toml
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/primitives/src/trie/account.rs
Labels: C-test, A-blockchain-tree

#5683 fix(tree): reinsert unwound state to dependent chains
  Cargo.lock
  bin/reth/Cargo.toml
  crates/blockchain-tree/Cargo.toml
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/beacon/Cargo.toml
  crates/primitives/src/trie/account.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/chain.rs
Labels: C-bug, A-blockchain-tree

#5670 test(storage): implement `DbCursorRO::walk_back` method for `CursorMock`
  crates/storage/db/src/abstraction/mock.rs
Labels: A-db, C-test

#5701 perf: misc changes
  crates/primitives/src/trie/hash_builder/mod.rs
  crates/primitives/src/trie/nibbles.rs
  crates/primitives/src/trie/nodes/mod.rs
  crates/storage/codecs/src/lib.rs
Labels: C-perf, A-db, A-trie

#5692 feat: make load_network_config and lookup_head generic over DB
  bin/reth/src/node/mod.rs
Labels: C-enhancement, A-cli

#5704 chore: temporarily disable doc related CI
  .github/workflows/book.yml
  .github/workflows/lint.yml
Labels: A-meta

#5703 chore(provider): better observability on append
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-debt, A-db, A-observability

#5706 chore: add fs read
  crates/primitives/src/fs.rs
Labels: C-enhancement

#5708 feat(primitives/net): make `parse_nodes` public
  crates/primitives/src/lib.rs
  crates/primitives/src/net.rs
Labels: A-utils

#5709 feat(primitives/net): export `ConnectionInfo`
  crates/net/network/src/peers/mod.rs
Labels: C-debt

#5714 chore: promote trace bad txs to debug
  crates/net/network/src/transactions.rs
Labels: A-observability

#5718 chore(book): update some expired links
  book/jsonrpc/txpool.md
Labels: C-docs

#5715 fix: use receover_signer_unchecked for tx receipt
  crates/primitives/src/transaction/mod.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-bug, A-rpc

#5721 fix: use unchecked sender recovery in rpc
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/transaction/mod.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-bug, C-perf, A-rpc

#5728 feat: add network bench
  Cargo.lock
  crates/net/network/Cargo.toml
  crates/net/network/benches/bench.rs
  crates/net/network/src/test_utils/testnet.rs
Labels: A-networking, C-benchmark

#5729 feat: add RethTransactionPoolConfig
  bin/reth/src/args/txpool_args.rs
  bin/reth/src/cli/config.rs
  bin/reth/src/node/mod.rs
Labels: A-cli

#5725 refactor(net): Simplified logic for determining shared capability versions
  crates/net/eth-wire/src/capability.rs
Labels: C-debt

#5690 feat: add DatabaseMetrics trait for generic DB in reth node
  bin/reth/src/node/mod.rs
  bin/reth/src/prometheus_exporter.rs
  crates/storage/db/src/abstraction/database_metrics.rs
  crates/storage/db/src/abstraction/mod.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/lib.rs
Labels: C-enhancement, A-db, A-observability, A-cli

#5730 docs(book): update CLI
  book/cli/cli.md
  book/cli/config.md
  book/cli/db.md
  book/cli/debug.md
  book/cli/import.md
  book/cli/init.md
  book/cli/node.md
  book/cli/p2p.md
  book/cli/recover.md
  book/cli/stage.md
  book/cli/test-vectors.md
Labels: C-docs

#5735 feat(bin): parse `RUST_LOG` in journald and log file filters
  bin/reth/src/cli/mod.rs
Labels: C-enhancement, A-observability, A-cli

#5583 feat(snapshots): refactor snapshot data access
  bin/reth/src/db/snapshots/mod.rs
  crates/storage/db/src/snapshot/cursor.rs
  crates/storage/nippy-jar/src/cursor.rs
  crates/storage/nippy-jar/src/lib.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
  crates/storage/provider/src/providers/snapshot/mod.rs
Labels: C-enhancement, A-snapshots

#5736 fix: dont include empty revert reason
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: A-rpc

#5559 feat: integrate multiplexing
  Cargo.lock
  crates/net/eth-wire/Cargo.toml
  crates/net/eth-wire/src/capability.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/hello.rs
  crates/net/eth-wire/src/multiplex.rs
  crates/net/eth-wire/src/test_utils.rs
  crates/net/eth-wire/src/types/status.rs
  crates/net/network/src/protocol.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/conn.rs
  crates/net/network/src/session/handle.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/tests/it/main.rs
  crates/net/network/tests/it/multiplex.rs
Labels: C-test, A-networking

#5710 feat(bin): I/O metrics
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/prometheus_exporter.rs
Labels: C-enhancement, A-observability, A-cli

#5705 Canonicalization metrics improvements
  crates/storage/provider/src/providers/database/metrics.rs
  etc/grafana/dashboards/overview.json
Labels: A-observability

#5759 chore: make CanonStateNotificationStream pub
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/traits/mod.rs
Labels: C-debt

#5761 feat: add SecretKey to networkconfig
  bin/reth/src/cli/config.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/session/mod.rs
Labels: A-networking

#5764 doc: --dev.block_time not available
  bin/reth/src/args/dev_args.rs
  book/cli/reth/node.md
Labels: C-docs

#5760 refactor: nippy jar writer, offsets
  crates/storage/db/src/snapshot/generation.rs
  crates/storage/nippy-jar/src/cursor.rs
  crates/storage/nippy-jar/src/lib.rs
  crates/storage/nippy-jar/src/writer.rs
Labels: C-debt, A-snapshots

#5765 fix(cli): allow no PHF or compression in snapshots
  bin/reth/src/db/snapshots/headers.rs
  bin/reth/src/db/snapshots/mod.rs
  bin/reth/src/db/snapshots/receipts.rs
  bin/reth/src/db/snapshots/transactions.rs
Labels: A-cli, A-snapshots

#5655 feat: `DatabaseProvider` delegates to `SnapshotProvider` on `ReceiptsProvider`
  bin/reth/src/db/snapshots/headers.rs
  bin/reth/src/db/snapshots/receipts.rs
  bin/reth/src/db/snapshots/transactions.rs
  bin/reth/src/node/mod.rs
  crates/interfaces/src/provider.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/snapshot/jar.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
  crates/storage/provider/src/providers/snapshot/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/receipts.rs
Labels: C-enhancement, A-snapshots

#5654 feat: `DatabaseProvider` delegates to `SnapshotProvider` on `TransactionsProvider`
  bin/reth/src/db/snapshots/headers.rs
  bin/reth/src/db/snapshots/receipts.rs
  bin/reth/src/db/snapshots/transactions.rs
  bin/reth/src/node/mod.rs
  crates/interfaces/src/provider.rs
  crates/rpc/rpc-types/src/eth/filter.rs
  crates/storage/nippy-jar/src/lib.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/snapshot/jar.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
  crates/storage/provider/src/providers/snapshot/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/receipts.rs
Labels: C-enhancement, A-snapshots

#5593 feat: `DatabaseProvider` delegates to `SnapshotProvider` on `HeadersProvider`
  bin/reth/src/db/snapshots/headers.rs
  bin/reth/src/db/snapshots/receipts.rs
  bin/reth/src/db/snapshots/transactions.rs
  bin/reth/src/node/mod.rs
  crates/interfaces/src/provider.rs
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/snapshot/jar.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
  crates/storage/provider/src/providers/snapshot/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/receipts.rs
Labels: C-enhancement, A-snapshots

#5768 chore: add note about execute fn in docs
  crates/storage/provider/src/traits/executor.rs
Labels: C-docs

#5769 chore: add helper for getting the final total difficulty if known
  crates/primitives/src/chain/spec.rs
Labels: C-enhancement

#5668 feat: Report MDBX commit latency metrics
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/metrics.rs
  crates/storage/libmdbx-rs/benches/transaction.rs
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/libmdbx-rs/src/lib.rs
  crates/storage/libmdbx-rs/src/transaction.rs
  crates/storage/libmdbx-rs/tests/cursor.rs
  crates/storage/libmdbx-rs/tests/transaction.rs
Labels: C-enhancement, A-db, A-observability

#5770 perf: reduce static data size
  crates/primitives/src/compression/mod.rs
  crates/primitives/src/compression/receipt_dictionary.bin
  crates/primitives/src/compression/receipt_dictionary.in
  crates/primitives/src/compression/transaction_dictionary.bin
  crates/primitives/src/compression/transaction_dictionary.in
Labels: C-perf

#5773 chore: remove RpcStateCacheArgs value parser
  bin/reth/src/args/rpc_state_cache_args.rs
Labels: C-enhancement, A-rpc

#5774 chore: add reorg metrics to grafana
  etc/grafana/dashboards/overview.json
Labels: A-observability

#5771 refactor: use `BlockWithSenders` in executors
  bin/reth/src/debug_cmd/build_block.rs
  bin/reth/src/debug_cmd/in_memory_merkle.rs
  crates/blockchain-tree/src/chain.rs
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/primitives/src/block.rs
  crates/revm/src/optimism/processor.rs
  crates/revm/src/processor.rs
  crates/stages/src/stages/execution.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/test_utils/executor.rs
  crates/storage/provider/src/traits/executor.rs
Labels: C-debt

#5776 refactor: make sender recovery explicit in provider
  bin/reth/src/debug_cmd/in_memory_merkle.rs
  bin/reth/src/debug_cmd/merkle.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/mod.rs
  crates/storage/provider/src/providers/database/metrics.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/block.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: C-debt

#5671 More descriptive reorg log
  crates/blockchain-tree/src/blockchain_tree.rs
Labels: A-observability

#5744 Archify EthStateCache
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/fee_history.rs
  crates/rpc/rpc/src/eth/cache/mod.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/logs_utils.rs
  crates/rpc/rpc/src/eth/pubsub.rs
Labels: C-perf, A-rpc

#5779 chore: bump proptest + arbitrary
  Cargo.toml
Labels: A-dependencies

#5778 fix: use the same ProviderFactory in reth node
  bin/reth/src/node/mod.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/prune/src/pruner.rs
Labels: C-enhancement, A-cli

#5786 feat: add PageOps metrics to libmdbx-rs
  .gitignore
  crates/storage/libmdbx-rs/src/environment.rs
Labels: C-enhancement, A-db, A-observability

#5792 fix(txpool): correct the EIP2930 Error logger in TxValidator
  crates/transaction-pool/src/validate/eth.rs
Labels: C-bug

#5791 feat: better usage of `by_id` methods in transaction pools
  crates/transaction-pool/src/pool/blob.rs
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/pending.rs
Labels: C-debt, A-tx-pool

#5789 refactor(primitives): small refactoring for pooled transactions
  crates/primitives/src/transaction/pooled.rs
Labels: C-debt, A-tx-pool

#5796 feat(grafana): sort stages
  etc/docker-compose.yml
  etc/grafana/dashboards/overview.json
Labels: A-observability, A-meta

#5797 chore: log full tx object in assert
  crates/transaction-pool/src/pool/blob.rs
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/pending.rs
Labels: C-debt, A-tx-pool

#5799 docs: adjust arm device guide
  book/installation/build-for-arm-devices.md
Labels: C-docs

#5808 chore: add note about grammar+typo prs
  CONTRIBUTING.md
Labels: A-meta

#5756 feat: support no-std for reth-codecs
  crates/storage/codecs/Cargo.toml
  crates/storage/codecs/src/lib.rs
Labels: C-enhancement

#5801 refactor: small refactoring for `Header` structure
  crates/primitives/src/header.rs
Labels: C-debt

#5787 feat: add SSZ encoding for `SignedBidSubmission`
  crates/rpc/rpc-types/src/eth/engine/payload.rs
  crates/rpc/rpc-types/src/eth/withdrawal.rs
  crates/rpc/rpc-types/src/relay.rs
  crates/rpc/rpc-types/test_data/relay/signed_bid_submission_capella.ssz
Labels: C-enhancement, A-rpc

#5780 feat: refactor indexing inside `SnapshotProvider`
  Cargo.lock
  crates/primitives/src/snapshot/mod.rs
  crates/primitives/src/snapshot/segment.rs
  crates/snapshot/src/snapshotter.rs
  crates/storage/db/src/snapshot/mod.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/providers/snapshot/manager.rs
Labels: A-snapshots

#5805 perf: skip initial transaction lookup during log queries
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/logs_utils.rs
  crates/rpc/rpc/src/eth/pubsub.rs
Labels: C-perf, A-rpc

#5777 feat: share decompressor buffer
  crates/primitives/src/compression/mod.rs
  crates/primitives/src/transaction/mod.rs
  crates/storage/codecs/derive/src/compact/generator.rs
Labels: C-perf, A-db

#5691 feat: make NodeState generic over DB with DatabaseMetadata
  bin/reth/src/node/events.rs
  crates/storage/db/src/abstraction/database_metrics.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/lib.rs
Labels: C-enhancement, A-db, A-cli

#5669 feat: refactor writing to `NippyJar`
  bin/reth/src/db/snapshots/mod.rs
  crates/storage/db/src/snapshot/generation.rs
  crates/storage/nippy-jar/src/cursor.rs
  crates/storage/nippy-jar/src/error.rs
  crates/storage/nippy-jar/src/lib.rs
  crates/storage/nippy-jar/src/writer.rs
  crates/storage/provider/src/providers/snapshot/mod.rs
Labels: C-enhancement, A-snapshots

#5738 feat: snapshots
  Cargo.lock
  bin/reth/src/db/snapshots/headers.rs
  bin/reth/src/db/snapshots/mod.rs
  bin/reth/src/db/snapshots/receipts.rs
  bin/reth/src/db/snapshots/transactions.rs
  bin/reth/src/node/mod.rs
  crates/interfaces/src/provider.rs
  crates/primitives/src/snapshot/mod.rs
  crates/primitives/src/snapshot/segment.rs
  crates/snapshot/src/snapshotter.rs
  crates/storage/db/src/snapshot/cursor.rs
  crates/storage/db/src/snapshot/generation.rs
  crates/storage/db/src/snapshot/mod.rs
  crates/storage/nippy-jar/src/cursor.rs
  crates/storage/nippy-jar/src/error.rs
  crates/storage/nippy-jar/src/lib.rs
  crates/storage/nippy-jar/src/writer.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/snapshot/jar.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
  crates/storage/provider/src/providers/snapshot/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/receipts.rs
Labels: A-snapshots

#5813 refactor: replace `std::fs` usages with `reth-primitives`
  bin/reth/src/debug_cmd/build_block.rs
  bin/reth/src/node/mod.rs
  crates/stages/benches/setup/account_hashing.rs
  crates/stages/benches/setup/mod.rs
  crates/storage/db/src/lib.rs
Labels: C-debt

#5815 feat: add submitblock request
  crates/rpc/rpc-types/src/relay.rs
  crates/rpc/rpc-types/test_data/relay/single_payload.json
Labels: C-enhancement, A-rpc

#5819 chore: bump fdlimit
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/run.rs
Labels: A-dependencies

#5821 chore: add optimism rpc errors
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/error.rs
Labels: C-enhancement, A-op-reth

#5834 feat: introduce PrunerBuilder
  Cargo.lock
  bin/reth/src/node/mod.rs
  crates/config/src/lib.rs
  crates/prune/Cargo.toml
  crates/prune/src/builder.rs
  crates/prune/src/lib.rs
  crates/prune/src/segments/set.rs
Labels: C-enhancement, A-cli, A-pruning

#5818 chore(nippy-jar): clippy
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/run.rs
  crates/rpc/rpc-types/src/relay/error.rs
  crates/rpc/rpc-types/src/relay/mod.rs
  crates/stages/src/stages/bodies.rs
  crates/storage/nippy-jar/src/writer.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
  crates/storage/provider/src/providers/snapshot/writer.rs
Labels: C-debt, A-snapshots

#5837 feat: create new methods with Config arguments for existing builders
  Cargo.lock
  bin/reth/src/chain/import.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/node/mod.rs
  crates/config/Cargo.toml
  crates/config/src/config.rs
  crates/config/src/lib.rs
  crates/net/downloaders/Cargo.toml
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
Labels: C-debt

#4653 Feature: Support db get for duptables (CLI)
  bin/reth/src/db/clear.rs
  bin/reth/src/db/get.rs
  bin/reth/src/db/list.rs
  bin/reth/src/utils.rs
  crates/storage/db/src/tables/mod.rs
Labels: C-enhancement, A-cli

#5842 feat: add testnet cancun timestamps
  crates/primitives/src/chain/spec.rs
Labels: C-enhancement, E-cancun

#5643 feat(trie): trie cursor abstraction
  bin/reth/src/debug_cmd/in_memory_merkle.rs
  bin/reth/src/recover/storage_tries.rs
  crates/stages/benches/setup/mod.rs
  crates/stages/src/stages/merkle.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/trie/src/proof.rs
  crates/trie/src/trie.rs
  crates/trie/src/trie_cursor/account_cursor.rs
  crates/trie/src/trie_cursor/database_cursors.rs
  crates/trie/src/trie_cursor/mod.rs
  crates/trie/src/trie_cursor/noop.rs
  crates/trie/src/trie_cursor/storage_cursor.rs
  crates/trie/src/walker.rs
Labels: C-enhancement, A-trie

#5845 chore: use bug issue template link in README
  README.md
Labels: C-enhancement

#5847 chore: remove `BlockBodyRoots` and reduce root calculation times
  crates/interfaces/src/p2p/full_block.rs
  crates/primitives/src/block.rs
  crates/primitives/src/header.rs
  crates/primitives/src/lib.rs
Labels: C-perf

#5848 chore(deps): cleanup reth-interfaces deps
  Cargo.lock
  crates/interfaces/Cargo.toml
  crates/interfaces/src/lib.rs
  crates/interfaces/src/p2p/full_block.rs
Labels: C-debt, A-dependencies

#5839 feat(bin): disable ETA for execution stage
  bin/reth/src/node/events.rs
Labels: C-enhancement, A-staged-sync, A-observability

#5849 fix(consensus): correct the fork name for validating 1559 transaction
  crates/consensus/common/src/validation.rs
Labels: C-bug, A-consensus

#5850 fix: mark pre-4844 blob txs as invalid in consensus
  crates/consensus/common/src/validation.rs
Labels: C-bug, A-consensus, C-test

#5832 chore(primitives): extract trie HashBuilder implementation
  Cargo.lock
  crates/primitives/Cargo.toml
  crates/primitives/src/trie/hash_builder/mod.rs
  crates/primitives/src/trie/hash_builder/proof_retainer.rs
  crates/primitives/src/trie/hash_builder/state.rs
  crates/primitives/src/trie/hash_builder/value.rs
  crates/primitives/src/trie/mask.rs
  crates/primitives/src/trie/mod.rs
  crates/primitives/src/trie/nodes/branch.rs
  crates/primitives/src/trie/nodes/extension.rs
  crates/primitives/src/trie/nodes/leaf.rs
  crates/primitives/src/trie/nodes/mod.rs
  crates/primitives/src/trie/proofs.rs
  crates/primitives/src/trie/storage.rs
  crates/primitives/src/trie/subnode.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/db/src/tables/mod.rs
  crates/trie/src/trie.rs
  crates/trie/src/trie_cursor/database_cursors.rs
  crates/trie/src/updates.rs
  crates/trie/src/walker.rs
Labels: A-trie

#5827 Trie hash optimizations
  Cargo.lock
  Cargo.toml
  crates/primitives/Cargo.toml
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/providers/database/provider.rs
  crates/trie/Cargo.toml
  crates/trie/src/hashed_cursor/post_state.rs
  crates/trie/src/node_iter.rs
  crates/trie/src/prefix_set/loader.rs
  crates/trie/src/prefix_set/mod.rs
  crates/trie/src/trie.rs
  crates/trie/src/trie_cursor/subnode.rs
  crates/trie/src/walker.rs
Labels: C-perf, A-trie

#5858 fix(txpool): missing condition that tx gas limit equal to block gas l…
  crates/transaction-pool/src/pool/txpool.rs
Labels: A-tx-pool

#5859 bin: run `reth` by default
  bin/reth/Cargo.toml
Labels: A-meta

#5860 log(downloader): log `count` instead of `distance`
  crates/net/downloaders/src/bodies/bodies.rs
Labels: A-observability, A-downloaders

#5864 refactor: small refactoring of revm database and documentation
  crates/revm/src/database.rs
Labels: C-docs

#5863 feat: add `sanity_check implementation` for block headers
  crates/primitives/src/header.rs
Labels: C-enhancement

#5824 feat: Introduce NodeBuilder
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/cli/db_type.rs
  bin/reth/src/cli/mod.rs
  bin/reth/src/cli/node_builder.rs
  bin/reth/src/dirs.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/utils.rs
  crates/net/network/src/manager.rs
  crates/storage/db/src/lib.rs
  crates/tracing/src/lib.rs
Labels: C-enhancement, C-test, A-cli

#5867 chore: bump itertools
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#5866 refactor: small refactoring and documentation in interfaces crate
  crates/interfaces/src/consensus.rs
  crates/interfaces/src/error.rs
  crates/interfaces/src/test_utils/full_block.rs
Labels: C-docs, C-debt

#5865 chore: add enum helper functions
  crates/rpc/rpc-builder/src/lib.rs
Labels: C-enhancement, A-rpc

#5875 feat(tree): track state trie updates
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/metrics.rs
Labels: A-observability, A-blockchain-tree

#5869 feat: Introduce NodeBuilder
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/cli/db_type.rs
  bin/reth/src/cli/mod.rs
  bin/reth/src/cli/node_builder.rs
  bin/reth/src/dirs.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/utils.rs
  crates/net/network/src/manager.rs
  crates/storage/db/src/lib.rs
  crates/tracing/src/lib.rs
Labels: C-enhancement

#5882 test: enable arbitrary feature for dependencies
  crates/primitives/Cargo.toml
Labels: C-debt

#5870 fix: better conversion error handling in `block_hash_ref`
  crates/interfaces/src/provider.rs
  crates/revm/src/database.rs
Labels: C-debt

#5876 refactor: move ethereum and op builder into separate crates
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  bin/reth/src/cli/ext.rs
  bin/reth/src/debug_cmd/build_block.rs
  crates/payload/basic/Cargo.toml
  crates/payload/basic/src/lib.rs
  crates/payload/basic/src/optimism.rs
  crates/payload/ethereum/Cargo.toml
  crates/payload/ethereum/src/lib.rs
  crates/payload/optimism/Cargo.toml
  crates/payload/optimism/src/lib.rs
Labels: C-debt, A-block-building

#5890 chore: ignore reth-ethereum-payload-builder in udeps
  Cargo.toml
Labels: C-debt

#5872 doc: improve documentation for trie crate
  crates/trie/src/node_iter.rs
  crates/trie/src/trie_cursor/database_cursors.rs
  crates/trie/src/trie_cursor/noop.rs
  crates/trie/src/trie_cursor/subnode.rs
  crates/trie/src/walker.rs
Labels: C-docs, A-trie

#5879 refactor(tree): block buffer
  crates/blockchain-tree/src/block_buffer.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/state.rs
Labels: C-bug, C-debt, A-blockchain-tree

#5886 chore: move reth commands to separate folder
  bin/reth/src/chain/mod.rs
  bin/reth/src/cli/ext.rs
  bin/reth/src/cli/mod.rs
  bin/reth/src/cli/node_builder.rs
  bin/reth/src/commands/config_cmd.rs
  bin/reth/src/commands/db/clear.rs
  bin/reth/src/commands/db/diff.rs
  bin/reth/src/commands/db/get.rs
  bin/reth/src/commands/db/list.rs
  bin/reth/src/commands/db/mod.rs
  bin/reth/src/commands/db/snapshots/bench.rs
  bin/reth/src/commands/db/snapshots/headers.rs
  bin/reth/src/commands/db/snapshots/mod.rs
  bin/reth/src/commands/db/snapshots/receipts.rs
  bin/reth/src/commands/db/snapshots/transactions.rs
  bin/reth/src/commands/db/tui.rs
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/debug_cmd/mod.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/init_cmd.rs
  bin/reth/src/commands/mod.rs
  bin/reth/src/commands/node/cl_events.rs
  bin/reth/src/commands/node/events.rs
  bin/reth/src/commands/node/mod.rs
  bin/reth/src/commands/p2p/mod.rs
  bin/reth/src/commands/recover/mod.rs
  bin/reth/src/commands/recover/storage_tries.rs
  bin/reth/src/commands/stage/drop.rs
  bin/reth/src/commands/stage/dump/execution.rs
  bin/reth/src/commands/stage/dump/hashing_account.rs
  bin/reth/src/commands/stage/dump/hashing_storage.rs
  bin/reth/src/commands/stage/dump/merkle.rs
  bin/reth/src/commands/stage/dump/mod.rs
  bin/reth/src/commands/stage/mod.rs
  bin/reth/src/commands/stage/run.rs
  bin/reth/src/commands/stage/unwind.rs
  bin/reth/src/commands/test_vectors/mod.rs
  bin/reth/src/commands/test_vectors/tables.rs
  bin/reth/src/lib.rs
  crates/consensus/auto-seal/tests/it/auto_mine.rs
Labels: C-enhancement, A-cli

#5899 chore: move builder to own module
  bin/reth/src/builder/mod.rs
  bin/reth/src/cli/mod.rs
  bin/reth/src/commands/node/mod.rs
  bin/reth/src/lib.rs
Labels: A-cli

#5900 feat: add TaskManager::current
  crates/tasks/src/lib.rs
Labels: C-enhancement

#5898 feat(chain): enable Holesky testnet dns with test
  crates/primitives/src/chain/mod.rs
Labels: C-enhancement

#5904 feat: add `nonce_after_all_transactions` implementation for `TxPool`
  crates/transaction-pool/src/pool/txpool.rs
Labels: A-tx-pool

#5914 docs: include s/2 value in docs
  crates/primitives/src/transaction/signature.rs
Labels: C-docs

#5908 chore: improve ipc error message
  crates/rpc/ipc/src/server/mod.rs
Labels: C-debt

#5909 fix: also adjust ipc path
  bin/reth/src/args/rpc_server_args.rs
Labels: C-bug
