Repository paradigmxyz/reth, pull requests merged in 2023-04, with the labels that each got.

#2072 chore: rm redundant pin_mut
  bin/reth/src/runner.rs
Labels: C-debt

#2073 fix: unix only sigterm
  bin/reth/src/runner.rs
Labels: C-debt, A-cli

#2075 refactor: reward calc cleanup
  Cargo.lock
  crates/consensus/common/src/calc.rs
  crates/consensus/common/src/lib.rs
  crates/executor/Cargo.toml
  crates/executor/src/executor.rs
  crates/primitives/src/constants.rs
  crates/revm/revm-primitives/src/config.rs
Labels: C-debt, A-consensus

#1976 rpc: add missing fields in send_transaction
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/traits.rs
Labels: C-enhancement, A-rpc

#2080 perf(txpool): filter by sender id
  crates/transaction-pool/src/identifier.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-perf, A-tx-pool

#2082 chore: impl transactions_by_block_range for mock provider
  crates/storage/provider/src/test_utils/mock.rs
Labels: C-test

#2085 chore: clippy fix
  crates/consensus/common/src/calc.rs
Labels: C-debt

#2087 fix(rpc): add basefee to header
  crates/rpc/rpc-types/src/eth/block.rs
Labels: A-rpc

#2089 chore(rpc): move trace_at function to trait
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/trace.rs
Labels: A-rpc

#2076 refactor: move executors to revm crate
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/chain/import.rs
  bin/reth/src/dump_stage/execution.rs
  bin/reth/src/dump_stage/merkle.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/mod.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/consensus/auto-seal/Cargo.toml
  crates/consensus/auto-seal/src/task.rs
  crates/executor/Cargo.toml
  crates/executor/src/lib.rs
  crates/revm/Cargo.toml
  crates/revm/src/executor.rs
  crates/revm/src/factory.rs
  crates/revm/src/lib.rs
  crates/stages/Cargo.toml
  crates/stages/src/lib.rs
  crates/stages/src/sets.rs
  crates/stages/src/stages/execution.rs
Labels: C-debt, A-execution

#2090 feat(rpc): impl debug_traceCall
  crates/revm/revm-inspectors/src/tracing/config.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: A-rpc

#2093 feat(rpc): add fourbyte inspector
  crates/primitives/src/lib.rs
  crates/revm/revm-inspectors/src/tracing/fourbyte.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
Labels: A-rpc

#2095 feat(db): add transaction_id helper
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/transactions.rs
Labels: A-db

#2094 fix(cli): display proper config path
  bin/reth/src/node/mod.rs
Labels: C-bug, A-cli

#2096 fix(cli): read existing jwt instead of recreating
  bin/reth/src/args/rpc_server_args.rs
Labels: A-cli

#2105 feat(rpc): use 4byte tracer
  crates/rpc/rpc/src/debug.rs
Labels: A-rpc

#2112 test: next key for seek_by_key_subkey
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: A-db, C-test

#2109 fix(net): enforce max transaction packet size
  crates/net/network/src/transactions.rs
Labels: A-networking

#2106 feat(rpc): implement trace call many
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/trace.rs
Labels: A-rpc

#2107 feat(rpc): add replay transaction
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/trace.rs
Labels: A-rpc

#2114 feat(rpc): impl debug trace block
  crates/rpc/rpc-types/src/eth/block.rs
  crates/rpc/rpc-types/src/eth/trace/geth/mod.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: A-rpc

#2111 feat: add opcount tracer
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/opcount.rs
Labels: A-rpc

#2118 chore(rpc): add proper engine_newPayload error messages
  Cargo.lock
  crates/consensus/beacon/src/engine/mod.rs
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/error.rs
  crates/rpc/rpc/src/engine.rs
Labels: A-rpc

#2122 fix: checked u64 downcast
  Cargo.lock
  crates/primitives/Cargo.toml
  crates/primitives/src/lib.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: C-bug, A-rpc

#2121 chore: add minimal protocol base fee
  crates/primitives/src/constants.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/test_utils/mock.rs
Labels: C-debt

#2124 fix(engine): future payload handling
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/executor.rs
Labels: C-bug, A-consensus

#2039 feat: Refactor TransitionId tables, BlockBodyIndices table.
  bin/reth/src/db/mod.rs
  bin/reth/src/dump_stage/execution.rs
  bin/reth/src/dump_stage/hashing_account.rs
  bin/reth/src/dump_stage/merkle.rs
  bin/reth/src/dump_stage/mod.rs
  bin/reth/src/test_vectors/tables.rs
  crates/interfaces/src/provider.rs
  crates/staged-sync/src/utils/init.rs
  crates/stages/benches/criterion.rs
  crates/stages/benches/setup/account_hashing.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/codecs/derive/src/compact/mod.rs
  crates/storage/db/benches/criterion.rs
  crates/storage/db/benches/iai.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/db/src/tables/models/blocks.rs
  crates/storage/libmdbx-rs/tests/transaction.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/provider/src/transaction.rs
  crates/storage/provider/src/utils.rs
Labels: C-debt, A-db

#2079 feat: emit new block events in --auto-mine
  Cargo.lock
  bin/reth/src/node/mod.rs
  crates/consensus/auto-seal/Cargo.toml
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/auto-seal/src/task.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/executor/src/blockchain_tree/mod.rs
  crates/interfaces/Cargo.toml
  crates/interfaces/src/events.rs
  crates/rpc/rpc-api/src/eth_pubsub.rs
Labels: C-enhancement

#2127 chore: add some traces
  crates/consensus/beacon/src/engine/mod.rs
  crates/stages/src/pipeline/mod.rs
Labels: A-observability

#2132 chore: add docs for PayloadStatusEnum
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: C-docs

#2117 feat(rpc): implement trace_Block
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/trace.rs
Labels: A-rpc

#2140 chore(docs): typos
  crates/executor/src/blockchain_tree/externals.rs
  crates/executor/src/blockchain_tree/mod.rs
Labels: C-docs

#2139 fix: always serialize validationError
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: A-rpc

#2142 chore/ci: update deny config and action
  .github/workflows/deny.yml
  deny.toml
Labels: A-observability, A-dependencies

#2143 feat: add Payload build abstraction
  Cargo.lock
  Cargo.toml
  crates/miner/Cargo.toml
  crates/miner/src/error.rs
  crates/miner/src/lib.rs
  crates/miner/src/payload.rs
  crates/primitives/src/withdrawal.rs
  crates/rpc/rpc-types/src/eth/engine/forkchoice.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: C-enhancement, A-rpc

#2149 chore: replace h64 with payload
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/message.rs
  crates/rpc/rpc/src/engine.rs
Labels: C-debt, A-rpc

#2138 fix: track ttd in auto mine
  crates/consensus/auto-seal/src/lib.rs
Labels: C-bug, A-consensus

#2147 chore(cli): remove mouse capturing
  bin/reth/src/db/tui.rs
Labels: A-cli

#2150 feat: add blockValue to execution payload
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/message.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
  crates/rpc/rpc/src/engine.rs
Labels: A-rpc

#1946 feat: add secret-key command line option
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/args/mod.rs
  bin/reth/src/args/network_args.rs
  bin/reth/src/args/secret_key.rs
  bin/reth/src/dirs.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/p2p/mod.rs
  bin/reth/src/stage/mod.rs
  crates/staged-sync/Cargo.toml
  crates/staged-sync/src/config.rs
Labels: C-enhancement, A-cli

#2158 feat: add engine rpc errors with codes
  crates/rpc/rpc-types/src/eth/engine/error.rs
  crates/rpc/rpc-types/src/eth/engine/mod.rs
Labels: A-rpc

#2162 chore(deps): bump tokio
  Cargo.lock
  crates/net/network/src/session/active.rs
Labels: A-dependencies

#2148 Network integrations tests with txpool task
  crates/net/network/src/config.rs
  crates/net/network/src/transactions.rs
  crates/transaction-pool/src/test_utils/mock.rs
Labels: A-tx-pool, C-test

#2164 chore: unify disable discovery builder functions
  crates/net/network/src/config.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/src/transactions.rs
Labels: C-debt

#2166 feat(trie): setup crate
  Cargo.lock
  Cargo.toml
  crates/trie/Cargo.toml
  crates/trie/src/lib.rs
Labels: C-enhancement, A-trie

#2169 docs: add note about post state
  crates/storage/provider/src/traits/state.rs
Labels: C-docs

#2170 feat(trie): nibbles
  crates/primitives/src/lib.rs
  crates/primitives/src/trie/mod.rs
  crates/primitives/src/trie/nibbles.rs
Labels: C-enhancement, A-trie

#2171 feat(trie): branch node
  crates/primitives/src/trie/branch_node.rs
  crates/primitives/src/trie/mask.rs
  crates/primitives/src/trie/mod.rs
Labels: C-enhancement, A-trie

#2173 chore: manual default for PostState
  crates/storage/provider/src/post_state.rs
Labels: C-perf, A-db

#2174 feat(trie): trie nodes
  Cargo.lock
  crates/trie/Cargo.toml
  crates/trie/src/lib.rs
  crates/trie/src/nodes/branch.rs
  crates/trie/src/nodes/extension.rs
  crates/trie/src/nodes/leaf.rs
  crates/trie/src/nodes/mod.rs
Labels: C-enhancement, A-trie

#2157 feat: more builder abstractions
  Cargo.lock
  crates/miner/Cargo.toml
  crates/miner/src/error.rs
  crates/miner/src/lib.rs
  crates/miner/src/payload.rs
  crates/miner/src/service.rs
  crates/miner/src/traits.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: C-enhancement

#2177 feat(trie): hash builder
  Cargo.lock
  crates/primitives/src/trie/branch_node.rs
  crates/primitives/src/trie/mask.rs
  crates/primitives/src/trie/nibbles.rs
  crates/trie/Cargo.toml
  crates/trie/src/hash_builder/mod.rs
  crates/trie/src/hash_builder/value.rs
  crates/trie/src/lib.rs
  crates/trie/src/nodes/branch.rs
  crates/trie/src/nodes/mod.rs
Labels: C-enhancement, A-trie

#2168 feat: add BlockchainTreeViewer::block_by_hash
  crates/executor/src/blockchain_tree/mod.rs
  crates/executor/src/blockchain_tree/shareable.rs
  crates/interfaces/src/blockchain_tree.rs
  crates/storage/provider/src/chain.rs
Labels: C-enhancement

#2183 fix: ensure Signature is ethereum scheme
  crates/primitives/src/transaction/signature.rs
Labels: C-bug

#2185 feat: extract commit_changes function
  crates/revm/src/executor.rs
Labels: C-enhancement

#2163 Adding miner args for cli
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/args/mod.rs
  bin/reth/src/args/payload_build_args.rs
Labels: C-enhancement, A-cli

#2137 perf: use `par_sort` on `TxLookup` stage
  crates/stages/src/stages/tx_lookup.rs
Labels: A-staged-sync, C-perf

#2191 chore: add PostState::logs_bloom
  crates/storage/provider/src/post_state.rs
Labels: C-enhancement

#2187 docs(rpc): add docs about engine_getPayloadV build process cancel
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc/src/engine.rs
Labels: C-docs, A-rpc

#2190 chore: add ChainSpec convenience function for Hardfork timestamps
  crates/primitives/src/chain/spec.rs
Labels: C-enhancement

#2188 chore: accept AsRef in calculate_transaction_root
  crates/primitives/src/proofs.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-enhancement

#2186 chore: extract withdrawal balance changes function
  crates/revm/src/executor.rs
Labels: C-enhancement

#2182 feat(trie): stored nibbles
  Cargo.lock
  crates/primitives/src/trie/mod.rs
  crates/primitives/src/trie/nibbles.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/db/src/tables/models/mod.rs
  crates/trie/Cargo.toml
  crates/trie/src/hash_builder/mod.rs
  crates/trie/src/lib.rs
  crates/trie/src/nibbles.rs
  crates/trie/src/nodes/extension.rs
  crates/trie/src/nodes/leaf.rs
  crates/trie/src/prefix_set.rs
Labels: C-enhancement, A-db, A-trie

#2194 fix(engine): initial sync target
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-bug, A-consensus

#2197 chore: clippy
  crates/storage/provider/src/traits/chain.rs
  crates/transaction-pool/src/config.rs
Labels: A-meta

#2193 fix(engine): pipeline run conditions
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-bug, A-consensus

#2198 fix(download): body consecutive range
  crates/net/downloaders/src/bodies/bodies.rs
Labels: C-bug, A-networking

#2201 feat: extract increment_account_balance
  crates/revm/src/executor.rs
Labels: C-enhancement

#2203 chore(trie): remove proptest with arbitrary leaves
  crates/trie/src/hash_builder/mod.rs
Labels: C-test, A-trie

#2200 feat(engine): basic beacon engine metrics
  Cargo.lock
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/engine/mod.rs
Labels: A-consensus, A-observability

#2212 fix(txpool): enforce minimum priority fee
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate.rs
Labels: A-tx-pool

#2213 chore: use cost in error
  crates/primitives/src/transaction/error.rs
  crates/transaction-pool/src/validate.rs
Labels: A-tx-pool

#2214 chore: enable tx inserts via p2p
  crates/net/network/src/transactions.rs
  crates/transaction-pool/src/error.rs
Labels: A-tx-pool

#2206 feat(trie): state root
  Cargo.lock
  crates/primitives/src/lib.rs
  crates/primitives/src/storage.rs
  crates/primitives/src/trie/branch_node.rs
  crates/primitives/src/trie/mask.rs
  crates/primitives/src/trie/mod.rs
  crates/primitives/src/trie/storage.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/stages/Cargo.toml
  crates/stages/benches/setup/mod.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/mod.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/provider/src/transaction.rs
  crates/storage/provider/src/trie/mod.rs
  crates/trie/Cargo.toml
  crates/trie/src/cursor/account_cursor.rs
  crates/trie/src/cursor/mod.rs
  crates/trie/src/cursor/storage_cursor.rs
  crates/trie/src/cursor/subnode.rs
  crates/trie/src/cursor/trie_cursor.rs
  crates/trie/src/errors.rs
  crates/trie/src/hash_builder/mod.rs
  crates/trie/src/lib.rs
  crates/trie/src/nibbles.rs
  crates/trie/src/nodes/branch.rs
  crates/trie/src/nodes/mod.rs
  crates/trie/src/prefix_set/loader.rs
  crates/trie/src/prefix_set/mod.rs
  crates/trie/src/test_utils.rs
  crates/trie/src/trie.rs
  crates/trie/src/walker.rs
Labels: C-enhancement, A-trie

#2216 chore(db): clarify upsert
  crates/storage/db/src/implementation/mdbx/cursor.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: C-docs, A-db, C-test

#2161 feat: add basic payload generator
  Cargo.lock
  Cargo.toml
  crates/miner/Cargo.toml
  crates/miner/src/error.rs
  crates/miner/src/payload.rs
  crates/miner/src/service.rs
  crates/miner/src/traits.rs
  crates/payload/basic/Cargo.toml
  crates/payload/basic/src/lib.rs
  crates/primitives/src/proofs.rs
  crates/primitives/src/receipt.rs
  crates/revm/Cargo.toml
  crates/revm/revm-primitives/src/config.rs
  crates/revm/src/executor.rs
  crates/storage/provider/src/post_state.rs
  crates/storage/provider/src/traits/evm_env.rs
  crates/tasks/src/lib.rs
Labels: C-enhancement

#2217 chore: rename miner to payload builder
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  bin/reth/src/node/mod.rs
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/engine/error.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/payload/basic/Cargo.toml
  crates/payload/basic/src/lib.rs
  crates/payload/builder/Cargo.toml
  crates/payload/builder/src/error.rs
  crates/payload/builder/src/lib.rs
  crates/payload/builder/src/payload.rs
  crates/payload/builder/src/service.rs
  crates/payload/builder/src/traits.rs
Labels: C-debt

#2223 chore: add payload code owners
  CODEOWNERS
Labels: A-meta

#2229 feat: add constants for slot and epoch
  crates/payload/basic/src/lib.rs
  crates/primitives/src/constants.rs
Labels: C-enhancement

#2226 fix(rpc): use exact error messages
  crates/rpc/rpc-types/src/eth/engine/error.rs
Labels: A-rpc

#2224 perf: shortcircuit if new payload is worse
  crates/payload/basic/src/lib.rs
  crates/payload/builder/src/error.rs
Labels: C-perf, A-block-building

#2220 chore: move client constant to primitives
  crates/net/eth-wire/src/hello.rs
  crates/primitives/src/constants.rs
Labels: C-debt

#2231 fix: add MaybePlatformPath
  bin/reth/src/args/network_args.rs
  bin/reth/src/args/secret_key.rs
  bin/reth/src/chain/import.rs
  bin/reth/src/chain/init.rs
  bin/reth/src/db/mod.rs
  bin/reth/src/dirs.rs
  bin/reth/src/drop_stage.rs
  bin/reth/src/dump_stage/mod.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/mod.rs
  bin/reth/src/utils.rs
Labels: C-bug, A-cli

#2234 fix(merkle): small merkle test flake
  crates/stages/src/stages/merkle.rs
Labels: A-staged-sync, A-db, C-test

#2248 fix: remove inaccurate warning about engine API being unsupported
  bin/reth/src/node/mod.rs
Labels: C-debt, A-observability, A-cli

#2245 fix: remove peers after incoming connection closed
  crates/net/network/src/manager.rs
  crates/net/network/src/peers/manager.rs
Labels: C-bug, A-networking

#2240 refactor: simplify engine Api
  Cargo.lock
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/node/mod.rs
  crates/consensus/beacon/src/engine/message.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/payload/builder/src/payload.rs
  crates/payload/builder/src/service.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/error.rs
  crates/rpc/rpc-engine-api/src/lib.rs
  crates/rpc/rpc-engine-api/src/message.rs
  crates/rpc/rpc-types/src/eth/engine/error.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
  crates/rpc/rpc/src/engine.rs
Labels: C-debt, A-rpc, A-block-building

#2184 perf: use ExecutionResult::into_logs
  Cargo.lock
  crates/payload/builder/Cargo.toml
  crates/revm/revm-inspectors/Cargo.toml
  crates/revm/revm-primitives/Cargo.toml
  crates/revm/src/executor.rs
  crates/rlp/Cargo.toml
  crates/rpc/rpc/Cargo.toml
  crates/storage/codecs/Cargo.toml
Labels: S-blocked, C-perf

#2256 fix: simplify SyncState and fix wrong update
  crates/interfaces/src/sync.rs
  crates/net/network/src/transactions.rs
  crates/net/network/tests/it/connect.rs
  crates/stages/src/id.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/pipeline/progress.rs
Labels: C-bug, A-staged-sync

#2259 Revert "Revert "chore: enable tx inserts via p2p" (#2252)"
  crates/net/network/src/transactions.rs
  crates/transaction-pool/src/error.rs
Labels: C-debt

#2261 fix(rpc): add missing v2 handler
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-bug

#2265 chore: move metrics to submodule
  crates/consensus/beacon/src/engine/metrics.rs
  crates/consensus/beacon/src/engine/mod.rs
Labels: A-consensus

#2268 fix: be less strict about what's a bad tx
  crates/transaction-pool/src/error.rs
Labels: A-tx-pool

#2269 fix(rpc): flip is empty check
  crates/rpc/rpc/src/eth/api/state.rs
Labels: C-bug, A-rpc, A-tx-pool

#2267 chore: make clippy happy
  crates/trie/src/cursor/storage_cursor.rs
  crates/trie/src/hash_builder/mod.rs
  crates/trie/src/trie.rs
Labels: C-debt

#2266 refactor: add beacon engine handle
  bin/reth/src/node/mod.rs
  crates/consensus/beacon/src/engine/error.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: A-rpc, A-consensus

#2273 fix(cli): event reporting
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/node/events.rs
  bin/reth/src/node/mod.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/rpc/rpc-types/src/eth/engine/forkchoice.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
  crates/stages/src/pipeline/mod.rs
  crates/tasks/src/lib.rs
Labels: C-bug, A-observability

#2271 chore: use client version as extradata
  crates/payload/basic/src/lib.rs
Labels: A-block-building

#2276 fix: poll_tick does not register waker if ready
  crates/net/discv4/src/lib.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/session/active.rs
  crates/payload/basic/src/lib.rs
Labels: C-bug

#2272 chore(rpc): rpc and auth server cleanup
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/node/mod.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-engine-api/src/lib.rs
Labels: C-debt, A-rpc

#2270 feat(net): add reported bad transactions metric
  crates/net/network/src/metrics.rs
  crates/net/network/src/transactions.rs
Labels: A-observability, A-networking

#2278 test: add basic auth server tests
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/args/rpc_server_args.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/auth.rs
  crates/rpc/rpc-builder/tests/it/main.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc/src/layers/jwt_secret.rs
  crates/rpc/rpc/src/layers/jwt_validator.rs
  crates/rpc/rpc/src/layers/mod.rs
  crates/rpc/rpc/src/lib.rs
Labels: A-rpc, C-test

#2281 Removing reth network api dependency from rpc types
  Cargo.lock
  crates/net/network-api/Cargo.toml
  crates/net/network-api/src/lib.rs
  crates/net/network-api/src/test_utils.rs
  crates/net/network/Cargo.toml
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/admin.rs
  crates/rpc/rpc-types/src/eth/syncing.rs
Labels: C-debt, A-rpc

#2282 fix(payload): use latest block for genesis block
  crates/payload/basic/src/lib.rs
Labels: C-bug, A-block-building

#2284 fix(payload): sum cumulative gas used before adding receipt
  crates/payload/basic/src/lib.rs
Labels: C-bug, A-block-building

#2280 chore(rpc): use cache layer for block endpoints
  crates/rpc/rpc/src/eth/api/block.rs
Labels: C-perf, A-rpc

#2285 chore: rename executor -> blockchain-tree
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  bin/reth/src/node/mod.rs
  crates/blockchain-tree/Cargo.toml
  crates/blockchain-tree/src/blockchain_tree/block_indices.rs
  crates/blockchain-tree/src/blockchain_tree/chain.rs
  crates/blockchain-tree/src/blockchain_tree/config.rs
  crates/blockchain-tree/src/blockchain_tree/externals.rs
  crates/blockchain-tree/src/blockchain_tree/mod.rs
  crates/blockchain-tree/src/blockchain_tree/post_state_data.rs
  crates/blockchain-tree/src/blockchain_tree/shareable.rs
  crates/blockchain-tree/src/eth_dao_fork.rs
  crates/blockchain-tree/src/lib.rs
  crates/blockchain-tree/src/test_utils/executor.rs
  crates/blockchain-tree/src/test_utils/factory.rs
  crates/blockchain-tree/src/test_utils/mod.rs
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/engine/mod.rs
  crates/revm/Cargo.toml
  crates/revm/src/executor.rs
  crates/stages/Cargo.toml
  docs/crates/stages.md
  docs/repo/layout.md
Labels: A-meta

#2286 chore: run commands as blocking task
  bin/reth/src/chain/init.rs
  bin/reth/src/cli.rs
  bin/reth/src/db/mod.rs
  bin/reth/src/drop_stage.rs
  bin/reth/src/dump_stage/mod.rs
  bin/reth/src/runner.rs
  bin/reth/src/stage/mod.rs
Labels: A-cli

#2291 fix: use JsonU256 for deserializing genesis U256s
  crates/primitives/src/genesis.rs
Labels: C-bug, A-utils

#2299 chore: simplify re-export
  crates/net/network/src/config.rs
Labels: C-debt

#2300 docs: extend validate docs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/validate.rs
Labels: C-docs, A-tx-pool

#2304 chore: add on forkchoice update traces
  crates/consensus/beacon/src/engine/mod.rs
Labels: A-observability

#2295 feat: process payload job initiation async
  crates/consensus/beacon/src/engine/error.rs
  crates/consensus/beacon/src/engine/message.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/payload/builder/src/service.rs
  crates/rpc/rpc-engine-api/src/error.rs
  crates/rpc/rpc-types/src/eth/engine/forkchoice.rs
Labels: A-rpc, A-consensus

#2287 chore: move StageEnum to separate module
  bin/reth/src/args/mod.rs
  bin/reth/src/args/stage_args.rs
  bin/reth/src/drop_stage.rs
  bin/reth/src/lib.rs
  bin/reth/src/stage/mod.rs
Labels: C-debt, A-cli

#2310 docs: add a few clarifying docs
  crates/storage/provider/src/chain.rs
  crates/storage/provider/src/post_state.rs
Labels: C-docs

#2317 feat(rpc): add engine eth subset rpc handler
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-api/src/lib.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/engine.rs
  crates/rpc/rpc/src/lib.rs
Labels: A-rpc, A-consensus

#2314 feat(cli): merkle debug cmd
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/cli.rs
  bin/reth/src/lib.rs
  bin/reth/src/merkle_debug.rs
Labels: C-enhancement, A-cli, A-trie

#2275 feat: block level indexing
  bin/reth/src/dump_stage/hashing_account.rs
  bin/reth/src/dump_stage/merkle.rs
  bin/reth/src/test_eth_chain/runner.rs
  bin/reth/src/utils.rs
  crates/blockchain-tree/src/blockchain_tree/chain.rs
  crates/blockchain-tree/src/blockchain_tree/mod.rs
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/beacon/src/beacon_consensus.rs
  crates/interfaces/src/consensus.rs
  crates/interfaces/src/p2p/bodies/downloader.rs
  crates/interfaces/src/p2p/bodies/response.rs
  crates/interfaces/src/p2p/error.rs
  crates/interfaces/src/provider.rs
  crates/interfaces/src/test_utils/generators.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/queue.rs
  crates/net/downloaders/src/bodies/request.rs
  crates/net/downloaders/src/bodies/task.rs
  crates/net/downloaders/src/test_utils/file_client.rs
  crates/net/downloaders/src/test_utils/mod.rs
  crates/payload/basic/src/lib.rs
  crates/primitives/src/lib.rs
  crates/revm/src/executor.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
  crates/stages/benches/setup/account_hashing.rs
  crates/stages/benches/setup/mod.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/codecs/derive/src/compact/mod.rs
  crates/storage/db/src/tables/codecs/fuzz/mod.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/db/src/tables/models/accounts.rs
  crates/storage/db/src/tables/models/blocks.rs
  crates/storage/db/src/tables/models/sharded_key.rs
  crates/storage/db/src/tables/models/storage_sharded_key.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/chain.rs
  crates/storage/provider/src/post_state.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/provider/src/transaction.rs
  crates/storage/provider/src/utils.rs
  crates/trie/src/prefix_set/loader.rs
  crates/trie/src/trie.rs
  docs/design/database.md
Labels: C-enhancement, C-perf, A-execution, A-db

#2322 chore: rm outdated TODOs
  crates/consensus/beacon/src/engine/mod.rs
  crates/net/network/src/transactions.rs
Labels: C-debt

#2323 fix: dont end beacon engine on bad payload
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt

#2321 chore(net): track all bad reported messages
  crates/net/network/src/transactions.rs
Labels: A-observability

#2279 feat(db): Don't store `TxHash` when writing to the table
  crates/consensus/auto-seal/src/task.rs
  crates/net/network/src/transactions.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/signature.rs
  crates/rpc/rpc-types/src/eth/block.rs
  crates/rpc/rpc-types/src/eth/transaction/mod.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/trace.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/codecs/derive/src/compact/generator.rs
  crates/storage/codecs/derive/src/compact/mod.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/transaction.rs
  crates/storage/provider/src/utils.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
Labels: A-db

#2233 feat(trie): read-only root calculation
  bin/reth/src/drop_stage.rs
  crates/primitives/src/checkpoints.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/trie/branch_node.rs
  crates/primitives/src/trie/hash_builder.rs
  crates/primitives/src/trie/mask.rs
  crates/primitives/src/trie/mod.rs
  crates/primitives/src/trie/subnode.rs
  crates/stages/benches/setup/mod.rs
  crates/stages/src/stages/merkle.rs
  crates/storage/codecs/src/lib.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/provider/src/transaction.rs
  crates/trie/src/cursor/account_cursor.rs
  crates/trie/src/cursor/storage_cursor.rs
  crates/trie/src/cursor/subnode.rs
  crates/trie/src/cursor/trie_cursor.rs
  crates/trie/src/hash_builder.rs
  crates/trie/src/hash_builder/value.rs
  crates/trie/src/lib.rs
  crates/trie/src/prefix_set/loader.rs
  crates/trie/src/progress.rs
  crates/trie/src/trie.rs
  crates/trie/src/updates.rs
  crates/trie/src/walker.rs
Labels: C-enhancement, A-trie

#2324 perf(tree): check block before inserting
  crates/blockchain-tree/src/blockchain_tree/block_indices.rs
  crates/blockchain-tree/src/blockchain_tree/mod.rs
  crates/blockchain-tree/src/blockchain_tree/shareable.rs
Labels: C-perf

#2332 chore: update code owners
  CODEOWNERS
Labels: A-meta

#2331 chore(trie): remove obsolete sender type
  crates/trie/src/hash_builder.rs
Labels: A-trie

#2335 chore(deps): bump h2 dependency
  Cargo.lock
Labels: A-dependencies

#2333 chore(trie): rename cursor module
  crates/trie/src/cursor/mod.rs
  crates/trie/src/lib.rs
  crates/trie/src/progress.rs
  crates/trie/src/trie.rs
  crates/trie/src/trie_cursor/account_cursor.rs
  crates/trie/src/trie_cursor/mod.rs
  crates/trie/src/trie_cursor/storage_cursor.rs
  crates/trie/src/trie_cursor/subnode.rs
  crates/trie/src/walker.rs
Labels: A-trie

#2330 perf(trie): swap trie updates `BTreeMap` for `HashMap`
  crates/primitives/src/trie/nibbles.rs
  crates/stages/src/stages/merkle.rs
  crates/trie/src/hash_builder.rs
  crates/trie/src/nibbles.rs
  crates/trie/src/progress.rs
  crates/trie/src/trie.rs
  crates/trie/src/updates.rs
Labels: C-perf, A-trie

#2338 style: use clear over truncate(0)
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/tx_lookup.rs
Labels: C-debt

#2327 chore(rpc): instrument rpc calls
  Cargo.lock
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/engine.rs
Labels: A-rpc

#2328 fix docs related to tables
  README.md
  docs/design/README.md
  docs/design/database.md
Labels: C-docs, C-debt

#1348 ci: hive tests
  .github/workflows/hive.yml
Labels: A-utils, C-test

#2343 fix: track exact number of transactions
  crates/stages/src/stages/tx_lookup.rs
  crates/storage/db/src/tables/models/blocks.rs
Labels: C-bug

#2350 feat: use caching layer when fetching blocks for logs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/eth/filter.rs
Labels: C-perf, A-rpc

#2353 fix: use a gauge for `mgas_processed` metric
  crates/stages/src/stages/execution.rs
Labels: C-bug, A-observability

#2359 chore(tree): Move tree related files to root of the lib
  Cargo.lock
  crates/blockchain-tree/src/block_indices.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/chain.rs
  crates/blockchain-tree/src/config.rs
  crates/blockchain-tree/src/externals.rs
  crates/blockchain-tree/src/lib.rs
  crates/blockchain-tree/src/post_state_data.rs
  crates/blockchain-tree/src/shareable.rs
  crates/blockchain-tree/src/test_utils/executor.rs
  crates/blockchain-tree/src/test_utils/mod.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/revm/Cargo.toml
  crates/revm/src/eth_dao_fork.rs
  crates/revm/src/executor.rs
  crates/revm/src/lib.rs
  crates/storage/provider/src/test_utils/executor.rs
  crates/storage/provider/src/test_utils/mod.rs
Labels: C-debt, A-execution

#2360 fix(provider): post state get didn't get receipts
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/provider/src/transaction.rs
Labels: C-bug, A-db

#2347 feat: add payload builder service metrics
  crates/payload/builder/Cargo.toml
  crates/payload/builder/src/lib.rs
  crates/payload/builder/src/metrics.rs
  crates/payload/builder/src/service.rs
Labels: C-enhancement, A-block-building, A-observability

#2352 chore(rpc): add missing eth filter traces
  crates/rpc/rpc/src/eth/filter.rs
Labels: A-rpc, A-observability

#2346 feat: add empty payload building support
  crates/payload/basic/src/lib.rs
  crates/payload/builder/src/service.rs
  crates/payload/builder/src/test_utils.rs
  crates/payload/builder/src/traits.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/error.rs
Labels: C-enhancement, A-block-building

#2363 chore(deps): bump Cargo.lock
  Cargo.lock
Labels: A-dependencies

#2355 fix: only write changed storage to changesets
  crates/revm/src/executor.rs
Labels: C-bug, A-execution

#2364 chore: dashboard updates
  etc/grafana/dashboards/overview.json
Labels: C-enhancement, A-observability

#2288 feat(trie): hashed cursor
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/post_state.rs
  crates/trie/src/hashed_cursor/default.rs
  crates/trie/src/hashed_cursor/mod.rs
  crates/trie/src/hashed_cursor/post_state.rs
  crates/trie/src/lib.rs
  crates/trie/src/trie.rs
Labels: C-enhancement, A-trie

#2372 feat: add missing pending block conversions
  crates/storage/provider/src/providers/mod.rs
Labels: A-rpc, A-db

#2367 feat: add payload build metrics
  Cargo.lock
  crates/payload/basic/Cargo.toml
  crates/payload/basic/src/lib.rs
  crates/payload/basic/src/metrics.rs
  crates/payload/builder/src/metrics.rs
Labels: A-block-building, A-observability

#2374 perf(trie): reuse `buf` for rlp encoding on `HashBuilder`
  bin/reth/src/stage/mod.rs
  crates/trie/src/hash_builder.rs
  crates/trie/src/nodes/branch.rs
  crates/trie/src/nodes/extension.rs
  crates/trie/src/nodes/leaf.rs
  crates/trie/src/trie.rs
  crates/trie/src/trie_cursor/storage_cursor.rs
Labels: C-perf, A-trie

#2369 feat(cli): drop history stages
  bin/reth/src/args/stage_args.rs
  bin/reth/src/drop_stage.rs
Labels: C-enhancement, A-cli

#2382 chore: remove default todo! impl
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/state.rs
Labels: C-debt
