Repository paradigmxyz/reth, pull requests merged in 2023-03, with the labels that each got.

#1530 test: fix hive tests
  Cargo.lock
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/genesis.rs
Labels: C-test

#1497 perf: bench merkle stage
  bin/reth/src/dump_stage/merkle.rs
  bin/reth/src/dump_stage/mod.rs
  crates/interfaces/Cargo.toml
  crates/interfaces/src/test_utils/generators.rs
  crates/primitives/src/storage.rs
  crates/stages/benches/criterion.rs
  crates/stages/benches/setup/account_hashing.rs
  crates/stages/benches/setup/mod.rs
  crates/stages/src/lib.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/test_utils/test_db.rs
  crates/stages/src/trie/mod.rs
  crates/storage/db/benches/utils.rs
Labels: C-bug, A-staged-sync, C-perf

#1591 Implement Decodable for TransactionSignedEcRecovered
  crates/primitives/src/transaction/mod.rs
Labels: C-debt, A-utils

#1598 chore: bump ethers
  Cargo.lock
  deny.toml
Labels: A-dependencies

#1601 fix(rpc): make exp claim optional
  crates/rpc/rpc/src/layers/auth_layer.rs
  crates/rpc/rpc/src/layers/jwt_secret.rs
Labels: A-rpc

#1596 feat(rpc): integrate eth cache and task executor in pipeline
  Cargo.lock
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/node/mod.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/cache.rs
  crates/rpc/rpc/src/eth/mod.rs
  crates/rpc/rpc/src/lib.rs
  crates/tasks/src/lib.rs
Labels: C-enhancement, A-rpc

#1604 chore(deps): rm unused deps in primitives
  Cargo.lock
  crates/primitives/Cargo.toml
Labels: A-dependencies

#1607 chore: expose methods and structs
  bin/reth/src/cli.rs
  bin/reth/src/dirs.rs
  crates/stages/src/stages/headers.rs
Labels: A-meta

#1605 feat(rpc): Add RpcModuleConfig and integrate in builder
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/cache.rs
  crates/rpc/rpc/src/eth/pubsub.rs
Labels: C-enhancement, A-rpc

#1610 chore: `get_evm_evn` -> `get_evm_env`
  crates/rpc/rpc/src/eth/cache.rs
Labels: C-debt, A-rpc

#1599 feat(rpc): impl eth_estimate
  Cargo.lock
  crates/primitives/src/constants.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/error.rs
Labels: C-enhancement, A-rpc

#1611 chore: remove unused config table
  crates/storage/db/src/tables/mod.rs
Labels: C-debt, A-db

#1612 feat(rpc): impl eth_call
  crates/rpc/rpc/src/eth/api/call.rs
Labels: C-enhancement, A-rpc

#1577 Support soft limit in NewPooledTransactions
  crates/net/network/src/transactions.rs
Labels: A-devp2p, A-networking

#1622 chore: add spawn_critical function to trait
  crates/tasks/src/lib.rs
Labels: C-enhancement

#1620 feat: add derive contract address functions
  crates/primitives/src/contract.rs
  crates/primitives/src/lib.rs
Labels: C-enhancement

#1616 fix: use correct serde impl for Withdrawal
  crates/primitives/src/lib.rs
  crates/primitives/src/serde_helper/jsonu256.rs
  crates/primitives/src/serde_helper/mod.rs
  crates/primitives/src/withdrawal.rs
Labels: C-bug, A-rpc

#1615 perf: improve initial pooled tx exchange
  crates/net/network/src/transactions.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/validate.rs
Labels: C-debt, A-networking

#1621 fix(disc): trigger bootstrap if table empty
  crates/net/discv4/src/lib.rs
Labels: C-bug, A-discv4

#1626 style: take ownership of header arg
  crates/net/downloaders/src/bodies/test_utils.rs
  crates/net/eth-wire/src/types/blocks.rs
Labels: C-debt

#1624 chore: reexport revm create address
  crates/primitives/src/contract.rs
Labels: C-debt

#1627 chore: drop tokio rt on separate thread
  bin/reth/src/runner.rs
Labels: C-debt

#1629 perf: allocate ping buffer and move to standalone function
  crates/net/eth-wire/src/p2pstream.rs
Labels: C-debt, A-networking

#1635 chore: add From bytes::Bytes impl
  crates/primitives/src/hex_bytes.rs
Labels: C-debt

#1634 feat(rpc): support eth_call state overrides
  crates/rpc/rpc-api/src/eth.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-types/src/eth/state.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/error.rs
Labels: C-enhancement, A-rpc

#1633 chore: spawn cache task as critical
  crates/rpc/rpc/src/eth/cache.rs
Labels: A-rpc

#1628 test: add empty decode buffer check
  crates/net/eth-wire/src/p2pstream.rs
  crates/storage/codecs/derive/src/arbitrary.rs
Labels: C-test

#1623 test: add test for display help
  bin/reth/src/cli.rs
  bin/reth/src/node/mod.rs
Labels: C-test, A-cli

#1639 chore: add tx type constants
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/tx_type.rs
Labels: C-debt

#1637 chore(deps): cargo update
  Cargo.lock
Labels: A-dependencies

#1638 ci: no longer pin nightly version
  .github/workflows/sanity.yml
Labels: C-debt

#1643 fix(txpool): queued tx ordering
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/transaction.rs
Labels: C-bug, A-tx-pool

#1645 docs(txpool): minor fixes
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-docs, A-tx-pool

#1649 chore(txpool): expose `PooledTransaction`
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/traits.rs
Labels: C-debt, A-tx-pool

#1651 chore(txpool): expose underlying tx
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#1650 perf(provider): remove redundant lookup
  crates/storage/provider/src/providers/mod.rs
Labels: C-perf, A-db

#1657 chore: add InvalidChainId error variant
  Cargo.lock
  crates/rpc/rpc/src/eth/error.rs
Labels: C-debt, A-rpc

#1658 chore(rpc): match all error variants
  crates/rpc/rpc/src/eth/error.rs
Labels: C-debt, A-rpc

#1646 bug: Remove old account/storage root in merkle trie
  crates/storage/provider/src/trie/mod.rs
Labels: C-bug, A-staged-sync

#1660 fix(net): enforce soft limit when propagating tx hashes
  crates/net/eth-wire/src/types/broadcast.rs
  crates/net/network/src/transactions.rs
Labels: A-networking

#1663 chore(executor): reuse revm hashmap
  Cargo.lock
  crates/executor/Cargo.toml
  crates/executor/src/executor.rs
Labels: C-debt, A-execution

#1652 feat(rpc): add `eth_createAccessList` implementation
  Cargo.lock
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/access_list.rs
  crates/primitives/src/transaction/mod.rs
  crates/revm/Cargo.toml
  crates/revm/src/lib.rs
  crates/rpc/rpc-api/src/eth.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-types/src/eth/log.rs
  crates/rpc/rpc-types/src/eth/transaction/mod.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/storage/provider/src/providers/mod.rs
Labels: C-enhancement, A-rpc

#1671 docs(txpool): clarify ParkedPool transaction type
  crates/transaction-pool/src/pool/parked.rs
Labels: C-docs, A-tx-pool

#1670 feat: add `debug-fast` profile
  Cargo.toml
Labels: C-enhancement, A-meta

#1672 feat: ExecutorFactory
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/chain/import.rs
  bin/reth/src/dump_stage/execution.rs
  bin/reth/src/dump_stage/merkle.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/mod.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/executor/src/executor.rs
  crates/executor/src/factory.rs
  crates/executor/src/lib.rs
  crates/interfaces/src/executor.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/stages/Cargo.toml
  crates/stages/src/lib.rs
  crates/stages/src/sets.rs
  crates/stages/src/stages/execution.rs
  crates/storage/db/benches/utils.rs
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/traits/executor.rs
  crates/storage/provider/src/traits/mod.rs
Labels: C-enhancement, A-execution

#1673 chore: add from u256 impl to JsonU256
  crates/primitives/src/serde_helper/jsonu256.rs
Labels: C-debt

#1640 feat: persist contract analysis in db
  Cargo.lock
  bin/reth/src/test_eth_chain/runner.rs
  crates/executor/src/executor.rs
  crates/primitives/src/account.rs
  crates/primitives/src/lib.rs
  crates/revm/revm-primitives/src/env.rs
  crates/revm/revm-primitives/src/lib.rs
  crates/revm/src/database.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/stages/src/stages/execution.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/macros.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/state.rs
  crates/storage/provider/src/transaction.rs
Labels: A-staged-sync, C-perf, A-execution, A-db

#1654 fix(primitives): write withdrawal hash at genesis
  bin/reth/src/chain/init.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/constants.rs
  crates/primitives/src/genesis.rs
Labels: C-bug, A-utils

#1677 fix: return zero latestValidHash pre-merge
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-types/src/eth/engine.rs
Labels: C-bug, A-consensus

#1681 fix(dep): update and lock revm
  Cargo.lock
  Cargo.toml
  crates/revm/revm-inspectors/src/stack.rs
Labels: A-dependencies

#1682 chore(deps): clean up `reth-stages` deps
  Cargo.lock
  crates/stages/Cargo.toml
Labels: A-dependencies

#1684 dep(revm): update
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#1685 chore: rm duplicate TxHashNumber entry
  bin/reth/src/db/mod.rs
Labels: C-debt

#1688 chore: replace lru with schnellru
  Cargo.lock
  crates/net/dns/Cargo.toml
  crates/net/dns/src/config.rs
  crates/net/dns/src/lib.rs
Labels: C-debt, C-perf

#1687 fix: serialize index as hex string
  Cargo.lock
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/eth/index.rs
Labels: A-rpc

#1690 chore(rpc): move EthRpcErrorCode to rpc-types
  crates/rpc/rpc-types/src/eth/error.rs
  crates/rpc/rpc-types/src/eth/mod.rs
  crates/rpc/rpc/src/eth/error.rs
Labels: C-debt, A-rpc

#1686 chore(rpc): add convenience from impl
  crates/rpc/rpc-types/src/eth/index.rs
Labels: A-rpc

#1683 chore(rpc): add required fields to Trace handler
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/trace.rs
Labels: A-rpc

#1618 feat: add Tracing inspector
  Cargo.lock
  crates/revm/revm-inspectors/Cargo.toml
  crates/revm/revm-inspectors/src/lib.rs
  crates/revm/revm-inspectors/src/stack/maybe_owned.rs
  crates/revm/revm-inspectors/src/stack/mod.rs
  crates/revm/revm-inspectors/src/tracing/arena.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
  crates/revm/revm-inspectors/src/tracing/utils.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/eth/trace/mod.rs
  crates/rpc/rpc-types/src/eth/trace/parity.rs
Labels: C-enhancement, A-rpc

#1694 chore: remove redundant handshake traces
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/p2pstream.rs
Labels: C-debt, A-observability

#1695 ci: delete project workflow
  .github/workflows/project.yml
Labels: C-debt, A-meta

#1697 refactor: extract transaction consensus errors to standalone type
  crates/consensus/src/beacon/beacon_consensus.rs
  crates/consensus/src/validation.rs
  crates/interfaces/src/consensus.rs
  crates/interfaces/src/error.rs
  crates/interfaces/src/p2p/error.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/network/src/import.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/error.rs
  crates/primitives/src/transaction/mod.rs
  crates/stages/src/error.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/test_utils/mod.rs
  crates/transaction-pool/src/validate.rs
Labels: C-debt

#1700 feat(rpc): add missing geth trace calls
  crates/rpc/rpc-api/src/debug.rs
  crates/rpc/rpc-types/src/eth/trace/common.rs
  crates/rpc/rpc-types/src/eth/trace/geth.rs
  crates/rpc/rpc-types/src/eth/trace/mod.rs
  crates/rpc/rpc-types/src/eth/trace/parity.rs
  crates/rpc/rpc/src/debug.rs
Labels: C-enhancement, A-rpc

#1702 fix(txpool): track promoted transactions
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-bug, A-tx-pool

#1703 chore(txpool): delete unused `removed` updates
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-debt, A-tx-pool

#1664 feat(rpc): `eth_transactionBy` impls
  crates/primitives/src/transaction/signature.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-types/src/eth/transaction/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-enhancement, A-rpc

#1710 chore(clippy): make clippy happy
  bin/reth/src/node/mod.rs
  bin/reth/src/p2p/mod.rs
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/test_utils.rs
  crates/net/dns/src/query.rs
  crates/net/downloaders/src/bodies/task.rs
  crates/net/downloaders/src/headers/task.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/src/transactions.rs
  crates/stages/src/pipeline/mod.rs
Labels: C-debt

#1706 refactor(sync): td stage consensus checks
  bin/reth/src/chain/import.rs
  bin/reth/src/node/mod.rs
  crates/stages/src/sets.rs
  crates/stages/src/stages/total_difficulty.rs
Labels: A-staged-sync, C-debt, A-consensus

#1562 feat: Implement is_syncing subscription handler
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc/src/eth/pubsub.rs
Labels: C-enhancement, A-rpc

#1716 fix(executor): reset access list
  crates/revm/revm-primitives/src/env.rs
Labels: C-bug, A-execution

#1714 chore(executor): add tx hash to evm error
  crates/executor/src/executor.rs
  crates/interfaces/src/executor.rs
Labels: A-execution

#1721 feat(rpc): add EthSubscriptionIdProvider
  crates/rpc/ipc/src/server/mod.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/eth/id_provider.rs
  crates/rpc/rpc/src/eth/mod.rs
  crates/rpc/rpc/src/lib.rs
Labels: A-rpc

#1718 bug: Increment transition_id if block changeset is present
  crates/storage/provider/src/transaction.rs
Labels: C-bug, A-staged-sync

#1727 docs: add api handler docs
  crates/rpc/rpc/src/trace.rs
Labels: C-docs

#1731 chore: rename trace handler functions
  crates/rpc/rpc-api/src/trace.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-debt, A-rpc

#1733 chore(txpool): remove Arc for internals
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/test_utils/mod.rs
  crates/transaction-pool/src/test_utils/pool.rs
Labels: C-debt, A-tx-pool

#1735 feat: add ReceiptProvider
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/mod.rs
  crates/storage/provider/src/traits/receipts.rs
Labels: C-enhancement, A-db

#1737 chore(docs): add method name to RPC handler implementation
  crates/rpc/rpc/src/admin.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/engine/mod.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/pubsub.rs
  crates/rpc/rpc/src/net.rs
  crates/rpc/rpc/src/web3.rs
Labels: C-docs

#1711 style(rpc): some transaction by touch ups
  crates/primitives/src/transaction/mod.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-debt, A-rpc

#1738 chore: add ReceiptProvider trait bound
  crates/storage/provider/src/traits/block.rs
Labels: C-enhancement, A-db

#1739 fix: default to correct ws port in rpc server args
  bin/reth/src/args/rpc_server_args.rs
Labels: C-bug, A-rpc

#1736 style: get rid of some else branches
  crates/storage/provider/src/providers/mod.rs
Labels: C-debt

#1740 fix(rpc): use eth id provider for filter
  crates/rpc/rpc/src/eth/filter.rs
Labels: A-rpc

#1729 feat: add trace inspector config
  crates/revm/revm-inspectors/src/tracing/config.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
Labels: C-enhancement, A-rpc

#1515 feat(rpc): add partial `eth_getProof` implementation
  crates/executor/src/executor.rs
  crates/interfaces/src/provider.rs
  crates/primitives/src/account.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/stages/Cargo.toml
  crates/stages/src/stages/merkle.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/macros.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/state.rs
  crates/storage/provider/src/transaction.rs
  crates/storage/provider/src/trie/mod.rs
Labels: C-enhancement, A-rpc

#1656 fix(stages): add commit threshold to merkle stage v2
  Cargo.lock
  bin/reth/src/dump_stage/merkle.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/proofs.rs
  crates/stages/benches/setup/mod.rs
  crates/stages/src/stages/merkle.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/transaction.rs
  crates/storage/provider/src/trie/mod.rs
Labels: C-bug, A-staged-sync

#1747 fix(stages): clear pre-eip161 accounts
  crates/executor/src/executor.rs
  crates/storage/provider/src/execution_result.rs
Labels: C-bug, A-staged-sync, A-execution

#1748 chore(rpc): make async
  crates/rpc/rpc-api/src/trace.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-debt

#1749 style: resort trait impl order
  crates/primitives/src/transaction/mod.rs
Labels: C-debt

#1750 chore(txpool): add IntoRecoveredTransaction to PoolTransaction
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate.rs
Labels: A-rpc

#1751 feat(rpc): add eth transactions trait
  crates/rpc/rpc-types/src/eth/transaction/mod.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/rpc/rpc/src/eth/mod.rs
Labels: A-rpc

#1741 feat(rpc): complete log filter
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/logs_utils.rs
  crates/rpc/rpc/src/eth/mod.rs
  crates/rpc/rpc/src/eth/pubsub.rs
Labels: A-rpc

#1752 chore(rpc): more trace prep
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/trace.rs
Labels: A-rpc

#1495 fix: use string instead of Vec<u8> for stageId.
  crates/stages/src/id.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/db/src/tables/models/mod.rs
  crates/storage/provider/src/providers/mod.rs
Labels: C-enhancement, A-db

#1212 feat: BlockchainTree
  Cargo.lock
  bin/reth/src/args/network_args.rs
  bin/reth/src/chain/import.rs
  bin/reth/src/chain/init.rs
  bin/reth/src/db/mod.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/p2p/mod.rs
  bin/reth/src/stage/mod.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/consensus/src/beacon/beacon_consensus.rs
  crates/consensus/src/beacon/builder.rs
  crates/executor/Cargo.toml
  crates/executor/src/blockchain_tree/block_indices.rs
  crates/executor/src/blockchain_tree/chain.rs
  crates/executor/src/blockchain_tree/mod.rs
  crates/executor/src/lib.rs
  crates/executor/src/substate.rs
  crates/interfaces/src/executor.rs
  crates/interfaces/src/provider.rs
  crates/net/network/src/config.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/block.rs
  crates/primitives/src/header.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/mod.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/staged-sync/src/utils/chainspec.rs
  crates/staged-sync/src/utils/init.rs
  crates/staged-sync/tests/sync.rs
  crates/stages/Cargo.toml
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/db/src/abstraction/common.rs
  crates/storage/db/src/abstraction/cursor.rs
  crates/storage/db/src/abstraction/database.rs
  crates/storage/db/src/implementation/mdbx/cursor.rs
  crates/storage/db/src/tables/models/blocks.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/execution_result.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/provider/src/test_utils/mod.rs
  crates/storage/provider/src/traits/account.rs
  crates/storage/provider/src/traits/block_hash.rs
  crates/storage/provider/src/transaction.rs
  crates/storage/provider/src/trie/mod.rs
  crates/storage/provider/src/utils.rs
Labels: C-enhancement, A-consensus

#1755 fix: make ChainState provider work for Box<dyn StateProvider>
  crates/executor/src/blockchain_tree/chain.rs
  crates/executor/src/blockchain_tree/mod.rs
  crates/storage/provider/src/providers/state/chain.rs
Labels: C-debt

#1665 feat(rpc): eth_sign*
  crates/interfaces/src/test_utils/generators.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/signature.rs
  crates/primitives/src/transaction/util.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/sign.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/rpc/rpc/src/eth/signer.rs
Labels: C-enhancement, A-rpc

#1521 feat: validate withdrawal when validating block.
  Cargo.lock
  crates/consensus/Cargo.toml
  crates/consensus/src/validation.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/traits/withdrawals.rs
Labels: C-enhancement, A-consensus

#1715 chore(deps): upgrade secp256k1+enr
  Cargo.lock
  bin/reth/Cargo.toml
  crates/interfaces/Cargo.toml
  crates/net/discv4/Cargo.toml
  crates/net/dns/Cargo.toml
  crates/net/dns/src/lib.rs
  crates/net/dns/src/tree.rs
  crates/net/ecies/Cargo.toml
  crates/net/eth-wire/Cargo.toml
  crates/net/network/Cargo.toml
  crates/primitives/Cargo.toml
  crates/revm/revm-primitives/Cargo.toml
  crates/rlp/Cargo.toml
  crates/staged-sync/Cargo.toml
  crates/storage/db/Cargo.toml
Labels: A-dependencies

#1725 Improve revm halt out of gas error handling
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/error.rs
Labels: A-rpc

#1763 feat(rpc): add with_state_at closure
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: A-rpc

#1761 fix: fix clippy and broken code
  crates/consensus/src/validation.rs
  crates/stages/benches/criterion.rs
  crates/stages/benches/setup/mod.rs
  crates/storage/db/benches/hash_keys.rs
  crates/storage/provider/src/transaction.rs
  crates/storage/provider/src/trie/mod.rs
Labels: C-debt

#1764 feat(cli): separate net dir
  bin/reth/src/dirs.rs
Labels: C-debt, A-cli

#1756 refactor(rpc): use ChainState type
  crates/primitives/src/block.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/state.rs
Labels: A-rpc

#1765 feat(rpc): impl parity trace_transaction
  crates/revm/revm-inspectors/src/tracing/arena.rs
  crates/revm/revm-inspectors/src/tracing/builder/geth.rs
  crates/revm/revm-inspectors/src/tracing/builder/mod.rs
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
  crates/revm/revm-primitives/src/env.rs
  crates/rpc/rpc-types/src/eth/trace/parity.rs
  crates/rpc/rpc-types/src/eth/transaction/common.rs
  crates/rpc/rpc-types/src/eth/transaction/mod.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-enhancement, A-rpc

#1767 chore(rpc): impl with_state_at closure
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: A-rpc

#1769 feat(rpc): impl trace_get
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/trace.rs
Labels: A-rpc

#1771 refactor(rpc): simplify state_at functions
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: A-rpc

#1760 chore(sync): blockchain tree config and externals
  crates/executor/src/blockchain_tree/block_indices.rs
  crates/executor/src/blockchain_tree/config.rs
  crates/executor/src/blockchain_tree/externals.rs
  crates/executor/src/blockchain_tree/mod.rs
Labels: A-blockchain-tree

#1779 chore(deps): remove unused deps
  Cargo.lock
  crates/stages/Cargo.toml
  crates/stages/benches/setup/mod.rs
Labels: C-debt, A-dependencies

#1780 chore(deps): bump aquamarine 0.3
  Cargo.lock
  crates/executor/Cargo.toml
  crates/net/network/Cargo.toml
  crates/stages/Cargo.toml
  crates/transaction-pool/Cargo.toml
Labels: C-docs, A-dependencies

#1775 chore(BlockchainTree): unwind function
  crates/executor/src/blockchain_tree/block_indices.rs
  crates/executor/src/blockchain_tree/mod.rs
Labels: C-enhancement, A-db, A-blockchain-tree

#1776 chore(provider): Added explanation for get_take ExecutionResult fn
  crates/storage/provider/src/transaction.rs
Labels: C-debt, A-db

#1786 fix(tree): vis of unwind block indices
  crates/executor/src/blockchain_tree/block_indices.rs
Labels: C-bug

#1790 fix(ci): downgrade nightly to `2023-03-14`
  .github/workflows/ci.yml
Labels: A-meta

#1792 feat(txpool): add EthTransactionValidator::new
  crates/transaction-pool/src/validate.rs
Labels: C-enhancement, A-tx-pool

#1796 chore: rearrange impl order
  crates/net/eth-wire/src/types/broadcast.rs
  crates/primitives/src/chain/mod.rs
  crates/primitives/src/genesis.rs
  crates/primitives/src/receipt.rs
  crates/rlp/src/encode.rs
  crates/rpc/rpc-types/src/eth/transaction/typed.rs
Labels: C-debt

#1797 docs: add some encode docs
  crates/rlp/src/encode.rs
Labels: C-docs

#1799 feat(rpc): enable eth_call eth_estimateGas
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/error.rs
Labels: A-rpc

#1798 feat(BcTree): return inserted block status Accepted/Valid/Disconnected
  crates/executor/src/blockchain_tree/block_indices.rs
  crates/executor/src/blockchain_tree/chain.rs
  crates/executor/src/blockchain_tree/mod.rs
Labels: C-enhancement, A-blockchain-tree

#1674 perf: write friendly `ExecutionResult`
  crates/executor/src/blockchain_tree/block_indices.rs
  crates/executor/src/blockchain_tree/chain.rs
  crates/executor/src/blockchain_tree/config.rs
  crates/executor/src/blockchain_tree/externals.rs
  crates/executor/src/blockchain_tree/mod.rs
  crates/executor/src/executor.rs
  crates/executor/src/lib.rs
  crates/executor/src/substate.rs
  crates/stages/src/stages/execution.rs
  crates/storage/provider/src/execution_result.rs
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/post_state.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/provider/src/traits/executor.rs
  crates/storage/provider/src/transaction.rs
Labels: C-perf, A-execution

#1800 fix(rpc): fallback to basefee when calculating fee fields
  crates/rpc/rpc-types/src/eth/call.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: C-bug, A-rpc

#1804 Issue 1770 move rlp impl for enr to discv4 crate
  crates/net/discv4/Cargo.toml
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/proto.rs
  crates/rlp/Cargo.toml
  crates/rlp/src/decode.rs
  crates/rlp/src/encode.rs
Labels: C-debt, A-discv4

#1795 feat: add canonical_headers_range
  Cargo.lock
  crates/executor/src/executor.rs
  crates/executor/src/substate.rs
  crates/net/network/src/eth_requests.rs
  crates/revm/src/database.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/macros.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/block_hash.rs
  crates/storage/provider/src/traits/block_id.rs
Labels: C-enhancement, A-rpc, A-db

#1807 ci: revert nightly downgrade
  .github/workflows/ci.yml
Labels: A-meta

#1808 fix(cli): tip number lookup
  bin/reth/src/node/mod.rs
Labels: C-bug, A-cli

#1813 chore: spawn engine api task as critical
  bin/reth/src/node/mod.rs
Labels: C-debt

#1811 feat: add int or hex serde parsers
  crates/primitives/src/serde_helper/mod.rs
  crates/primitives/src/serde_helper/num.rs
  crates/rpc/rpc-types/src/eth/trace/geth/mod.rs
Labels: C-enhancement, A-rpc

#1814 refactor: split consensus crate
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  bin/reth/src/chain/import.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/mod.rs
  crates/consensus/Cargo.toml
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/beacon_consensus.rs
  crates/consensus/beacon/src/builder.rs
  crates/consensus/beacon/src/lib.rs
  crates/consensus/common/Cargo.toml
  crates/consensus/common/src/lib.rs
  crates/consensus/common/src/validation.rs
  crates/consensus/src/beacon/mod.rs
Labels: C-debt

#1815 chore: cleanup some staged-sync deps
  Cargo.lock
  crates/staged-sync/Cargo.toml
  crates/staged-sync/src/lib.rs
  crates/staged-sync/src/test_utils/clique.rs
  crates/staged-sync/src/test_utils/mod.rs
  crates/staged-sync/src/utils/init.rs
Labels: C-debt

#1816 chore(deps): bump revm and use new utils
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc/src/eth/error.rs
Labels: A-dependencies

#1810 style: prefer `then_some` over `if else`
  bin/reth/src/test_eth_chain/runner.rs
  crates/executor/src/executor.rs
  crates/metrics/metrics-derive/tests/metrics.rs
  crates/revm/revm-primitives/src/compat.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/storage/provider/src/test_utils/mock.rs
Labels: A-meta

#1821 chore(deps): rm unused rlp dep
  Cargo.lock
  crates/rlp/Cargo.toml
Labels: A-dependencies

#1824 docs: `finish_transition` clarification
  crates/storage/provider/src/post_state.rs
Labels: C-docs

#1823 chore: small nits in executor from #1674
  crates/executor/src/executor.rs
Labels: C-debt

#1812 feat(rpc): port all geth tracing types
  Cargo.lock
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/eth/trace/geth/call.rs
  crates/rpc/rpc-types/src/eth/trace/geth/four_byte.rs
  crates/rpc/rpc-types/src/eth/trace/geth/mod.rs
  crates/rpc/rpc-types/src/eth/trace/geth/noop.rs
  crates/rpc/rpc-types/src/eth/trace/geth/pre_state.rs
  crates/rpc/rpc-types/test_data/call_tracer/default.json
  crates/rpc/rpc-types/test_data/call_tracer/legacy.json
  crates/rpc/rpc-types/test_data/call_tracer/only_top_call.json
  crates/rpc/rpc-types/test_data/call_tracer/with_log.json
  crates/rpc/rpc-types/test_data/pre_state_tracer/default.json
  crates/rpc/rpc-types/test_data/pre_state_tracer/diff_mode.json
  crates/rpc/rpc-types/test_data/pre_state_tracer/legacy.json
Labels: C-debt, A-rpc

#1827 feat: allow `--db` before or after subcommand
  bin/reth/src/db/mod.rs
Labels: C-enhancement, A-cli

#1828 ci: check that benchmarks compile
  .github/workflows/bench.yml
Labels: C-enhancement, C-test

#1832 perf(stages): use regular rayon spawn
  crates/stages/src/stages/sender_recovery.rs
Labels: A-staged-sync, C-perf

#1833 refactor: various cleanups
  crates/executor/src/blockchain_tree/chain.rs
  crates/executor/src/blockchain_tree/mod.rs
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/test_utils.rs
  crates/net/dns/src/query.rs
  crates/net/downloaders/src/bodies/request.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/nat/src/lib.rs
  crates/net/network/src/eth_requests.rs
  crates/net/network/src/fetch/mod.rs
  crates/primitives/src/block.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/net.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc/src/result.rs
  crates/storage/libmdbx-rs/src/cursor.rs
  crates/transaction-pool/src/identifier.rs
Labels: C-debt

#1834 perf: dynamically batch tx sender recovery
  crates/stages/src/stages/sender_recovery.rs
Labels: A-staged-sync, C-perf

#1835 chore: indent stuff in #1833
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-debt

#1829 feat: add mainnet timestamp for shanghai
  crates/primitives/src/chain/spec.rs
Labels: C-enhancement, A-consensus

#1839 chore(deps): rm some rlp deps
  Cargo.lock
  crates/rlp/Cargo.toml
  crates/rlp/rlp-derive/src/lib.rs
  crates/rlp/src/lib.rs
Labels: C-debt, A-dependencies

#1831 refactor(sync): header sync mode
  Cargo.lock
  bin/reth/src/chain/import.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/mod.rs
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/beacon_consensus.rs
  crates/consensus/beacon/src/builder.rs
  crates/consensus/beacon/src/lib.rs
  crates/interfaces/src/consensus.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/stages/src/lib.rs
  crates/stages/src/pipeline/builder.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/sets.rs
  crates/stages/src/stages/headers.rs
Labels: A-staged-sync, C-debt

#1841 chore(executor): extract test utils
  crates/executor/Cargo.toml
  crates/executor/src/blockchain_tree/mod.rs
  crates/executor/src/lib.rs
  crates/executor/src/test_utils/executor.rs
  crates/executor/src/test_utils/factory.rs
  crates/executor/src/test_utils/mod.rs
Labels: C-debt, A-execution

#1842 chore(pipeline): extract helper types to separate files
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/pipeline/progress.rs
  crates/stages/src/pipeline/sync_metrics.rs
Labels: A-staged-sync, C-debt

#1843 chore(blockchain_tree): wrap tree database in `Arc`
  crates/executor/src/blockchain_tree/externals.rs
  crates/executor/src/blockchain_tree/mod.rs
Labels: A-blockchain-tree

#1844 chore(pipeline): expose `TestStage` and add test stage set
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/test_utils/mod.rs
  crates/stages/src/test_utils/set.rs
  crates/stages/src/test_utils/stage.rs
Labels: A-staged-sync, C-test

#1772 feat(rpc): kickoff geth traces
  crates/revm/revm-inspectors/src/tracing/builder/geth.rs
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/revm/revm-inspectors/src/tracing/config.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/rpc/rpc-types/src/eth/trace/geth/call.rs
  crates/rpc/rpc-types/src/eth/trace/geth/mod.rs
  crates/rpc/rpc-types/src/eth/trace/geth/pre_state.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/rpc/rpc/src/result.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-enhancement, A-rpc
