Repository paradigmxyz/reth, pull requests merged in 2023-11, with the labels that each got.

#5262 fix: peek returns nth element from the top of the stack
  crates/revm/revm-inspectors/src/tracing/js/bindings.rs
Labels: C-bug, A-rpc

#5259 Update overview.json – fix description of "File descriptors" panel
  etc/grafana/dashboards/overview.json
Labels: A-observability

#5269 chore(tree): remove redundant BlockchainTree RethError variant
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/blockchain_tree/error.rs
  crates/interfaces/src/error.rs
Labels: C-debt, A-blockchain-tree

#5265 feat(rpc-testing-utils) : stream support for trace_get functionality
  crates/rpc/rpc-testing-util/src/trace.rs
Labels: C-test

#5199 feat(primitives): extended display and formatting for JsonU256
  crates/primitives/src/serde_helper/jsonu256.rs
  crates/primitives/src/serde_helper/mod.rs
  crates/rpc/rpc-types/src/serde_helpers/json_u256.rs
Labels: C-debt

#5240 feat: feature gate c-kzg in reth-primitives
  crates/primitives/Cargo.toml
  crates/primitives/src/constants/eip4844.rs
  crates/primitives/src/eip4844.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/eip4844.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/primitives/src/transaction/sidecar.rs
Labels: C-enhancement

#5243 feat(rpc): limit block_range by 100_000 per eth_getLogs request
  bin/reth/src/args/mod.rs
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/args/types.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/constants.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/mod.rs
Labels: M-changelog, A-rpc

#5153 fix: check payload length and consumed buf for pooled tx
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/primitives/src/transaction/sidecar.rs
Labels: C-bug, A-devp2p

#5270 docs: add an overview of the creation and querying of snapshots
  crates/snapshot/README.md
Labels: C-docs, A-snapshots

#5273 feat(rpc-types): Implement Clone for TraceFilter struct
  crates/rpc/rpc-types/src/eth/trace/filter.rs
Labels: A-rpc, C-test

#5238 Parse Genesis Value from Memory
  bin/reth/src/args/utils.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/lib.rs
Labels: C-enhancement, A-cli

#5271 feat: add --rpc.jwtsecret arg
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/cli/config.rs
  bin/reth/src/dirs.rs
  bin/reth/src/node/mod.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/layers/jwt_secret.rs
Labels: M-changelog, A-rpc, A-cli

#5276 chore: make BodiesDownloaderBuilder default equal to BodiesConfig
  crates/net/downloaders/src/bodies/bodies.rs
Labels: C-debt, A-downloaders

#5274 feat(tasks) : add docs
  crates/tasks/src/metrics.rs
Labels: C-docs

#5231 feat: implement providers for `SnapshotJarProvider`
  crates/interfaces/src/provider.rs
  crates/primitives/src/transaction/mod.rs
  crates/storage/db/src/snapshot/cursor.rs
  crates/storage/nippy-jar/src/cursor.rs
  crates/storage/provider/src/providers/snapshot/jar.rs
Labels: C-enhancement, A-snapshots

#5266 feat(tree): measure different parts of canonicalization
  Cargo.lock
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/metrics.rs
  crates/stages/src/pipeline/mod.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/providers/database/metrics.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/history.rs
Labels: C-enhancement, A-observability, A-blockchain-tree

#5264 perf: gc refs for js tracing
  crates/revm/revm-inspectors/src/tracing/js/bindings.rs
  crates/revm/revm-inspectors/src/tracing/js/builtins.rs
  crates/revm/revm-inspectors/src/tracing/js/mod.rs
Labels: M-changelog, C-perf, A-rpc

#5286 chore: add basic downloader empty response and exceeding limit tests
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/test_utils/bodies_client.rs
Labels: C-test, A-downloaders

#5290 fix: replace mainnet TTD so geth mainnet genesis parsing works
  bin/reth/src/args/utils.rs
  crates/primitives/src/chain/spec.rs
Labels: C-bug

#5275 feat(rpc-testing-utils) : enhanced tansaction replay
  crates/rpc/rpc-testing-util/tests/it/trace.rs
Labels: C-test

#5291 fix: `trace_filter` properly matches when `from_addresses` or `to_addresses` aren't set
  crates/rpc/rpc-types/src/eth/trace/filter.rs
Labels: A-rpc

#5307 chore(meta): add myself to .github CODEOWNERS
  CODEOWNERS
Labels: A-meta

#5308 fmt: format doc comments
  bin/reth/src/cli/components.rs
  bin/reth/src/dirs.rs
  crates/consensus/common/src/calc.rs
  crates/metrics/metrics-derive/src/lib.rs
  crates/net/discv4/src/lib.rs
  crates/net/dns/src/lib.rs
  crates/net/dns/src/resolver.rs
  crates/net/downloaders/src/bodies/task.rs
  crates/net/eth-wire/src/builder.rs
  crates/net/eth-wire/src/hello.rs
  crates/net/network/src/config.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/tests/it/clique/geth.rs
  crates/rpc/ipc/src/client.rs
  crates/rpc/ipc/src/server/mod.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-types/src/eth/filter.rs
  crates/rpc/rpc/src/layers/auth_layer.rs
  crates/rpc/rpc/src/layers/jwt_secret.rs
  crates/stages/src/lib.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/tasks/src/lib.rs
  crates/transaction-pool/src/lib.rs
  rustfmt.toml
Labels: C-debt

#5309 chore: drain fetching transaction events
  crates/net/network/src/transactions.rs
Labels: C-bug, A-networking

#5311 fix(ci): Integration Test Specify Reth Binary
  .github/workflows/integration.yml
Labels: A-meta

#5316 feat(primitives) : match exhaustive
  crates/primitives/src/transaction/tx_type.rs
Labels: C-debt

#5293 feat(rpc-testing-utils) : trace_filter test
  crates/rpc/rpc-testing-util/src/trace.rs
Labels: C-test

#5313 fix(payload): Ethereum Payload Builder Zero Type
  bin/reth/src/cli/ext.rs
  crates/payload/basic/src/lib.rs
  crates/payload/basic/src/optimism.rs
Labels: A-block-building

#5292 feat: add more beacon API types
  crates/rpc/rpc-types/src/beacon/constants.rs
  crates/rpc/rpc-types/src/beacon/events/attestation.rs
  crates/rpc/rpc-types/src/beacon/events/light_client_finality.rs
  crates/rpc/rpc-types/src/beacon/events/light_client_optimistic.rs
  crates/rpc/rpc-types/src/beacon/events/mod.rs
  crates/rpc/rpc-types/src/beacon/mod.rs
  crates/rpc/rpc-types/src/beacon/payload.rs
  crates/rpc/rpc-types/src/beacon/withdrawals.rs
  crates/rpc/rpc-types/src/eth/engine/beacon_api/mod.rs
  crates/rpc/rpc-types/src/eth/engine/mod.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
  crates/rpc/rpc-types/src/eth/mod.rs
  crates/rpc/rpc-types/src/eth/transaction/mod.rs
  crates/rpc/rpc-types/src/eth/withdrawal.rs
  crates/rpc/rpc-types/src/lib.rs
  crates/rpc/rpc-types/src/relay.rs
  examples/beacon-api-sse/src/main.rs
Labels: C-enhancement, A-rpc

#5324 feat(primitives): format stage progress with two decimal places
  crates/primitives/src/stage/checkpoints.rs
Labels: C-enhancement, A-staged-sync, A-observability

#5198 feat: add TransactionsHandle function
  crates/net/network/src/transactions.rs
Labels: C-enhancement, A-networking

#5327 chore: use u64 for payloadattributes directly
  bin/reth/src/debug_cmd/build_block.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/payload/builder/src/payload.rs
  crates/rpc/rpc-engine-api/src/payload.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
  crates/rpc/rpc-types/src/beacon/payload.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: C-debt

#5325 chore(primitives): Compact TxType Unit Table Test
  crates/primitives/src/transaction/tx_type.rs
Labels: C-test

#5331 docs: call many docs
  crates/rpc/rpc-types/src/eth/call.rs
Labels: C-debt, A-rpc

#5322 fix: use helper to deserialize mainnet TTD
  bin/reth/src/args/utils.rs
  crates/primitives/src/genesis.rs
  crates/rpc/rpc-types/src/serde_helpers/json_u256.rs
Labels: C-bug, C-debt

#5285 feat: downgrade trie debug logs to trace, cleanup debug logs more
  Cargo.toml
  bin/reth/src/cli/mod.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/payload/basic/Cargo.toml
  crates/payload/builder/Cargo.toml
  crates/primitives/src/trie/hash_builder/mod.rs
  crates/tasks/Cargo.toml
  crates/trie/src/trie.rs
Labels: C-enhancement, A-observability

#5339 fix: output field is called value
  crates/rpc/rpc-types/src/eth/call.rs
  crates/rpc/rpc/src/eth/api/call.rs
Labels: C-bug, A-rpc

#5340 docs: add docs about call order of config trait
  bin/reth/src/cli/ext.rs
Labels: C-docs

#5342 feat: add response type for execution header
  crates/rpc/rpc-types/src/beacon/payload.rs
Labels: A-rpc

#5345 chore: serde misc CallRequest
  crates/rpc/rpc-types/src/eth/call.rs
  crates/rpc/rpc-types/src/eth/transaction/request.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: A-rpc

#5338 feat(rpc): record call metrics per method
  crates/rpc/ipc/src/server/mod.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/src/metrics.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-enhancement, A-rpc, A-observability

#5344 fix: prevent decoding U256 TxValue on mainnet
  crates/primitives/src/transaction/tx_value.rs
Labels: C-bug, A-networking

#5350 feat: add established timestamp to peerinfo
  crates/net/network-api/src/lib.rs
  crates/net/network/src/session/handle.rs
Labels: A-networking

#5355 feat(bin): report freelist in `db stats`
  bin/reth/src/db/mod.rs
  crates/storage/libmdbx-rs/src/database.rs
Labels: C-enhancement, A-db, A-cli

#5354 feat: add trait for`NetworkEvents`
  bin/reth/src/cli/components.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/node/mod.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/network.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/src/transactions.rs
  crates/net/network/tests/it/big_pooled_txs_req.rs
  crates/net/network/tests/it/connect.rs
  crates/net/network/tests/it/geth.rs
  crates/net/network/tests/it/requests.rs
  crates/net/network/tests/it/session.rs
Labels: A-networking

#5351 feat: add for peers functions
  crates/net/network-api/src/lib.rs
  crates/net/network-api/src/noop.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/tests/it/connect.rs
  crates/rpc/rpc/src/admin.rs
Labels: C-enhancement, A-networking

#5358 feat(docs): MDBX freelist troubleshooting
  book/installation/build-for-arm-devices.md
  book/run/troubleshooting.md
Labels: C-docs, A-db

#5361 feat(rpc): measure request/call time in seconds
  crates/rpc/rpc-builder/src/metrics.rs
  etc/grafana/dashboards/overview.json
Labels: C-enhancement, A-rpc, A-observability

#5362 chore: support static str in capability
  crates/net/eth-wire/src/capability.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/hello.rs
  crates/net/network/tests/it/session.rs
Labels: C-enhancement

#5364 feat(engine): insert new payloads even when hook is running
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-enhancement, A-consensus

#5353 chore(meta): manifest maintenance
  Cargo.toml
  bin/reth/Cargo.toml
  crates/blockchain-tree/Cargo.toml
  crates/config/Cargo.toml
  crates/consensus/auto-seal/Cargo.toml
  crates/consensus/beacon/Cargo.toml
  crates/interfaces/Cargo.toml
  crates/metrics/Cargo.toml
  crates/net/common/Cargo.toml
  crates/net/discv4/Cargo.toml
  crates/net/dns/Cargo.toml
  crates/net/ecies/Cargo.toml
  crates/net/eth-wire/Cargo.toml
  crates/net/nat/Cargo.toml
  crates/net/network-api/Cargo.toml
  crates/net/network/Cargo.toml
  crates/payload/basic/Cargo.toml
  crates/primitives/Cargo.toml
  crates/prune/Cargo.toml
  crates/revm/Cargo.toml
  crates/rpc/ipc/Cargo.toml
  crates/rpc/rpc-api/Cargo.toml
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-testing-util/Cargo.toml
  crates/rpc/rpc-types-compat/Cargo.toml
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc/Cargo.toml
  crates/snapshot/Cargo.toml
  crates/stages/Cargo.toml
  crates/storage/db/Cargo.toml
  crates/storage/provider/Cargo.toml
  crates/tokio-util/Cargo.toml
  crates/transaction-pool/Cargo.toml
  crates/trie/Cargo.toml
  testing/ef-tests/Cargo.toml
Labels: A-meta

#5363 feat: support multiple shared caps
  crates/net/eth-wire/src/capability.rs
  crates/net/eth-wire/src/errors/p2p.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/eth-wire/src/types/message.rs
  crates/net/eth-wire/src/types/version.rs
  crates/net/network/src/error.rs
  crates/net/network/src/session/mod.rs
  examples/manual-p2p/src/main.rs
Labels: A-networking

#5366 chore: rm default features
  crates/rpc/rpc-testing-util/Cargo.toml
Labels: A-meta

#5365 docs: more shared cap docs
  crates/net/eth-wire/src/capability.rs
  crates/net/eth-wire/src/lib.rs
Labels: C-docs

#5368 fix: delete file with invalid name
  bin/reth/src/chain/import.rs:64:9
Labels: C-bug

#5367 chore: add blob subpool docs on add_transaction
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-docs, A-tx-pool

#5369 chore: fix a bunch of features
  crates/consensus/beacon/Cargo.toml
  crates/net/downloaders/Cargo.toml
  crates/net/network/Cargo.toml
  crates/payload/builder/Cargo.toml
  crates/primitives/Cargo.toml
  crates/primitives/src/transaction/mod.rs
  crates/rpc/rpc/Cargo.toml
  crates/stages/Cargo.toml
  crates/transaction-pool/Cargo.toml
Labels: C-debt

#5370 implement Stream for Discovery
  crates/net/network/src/discovery.rs
Labels: A-networking

#5371 feat: support hello message with protocols
  bin/reth/src/args/network_args.rs
  crates/net/eth-wire/src/builder.rs
  crates/net/eth-wire/src/capability.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/hello.rs
  crates/net/eth-wire/src/lib.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/eth-wire/src/protocol.rs
  crates/net/eth-wire/src/types/version.rs
  crates/net/network/src/config.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/tests/it/session.rs
Labels: A-networking

#5377 fix: use saturating mul for max response size bytes
  bin/reth/src/args/rpc_server_args.rs
Labels: C-bug

#5347 feat(rpc-testing-utils): implement trace_call streaming
  crates/rpc/rpc-testing-util/src/trace.rs
Labels: A-rpc, C-test

#5267 feat(rpc-builder): test requests params
  crates/rpc/rpc-builder/tests/it/http.rs
Labels: A-rpc, C-test

#5379 feat(bin) : max_values Macro for CLI args parsing
  bin/reth/src/args/types.rs
Labels: A-cli

#5383 fix: use SharedCapabilities
  crates/net/network/src/protocol.rs
Labels: A-networking

#5382 feat(rpc): add blob support for TransactionRequest
  crates/rpc/rpc-types/src/eth/transaction/request.rs
  crates/rpc/rpc-types/src/eth/transaction/typed.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: A-rpc

#5385 feat(`rpc-types`): from U64 for `BlockHashOrNumber` and `BlockId`
  crates/rpc/rpc-types/src/eth/block.rs
Labels: A-rpc

#5393 chore: support MaxU32 on more rpc args
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/args/types.rs
Labels: C-enhancement, A-cli

#5391 Feat/enable non namespaces
  bin/reth/src/args/rpc_server_args.rs
  crates/rpc/rpc-builder/src/lib.rs
Labels: A-cli

#5397 feat(bin) : refactor ZeroAsNone struct to a Macro
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/args/types.rs
  bin/reth/src/cli/mod.rs
Labels: A-cli

#5410 feat: changesetreader for mockethprovider
  crates/storage/provider/src/test_utils/mock.rs
Labels: C-test

#5411 meta: add @joshieDo to snapshot codeowners
  CODEOWNERS
Labels: A-meta

#5416 perf: reduce overhead with open state
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-perf

#5390 chore: add rlp codec for Sidecar
  crates/primitives/src/transaction/sidecar.rs
Labels: E-cancun

#5335 feat: add eviction ordering for blob transactions
  crates/transaction-pool/src/pool/blob.rs
Labels: C-enhancement, A-tx-pool

#5419 chore(state): `split_at` refactor
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/chain.rs
Labels: C-debt, A-blockchain-tree

#5329 feat(consensus): support test for `check_gas_limit` function
  crates/consensus/common/src/validation.rs
Labels: C-test

#5249 feat: share `SnapshotProvider` through `ProviderFactory`
  bin/reth/src/dirs.rs
  bin/reth/src/node/mod.rs
  crates/primitives/src/snapshot/mod.rs
  crates/snapshot/src/lib.rs
  crates/snapshot/src/snapshotter.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
Labels: C-enhancement, A-snapshots

#5389 feat: add on disk blob pool
  Cargo.lock
  Cargo.toml
  crates/consensus/beacon/Cargo.toml
  crates/net/dns/Cargo.toml
  crates/rpc/rpc/Cargo.toml
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/blobstore/disk.rs
  crates/transaction-pool/src/blobstore/mem.rs
  crates/transaction-pool/src/blobstore/mod.rs
Labels: C-enhancement, E-cancun

#5425 chore: decriptive panic on non-existing block indices
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
Labels: A-consensus, A-db

#5283 feat: add directory paths to `Snapshotter` and `SnapshotProvider`
  Cargo.lock
  bin/reth/src/db/snapshots/headers.rs
  bin/reth/src/db/snapshots/mod.rs
  bin/reth/src/db/snapshots/receipts.rs
  bin/reth/src/db/snapshots/transactions.rs
  bin/reth/src/node/mod.rs
  crates/interfaces/src/error.rs
  crates/primitives/src/fs.rs
  crates/primitives/src/snapshot/compression.rs
  crates/primitives/src/snapshot/filters.rs
  crates/primitives/src/snapshot/segment.rs
  crates/snapshot/Cargo.toml
  crates/snapshot/src/segments/mod.rs
  crates/snapshot/src/snapshotter.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
Labels: C-enhancement, A-snapshots

#5287 feat: `Snapshotter` triggers segment snapshots
  bin/reth/src/db/snapshots/headers.rs
  bin/reth/src/db/snapshots/receipts.rs
  bin/reth/src/db/snapshots/transactions.rs
  crates/primitives/src/snapshot/mod.rs
  crates/primitives/src/snapshot/segment.rs
  crates/snapshot/src/segments/headers.rs
  crates/snapshot/src/segments/mod.rs
  crates/snapshot/src/segments/receipts.rs
  crates/snapshot/src/segments/transactions.rs
  crates/snapshot/src/snapshotter.rs
Labels: C-enhancement, A-snapshots

#5433 chore: remove unnecessary async_trait usage
  crates/interfaces/src/consensus.rs
  crates/interfaces/src/test_utils/bodies.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/stages/src/test_utils/runner.rs
  crates/transaction-pool/src/test_utils/mod.rs
Labels: C-debt

#5435 chore(storage): rebuild MDBX if sources changed
  .gitignore
  crates/storage/libmdbx-rs/mdbx-sys/build.rs
Labels: A-db

#5436 chore: put env types into container type
  crates/storage/libmdbx-rs/src/environment.rs
Labels: C-debt

#5438 docs: fix spelling mistakes in eth-wire.md
  docs/crates/eth-wire.md
Labels: C-docs

#5437 refactor: transaction internals
  crates/storage/libmdbx-rs/src/cursor.rs
  crates/storage/libmdbx-rs/src/database.rs
  crates/storage/libmdbx-rs/src/transaction.rs
Labels: C-debt, A-db

#5439 feat: phase out environment trait
  bin/reth/src/db/diff.rs
  bin/reth/src/db/list.rs
  bin/reth/src/db/snapshots/bench.rs
  bin/reth/src/db/snapshots/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/lib.rs
  crates/storage/libmdbx-rs/benches/utils.rs
  crates/storage/libmdbx-rs/src/cursor.rs
  crates/storage/libmdbx-rs/src/database.rs
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/libmdbx-rs/src/error.rs
  crates/storage/libmdbx-rs/src/flags.rs
  crates/storage/libmdbx-rs/src/lib.rs
  crates/storage/libmdbx-rs/src/transaction.rs
  crates/storage/libmdbx-rs/tests/cursor.rs
  crates/storage/libmdbx-rs/tests/environment.rs
  crates/storage/libmdbx-rs/tests/transaction.rs
Labels: C-debt

#5373 feat: search for a snapshot that fulfills a queried `BlockHash` or `TxHash`
  bin/reth/src/db/snapshots/headers.rs
  bin/reth/src/db/snapshots/receipts.rs
  bin/reth/src/db/snapshots/transactions.rs
  crates/consensus/common/src/validation.rs
  crates/interfaces/src/provider.rs
  crates/primitives/src/snapshot/mod.rs
  crates/primitives/src/snapshot/segment.rs
  crates/snapshot/src/segments/mod.rs
  crates/snapshot/src/snapshotter.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
  crates/storage/provider/src/providers/snapshot/mod.rs
Labels: C-enhancement, A-snapshots

#5447 chore: make it harder to misuse raw pointers
  crates/storage/libmdbx-rs/benches/transaction.rs
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/libmdbx-rs/src/error.rs
  crates/storage/libmdbx-rs/src/transaction.rs
Labels: C-debt

#5448 fix(net): check bounds on message logging
  crates/net/eth-wire/src/ethstream.rs
Labels: C-bug, A-networking

#5441 chore: some blob reinject improvements
  crates/transaction-pool/src/blobstore/disk.rs
  crates/transaction-pool/src/blobstore/mem.rs
  crates/transaction-pool/src/blobstore/mod.rs
  crates/transaction-pool/src/blobstore/noop.rs
  crates/transaction-pool/src/blobstore/tracker.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool

#5451 feat(bin) : refactor auth_jwt_secret function
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/utils.rs
Labels: C-debt, A-cli

#5449 feat: add rpc-api trait for call bundle
  crates/rpc/rpc-api/src/bundle.rs
  crates/rpc/rpc-api/src/lib.rs
  crates/rpc/rpc/src/eth/bundle.rs
Labels: C-enhancement, A-rpc

#5450 feat(eth-wire): update docs
  crates/net/eth-wire/src/errors/eth.rs
Labels: C-docs

#5455 chore: more libmdbx cleanup
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/libmdbx-rs/src/error.rs
  crates/storage/libmdbx-rs/src/transaction.rs
Labels: C-debt, A-db

#5460 fix: fetch 4844 blob before reinjected reorged blob txs
  crates/net/network/src/transactions.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: C-bug, A-tx-pool

#5456 chore: make decode_enveloped args consistent with other fns
  crates/payload/builder/src/payload.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/optimism.rs
  crates/revm/src/optimism/mod.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: C-debt

#5465 feat: add eth-call-bundle module
  crates/rpc/rpc-builder/src/lib.rs
Labels: A-rpc, A-cli

#5457 chore: add optimism_deposit_tx_signature function
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/signature.rs
Labels: C-debt

#5470 feat(provider): `HeaderProvider::sealed_headers_while`
  crates/consensus/common/src/validation.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/snapshot/jar.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/header.rs
Labels: C-enhancement, A-db

#5473 chore(provider): migrate providers to `ProviderError`
  bin/reth/src/chain/import.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/debug_cmd/in_memory_merkle.rs
  bin/reth/src/debug_cmd/merkle.rs
  bin/reth/src/init.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/run.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/common/src/validation.rs
  crates/interfaces/src/blockchain_tree/error.rs
  crates/interfaces/src/error.rs
  crates/interfaces/src/provider.rs
  crates/payload/builder/src/error.rs
  crates/prune/src/segments/mod.rs
  crates/prune/src/segments/receipts.rs
  crates/revm/src/processor.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/cache/mod.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/result.rs
  crates/snapshot/src/segments/headers.rs
  crates/snapshot/src/segments/mod.rs
  crates/snapshot/src/segments/receipts.rs
  crates/snapshot/src/segments/transactions.rs
  crates/stages/src/error.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/test_utils/runner.rs
  crates/storage/db/src/snapshot/cursor.rs
  crates/storage/db/src/snapshot/generation.rs
  crates/storage/nippy-jar/src/error.rs
  crates/storage/provider/src/providers/bundle_state_provider.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/snapshot/jar.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
  crates/storage/provider/src/providers/snapshot/mod.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/macros.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/account.rs
  crates/storage/provider/src/traits/block.rs
  crates/storage/provider/src/traits/block_hash.rs
  crates/storage/provider/src/traits/block_id.rs
  crates/storage/provider/src/traits/evm_env.rs
  crates/storage/provider/src/traits/hashing.rs
  crates/storage/provider/src/traits/header.rs
  crates/storage/provider/src/traits/history.rs
  crates/storage/provider/src/traits/prune_checkpoint.rs
  crates/storage/provider/src/traits/receipts.rs
  crates/storage/provider/src/traits/stage_checkpoint.rs
  crates/storage/provider/src/traits/state.rs
  crates/storage/provider/src/traits/storage.rs
  crates/storage/provider/src/traits/transactions.rs
  crates/storage/provider/src/traits/withdrawals.rs
  crates/transaction-pool/src/maintain.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: C-debt

#5459 chore: `make maxperf`, enable GC profiling on MDBX debug
  Makefile
  crates/storage/libmdbx-rs/mdbx-sys/build.rs
Labels: A-db, A-observability, A-meta

#5468 feat: add benchmark for blob_tx_priority and fee_delta
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/benches/priority.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/pool/blob.rs
  crates/transaction-pool/src/pool/mod.rs
Labels: C-enhancement, A-tx-pool, C-benchmark

#5476 feat: get rid of cursor lifetime
  Cargo.lock
  crates/stages/src/stages/mod.rs
  crates/storage/db/src/implementation/mdbx/cursor.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/libmdbx-rs/Cargo.toml
  crates/storage/libmdbx-rs/benches/cursor.rs
  crates/storage/libmdbx-rs/src/codec.rs
  crates/storage/libmdbx-rs/src/cursor.rs
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/libmdbx-rs/src/transaction.rs
Labels: C-debt

#4636 refactor: split async/sync work in stages
  bin/reth/src/chain/import.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/debug_cmd/merkle.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/dump/execution.rs
  bin/reth/src/stage/dump/hashing_account.rs
  bin/reth/src/stage/dump/hashing_storage.rs
  bin/reth/src/stage/dump/merkle.rs
  bin/reth/src/stage/run.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/interfaces/src/provider.rs
  crates/stages/benches/criterion.rs
  crates/stages/benches/setup/mod.rs
  crates/stages/src/error.rs
  crates/stages/src/lib.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/sets.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/finish.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/mod.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/test_utils/runner.rs
  crates/stages/src/test_utils/stage.rs
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/header_sync_gap.rs
  crates/storage/provider/src/traits/mod.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: A-staged-sync, C-debt, M-prevent-stale

#5479 chore: make Cursor iterators depend on the cursor's lifetime
  crates/storage/libmdbx-rs/src/codec.rs
  crates/storage/libmdbx-rs/src/cursor.rs
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/libmdbx-rs/src/transaction.rs
Labels: C-debt

#5481 chore: clean up `Self: Sized` bounds
  crates/primitives/src/account.rs
  crates/primitives/src/stage/checkpoints.rs
  crates/primitives/src/storage.rs
  crates/primitives/src/trie/hash_builder/state.rs
  crates/primitives/src/trie/hash_builder/value.rs
  crates/primitives/src/trie/mask.rs
  crates/primitives/src/trie/nibbles.rs
  crates/primitives/src/trie/nodes/branch.rs
  crates/primitives/src/trie/storage.rs
  crates/primitives/src/trie/subnode.rs
  crates/rpc/rpc/src/result.rs
  crates/storage/codecs/src/lib.rs
  crates/storage/db/src/abstraction/mock.rs
  crates/storage/db/src/implementation/mdbx/cursor.rs
  crates/storage/db/src/tables/models/accounts.rs
  crates/storage/libmdbx-rs/src/codec.rs
Labels: C-debt

#5480 pipeline: error on missing buffer in online stages
  crates/stages/src/error.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/headers.rs
Labels: C-enhancement, A-staged-sync

#5472 chore(downloader): replace database with header provider
  Cargo.lock
  bin/reth/src/chain/import.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/run.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/interfaces/src/p2p/error.rs
  crates/net/downloaders/Cargo.toml
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/task.rs
  crates/net/downloaders/src/test_utils/file_client.rs
  crates/stages/src/lib.rs
  crates/stages/src/stages/bodies.rs
Labels: C-debt, A-downloaders

#5483 fix: track actually requested transactions
  crates/net/network/src/transactions.rs
Labels: C-bug, A-networking

#5484 chore(pipeline): stage poll extension trait
  Cargo.lock
  bin/reth/src/stage/run.rs
  crates/stages/Cargo.toml
  crates/stages/benches/criterion.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stage.rs
  crates/stages/src/test_utils/runner.rs
Labels: C-enhancement, A-staged-sync

#5487 chore(tree): minor `Chain` modifications
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/chain.rs
  crates/storage/provider/src/chain.rs
Labels: C-debt, A-blockchain-tree

#5485 feat(provider): `StateRootProvider::state_root_with_updates`
  Cargo.lock
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/chain.rs
  crates/revm/Cargo.toml
  crates/revm/src/processor.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/bundle_state/state_changes.rs
  crates/storage/provider/src/providers/bundle_state_provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/macros.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/state.rs
Labels: C-enhancement, A-db, A-trie

#5478 feat: get rid of lifetime GATs
  bin/reth/src/db/snapshots/bench.rs
  bin/reth/src/db/snapshots/headers.rs
  bin/reth/src/db/snapshots/receipts.rs
  bin/reth/src/db/snapshots/transactions.rs
  bin/reth/src/init.rs
  crates/prune/src/segments/account_history.rs
  crates/prune/src/segments/headers.rs
  crates/prune/src/segments/history.rs
  crates/prune/src/segments/mod.rs
  crates/prune/src/segments/receipts.rs
  crates/prune/src/segments/receipts_by_logs.rs
  crates/prune/src/segments/sender_recovery.rs
  crates/prune/src/segments/storage_history.rs
  crates/prune/src/segments/transaction_lookup.rs
  crates/prune/src/segments/transactions.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/snapshot/src/segments/headers.rs
  crates/snapshot/src/segments/mod.rs
  crates/snapshot/src/segments/receipts.rs
  crates/snapshot/src/segments/transactions.rs
  crates/snapshot/src/snapshotter.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/finish.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/mod.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/test_utils/stage.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/db/src/abstraction/common.rs
  crates/storage/db/src/abstraction/database.rs
  crates/storage/db/src/abstraction/mock.rs
  crates/storage/db/src/abstraction/transaction.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/lib.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/state.rs
  crates/trie/src/hashed_cursor/default.rs
  crates/trie/src/hashed_cursor/post_state.rs
  crates/trie/src/trie.rs
  docs/crates/db.md
Labels: C-debt, A-db

#5494 chore: preallocate buffer for rlp
  crates/primitives/src/transaction/mod.rs
Labels: C-perf

#5496 chore: add another module parser test
  bin/reth/src/args/rpc_server_args.rs
  crates/rpc/rpc-builder/src/lib.rs
Labels: C-test

#5507 chore: simplify clap next heading and use clap attribute
  bin/reth/src/args/database_args.rs
  bin/reth/src/args/debug_args.rs
  bin/reth/src/args/dev_args.rs
  bin/reth/src/args/gas_price_oracle_args.rs
  bin/reth/src/args/network_args.rs
  bin/reth/src/args/payload_builder_args.rs
  bin/reth/src/args/pruning_args.rs
  bin/reth/src/args/rollup_args.rs
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/args/txpool_args.rs
Labels: C-debt

#5508 chore: remove duplicate serde helpers
  crates/primitives/src/genesis.rs
  crates/primitives/src/serde_helper/mod.rs
  crates/primitives/src/serde_helper/num.rs
  crates/primitives/src/serde_helper/storage.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
  crates/rpc/rpc-types/src/lib.rs
  crates/rpc/rpc-types/src/serde_helpers/mod.rs
  crates/rpc/rpc-types/src/serde_helpers/num.rs
  crates/rpc/rpc-types/src/serde_helpers/u64_hex.rs
Labels: C-debt

#5500 feat: add get_block_transactions_ecrecovered
  crates/rpc/rpc/src/eth/cache/mod.rs
Labels: C-enhancement

#5513 fix(op-reth): clear accesslist for Deposit txs
  crates/primitives/src/revm/env.rs
Labels: C-bug, A-execution, A-op-reth

#5516 feat: add getters for tx by origin
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#5518 feat(bin): improve status logs
  bin/reth/src/chain/import.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/node/events.rs
  bin/reth/src/node/mod.rs
  crates/primitives/src/stage/checkpoints.rs
  crates/stages/src/pipeline/event.rs
  crates/stages/src/pipeline/mod.rs
Labels: C-enhancement, A-observability, A-cli

#5523 release: v0.1.0-alpha.11
  Cargo.lock
  Cargo.toml
Labels: A-meta

#5525 chore(deps): make c-kzg actually a feature of reth-primitives
  Cargo.toml
  crates/primitives/Cargo.toml
Labels: A-dependencies

#5530 test(provider): utility functions for initializing provider factory
  crates/storage/provider/src/test_utils/mod.rs
Labels: A-db, C-test

#5529 meta: fix release draft cmd
  .github/workflows/release.yml
Labels: A-meta

#5534 test(provider): instantiate provider with util function
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/snapshot/mod.rs
Labels: A-db, C-test

#5532 chore(sync): migrate pipeline to `ProviderFactory`
  bin/reth/src/chain/import.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/run.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/interfaces/src/p2p/error.rs
  crates/prune/src/segments/account_history.rs
  crates/prune/src/segments/headers.rs
  crates/prune/src/segments/receipts.rs
  crates/prune/src/segments/receipts_by_logs.rs
  crates/prune/src/segments/sender_recovery.rs
  crates/prune/src/segments/storage_history.rs
  crates/prune/src/segments/transaction_lookup.rs
  crates/prune/src/segments/transactions.rs
  crates/snapshot/src/snapshotter.rs
  crates/stages/benches/criterion.rs
  crates/stages/benches/setup/account_hashing.rs
  crates/stages/benches/setup/mod.rs
  crates/stages/src/lib.rs
  crates/stages/src/pipeline/builder.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/sets.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/finish.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/mod.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/test_utils/mod.rs
  crates/stages/src/test_utils/runner.rs
  crates/stages/src/test_utils/stage.rs
  crates/stages/src/test_utils/test_db.rs
Labels: A-staged-sync, C-debt

#5533 chore(execution): rename `EVMProcessor` factory
  bin/reth/src/chain/import.rs
  bin/reth/src/debug_cmd/build_block.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/debug_cmd/in_memory_merkle.rs
  bin/reth/src/debug_cmd/merkle.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/dump/execution.rs
  bin/reth/src/stage/dump/merkle.rs
  bin/reth/src/stage/run.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/revm/src/factory.rs
  crates/revm/src/lib.rs
  crates/stages/src/lib.rs
  crates/stages/src/sets.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/mod.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: C-debt, A-execution

#5517 feat: add graceful shutdown tasks
  bin/reth/src/node/mod.rs
  crates/tasks/src/lib.rs
  crates/tasks/src/shutdown.rs
Labels: C-enhancement, A-cli

#5535 test(trie): instantiate provider with util function
  crates/trie/Cargo.toml
  crates/trie/src/proof.rs
  crates/trie/src/trie.rs
  crates/trie/src/trie_cursor/account_cursor.rs
  crates/trie/src/trie_cursor/storage_cursor.rs
  crates/trie/src/walker.rs
Labels: C-test, A-trie

#5536 feat: add configure network function to cli ext
  bin/reth/src/cli/config.rs
  bin/reth/src/cli/ext.rs
  bin/reth/src/node/mod.rs
  crates/net/network/src/builder.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/protocol.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/swarm.rs
Labels: A-cli

#5413 feat: rlpx multiplexing
  crates/net/eth-wire/src/lib.rs
  crates/net/eth-wire/src/multiplex.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/eth-wire/src/test_utils.rs
  crates/net/network/src/protocol.rs
Labels: C-enhancement

#5543 feat: add NetworkProtocols trait
  bin/reth/src/cli/components.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
Labels: C-enhancement

#5545 chore: make fields pub
  crates/revm/revm-inspectors/src/tracing/arena.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: C-debt

#5549 chore: use rpc types Accesslist in inspector
  crates/primitives/src/transaction/access_list.rs
  crates/revm/revm-inspectors/src/access_list.rs
  crates/rpc/rpc-types-compat/src/log.rs
  crates/rpc/rpc-types-compat/src/transaction/mod.rs
  crates/rpc/rpc-types-compat/src/transaction/typed.rs
  crates/rpc/rpc/src/eth/api/call.rs
Labels: C-debt

#5548 chore: reuse alloy Log type
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: C-debt

#5541 feat: add find by offset functions
  crates/net/eth-wire/src/capability.rs
Labels: C-enhancement

#5552 chore: phase out reth-primitives from inspectors
  Cargo.lock
  crates/revm/revm-inspectors/Cargo.toml
  crates/revm/revm-inspectors/src/tracing/js/bindings.rs
  crates/revm/revm-inspectors/src/tracing/js/mod.rs
  crates/rpc/rpc/src/debug.rs
Labels: C-debt

#5556 Results to MockEthProvider
  crates/storage/provider/src/test_utils/mock.rs
Labels: C-test

#5557 chore(deps): bump alloy 0.5
  Cargo.lock
  Cargo.toml
  crates/net/ecies/src/codec.rs
  crates/primitives/src/lib.rs
Labels: A-dependencies

#5407 feat(rpc-testing-utils) : make replay transactions reponses comparaison in RpcComparer.
  crates/rpc/rpc-testing-util/Cargo.toml
  crates/rpc/rpc-testing-util/src/trace.rs
Labels: A-rpc, C-test

#5553 chore: some multiplex followup
  crates/net/eth-wire/src/capability.rs
  crates/net/eth-wire/src/multiplex.rs
  crates/net/eth-wire/src/p2pstream.rs
Labels: C-debt

#5469 feat: add metrics for best and resolved payloads
  crates/payload/builder/src/metrics.rs
  crates/payload/builder/src/service.rs
Labels: A-block-building, A-observability

#5464 feat: refactor generation of snapshots from the cli
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/db/snapshots/headers.rs
  bin/reth/src/db/snapshots/mod.rs
  bin/reth/src/db/snapshots/receipts.rs
  bin/reth/src/db/snapshots/transactions.rs
  crates/primitives/src/snapshot/segment.rs
  crates/snapshot/src/segments/headers.rs
  crates/snapshot/src/segments/mod.rs
  crates/snapshot/src/segments/receipts.rs
  crates/snapshot/src/segments/transactions.rs
  crates/snapshot/src/snapshotter.rs
  crates/storage/nippy-jar/src/filter/cuckoo.rs
  crates/storage/nippy-jar/src/filter/mod.rs
  crates/storage/nippy-jar/src/lib.rs
Labels: A-cli, A-snapshots

#5564 fix: use direct conversion for payload fee metrics
  crates/payload/builder/src/service.rs
Labels: C-debt, A-block-building

#5565 feat: add into_registry function
  crates/rpc/rpc-builder/src/lib.rs
Labels: C-enhancement

#5566 chore: export `StackSnapshotType`
  crates/revm/revm-inspectors/src/tracing/mod.rs
Labels: C-debt

#5568 feat: initial relay ssz support
  Cargo.lock
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/relay.rs
Labels: C-enhancement, A-rpc

#5574 docs: add panics section
  crates/primitives/src/block.rs
Labels: C-debt
