Repository paradigmxyz/reth, pull requests merged in 2023-02, with the labels that each got.

#1111 feat: introduce FileClient for importing blocks
  Cargo.lock
  crates/net/downloaders/Cargo.toml
  crates/net/downloaders/src/bodies/mod.rs
  crates/net/downloaders/src/lib.rs
  crates/net/downloaders/src/test_utils/file_client.rs
  crates/net/downloaders/src/test_utils/mod.rs
  crates/net/downloaders/src/test_utils/test_client.rs
Labels: C-enhancement, A-utils

#1112 chore(rpc): replace all todo! macros in rpc crate with rpc error responses
  crates/net/rpc/src/debug.rs
  crates/net/rpc/src/engine/mod.rs
  crates/net/rpc/src/eth/api/server.rs
  crates/net/rpc/src/trace.rs
Labels: C-debt, A-rpc

#1115 perf(net): use qualified types for headers client future
  bin/reth/src/p2p/mod.rs
  crates/interfaces/src/p2p/headers/client.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/network/src/fetch/client.rs
  crates/net/network/tests/it/requests.rs
Labels: A-networking

#1119 feat(consensus): beacon consensus builder
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/mod.rs
  crates/consensus/src/beacon/beacon_consensus.rs
  crates/consensus/src/beacon/builder.rs
  crates/consensus/src/beacon/mod.rs
  crates/interfaces/src/consensus.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/stages/src/stages/headers.rs
Labels: C-enhancement, A-consensus

#1124 docs(provider): More context about Stateprovider
  crates/storage/provider/src/traits/state.rs
Labels: C-docs, A-db

#1118 feat(rpc): add EthSigner trait
  Cargo.lock
  crates/net/rpc/Cargo.toml
  crates/net/rpc/src/eth/api/mod.rs
  crates/net/rpc/src/eth/mod.rs
  crates/net/rpc/src/eth/signer.rs
Labels: C-enhancement, A-rpc

#1134 fix(rpc): add mix hash
  crates/net/rpc-types/src/eth/block.rs
Labels: A-rpc

#1135 feat(rpc): impl accounts handler
  crates/net/rpc/src/eth/api/mod.rs
  crates/net/rpc/src/eth/api/server.rs
Labels: A-rpc

#1145 fix(download): body downloader flaky test
  crates/net/downloaders/src/bodies/bodies.rs
Labels: C-test, A-networking

#1136 feat(rpc): add basic state access functions
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/state.rs
Labels: C-enhancement, A-rpc

#1113 feat: implement headers for FileClient
  Cargo.lock
  crates/net/downloaders/Cargo.toml
  crates/net/downloaders/src/bodies/mod.rs
  crates/net/downloaders/src/bodies/test_utils.rs
  crates/net/downloaders/src/headers/mod.rs
  crates/net/downloaders/src/headers/test_utils.rs
  crates/net/downloaders/src/test_utils/file_client.rs
  crates/net/downloaders/src/test_utils/file_codec.rs
  crates/net/downloaders/src/test_utils/mod.rs
Labels: C-enhancement, A-networking, A-cli

#1150 feat: use MeteredSender for ActiveSession Sender Half
  Cargo.lock
  crates/metrics/common/src/metered_sender.rs
  crates/net/network/Cargo.toml
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/mod.rs
Labels: A-observability, A-networking

#1161 test(db): cursor write operations are working properly wherever cursor is
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: A-db, C-test

#1166 chore: restructure transaction impl order
  crates/primitives/src/transaction/mod.rs
Labels: C-debt

#1096 chore(execution): Refactor unused executor
  crates/executor/src/eth_dao_fork.rs
  crates/executor/src/execution_result.rs
  crates/executor/src/executor.rs
  crates/executor/src/lib.rs
  crates/executor/src/revm_wrap.rs
  crates/interfaces/src/executor.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/stages/src/stages/execution.rs
Labels: C-debt, A-execution

#994 feat(sync): `MerkleStage`
  Cargo.lock
  crates/interfaces/src/consensus.rs
  crates/interfaces/src/test_utils/generators.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/proofs.rs
  crates/primitives/src/storage.rs
  crates/rlp/src/encode.rs
  crates/stages/Cargo.toml
  crates/stages/src/db.rs
  crates/stages/src/lib.rs
  crates/stages/src/sets.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/test_utils/macros.rs
  crates/stages/src/test_utils/runner.rs
  crates/stages/src/trie/mod.rs
  crates/storage/db/src/abstraction/cursor.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/db/src/tables/mod.rs
Labels: C-enhancement, A-staged-sync

#1158 perf(net): increase default capacity for incoming messages
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/peers/mod.rs
  crates/net/network/src/session/config.rs
Labels: C-perf, A-networking

#1153 chore(net): emit message traces
  crates/net/network/src/session/active.rs
Labels: A-observability, A-networking

#1156 feat: format PoorError to mirror Geth's TxPool Error messages
  crates/rpc/rpc/src/eth/error.rs
Labels: C-enhancement, A-rpc

#1011 feat(net): add shutdown network signal
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/session/handle.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/swarm.rs
  crates/net/network/tests/it/connect.rs
Labels: C-enhancement, A-networking

#1152 chore(net): support multiple eth protocol versions.
  crates/net/network/src/session/mod.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/tests/it/main.rs
  crates/net/network/tests/it/session.rs
Labels: C-bug, A-networking

#1155 perf(net): add manual yield point
  crates/net/network/src/manager.rs
Labels: C-perf, A-networking

#1182 chore: add disable discovery options
  crates/net/network/src/config.rs
  crates/net/network/src/test_utils/testnet.rs
Labels: A-networking

#1177 chore(rpc): update forkchoice state in `fork_choice_updated` handler
  Cargo.lock
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/storage/provider/src/test_utils/mock.rs
Labels: C-enhancement, A-rpc

#1180 fix: consider empty headers response edge case
  crates/interfaces/src/p2p/error.rs
Labels: C-bug, A-networking

#1077 Configure RPC endpoints specific to transports
  crates/rpc/rpc-builder/src/lib.rs
Labels: C-enhancement, A-rpc

#1188 feat: add `db.commit` metric
  Cargo.lock
  crates/storage/db/Cargo.toml
  crates/storage/db/src/implementation/mdbx/tx.rs
Labels: C-enhancement, A-observability

#1178 chore(download): lower the buffer limit for bodies downloader
  crates/staged-sync/src/config.rs
Labels: C-perf, A-networking

#1193 chore: update Cargo.lock
  Cargo.lock
Labels: A-dependencies

#1169 feat: Add account_code helper function to AccountProvider
  crates/storage/provider/src/traits/state.rs
Labels: A-rpc, A-db

#1191 perf(net): backoff on incoming if channel at capacity
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/mod.rs
Labels: C-perf, A-networking

#1127 feat: JWT to authenticate external CL against Reth
  Cargo.lock
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/layers/auth_layer.rs
  crates/rpc/rpc/src/layers/jwt_secret.rs
  crates/rpc/rpc/src/layers/jwt_validator.rs
  crates/rpc/rpc/src/layers/mod.rs
  crates/rpc/rpc/src/lib.rs
Labels: C-enhancement, A-rpc

#1192 Fix transition id in storage hashing stage
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/test_utils/macros.rs
Labels: C-bug, A-staged-sync, C-perf

#1198 Impl state and account trait for NoopProvider
  crates/storage/provider/src/test_utils/noop.rs
Labels: A-db, C-test

#1185 metrics(download): out of order requests metric
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/downloaders/src/metrics.rs
Labels: A-observability, A-networking

#1128 feat: support time-based forking
  bin/reth/res/chainspec/goerli.json
  bin/reth/res/chainspec/mainnet.json
  bin/reth/res/chainspec/sepolia.json
  bin/reth/src/node/mod.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/consensus/src/beacon/beacon_consensus.rs
  crates/consensus/src/validation.rs
  crates/executor/src/config.rs
  crates/executor/src/executor.rs
  crates/interfaces/src/consensus.rs
  crates/interfaces/src/executor.rs
  crates/interfaces/src/p2p/headers/client.rs
  crates/interfaces/src/p2p/headers/downloader.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/eth-wire/src/builder.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/types/status.rs
  crates/net/network/src/config.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/session/mod.rs
  crates/primitives/src/chain/mod.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/forkid.rs
  crates/primitives/src/genesis.rs
  crates/primitives/src/hardfork.rs
  crates/primitives/src/header.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/proofs.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/staged-sync/src/utils/init.rs
  crates/staged-sync/tests/sync.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/test_utils/test_db.rs
  crates/stages/src/trie/mod.rs
  crates/storage/provider/src/utils.rs
Labels: C-enhancement, A-consensus, A-networking

#1200 fix(rpc): make NodeInfo behave as geth nodeInfo
  crates/net/network-api/src/lib.rs
  crates/primitives/src/jsonu256.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/net.rs
  crates/rpc/rpc-types/src/admin.rs
Labels: A-rpc, A-networking

#1201 chore(download): remove body download range recovery
  crates/interfaces/src/p2p/error.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/queue.rs
  crates/net/downloaders/src/bodies/task.rs
Labels: C-bug, C-perf, A-networking

#1205 fix: add serde feature to secp256k1 dep in discv4
  crates/net/discv4/Cargo.toml
Labels: A-discv4

#1204 feat(net): add test-utils and NoopNetwork
  crates/net/network-api/Cargo.toml
  crates/net/network-api/src/lib.rs
  crates/net/network-api/src/test_utils.rs
Labels: C-test, A-networking

#1203 feat(rpc): impl rpc-builder types
  Cargo.lock
  crates/rpc/rpc-api/src/lib.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-builder/tests/it/main.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/trace.rs
  crates/transaction-pool/src/test_utils/mod.rs
Labels: A-rpc, A-cli

#1210 feat(rpc): impl get code handler
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/error.rs
Labels: A-rpc

#1138 feat: gracefully disconnect incoming connections if at capacity
  Cargo.lock
  crates/net/network/Cargo.toml
  crates/net/network/src/session/mod.rs
  crates/net/network/src/swarm.rs
Labels: C-enhancement, A-networking

#1213 feat(cli): integrate rpc server
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/node/mod.rs
  crates/storage/provider/src/providers/mod.rs
Labels: A-rpc, A-cli

#1220 Test(rpc): Add Testing for EthApi RPC send raw transaction
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: A-rpc, A-tx-pool

#1222 test: basic rpc testing support
  Cargo.lock
  crates/rpc/rpc-api/src/admin.rs
  crates/rpc/rpc-api/src/lib.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc/src/admin.rs
Labels: A-rpc, C-test

#1229 feat(rpc): add Standard rpc module selection
  crates/rpc/rpc-builder/src/lib.rs
Labels: C-enhancement, A-rpc

#1228 fix(rpc): remove unused rpc transaction fields
  crates/rpc/rpc-types/src/eth/transaction/mod.rs
  crates/rpc/rpc-types/src/eth/transaction/signature.rs
Labels: C-debt, A-rpc

#1167 feat(cli): add persistent peers
  Cargo.lock
  bin/reth/src/dirs.rs
  bin/reth/src/lib.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/p2p/mod.rs
  bin/reth/src/stage/mod.rs
  crates/net/network/Cargo.toml
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/peers/mod.rs
  crates/staged-sync/src/config.rs
Labels: C-enhancement, A-networking, A-cli

#1233 add a test on incoming connections disconnect
  crates/net/network/tests/it/connect.rs
Labels: C-test, A-networking

#1227 Integrate RPC in CLI
  bin/reth/src/lib.rs
  bin/reth/src/node/mod.rs
  crates/rpc/rpc-builder/src/lib.rs
Labels: C-enhancement, A-rpc, A-cli

#1246 feat(rpc): add EthApiSpec to DebugApi
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/mod.rs
Labels: C-enhancement, A-rpc

#1245 feat: add encode_enveloped function
  crates/primitives/src/transaction/mod.rs
Labels: C-enhancement, A-rpc

#1251 chore: move StateProvider impls to state module
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/mod.rs
Labels: C-debt, A-db

#1252 fix: remove ctrl handling
  bin/reth/src/node/mod.rs
Labels: C-bug, A-cli

#1253 Update copyright year in MIT License
  LICENSE-MIT
Labels: C-debt

#1190 feat: init stage checkpoint metric
  Cargo.lock
  crates/stages/Cargo.toml
  crates/stages/src/id.rs
  crates/stages/src/pipeline/builder.rs
  crates/stages/src/pipeline/ctrl.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/pipeline/state.rs
Labels: C-enhancement, A-staged-sync, A-observability

#877 feat: add `reth init` and `reth import`
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/chain/import.rs
  bin/reth/src/chain/init.rs
  bin/reth/src/chain/mod.rs
  bin/reth/src/cli.rs
  bin/reth/src/lib.rs
  bin/reth/src/node/mod.rs
  crates/executor/src/executor.rs
  crates/net/downloaders/Cargo.toml
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/downloaders/src/test_utils/file_client.rs
  crates/primitives/src/chain/mod.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/lib.rs
  crates/staged-sync/Cargo.toml
  crates/staged-sync/src/config.rs
  crates/staged-sync/src/utils/chainspec.rs
Labels: C-enhancement, A-cli

#1130 perf(stages): Adds benchmark to `TransactionLookupStage`
  bin/reth/src/db/mod.rs
  crates/primitives/src/block.rs
  crates/primitives/src/header.rs
  crates/stages/benches/criterion.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/storage/db/Cargo.toml
  crates/storage/db/benches/hash_keys.rs
Labels: A-staged-sync, C-perf

#1258 fix(disc): initiate endpoint proof on ping
  crates/net/discv4/src/lib.rs
Labels: C-bug, A-discv4

#1226 refactor/perf: use rayon spawn for recovery jobs
  Cargo.lock
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/mod.rs
  crates/staged-sync/src/config.rs
  crates/stages/Cargo.toml
  crates/stages/benches/criterion.rs
  crates/stages/src/stages/mod.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/stream.rs
  docs/repo/crates/network.md
Labels: A-staged-sync, C-perf

#1261 chore: make clippy happy
  bin/reth/src/chain/import.rs
Labels: C-debt, A-cli

#1263 feat(primitives): rm RawBlockBody, use Block
  crates/net/downloaders/src/bodies/test_utils.rs
  crates/net/downloaders/src/test_utils/file_client.rs
  crates/net/downloaders/src/test_utils/file_codec.rs
  crates/net/eth-wire/src/types/blocks.rs
  crates/net/eth-wire/src/types/broadcast.rs
  crates/primitives/src/block.rs
Labels: C-debt, A-utils

#1239 feat: create primitive to rpc conversions
  Cargo.lock
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/signature.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/eth/block.rs
  crates/rpc/rpc-types/src/eth/transaction/mod.rs
  crates/rpc/rpc-types/src/eth/transaction/signature.rs
  crates/rpc/rpc/src/eth/api/block.rs
Labels: C-enhancement, A-rpc

#1260 chore: document parts of ECIES and MAC
  crates/net/ecies/src/algorithm.rs
  crates/net/ecies/src/mac.rs
Labels: C-docs, A-devp2p

#1266 ci: decrease proptest cases for `trie::arbitrary`
  crates/stages/src/trie/mod.rs
Labels: C-test

#1269 test(net): speedup network tests
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/tests/it/connect.rs
Labels: C-test, A-networking

#1270 feat: add scaffold impl of EthFilter API handler
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/mod.rs
  crates/rpc/rpc/src/eth/pubsub.rs
  crates/rpc/rpc/src/lib.rs
Labels: C-enhancement, A-rpc

#1249 feat: add ChainState type
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/state/chain.rs
  crates/storage/provider/src/providers/state/mod.rs
  crates/storage/provider/src/traits/state.rs
Labels: A-db, C-discussion

#1271 perf: reuse genesis hash
  crates/net/eth-wire/src/types/status.rs
Labels: C-perf

#1274 refactor: make SharableDatabase more relax
  bin/reth/src/node/mod.rs
  crates/staged-sync/src/config.rs
  crates/storage/db/src/abstraction/database.rs
  crates/storage/provider/src/providers/mod.rs
Labels: C-enhancement, A-db

#1248 chore: update revm to v3.0.0
  Cargo.lock
  crates/executor/Cargo.toml
  crates/executor/src/config.rs
  crates/executor/src/execution_result.rs
  crates/executor/src/executor.rs
  crates/executor/src/revm_wrap.rs
  crates/interfaces/Cargo.toml
  crates/interfaces/src/executor.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/lib.rs
  crates/rlp/Cargo.toml
  crates/rlp/src/decode.rs
  crates/rlp/src/encode.rs
  crates/storage/codecs/Cargo.toml
  crates/storage/codecs/src/lib.rs
Labels: A-dependencies

#1242 chore(db): remove block numhash key
  crates/interfaces/src/provider.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/test_utils.rs
  crates/staged-sync/src/utils/init.rs
  crates/stages/src/db.rs
  crates/stages/src/error.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/utils.rs
  docs/repo/crates/db.md
Labels: A-staged-sync, C-debt, A-db

#1276 Unify builder argument order
  bin/reth/src/chain/import.rs
  bin/reth/src/node/mod.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/downloaders/src/headers/task.rs
  crates/net/downloaders/src/test_utils/file_client.rs
  crates/stages/src/lib.rs
  crates/stages/src/stages/headers.rs
Labels: C-debt, A-networking

#1278 feat: impl Provider for ChainState type
  crates/storage/provider/src/providers/state/chain.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/macros.rs
Labels: C-enhancement, A-db

#1277 perf: move local_thread around ExecutionStage execute_inner
  crates/stages/src/stages/execution.rs
Labels: A-staged-sync, C-perf

#1250 refactor: move structs to args mod
  bin/reth/src/args/mod.rs
  bin/reth/src/args/network_args.rs
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/chain/import.rs
  bin/reth/src/chain/init.rs
  bin/reth/src/lib.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/p2p/mod.rs
  bin/reth/src/stage/mod.rs
Labels: C-debt, A-cli

#1238 chore: move Transaction container to reth_provider
  bin/reth/src/stage/mod.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/interfaces/src/provider.rs
  crates/stages/src/error.rs
  crates/stages/src/lib.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/test_utils/runner.rs
  crates/stages/src/test_utils/test_db.rs
  crates/stages/src/trie/mod.rs
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/transaction.rs
  crates/storage/provider/src/utils.rs
  docs/repo/crates/db.md
Labels: C-debt, A-db

#1209 feat: JWT secret lifecycle
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/cli.rs
  bin/reth/src/dirs.rs
  bin/reth/src/lib.rs
  bin/reth/src/node/mod.rs
  crates/rpc/rpc/src/layers/jwt_secret.rs
Labels: A-rpc, A-cli

#1284 feat: refactoring reth_methods() to return multiple Methods
  crates/rpc/rpc-builder/src/lib.rs
Labels: C-enhancement, A-rpc

#1291 chore(rpc): use consistent generic type order
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/pubsub.rs
Labels: C-debt, A-rpc

#1285 fix: chainspec ttd check
  crates/consensus/src/beacon/beacon_consensus.rs
  crates/executor/src/config.rs
  crates/executor/src/executor.rs
  crates/interfaces/src/consensus.rs
  crates/interfaces/src/p2p/bodies/response.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/network/src/config.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/header.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/storage/provider/src/utils.rs
Labels: C-bug

#1293 chore: new grafana dashboard
  etc/grafana/overview.json
Labels: C-enhancement, A-observability

#1292 feat(cli): integrate task manager and ctrl-c handling
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/cli.rs
  bin/reth/src/lib.rs
  bin/reth/src/main.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/runner.rs
Labels: C-enhancement, A-cli

#1286 test(disc): add wrong to test
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/test_utils.rs
Labels: C-test, A-discv4

#1241 feat: convert EthApiError to RpcError directly
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/error.rs
Labels: A-rpc

#1288 Test(rpc): Test support for different api modules
  Cargo.lock
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-types/src/eth/index.rs
Labels: A-rpc, C-test

#1303 chore(disc): add traces when node record added
  crates/net/discv4/src/lib.rs
Labels: A-observability, A-discv4

#1302 feat: extend task executor
  Cargo.lock
  crates/net/network/src/session/mod.rs
  crates/tasks/Cargo.toml
  crates/tasks/src/lib.rs
Labels: C-enhancement

#1310 test(net): add tracing to shutdown test
  crates/net/network/tests/it/connect.rs
Labels: C-test, A-networking

#1316 fix: compile errors on standalone txpool build
  crates/transaction-pool/src/traits.rs
Labels: C-debt, A-tx-pool

#1313 perf(sync): do not store empty ommers entries
  crates/primitives/src/header.rs
  crates/stages/src/stages/bodies.rs
  crates/storage/provider/src/utils.rs
Labels: A-staged-sync, C-perf

#1312 chore: stop logging jwt secret
  crates/rpc/rpc/src/layers/auth_layer.rs
  crates/rpc/rpc/src/layers/jwt_secret.rs
Labels: C-debt, A-rpc

#1319 bug: wipe storage only on selfdestruct
  crates/executor/src/executor.rs
Labels: C-bug, A-staged-sync, A-execution

#1314 cli: integrate TaskExecutor
  Cargo.lock
  bin/reth/src/args/network_args.rs
  bin/reth/src/dirs.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/p2p/mod.rs
  bin/reth/src/runner.rs
  bin/reth/src/stage/mod.rs
  crates/net/network/src/config.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/peers/manager.rs
  crates/staged-sync/Cargo.toml
  crates/staged-sync/src/config.rs
Labels: C-enhancement, A-cli

#1321 feat(rlp): support deriving optional fields
  crates/rlp/rlp-derive/src/de.rs
  crates/rlp/rlp-derive/src/en.rs
  crates/rlp/rlp-derive/src/lib.rs
  crates/rlp/rlp-derive/src/utils.rs
  crates/rlp/tests/rlp.rs
Labels: C-enhancement, A-utils

#1318 feat: add TaskSpawner trait
  crates/tasks/Cargo.toml
  crates/tasks/src/lib.rs
Labels: C-enhancement

#1186 Add TransactionSigned::decode_enveloped
  crates/primitives/src/transaction/mod.rs
Labels: C-enhancement, A-rpc

#1309 feat(storage): accept any `RangeBounds` to `walk_range`
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/trie/mod.rs
  crates/storage/db/src/abstraction/cursor.rs
  crates/storage/db/src/abstraction/mock.rs
  crates/storage/db/src/implementation/mdbx/cursor.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: C-enhancement, A-db

#1265 feat: add `reth dump-stage` command
  bin/reth/src/cli.rs
  bin/reth/src/db/mod.rs
  bin/reth/src/dump_stage/mod.rs
  bin/reth/src/lib.rs
  crates/stages/src/stages/execution.rs
  crates/storage/db/src/abstraction/database.rs
  crates/storage/db/src/abstraction/mock.rs
  crates/storage/db/src/abstraction/table.rs
  crates/storage/db/src/abstraction/transaction.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/tables/models/blocks.rs
  crates/storage/provider/src/transaction.rs
Labels: A-staged-sync, A-db, A-cli

#1330 ci: add sync ci job
  .github/workflows/ci.yml
Labels: A-staged-sync, C-test

#1331 feat(storage): make `Database::view` accept `FnOnce` instead of `FnMut`
  crates/storage/db/src/abstraction/database.rs
Labels: C-debt, A-db

#1334 fix(chainspec): cascading paris fork activation
  crates/primitives/src/chain/spec.rs
Labels: C-bug

#1341 chore: only log chain id and genesis
  bin/reth/src/chain/import.rs
  bin/reth/src/node/mod.rs
Labels: C-enhancement, A-cli

#1338 feat: add ChainEventSubscriptions trait
  crates/interfaces/src/events.rs
  crates/interfaces/src/lib.rs
Labels: C-enhancement, A-staged-sync, A-rpc

#1332 chore: add proptest-regressions to gitignore
  .gitignore
Labels: C-debt

#1337 test(net): speedup network tests
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/tests/it/session.rs
Labels: C-test, A-networking

#1339 ci: use matrix for sync job
  .github/workflows/ci.yml
Labels: C-debt, C-test

#1279 feat: add `Finish` stage
  bin/reth/src/args/network_args.rs
  bin/reth/src/chain/import.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/p2p/mod.rs
  bin/reth/src/stage/mod.rs
  crates/interfaces/src/p2p/headers/client.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/network/src/config.rs
  crates/primitives/src/chain/info.rs
  crates/staged-sync/src/config.rs
  crates/stages/src/lib.rs
  crates/stages/src/sets.rs
  crates/stages/src/stages/finish.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/mod.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/transaction.rs
Labels: C-enhancement, A-staged-sync

#1345 ci: split ci workflow
  .github/workflows/bench.yml
  .github/workflows/ci.yml
  .github/workflows/fuzz.yml
  .github/workflows/integration.yml
  .github/workflows/unit.yml
  docs/README.md
  docs/crates/README.md
  docs/crates/db.md
  docs/crates/discv4.md
  docs/crates/eth-wire.md
  docs/crates/network.md
  docs/crates/stages.md
  docs/repo/README.md
  docs/repo/ci.md
Labels: C-enhancement, C-test

#1346 fix(net): handle closed channel in Spawned downloader
  Cargo.lock
  bin/reth/src/chain/import.rs
  bin/reth/src/node/mod.rs
  crates/net/downloaders/Cargo.toml
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/task.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/downloaders/src/headers/task.rs
Labels: A-networking, A-cli

#1328 feat: add `reth dump-stage` command
  bin/reth/src/cli.rs
  bin/reth/src/db/mod.rs
  bin/reth/src/dump_stage/execution.rs
  bin/reth/src/dump_stage/hashing_storage.rs
  bin/reth/src/dump_stage/mod.rs
  bin/reth/src/lib.rs
  crates/stages/src/stages/execution.rs
  crates/storage/db/src/abstraction/database.rs
  crates/storage/db/src/abstraction/mock.rs
  crates/storage/db/src/abstraction/table.rs
  crates/storage/db/src/abstraction/transaction.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/tables/models/blocks.rs
  crates/storage/provider/src/transaction.rs
Labels: C-enhancement, A-staged-sync, A-db, A-cli

#1351 perf: use pre-computed genesis hash for known chains
  crates/primitives/src/chain/spec.rs
Labels: C-perf

#1349 ci: partition tests
  .github/workflows/integration.yml
  .github/workflows/unit.yml
Labels: C-enhancement, C-test

#1354 chore: make TaskSpawner dyncloneable
  Cargo.lock
  crates/tasks/Cargo.toml
  crates/tasks/src/lib.rs
Labels: C-enhancement

#1356 chore: integrate Boxed TaskSpawner
  bin/reth/src/node/mod.rs
  crates/net/network/src/config.rs
  crates/net/network/src/session/mod.rs
  crates/tasks/src/lib.rs
Labels: C-debt, A-networking

#1189 feat: more downloader metrics
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/downloaders/src/metrics.rs
Labels: C-enhancement, A-observability, A-networking

#1359 fix: don't mark ok tasks as panicked
  crates/tasks/src/lib.rs
Labels: C-bug, A-utils

#1360 feat: tell user that we are shutting down
  bin/reth/src/runner.rs
Labels: C-enhancement, A-cli

#1290 feat(rpc): work on subscriptions
  Cargo.lock
  crates/rpc/rpc-api/src/eth_pubsub.rs
  crates/rpc/rpc-types/src/eth/pubsub.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/pubsub.rs
Labels: C-enhancement, A-rpc

#1365 fix(download): propagate body request error
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/queue.rs
  crates/net/downloaders/src/bodies/request.rs
Labels: C-bug, A-networking

#1323 Split the http_ws_addr
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
Labels: C-enhancement, A-rpc

#1367 chore: change RpcServer build
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/http.rs
Labels: C-debt

#1366 fix(rlp): encode `None` optional fields as empty if any values left
  crates/rlp/rlp-derive/src/de.rs
  crates/rlp/rlp-derive/src/en.rs
  crates/rlp/rlp-derive/src/utils.rs
  crates/rlp/tests/rlp.rs
Labels: C-bug, A-utils

#1369 fix: handle closed download channel in headers downloader
  crates/net/downloaders/src/headers/reverse_headers.rs
Labels: C-bug, A-networking

#1370 fix(rpc): use rpc::BlockNumber type not u64
  crates/rpc/rpc-api/src/eth.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/server.rs
Labels: A-rpc

#1377 fix(disc): only initiate endpoint proof if insert was succesful
  crates/net/discv4/src/lib.rs
Labels: C-bug, A-discv4

#1375 fix(disc): add missing expiration checks on messages
  crates/net/discv4/src/lib.rs
Labels: C-bug, A-discv4

#1379 fix(stage): fatal channel closed error
  crates/stages/src/error.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/headers.rs
Labels: A-staged-sync, C-debt

#1376 chore(rpc): rename RpcModuleConfig --> RpcModuleSelection
  bin/reth/src/args/rpc_server_args.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
Labels: C-debt, A-rpc

#1364 fix: use `walk_range` on `import_table_with_range`
  crates/storage/db/src/abstraction/table.rs
Labels: C-bug, A-db, A-cli

#1362 fix: storage hashing stage gets stuck in a loop on big contracts
  bin/reth/src/dump_stage/hashing_storage.rs
  crates/stages/src/stages/hashing_storage.rs
Labels: C-bug, A-staged-sync

#1378 feat: make SubscriptionIdcompatible with client proc macro
  Cargo.lock
  crates/rpc/rpc-api/src/eth_filter.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/eth/filter.rs
  crates/rpc/rpc/src/eth/filter.rs
Labels: C-debt, A-rpc

#1380 chore(rpc): add more helper functions to modle regsitry
  crates/rpc/rpc-builder/src/lib.rs
Labels: C-enhancement, A-rpc

#1382 test: Hardfork
  crates/primitives/src/hardfork.rs
Labels: A-utils, C-test

#1237 feat: add native BlockId type and implement requiredCanonical field
  crates/primitives/src/block.rs
  crates/primitives/src/lib.rs
Labels: C-enhancement, A-utils

#1385 fix: return correct file client tip
  crates/net/downloaders/src/test_utils/file_client.rs
Labels: C-bug, A-devp2p, A-utils

#1357 feat: Add Shanghai on Sepolia
  crates/primitives/src/chain/spec.rs
Labels: C-enhancement, A-consensus

#1386 fix: use td from current head for status
  crates/net/eth-wire/src/types/status.rs
Labels: C-bug, A-devp2p

#1388 chore: add test for status init
  crates/net/eth-wire/src/types/status.rs
Labels: A-devp2p, C-test

#1390 fix: convert fuzz test names to snake case
  Cargo.lock
  crates/storage/codecs/derive/Cargo.toml
  crates/storage/codecs/derive/src/compact/generator.rs
  crates/storage/codecs/derive/src/compact/mod.rs
Labels: C-debt, A-utils

#1275 feat(rpc, storage): `eth_feeHistory` except `reward` field
  Cargo.lock
  crates/consensus/src/validation.rs
  crates/interfaces/src/db.rs
  crates/primitives/src/block.rs
  crates/rpc/rpc-api/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/eth/fee.rs
  crates/rpc/rpc-types/src/eth/mod.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/header.rs
Labels: C-enhancement, A-rpc

#1401 fix(disc): check insert result on neighbours response
  crates/net/discv4/src/lib.rs
Labels: C-bug, A-discv4

#1404 fix(disc): only answer FindNode if endpoint proof exists
  crates/net/discv4/src/lib.rs
Labels: C-bug, A-discv4

#1381 feat: add Error extension trait for `Result<Option<Block>>`
  crates/rpc/rpc/src/result.rs
Labels: C-enhancement, A-rpc

#1409 chore: `Header::seal` and `Header::seal_slow` distinction
  bin/reth/src/p2p/mod.rs
  bin/reth/src/test_eth_chain/models.rs
  crates/consensus/src/validation.rs
  crates/interfaces/src/test_utils/generators.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/request.rs
  crates/net/downloaders/src/bodies/test_utils.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/downloaders/src/headers/test_utils.rs
  crates/primitives/src/header.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/staged-sync/tests/sync.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/merkle.rs
Labels: C-debt

#1411 perf(disc): allow more FindNode failures
  crates/net/discv4/src/config.rs
  crates/net/discv4/src/lib.rs
Labels: C-perf, A-discv4

#1412 perf(disc): only remove node from table if its bucket is half full
  crates/net/discv4/src/lib.rs
Labels: C-perf, A-discv4

#1410 feat(engine-api): additional shanghai methods and types
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-types/src/eth/engine.rs
  crates/rpc/rpc/src/engine/mod.rs
Labels: C-enhancement, A-rpc

#1406 feat: allows to disable dns and discv4 discovery separately
  bin/reth/src/args/mod.rs
  bin/reth/src/args/network_args.rs
  bin/reth/src/p2p/mod.rs
  crates/net/network/src/config.rs
Labels: C-enhancement, A-cli
