Repository paradigmxyz/reth, pull requests merged in 2023-06, with the labels that each got.

#2920 chore(engine): ensure previous pipeline run finished
  bin/reth/src/node/mod.rs
  crates/consensus/beacon/src/engine/mod.rs
Labels: A-staged-sync, A-consensus

#2939 feat: track invalid ancestor in invalid headers cache
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-enhancement, A-consensus

#2910 feat(stages): sender recovery stage progress
  bin/reth/src/stage/drop.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/storage/db/src/tables/mod.rs
Labels: C-enhancement, A-staged-sync

#2948 chore: only log block essentials
  crates/blockchain-tree/src/shareable.rs
Labels: A-observability

#2945 fix: set reputation change for already seen txs to 0
  crates/net/network/src/peers/reputation.rs
Labels: A-networking

#2943 feat(stages): transaction lookup stage progress
  crates/stages/src/stages/tx_lookup.rs
Labels: C-enhancement, A-staged-sync

#2951 feat: add Transaction setters and separate random tx signing
  crates/interfaces/src/test_utils/generators.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-enhancement, A-utils, C-test

#2925 feat(stages): execution stage progress
  crates/primitives/src/stage/checkpoints.rs
  crates/primitives/src/stage/mod.rs
  crates/stages/src/pipeline/sync_metrics.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/storage/codecs/derive/src/compact/structs.rs
Labels: C-enhancement, A-staged-sync

#2928 feat(rpc): add rpc_ namespace
  crates/rpc/rpc-api/src/lib.rs
  crates/rpc/rpc-api/src/rpc.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-types/src/lib.rs
  crates/rpc/rpc-types/src/rpc.rs
  crates/rpc/rpc/src/lib.rs
  crates/rpc/rpc/src/rpc.rs
Labels: C-enhancement, A-rpc

#2959 chore: dont get plain state if not shard is there
  crates/storage/provider/src/providers/state/historical.rs
Labels: C-perf, A-db

#2960 fix: off by one unwind range
  bin/reth/src/stage/unwind.rs
Labels: C-bug

#2962 chore: typos, rm oudated todos
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/chain.rs
  crates/primitives/src/header.rs
Labels: C-debt

#2941 feat: improve block downloads
  crates/consensus/beacon/src/engine/forkchoice.rs
  crates/consensus/beacon/src/engine/message.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/interfaces/src/blockchain_tree/mod.rs
  crates/storage/provider/src/providers/state/historical.rs
Labels: A-consensus, A-blockchain-tree

#2963 chore(clippy): make clippy happy
  crates/rpc/rpc-types/src/rpc.rs
  crates/storage/provider/src/providers/state/historical.rs
Labels: C-debt

#2950 fix(stages): include block range in headers checkpoint
  crates/primitives/src/stage/checkpoints.rs
  crates/primitives/src/stage/mod.rs
  crates/stages/src/pipeline/sync_metrics.rs
  crates/stages/src/stages/headers.rs
Labels: C-bug, A-staged-sync

#2967 fix: clear active download requests if node fully synced
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-perf, A-consensus

#2874 ci: upgrade to geth 1.12.0-e501b3b0
  .github/workflows/integration.yml
  .github/workflows/sanity.yml
  Cargo.lock
  crates/net/eth-wire/Cargo.toml
  crates/net/network/Cargo.toml
  crates/primitives/Cargo.toml
  crates/rpc/rpc/Cargo.toml
  crates/staged-sync/Cargo.toml
  crates/staged-sync/src/test_utils/clique_middleware.rs
Labels: C-debt, A-meta

#2957 refactor(primitives, stages): make `EntitiesCheckpoint.total` non-optional
  crates/primitives/src/stage/checkpoints.rs
  crates/stages/src/pipeline/sync_metrics.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/tx_lookup.rs
Labels: A-staged-sync, C-debt

#2949 feat(stages): index history stages progress
  crates/primitives/src/stage/checkpoints.rs
  crates/primitives/src/stage/mod.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/pipeline/sync_metrics.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/provider/src/transaction.rs
Labels: C-enhancement, A-staged-sync

#2979 fix: push_trace iteratively
  crates/revm/revm-inspectors/src/tracing/arena.rs
Labels: C-debt, A-rpc

#2973 perf: only check pool if disk lookup came up empty
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: A-rpc

#2936 chore: percentage sync progress in Grafana dashboard
  etc/grafana/dashboards/overview.json
Labels: A-meta

#2977 chore: Better debug and json serialization for elias fano list
  bin/reth/src/db/get.rs
  crates/primitives/src/integer_list.rs
Labels: C-enhancement, A-cli

#2969 perf: use final paris difficulty if configured
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-perf, A-db

#2980 fix: process geth steps iteratively
  crates/revm/revm-inspectors/src/tracing/builder/geth.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: C-debt, A-rpc

#2968 fix: implement pending evm env
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/block.rs
Labels: C-enhancement, A-rpc

#2986 chore: test typo
  crates/blockchain-tree/src/block_buffer.rs
Labels: C-debt, C-test

#2984 refactor: move cli-only utils out of staged-sync
  bin/reth/src/args/mod.rs
  bin/reth/src/args/payload_builder_args.rs
  bin/reth/src/args/utils.rs
  bin/reth/src/chain/import.rs
  bin/reth/src/chain/init.rs
  bin/reth/src/db/mod.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/debug_cmd/merkle.rs
  bin/reth/src/dirs.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/p2p/mod.rs
  bin/reth/src/stage/drop.rs
  bin/reth/src/stage/dump/mod.rs
  bin/reth/src/stage/run.rs
  bin/reth/src/stage/unwind.rs
  bin/reth/src/utils.rs
  crates/staged-sync/src/utils/chainspec.rs
  crates/staged-sync/src/utils/mod.rs
Labels: C-debt, A-cli

#2978 bug(Tree): Commit from tree now calculates history indices
  crates/consensus/beacon/src/engine/mod.rs
  crates/storage/provider/src/transaction.rs
  crates/storage/provider/src/utils.rs
Labels: C-bug, A-db, A-blockchain-tree, S-breaking

#2982 feat: Better progress reporting for stage checkpoints
  bin/reth/src/args/stage_args.rs
  bin/reth/src/stage/drop.rs
  bin/reth/src/stage/run.rs
  crates/interfaces/src/db.rs
  crates/primitives/src/stage/checkpoints.rs
  crates/primitives/src/stage/mod.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/pipeline/sync_metrics.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/storage/codecs/derive/src/compact/structs.rs
  crates/storage/db/src/abstraction/mock.rs
  crates/storage/db/src/abstraction/transaction.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/libmdbx-rs/src/transaction.rs
  crates/storage/provider/src/transaction.rs
  crates/trie/src/progress.rs
  crates/trie/src/trie.rs
  etc/grafana/dashboards/overview.json
Labels: C-enhancement, A-staged-sync

#2961 chore(consensus): emit warnings if no CL found
  bin/reth/src/node/cl_events.rs
  bin/reth/src/node/events.rs
  bin/reth/src/node/mod.rs
  crates/consensus/beacon/src/engine/message.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/storage/provider/src/providers/chain_info.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/traits/chain_info.rs
Labels: A-observability, A-cli

#2985 ci: add docker release workflow
  .github/workflows/docker.yml
  Dockerfile.cross
  Makefile
Labels: A-meta

#2988 feat: rework logs
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/cli.rs
  bin/reth/src/utils.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/test_utils.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/task.rs
  crates/net/nat/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/swarm.rs
  crates/payload/builder/src/service.rs
  crates/rpc/ipc/src/server/mod.rs
  crates/rpc/rpc/src/eth/gas_oracle.rs
  crates/rpc/rpc/src/layers/jwt_validator.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/merkle.rs
  crates/tracing/src/lib.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/pool/mod.rs
Labels: A-cli

#2994 perf: use BTreeMap::pop_last
  crates/transaction-pool/src/pool/best.rs
Labels: C-debt

#2998 Update rust version from 1.65.0 to 1.70.0 in README.md
  README.md
Labels: C-docs, C-debt

#2844 feat: Increment history shard size
  crates/storage/db/src/tables/models/sharded_key.rs
  crates/storage/db/src/tables/models/storage_sharded_key.rs
Labels: A-db, S-breaking

#2952 fix: ignore forkchoice updates to old head
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/blockchain_tree/mod.rs
Labels: C-bug, A-consensus, C-test

#2999 fix(rpc): make memSize optional
  crates/revm/revm-inspectors/src/tracing/types.rs
  crates/rpc/rpc-types/src/eth/trace/geth/mod.rs
  crates/rpc/rpc-types/test_data/default/structlogs_01.json
Labels: C-bug, A-rpc

#3003 fix: mark downloaded block as invalid if insertion fails
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/blockchain_tree/error.rs
Labels: C-bug, A-consensus, C-test

#3004 fix(rpc): use u64 for gas
  crates/revm/revm-inspectors/src/tracing/builder/geth.rs
  crates/rpc/rpc-types/src/eth/trace/geth/mod.rs
  crates/rpc/rpc/src/debug.rs
Labels: A-rpc

#3005 chore(clippy): make clippy happy
  crates/rpc/rpc/src/layers/jwt_secret.rs
  crates/rpc/rpc/src/layers/jwt_validator.rs
Labels: C-debt

#3014 chore(db): fix dupsort typo
  crates/storage/db/src/tables/mod.rs
  crates/storage/db/src/tables/raw.rs
Labels: C-debt, A-db

#3012 fix(bin): skip first `ConsensusLayerHealthEvents` tick
  bin/reth/src/node/cl_events.rs
Labels: A-observability, A-cli

#3016 fix: serialize storage map without prefix
  Cargo.lock
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/eth/trace/geth/mod.rs
Labels: A-rpc

#3015 chore: add helper serialize functions
  crates/primitives/src/serde_helper/mod.rs
Labels: C-enhancement

#3017 chore(deps): use revm and revm-primitives as workspace deps
  Cargo.toml
  crates/interfaces/Cargo.toml
  crates/payload/basic/Cargo.toml
  crates/payload/builder/Cargo.toml
  crates/primitives/Cargo.toml
  crates/revm/Cargo.toml
  crates/revm/revm-inspectors/Cargo.toml
  crates/revm/revm-primitives/Cargo.toml
  crates/rlp/Cargo.toml
  crates/rpc/rpc/Cargo.toml
  crates/storage/codecs/Cargo.toml
Labels: A-dependencies

#3018 chore(deps): bump xml-rs to 0.8.14
  Cargo.lock
Labels: A-dependencies

#3020 fix(rpc): use correct rename
  crates/rpc/rpc-types/src/eth/trace/geth/mod.rs
Labels: A-rpc

#3021 chore: add TracingCallGuard::aquire-many
  crates/rpc/rpc/src/call_guard.rs
Labels: A-rpc

#3023 chore: increase default max response limit
  bin/reth/src/args/rpc_server_args.rs
Labels: A-rpc, A-cli

#3026 chore: dont set bad-function-cast warning on linux
  crates/storage/libmdbx-rs/mdbx-sys/build.rs
Labels: C-debt

#3024 fix(bin): log latest engine block if pipeline is idle
  bin/reth/src/node/events.rs
Labels: A-observability, A-cli

#3027 feat: add metrics for active block downloads
  crates/consensus/beacon/src/engine/metrics.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
Labels: A-consensus, A-observability

#3031 perf: only set fields if enabled
  crates/revm/revm-inspectors/src/tracing/builder/geth.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
  crates/rpc/rpc-types/src/eth/trace/geth/mod.rs
Labels: A-rpc

#2987 fix: exclude calls to precompiles in parity tracers
  Cargo.lock
  Cargo.toml
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/revm/revm-inspectors/src/tracing/config.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: C-bug, S-blocked, A-rpc

#3036 test: use free port
  crates/net/ecies/src/stream.rs
Labels: C-test

#2938 fix: unwind on execution and senders errors
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/blockchain_tree/error.rs
  crates/interfaces/src/executor.rs
  crates/interfaces/src/provider.rs
  crates/revm/src/executor.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/storage/provider/src/transaction.rs
Labels: A-staged-sync, C-debt, A-consensus, A-db

#3029 fix(storage): invalid stage checkpoints on unwind
  crates/storage/provider/src/transaction.rs
Labels: C-bug, A-staged-sync

#3013 feat(stages): normalized sender recovery commits
  crates/config/src/config.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/test_utils/test_db.rs
Labels: C-enhancement, A-staged-sync

#3010 feat(stages): bodies & TD progress
  bin/reth/src/args/stage_args.rs
  bin/reth/src/stage/drop.rs
  crates/primitives/src/chain/spec.rs
  crates/staged-sync/src/utils/init.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/total_difficulty.rs
Labels: C-enhancement, A-staged-sync

#3043 test: fix flaky shutdown test with race condition
  crates/net/network/tests/it/connect.rs
Labels: C-test, A-networking

#3042 fix: fix error types in recover_sender utility fn
  crates/stages/src/stages/sender_recovery.rs
Labels: C-bug, A-staged-sync

#3044 fix(autoseal): use higher difficulty and fix root calc
  bin/reth/src/node/mod.rs
  crates/consensus/auto-seal/src/task.rs
  crates/revm/src/executor.rs
Labels: C-bug, A-staged-sync, C-test

#3041 feat: support disable* fields
  crates/rpc/rpc-types/src/eth/trace/geth/mod.rs
Labels: A-rpc

#3054 chore: clarify gas field
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: C-debt, A-rpc

#3053 fix: use value of top trace for delegate call
  crates/revm/revm-inspectors/src/tracing/mod.rs
Labels: C-bug, A-rpc

#3049 feat(rpc): track gas remaining
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
  crates/rpc/rpc-types/src/eth/trace/parity.rs
Labels: A-rpc

#3045 chore: use new is_enabled functions
  crates/revm/revm-inspectors/src/tracing/builder/geth.rs
Labels: C-debt, A-rpc

#3063 fix: use gas limit for gas
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: A-rpc

#3065 fix: don't account for refunds after call
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/utils.rs
Labels: C-bug, A-rpc

#3055 chore(stages): cleanup execute/unwind logs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/stages/tx_lookup.rs
Labels: C-enhancement, A-staged-sync, A-observability

#3025 refactor(primitives): `stage_unit_checkpoints` macro
  crates/primitives/src/stage/checkpoints.rs
Labels: A-staged-sync, C-debt

#3071 fix: increase tokio thread stack size 8MB
  bin/reth/src/runner.rs
Labels: A-rpc

#3077 fix(bin): unwind CLI `to-block` behavior
  bin/reth/src/stage/unwind.rs
Labels: C-bug, A-cli

#3078 chore: replace todo with error
  crates/rpc/rpc/src/debug.rs
Labels: C-debt, A-rpc

#3084 Set namespace in one place
  crates/rpc/rpc-api/src/admin.rs
  crates/rpc/rpc-api/src/debug.rs
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-api/src/eth.rs
  crates/rpc/rpc-api/src/eth_filter.rs
  crates/rpc/rpc-api/src/eth_pubsub.rs
  crates/rpc/rpc-api/src/net.rs
  crates/rpc/rpc-api/src/rpc.rs
  crates/rpc/rpc-api/src/trace.rs
  crates/rpc/rpc-api/src/txpool.rs
  crates/rpc/rpc-api/src/web3.rs
Labels: A-rpc

#3008 fix(stages): check for empty block range and return previous checkpoint
  crates/stages/src/stage.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/stages/tx_lookup.rs
Labels: C-bug, A-staged-sync

#3080 feat: support block overrides
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-enhancement, A-rpc

#3083 perf: use cached reads across payload jobs
  crates/payload/basic/src/lib.rs
Labels: C-perf, A-block-building

#3085 chore: move extradata bytes to function
  bin/reth/src/args/payload_builder_args.rs
  bin/reth/src/node/mod.rs
Labels: A-cli

#3066 feat(stages): unwind on detached local head
  crates/consensus/common/src/validation.rs
  crates/interfaces/src/consensus.rs
  crates/interfaces/src/p2p/error.rs
  crates/interfaces/src/p2p/headers/downloader.rs
  crates/interfaces/src/p2p/headers/error.rs
  crates/interfaces/src/p2p/headers/mod.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/downloaders/src/headers/task.rs
  crates/net/downloaders/src/test_utils/file_client.rs
  crates/primitives/src/constants.rs
  crates/stages/src/error.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stages/headers.rs
Labels: C-enhancement, A-staged-sync

#3075 Put ChainsSpecs in Arc<>
  bin/reth/src/args/utils.rs
  bin/reth/src/stage/dump/execution.rs
  bin/reth/src/stage/dump/merkle.rs
  crates/net/network/src/config.rs
  crates/primitives/src/chain/spec.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/staged-sync/src/utils/init.rs
  crates/storage/provider/src/transaction.rs
Labels: C-debt

#3090 chore(clippy): make clippy happy
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/staged-sync/src/utils/init.rs
  crates/stages/src/lib.rs
  crates/stages/src/sets.rs
Labels: C-debt

#3096 feat(rpc): add `block_overrides` in `eth_call`
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-api/src/eth.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/engine.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: C-enhancement, A-rpc

#3070 docs: book pass + rpc chapter
  book/SUMMARY.md
  book/faq/README.md
  book/installation/binaries.md
  book/installation/docker.md
  book/installation/installation.md
  book/installation/source.md
  book/intro.md
  book/jsonrpc/admin.md
  book/jsonrpc/debug.md
  book/jsonrpc/engine.md
  book/jsonrpc/eth.md
  book/jsonrpc/intro.md
  book/jsonrpc/net.md
  book/jsonrpc/rpc.md
  book/jsonrpc/trace.md
  book/jsonrpc/tracing.md
  book/jsonrpc/txpool.md
  book/jsonrpc/web3.md
  book/run/config.md
  book/run/local_testnet.md
  crates/rpc/rpc-api/src/debug.rs
  crates/rpc/rpc-api/src/net.rs
  crates/rpc/rpc-api/src/txpool.rs
Labels: C-docs, C-enhancement

#3099 feat: add ParityTraceBuilder::callers
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
Labels: C-enhancement, A-rpc

#3097 feat: add util function for fetching tagged headers
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/block.rs
Labels: C-enhancement

#3108 chore: bump default rpc response size
  bin/reth/src/args/rpc_server_args.rs
Labels: A-cli

#3110 chore: map provider error variants to blocknotfound
  crates/rpc/rpc/src/eth/error.rs
Labels: A-rpc

#3089 chore(engine): run pipeline on start if any of the stages is lagging behind
  crates/consensus/beacon/src/engine/mod.rs
Labels: A-staged-sync, A-consensus

#3113 book: fix book installation link
  book/run/mainnet.md
Labels: C-docs

#3102 feat(rpc): add `BlockOverrides` in `trace_*`
  crates/rpc/rpc-api/src/trace.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-enhancement, A-rpc

#3034 refactor: remove `Transaction` and add `DatabaseProvider` to stages
  .gitignore
  Cargo.lock
  bin/reth/src/chain/import.rs
  bin/reth/src/db/mod.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/debug_cmd/merkle.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/drop.rs
  bin/reth/src/stage/dump/execution.rs
  bin/reth/src/stage/dump/hashing_account.rs
  bin/reth/src/stage/dump/hashing_storage.rs
  bin/reth/src/stage/dump/merkle.rs
  bin/reth/src/stage/dump/mod.rs
  bin/reth/src/stage/run.rs
  bin/reth/src/stage/unwind.rs
  bin/reth/src/utils.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/staged-sync/Cargo.toml
  crates/staged-sync/src/utils/init.rs
  crates/stages/benches/criterion.rs
  crates/stages/benches/setup/account_hashing.rs
  crates/stages/benches/setup/mod.rs
  crates/stages/src/error.rs
  crates/stages/src/lib.rs
  crates/stages/src/pipeline/builder.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/sets.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/finish.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/test_utils/runner.rs
  crates/stages/src/test_utils/stage.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/db/src/abstraction/database.rs
  crates/storage/db/src/abstraction/mock.rs
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/provider/src/traits/account.rs
  crates/storage/provider/src/traits/mod.rs
  crates/storage/provider/src/transaction.rs
  crates/trie/src/trie.rs
  crates/trie/src/trie_cursor/account_cursor.rs
  crates/trie/src/trie_cursor/storage_cursor.rs
  crates/trie/src/walker.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: C-debt, A-db

#3116 fix: re-enable the geth genesis format
  bin/reth/src/args/utils.rs
Labels: C-bug, A-utils, A-cli

#3119 refactor(stages): input target reached & output done checks
  bin/reth/src/debug_cmd/merkle.rs
  bin/reth/src/node/events.rs
  bin/reth/src/stage/dump/hashing_account.rs
  bin/reth/src/stage/dump/hashing_storage.rs
  bin/reth/src/stage/dump/merkle.rs
  bin/reth/src/stage/run.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/stages/src/pipeline/event.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/finish.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/test_utils/macros.rs
  crates/stages/src/test_utils/stage.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: A-staged-sync, C-debt

#3127 test: fix failing rpc test
  crates/rpc/rpc-builder/tests/it/http.rs
Labels: A-rpc, C-test

#3129 fix(cli): commit on stage run unwind
  bin/reth/src/stage/run.rs
Labels: A-staged-sync, A-cli

#3126 feat(rpc): rename `Client` generics to `Provider`
  bin/reth/src/args/rpc_server_args.rs
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-testing-util/src/trace.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/sign.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/cache.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/gas_oracle.rs
  crates/rpc/rpc/src/eth/pubsub.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-debt, A-rpc

#3125 feat(bin): sort `db stats` rows
  bin/reth/src/db/mod.rs
Labels: C-enhancement, A-cli

#3132 chore: use workspace dependencies
  Cargo.toml
  bin/reth/Cargo.toml
  crates/blockchain-tree/Cargo.toml
  crates/config/Cargo.toml
  crates/consensus/auto-seal/Cargo.toml
  crates/consensus/beacon/Cargo.toml
  crates/consensus/common/Cargo.toml
  crates/interfaces/Cargo.toml
  crates/metrics/Cargo.toml
  crates/net/common/Cargo.toml
  crates/net/discv4/Cargo.toml
  crates/net/dns/Cargo.toml
  crates/net/downloaders/Cargo.toml
  crates/net/ecies/Cargo.toml
  crates/net/eth-wire/Cargo.toml
  crates/net/nat/Cargo.toml
  crates/net/network-api/Cargo.toml
  crates/net/network/Cargo.toml
  crates/payload/basic/Cargo.toml
  crates/payload/builder/Cargo.toml
  crates/primitives/Cargo.toml
  crates/revm/Cargo.toml
  crates/revm/revm-inspectors/Cargo.toml
  crates/revm/revm-primitives/Cargo.toml
  crates/rlp/Cargo.toml
  crates/rpc/ipc/Cargo.toml
  crates/rpc/rpc-api/Cargo.toml
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-testing-util/Cargo.toml
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc/Cargo.toml
  crates/staged-sync/Cargo.toml
  crates/stages/Cargo.toml
  crates/storage/codecs/derive/Cargo.toml
  crates/storage/db/Cargo.toml
  crates/storage/libmdbx-rs/Cargo.toml
  crates/storage/provider/Cargo.toml
  crates/tasks/Cargo.toml
  crates/transaction-pool/Cargo.toml
  crates/trie/Cargo.toml
  testing/ef-tests/Cargo.toml
Labels: C-debt

#3100 feat: add js tracer
  Cargo.lock
  crates/revm/revm-inspectors/Cargo.toml
  crates/revm/revm-inspectors/src/tracing/js/bigint.js
  crates/revm/revm-inspectors/src/tracing/js/bindings.rs
  crates/revm/revm-inspectors/src/tracing/js/builtins.rs
  crates/revm/revm-inspectors/src/tracing/js/mod.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/src/database.rs
  crates/rpc/rpc-types/src/eth/trace/geth/mod.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/error.rs
Labels: C-enhancement, A-rpc

#3144 refactor: convert closure into function
  crates/stages/src/stages/tx_lookup.rs
Labels: A-staged-sync

#3147 feat(rpc): add helper function to also return the used state
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: A-rpc

#3151 chore: update ef-tests crate description
  testing/ef-tests/Cargo.toml
Labels: C-debt

#3154 fix: use serde json value for tracer config
  crates/rpc/rpc-types/src/eth/trace/geth/call.rs
  crates/rpc/rpc-types/src/eth/trace/geth/mod.rs
  crates/rpc/rpc-types/src/eth/trace/geth/pre_state.rs
  crates/rpc/rpc/src/debug.rs
Labels: A-rpc

#3165 feat: add downloader buffer graph
  etc/grafana/dashboards/overview.json
Labels: A-observability

#3170 feat: put blocks on right side with separate axis placement
  etc/grafana/dashboards/overview.json
Labels: C-enhancement, A-observability

#3141 fix: exclude calls to precompiles in call graphs
  crates/revm/revm-inspectors/src/tracing/arena.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
Labels: C-bug, A-rpc

#3142 refactor: trigger pipeline with finalized hash
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#3169 perf: reduce allocations in changeset helpers
  crates/storage/provider/src/providers/database/provider.rs
Labels: A-staged-sync, C-perf

#3172 docs: various book chores
  book/SUMMARY.md
  book/run/observability.md
Labels: C-docs

#3176 perf: reduce more allocs
  crates/storage/provider/src/providers/database/provider.rs
Labels: A-staged-sync, C-debt, C-perf, A-db

#3177 chore(sync): remove progress terminology from test macros
  crates/stages/src/test_utils/macros.rs
Labels: A-staged-sync, C-debt

#3180 chore(rpc): simplify GethTrace type
  crates/rpc/rpc-api/src/debug.rs
  crates/rpc/rpc-types/src/eth/trace/geth/mod.rs
  crates/rpc/rpc-types/src/eth/trace/geth/noop.rs
  crates/rpc/rpc-types/src/eth/trace/geth/pre_state.rs
  crates/rpc/rpc/src/debug.rs
Labels: C-debt, A-rpc

#3184 fix: use eth namespace for filter trait
  crates/rpc/rpc-api/src/eth_filter.rs
Labels: C-bug, A-rpc

#3185 chore: Cargo.lock out of sync
  Cargo.lock
Labels: C-debt

#3178 fix(stages): disable index history stages checkpoints
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
Labels: C-bug, A-staged-sync

#2971 feat: try to canonicalize safe and finalized
  crates/consensus/beacon/src/engine/forkchoice.rs
  crates/consensus/beacon/src/engine/mod.rs
Labels: A-consensus

#3187 fix: mark state as synced when transition to live sync
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-bug, A-consensus

#3183 docs: add some content to dev section of book
  book/SUMMARY.md
  book/developers/architecture.md
  book/developers/contribute.md
  book/developers/developers.md
Labels: C-docs, C-enhancement

#3168 chore: replace `ExecutionStage::read_block_with_senders` with `BlockProvider::block_with_senders`
  crates/interfaces/src/provider.rs
  crates/stages/src/stages/execution.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/block.rs
  crates/storage/provider/src/traits/transactions.rs
  crates/storage/provider/src/traits/withdrawals.rs
Labels: C-enhancement, A-db

#3171 feat(metrics): split `DownloaderMetrics` into body and headers downloaders
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/queue.rs
  crates/net/downloaders/src/bodies/request.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/downloaders/src/metrics.rs
Labels: C-debt, A-observability

#3179 fix: poll sync controller once if pipeline sync is pending
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
Labels: C-perf, A-consensus

#3192 ci: fix required checks
  .github/workflows/bench.yml
  .github/workflows/ci.yml
  .github/workflows/fuzz.yml
  .github/workflows/integration.yml
  .github/workflows/unit.yml
Labels: C-bug, A-meta

#3193 fix: encode forkid entry in struct, accept trailing fields
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/proto.rs
  crates/net/network/src/discovery.rs
Labels: C-bug, A-discv4

#3153 feat: add js debug test utils
  Cargo.lock
  crates/rpc/rpc-testing-util/Cargo.toml
  crates/rpc/rpc-testing-util/assets/noop-tracer.js
  crates/rpc/rpc-testing-util/src/debug.rs
  crates/rpc/rpc-testing-util/src/lib.rs
Labels: A-rpc

#3191 fix: shrink queued bodies and headers when drained or split
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
Labels: C-bug, A-networking

#3197 perf(rlp): improve uint encoding performance
  crates/rlp/src/encode.rs
Labels: C-perf

#3196 chore: remove unused methods on `DatabaseProvider`
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-debt

#3198 chore(provider): remove transition terminology
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-debt

#2311 refactor: phase out ether genesis in primitives
  crates/net/eth-wire/src/types/status.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/genesis.rs
  crates/primitives/src/serde_helper/jsonu256.rs
  crates/primitives/src/serde_helper/mod.rs
  crates/primitives/src/serde_helper/storage.rs
  crates/staged-sync/tests/sync.rs
Labels: C-debt

#3211 test: more js testing support
  crates/rpc/rpc-testing-util/assets/tracer-template.js
  crates/rpc/rpc-testing-util/src/debug.rs
Labels: A-rpc, C-test

#3207 fix(rpc): enter,exit functions dont take db object
  crates/revm/revm-inspectors/src/tracing/js/mod.rs
Labels: A-rpc

#3199 feat: support nonce and balance changes in state diff tracers
  crates/revm/revm-inspectors/src/tracing/builder/mod.rs
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/trace.rs
Labels: A-rpc

#3206 fix(bin): calculate ETA only if `EntitiesCheckpoint` is present
  bin/reth/src/node/events.rs
  crates/primitives/src/stage/checkpoints.rs
Labels: C-bug, A-cli

#3189 chore: replaces `tx.get::<Table>` with provider methods
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/debug_cmd/merkle.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/run.rs
  crates/stages/benches/setup/account_hashing.rs
  crates/stages/benches/setup/mod.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/test_utils/runner.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/provider/src/post_state/mod.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/transactions.rs
  crates/storage/provider/src/transaction.rs
Labels: C-enhancement, A-db

#3134 fix: dynamic batch size for tx lookup stage
  crates/stages/src/stages/tx_lookup.rs
Labels: A-staged-sync, C-perf

#3195 chore: move stage methods to `StageCheckpointProvider` and add `StageCheckpointWriter`
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/debug_cmd/merkle.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/run.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stages/merkle.rs
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/mod.rs
  crates/storage/provider/src/traits/stage_checkpoint.rs
Labels: C-enhancement, A-db

#3157 feat: set max response size for auth server on start
  crates/rpc/rpc-builder/src/auth.rs
Labels: C-enhancement, A-rpc

#3214 fix: set call trace gas limit with call inputs gas limit
  crates/revm/revm-inspectors/src/tracing/mod.rs
Labels: C-bug, A-rpc

#3217 perf: calculate trace address on demand
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
Labels: C-perf

#3216 fix: prevent panic in trace call
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: C-bug, A-rpc

#3222 perf(provider): return empty ommers after merge
  crates/primitives/src/chain/spec.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-perf

#3215 feat(config): missing stage configs
  bin/reth/src/node/mod.rs
  crates/config/src/config.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/merkle.rs
Labels: A-staged-sync, C-debt

#3219 test: add another fork id test
  crates/net/discv4/src/lib.rs
Labels: C-test, A-networking

#3221 perf: better state retrieval
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/state.rs
Labels: A-rpc

#3220 fix: fork id decoding from enr response
  crates/net/discv4/src/proto.rs
Labels: C-bug, A-networking

#3225 chore: expose txpool types that enable implementing `TransactionPool` trait
  crates/transaction-pool/src/lib.rs
Labels: C-debt, A-tx-pool

#3228 chore: `AccountProvider` -> `AccountReader` & `AccountWriter`
  crates/consensus/common/src/validation.rs
  crates/revm/src/executor.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/staged-sync/src/utils/init.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/index_account_history.rs
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/post_state/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/post_state_provider.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/macros.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/account.rs
  crates/storage/provider/src/traits/mod.rs
  crates/storage/provider/src/traits/state.rs
  crates/transaction-pool/src/validate.rs
Labels: C-debt, A-db

#3229 chore: move `update_pipeline_stages` to `StageCheckpointWriter`
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/stage_checkpoint.rs
Labels: C-debt, A-db
