Repository paradigmxyz/reth, pull requests merged in 2023-05, with the labels that each got.

#2484 fix(consensus): clique block rewards
  crates/consensus/common/src/calc.rs
Labels: C-bug, A-execution, A-consensus

#2480 fix(poststate): introduce wiped counter
  crates/revm/src/executor.rs
  crates/storage/provider/src/post_state.rs
  crates/storage/provider/src/providers/post_state_provider.rs
Labels: C-bug, A-execution

#2467 feat: add metrics for already seen txs and hashes
  crates/net/network/src/metrics.rs
  crates/net/network/src/transactions.rs
Labels: A-observability, A-networking

#2482 feat: add Resolve Payload function
  crates/payload/basic/src/lib.rs
  crates/payload/builder/src/lib.rs
  crates/payload/builder/src/test_utils.rs
  crates/payload/builder/src/traits.rs
Labels: A-block-building

#1888 feat(mock) `ExtendedAccount` storage method
  crates/rpc/rpc/src/eth/api/state.rs
  crates/storage/provider/src/test_utils/mock.rs
Labels: C-enhancement, C-test

#2486 refactor: roll custom canon state notification stream
  Cargo.lock
  bin/reth/src/node/mod.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/traits/chain.rs
Labels: C-debt

#2479 fix(txpool): move tx correctly after basefee update
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-bug, A-tx-pool

#2501 feat(grafana): bodies downloader errors chart
  etc/grafana/dashboards/overview.json
Labels: A-observability

#2468 feat: add new already seen transactions reputation variant
  crates/net/network-api/src/reputation.rs
  crates/net/network/src/peers/reputation.rs
  crates/net/network/src/transactions.rs
Labels: C-perf, A-networking

#2473 feat(cli): consensus engine events
  Cargo.lock
  bin/reth/src/node/events.rs
  bin/reth/src/node/mod.rs
  crates/consensus/beacon/src/engine/event.rs
  crates/consensus/beacon/src/engine/message.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/net/network/src/manager.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/lib.rs
  crates/primitives/src/listener/event_listeners.rs
  crates/primitives/src/listener/mod.rs
  crates/stages/src/pipeline/event.rs
  crates/stages/src/pipeline/mod.rs
Labels: C-enhancement, A-consensus, A-observability

#2499 chore: annotate with track caller
  crates/storage/provider/src/chain.rs
Labels: C-enhancement

#2493 chore(trie): move hash builder to primitives
  Cargo.lock
  crates/primitives/Cargo.toml
  crates/primitives/src/checkpoints.rs
  crates/primitives/src/trie/hash_builder/mod.rs
  crates/primitives/src/trie/hash_builder/state.rs
  crates/primitives/src/trie/hash_builder/value.rs
  crates/primitives/src/trie/mod.rs
  crates/primitives/src/trie/nibbles.rs
  crates/primitives/src/trie/nodes/branch.rs
  crates/primitives/src/trie/nodes/extension.rs
  crates/primitives/src/trie/nodes/leaf.rs
  crates/primitives/src/trie/nodes/mod.rs
  crates/trie/benches/prefix_set.rs
  crates/trie/src/hashed_cursor/post_state.rs
  crates/trie/src/lib.rs
  crates/trie/src/nibbles.rs
  crates/trie/src/nodes/branch.rs
  crates/trie/src/prefix_set/loader.rs
  crates/trie/src/prefix_set/mod.rs
  crates/trie/src/progress.rs
  crates/trie/src/trie.rs
  crates/trie/src/trie_cursor/subnode.rs
  crates/trie/src/updates.rs
  crates/trie/src/walker.rs
Labels: A-trie

#2441 feat: write account and storage hashes in genesis
  crates/primitives/src/genesis.rs
  crates/staged-sync/src/utils/init.rs
  crates/storage/provider/src/transaction.rs
  crates/trie/src/errors.rs
Labels: C-enhancement, A-consensus

#2465 feat: add helper for accessing pending block object
  crates/blockchain-tree/src/block_indices.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/shareable.rs
  crates/interfaces/src/blockchain_tree.rs
  crates/storage/provider/src/providers/mod.rs
Labels: A-db

#2464 adding payload builder panel in grafana dashboard
  etc/grafana/dashboards/overview.json
Labels: A-observability

#2507 feat: implement resolve step
  crates/payload/builder/src/service.rs
  crates/payload/builder/src/traits.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: A-block-building

#2462 feat(tree): Return block status for old blocks
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/shareable.rs
Labels: A-blockchain-tree

#2506 feat: find canonical ancestor
  crates/blockchain-tree/src/shareable.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/blockchain_tree.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
  crates/storage/provider/src/providers/mod.rs
Labels: A-consensus, A-blockchain-tree

#2518 proofs: prefer `encode_list` over `encode_iter`
  crates/consensus/common/src/validation.rs
  crates/interfaces/src/test_utils/generators.rs
  crates/primitives/src/proofs.rs
  crates/rlp/src/encode.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: C-debt

#2513 bench(proofs): root calculations
  crates/primitives/Cargo.toml
  crates/primitives/benches/trie_root.rs
  crates/primitives/src/proofs.rs
  crates/primitives/src/receipt.rs
Labels: C-benchmark

#2517 perf(proofs): root calculation using hash builder
  crates/consensus/auto-seal/src/task.rs
  crates/consensus/common/src/validation.rs
  crates/interfaces/src/test_utils/generators.rs
  crates/payload/basic/src/lib.rs
  crates/primitives/src/proofs.rs
  crates/revm/src/executor.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
  crates/storage/provider/src/post_state.rs
Labels: C-perf

#2523 fix: dont include latest valid hash on block hash error
  crates/consensus/beacon/src/engine/mod.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: A-consensus

#2524 feat(rpc): support pending block tag
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/storage/provider/src/providers/database.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/block.rs
Labels: C-enhancement, A-rpc

#2525 fix(cli): compute clean root till done
  bin/reth/src/merkle_debug.rs
Labels: C-bug, A-cli, A-trie

#2531 fix: drop tokio runtime on separate thread
  bin/reth/src/runner.rs
Labels: A-cli

#2530 feat(rpc): support launching on same port
  crates/rpc/rpc-builder/src/error.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/startup.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
Labels: A-rpc

#2535 docs: add a few notes about where states point to
  crates/storage/provider/src/traits/state.rs
Labels: C-docs

#2534 refactor: remove SyncstateUpdater generics and use boxed instead
  bin/reth/src/chain/import.rs
  bin/reth/src/node/mod.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/pipeline_state.rs
  crates/interfaces/src/sync.rs
  crates/stages/src/lib.rs
  crates/stages/src/pipeline/builder.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/sets.rs
Labels: A-staged-sync

#2541 chore: downgrade error and warn traces to debug
  bin/reth/src/node/events.rs
  crates/net/discv4/src/lib.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/request.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/state.rs
Labels: A-observability

#2547 dep: bump revm to 3.3.0
  Cargo.lock
Labels: A-dependencies

#2546 fix: ensure parent hash and number match
  crates/blockchain-tree/src/block_indices.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: A-blockchain-tree

#2232 feat: A basic json dump extension to reth db list.
  bin/reth/src/db/mod.rs
  crates/storage/db/src/tables/models/sharded_key.rs
  crates/storage/db/src/tables/models/storage_sharded_key.rs
Labels: C-enhancement, A-cli

#2509 Insert new blocks into cache
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/eth/cache.rs
Labels: C-perf, A-rpc

#2557 docs: add a few additional tree docs
  crates/blockchain-tree/src/block_indices.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/shareable.rs
  crates/interfaces/src/blockchain_tree.rs
Labels: C-docs, A-blockchain-tree

#2550 chore: add pipeline field docs and remove continous
  crates/stages/src/pipeline/builder.rs
  crates/stages/src/pipeline/mod.rs
Labels: C-docs, C-debt

#2552 fix: respect --p2p-secret-key argument
  bin/reth/src/args/network_args.rs
  bin/reth/src/args/secret_key.rs
  bin/reth/src/cli.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/p2p/mod.rs
  bin/reth/src/stage/mod.rs
Labels: C-bug, A-cli

#2532 fix(rpc): replay transactions before tracing
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
  crates/rpc/rpc/src/trace.rs
Labels: A-rpc

#2564 chore(cli): add possible valus to ws,http api
  bin/reth/src/args/rpc_server_args.rs
  crates/rpc/rpc-builder/src/lib.rs
Labels: A-cli

#2563 chore(provider): seperate error on unwind root mismatch
  crates/storage/provider/src/transaction.rs
Labels: C-debt

#2562 chore(cli): add details to --nat help message
  bin/reth/src/args/network_args.rs
Labels: A-cli

#2561 test(walker): walk range on dup table
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: A-db, C-test

#2559 feat: make logs per response configurable
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/eth/filter.rs
Labels: A-rpc

#2533 fix(rpc): use parent state when replaying block
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-bug, A-rpc

#2565 fix(engine): fail on canonical errors
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/executor.rs
Labels: C-bug, A-consensus

#2572 perf(rpc): use cached block receipts
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-perf, A-rpc

#2570 fix(rpc): set effective gas price
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/meta.rs
  crates/primitives/src/transaction/tx_type.rs
  crates/rpc/rpc-types/src/eth/transaction/receipt.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/storage/provider/src/providers/database.rs
Labels: A-rpc

#2494 feat(execution): state change size based commits
  Cargo.lock
  bin/reth/src/chain/import.rs
  bin/reth/src/dump_stage/merkle.rs
  bin/reth/src/merkle_debug.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/mod.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/primitives/src/constants.rs
  crates/revm/src/executor.rs
  crates/staged-sync/src/config.rs
  crates/stages/src/sets.rs
  crates/stages/src/stages/execution.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/post_state/account.rs
  crates/storage/provider/src/post_state/mod.rs
  crates/storage/provider/src/post_state/storage.rs
Labels: C-enhancement, A-staged-sync, A-execution

#2579 feat(rpc): set eip1559 gasPrice field
  crates/primitives/src/transaction/mod.rs
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/rpc/rpc-types/src/eth/block.rs
  crates/rpc/rpc-types/src/eth/transaction/common.rs
  crates/rpc/rpc-types/src/eth/transaction/mod.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/trace.rs
Labels: A-rpc

#2574 fix(rpc): use parent block state when tracing blocks
  crates/revm/revm-primitives/src/env.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/trace.rs
Labels: A-rpc

#2576 feat(rpc): add parity trace conversion
  crates/revm/revm-inspectors/src/tracing/builder/geth.rs
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
  crates/rpc/rpc-types/src/eth/trace/parity.rs
Labels: A-rpc

#2582 chore: rm unused var
  crates/rpc/rpc/src/eth/api/call.rs
Labels: C-debt

#2595 chore: improve channel is full log
  crates/transaction-pool/src/pool/mod.rs
Labels: A-observability

#2593 feat(txpool): add a few more maintain checks
  crates/transaction-pool/src/maintain.rs
Labels: A-tx-pool

#2603 feat(txpool): add add_and_subscribe
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/pool/listener.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate.rs
Labels: C-enhancement, A-tx-pool

#2609 chore: add traces for jwt file
  bin/reth/src/args/rpc_server_args.rs
Labels: A-observability

#2610 fix: make stats args global
  bin/reth/src/db/mod.rs
  bin/reth/src/dirs.rs
Labels: C-bug, A-cli

#2611 fix(rpc): initialize arena with root node
  crates/revm/revm-inspectors/src/tracing/arena.rs
Labels: C-bug, A-rpc

#2614 chore: move error module to integer list
  crates/primitives/src/error.rs
  crates/primitives/src/integer_list.rs
  crates/primitives/src/lib.rs
Labels: C-debt

#2617 chore: remove allow unused in rpc
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/pubsub.rs
  crates/rpc/rpc/src/lib.rs
  crates/rpc/rpc/src/result.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-debt, A-rpc

#2616 chore: use 4gb growth step
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: A-db

#2613 feat: add fullblock client
  Cargo.lock
  crates/interfaces/Cargo.toml
  crates/interfaces/src/p2p/bodies/client.rs
  crates/interfaces/src/p2p/full_block.rs
  crates/interfaces/src/p2p/headers/client.rs
  crates/interfaces/src/p2p/mod.rs
  crates/primitives/src/block.rs
  crates/primitives/src/peer.rs
Labels: A-networking

#2606 feat: Include genesis accounts in changesets
  crates/staged-sync/src/utils/init.rs
Labels: A-db

#2618 fix: reset correct value
  crates/interfaces/src/p2p/full_block.rs
Labels: C-debt

#2627 feat: use BlockHashOrNum in providers
  bin/reth/src/args/rpc_server_args.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/common/src/validation.rs
  crates/payload/basic/src/lib.rs
  crates/primitives/src/chain/info.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/logs_utils.rs
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/providers/database.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/block.rs
  crates/storage/provider/src/traits/block_id.rs
  crates/storage/provider/src/traits/evm_env.rs
  crates/storage/provider/src/traits/mod.rs
  crates/storage/provider/src/traits/receipts.rs
  crates/storage/provider/src/traits/transactions.rs
  crates/storage/provider/src/traits/withdrawals.rs
  crates/transaction-pool/src/maintain.rs
Labels: C-enhancement, A-rpc, A-db

#2620 test: add open ended filter test
  crates/primitives/src/filter.rs
  crates/rpc/rpc/src/eth/logs_utils.rs
Labels: C-test

#2349 feat: implement call tracer
  crates/revm/revm-inspectors/Cargo.toml
  crates/revm/revm-inspectors/src/tracing/builder/geth.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
  crates/rpc/rpc-types/src/eth/trace/geth/call.rs
  crates/rpc/rpc-types/src/eth/trace/geth/mod.rs
  crates/rpc/rpc/src/debug.rs
Labels: C-enhancement, A-rpc

#2635 perf: read header range first
  crates/rpc/rpc/src/eth/filter.rs
Labels: C-perf, A-rpc

#2639 chore: bump cache sizes
  crates/rpc/rpc/src/eth/cache.rs
Labels: A-rpc

#2640 chore(deps): bump jsonrpsee 0.18
  Cargo.lock
  crates/rpc/ipc/Cargo.toml
  crates/rpc/ipc/src/server/ipc.rs
  crates/rpc/ipc/src/server/mod.rs
  crates/rpc/rpc-api/Cargo.toml
  crates/rpc/rpc-api/src/admin.rs
  crates/rpc/rpc-api/src/debug.rs
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-api/src/eth.rs
  crates/rpc/rpc-api/src/eth_filter.rs
  crates/rpc/rpc-api/src/eth_pubsub.rs
  crates/rpc/rpc-api/src/net.rs
  crates/rpc/rpc-api/src/trace.rs
  crates/rpc/rpc-api/src/txpool.rs
  crates/rpc/rpc-api/src/web3.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/error.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-engine-api/src/error.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/eth/syncing.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/admin.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/pubsub.rs
  crates/rpc/rpc/src/layers/auth_layer.rs
  crates/rpc/rpc/src/result.rs
  deny.toml
Labels: A-rpc, A-dependencies

#2555 feat: add forkchoice update tracker type
  bin/reth/src/node/mod.rs
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/engine/mod.rs
  crates/rpc/rpc-types/src/eth/engine/forkchoice.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/providers/chain_info.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/traits/chain_info.rs
  crates/storage/provider/src/traits/mod.rs
Labels: A-rpc

#2646 meta: add beacon consensus code owners
  CODEOWNERS
Labels: A-meta

#2641 fix(codec): Use variable length encoding for lengths on `Vec<T>` and `Option<T>`
  crates/primitives/src/receipt.rs
  crates/storage/codecs/src/lib.rs
Labels: C-bug, A-db, S-breaking

#2647 feat: add getter for last FCU timestamp
  crates/storage/provider/src/providers/chain_info.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/traits/chain_info.rs
Labels: C-enhancement

#2645 chore: split on new payload function
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#2650 feat: impl BlockIdProvider for BlockchainProvider
  crates/storage/provider/src/providers/mod.rs
Labels: C-enhancement, A-rpc

#2622 fix: remove `Account` length from compact on `AccountBeforeTx`
  crates/storage/db/src/tables/models/accounts.rs
Labels: A-db, S-breaking

#2632 fix(poststate): duplicate receipts
  crates/consensus/auto-seal/src/task.rs
  crates/payload/basic/src/lib.rs
  crates/revm/src/executor.rs
  crates/rpc/rpc/src/eth/cache.rs
  crates/storage/provider/src/chain.rs
  crates/storage/provider/src/post_state/mod.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/provider/src/transaction.rs
Labels: C-bug, A-execution, S-breaking

#2634 fix(poststate): handle secondary selfdestructs
  crates/revm/src/executor.rs
  crates/storage/provider/src/post_state/mod.rs
  crates/storage/provider/src/post_state/storage.rs
Labels: C-bug, A-execution, S-breaking

#2636 fix(poststate): storage revert before selfdestruct
  Cargo.lock
  crates/storage/provider/src/post_state/mod.rs
  crates/storage/provider/src/post_state/storage.rs
Labels: C-bug, S-blocked, A-execution, S-breaking

#2500 fix: unwind stages with respect to commit threshold
  Cargo.lock
  bin/reth/src/stage/mod.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/stages/tx_lookup.rs
Labels: C-bug, A-staged-sync

#2631 fix(executor): do not insert empty changesets for touched accounts
  crates/revm/src/executor.rs
Labels: C-bug, A-execution, S-breaking

#2630 fix(executor): do not destroy empty accounts
  crates/revm/src/executor.rs
Labels: C-bug, A-execution, S-breaking

#2600 feat: gas price oracle
  crates/interfaces/src/provider.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/gas_oracle.rs
  crates/rpc/rpc/src/eth/mod.rs
Labels: C-enhancement, A-rpc

#2654 feat: add safe and finalized tags to StateProviderFactory
  crates/interfaces/src/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/block_id.rs
  crates/storage/provider/src/traits/state.rs
Labels: C-enhancement, A-rpc

#2653 chore(poststate): size hint
  crates/stages/src/stages/execution.rs
  crates/storage/provider/src/post_state/mod.rs
Labels: C-debt, A-execution

#2657 perf(rpc): improve gas price perf by skipping hash
  crates/blockchain-tree/src/shareable.rs
  crates/interfaces/src/blockchain_tree.rs
  crates/rpc/rpc/src/eth/gas_oracle.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/block.rs
Labels: C-perf, A-rpc, A-db

#2656 perf: restrict bodies downloader by number of blocks
  bin/reth/src/stage/mod.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/queue.rs
  crates/net/downloaders/src/bodies/request.rs
  crates/net/downloaders/src/metrics.rs
  crates/primitives/src/block.rs
  crates/staged-sync/src/config.rs
Labels: A-staged-sync, C-perf, A-networking

#2660 fix: don't starve high priority requests
  crates/interfaces/src/p2p/priority.rs
  crates/net/network/src/fetch/mod.rs
Labels: C-perf, A-networking

#2661 fix: dont upscale concurrent request for lower peer count
  crates/net/downloaders/src/bodies/bodies.rs
Labels: C-perf, A-networking

#2666 feat: add a few EthRequestHandler metrics
  crates/net/network/src/eth_requests.rs
  crates/net/network/src/metrics.rs
Labels: A-observability

#2664 Configure Gas Price Oracle with CLI arguments
  bin/reth/src/args/gas_price_oracle_args.rs
  bin/reth/src/args/mod.rs
  bin/reth/src/args/rpc_server_args.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/eth/gas_oracle.rs
Labels: A-rpc, A-cli

#2671 test(executor): account created & destroyed within the same transaction
  Cargo.lock
  crates/revm/Cargo.toml
  crates/revm/src/executor.rs
Labels: A-execution, C-test

#2674 chore: cleanup engine api errors
  crates/consensus/beacon/src/engine/error.rs
  crates/consensus/beacon/src/engine/message.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/error.rs
  crates/rpc/rpc-types/src/eth/engine/forkchoice.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: C-debt, A-rpc

#2675 chore: make clippy happy, tests edition
  crates/storage/provider/src/post_state/mod.rs
Labels: C-debt

#2667 feat: support subscriptions over IPC
  Cargo.lock
  crates/rpc/ipc/Cargo.toml
  crates/rpc/ipc/src/server/ipc.rs
  crates/rpc/ipc/src/server/mod.rs
Labels: C-enhancement, A-rpc

#2676 fix: dont exit engine on failed FCU
  crates/consensus/beacon/src/engine/error.rs
  crates/consensus/beacon/src/engine/message.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/rpc/rpc-engine-api/src/error.rs
Labels: C-bug, C-debt, A-consensus

#2668 feat(rpc): set starting block to latest at launch
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
Labels: A-rpc

#2684 fix: use bounded sender for bodies responses
  crates/net/downloaders/src/bodies/task.rs
Labels: C-bug, A-networking

#2685 perf: spawn blocking trace calls
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-perf, A-rpc

#2686 perf: spawn blocking eth calls
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/error.rs
Labels: C-perf, A-rpc

#2687 fix: use bounded channel for headers download task
  crates/net/downloaders/src/headers/task.rs
Labels: C-bug, A-networking

#2670 fix(poststate): collapse account changes
  crates/storage/provider/src/post_state/account.rs
  crates/storage/provider/src/post_state/mod.rs
Labels: C-bug, A-execution, S-breaking

#2688 chore: bump max logs per response to 10k
  crates/rpc/rpc-builder/src/eth.rs
Labels: A-rpc

#2652 perf: do not compile traces in release mode
  Cargo.toml
  bin/reth/Cargo.toml
  crates/blockchain-tree/Cargo.toml
  crates/consensus/auto-seal/Cargo.toml
  crates/consensus/beacon/Cargo.toml
  crates/interfaces/Cargo.toml
  crates/net/discv4/Cargo.toml
  crates/net/dns/Cargo.toml
  crates/net/downloaders/Cargo.toml
  crates/net/ecies/Cargo.toml
  crates/net/eth-wire/Cargo.toml
  crates/net/nat/Cargo.toml
  crates/net/network/Cargo.toml
  crates/payload/basic/Cargo.toml
  crates/payload/builder/Cargo.toml
  crates/primitives/Cargo.toml
  crates/revm/Cargo.toml
  crates/rpc/ipc/Cargo.toml
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc/Cargo.toml
  crates/staged-sync/Cargo.toml
  crates/stages/Cargo.toml
  crates/storage/provider/Cargo.toml
  crates/tasks/Cargo.toml
  crates/tracing/Cargo.toml
  crates/transaction-pool/Cargo.toml
  crates/trie/Cargo.toml
Labels: C-perf

#2691 fix: use proper base fee in auto seal
  crates/consensus/auto-seal/src/task.rs
  crates/primitives/src/chain/spec.rs
Labels: C-bug, A-consensus, A-block-building

#2690 fix: use auto seal client for consensus
  bin/reth/src/node/mod.rs
  crates/interfaces/src/p2p/either.rs
  crates/interfaces/src/p2p/mod.rs
Labels: C-bug, A-consensus, A-cli

#2693 chore(deps): enable tracing default features
  Cargo.toml
  crates/tasks/Cargo.toml
  crates/tracing/Cargo.toml
Labels: A-dependencies

#2697 fix(dep): `tokio-util` is no longer optional
  crates/net/downloaders/Cargo.toml
Labels: A-dependencies

#2694 fix: use saturated range
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: A-rpc

#2696 perf: spawn eth filter tasks
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/eth/filter.rs
Labels: C-perf, A-rpc

#2699 fix(p2p): network sync state
  bin/reth/src/chain/import.rs
  bin/reth/src/node/mod.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/p2p/headers/client.rs
  crates/interfaces/src/sync.rs
  crates/interfaces/src/test_utils/headers.rs
  crates/net/downloaders/src/test_utils/file_client.rs
  crates/net/network/src/network.rs
  crates/net/network/src/transactions.rs
  crates/net/network/tests/it/connect.rs
  crates/stages/src/lib.rs
  crates/stages/src/pipeline/builder.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/sets.rs
  crates/stages/src/stages/finish.rs
Labels: A-staged-sync, C-debt, A-consensus

#2710 refactor: cleanup Providererror
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/provider.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stages/finish.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/storage/provider/src/providers/database.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/traits/state.rs
  crates/storage/provider/src/transaction.rs
Labels: C-debt

#2709 chore: executor error cleanup
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/chain.rs
  crates/blockchain-tree/src/shareable.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/blockchain_tree.rs
  crates/interfaces/src/error.rs
  crates/interfaces/src/executor.rs
  crates/revm/src/executor.rs
  crates/stages/src/error.rs
  crates/storage/provider/src/chain.rs
  crates/storage/provider/src/test_utils/executor.rs
  crates/storage/provider/src/traits/executor.rs
Labels: C-debt

#2714 chore: add missing crates to codeowners
  CODEOWNERS
Labels: A-meta

#2713 chore: remove crate-template
  Cargo.toml
  crate-template/Cargo.toml
  crate-template/src/lib.rs
  docs/repo/layout.md
Labels: C-debt

#2711 chore: rm unused error variants
  crates/interfaces/src/consensus.rs
Labels: C-debt

#2716 docs: update layout docs
  docs/repo/layout.md
Labels: C-docs, C-debt

#2718 chore: rename Error to DatabaseError
  bin/reth/src/node/mod.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/consensus/beacon/src/engine/error.rs
  crates/interfaces/src/db.rs
  crates/interfaces/src/error.rs
  crates/interfaces/src/p2p/error.rs
  crates/net/downloaders/src/bodies/test_utils.rs
  crates/staged-sync/src/utils/init.rs
  crates/stages/benches/setup/account_hashing.rs
  crates/stages/src/error.rs
  crates/stages/src/id.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/test_utils/runner.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/db/src/abstraction/common.rs
  crates/storage/db/src/abstraction/cursor.rs
  crates/storage/db/src/abstraction/database.rs
  crates/storage/db/src/abstraction/mock.rs
  crates/storage/db/src/abstraction/table.rs
  crates/storage/db/src/abstraction/transaction.rs
  crates/storage/db/src/implementation/mdbx/cursor.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/lib.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/db/src/tables/codecs/postcard.rs
  crates/storage/db/src/tables/codecs/scale.rs
  crates/storage/db/src/tables/models/accounts.rs
  crates/storage/db/src/tables/models/integer_list.rs
  crates/storage/db/src/tables/models/mod.rs
  crates/storage/db/src/tables/models/sharded_key.rs
  crates/storage/db/src/tables/models/storage_sharded_key.rs
  crates/storage/db/src/tables/raw.rs
  crates/storage/db/src/tables/utils.rs
  crates/storage/provider/src/post_state/mod.rs
  crates/storage/provider/src/providers/database.rs
  crates/storage/provider/src/transaction.rs
  crates/trie/src/errors.rs
  crates/trie/src/hashed_cursor/default.rs
  crates/trie/src/hashed_cursor/mod.rs
  crates/trie/src/hashed_cursor/post_state.rs
  crates/trie/src/prefix_set/loader.rs
  crates/trie/src/trie_cursor/account_cursor.rs
  crates/trie/src/trie_cursor/mod.rs
  crates/trie/src/trie_cursor/storage_cursor.rs
  crates/trie/src/updates.rs
  crates/trie/src/walker.rs
Labels: C-debt

#2722 fix: set sync state at startup to idle
  crates/consensus/beacon/src/engine/mod.rs
  crates/net/network/src/network.rs
  crates/net/network/tests/it/startup.rs
Labels: A-consensus, A-networking

#2721 chore: rm duplicate transact
  crates/payload/basic/src/lib.rs
Labels: C-debt

#2725 fix: return latestValidHash from sidechains
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-bug, A-consensus, C-test

#2702 fix: check db and indices for canonical block
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/primitives/src/chain/spec.rs
Labels: C-bug, A-consensus, C-test, A-blockchain-tree

#2717 chore: rm changelog
  CHANGELOG.md
Labels: C-debt

#2731 test: ensure port is unused for udp and tcp
  crates/net/network/src/test_utils/init.rs
  crates/net/network/src/test_utils/mod.rs
  crates/staged-sync/tests/sync.rs
Labels: C-test

#2701 feat(stages): rich checkpoint
  bin/reth/src/drop_stage.rs
  bin/reth/src/dump_stage/execution.rs
  bin/reth/src/dump_stage/hashing_account.rs
  bin/reth/src/dump_stage/hashing_storage.rs
  bin/reth/src/dump_stage/merkle.rs
  bin/reth/src/merkle_debug.rs
  bin/reth/src/node/events.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/mod.rs
  bin/reth/src/test_eth_chain/runner.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/primitives/src/account.rs
  crates/primitives/src/checkpoints.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/trie/hash_builder/value.rs
  crates/staged-sync/src/utils/init.rs
  crates/stages/benches/criterion.rs
  crates/stages/benches/setup/account_hashing.rs
  crates/stages/src/id.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/pipeline/sync_metrics.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/finish.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/test_utils/macros.rs
  crates/storage/codecs/src/lib.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/provider/src/providers/database.rs
  crates/storage/provider/src/transaction.rs
Labels: A-staged-sync, C-debt, S-breaking

#2727 fix(cli): run pipeline to completion after restart
  bin/reth/src/node/mod.rs
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-bug, A-consensus, A-cli

#2736 chore: fix typo
  crates/interfaces/src/executor.rs
  crates/revm/src/executor.rs
Labels: C-debt

#2744 fix: calculate state root for auto-seal
  crates/consensus/auto-seal/src/task.rs
Labels: A-consensus

#2740 chore: run `dump stage` as blocking task
  bin/reth/src/cli.rs
Labels: C-debt, A-cli

#2743 docs: add warning note on get_payload_bodies_by_range
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-docs, A-rpc, A-consensus

#2737 refactor: rm dupe `InvalidTransactionError`s
  crates/consensus/common/src/validation.rs
  crates/interfaces/src/consensus.rs
  crates/primitives/src/transaction/error.rs
  crates/transaction-pool/src/error.rs
Labels: C-debt

#2741 refactor: move stage commands to `reth stage`
  bin/reth/src/cli.rs
  bin/reth/src/lib.rs
  bin/reth/src/stage/drop.rs
  bin/reth/src/stage/dump/execution.rs
  bin/reth/src/stage/dump/hashing_account.rs
  bin/reth/src/stage/dump/hashing_storage.rs
  bin/reth/src/stage/dump/merkle.rs
  bin/reth/src/stage/dump/mod.rs
  bin/reth/src/stage/mod.rs
  bin/reth/src/stage/run.rs
Labels: C-debt, A-cli

#2739 refactor: remove unused `Transaction` fns
  crates/storage/provider/src/transaction.rs
Labels: C-debt, A-db

#2732 fix(poststate): state clear eip
  crates/revm/src/executor.rs
Labels: C-bug, A-execution, S-breaking

#2543 feat: add state root validation on new insert
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/chain.rs
Labels: A-blockchain-tree

#2742 refactor: expanded cli version info
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/build.rs
  bin/reth/src/chain/import.rs
  bin/reth/src/cli.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/run.rs
  bin/reth/src/version.rs
Labels: C-debt, A-cli

#2754 fix: make vergen emit cargo target triple
  bin/reth/build.rs
  bin/reth/src/version.rs
Labels: C-bug

#2749 refactor: convert InsertBlockError
  crates/consensus/beacon/src/engine/error.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/blockchain_tree/error.rs
  crates/rpc/rpc-engine-api/src/error.rs
Labels: A-consensus

#2748 chore: properly convert invalid transaction errors
  crates/primitives/src/transaction/error.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/rpc/rpc/src/eth/gas_oracle.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: C-debt, A-rpc

#2757 feat: integrate payload builder args in cli
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/args/mod.rs
  bin/reth/src/args/payload_build_args.rs
  bin/reth/src/args/payload_builder_args.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/utils.rs
  crates/payload/basic/src/lib.rs
Labels: C-enhancement, A-cli

#2758 feat: add node identity to networking stack
  bin/reth/src/args/network_args.rs
  crates/net/eth-wire/src/hello.rs
  crates/net/network/src/lib.rs
Labels: C-enhancement, A-cli

#2771 feat(net): add function to set NetworkMode in builder
  crates/net/network/src/config.rs
Labels: A-networking

#2756 ci: disable bench comparison workflow for main
  .github/workflows/bench.yml
Labels: C-bug, C-benchmark

#2761 chore: consistent _senders suffix
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/blockchain_tree/mod.rs
Labels: C-debt

#2760 chore: trace return values on insert
  crates/consensus/beacon/src/engine/mod.rs
Labels: A-observability

#2763 chore: add SealedHeader::split
  crates/primitives/src/header.rs
Labels: C-enhancement, C-debt

#2773 chore: use release profile in docker file
  Dockerfile
Labels: A-meta

#2775 fix: ensure extradata is 32 bytes or less
  bin/reth/src/args/network_args.rs
  bin/reth/src/args/payload_builder_args.rs
  bin/reth/src/version.rs
  crates/consensus/beacon/src/beacon_consensus.rs
  crates/primitives/src/constants.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: C-bug, A-cli

#2769 feat: add sealed headers range
  crates/consensus/common/src/validation.rs
  crates/storage/provider/src/providers/database.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/header.rs
Labels: C-enhancement, A-db

#2780 fix(mdbx): use windows symbols on windows
  crates/storage/libmdbx-rs/src/environment.rs
Labels: C-bug, A-db
