Repository paradigmxyz/reth, pull requests merged in 2023-09, with the labels that each got.

#4447 feat: add blob count checks
  crates/primitives/src/constants/eip4844.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool

#4410 feat(storage, tree): respect `Transaction Lookup` pruning in the blockchain tree
  Cargo.lock
  Cargo.toml
  bin/reth/src/debug_cmd/in_memory_merkle.rs
  bin/reth/src/debug_cmd/merkle.rs
  bin/reth/src/node/mod.rs
  crates/blockchain-tree/Cargo.toml
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/consensus/common/Cargo.toml
  crates/net/downloaders/Cargo.toml
  crates/primitives/Cargo.toml
  crates/primitives/src/prune/mode.rs
  crates/prune/Cargo.toml
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc/Cargo.toml
  crates/stages/Cargo.toml
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/mod.rs
  crates/storage/db/Cargo.toml
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/block.rs
  crates/transaction-pool/Cargo.toml
  examples/rpc-db.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: C-enhancement, A-db, A-blockchain-tree, A-pruning

#4390 feat(stages): respect `PruneModes` in `TxLookup` stage
  Cargo.lock
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/run.rs
  crates/config/src/config.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/prune/src/pruner.rs
  crates/stages/benches/criterion.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/tx_lookup.rs
Labels: C-enhancement, A-staged-sync, A-pruning

#4458 chore: do not warn when the chain is syncing normally
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus, A-observability

#4461 Fix: high load RPC putting node in a broken state: avoid running blocking tasks within blocking tasks
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-perf, A-rpc

#4453 consolidate eip4844 pool errors
  crates/rpc/rpc/src/eth/error.rs
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: C-debt, A-tx-pool

#4454 docs(book): mention full node in `mainnet.md`
  book/run/mainnet.md
Labels: C-docs, A-pruning

#4463 docs: add WSL2 Disk allocation (Bus error)
  book/installation/source.md
Labels: C-docs

#4280 feat(storage): recover senders if not found in database
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-enhancement, A-db, A-pruning

#4470 test(storage): recover senders if not found in database
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: A-db, C-test

#4474 chore(executor): split bundle state on write
  crates/storage/provider/src/change.rs
Labels: A-execution

#4473 chore(executor): optional first block
  crates/revm/src/processor.rs
Labels: C-debt, A-execution

#4425 feat: pass parent beacon block root to payload builder
  crates/payload/basic/src/lib.rs
  crates/payload/builder/src/payload.rs
Labels: C-enhancement, A-block-building, M-eip, E-cancun

#4478 chore: add cancun to hive job
  .github/workflows/hive.yml
Labels: C-enhancement, E-cancun

#4477 add semaphore to EthStateCacheService
  crates/rpc/rpc/src/eth/cache/config.rs
  crates/rpc/rpc/src/eth/cache/mod.rs
Labels: C-perf, A-rpc

#4485 Remove redundant clones
  bin/reth/src/recover/storage_tries.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/prune/src/pruner.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-debt

#4482 feat: add get blobs exact
  crates/payload/basic/src/lib.rs
  crates/transaction-pool/src/blobstore/mem.rs
  crates/transaction-pool/src/blobstore/mod.rs
  crates/transaction-pool/src/blobstore/noop.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/traits.rs
Labels: C-perf, A-block-building, A-tx-pool

#4480 perf: skip blobs if no blob space available
  crates/payload/basic/src/lib.rs
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/traits.rs
Labels: A-block-building, A-tx-pool

#4408 feat: delete discarded blob txs from blob store
  crates/transaction-pool/src/pool/mod.rs
Labels: C-enhancement, A-tx-pool, E-cancun

#4431 feat(storage, tree): respect `Sender Recovery` pruning in the blockchain tree
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-enhancement, M-changelog, A-db, A-blockchain-tree, A-pruning

#4488 feat(primitives): remove constraints on `SenderRecovery` pruning
  bin/reth/src/args/pruning_args.rs
  crates/primitives/src/prune/target.rs
Labels: C-enhancement, M-changelog, A-pruning

#4489 feat: add blob costs to cost value
  crates/primitives/src/transaction/mod.rs
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#4487 feat: enforce no nonce gaps for eip-4844
  crates/rpc/rpc/src/eth/error.rs
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/validate/mod.rs
Labels: A-tx-pool

#4491 fix(primitives): map cancun to timestamp fork
  crates/primitives/src/chain/spec.rs
Labels: C-bug, A-utils, E-cancun

#4490 feat(engine): enable v3 endpoints
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-enhancement, A-rpc, E-cancun

#4492 fix(rpc-types): do not flatten in ExecutionPayloadV3
  crates/payload/builder/src/payload.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: C-bug, A-rpc, A-consensus, E-cancun

#4481 add metrics counter for finished spawned tasks
  crates/tasks/src/lib.rs
  crates/tasks/src/metrics.rs
Labels: A-observability

#4498 chore: remove outdated TODOs
  crates/payload/builder/src/payload.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-debt, A-rpc, A-consensus

#4499 chore: bump c-kzg and add serde feature
  Cargo.lock
  bin/reth/src/node/mod.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/constants/eip4844.rs
Labels: A-dependencies

#4501 fix: filter out pre-genesis timestamp forks
  crates/net/eth-wire/src/ethstream.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/forkid.rs
Labels: C-bug, A-devp2p, A-networking

#4503 fix: skip optional fields in parity trace
  crates/rpc/rpc-types/src/eth/trace/parity.rs
Labels: A-rpc

#4507 chore: add is_empty check before read lock
  crates/transaction-pool/src/pool/mod.rs
Labels: C-perf, A-tx-pool

#4505 perf: small access list perf
  crates/primitives/src/transaction/access_list.rs
  crates/revm/revm-inspectors/src/access_list.rs
  crates/rpc/rpc/src/eth/api/call.rs
Labels: C-debt, C-perf

#4500 fix(primitives): set cancun header fields if active at genesis
  crates/primitives/src/chain/spec.rs
Labels: C-bug, A-utils, E-cancun

#4509 fix(tasks): use `crate::metrics` to avoid ambiguity
  crates/tasks/src/lib.rs
Labels: C-bug

#4511 chore(ci): cargo check
  .github/workflows/ci.yml
Labels: A-meta

#4516 feat: add base fee and blob fields to genesis
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/genesis.rs
Labels: C-enhancement, A-utils, E-cancun

#4517 fix: ensure only canonical state is returned if requested by number/hash
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/traits/state.rs
Labels: C-bug, A-rpc

#4524 fix: check for parent root before cancun
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-bug, A-rpc, A-consensus, E-cancun

#4523 fix: use `blob_fee` to calculate blob_gas_used in receipts
  crates/primitives/src/constants/eip4844.rs
  crates/primitives/src/header.rs
  crates/primitives/src/transaction/meta.rs
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-bug, A-rpc, E-cancun

#4522 fix: enable cancun in transaction validator if active at genesis
  crates/transaction-pool/src/validate/eth.rs
Labels: C-bug, A-tx-pool, E-cancun

#4521 fix: use max_fee_per_blob_gas in blob gas cost calc
  crates/transaction-pool/src/traits.rs
Labels: C-bug, A-tx-pool, E-cancun

#4508 #2511: extended reth-rpc example with custom rpc ext
  Cargo.lock
  Cargo.toml
  bin/reth/src/lib.rs
  bin/reth/src/utils.rs
  examples/Cargo.toml
  examples/rpc-db/Cargo.toml
  examples/rpc-db/src/main.rs
  examples/rpc-db/src/myrpc_ext.rs
Labels: C-enhancement

#4518 Apply foundry improvements to reth
  crates/revm/revm-inspectors/src/access_list.rs
  crates/revm/revm-inspectors/src/tracing/js/mod.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
Labels: C-debt

#4532 chore: rm todo about polling jobs
  crates/payload/builder/src/service.rs
Labels: C-debt

#4531 test: add backward compat toml test
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  crates/config/Cargo.toml
  crates/config/src/config.rs
Labels: C-test

#4527 chore: change best unconnected condition
  crates/net/network/src/peers/manager.rs
Labels: C-perf

#4528 perf: increase refill slots interval
  crates/net/network/src/peers/manager.rs
Labels: C-perf

#4359 feat: holesky support
  crates/primitives/res/genesis/holesky.json
  crates/primitives/src/chain/mod.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/constants/mod.rs
  crates/primitives/src/lib.rs
Labels: C-enhancement

#4536 fix: wake future after buffering pong
  crates/net/eth-wire/src/p2pstream.rs
Labels: C-bug, A-devp2p, A-networking

#4541 fix: add missing holesky variant
  bin/reth/src/args/utils.rs
Labels: C-bug

#4506 fix: set trace results root trace's gas used to execution results gas
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/rpc/rpc-types/src/eth/trace/parity.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-bug, A-rpc

#4526 chore: bump sale period to 21 days
  .github/workflows/stale.yml
Labels: A-meta

#4543 feat: add discovery port function
  crates/net/discv4/src/lib.rs
  crates/net/network/src/config.rs
Labels: C-enhancement, C-debt

#4486 feat(state): receipts pruning
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/shareable.rs
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/interfaces/src/blockchain_tree/error.rs
  crates/interfaces/src/executor.rs
  crates/payload/basic/src/lib.rs
  crates/primitives/src/proofs.rs
  crates/primitives/src/prune/part.rs
  crates/revm/src/factory.rs
  crates/revm/src/processor.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  crates/rpc/rpc/src/eth/cache/mod.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/mod.rs
  crates/storage/provider/src/chain.rs
  crates/storage/provider/src/change.rs
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/provider/src/test_utils/executor.rs
  crates/storage/provider/src/traits/executor.rs
  crates/storage/provider/src/traits/mod.rs
Labels: A-execution, A-pruning

#4547 feat: add metrics for inflight get pooled tx requests
  crates/net/network/src/metrics.rs
  crates/net/network/src/transactions.rs
Labels: A-observability

#4544 test: enable geth tests again
  crates/net/network/tests/it/connect.rs
Labels: C-test

#4533 feat: add `cuckoofilter` to `nippy-jar`
  Cargo.lock
  crates/storage/nippy-jar/Cargo.toml
  crates/storage/nippy-jar/src/compression/mod.rs
  crates/storage/nippy-jar/src/filter/cuckoo.rs
  crates/storage/nippy-jar/src/filter/mod.rs
  crates/storage/nippy-jar/src/lib.rs
Labels: C-enhancement, A-snapshots

#4549 chore(book): fix imposter USDC address
  book/run/config.md
Labels: C-docs

#4552 chore: pin git dependencies to specific revs
  Cargo.lock
  Cargo.toml
  crates/net/discv4/Cargo.toml
  crates/net/nat/Cargo.toml
  crates/revm/revm-inspectors/Cargo.toml
  deny.toml
Labels: A-dependencies

#4539 feat: enforce replacements dont conflict
  crates/rpc/rpc/src/eth/error.rs
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/validate/mod.rs
Labels: A-tx-pool

#4534 feat: add blob tx replacement overdraft check
  crates/transaction-pool/src/pool/txpool.rs
Labels: A-tx-pool

#4556 fix: set trace results root trace's gas used to execution result gas
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/rpc/rpc-types/src/eth/trace/parity.rs
  crates/rpc/rpc/src/trace.rs
Labels: A-rpc

#4530 perf: limit number of new batch of dials
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/peers/mod.rs
Labels: C-perf, A-networking

#4560 fix: update Status ForkId on new head
  crates/net/network/src/session/mod.rs
Labels: C-bug, A-devp2p, A-networking

#4561 fix: use with_bundle_update to prevent take_bundle panic
  crates/payload/basic/src/lib.rs
Labels: C-bug, A-execution, A-block-building

#4558 fix(state): store receipts in vec
  crates/consensus/auto-seal/src/lib.rs
  crates/payload/basic/src/lib.rs
  crates/revm/src/processor.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  crates/rpc/rpc/src/eth/cache/mod.rs
  crates/storage/provider/src/chain.rs
  crates/storage/provider/src/change.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/test_utils/blocks.rs
Labels: C-bug, A-execution, A-pruning

#4566 chore(execution): rely on bundle size hint for commits
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/revm/src/processor.rs
  crates/stages/src/stages/execution.rs
  crates/storage/provider/src/test_utils/executor.rs
  crates/storage/provider/src/traits/executor.rs
Labels: C-debt, A-execution

#4565 chore: add missing is empty check
  crates/transaction-pool/src/pool/mod.rs
Labels: C-perf, A-tx-pool

#4562 fix: enforce unsupported fork rules on get_payload_v3
  crates/payload/basic/src/lib.rs
  crates/payload/builder/src/lib.rs
  crates/payload/builder/src/service.rs
  crates/payload/builder/src/test_utils.rs
  crates/payload/builder/src/traits.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-bug, A-rpc, A-consensus, A-block-building, E-cancun

#4545 Update network.rs -- typo fix
  crates/net/network/src/network.rs
Labels: C-docs

#4570 docs: add note about eip-4844 broadcast
  crates/net/network/src/transactions.rs
Labels: C-docs

#4569 fix: ensure final message is always delivered
  crates/metrics/src/common/mpsc.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/mod.rs
Labels: C-bug, A-networking

#4574 chore: silence clippy clone warning
  crates/primitives/src/lib.rs
Labels: C-enhancement

#4578 chore(clippy): make clippy happy
  crates/rlp/src/encode.rs
  crates/storage/libmdbx-rs/src/codec.rs
Labels: C-docs

#4579 chore(ci): different clippy action
  .github/workflows/ci.yml
Labels: A-meta

#4581 feat: add missing caps
  crates/rpc/rpc-types/src/eth/engine/mod.rs
Labels: E-cancun

#4584 fix: limit payload bodies range by best block
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-bug

#4577 fix: use cached encoded length
  crates/net/network/src/transactions.rs
Labels: C-perf, A-networking

#4597 chore: new lint name
  crates/primitives/src/lib.rs
Labels: C-debt

#4598 chore: new clippy lints
  crates/net/network/src/test_utils/testnet.rs
Labels: C-debt

#4595 feat(state): storage revert iterator
  crates/storage/provider/src/change.rs
Labels: C-enhancement, A-execution

#4599 fix: remove popped tx from total set
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-bug, M-changelog, A-tx-pool

#4596 test(txpool): add replacement test
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool, C-test

#4594 chore(state): improve state change logs
  Cargo.lock
  crates/storage/provider/src/change.rs
Labels: A-execution, A-observability

#4605 fix(ci): valgrind installation
  .github/workflows/bench.yml
Labels: A-meta

#4610 fix(txpool): pending subpool basefee update
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/pool/size.rs
Labels: C-bug, A-tx-pool

#4606 test: add blob exclusive test e2e
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/tests/it/blobs.rs
  crates/transaction-pool/tests/it/main.rs
Labels: C-test

#4611 Make tx pool mock public
  crates/transaction-pool/src/test_utils/mock.rs
Labels: A-tx-pool

#4616 fix: holesky genesis
  crates/primitives/res/genesis/holesky.json
  crates/primitives/src/chain/spec.rs
Labels: C-bug

#4593 fix: return UnsupportedFork on V2 endpoints
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-bug, A-rpc, A-consensus, E-cancun

#4624 chore(deps): bump jsonrpsee 0.20.1
  Cargo.lock
Labels: A-dependencies

#4591 fix: apply FCU on invalid PayloadAttributes
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-bug, A-consensus, A-block-building

#4564 chore: demote session established log level
  crates/net/network/src/manager.rs
Labels: A-observability

#4623 test: add assert_invariants
  crates/transaction-pool/src/pool/blob.rs
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: A-tx-pool, C-test

#4633 fix: fill missing eip4844 settings
  crates/revm/revm-primitives/src/env.rs
Labels: M-eip

#4192 feat: enable size-limited file logs by default
  Cargo.lock
  bin/reth/src/cli/mod.rs
  crates/tracing/Cargo.toml
  crates/tracing/src/lib.rs
Labels: C-enhancement, M-changelog, A-cli, S-breaking

#4592 perf(rpc): fetch range of blocks and return empty if unchanged
  crates/rpc/rpc/src/eth/filter.rs
  crates/storage/provider/src/traits/block_hash.rs
Labels: C-bug, A-rpc

#4634 feat: use `mmap` in `NippyJar::load` and `NippyJarCursor`
  crates/storage/nippy-jar/src/cursor.rs
  crates/storage/nippy-jar/src/lib.rs
Labels: C-enhancement, A-bittorrent

#4638 chore: get rid of unreachable
  Cargo.lock
  crates/rpc/rpc/src/eth/error.rs
Labels: C-debt

#4637 refactor: use revm blob fee calc
  crates/payload/builder/src/payload.rs
  crates/primitives/src/constants/eip4844.rs
  crates/primitives/src/eip4844.rs
  crates/primitives/src/header.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/transaction-pool/src/maintain.rs
Labels: C-debt

#4639 chore: fix doc lints
  bin/reth/src/args/secret_key.rs
  crates/net/dns/src/resolver.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/downloaders/src/test_utils/file_client.rs
  crates/net/eth-wire/src/builder.rs
  crates/net/eth-wire/src/disconnect.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/eth-wire/src/types/status.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/transactions.rs
  crates/primitives/src/block.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/serde_helper/num.rs
  crates/revm/revm-inspectors/src/stack/mod.rs
  crates/revm/src/lib.rs
  crates/rpc/rpc/src/layers/auth_layer.rs
  crates/rpc/rpc/src/layers/jwt_secret.rs
  crates/rpc/rpc/src/layers/mod.rs
  crates/stages/src/pipeline/builder.rs
  crates/storage/libmdbx-rs/src/transaction.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/pool/blob.rs
Labels: A-meta

#4641 feat(bin): log prune config on startup
  bin/reth/src/node/mod.rs
Labels: C-enhancement, A-cli

#4644 feat: add max logs per response cli arg
  bin/reth/src/args/rpc_server_args.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/constants.rs
  crates/rpc/rpc-builder/src/eth.rs
Labels: C-enhancement, M-changelog, A-cli

#4646 feat(rpc): split `test_fee_history` in multiple tests
  crates/rpc/rpc/src/eth/api/server.rs
Labels: C-test

#4418 refactor: remove duplicate RPC namespaces from arguments
  bin/reth/src/args/rpc_server_args.rs
  crates/rpc/rpc-builder/src/lib.rs
Labels: C-bug, A-cli

#4655 perf: optimize engine poll loop
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-perf

#4457 feat: add pre-block EIP-4788 beacon root contract call
  crates/consensus/auto-seal/src/lib.rs
  crates/interfaces/src/executor.rs
  crates/payload/basic/src/lib.rs
  crates/primitives/src/constants/mod.rs
  crates/revm/Cargo.toml
  crates/revm/revm-primitives/src/config.rs
  crates/revm/revm-primitives/src/env.rs
  crates/revm/src/processor.rs
  crates/revm/src/state_change.rs
Labels: C-enhancement, A-execution, M-eip, E-cancun

#4658 fix: clear buffered blocks on sync
  crates/consensus/beacon/src/engine/sync.rs
Labels: C-bug, C-perf

#4186 feat: Duplicate Withdrawal and move try from impls to rpc-compat
  Cargo.lock
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/engine/mod.rs
  crates/payload/builder/Cargo.toml
  crates/payload/builder/src/payload.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/tests/it/auth.rs
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/payload.rs
  crates/rpc/rpc-engine-api/tests/it/payload.rs
  crates/rpc/rpc-types-compat/Cargo.toml
  crates/rpc/rpc-types-compat/src/engine/mod.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
  crates/rpc/rpc-types-compat/src/lib.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/eth/engine/mod.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
  crates/rpc/rpc-types/src/eth/mod.rs
  crates/rpc/rpc-types/src/eth/withdrawal.rs
Labels: C-debt

#4667 fix: deny unknown payload fields
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: C-bug, A-rpc, C-test, E-cancun

#4672 fix: set block env excess blob gas
  crates/revm/revm-primitives/src/env.rs
  crates/revm/src/processor.rs
Labels: C-bug, M-eip

#4675 fix: convert SpecId::Cancun to cancun precompile id
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: C-bug

#4668 feat(net): add helper functions to `TransactionsHandle` implementation
  crates/net/network/src/transactions.rs
Labels: C-enhancement, A-networking

#4666 chore: shorten info interval
  bin/reth/src/node/events.rs
Labels: A-observability

#4677 feat: add pyspec cancun tests to hive workflow
  .github/workflows/hive.yml
Labels: C-test, E-cancun

#4676 feat: validate blob_gas_used in header
  crates/consensus/common/src/validation.rs
  crates/interfaces/src/consensus.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: A-consensus, M-eip, E-cancun

#3899 feat(error): revamp `make_canonical` error
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/blockchain_tree/error.rs
  crates/interfaces/src/error.rs
Labels: C-debt, A-blockchain-tree

#4657 refactor(engine): always connect buffered blocks on r/w hook finish
  crates/consensus/beacon/src/engine/hooks/controller.rs
  crates/consensus/beacon/src/engine/hooks/mod.rs
  crates/consensus/beacon/src/engine/hooks/prune.rs
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#4601 feat: add perfect hashing function to `nippy-jar`
  Cargo.lock
  crates/storage/nippy-jar/Cargo.toml
  crates/storage/nippy-jar/src/compression/mod.rs
  crates/storage/nippy-jar/src/filter/cuckoo.rs
  crates/storage/nippy-jar/src/filter/mod.rs
  crates/storage/nippy-jar/src/lib.rs
  crates/storage/nippy-jar/src/phf/fmph.rs
  crates/storage/nippy-jar/src/phf/go_fmph.rs
  crates/storage/nippy-jar/src/phf/mod.rs
Labels: C-enhancement, A-snapshots

#4682 fix: add `test_zstd_no_dictionaries`
  crates/storage/nippy-jar/src/compression/zstd.rs
  crates/storage/nippy-jar/src/lib.rs
Labels: C-bug, A-bittorrent

#4692 feat(primitives): add `calculate_blob_gas_used` function in `SealedBlock`
  crates/consensus/common/src/validation.rs
  crates/primitives/src/block.rs
Labels: C-enhancement

#4696 chore: update revm and map new errors to rpc
  Cargo.lock
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/revm/revm-inspectors/src/tracing/js/bindings.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
  crates/rpc/rpc/src/eth/error.rs
Labels: A-rpc

#4693 feat(interfaces): better document `BlockchainTreeError`
  crates/interfaces/src/blockchain_tree/error.rs
Labels: C-docs

#4680 feat: add enough blob fee tx state
  crates/transaction-pool/src/pool/state.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: A-tx-pool

#4699 fix: add CANCUN to revm_spec_by_timestamp_after_merge
  crates/revm/revm-primitives/src/config.rs
Labels: C-bug, A-execution, A-block-building

#4681 chore: simplify get precompiles
  crates/revm/revm-inspectors/src/access_list.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: C-debt

#4622 feat: sets up offset logic on `nippy-jar`
  Cargo.lock
  crates/storage/nippy-jar/Cargo.toml
  crates/storage/nippy-jar/src/compression/mod.rs
  crates/storage/nippy-jar/src/compression/zstd.rs
  crates/storage/nippy-jar/src/cursor.rs
  crates/storage/nippy-jar/src/error.rs
  crates/storage/nippy-jar/src/filter/mod.rs
  crates/storage/nippy-jar/src/lib.rs
  crates/storage/nippy-jar/src/phf/fmph.rs
  crates/storage/nippy-jar/src/phf/go_fmph.rs
  crates/storage/nippy-jar/src/phf/mod.rs
Labels: C-enhancement, A-snapshots

#4687 refactor(engine): update sync state for r/w hooks
  crates/consensus/beacon/src/engine/hooks/mod.rs
  crates/consensus/beacon/src/engine/hooks/prune.rs
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#4683 feat: add a custom user header to `NippyJar`
  Cargo.lock
  crates/storage/nippy-jar/Cargo.toml
  crates/storage/nippy-jar/src/compression/mod.rs
  crates/storage/nippy-jar/src/compression/zstd.rs
  crates/storage/nippy-jar/src/cursor.rs
  crates/storage/nippy-jar/src/lib.rs
Labels: C-enhancement, A-bittorrent

#4711 (chore) surface block hash for MissingTotalDifficulty error
  crates/interfaces/src/executor.rs
Labels: C-debt

#4612 fix(tree): retain `max(additional, max_reorg_depth)` block hashes
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/config.rs
  crates/interfaces/src/blockchain_tree/mod.rs
Labels: C-debt, A-blockchain-tree

#4665 feat: add updated beacon root contract address
  crates/primitives/src/constants/mod.rs
  crates/revm/src/processor.rs
Labels: S-blocked, A-execution, M-eip, E-cancun

#4719 remove deprecated log line
  etc/docker-compose.yml
Labels: C-debt

#4512 feat: add `nippy-jar` format for snapshots
  Cargo.lock
  Cargo.toml
  crates/storage/nippy-jar/Cargo.toml
  crates/storage/nippy-jar/src/compression/mod.rs
  crates/storage/nippy-jar/src/compression/zstd.rs
  crates/storage/nippy-jar/src/cursor.rs
  crates/storage/nippy-jar/src/error.rs
  crates/storage/nippy-jar/src/filter/cuckoo.rs
  crates/storage/nippy-jar/src/filter/mod.rs
  crates/storage/nippy-jar/src/lib.rs
  crates/storage/nippy-jar/src/phf/fmph.rs
  crates/storage/nippy-jar/src/phf/go_fmph.rs
  crates/storage/nippy-jar/src/phf/mod.rs
Labels: C-enhancement, A-snapshots

#4723 chore: bump revm
  Cargo.lock
  Cargo.toml
  crates/payload/builder/src/payload.rs
  crates/primitives/src/eip4844.rs
  crates/primitives/src/header.rs
  crates/revm/revm-primitives/src/env.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/error.rs
Labels: M-eip, E-cancun

#4725 feat(interfaces): better documentation for `ConsensusError`
  crates/interfaces/src/consensus.rs
Labels: C-docs, A-consensus

#4726 feat: add merge and pre-merge pyspec jobs
  .github/workflows/hive.yml
Labels: C-enhancement, C-test

#4729 chore: fix flaky test
  crates/net/network/tests/it/connect.rs
Labels: C-test

#4728 feat(CI): add timeout to CI
  .github/workflows/book.yml
  .github/workflows/ci.yml
  .github/workflows/integration.yml
  .github/workflows/unit.yml
Labels: C-test, A-meta

#4732 fix: add slash to match only fork suites
  .github/workflows/hive.yml
Labels: C-bug, C-test

#4733 fix: allow unknown fields in ExecutionPayloadV1
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: C-bug, A-rpc, A-consensus

#4688 support EIP-4844 transaction when building pending block
  crates/revm/src/state_change.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
Labels: A-rpc, M-eip

#4603 perf/refactor: use tokio_util::sync::PollSender for ActiveSession -> SessionManager messages
  Cargo.lock
  crates/metrics/Cargo.toml
  crates/metrics/src/common/mpsc.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/mod.rs
Labels: C-debt, C-perf, A-devp2p, A-networking

#4744 fix(hive): jobs need experimental flag
  .github/workflows/hive.yml
Labels: C-bug, C-test

#4722 feat(txpool) add blob transaction sidecar listeners
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/tests/it/blobs.rs
Labels: A-tx-pool

#4747 fix: export self::zstd
  crates/storage/nippy-jar/src/compression/mod.rs
Labels: C-bug

#4751 chore: drop `smol_str`
  Cargo.lock
  crates/net/eth-wire/Cargo.toml
  crates/net/eth-wire/src/capability.rs
Labels: A-dependencies

#4753 (chore) fix reth book dockercmd with correct datadir path for volume
  book/installation/docker.md
Labels: C-docs

#4746 fix: block overrides inconsistencies
  crates/rpc/rpc-types/src/eth/block.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: M-changelog, A-rpc
