Repository paradigmxyz/reth, pull requests merged in 2023-07, with the labels that each got.

#3508 chore(download): bodies downloader size limit
  bin/reth/src/stage/run.rs
  crates/config/src/config.rs
  crates/net/downloaders/src/bodies/bodies.rs
Labels: A-downloaders

#3519 chore(rpc): split cache into multiple files
  crates/rpc/rpc/src/eth/cache/config.rs
  crates/rpc/rpc/src/eth/cache/metrics.rs
  crates/rpc/rpc/src/eth/cache/mod.rs
  crates/rpc/rpc/src/eth/cache/multi_consumer.rs
Labels: C-debt, A-rpc

#3521 fix(book): typo
  book/intro.md
Labels: C-docs

#3367 feat(error): add wrappers for `std::fs` methods to track path for errors
  bin/reth/src/args/secret_key.rs
  bin/reth/src/args/utils.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/debug_cmd/merkle.rs
  bin/reth/src/stage/drop.rs
  bin/reth/src/test_vectors/tables.rs
  bin/reth/src/utils.rs
  crates/primitives/src/fs.rs
  crates/primitives/src/lib.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/layers/jwt_secret.rs
  crates/storage/db/benches/criterion.rs
  crates/storage/db/benches/hash_keys.rs
  crates/storage/db/benches/utils.rs
Labels: C-enhancement

#3532 chore: rustfmt
  crates/blockchain-tree/src/block_indices.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/nat/src/lib.rs
  crates/net/network/src/eth_requests.rs
  crates/net/network/src/peers/manager.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/storage/provider/src/chain.rs
  crates/trie/src/walker.rs
Labels: C-debt

#3531 docs: add additional context to internal tracing error
  crates/rpc/rpc/src/eth/error.rs
Labels: C-docs

#3526 fix: precompile condition
  crates/revm/revm-inspectors/src/tracing/mod.rs
Labels: C-bug, A-rpc

#3525 chore: add TaskManager must_use annotation
  crates/tasks/src/lib.rs
Labels: C-debt

#3501 feat: add another distance check
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/shareable.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/blockchain_tree/mod.rs
  crates/storage/provider/src/providers/mod.rs
Labels: C-perf, A-consensus

#3491 fix: add block rewards to `trace_block`
  Cargo.lock
  bin/reth/src/args/rpc_server_args.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/trace.rs
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/mod.rs
  crates/storage/provider/src/traits/receipts.rs
  crates/storage/provider/src/traits/spec.rs
Labels: C-bug, M-changelog, A-rpc

#3540 chore: fix clippy
  .github/workflows/ci.yml
  Cargo.lock
  crates/blockchain-tree/src/block_buffer.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/revm/revm-inspectors/src/access_list.rs
  crates/revm/src/executor.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/pubsub.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/storage/codecs/derive/src/lib.rs
  crates/storage/libmdbx-rs/Cargo.toml
  crates/storage/libmdbx-rs/src/cursor.rs
  crates/storage/libmdbx-rs/src/transaction.rs
  crates/storage/provider/src/chain.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/test_utils/executor.rs
  crates/trie/src/updates.rs
Labels: C-debt

#3543 fix(codec): fix last field compilation check
  crates/storage/codecs/derive/src/compact/generator.rs
  crates/storage/codecs/derive/src/compact/structs.rs
  crates/storage/codecs/derive/src/lib.rs
Labels: C-bug, A-db

#3541 perf: join futures in tracing
  crates/rpc/rpc/src/trace.rs
Labels: C-perf, A-rpc

#3536 feat: add NoopTransactionPool impl
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/test_utils/mod.rs
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#3539 nit: spelling
  docs/design/database.md
Labels: C-debt

#3418 chore: run tests with coverage in `Makefile`
  .gitignore
  Makefile
Labels: C-enhancement, A-meta

#3482 fix: create a test db with path
  crates/stages/src/test_utils/test_db.rs
Labels: C-bug, C-test

#3545 docs: add payload builder example
  crates/payload/builder/src/lib.rs
Labels: C-docs

#3524 feat(bin, storage): configurable MDBX log level
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/args/database_args.rs
  bin/reth/src/args/debug_args.rs
  bin/reth/src/args/gas_price_oracle_args.rs
  bin/reth/src/args/mod.rs
  bin/reth/src/chain/import.rs
  bin/reth/src/chain/init.rs
  bin/reth/src/db/mod.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/debug_cmd/merkle.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/p2p/mod.rs
  bin/reth/src/stage/drop.rs
  bin/reth/src/stage/dump/mod.rs
  bin/reth/src/stage/run.rs
  bin/reth/src/stage/unwind.rs
  crates/interfaces/Cargo.toml
  crates/interfaces/src/db.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/lib.rs
  crates/storage/libmdbx-rs/benches/cursor.rs
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/libmdbx-rs/src/lib.rs
  crates/storage/provider/src/providers/database/mod.rs
  examples/db-access.rs
  examples/rpc-db.rs
Labels: C-enhancement, A-db, A-observability

#3496 feat: add docker compose with docs
  book/installation/docker.md
  etc/.gitignore
  etc/README.md
  etc/docker-compose.yml
  etc/docker-monitoring.yml
  etc/generate-jwt.sh
  etc/prometheus/prometheus.yml
Labels: C-enhancement, A-meta

#3548 chore: export `TransactionPoolExt` trait
  crates/transaction-pool/src/lib.rs
Labels: C-debt, A-tx-pool

#3549 fix(rpc): fix parity tracing config
  crates/revm/revm-inspectors/src/tracing/config.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-bug, M-changelog, A-rpc

#3546 docs: minimum docker engine version
  book/installation/docker.md
Labels: C-enhancement, A-meta

#3552 docs: update rpc cache flags
  book/cli/node.md
Labels: C-docs, C-enhancement

#3563 fix: add missing single block body download validation
  crates/interfaces/src/p2p/full_block.rs
  crates/primitives/src/peer.rs
Labels: C-bug, A-consensus

#3556 chore: add stale workflow
  .github/workflows/stale.yml
Labels: C-enhancement, A-meta

#3564 chore(`crates`): deprecate `staged-sync`
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  bin/reth/src/chain/import.rs
  bin/reth/src/chain/init.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/init.rs
  bin/reth/src/lib.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/drop.rs
  codecov.yml
  crates/net/network/Cargo.toml
  crates/net/network/tests/it/clique/clique.rs
  crates/net/network/tests/it/clique/clique_middleware.rs
  crates/net/network/tests/it/clique/mod.rs
  crates/net/network/tests/it/geth.rs
  crates/net/network/tests/it/main.rs
  crates/staged-sync/Cargo.toml
  crates/staged-sync/src/lib.rs
  crates/staged-sync/src/utils/mod.rs
  docs/repo/layout.md
Labels: C-debt

#3575 feat(cli): txpool args
  bin/reth/src/args/mod.rs
  bin/reth/src/args/txpool_args.rs
  bin/reth/src/node/mod.rs
  crates/transaction-pool/src/config.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-enhancement, M-changelog, A-tx-pool, A-cli

#3572 docs(trie): hashed post state & cursors
  crates/storage/provider/src/post_state/mod.rs
  crates/storage/provider/src/traits/state.rs
  crates/trie/src/hashed_cursor/post_state.rs
Labels: C-docs, A-trie

#3565 feat(txpool): all transactions event listener
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/events.rs
  crates/transaction-pool/src/pool/listener.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/traits.rs
Labels: C-enhancement, A-tx-pool

#3590 refactor: extract on pipeline finished
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#3582 perf: put all prefix sets in Rc
  crates/trie/benches/prefix_set.rs
  crates/trie/src/hashed_cursor/post_state.rs
  crates/trie/src/prefix_set/loader.rs
  crates/trie/src/prefix_set/mod.rs
  crates/trie/src/trie.rs
  crates/trie/src/walker.rs
Labels: C-perf, A-trie

#3589 fix: use DatabaseRef impl when fetching overriden account
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: C-bug, A-rpc

#3584 perf: better engine downloads
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-perf, A-consensus

#3593 fix: use same stale label for prs
  .github/workflows/stale.yml
Labels: C-bug, A-meta

#3586 test: add test for state override json
  crates/rpc/rpc-types/src/eth/state.rs
Labels: C-test

#3578 feat: add cargo binstall support
  Cargo.toml
  book/installation/binaries.md
Labels: C-enhancement

#3598 chore: change field TransactionTrace order
  crates/rpc/rpc-types/src/eth/trace/parity.rs
Labels: C-debt, A-rpc

#3599 fix(book): change recommended `--authrpc.port` value from 9999 to 8551
  book/run/mainnet.md
Labels: C-docs

#3596 docs: add transaction pool example
  bin/reth/src/node/mod.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: C-docs

#3040 perf: only record return value if required
  crates/revm/revm-inspectors/src/tracing/builder/geth.rs
  crates/revm/revm-inspectors/src/tracing/config.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: C-perf, A-rpc

#3573 feat: add ethereum-metrics-exporter
  book/installation/docker.md
  etc/docker-compose.yml
  etc/ethereum-metrics-exporter/config.yaml
  etc/generate-jwt.sh
  etc/grafana/dashboards/metrics-exporter.json
  etc/lighthouse.yml
  etc/prometheus/prometheus.yml
Labels: C-enhancement, A-meta

#3588 perf(trie): post state cursors
  crates/storage/provider/src/post_state/mod.rs
  crates/trie/src/hashed_cursor/post_state.rs
Labels: M-changelog, C-perf, A-trie

#3605 refactor: extract exceeds pipeline threshold
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#3613 ci: remove broken book workflow
  .github/workflows/book.yml
Labels: C-bug, A-meta

#3608 fix: correct types in `libmdbx-rs` for windows
  crates/storage/libmdbx-rs/src/cursor.rs
  crates/storage/libmdbx-rs/src/database.rs
  crates/storage/libmdbx-rs/src/flags.rs
  crates/storage/libmdbx-rs/src/transaction.rs
Labels: C-bug, A-db

#3609 docs: note that only wsl2 works
  book/installation/source.md
Labels: C-docs, C-enhancement

#3208 feat(rpc): use log indices for address and topic filters
  Cargo.lock
  bin/reth/src/args/rpc_server_args.rs
  crates/consensus/common/src/validation.rs
  crates/primitives/src/integer_list.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/filter.rs
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/block.rs
  crates/storage/provider/src/traits/header.rs
  crates/storage/provider/src/traits/logs.rs
  crates/storage/provider/src/traits/mod.rs
  crates/storage/provider/src/traits/receipts.rs
Labels: S-blocked, M-changelog, A-rpc

#3611 feat: add error field to parity transaction traces
  crates/revm/revm-inspectors/src/tracing/types.rs
  crates/rpc/rpc-types/src/eth/trace/parity.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-enhancement, A-rpc

#3416 feat: download block ranges
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/interfaces/src/p2p/full_block.rs
  crates/interfaces/src/test_utils/full_block.rs
  crates/primitives/src/block.rs
  crates/primitives/src/header.rs
  crates/primitives/src/lib.rs
Labels: C-enhancement, M-changelog, A-consensus, A-networking

#3621 chore: add commit to client version
  bin/reth/src/version.rs
Labels: C-enhancement, A-rpc

#3623 chore(engine): warn on inconsistent pipeline
  crates/consensus/beacon/src/engine/mod.rs
Labels: A-consensus, A-observability

#3622 chore: remove network-api test-utils feature
  crates/net/network-api/Cargo.toml
  crates/net/network-api/src/lib.rs
  crates/net/network-api/src/noop.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  examples/Cargo.toml
  examples/db-access.rs
  examples/rpc-db.rs
Labels: C-debt, A-rpc

#3627 fix: populate transaction trace error field
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: A-rpc

#3630 fix: rm outdated flatten
  crates/rpc/rpc-types/src/eth/trace/parity.rs
Labels: C-bug, A-rpc

#3636 fix: put attribute on correct line
  crates/rpc/rpc-types/src/eth/trace/parity.rs
Labels: C-bug, A-rpc

#3633 chore: move BeaconConsensusEngineHandle to separate file
  crates/consensus/beacon/src/engine/handle.rs
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#3635 fix(docs): fix malformed link
  .github/workflows/release.yml
Labels: C-docs

#3637 fix: rm bad flatten
  crates/rpc/rpc-types/src/eth/trace/parity.rs
Labels: C-bug, A-rpc

#3640 Match statement for handling error messages - reverted and default case
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: A-rpc

#3632 test: use concrete type for arbitrary strategy
  crates/storage/db/src/tables/utils.rs
Labels: C-perf, C-test

#3642 fix(txpool): emit replaced events
  crates/transaction-pool/src/pool/listener.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-bug, A-tx-pool

#3606 chore(prometheus): add `localhost:9001` scrape target
  book/installation/docker.md
  etc/prometheus/prometheus.yml
Labels: A-observability

#3652 add build profile to version info
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/version.rs
Labels: A-cli

#3646 chore: add missing helper functions and docs
  crates/transaction-pool/src/pool/state.rs
Labels: A-tx-pool

#3653 chore(txpool): enriched pool transaction event
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/events.rs
  crates/transaction-pool/src/pool/listener.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#3656 fix: subpool variant order
  crates/transaction-pool/src/pool/state.rs
Labels: A-tx-pool

#3663 test: tmp ignore another flaky geth test
  crates/net/network/tests/it/connect.rs
Labels: C-test

#3644 pop duplicates entries when returning downloaded blocks in engine
  crates/consensus/beacon/src/engine/sync.rs
Labels: C-perf, A-consensus

#3660 feat: support all alias
  crates/rpc/rpc-builder/src/lib.rs
Labels: A-rpc, A-cli

#3659 chore: add a few noop functions to builder
  crates/rpc/rpc-builder/src/lib.rs
Labels: C-enhancement, A-rpc

#3664 Add propagate field to TransactionValidationOutcome
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/mod.rs
Labels: A-tx-pool

#3669 add build profile to version info take II
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/version.rs
Labels: A-cli

#3680 fix: expose call method so a consumer can use it
  crates/rpc/rpc/src/eth/api/call.rs
Labels: C-debt

#3671 fix(tree): update metrics only on canonical/side chain changes
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/shareable.rs
Labels: C-bug, A-observability

#3670 feat(stages): trace log for metric event receive
  crates/stages/src/metrics/listener.rs
Labels: A-observability

#3684 chore: use units on dashboard
  etc/grafana/dashboards/overview.json
Labels: C-enhancement, A-observability

#3686 fix: expose the revm_utils to consumer as needed structs from it
  crates/rpc/rpc/src/eth/mod.rs
Labels: C-debt

#3668 feat: add subpool transaction streams
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/traits.rs
Labels: C-enhancement, A-tx-pool

#3677 feat: enforce txpool propagation setting
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-enhancement, A-tx-pool

#3587 feat(config, primitives): validate Receipts prune part
  crates/config/src/config.rs
  crates/primitives/src/serde_helper/mod.rs
  crates/primitives/src/serde_helper/prune.rs
Labels: C-enhancement, A-pruning

#3662 feat: run pipeline if latest finalized is far from pipeline progress
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-enhancement, C-perf, A-consensus

#3649 feat: add full pending txs to stream
  crates/rpc/rpc-types/src/eth/pubsub.rs
  crates/rpc/rpc/src/eth/pubsub.rs
Labels: A-tx-pool

#2803 test: add payload status error serde tests
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: C-debt

#3618 style: replace next_sync_target Receiver loop with call to `wait_for`
  crates/stages/src/stages/headers.rs
Labels: C-debt, A-downloaders

#3643 test: `eth_getProof` without storage proof
  crates/rpc/rpc-types/src/eth/account.rs
Labels: A-rpc, C-test

#3689 chore(prometheus): add host.docker.internal:9001 scrape target
  etc/prometheus/prometheus.yml
Labels: A-observability

#3585 feat(pruning): prune `Receipts` during pipeline
  Cargo.lock
  bin/reth/src/chain/import.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/debug_cmd/merkle.rs
  bin/reth/src/init.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/dump/merkle.rs
  bin/reth/src/stage/run.rs
  crates/config/src/config.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/lib.rs
  crates/primitives/src/prune/mod.rs
  crates/primitives/src/prune/mode.rs
  crates/primitives/src/prune/target.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/execution.rs
  crates/storage/provider/src/post_state/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-enhancement, A-staged-sync, A-pruning

#3675 fix: transaction calls on the reth-provider should not generate a hash by default
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/transactions.rs
Labels: C-perf, A-db

#3711 docs: how to enable JSON-RPC endpoints for http/ws
  book/jsonrpc/intro.md
Labels: C-docs

#3715 feat: add txpool maintain metrics
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/metrics.rs
Labels: A-tx-pool, A-observability

#3685 perf: handle engine API range request in a new task
  Cargo.lock
  bin/reth/src/node/mod.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-perf, A-rpc

#3716 fix: treat bool params as invalid in logs subscription
  crates/rpc/rpc-types/src/eth/pubsub.rs
  crates/rpc/rpc/src/eth/pubsub.rs
Labels: A-rpc

#3718 chore: use `transaction_by_id_no_hash` to avoid hash computation
  crates/stages/src/stages/sender_recovery.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-enhancement, A-db

#3603 docs: add a few more docs to ControlFlow
  crates/consensus/beacon/src/engine/mod.rs
  crates/stages/src/pipeline/ctrl.rs
  crates/stages/src/pipeline/mod.rs
Labels: C-docs

#3719 fix: use tx gas limit for root trace
  crates/revm/revm-inspectors/src/tracing/mod.rs
Labels: A-rpc

#3720 fix: register precompiles correctly
  crates/revm/revm-inspectors/src/tracing/js/mod.rs
Labels: A-rpc

#3727 fix: use engine responses to progress autoseal mining task
  crates/consensus/auto-seal/src/task.rs
  crates/consensus/beacon/src/engine/message.rs
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-bug, A-consensus, A-utils

#3730 fix: perform forkchoice update consistency checks
  crates/blockchain-tree/src/shareable.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/blockchain_tree/mod.rs
  crates/storage/provider/src/providers/mod.rs
Labels: C-bug, A-consensus, C-test

#3731 fix(consensus): call `finalize_block` when finalized block changes.
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-bug, A-consensus

#3529 feat: complete vm and statediff tracers
  crates/revm/revm-inspectors/src/tracing/builder/mod.rs
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/revm/revm-inspectors/src/tracing/builder/walker.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: C-enhancement, M-changelog, A-rpc

#3736 fix: serialize selfdestruct as suicide
  crates/rpc/rpc-types/src/eth/trace/parity.rs
Labels: A-rpc

#3744 chore(storage): transactions -> receipts in `receipts_by_block`
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-debt, A-db

#3729 #3667 Add Dial Success Metric
  crates/net/network/src/metrics.rs
  crates/net/network/src/session/mod.rs
Labels: A-observability

#3757 test: ignore another flaky geth test
  crates/net/network/tests/it/connect.rs
Labels: C-test

#3758 chore: reorder call action fields
  crates/rpc/rpc-types/src/eth/trace/parity.rs
Labels: A-rpc

#3761 fix: poll logic when pipeline active
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-bug, A-consensus

#3762 fix: return null withdrawals
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: C-bug, A-consensus

#3767 chore: add some txs helpers
  crates/primitives/src/transaction/mod.rs
Labels: C-debt

#3770 fix(rpc): serialize traces always as vec
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/rpc/rpc-types/src/eth/trace/parity.rs
Labels: A-rpc

#3772 fix(rpc): make trace filter req field hex or decimal
  crates/primitives/src/serde_helper/num.rs
  crates/rpc/rpc-types/src/eth/trace/filter.rs
Labels: C-bug, A-rpc

#3773 perf: only lookup in db in cache layer
  crates/rpc/rpc/src/eth/cache/mod.rs
Labels: A-consensus, A-db

#3766 fix: add missing null check
  crates/rpc/rpc-types/src/eth/trace/geth/mod.rs
Labels: C-bug, A-rpc

#3777 adding row for total db size in db stats command
  bin/reth/src/db/mod.rs
Labels: C-enhancement, A-cli

#3779 fix: add unknown block error
  crates/rpc/rpc-types/src/eth/error.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/storage/provider/src/traits/block_id.rs
Labels: A-rpc

#3735 chore: enable jemalloc by default on unix
  bin/reth/Cargo.toml
  bin/reth/src/lib.rs
  bin/reth/src/main.rs
  bin/reth/src/prometheus_exporter.rs
Labels: C-perf

#3780 feat: remove peers after several unsuccessful attempts
  crates/config/src/config.rs
  crates/net/network/src/error.rs
  crates/net/network/src/peers/manager.rs
Labels: C-perf, A-networking

#3783 fix: remove single body response check
  crates/net/downloaders/src/bodies/request.rs
Labels: C-bug, A-networking

#3666 chore: make some session types pub
  crates/net/network/src/lib.rs
  crates/net/network/src/session/handle.rs
  crates/net/network/src/session/mod.rs
Labels: C-enhancement, A-devp2p, A-networking

#3788 chore(downloader): simplify bodies task polling
  crates/net/downloaders/src/bodies/task.rs
Labels: C-debt, A-downloaders

#3645 chore(tree): remove revert notification
  crates/storage/provider/src/traits/chain.rs
  crates/transaction-pool/src/maintain.rs
Labels: C-debt, A-blockchain-tree

#3789 feat: trim cmd args in parser
  bin/reth/src/args/rpc_server_args.rs
  crates/rpc/rpc-builder/src/lib.rs
Labels: A-rpc, A-cli

#3755 feat: txpool block building fallback
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-enhancement, A-rpc

#3790 fix: concurrent ipc driver impl
  Cargo.lock
  crates/rpc/ipc/Cargo.toml
  crates/rpc/ipc/src/server/connection.rs
  crates/rpc/ipc/src/server/mod.rs
Labels: C-perf, A-rpc

#3791 fix: rpc cap block range correctly
  crates/rpc/rpc/src/eth/api/fees.rs
Labels: A-rpc

#3732 feat: reload dirty accounts if pool drifts
  Cargo.lock
  bin/reth/src/node/mod.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#3737 feat(txpool): add best_with_base_fee
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/ordering.rs
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/traits.rs
Labels: C-enhancement, A-tx-pool

#3479 bug(stages): TxLookup/Sender stages fix range if there is no tx
  bin/reth/src/stage/drop.rs
  crates/stages/src/stage.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/test_utils/test_db.rs
Labels: C-bug, M-changelog, A-staged-sync, C-perf

#3748 feat: better blocksize heuristics
  book/run/config.md
  crates/config/src/config.rs
  crates/interfaces/src/p2p/bodies/response.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/request.rs
  crates/net/downloaders/src/metrics.rs
  crates/primitives/src/block.rs
  crates/primitives/src/header.rs
  crates/primitives/src/transaction/access_list.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/signature.rs
  crates/primitives/src/withdrawal.rs
  etc/grafana/dashboards/overview.json
Labels: C-bug, C-enhancement, A-networking, A-downloaders

#3796 fix(stages): update entities metrics on `SyncHeight` event
  crates/stages/src/metrics/listener.rs
Labels: A-observability

#3804 chore: use best with base fee
  crates/payload/basic/src/lib.rs
Labels: A-block-building

#3707 feat:new discovered node record event stream
  crates/net/network/src/discovery.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/state.rs
Labels: C-enhancement, A-networking

#3458 feat: make rpc gas cap configurable
  bin/reth/src/args/rpc_server_args.rs
  book/cli/node.md
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-enhancement, M-changelog, A-rpc

#3808 chore: bump version .alpha4
  Cargo.lock
  Cargo.toml
Labels: M-changelog

#3800 feat: add `yParity` to rpc signatures
  crates/rpc/rpc-types/src/eth/transaction/mod.rs
  crates/rpc/rpc-types/src/eth/transaction/signature.rs
Labels: C-enhancement, A-rpc

#3809 feat: add network txpool example
  Cargo.lock
  examples/Cargo.toml
  examples/network-txpool.rs
Labels: C-enhancement

#3812 chore: use 50M default gas limit for calls in rpc
  bin/reth/src/args/rpc_server_args.rs
  crates/rpc/rpc-builder/src/constants.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
  crates/rpc/rpc/src/trace.rs
Labels: A-rpc

#3820 chore(deps): bump some deps
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  crates/primitives/Cargo.toml
  crates/primitives/src/chain/mod.rs
  crates/rpc/rpc-builder/Cargo.toml
Labels: A-dependencies

#3823 chore: fix SessionManagerMetrics typo
  crates/net/network/src/metrics.rs
  crates/net/network/src/session/mod.rs
Labels: C-bug, A-observability

#3827 chore: make clippy happy
  bin/reth/src/init.rs
  bin/reth/src/stage/dump/execution.rs
  bin/reth/src/stage/dump/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/primitives/src/hex_bytes.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/rlp/benches/bench.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc-types/src/eth/fee.rs
  crates/trie/src/hashed_cursor/post_state.rs
Labels: C-debt

#3811 feat: build local pending block
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: A-rpc

#3833 feat: add timestamp to pool update
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#3837 fix: map more errors to messages
  crates/revm/revm-inspectors/src/tracing/config.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: A-rpc

#3828 feat: add builder type for eth tx validator
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/mod.rs
Labels: A-tx-pool

#3768 feat: implement reth_getBalanceChangesInBlock
  bin/reth/src/args/rpc_server_args.rs
  crates/rpc/rpc-api/src/lib.rs
  crates/rpc/rpc-api/src/reth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/lib.rs
  crates/rpc/rpc/src/reth.rs
  crates/storage/provider/src/lib.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/account.rs
  crates/storage/provider/src/traits/mod.rs
Labels: C-enhancement, A-rpc

#3839 feat: let consensus tests configure pipeline, executor, and client
  Cargo.lock
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-enhancement, A-consensus, C-test

#3838 feat(book): more precise disk requirements
  book/installation/installation.md
Labels: C-docs

#3840 chore: set trace result to null if non revert or selfdestruct
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: A-rpc

#3842 feat: add key gen util and simple fcu validation test with custom alloc
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/test_utils/generators.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/util.rs
Labels: C-enhancement, A-consensus, C-test

#3778 feat(rpc): Add ots_ namespace and trait bindings for Otterscan Endpoints
  crates/rpc/rpc-api/src/lib.rs
  crates/rpc/rpc-api/src/otterscan.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-types/src/lib.rs
  crates/rpc/rpc-types/src/otterscan.rs
  crates/rpc/rpc/src/lib.rs
  crates/rpc/rpc/src/otterscan.rs
Labels: A-rpc
