Repository paradigmxyz/reth, pull requests merged in 2023-08, with the labels that each got.

#4005 chore: add example how to install additional rpc namespace
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  bin/reth/src/cli/mod.rs
  bin/reth/src/lib.rs
  bin/reth/src/node/mod.rs
  crates/rpc/rpc-builder/src/lib.rs
  examples/additional-rpc-namespace-in-cli/Cargo.toml
  examples/additional-rpc-namespace-in-cli/src/main.rs
Labels: A-cli

#4016 chore: add subkey docs to `StorageEntry`
  crates/primitives/src/storage.rs
Labels: C-docs, A-db

#4015 chore: fix `PrefixSetMut` doc comment
  crates/trie/src/prefix_set/mod.rs
Labels: C-docs, C-enhancement, A-trie

#4007 feat(rpc): ots_getBlockDetails and ots_getBlockDetailsByHash
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-types/src/eth/block.rs
  crates/rpc/rpc-types/src/otterscan.rs
  crates/rpc/rpc/src/otterscan.rs
Labels: A-rpc

#3912 feat(pruner): transaction senders
  crates/primitives/src/prune/target.rs
  crates/prune/src/pruner.rs
  crates/stages/src/stages/sender_recovery.rs
  crates/stages/src/test_utils/test_db.rs
Labels: C-enhancement, A-pruning

#4020 fix(txpool): clone impl for `FullTransactionEvent`
  crates/transaction-pool/src/pool/events.rs
Labels: C-bug, A-tx-pool

#3921 fix: record selfdstructs properly
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: C-bug, M-changelog, A-rpc

#4018 chore(stages): remove unnecessary prune configuration from history index stages
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/mod.rs
Labels: C-debt, A-db

#4019 test(txpool): listener it tests
  Cargo.lock
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/tests/it/listeners.rs
  crates/transaction-pool/tests/it/main.rs
Labels: A-tx-pool, C-test

#4010 feat(engine): payload cancun fields
  crates/consensus/auto-seal/src/lib.rs
  crates/payload/basic/src/lib.rs
  crates/rpc/rpc-types/src/eth/block.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  testing/ef-tests/src/models.rs
Labels: C-enhancement, A-consensus, E-cancun

#4024 feat(cli): add max peer args
  bin/reth/src/args/network_args.rs
  crates/net/network/src/peers/manager.rs
Labels: M-changelog, A-cli

#4023 feat(pruner): metrics
  Cargo.lock
  bin/reth/src/node/mod.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/prune/Cargo.toml
  crates/prune/src/lib.rs
  crates/prune/src/metrics.rs
  crates/prune/src/pruner.rs
Labels: C-enhancement, A-observability, A-pruning

#4000 feat(pruner): account history
  crates/interfaces/src/test_utils/generators.rs
  crates/prune/src/pruner.rs
  crates/stages/benches/setup/mod.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-enhancement, A-pruning

#4006 feat(pruner): storage history
  crates/prune/src/pruner.rs
  crates/rpc/rpc-builder/src/lib.rs
Labels: C-enhancement, A-pruning

#3954 feat(engine): require `VALID` latest FCU status before pruning
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-enhancement, A-pruning

#4036 chore: make ipcpath arg default
  bin/reth/src/args/rpc_server_args.rs
Labels: A-cli

#4034 fix: validate headers in full block downloader
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/interfaces/src/consensus.rs
  crates/interfaces/src/p2p/full_block.rs
Labels: M-changelog, A-consensus, A-downloaders

#4025 feat(prune): don't prune changesets if taking an incremental hashing/trie route
  bin/reth/src/chain/import.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/debug_cmd/merkle.rs
  bin/reth/src/node/mod.rs
  bin/reth/src/stage/dump/merkle.rs
  bin/reth/src/stage/run.rs
  crates/stages/benches/criterion.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/mod.rs
  crates/storage/provider/src/post_state/mod.rs
Labels: C-enhancement, A-staged-sync

#4038 chore: ignore ef blobTx test
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: C-test

#4031 chore: dont penalize on dropped connections
  crates/net/network/src/transactions.rs
Labels: A-networking

#4027 Fix: successful execution of 'reth stage --commit' did not write results to the database
  bin/reth/src/stage/run.rs
Labels: C-bug, M-changelog, A-cli

#4039 perf: spawn ipc requests
  crates/rpc/ipc/src/server/mod.rs
Labels: M-changelog, C-perf, A-rpc

#3878 feat: add erigons debugTraceCallMany
  crates/rpc/rpc-api/src/debug.rs
  crates/rpc/rpc-types/src/eth/call.rs
  crates/rpc/rpc-types/src/eth/mod.rs
  crates/rpc/rpc/src/debug.rs
Labels: C-enhancement, M-changelog, A-rpc

#4043 fix(engine, pruner): prune poll logic, history indices
  crates/consensus/beacon/src/engine/forkchoice.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/prune/src/pruner.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-bug, A-pruning

#4047 chore: move call op match to fn
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: C-debt

#4046 feat: populate gas cost for vm instructions
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
Labels: M-changelog, A-rpc

#4050 fix: only propagate txs that are allowed to be propagated
  crates/net/network/src/transactions.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/test_utils/mod.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/mod.rs
  crates/transaction-pool/tests/it/listeners.rs
Labels: M-changelog, A-tx-pool

#4022 feat: extend RethCliExt with payload builder
  bin/reth/src/args/payload_builder_args.rs
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/cli/config.rs
  bin/reth/src/cli/ext.rs
  bin/reth/src/cli/mod.rs
  bin/reth/src/node/mod.rs
  examples/additional-rpc-namespace-in-cli/src/main.rs
Labels: A-cli

#4061 fix(pruner): tx number range with genesis
  crates/prune/src/pruner.rs
Labels: C-test, A-pruning

#4059 (feat):add private variant in tx origin
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: M-changelog, A-tx-pool

#4068 chore(engine): downgrade new payload buffering log to debug
  crates/consensus/beacon/src/engine/mod.rs
Labels: A-observability

#4058 chore: make txpool cargo test compile
  Cargo.toml
  bin/reth/Cargo.toml
  crates/interfaces/Cargo.toml
  crates/net/eth-wire/Cargo.toml
  crates/primitives/Cargo.toml
  crates/storage/codecs/Cargo.toml
  crates/storage/db/Cargo.toml
  crates/transaction-pool/Cargo.toml
  crates/trie/Cargo.toml
Labels: C-debt

#4067 chore: explicitly set max allowed connections for auth server
  crates/rpc/rpc-builder/src/auth.rs
Labels: A-rpc

#4053 feat(txpool) feed new pending transactions to BestTxns iterator
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/tests/it/main.rs
  crates/transaction-pool/tests/it/pending.rs
Labels: A-tx-pool

#4079 chore: relax network blockreader trait bounds
  crates/net/network/src/manager.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
Labels: C-debt, A-networking

#4080 chore: rename command to NodeCommand and make fields pub
  bin/reth/src/cli/ext.rs
  bin/reth/src/cli/mod.rs
  bin/reth/src/node/mod.rs
Labels: A-cli

#4081 chore: make ext fns mut
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/cli/ext.rs
  bin/reth/src/node/mod.rs
  examples/additional-rpc-namespace-in-cli/src/main.rs
Labels: A-cli

#4070 RFC: Add rpc method eth_callMany
  crates/rpc/rpc-api/src/eth.rs
  crates/rpc/rpc-types/src/eth/call.rs
  crates/rpc/rpc-types/src/eth/mod.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/server.rs
Labels: A-rpc

#4082 chore: use remaining
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
Labels: A-rpc

#4076 chore: add missing op and idx fields
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/rpc/rpc-types/src/eth/trace/parity.rs
Labels: A-rpc

#4062 perf(trie): use available pre-loaded prefixsets
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/hashing.rs
Labels: C-perf, A-trie

#4087 chore: add with ext function
  bin/reth/src/node/mod.rs
Labels: A-cli

#3992 feat: make base fee computation parameters configurable via chain spec
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/init.rs
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/auto-seal/src/task.rs
  crates/consensus/common/src/validation.rs
  crates/payload/builder/src/payload.rs
  crates/primitives/src/basefee.rs
  crates/primitives/src/chain/mod.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/constants/mod.rs
  crates/primitives/src/hardfork.rs
  crates/primitives/src/header.rs
  crates/primitives/src/lib.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/maintain.rs
Labels: C-enhancement, M-changelog, A-op-reth

#4096 perf: no longer spawn filter tasks
  crates/rpc/rpc/src/eth/filter.rs
Labels: C-perf, A-rpc

#4077 fix: record push stack as vec u256
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
  crates/rpc/rpc-types/src/eth/trace/parity.rs
Labels: C-bug, M-changelog, A-rpc

#4084 feat: re-export `c-kzg` types and impl rlp traits
  Cargo.lock
  Cargo.toml
  crates/primitives/Cargo.toml
  crates/primitives/src/lib.rs
  crates/rlp/Cargo.toml
  crates/rlp/src/encode.rs
  deny.toml
Labels: C-enhancement, M-eip, E-cancun

#4074 feat(eip4844): include `TxEip4844` in the primitive `Transaction` enum
  crates/consensus/common/src/validation.rs
  crates/primitives/src/transaction/mod.rs
  crates/revm/revm-primitives/src/env.rs
  crates/rpc/rpc-types/src/eth/transaction/mod.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
Labels: C-enhancement, M-changelog, M-eip

#4100 fix(txpool): pending worst transaction
  crates/transaction-pool/src/pool/pending.rs
Labels: C-bug, A-tx-pool

#4101 fix(txpool): emit events on discarding worst txs
  crates/transaction-pool/src/pool/mod.rs
Labels: C-bug, A-tx-pool

#4108 fix(trie): dangling storage hashes
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/hashing.rs
  crates/trie/src/prefix_set/loader.rs
  crates/trie/src/prefix_set/mod.rs
  crates/trie/src/trie.rs
  crates/trie/src/updates.rs
Labels: C-bug, P-critical, M-changelog, A-trie

#4109 feat(cli): storage tries recovery
  bin/reth/src/cli/mod.rs
  bin/reth/src/lib.rs
  bin/reth/src/recover/mod.rs
  bin/reth/src/recover/storage_tries.rs
Labels: M-changelog, A-cli

#4106 chore: unused deps sanity check
  Cargo.lock
  crates/rpc/rpc/src/eth/api/server.rs
Labels: C-bug, A-rpc, C-test

#4098 feat: add `TransactionSigned::recover_signers`
  Cargo.lock
  crates/consensus/auto-seal/src/lib.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/block.rs
  crates/primitives/src/transaction/mod.rs
  crates/revm/src/executor.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-enhancement, C-benchmark

#4113 fix: bad recursion in logs
  crates/rpc/rpc-api/src/lib.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/eth/filter.rs
Labels: C-bug, A-rpc

#4112 feat(bin): temporarily disable full node
  bin/reth/src/args/pruning_args.rs
  bin/reth/src/node/mod.rs
Labels: A-cli

#4115 Revert "feat: add `TransactionSigned::recover_signers`"
  Cargo.lock
  crates/consensus/auto-seal/src/lib.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/block.rs
  crates/primitives/src/transaction/mod.rs
  crates/revm/src/executor.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-bug

#4119 feat(cli): full storage trie recovery
  bin/reth/src/recover/storage_tries.rs
Labels: A-cli, A-trie

#4126 fix(trie): include destroyed accounts in account prefix set
  Cargo.lock
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-bug, A-trie

#4088 standalone rpc_types
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc-types-compat/Cargo.toml
  crates/rpc/rpc-types-compat/src/block.rs
  crates/rpc/rpc-types-compat/src/lib.rs
  crates/rpc/rpc-types-compat/src/transaction/mod.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/eth/block.rs
  crates/rpc/rpc-types/src/eth/transaction/mod.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/pubsub.rs
  crates/rpc/rpc/src/txpool.rs
Labels: C-debt, A-rpc

#4065 chore: disable eta for headers & bodies
  bin/reth/src/node/events.rs
Labels: C-debt, A-observability

#4118 ask for confirmation during reth db drop
  bin/reth/src/db/mod.rs
Labels: A-cli

#4116 feat: adds `arbitratry` to `BlobTransaction` and `KZG_TRUSTED_SETUP`
  Cargo.lock
  crates/net/eth-wire/src/types/transactions.rs
  crates/primitives/Cargo.toml
  crates/primitives/res/eip4844/trusted_setup.txt
  crates/primitives/src/constants/eip4844.rs
Labels: A-networking, M-eip, E-cancun

#4129 feat: add max_fee_per_blob_gas fn
  crates/primitives/src/transaction/eip1559.rs
  crates/primitives/src/transaction/eip4844.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-enhancement, M-eip

#4094 chore: pruner charts in Grafana dashboard
  etc/grafana/dashboards/overview.json
Labels: A-observability, A-pruning

#4130 fix(trie): account prefixset unwind
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-bug, A-trie

#4092 feat(storage): account for pruned account/storage history
  crates/interfaces/src/provider.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/state/historical.rs
Labels: A-rpc, A-pruning

#4075 feat(txpool) modify txpool guard to be for pipeline syncs only
  crates/interfaces/src/sync.rs
  crates/net/network-api/src/lib.rs
  crates/net/network-api/src/noop.rs
  crates/net/network/src/network.rs
  crates/net/network/src/transactions.rs
Labels: A-tx-pool

#4069 feat(pruner, metrics): `skip` attribute for metrics derive macro
  crates/metrics/metrics-derive/src/expand.rs
  crates/metrics/metrics-derive/tests/metrics.rs
  crates/prune/src/metrics.rs
  crates/prune/src/pruner.rs
Labels: C-enhancement, A-observability

#4133 chore: remove cargo deny rule for c-kzg
  Cargo.lock
  deny.toml
Labels: C-debt, A-utils

#4009 fix(Makefile): Graceful cargo-nextest install
  Makefile
Labels: A-meta

#4078 feat: add rpc server metrics into dashboard
  etc/grafana/dashboards/overview.json
Labels: M-changelog, A-observability

#4136 chore: improve ef-tests readability
  testing/ef-tests/src/assert.rs
  testing/ef-tests/src/cases/blockchain_test.rs
  testing/ef-tests/src/models.rs
  testing/ef-tests/src/result.rs
Labels: C-debt, C-test

#4141 chore: make unit type default
  bin/reth/src/cli/ext.rs
  crates/rpc/rpc-builder/src/lib.rs
  examples/additional-rpc-namespace-in-cli/src/main.rs
Labels: A-rpc

#4144 chore(cli): expose registry provider
  crates/rpc/rpc-builder/src/lib.rs
Labels: A-cli

#4147 feat: add is eip4844 fn
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/tx_type.rs
  crates/transaction-pool/src/traits.rs
Labels: C-enhancement, M-changelog

#4149 fix: exclude single stop vm trace instruction
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: C-bug, A-rpc

#4151 fix: sub field is always serialized
  crates/rpc/rpc-types/src/eth/trace/parity.rs
Labels: C-bug, A-rpc

#4152 (feat):add transaction::is_dynamic_fee
  crates/primitives/src/transaction/mod.rs
Labels: C-enhancement

#4160 fix(txpool): maintenance tracing target
  crates/transaction-pool/src/maintain.rs
Labels: A-tx-pool, A-observability

#4156 feat(txpool): Make TransactionPool trait object safe
  crates/consensus/auto-seal/src/task.rs
  crates/net/network/src/transactions.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/traits.rs
Labels: C-enhancement, A-tx-pool

#4164 fix: remove discarded transactions
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-bug, M-changelog, A-tx-pool

#4161 fix(rpc): tracing target
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/layers/jwt_validator.rs
Labels: A-rpc, A-observability

#4171 docs(tx-pool): fix pending tx listener typo
  crates/transaction-pool/src/traits.rs
Labels: C-docs

#4177 docs: fix smol typo
  crates/transaction-pool/src/traits.rs
Labels: C-docs

#4183 chore(cli): remove unused `debug.tip` argument from execution debug script
  bin/reth/src/debug_cmd/execution.rs
Labels: C-debt, A-cli

#4180 fix: spawn js service task on blocking pool
  crates/rpc/rpc/src/debug.rs
Labels: C-bug, A-rpc

#4033 feat: add flag to CLI to disable colour coding of console output
  bin/reth/src/cli/mod.rs
  crates/tracing/src/lib.rs
Labels: M-changelog, A-observability, A-cli

#4169 style: use unwrap or default
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/rpc/rpc-types/src/eth/trace/parity.rs
Labels: C-debt

#4178 fix: restrict max active queries
  crates/net/common/src/ratelimit.rs
  crates/net/dns/src/query.rs
Labels: C-perf, A-networking

#4137 feat: download blocks in merkle debug script
  bin/reth/src/debug_cmd/merkle.rs
  bin/reth/src/debug_cmd/mod.rs
Labels: A-cli, A-trie

#4181 chore: bump jsonrpsee 0.20
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#4190 feat(interfaces): database write error details
  crates/interfaces/src/db.rs
  crates/storage/db/src/implementation/mdbx/cursor.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/lib.rs
Labels: A-db, A-observability

#4196 feat(doc): document ARM limitations
  book/installation/build-for-arm-devices.md
Labels: C-docs, C-enhancement

#4184 fix: return engine on fatal error
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/executor.rs
Labels: C-debt

#4163 chore(clippy): make clippy happy
  crates/transaction-pool/benches/reorder.rs
Labels: C-debt

#4204 chore(txpool): bench requires arbitrary feature
  crates/transaction-pool/Cargo.toml
Labels: A-tx-pool

#4203 perf: let sync status mirror FCU
  crates/consensus/beacon/src/engine/message.rs
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-perf

#4158 Splitting Reth Node Command Ext
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/cli/ext.rs
  bin/reth/src/node/mod.rs
  examples/additional-rpc-namespace-in-cli/src/main.rs
Labels: M-changelog, A-cli

#4194 docs: update table layout
  docs/design/database.md
Labels: C-docs, C-enhancement

#4208 chore: rm some unused
  crates/storage/provider/src/providers/chain_info.rs
Labels: C-debt

#4211 chore: handle full peer request channel
  crates/net/network/src/metrics.rs
  crates/net/network/src/transactions.rs
Labels: A-observability, A-networking

#4210 chore: enforce recommended soft limit for get pooled requests
  crates/net/network/src/transactions.rs
Labels: A-networking

#4197 fix(pruner): percentage progress
  crates/prune/src/pruner.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-enhancement, A-cli, A-pruning

#4165 feat(db): add search to `reth db list` command
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/db/list.rs
  bin/reth/src/db/tui.rs
  bin/reth/src/init.rs
  bin/reth/src/test_vectors/tables.rs
  bin/reth/src/utils.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/db/benches/hash_keys.rs
  crates/storage/db/benches/utils.rs
  crates/storage/db/src/abstraction/cursor.rs
  crates/storage/db/src/abstraction/table.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/db/src/tables/raw.rs
  crates/storage/db/src/tables/utils.rs
Labels: M-changelog, A-db, A-cli

#4120 feat: add `TransactionSigned::recover_signers` with the same order
  Cargo.lock
  crates/consensus/auto-seal/src/lib.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/block.rs
  crates/primitives/src/transaction/mod.rs
  crates/revm/src/executor.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-enhancement, C-benchmark

#4219 (fix)db commit on debug_traceCallMany
  crates/rpc/rpc/src/debug.rs
Labels: C-bug, A-rpc

#4220 chore: move bitflags to workspace
  Cargo.lock
  Cargo.toml
  crates/storage/libmdbx-rs/Cargo.toml
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/pool/state.rs
Labels: A-dependencies

#4228 Move parking_lot dependency to workspace dep
  Cargo.toml
  crates/blockchain-tree/Cargo.toml
  crates/interfaces/Cargo.toml
  crates/net/dns/Cargo.toml
  crates/net/network/Cargo.toml
  crates/storage/db/Cargo.toml
  crates/storage/libmdbx-rs/Cargo.toml
  crates/storage/provider/Cargo.toml
  crates/transaction-pool/Cargo.toml
Labels: A-dependencies

#4234 chore(deps): bump boa + thiserror
  Cargo.lock
  Cargo.toml
  crates/revm/revm-inspectors/Cargo.toml
Labels: A-dependencies

#4044 feat(pipeline): prune receipts based on log emitters
  bin/reth/src/args/pruning_args.rs
  bin/reth/src/debug_cmd/execution.rs
  bin/reth/src/node/mod.rs
  crates/config/src/config.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/prune/mod.rs
  crates/primitives/src/prune/mode.rs
  crates/primitives/src/prune/part.rs
  crates/primitives/src/prune/target.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/mod.rs
  crates/storage/provider/src/post_state/mod.rs
Labels: M-changelog, A-staged-sync, A-pruning

#4231 perf: use futures unordered for active requests
  crates/net/network/src/transactions.rs
Labels: C-perf

#4172 feat: implement network encoding for blob transactions
  Cargo.lock
  Cargo.toml
  crates/net/eth-wire/src/types/transactions.rs
  crates/net/eth-wire/testdata/blob_transaction
  crates/net/eth-wire/testdata/pooled_transactions_with_blob
  crates/net/eth-wire/tests/pooled_transactions.rs
  crates/net/network/src/message.rs
  crates/net/network/src/transactions.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/eip1559.rs
  crates/primitives/src/transaction/eip2930.rs
  crates/primitives/src/transaction/eip4844.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/primitives/src/transaction/signature.rs
Labels: C-enhancement, A-networking, M-eip, E-cancun

#4236 fix: propagate promoted transactions
  crates/transaction-pool/src/pool/mod.rs
Labels: C-bug, A-tx-pool

#4242 (fix): Impl. Lagged error in pool update channel
  crates/transaction-pool/src/pool/best.rs
Labels: C-debt, A-tx-pool

#4241 feat: refactor PooledTransactionsElement into typed variants
  crates/primitives/src/transaction/eip1559.rs
  crates/primitives/src/transaction/eip2930.rs
  crates/primitives/src/transaction/eip4844.rs
  crates/primitives/src/transaction/legacy.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
Labels: A-networking, M-eip, E-cancun

#4195 feat(doc): enhance `append_blocks_with_post_state` doc
  crates/storage/provider/src/traits/block.rs
Labels: C-docs

#4248 fix: broadcast promoted transactions
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-bug, M-changelog, A-tx-pool

#4245 feat: add 4844 config and basic checks
  crates/primitives/src/transaction/error.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: C-enhancement

#4251 perf: remove clones in PooledTransaction encoding
  crates/primitives/src/transaction/eip1559.rs
  crates/primitives/src/transaction/eip2930.rs
  crates/primitives/src/transaction/eip4844.rs
  crates/primitives/src/transaction/legacy.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
Labels: C-perf, A-networking, M-eip, E-cancun

#4252 chore: rename transaction
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/traits.rs
  examples/network-txpool.rs
Labels: M-changelog, C-debt

#4254 feat: add blob sidecar extraction to tx validation
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/mod.rs
  examples/network-txpool.rs
Labels: M-changelog, A-tx-pool

#4232 debug_backtraceAt
  Cargo.lock
  crates/rpc/rpc-api/src/debug.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/debug.rs
Labels: A-rpc

#4258 feat(transaction-pool): make `EthTransactionValidator` generic over Validator
  bin/reth/src/node/mod.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/mod.rs
  crates/transaction-pool/src/validate/task.rs
  examples/network-txpool.rs
Labels: M-changelog, A-tx-pool

#4268 fix: prevent node info zero address
  crates/net/network/src/network.rs
Labels: C-bug, A-networking

#4249 feat(trie): account proofs
  Cargo.lock
  crates/primitives/src/trie/nodes/mod.rs
  crates/trie/Cargo.toml
  crates/trie/src/errors.rs
  crates/trie/src/lib.rs
  crates/trie/src/proof.rs
Labels: C-enhancement, M-changelog, A-trie

#4264 fix: record geth selfdestructs
  crates/revm/revm-inspectors/src/tracing/builder/geth.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: C-bug, M-changelog, A-rpc

#4266 feat: integrate blobstore in pool
  bin/reth/src/node/mod.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/metrics.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/test_utils/mod.rs
  examples/network-txpool.rs
Labels: M-changelog, A-tx-pool

#4267 feat: add recovered wrapper type and eth pool conversions
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/eip1559.rs
  crates/primitives/src/transaction/eip2930.rs
  crates/primitives/src/transaction/eip4844.rs
  crates/primitives/src/transaction/legacy.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/transaction-pool/src/traits.rs
Labels: C-enhancement, S-blocked, M-changelog, A-tx-pool

#4256 feat: validate engine cancun fields based on method version
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/error.rs
  crates/rpc/rpc-engine-api/src/lib.rs
  crates/rpc/rpc-engine-api/src/payload.rs
Labels: C-enhancement, A-consensus, M-eip, E-cancun

#4272 feat: add TransactionPool blob getters
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/traits.rs
Labels: C-enhancement, M-changelog, A-tx-pool

#4273 feat: integrate blobstore in validator
  bin/reth/src/node/mod.rs
  crates/transaction-pool/src/blobstore/mod.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/task.rs
Labels: M-changelog, A-tx-pool

#4261 dev: use U64 for `transaction_index`
  crates/rpc/rpc-types/src/eth/transaction/receipt.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: A-rpc

#4284 chore: simplify builder fn
  crates/net/network/src/config.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/tests/it/geth.rs
  examples/network-txpool.rs
  examples/network.rs
Labels: A-dependencies

#4285 chore: rename test mod to make clippy happy
  crates/net/network/tests/it/clique/geth.rs
  crates/net/network/tests/it/clique/mod.rs
Labels: C-debt

#4289 dep: move `metrics` to workspace
  Cargo.toml
  bin/reth/Cargo.toml
  crates/blockchain-tree/Cargo.toml
  crates/consensus/beacon/Cargo.toml
  crates/metrics/Cargo.toml
  crates/metrics/metrics-derive/Cargo.toml
  crates/net/downloaders/Cargo.toml
  crates/net/eth-wire/Cargo.toml
  crates/net/network/Cargo.toml
  crates/payload/basic/Cargo.toml
  crates/payload/builder/Cargo.toml
  crates/prune/Cargo.toml
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc/Cargo.toml
  crates/stages/Cargo.toml
  crates/storage/db/Cargo.toml
  crates/tasks/Cargo.toml
  crates/transaction-pool/Cargo.toml
Labels: C-debt, A-dependencies

#4290 feat: add load_trusted_setup_from_bytes
  crates/primitives/src/constants/eip4844.rs
Labels: C-enhancement

#4291 chore: reorder receipt fields
  crates/rpc/rpc-types/src/eth/transaction/receipt.rs
Labels: A-rpc

#4279 feat: add additional conversion trait for pooled tx element
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
Labels: M-changelog, A-tx-pool

#4286 feat: integrate kzg setting in validator
  crates/transaction-pool/src/validate/eth.rs
Labels: M-changelog, A-tx-pool, M-eip

#4270 feat: provide a way to opt out of pool updates
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/traits.rs
Labels: M-changelog, A-tx-pool

#4292 chore: add additional docs about root call gas limit
  crates/revm/revm-inspectors/src/tracing/mod.rs
Labels: C-docs

#4293 fix: use gas_used from execution result
  crates/revm/revm-inspectors/src/tracing/builder/geth.rs
  crates/rpc/rpc/src/debug.rs
Labels: C-bug, M-changelog, A-rpc

#4296 docs: typos & cleanup
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/ChangeLog.md
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/README.md
  docs/crates/db.md
  docs/crates/discv4.md
  docs/crates/eth-wire.md
  docs/crates/network.md
  docs/crates/stages.md
  docs/design/database.md
Labels: C-docs

#4294 feat: support blob transactions in manager
  crates/net/eth-wire/src/types/broadcast.rs
  crates/net/network/src/transactions.rs
  crates/primitives/src/transaction/pooled.rs
Labels: M-changelog, A-networking, M-eip

#4298 fix: state overrides and call many args
  crates/rpc/rpc-api/src/debug.rs
  crates/rpc/rpc-types/src/eth/state.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: C-bug, A-rpc

#4303 feat: add Validator::on_new_head_block
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/mod.rs
Labels: C-enhancement, A-tx-pool

#4304 Docs: Add a guide on how to spin up a private Reth testnet using Kurtosis
  book/SUMMARY.md
  book/run/private-testnet.md
Labels: C-docs

#4309 feat(bin): show db path when confirming the drop
  bin/reth/src/db/mod.rs
Labels: A-cli

#4301 fix(pruner): history indices `cursor.prev()` emptiness check
  crates/prune/src/pruner.rs
Labels: C-bug, A-pruning

#4302 fix: add docs and serde attrs to ExecutionPayload v3 fields
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: C-docs, M-eip, E-cancun
