Repository paradigmxyz/reth, pull requests merged in 2024-03, with the labels that each got.

#6900 feat: sat math for tx value
  crates/transaction-pool/src/traits.rs
Labels: C-enhancement, A-tx-pool

#6904 chore: unify decode enveloped fn args
  crates/net/eth-wire/tests/pooled_transactions.rs
  crates/primitives/src/transaction/pooled.rs
  crates/rpc/rpc/src/eth/utils.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: C-debt

#6719 Add grafana panel for maintenance txpool metrics
  etc/grafana/dashboards/overview.json
Labels: A-observability

#6865 feat: add activation timestamps
  crates/ethereum-forks/src/hardfork.rs
Labels: C-enhancement

#6896 feat(provider): consistent database view
  crates/interfaces/src/provider.rs
  crates/storage/provider/src/providers/consistent_view.rs
  crates/storage/provider/src/providers/mod.rs
Labels: C-enhancement, A-db

#6912 Remove accidentally merged fields
  crates/net/network/src/transactions/fetcher.rs
Labels: A-observability, A-networking

#6908 feat(node-core, storage): static files segment metrics
  bin/reth/src/commands/db/stats.rs
  bin/reth/src/commands/stage/run.rs
  crates/node-builder/src/builder.rs
  crates/node-core/src/metrics/prometheus_exporter.rs
  crates/node-core/src/node_config.rs
  crates/primitives/src/fs.rs
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/storage/provider/src/providers/static_file/metrics.rs
  etc/grafana/dashboards/overview.json
Labels: C-enhancement, A-observability, A-static-files

#6916 fix: do not attempt clique header sender recovery on genesis
  crates/primitives/src/revm/env.rs
Labels: C-bug, A-consensus

#6827 feat: raw_tx_by_hash
  crates/rpc/rpc-api/src/eth.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: A-rpc

#6919 Revert "feat(storage): use `mdbx_txn_reset` to time out transactions …
  crates/node-core/src/metrics/prometheus_exporter.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/libmdbx-rs/benches/cursor.rs
  crates/storage/libmdbx-rs/benches/transaction.rs
  crates/storage/libmdbx-rs/src/cursor.rs
  crates/storage/libmdbx-rs/src/database.rs
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/libmdbx-rs/src/error.rs
  crates/storage/libmdbx-rs/src/transaction.rs
  crates/storage/libmdbx-rs/src/txn_manager.rs
Labels: C-bug, A-db

#6926 Add test for tx response verification
  crates/net/network/src/transactions/fetcher.rs
Labels: C-test, A-networking

#6923 fix(db): race condition in Tx cached handles
  crates/storage/db/src/implementation/mdbx/tx.rs
Labels: C-bug, A-db

#6931 feat(transaction-pool): remove deposit variant for mocktransaction
  crates/transaction-pool/src/test_utils/mock.rs
Labels: C-debt, A-tx-pool, C-test

#6932 Filter announcement txns pending import
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
Labels: C-perf, A-networking

#6929 chore(task): move blocking pool to `reth-tasks`
  Cargo.lock
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/bundle.rs
  crates/rpc/rpc/src/lib.rs
  crates/rpc/rpc/src/trace.rs
  crates/tasks/Cargo.toml
  crates/tasks/src/lib.rs
  crates/tasks/src/pool.rs
Labels: C-debt

#6938 feat: creating issues when hive fails
  .github/workflows/hive.yml
Labels: A-meta

#6892 Add panel for observing network manager future
  etc/grafana/dashboards/overview.json
Labels: A-observability, A-networking

#6864 Return fetch error on response that fails verification or validation
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
Labels: C-bug, A-networking

#6911 Small tx response verification optimisation
  crates/net/eth-wire/src/types/broadcast.rs
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
Labels: C-perf, A-networking

#6928 fix(tx-fetcher): only remove peer from active_peers when inflight_count <= 0
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
Labels: C-bug, A-networking

#6924 feat(storage): use `mdbx_txn_reset` to time out transactions
  crates/node-core/src/metrics/prometheus_exporter.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/libmdbx-rs/benches/cursor.rs
  crates/storage/libmdbx-rs/benches/transaction.rs
  crates/storage/libmdbx-rs/src/cursor.rs
  crates/storage/libmdbx-rs/src/database.rs
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/libmdbx-rs/src/error.rs
  crates/storage/libmdbx-rs/src/transaction.rs
  crates/storage/libmdbx-rs/src/txn_manager.rs
Labels: C-enhancement, A-db

#6918 feat(storage): log debug commit message only on commit
  Cargo.lock
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/metrics.rs
Labels: C-enhancement, A-db, A-observability

#6942 feat: dependabot to keep github actions workflows up to date
  .github/dependabot.yml
Labels: C-enhancement, A-dependencies

#6955 chore(ci): run clippy with `--locked`
  .github/workflows/lint.yml
Labels: A-meta

#6943 feat(trie): metrics
  Cargo.lock
  crates/trie/Cargo.toml
  crates/trie/src/lib.rs
  crates/trie/src/metrics.rs
  crates/trie/src/stats.rs
  crates/trie/src/trie.rs
Labels: A-observability, A-trie

#6651 Comment `TransactionsManager`
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
Labels: C-docs, C-debt, A-networking

#6860 restrict max concurrent outbound dials
  crates/net/network/src/manager.rs
  crates/net/network/src/peers/manager.rs
Labels: C-enhancement, A-networking

#6952 txpool: track failed delete blobs in cleanup
  crates/transaction-pool/src/blobstore/disk.rs
  crates/transaction-pool/src/blobstore/mem.rs
  crates/transaction-pool/src/blobstore/mod.rs
  crates/transaction-pool/src/blobstore/noop.rs
  crates/transaction-pool/src/pool/mod.rs
Labels: A-tx-pool

#6964 fix(stages, etl): clear ETL collectors in Headers stage when done
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/import.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/etl/src/lib.rs
  crates/node-core/src/node_config.rs
  crates/stages/src/lib.rs
  crates/stages/src/sets.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/tx_lookup.rs
Labels: C-bug, A-staged-sync, A-observability

#6970 feat(bin): delete static files from highest to lowest in `drop stage`
  bin/reth/src/commands/stage/drop.rs
Labels: C-bug, A-cli, A-static-files

#6871 feat(api,rpc): improve engine API abstraction
  Cargo.lock
  Cargo.toml
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  crates/node-api/src/engine/mod.rs
  crates/node-api/src/engine/traits.rs
  crates/node-ethereum/src/engine.rs
  crates/node-optimism/src/engine.rs
  crates/node-optimism/src/node.rs
  crates/payload/basic/src/lib.rs
  crates/payload/builder/src/lib.rs
  crates/payload/builder/src/optimism.rs
  crates/payload/builder/src/payload.rs
  crates/payload/optimism/src/lib.rs
  crates/primitives/src/chain/spec.rs
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  deny.toml
  examples/custom-node/src/main.rs
Labels: C-enhancement

#6902 feat: add OP specific txpool
  Cargo.lock
  crates/node-optimism/Cargo.toml
  crates/node-optimism/src/lib.rs
  crates/node-optimism/src/node.rs
  crates/node-optimism/src/txpool.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/mod.rs
  crates/transaction-pool/src/validate/task.rs
Labels: C-enhancement, A-op-reth

#6971 chore(node-core): log errors in debug when ETA fails to calculate
  bin/reth/src/sigsegv_handler.rs
  crates/ethereum-forks/src/hardfork.rs
  crates/node-core/src/events/node.rs
  crates/transaction-pool/src/test_utils/mock.rs
  examples/custom-node/src/main.rs
Labels: A-cli

#6974 feat(node-core): stage progress decimal places
  crates/primitives/src/stage/checkpoints.rs
Labels: C-enhancement, A-observability, A-cli

#6963 feat: add engine API metrics graphs
  etc/grafana/dashboards/overview.json
Labels: C-enhancement, A-observability

#6976 chore: rm coverage badge
  README.md
Labels: A-meta

#6978 feat: support any Inspector for block + tx tracing
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-enhancement, A-rpc

#6977 feat: add trace opcode gas
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc-api/src/trace.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-enhancement, M-changelog, A-rpc

#6981 chore: rm more optimism features
  crates/node-optimism/src/txpool.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
Labels: C-debt

#6984 feat(grafana): override Jemalloc chart axis
  etc/grafana/dashboards/overview.json
Labels: A-observability

#6991 chore(node-core): add stage id to eta overflow log
  crates/node-core/src/events/node.rs
Labels: A-observability, A-cli

#6994 test(storage): make read transaction safety tests faster
  crates/storage/db/src/implementation/mdbx/tx.rs
Labels: A-db, C-test

#6995 test(storage): fix flaky read transaction safety
  crates/storage/db/src/implementation/mdbx/tx.rs
Labels: A-db, C-test

#6990 fix: Canyon timestamp overflow
  crates/revm/src/optimism/mod.rs
Labels: C-bug, A-op-reth

#6996 remove clique related tests
  crates/net/network/tests/it/clique/clique_middleware.rs
  crates/net/network/tests/it/clique/geth.rs
  crates/net/network/tests/it/clique/mod.rs
  crates/net/network/tests/it/geth.rs
  crates/net/network/tests/it/main.rs
Labels: C-debt, A-networking

#6590 Prioritisation network manager + transactions manager + eth request handler
  Cargo.lock
  crates/net/network/Cargo.toml
  crates/net/network/src/budget.rs
  crates/net/network/src/eth_requests.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/transactions/mod.rs
  crates/rpc/rpc/src/eth/filter.rs
Labels: C-perf, A-networking

#6997 fix: immediately refill slots
  crates/net/network/src/peers/manager.rs
Labels: C-perf, A-networking

#6999 chore: remove most ethers mentions and code
  Cargo.lock
  Cargo.toml
  README.md
  book/intro.md
  crates/net/eth-wire/Cargo.toml
  crates/net/network/Cargo.toml
  crates/primitives/Cargo.toml
  crates/primitives/src/header.rs
Labels: C-debt, A-dependencies

#6988 Shorten error message on debug assertion
  crates/net/network/src/transactions/fetcher.rs
Labels: A-observability, A-networking

#7009 fix: setting GH_TOKEN for hive tests
  .github/workflows/hive.yml
Labels: C-bug

#7011 test(stages): fix deadlock with multiple static file writers
  crates/stages/src/test_utils/test_db.rs
Labels: C-bug, A-staged-sync, C-test, A-static-files

#6878 docs: update static file documentation
  crates/etl/src/lib.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/static-file/README.md
  crates/storage/provider/src/providers/database/mod.rs
Labels: C-docs, A-static-files

#6634 chore(deps): bump ethers to 2.0.14, enr to 0.10, unpin discv5
  Cargo.lock
  Cargo.toml
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/proto.rs
  crates/net/dns/src/lib.rs
  deny.toml
Labels: A-dependencies

#7021 release: v0.2.0-beta.1
  Cargo.lock
  Cargo.toml
Labels: A-meta

#7023 chore: condition export of generate_blob_sidecar on its cfg
  crates/primitives/src/transaction/mod.rs
Labels: C-bug, C-test

#6917 feat(storage): improve current process detection for MDBX HSR
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: C-enhancement, A-db

#6914 test(ef-tests, storage): do not `sync_all` static files in state tests
  crates/storage/nippy-jar/Cargo.toml
  crates/storage/nippy-jar/src/writer.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/providers/static_file/writer.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: C-test, A-static-files

#7034 docs: more node-builder docs
  crates/node-builder/Cargo.toml
  crates/node-builder/README.md
  crates/node-builder/src/builder.rs
Labels: C-docs

#7010 decrease default tracing permits
  crates/node-core/src/args/rpc_server_args.rs
  crates/rpc/rpc-builder/src/constants.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/tasks/src/pool.rs
  examples/custom-inspector/src/main.rs
Labels: C-perf, A-rpc

#7035 Revert "chore(github): skip some heavy jobs when PR is not related (#6667)"
  .github/workflows/bench.yml
  .github/workflows/book.yml
  .github/workflows/grafana.yml
  .github/workflows/integration.yml
  .github/workflows/lint.yml
  .github/workflows/unit.yml
Labels: A-meta

#7048 chore: mem take topics when converting logs
  crates/primitives/src/log.rs
Labels: C-debt

#7041 chore: remove repetitive words
  book/cli/reth/node.md
  crates/consensus/beacon/src/engine/mod.rs
  crates/node-core/src/args/rpc_server_args.rs
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h
Labels: C-docs

#7047 perf: replace BytesMut with alloy_rlp::encode
  crates/net/discv4/src/config.rs
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/proto.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/primitives/src/net.rs
  crates/rpc/rpc-types/src/net.rs
Labels: C-debt

#7052 chore: be less strict when slashing trusted peers
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/peers/reputation.rs
Labels: A-networking

#7051 chore(txpool): update size metrics on every insert & removal of transactions
  crates/transaction-pool/src/pool/txpool.rs
Labels: A-tx-pool, A-observability

#7057 chore: bump max concurrent outbound dials
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/peers/mod.rs
Labels: C-perf, A-networking

#7062 perf: use special geth tracer config setups
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc/src/debug.rs
Labels: C-perf

#7029 Remove tx pool row from reth dashboard
  etc/grafana/dashboards/overview.json
  etc/grafana/dashboards/reth-mempool.json
Labels: A-observability

#7069 fix: remove redundant checking for if peer is banned
  crates/net/network/src/peers/manager.rs
Labels: C-debt, A-networking

#7025 grafana/overview: add RPC QPS dashboard
  etc/grafana/dashboards/overview.json
Labels: A-observability

#7074 fix(rpc): cache transaction hash when filtering over receipt logs
  crates/rpc/rpc/src/eth/logs_utils.rs
Labels: C-bug, A-rpc

#7060 fix(rpc): less clones in logs filter
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc/src/eth/logs_utils.rs
  examples/db-access.rs
Labels: C-perf, A-rpc

#7088 chore: mount all datadirs in docker-compose.yml
  etc/docker-compose.yml
Labels: A-meta

#7089 fix(bin, node-core): commit genesis header into static files after db
  bin/reth/src/commands/stage/drop.rs
  crates/node-core/src/init.rs
Labels: C-bug, A-static-files

#7090 feat(storage): bump mdbx to 0.12.9
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/VERSION.txt
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c++
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h++
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_chk.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_copy.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_drop.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_dump.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_load.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_stat.c
Labels: C-enhancement, A-db

#7084 chore: more Vec over BytesMut
  crates/net/discv4/src/proto.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/eth-wire/src/types/broadcast.rs
  crates/node-core/src/cli/config.rs
  crates/payload/basic/src/lib.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/header.rs
  crates/primitives/src/receipt.rs
  crates/primitives/src/transaction/eip2930.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/transaction-pool/src/maintain.rs
Labels: C-debt

#7092 fix: add timeouts to the hive CI
  .github/workflows/hive.yml
Labels: A-meta

#7078 feat(rpc): Add 4844 checks to `ethCallBundle`
  crates/rpc/rpc/src/eth/bundle.rs
Labels: A-rpc, E-cancun

#7033 primitives/chain: dev chain support cancun upgrade
  crates/consensus/auto-seal/src/lib.rs
  crates/primitives/src/chain/spec.rs
Labels: C-enhancement

#7073 docs: add note about hashing
  crates/primitives/src/transaction/mod.rs
Labels: C-docs, C-debt

#7095 cmd/debug: use inline cfg to reduce optimism/ethereum code duplicate
  bin/reth/src/commands/debug_cmd/build_block.rs
Labels: C-debt

#7099 chore: use safe math when calculating missing senders
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-debt

#6826 Feat: add signers
  Cargo.lock
  Cargo.toml
  crates/node-builder/src/builder.rs
  crates/rpc/rpc-api/src/eth.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/sign.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/signer.rs
  crates/tasks/Cargo.toml
Labels: C-enhancement, A-rpc

#7102 feat(book): update CLI section
  book/cli/reth.md
  book/cli/reth/dump-genesis.md
  book/cli/reth/node.md
  book/cli/reth/p2p.md
  book/cli/reth/stage/run.md
Labels: C-docs

#7107 chore: remove test structs that are never constructed
  crates/net/network/src/eth_requests.rs
  crates/stages/src/stages/bodies.rs
Labels: C-debt

#7101 fix: `eth_getRawReceipts`
  crates/primitives/src/receipt.rs
  crates/rpc/rpc/src/debug.rs
Labels: C-bug, A-rpc

#7112 feat(grafana): trie charts
  etc/grafana/dashboards/overview.json
Labels: A-observability

#7111 fix(chain_spec): Set correct paris block and chain difficulty
  crates/primitives/src/chain/spec.rs
Labels: C-bug

#7108 fix: refactor ecies message parsing to check bounds
  crates/net/ecies/src/algorithm.rs
  crates/net/ecies/src/error.rs
Labels: C-bug, A-networking

#7117 fix: use checked math for read_body
  crates/net/ecies/src/algorithm.rs
Labels: C-bug, A-devp2p, A-networking

#7118 fix: check that data is large enough to fit header and mac
  crates/net/ecies/src/algorithm.rs
Labels: C-bug, A-networking

#6784 fix(op-reth): non-deposit txs have depositReceiptVersion=1
  Cargo.lock
  crates/primitives/src/transaction/signature.rs
  crates/revm/Cargo.toml
  crates/revm/src/lib.rs
  crates/revm/src/optimism/processor.rs
  crates/revm/src/processor.rs
  crates/revm/src/test_utils.rs
Labels: C-test, A-op-reth

#7103 feat(ci): tag docker image as latest only for beta
  .github/workflows/docker.yml
  Makefile
Labels: A-meta

#7067 Adds metrics for All Transactions
  crates/transaction-pool/src/metrics.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: A-tx-pool, A-observability

#7116 chore(primitives): remove static file stage
  crates/primitives/src/stage/id.rs
Labels: A-staged-sync, C-debt

#7125 chore(make): run doctest in `make test`
  Makefile
Labels: A-meta

#7127 test: headers first stage
  crates/primitives/src/stage/id.rs
Labels: A-staged-sync, C-test

#7128 docs(txpool): fix docs for cancun activation check
  crates/transaction-pool/src/validate/eth.rs
Labels: C-docs, A-tx-pool

#7113 chore(stages): debug logs with progress in sender recovery
  crates/stages/src/stages/sender_recovery.rs
Labels: C-enhancement, A-staged-sync, A-observability

#7119 feat(db): record client version history
  Cargo.lock
  bin/reth/src/commands/db/diff.rs
  bin/reth/src/commands/db/list.rs
  bin/reth/src/commands/db/mod.rs
  bin/reth/src/commands/db/static_files/mod.rs
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/init_cmd.rs
  bin/reth/src/commands/node/mod.rs
  bin/reth/src/commands/p2p/mod.rs
  bin/reth/src/commands/recover/storage_tries.rs
  bin/reth/src/commands/stage/drop.rs
  bin/reth/src/commands/stage/dump/mod.rs
  bin/reth/src/commands/stage/run.rs
  bin/reth/src/commands/stage/unwind.rs
  crates/node-core/src/args/database_args.rs
  crates/node-core/src/version.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/lib.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/db/src/tables/models/client_version.rs
  crates/storage/db/src/tables/models/mod.rs
  crates/storage/provider/src/providers/database/mod.rs
  examples/db-access.rs
  examples/rpc-db/Cargo.toml
  examples/rpc-db/src/main.rs
Labels: C-enhancement, A-db

#7126 add more helper functions to PooledTransactionElement
  crates/primitives/src/transaction/pooled.rs
Labels: A-tx-pool, C-test

#7129 fix: receipt for non EIP-4844 transactions
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-bug, A-rpc

#7124 feat: add `EtlConfig` as well as setting the directory to datadir
  Cargo.lock
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/stage/run.rs
  book/cli/reth/recover/storage-tries.md
  book/cli/reth/stage/run.md
  crates/config/src/config.rs
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/etl/src/lib.rs
  crates/node-builder/src/builder.rs
  crates/node-core/src/node_config.rs
  crates/stages/Cargo.toml
  crates/stages/benches/criterion.rs
  crates/stages/src/lib.rs
  crates/stages/src/sets.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/tx_lookup.rs
Labels: C-enhancement, A-staged-sync

#7135 fix: apply block overrides before create env
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: C-bug, A-rpc

#7087 perf: replace BytesMut with alloy_rlp::encode
  crates/interfaces/src/test_utils/generators.rs
  crates/net/discv4/src/proto.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/node-core/src/cli/config.rs
  crates/payload/basic/src/lib.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/header.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-perf

#7133 fix: estimate gas
  crates/rpc/rpc/src/eth/api/call.rs
Labels: C-bug, A-rpc

#7136 fix: payload builder london boundary block gaslimit and basefee
  Cargo.lock
  crates/payload/builder/Cargo.toml
  crates/payload/builder/src/payload.rs
Labels: C-bug, A-consensus, A-block-building, C-test, C-hivetest

#7137 chore: add safety check on `StaticFileProviderRW::increment_block`
  crates/interfaces/src/provider.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/test_utils/test_db.rs
  crates/static-file/src/segments/receipts.rs
  crates/static-file/src/segments/transactions.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/static_file/writer.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: A-static-files

#7148 dep: lock enr
  Cargo.toml
Labels: A-dependencies

#7140 Always accept incoming connections from trusted peers
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/swarm.rs
  crates/net/network/tests/it/connect.rs
Labels: C-enhancement, A-networking

#7147 chore: rm duplicated code
  crates/node-core/src/node_config.rs
Labels: C-debt

#7150 chore: move tower+hyper to workspace
  Cargo.toml
  crates/node-core/Cargo.toml
  crates/rpc/ipc/Cargo.toml
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc/Cargo.toml
Labels: A-dependencies

#7151 chore: remove unused deps
  Cargo.lock
  crates/node-core/Cargo.toml
  crates/node-core/src/args/network_args.rs
  crates/node-core/src/lib.rs
Labels: A-dependencies

#7152 chore: add ipv6 related cases in NodeRecord UT
  crates/rpc/rpc-types/src/net.rs
Labels: C-test, A-networking

#7143 fix(static-file): pass producer as `Arc<Mutex<_>>` to ensure only one is active
  Cargo.lock
  bin/reth/src/commands/import.rs
  crates/consensus/beacon/src/engine/hooks/static_file.rs
  crates/node-builder/src/builder.rs
  crates/revm/src/stack.rs
  crates/rpc/rpc/src/eth/bundle.rs
  crates/stages/src/pipeline/mod.rs
  crates/static-file/Cargo.toml
  crates/static-file/src/lib.rs
  crates/static-file/src/static_file_producer.rs
Labels: C-enhancement, A-consensus, A-static-files

#7163 Track PendingIn state separately
  crates/net/network/src/peers/manager.rs
Labels: A-networking

#7156 feat(node-core, stages): stage preparation notification
  crates/node-core/src/events/node.rs
  crates/stages/src/pipeline/event.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stages/headers.rs
Labels: C-enhancement, A-staged-sync, A-observability

#7165 fix: decrease connection info based on current state
  crates/net/network/src/manager.rs
  crates/net/network/src/peers/manager.rs
Labels: A-networking

#7120 docs(node-core): add document of build_blockchain_tree
  crates/node-builder/src/components/payload.rs
  crates/node-builder/src/node.rs
  crates/node-core/src/events/node.rs
  crates/node-core/src/node_config.rs
Labels: C-docs, A-cli

#7167 chore: bump revm inspector, bump msrv
  .github/workflows/lint.yml
  Cargo.lock
  Cargo.toml
  README.md
  clippy.toml
  crates/rpc/rpc-types-compat/src/proof.rs
  crates/rpc/rpc-types-compat/src/transaction/mod.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: A-dependencies

#7168 fix: use unit workflow for README CI badge
  README.md
Labels: C-bug

#7166 release: v0.2.0-beta.3
  Cargo.lock
  Cargo.toml
Labels: A-meta

#7171 fix: panic conditions for concat kdf in ecies
  crates/net/ecies/src/algorithm.rs
Labels: C-bug, C-docs, A-devp2p

#7155 feat: support trusted peer ids without address
  crates/net/network-api/src/lib.rs
  crates/net/network-api/src/noop.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/state.rs
Labels: C-enhancement, A-networking

#7184 chore(hardfork): add hardfork upgrade url
  crates/ethereum-forks/src/hardfork.rs
Labels: C-docs

#7182 bugfix: setup discovery addr appropriately
  crates/node-core/src/args/network_args.rs
  crates/node-core/src/node_config.rs
Labels: C-bug, A-cli

#7179 Small refactoring in transaction pool
  crates/transaction-pool/src/pool/blob.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/mod.rs
Labels: C-debt, A-tx-pool

#7192 chore: add AllTransactionsEvents::new
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/listener.rs
Labels: C-enhancement, A-tx-pool

#7164 fix: propagate try_make_sync_target_canonical error
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/blockchain_tree/error.rs
Labels: C-bug, A-consensus, A-blockchain-tree

#7198 docs: fix metric doc
  crates/net/network/src/metrics.rs
  etc/grafana/dashboards/overview.json
Labels: C-docs

#7199 chore: remove txpool optimism feature
  bin/reth/Cargo.toml
  crates/net/network/Cargo.toml
  crates/net/network/src/metrics.rs
  crates/node-core/Cargo.toml
  crates/node-optimism/Cargo.toml
  crates/payload/builder/Cargo.toml
  crates/payload/optimism/Cargo.toml
  crates/rpc/rpc/Cargo.toml
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: C-debt

#7197 fix: decrease pending out on already connected
  crates/net/network/src/peers/manager.rs
Labels: C-bug, A-networking

#7149 feat: autoscale session event capacity
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/session/config.rs
  crates/node-core/src/args/network_args.rs
Labels: C-enhancement, A-networking

#7208 Small refactor
  crates/node-core/src/engine_api_store.rs
  crates/primitives/src/chain/spec.rs
Labels: C-debt

#7186 perf(trie): calculate state root from `BundleState`
  crates/blockchain-tree/src/chain.rs
  crates/consensus/auto-seal/src/lib.rs
  crates/payload/ethereum/src/lib.rs
  crates/payload/optimism/src/lib.rs
  crates/revm/src/test_utils.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  crates/storage/provider/src/providers/bundle_state_provider.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/macros.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/state.rs
Labels: C-perf, A-trie

#7207 feat: Display the reth version in the log
  bin/reth/src/commands/node/mod.rs
Labels: C-enhancement, A-observability, A-cli

#7221 Enable clippy's equatable_if_let linter
  Cargo.toml
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/transaction/mod.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/stages/src/stages/mod.rs
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: C-debt

#7213 `reth-primitives`: Fix warnings when default features are off.
  crates/primitives/Cargo.toml
Labels: C-debt

#7141 Add AllTransactionsMetrics graph in txpool dashboard
  etc/grafana/dashboards/reth-mempool.json
Labels: A-observability

#7219 fix: enforce timeouts for pending sessions
  crates/net/network/src/error.rs
  crates/net/network/src/session/config.rs
  crates/net/network/src/session/handle.rs
  crates/net/network/src/session/mod.rs
Labels: C-bug, A-networking

#7222 Enable clippy's or_fun_call linter
  Cargo.toml
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/node/mod.rs
  bin/reth/src/commands/p2p/mod.rs
  bin/reth/src/commands/stage/run.rs
  crates/interfaces/src/test_utils/generators.rs
  crates/net/network/src/config.rs
  crates/node-builder/src/builder.rs
  crates/payload/optimism/src/lib.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
  crates/rpc/rpc/src/layers/auth_layer.rs
  crates/storage/provider/src/providers/static_file/writer.rs
  crates/tracing/src/formatter.rs
  crates/trie/src/hashed_cursor/post_state.rs
Labels: C-debt

#7223 Enable clippy's branches_sharing_code linter
  Cargo.toml
  crates/transaction-pool/src/pool/pending.rs
Labels: C-debt

#7218 feat(node-core): omit stage progress from logs if empty
  crates/node-core/src/events/node.rs
Labels: C-enhancement, A-observability, A-cli

#7220 Enable clippy's useless_let_if_seq linter
  Cargo.toml
  crates/consensus/auto-seal/src/lib.rs
  crates/payload/ethereum/src/lib.rs
  crates/payload/optimism/src/lib.rs
  crates/primitives/src/header.rs
  crates/rpc/rpc/src/eth/gas_oracle.rs
  crates/stages/src/stages/execution.rs
  crates/static-file/src/segments/headers.rs
  crates/static-file/src/segments/receipts.rs
  crates/static-file/src/segments/transactions.rs
  crates/storage/db/src/tables/models/accounts.rs
  crates/storage/nippy-jar/src/writer.rs
Labels: C-debt

#7229 fix: enforce max inbound == 0
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/swarm.rs
  crates/net/network/tests/it/connect.rs
Labels: C-debt, A-networking

#7230 feat: add BeaconConsensusEvent for live sync download requests
  crates/consensus/beacon/src/engine/event.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/node-core/src/events/node.rs
Labels: C-enhancement, A-observability, A-downloaders

#7236 feat(storage): bump mdbx to 0.12.10
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/CMakeLists.txt
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/VERSION.txt
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/cmake/compiler.cmake
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/cmake/profile.cmake
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/cmake/utils.cmake
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_chk.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_copy.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_drop.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_dump.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_load.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_stat.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c++
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h++
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_chk.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_copy.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_drop.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_dump.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_load.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_stat.c
Labels: C-enhancement, A-db

#7246 dev: `with_capacity` for HashMap
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/node-core/src/init.rs
Labels: C-perf

#7206 Integrate Config into admin_nodeInfo response
  Cargo.lock
  crates/net/network-api/src/noop.rs
  crates/net/network/src/manager.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/admin.rs
  crates/rpc/rpc/src/admin.rs
Labels: C-enhancement, A-rpc

#7251 fix: skip block tracing if empty
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-bug, A-rpc
