Repository paradigmxyz/reth, pull requests merged in 2024-02, with the labels that each got.

#6244 refactor(trie): hashed state
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  crates/storage/provider/src/bundle_state/hashed_state_changes.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/trie/src/hashed_cursor/post_state.rs
  crates/trie/src/lib.rs
  crates/trie/src/state.rs
Labels: C-debt, A-trie

#6312 feat(primitives): remove snapshot block interval from chain spec
  crates/primitives/src/chain/spec.rs
Labels: C-debt, A-snapshots

#6319 fix: ensure backwards compat config
  crates/config/src/config.rs
  crates/net/network/src/peers/reputation.rs
Labels: C-bug

#6322 feat(bin): use snapshots in `stage run` and `stage unwind`
  bin/reth/src/commands/stage/run.rs
  bin/reth/src/commands/stage/unwind.rs
Labels: C-enhancement, A-cli, A-snapshots

#6320 fix: op features for op crate
  bin/reth/Cargo.toml
  bin/reth/src/commands/debug_cmd/build_block.rs
Labels: A-dependencies

#6328 fix: set excess blob gas and blob gas used for empty payloads
  crates/payload/ethereum/src/lib.rs
  crates/primitives/src/header.rs
Labels: C-bug, A-consensus, E-cancun

#6327 fix: use ecrevored transaction for tracing
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-perf, A-rpc

#6325 Fix bug, limit for broadcast message
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
Labels: A-tx-pool, A-networking

#6338 chore: add all-forks genesis forkid test
  crates/primitives/src/chain/spec.rs
Labels: C-enhancement, C-test

#6339 chore: add test for invalid devnet block hash
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: C-bug, A-consensus, A-block-building

#6307 feat(bin): delete snapshot jars in `stage drop`
  bin/reth/src/commands/db/diff.rs
  bin/reth/src/commands/db/get.rs
  bin/reth/src/commands/db/list.rs
  bin/reth/src/commands/db/mod.rs
  bin/reth/src/commands/stage/drop.rs
  bin/reth/src/commands/stage/dump/execution.rs
  bin/reth/src/commands/stage/dump/hashing_account.rs
  bin/reth/src/commands/stage/dump/hashing_storage.rs
  bin/reth/src/commands/stage/dump/merkle.rs
  bin/reth/src/commands/stage/dump/mod.rs
  bin/reth/src/utils.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
Labels: C-enhancement, A-cli, A-snapshots

#6285 feat(bin): show snapshots in `db stats`
  bin/reth/src/commands/db/mod.rs
  bin/reth/src/commands/db/stats.rs
  crates/storage/nippy-jar/src/lib.rs
Labels: C-enhancement, A-db, A-cli

#6345 fix: Remove redundant Result wrapper
  crates/net/network/src/transactions/mod.rs
  crates/net/network/tests/it/big_pooled_txs_req.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#5463 feat(storage): use roaring bitmaps for history tables
  Cargo.lock
  bin/reth/src/commands/stage/run.rs
  crates/interfaces/src/test_utils/generators.rs
  crates/primitives/Cargo.toml
  crates/primitives/benches/integer_list.rs
  crates/primitives/src/integer_list.rs
  crates/prune/src/segments/account_history.rs
  crates/prune/src/segments/history.rs
  crates/prune/src/segments/storage_history.rs
  crates/stages/benches/setup/account_hashing.rs
  crates/stages/benches/setup/mod.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/index_account_history.rs
  crates/stages/src/stages/index_storage_history.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/state/historical.rs
Labels: C-enhancement, A-db, S-breaking, M-prevent-stale

#6352 perf: do heavy blob validation last
  crates/transaction-pool/src/validate/eth.rs
Labels: C-perf, A-tx-pool

#6344 feat(storage): make snapshots non-optional in provider factory
  bin/reth/src/commands/db/clear.rs
  bin/reth/src/commands/db/mod.rs
  bin/reth/src/commands/db/snapshots/bench.rs
  bin/reth/src/commands/db/snapshots/headers.rs
  bin/reth/src/commands/db/snapshots/mod.rs
  bin/reth/src/commands/db/snapshots/receipts.rs
  bin/reth/src/commands/db/snapshots/transactions.rs
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/init_cmd.rs
  bin/reth/src/commands/p2p/mod.rs
  bin/reth/src/commands/recover/storage_tries.rs
  bin/reth/src/commands/stage/drop.rs
  bin/reth/src/commands/stage/dump/execution.rs
  bin/reth/src/commands/stage/dump/hashing_account.rs
  bin/reth/src/commands/stage/dump/hashing_storage.rs
  bin/reth/src/commands/stage/dump/merkle.rs
  bin/reth/src/commands/stage/dump/mod.rs
  bin/reth/src/commands/stage/run.rs
  bin/reth/src/commands/stage/unwind.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/task.rs
  crates/net/downloaders/src/file_client.rs
  crates/node-core/src/node_config.rs
  crates/prune/src/pruner.rs
  crates/snapshot/src/snapshotter.rs
  crates/stages/src/lib.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/test_utils/mod.rs
  examples/db-access.rs
  examples/rpc-db/src/main.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: C-enhancement, A-db, A-snapshots

#6355 feat: benchmark blob validation
  crates/primitives/Cargo.toml
  crates/primitives/benches/validate_blob_tx.rs
Labels: A-tx-pool, C-benchmark

#6358 small refactoring in payload crate
  crates/payload/builder/src/database.rs
  crates/payload/builder/src/noop.rs
  crates/payload/builder/src/optimism.rs
  crates/payload/builder/src/payload.rs
Labels: C-debt

#6361 feat: remove blobs associated with discarded blob txs
  crates/transaction-pool/src/pool/mod.rs
Labels: C-bug, A-tx-pool

#6353 feat(db): propagate text error messages from mdbx
  crates/interfaces/src/db.rs
  crates/interfaces/src/error.rs
  crates/storage/db/src/implementation/mdbx/cursor.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
Labels: C-enhancement, A-db, A-observability

#6368 fix: bad blob pool eviction
  crates/transaction-pool/src/config.rs
  crates/transaction-pool/src/pool/blob.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/test_utils/mock.rs
Labels: C-bug, A-tx-pool

#6366 fix: add test for truncating parked with large transactions
  Cargo.lock
  crates/primitives/src/transaction/mod.rs
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/test_utils/mock.rs
Labels: C-bug, A-tx-pool

#6373 feature: add Blob pool metrics
  crates/transaction-pool/src/metrics.rs
  crates/transaction-pool/src/pool/txpool.rs
  docs/design/metrics.md
  etc/grafana/dashboards/overview.json
Labels: A-tx-pool, A-observability

#6375 chore: remove node-api optimism feature
  bin/reth/Cargo.toml
  crates/consensus/beacon/Cargo.toml
  crates/node-api/Cargo.toml
  crates/node-api/src/engine/mod.rs
  crates/node-api/src/lib.rs
  crates/node-core/Cargo.toml
  crates/node-optimism/Cargo.toml
  crates/node-optimism/src/engine.rs
Labels: C-debt

#6377 chore: rm unused reexport
  crates/primitives/src/lib.rs
  testing/ef-tests/src/models.rs
Labels: C-debt

#6381 chore: apply missing const for fn lint txpool
  crates/transaction-pool/src/config.rs
  crates/transaction-pool/src/identifier.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/pool/blob.rs
  crates/transaction-pool/src/pool/events.rs
  crates/transaction-pool/src/pool/listener.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/state.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/test_utils/gen.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/mod.rs
Labels: C-debt

#6371 fix: rpc-builder crate compilation
  Cargo.lock
  crates/node-api/src/engine/mod.rs
  crates/node-core/src/args/rpc_server_args.rs
  crates/node-ethereum/src/engine.rs
  crates/node-optimism/src/engine.rs
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/lib.rs
  examples/rpc-db/Cargo.toml
  examples/rpc-db/src/main.rs
Labels: C-debt, A-dependencies

#6392 chore: bump strum
  Cargo.lock
  Cargo.toml
  crates/node-core/src/args/rpc_server_args.rs
  crates/rpc/rpc-builder/src/lib.rs
Labels: A-dependencies

#6276 feat(tree): re-enable trie caching
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/chain.rs
  crates/storage/provider/src/test_utils/blocks.rs
Labels: A-blockchain-tree, A-trie

#6380 docs: add more docs for on_canonical_state_change
  crates/transaction-pool/src/traits.rs
Labels: C-docs, A-tx-pool

#6391 chore(make): add build/build-op subcommand
  Makefile
Labels: A-meta

#6378 chore: remove prune serde helpers mod
  crates/primitives/src/prune/target.rs
  crates/primitives/src/serde_helper.rs
  crates/primitives/src/serde_helper/mod.rs
  crates/primitives/src/serde_helper/prune.rs
Labels: C-debt

#6393 Example/polygon p2p
  Cargo.lock
  Cargo.toml
  crates/net/network/src/config.rs
  examples/polygon-p2p/Cargo.toml
  examples/polygon-p2p/src/chain_cfg.rs
  examples/polygon-p2p/src/genesis.json
  examples/polygon-p2p/src/main.rs
Labels: A-networking

#6401 chore: improve `Withdrawals` interface
  crates/consensus/common/src/validation.rs
  crates/primitives/src/withdrawal.rs
  crates/revm/src/processor.rs
  crates/revm/src/state_change.rs
Labels: C-debt

#6316 Fix bug, rebuffer hashes that were received over broadcast
  crates/net/network/src/transactions/fetcher.rs
Labels: A-networking

#6384 Disable tx refetch logic
  crates/net/network/src/transactions/mod.rs
Labels: A-networking

#6400 fix(engine): skip payload building on already canonical
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-bug, A-consensus

#6395 add `TestPoolWrapper` around `TestPool`
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/tests/it/big_pooled_txs_req.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/transaction-pool/src/pool/blob.rs
  crates/transaction-pool/src/test_utils/mod.rs
  crates/transaction-pool/tests/it/blobs.rs
  crates/transaction-pool/tests/it/listeners.rs
  crates/transaction-pool/tests/it/pending.rs
Labels: A-tx-pool, C-test

#6402 chore: rm trait bounds
  crates/transaction-pool/src/validate/eth.rs
Labels: C-debt, A-tx-pool

#6394 Deprecate `best_transactions_with_base_fee`
  crates/payload/ethereum/src/lib.rs
  crates/payload/optimism/src/lib.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/traits.rs
Labels: C-enhancement, A-tx-pool

#6273 feat(snapshots): write Headers to snapshots during `HeaderStage`
  Cargo.lock
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/init_cmd.rs
  bin/reth/src/commands/recover/storage_tries.rs
  bin/reth/src/commands/stage/drop.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/externals.rs
  crates/consensus/beacon/Cargo.toml
  crates/consensus/common/src/validation.rs
  crates/ethereum-forks/src/hardfork.rs
  crates/etl/src/lib.rs
  crates/net/network/src/transactions/fetcher.rs
  crates/node-core/src/init.rs
  crates/node-core/src/node_config.rs
  crates/prune/src/segments/headers.rs
  crates/snapshot/src/segments/headers.rs
  crates/snapshot/src/snapshotter.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/merkle.rs
  crates/stages/src/stages/mod.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/libmdbx-rs/Cargo.toml
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/libmdbx-rs/src/error.rs
  crates/storage/nippy-jar/src/writer.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
  crates/storage/provider/src/providers/snapshot/writer.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/transaction-pool/src/test_utils/mock.rs
  docs/crates/stages.md
  testing/ef-tests/Cargo.toml
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: A-snapshots

#6374 grafana: add build version,gitsha,timestamp into dashboard
  etc/grafana/dashboards/overview.json
Labels: A-observability

#6416 test(ef-tests): disable HighGasPriceParis
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: A-execution, C-test

#6419 chore: log long tx backtrace on a new line
  crates/storage/db/src/implementation/mdbx/tx.rs
Labels: A-observability

#6426 feat: add size generator to MockTransactionDistribution
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/test_utils/pool.rs
Labels: C-enhancement, A-tx-pool, C-test

#6423 chore: rename EvmEnvConfig to ConfigureEvmEnv
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/auto-seal/src/task.rs
  crates/node-api/src/evm/mod.rs
  crates/node-api/src/lib.rs
  crates/node-core/src/args/rpc_server_args.rs
  crates/node-core/src/cli/components.rs
  crates/node-core/src/node_config.rs
  crates/node-ethereum/src/evm.rs
  crates/node-ethereum/src/lib.rs
  crates/node-optimism/src/evm.rs
  crates/node-optimism/src/lib.rs
  crates/revm/src/factory.rs
  crates/revm/src/optimism/processor.rs
  crates/revm/src/processor.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/cache/mod.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/evm_env.rs
Labels: C-debt, A-cli, A-sdk

#6435 ci: tmp pin nightly version
  .github/workflows/book.yml
  .github/workflows/dependencies.yml
  .github/workflows/lint.yml
  .github/workflows/sanity.yml
Labels: A-meta

#6428 chore: move alias top of file
  crates/primitives/src/transaction/mod.rs
Labels: C-debt

#6433 fix: put noop helper behind feature
  crates/net/network/src/config.rs
  examples/polygon-p2p/src/main.rs
Labels: C-debt

#6434 fix: remove debug assert dependend traces
  crates/net/network/src/transactions/fetcher.rs
Labels: C-bug, A-observability

#6442 fix(consensus): skip building only for ancestor
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-bug, A-consensus

#6443 chore: bump some deps
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#6404 Encapsulate `validate_header_regarding_parent` inside `SealedHeader`
  Cargo.lock
  crates/consensus/beacon-core/src/lib.rs
  crates/consensus/common/src/validation.rs
  crates/interfaces/src/consensus.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/header.rs
  crates/primitives/src/lib.rs
Labels: C-debt

#6448 add minor improvements
  crates/primitives/src/block.rs
  crates/primitives/src/storage.rs
  crates/primitives/src/withdrawal.rs
  crates/transaction-pool/src/validate/mod.rs
Labels: C-debt

#6449 fix: initial total_bytes value for response limit and typos
  crates/consensus/beacon/src/engine/handle.rs
  crates/net/discv4/src/config.rs
  crates/net/discv4/src/lib.rs
  crates/net/eth-wire/src/types/blocks.rs
  crates/net/network/src/config.rs
  crates/net/network/src/eth_requests.rs
  crates/primitives/src/transaction/pooled.rs
  crates/primitives/src/transaction/sidecar.rs
  crates/transaction-pool/src/traits.rs
Labels: C-enhancement, A-devp2p

#6437 feat: add txpool eviction property tests
  crates/transaction-pool/src/config.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/tests/it/evict.rs
  crates/transaction-pool/tests/it/main.rs
Labels: A-tx-pool, C-test

#6431 add unit tests for `BlobTransactionSidecar`
  crates/primitives/src/transaction/blob_data/README.md
  crates/primitives/src/transaction/blob_data/blob1.json
  crates/primitives/src/transaction/blob_data/blob2.json
  crates/primitives/src/transaction/blob_data/blob3.json
  crates/primitives/src/transaction/blob_data/blob4.json
  crates/primitives/src/transaction/sidecar.rs
Labels: C-test

#6458 chore: bump rpc deps
  Cargo.lock
  crates/rpc/rpc/src/eth/api/fees.rs
Labels: A-rpc

#6459 chore(net): downgrade unseen hashes log to trace
  crates/net/network/src/transactions/mod.rs
Labels: C-enhancement, A-observability, A-networking

#6466 perf(trie): pre-allocate prefix sets
  crates/trie/src/prefix_set/mod.rs
  crates/trie/src/state.rs
Labels: C-perf, A-trie

#6470 chore(`reth-primitives`): add decode/recover test for 4844 tx
  crates/primitives/src/transaction/mod.rs
Labels: C-test

#6456 fix: sealed header should not be immutable borrowed
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/node/events.rs
  bin/reth/src/init.rs
  crates/blockchain-tree/src/block_buffer.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/noop.rs
  crates/blockchain-tree/src/shareable.rs
  crates/consensus/auto-seal/src/task.rs
  crates/consensus/beacon/src/engine/invalid_headers.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/interfaces/src/blockchain_tree/error.rs
  crates/interfaces/src/p2p/full_block.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/node-core/src/utils.rs
  crates/payload/basic/src/lib.rs
  crates/payload/ethereum/src/lib.rs
  crates/payload/optimism/src/lib.rs
  crates/primitives/src/block.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/header.rs
  crates/rpc/rpc-types-compat/src/block.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/fee_history.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/cache/mod.rs
  crates/rpc/rpc/src/eth/gas_oracle.rs
  crates/rpc/rpc/src/trace.rs
  crates/stages/src/error.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/mod.rs
  crates/storage/provider/src/chain.rs
  crates/storage/provider/src/providers/snapshot/mod.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/traits.rs
  examples/db-access.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: C-debt

#6472 fix/ci: check individual crates in ci, fix features
  .github/workflows/lint.yml
  crates/ethereum-forks/Cargo.toml
Labels: C-debt

#6474 chore: fix validate_payload_timestamp engine spec comments
  crates/node-api/src/engine/mod.rs
Labels: C-docs, C-enhancement, A-consensus

#6478 feat(op): `Ecotone` hardfork spec
  crates/ethereum-forks/src/hardfork.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/revm/config.rs
Labels: A-op-reth

#6479 feat(op): `Ecotone` L1 fee parsing
  crates/revm/src/optimism/mod.rs
  crates/rpc/rpc/src/eth/api/block.rs
Labels: A-op-reth

#6480 feat(op): `Ecotone` reject blob txs
  crates/interfaces/src/executor.rs
  crates/payload/optimism/src/error.rs
  crates/payload/optimism/src/lib.rs
  crates/revm/src/optimism/processor.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: A-op-reth

#6468 fix(blockchain-tree): query latest canonical hashes from both db and snapshots
  crates/blockchain-tree/src/externals.rs
Labels: C-bug, A-blockchain-tree, A-snapshots

#6477 feat(txpool): discard_worst compat with suffix comma
  crates/transaction-pool/src/pool/txpool.rs
Labels: A-tx-pool

#6486 fix: update outdated op links
  book/run/optimism.md
Labels: C-docs

#6483 fix(trie): hashed state extension
  crates/trie/src/state.rs
Labels: C-bug, A-trie

#6445 add `test_discard_blobs_on_blob_tx_eviction` unit test
  Cargo.lock
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/sidecar.rs
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/blobstore/mem.rs
  crates/transaction-pool/src/blobstore/mod.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/test_data/blob1.json
Labels: C-test

#6488 feat(primitives): implement `Display` for `SegmentRangeInclusive`
  bin/reth/src/commands/db/stats.rs
  crates/primitives/src/snapshot/segment.rs
Labels: C-enhancement, A-cli, A-snapshots

#6491 chore(deps): rm unused dep
  Cargo.lock
  crates/consensus/auto-seal/Cargo.toml
  crates/consensus/auto-seal/tests/it/auto_mine.rs
Labels: C-debt

#6492 fix(bin): add snapshot hook to list of hooks
  bin/reth/src/builder.rs
  crates/consensus/beacon/src/engine/hooks/controller.rs
  crates/consensus/beacon/src/engine/hooks/snapshot.rs
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-bug, A-consensus, A-cli, A-snapshots

#6495 fix(docker): disable jemalloc feature by default
  Dockerfile
Labels: A-meta

#6497 chore(deps): bump curve25519-dalek, revert nightly pin
  .github/workflows/book.yml
  .github/workflows/dependencies.yml
  .github/workflows/lint.yml
  .github/workflows/sanity.yml
  Cargo.lock
  crates/net/network/src/protocol.rs
  crates/rpc/rpc/src/result.rs
Labels: A-meta

#6498 feat(bin): do not show target on INFO level
  crates/tracing/src/formatter.rs
Labels: C-enhancement, A-observability, A-cli

#6499 chore: make timestamp fork tests better
  Cargo.lock
  crates/consensus/beacon/src/engine/handle.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/chain/spec.rs
  crates/rpc/rpc-builder/src/auth.rs
Labels: C-enhancement, C-test

#6095 feat: Enhance block import log line
  bin/reth/src/commands/node/events.rs
  crates/consensus/beacon/src/engine/event.rs
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-enhancement, A-observability, A-cli

#6484 Cache update on chain action
  crates/rpc/rpc/src/eth/cache/mod.rs
Labels: C-bug, A-rpc

#6502 refactor(trie): prefix sets
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/trie/src/prefix_set/loader.rs
  crates/trie/src/prefix_set/mod.rs
  crates/trie/src/state.rs
  crates/trie/src/trie.rs
Labels: C-debt, A-trie

#6505 Update ci hive eth test suite
  .github/workflows/hive.yml
Labels: C-test

#6364 refactor: rm `CallRequest`
  Cargo.lock
  Cargo.toml
  crates/primitives/src/proofs.rs
  crates/rpc/rpc-api/src/debug.rs
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-api/src/eth.rs
  crates/rpc/rpc-api/src/trace.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-testing-util/src/debug.rs
  crates/rpc/rpc-testing-util/src/trace.rs
  crates/rpc/rpc-types-compat/src/transaction/mod.rs
  crates/rpc/rpc-types/src/eth/transaction/request.rs
  crates/rpc/rpc-types/src/eth/transaction/typed.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/engine.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-debt

#6509 chore(trie): export node iter
  crates/trie/src/lib.rs
  crates/trie/src/node_iter.rs
Labels: A-trie

#6512 dep: pin alloy & revm inspectors
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#6514 chore: actually impl clone regardless of trait
  crates/payload/builder/src/service.rs
Labels: C-debt, A-block-building

#5896 replace &Bytes with &[u8] in optimism functions
  crates/revm/src/optimism/mod.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: C-debt

#6517 chore: remove op-flagged arguments from receipt root calc
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/auto-seal/src/lib.rs
  crates/primitives/src/proofs.rs
  crates/primitives/src/receipt.rs
  crates/revm/src/optimism/processor.rs
  crates/revm/src/processor.rs
Labels: C-debt, A-sdk

#6523 chore: remove chain_spec from ExecutorFactory
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/revm/src/factory.rs
  crates/storage/provider/src/test_utils/executor.rs
  crates/storage/provider/src/traits/executor.rs
Labels: C-debt, A-blockchain-tree

#6519 best way to bring cli param to EthTransactionValidatorInner?
  bin/reth/src/commands/debug_cmd/build_block.rs
  book/cli/reth/node.md
  crates/node-core/src/args/txpool_args.rs
  crates/node-core/src/node_config.rs
  crates/transaction-pool/src/validate/constants.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/mod.rs
Labels: A-tx-pool

#6535 chore: bump revm +revm-inspectors+alloy
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#6537 chore(deps): remove build-time dependency on libgit2
  Cargo.lock
  crates/node-core/Cargo.toml
Labels: A-dependencies

#6548 perf(trie): reduce key copying
  crates/trie/src/trie_cursor/database_cursors.rs
  crates/trie/src/trie_cursor/mod.rs
  crates/trie/src/trie_cursor/noop.rs
  crates/trie/src/walker.rs
Labels: C-debt, C-perf, A-trie

#6540 reuse alloy-eips constants
  Cargo.lock
  Cargo.toml
  crates/primitives/Cargo.toml
  crates/primitives/src/constants/eip4844.rs
Labels: C-debt

#6539 More raw rpc request testing
  crates/rpc/rpc-builder/tests/it/http.rs
Labels: A-rpc, C-test

#6555 chore: remove non-existant `test-utils` cfg
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt

#6550 perf(db): introduce environment-level cache for metric handles
  Cargo.lock
  crates/storage/db/Cargo.toml
  crates/storage/db/src/implementation/mdbx/cursor.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/metrics.rs
  crates/storage/db/src/tables/mod.rs
Labels: C-perf, A-db

#6554 More raw rpc request testing
  crates/rpc/rpc-builder/tests/it/http.rs
Labels: A-rpc, C-test

#6552 refactor(db): unify table macros
  bin/reth/src/commands/db/diff.rs
  crates/storage/db/src/abstraction/table.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/metrics.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/db/src/tables/raw.rs
Labels: C-debt, A-db

#6563 chore: use `Table::TABLE` in more places
  bin/reth/src/commands/db/diff.rs
  bin/reth/src/commands/db/get.rs
  crates/prune/src/segments/headers.rs
  crates/storage/db/src/implementation/mdbx/cursor.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/metrics.rs
  crates/storage/db/src/tables/mod.rs
Labels: C-debt

#6465 feat(bin): `db get` for snapshots
  bin/reth/src/commands/db/get.rs
  crates/storage/db/src/snapshot/mask.rs
  crates/storage/db/src/snapshot/masks.rs
Labels: C-enhancement, A-cli, A-snapshots

#6561 fix: use real hash for derived from latest
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
Labels: C-bug, A-rpc

#6567 chore: remove EitherBlockExecutor
  crates/consensus/beacon/src/engine/test_utils.rs
Labels: C-debt, C-test

#6572 chore: improve BundleStateWithReceipts docs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
Labels: C-docs, A-execution

#6573 perf(db): pre-populate metric handles hashmap on env init
  Cargo.lock
  crates/storage/db/Cargo.toml
  crates/storage/db/src/metrics.rs
Labels: C-perf, A-db

#6577 small refactoring in rpc crate
  crates/rpc/rpc/src/eth/api/fee_history.rs
  crates/rpc/rpc/src/eth/api/sign.rs
  crates/rpc/rpc/src/eth/api/state.rs
Labels: A-rpc

#6387 feat(grafana): use reth_info to query Reth instances
  etc/grafana/dashboards/overview.json
Labels: A-observability

#6579 fix(bin): do not display stage progress when we start executing
  bin/reth/src/commands/node/events.rs
Labels: C-bug, A-staged-sync, A-observability

#6580 chore: simplify networkbuilder
  bin/reth/src/builder.rs
  crates/node-core/src/node_config.rs
Labels: C-debt

#6581 chore: move init to node-core
  bin/reth/src/builder.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/init_cmd.rs
  bin/reth/src/commands/recover/storage_tries.rs
  bin/reth/src/commands/stage/drop.rs
  bin/reth/src/lib.rs
  crates/node-core/src/init.rs
  crates/node-core/src/lib.rs
Labels: C-debt

#6549 Payload Events
  crates/node-api/src/engine/mod.rs
  crates/payload/builder/src/events.rs
  crates/payload/builder/src/lib.rs
  crates/payload/builder/src/noop.rs
  crates/payload/builder/src/service.rs
  crates/payload/builder/src/test_utils.rs
  crates/payload/builder/src/traits.rs
Labels: A-block-building

#6585 chore: move events mod to node core
  bin/reth/src/builder.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/node/mod.rs
  crates/node-core/src/events/cl.rs
  crates/node-core/src/events/mod.rs
  crates/node-core/src/events/node.rs
  crates/node-core/src/lib.rs
Labels: C-debt

#6584 feat(bin): `db stats --summary` to display totals for snapshots
  bin/reth/src/commands/db/stats.rs
Labels: C-enhancement, A-cli, A-snapshots

#6586 chore: bump alloy revm + inspectors
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-bug, A-dependencies

#6587 chore: add exit future back
  bin/reth/src/builder.rs
  crates/node-core/src/exit.rs
  crates/node-core/src/lib.rs
Labels: C-debt

#6318 Speed up request buffered hashes
  crates/net/eth-wire/src/types/broadcast.rs
  crates/net/network/src/cache.rs
  crates/net/network/src/metrics.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/peers/mod.rs
  crates/net/network/src/session/config.rs
  crates/net/network/src/transactions/constants.rs
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/traits.rs
Labels: M-changelog, C-perf, A-devp2p, A-tx-pool, A-networking

#6591 ci: auto-update homebrew formula
  .github/workflows/release-dist.yml
Labels: A-meta

#6596 chore: impl default for PendingPoolImportsInfo
  Cargo.lock
  crates/net/network/src/transactions/mod.rs
Labels: C-debt

#6600 chore: remove redundant map
  crates/node-api/src/engine/traits.rs
Labels: C-debt

#6603 oneline change set excess_blob_gas in local pending block header
  crates/rpc/rpc/src/eth/api/mod.rs
Labels: C-bug, A-rpc

#6609 fix(op): set handler cfg correctly in EvmProcessor
  crates/revm/src/processor.rs
Labels: C-bug, A-op-reth

#6607 fix: add missing depositReceiptVersion field
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: A-rpc, A-op-reth

#6487 feat: add `lz4` to `SnapshotSegment::Headers`
  crates/primitives/src/snapshot/segment.rs
  crates/storage/provider/src/providers/snapshot/writer.rs
Labels: A-snapshots

#6542 Cache invalid txns
  crates/net/network/src/metrics.rs
  crates/net/network/src/transactions/constants.rs
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
Labels: C-perf, A-tx-pool

#6612 fix: set AutoSealConsensus best_block correctly
  crates/consensus/auto-seal/src/lib.rs
Labels: C-bug, A-consensus, A-block-building, A-cli

#6608 feat: check snapshot range on `ProviderFactory`
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
Labels: A-snapshots

#6618 fix: update highest nonce if highest nonce
  crates/transaction-pool/src/pool/pending.rs
Labels: A-tx-pool

#6538 Implement `Deref` and `DerefMut` for `StateProviderDatabase`
  crates/revm/src/database.rs
  crates/rpc/rpc/src/eth/api/call.rs
Labels: C-debt

#6620 chore: dont set some ready when draining pending txs
  crates/net/network/src/transactions/mod.rs
Labels: C-perf

#6399 Accurately tracking on-disk blobstore metrics
  crates/transaction-pool/src/blobstore/disk.rs
  crates/transaction-pool/src/blobstore/mem.rs
  crates/transaction-pool/src/blobstore/mod.rs
  crates/transaction-pool/src/blobstore/noop.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#6623 Segmenting cfg and block env impl from PayloadBuilderAttributes
  bin/reth/Cargo.toml
  crates/consensus/beacon/Cargo.toml
  crates/node-api/Cargo.toml
  crates/node-api/src/engine/traits.rs
  crates/node-core/Cargo.toml
  crates/node-optimism/Cargo.toml
  crates/payload/builder/Cargo.toml
  crates/payload/builder/src/optimism.rs
  crates/payload/builder/src/payload.rs
  crates/revm/Cargo.toml
  crates/rpc/rpc-api/Cargo.toml
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc/Cargo.toml
  crates/storage/provider/Cargo.toml
  examples/custom-node/src/main.rs
Labels: C-debt

#6629 chore: remove unused smallvec dep
  Cargo.lock
  crates/primitives/Cargo.toml
Labels: C-debt, A-dependencies

#6635 Bump lru version
  Cargo.lock
  crates/blockchain-tree/Cargo.toml
Labels: A-dependencies

#6556 fix(revm): calculate failed transaction hash for logging
  crates/revm/src/processor.rs
Labels: C-bug, A-staged-sync, A-observability

#6636 feat: add debug_traceBlock test for entire chain
  crates/rpc/rpc-testing-util/src/debug.rs
  crates/rpc/rpc-testing-util/src/trace.rs
  crates/rpc/rpc-testing-util/tests/it/trace.rs
Labels: C-enhancement, A-rpc, C-test

#6638 chore: bump revm 6.0
  Cargo.lock
  Cargo.toml
  crates/node-ethereum/src/evm.rs
  crates/node-optimism/src/evm.rs
  crates/payload/builder/src/payload.rs
  crates/revm/src/processor.rs
  crates/rpc/rpc-types-compat/src/block.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/cache/mod.rs
  crates/storage/provider/src/traits/evm_env.rs
  examples/custom-node/src/main.rs
Labels: M-changelog, A-dependencies

#6627 updating block_env
  crates/rpc/rpc/src/debug.rs
Labels: C-bug, D-good-first-issue, A-rpc

#6640 chore: decrease network manager budget
  crates/net/network/src/manager.rs
Labels: A-networking

#6639 chore: discv4 touchups
  crates/net/discv4/src/config.rs
  crates/net/discv4/src/lib.rs
Labels: C-debt, A-networking

#6650 chore(grafana): make network pool metric readable
  etc/grafana/dashboards/overview.json
Labels: A-observability

#6652 test: enhance invalid tx test
  crates/net/network/src/transactions/mod.rs
  crates/net/network/tests/it/txgossip.rs
Labels: C-test, A-networking

#6653 test: fix connect many race condition
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/tests/it/connect.rs
Labels: C-test, A-networking

#6648 implements 'ethGetHeaderByNumber' and 'ethGetHeaderByHash'
  crates/rpc/rpc-api/src/eth.rs
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/server.rs
Labels: A-rpc

#6668 docs: finish missing doc
  crates/net/discv4/src/lib.rs
Labels: C-docs

#6658 feat: add metrics for highest pruned block per segment
  crates/prune/src/metrics.rs
  crates/prune/src/pruner.rs
Labels: C-enhancement, A-observability

#6669 fix(provider): history by block hash race condition
  crates/storage/provider/src/providers/database/mod.rs
Labels: C-bug, A-db

#6671 fix: set fees correctly on eth_sendTransaction
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-bug, A-rpc

#6672 fix: correct nonce gap update check
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-bug, A-tx-pool

#6649 fix the issue of network is not known to be merged
  bin/reth/src/builder.rs
  crates/node-builder/src/builder.rs
  crates/primitives/src/chain/spec.rs
Labels: C-enhancement, A-cli
