Repository paradigmxyz/reth, pull requests merged in 2024-11, with the labels that each got.

#12241 refactor(revm): simplify `Database` impl for `StateProviderDatabase`
  crates/revm/src/database.rs
Labels: C-debt

#12240 revm: add `Database` `Either` helper type
  crates/revm/src/either.rs
  crates/revm/src/lib.rs
Labels: C-enhancement, A-db

#12239 rpc: add `rename` method in `TransportRpcModules`
  crates/rpc/rpc-builder/src/lib.rs
Labels: C-enhancement

#12253 chore: apply same member order
  crates/blockchain-tree/src/noop.rs
  crates/exex/exex/src/notifications.rs
  crates/node/builder/src/builder/states.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/primitives/src/block.rs
  crates/rpc/rpc-eth-api/src/node.rs
  crates/rpc/rpc/src/eth/core.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/trie/trie/src/hashed_cursor/noop.rs
  crates/trie/trie/src/prefix_set.rs
Labels: C-debt

#12220 feat: track buffered outgoing messages
  crates/net/network/src/metrics.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/mod.rs
Labels: A-observability

#12185 Remove redundant `SignedTransaction::Signature`
  crates/primitives-traits/src/transaction/signed.rs
Labels: C-debt, A-sdk

#12236 feature: transaction's input truncate function
  crates/rpc/rpc-types-compat/src/transaction/mod.rs
Labels: A-rpc

#12252 refactor: move `payload/builder/src/database.rs` to `revm/src/cached.rs`
  Cargo.lock
  bin/reth/src/commands/debug_cmd/build_block.rs
  crates/payload/basic/Cargo.toml
  crates/payload/basic/src/lib.rs
  crates/payload/builder/Cargo.toml
  crates/payload/builder/src/lib.rs
  crates/revm/src/cached.rs
  crates/revm/src/lib.rs
Labels: C-debt

#12110 test(chain-state): add unit tests for `CanonStateNotification`
  crates/chain-state/src/notifications.rs
  crates/evm/execution-types/src/chain.rs
Labels: C-test

#12242 chore: simplify cached db usage
  crates/ethereum/payload/src/lib.rs
  crates/optimism/payload/src/builder.rs
  crates/revm/src/cached.rs
Labels: S-blocked, C-debt, A-block-building

#12255 renamed OptimismNetworkBuilder to OpNetworkBuilder
  crates/optimism/node/src/node.rs
Labels: A-op-reth

#12257 feat: add asref impls
  crates/revm/src/cached.rs
  crates/revm/src/database.rs
Labels: C-enhancement

#12235 fix: check hashed state for loading `TriePrefixSets::destroyed_accounts`
  crates/trie/db/src/prefix_set.rs
Labels: C-bug, A-staged-sync, A-trie

#12261 test: make cargo t compile in codecs
  crates/storage/codecs/src/alloy/mod.rs
  crates/storage/codecs/src/alloy/transaction/eip4844.rs
Labels: C-debt

#12265 renamed OptimismConsensusBuilder to OpConsensusBuilder
  crates/optimism/node/src/node.rs
Labels: A-op-reth

#12243 feat: flashbots_validateBuilderSubmissionV4
  crates/ethereum/node/tests/e2e/rpc.rs
  crates/rpc/rpc-api/src/lib.rs
  crates/rpc/rpc-api/src/validation.rs
  crates/rpc/rpc/src/validation.rs
Labels: C-enhancement, A-rpc

#12269 fix: clippy lints
  .github/workflows/lint.yml
  crates/chain-state/src/notifications.rs
Labels: C-debt

#12268 Use Arc<ChainSpec> in SystemCaller
  crates/engine/util/src/reorg.rs
  crates/ethereum/evm/src/execute.rs
  crates/evm/src/system_calls/mod.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/payload/src/builder.rs
  crates/payload/validator/src/lib.rs
Labels: C-debt, C-perf

#12270 renamed OptimismGenesisInfo to OpGenesisInfo
  crates/optimism/chainspec/src/lib.rs
Labels: A-op-reth

#12271 renamed OptimismBeaconConsensus to OpBeaconConsensus
  crates/optimism/consensus/src/lib.rs
  crates/optimism/node/src/node.rs
Labels: A-op-reth

#12272 chore(ci): unpin kurtosis
  .github/workflows/kurtosis.yml
Labels: C-debt, A-ci

#12277 feat: add `CachedReads::extend`
  crates/revm/src/cached.rs
Labels: A-db

#12281 renamed OptimismPayloadTypes to OpPayloadTypes
  crates/optimism/node/src/engine.rs
Labels: A-op-reth

#12280 feat: remove AnyNetwork usage
  Cargo.lock
  crates/optimism/rpc/src/eth/receipt.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-builder/tests/it/middleware.rs
  crates/rpc/rpc-eth-api/src/types.rs
  crates/rpc/rpc-eth-types/Cargo.toml
  crates/rpc/rpc-eth-types/src/lib.rs
  crates/rpc/rpc-eth-types/src/receipt.rs
  crates/rpc/rpc-types-compat/Cargo.toml
  crates/rpc/rpc-types-compat/src/transaction/mod.rs
  crates/rpc/rpc/src/eth/core.rs
  crates/rpc/rpc/src/eth/helpers/block.rs
  crates/rpc/rpc/src/eth/helpers/receipt.rs
  crates/rpc/rpc/src/eth/helpers/types.rs
  crates/rpc/rpc/src/eth/pubsub.rs
Labels: A-rpc

#12284 renamed OptimismEvmConfig to OpEvmConfig
  crates/optimism/evm/src/execute.rs
  crates/optimism/evm/src/lib.rs
  crates/optimism/node/src/node.rs
Labels: A-op-reth

#12288 feat: add more decimals to database growth
  etc/grafana/dashboards/overview.json
Labels: C-enhancement, A-observability

#12293 docs: add debug.etherscan in the book
  book/run/mainnet.md
Labels: C-docs

#12329 chore: switch op to new engine
  crates/optimism/bin/src/main.rs
  crates/optimism/node/src/args.rs
Labels: A-op-reth

#12324 chore: limit initial status size
  crates/net/eth-wire/src/ethstream.rs
Labels: A-networking

#12334 chore: 1.1.1
  Cargo.lock
  Cargo.toml
Labels: A-meta

#12229 feat: restructure op builder
  crates/optimism/payload/src/builder.rs
  crates/payload/basic/src/lib.rs
  crates/transaction-pool/src/traits.rs
Labels: S-blocked, C-debt, A-block-building, A-op-reth

#12343 feat(payload) : optimize new payload job by fetching only header hash instead of block
  crates/payload/basic/src/lib.rs
  crates/payload/primitives/src/error.rs
Labels: C-perf, A-block-building

#12316 feat(engine): use execute_with_state_hook in ExecutorMetrics
  Cargo.lock
  crates/engine/tree/src/tree/mod.rs
  crates/evm/Cargo.toml
  crates/evm/src/metrics.rs
Labels: C-perf, A-blockchain-tree

#12326 chore(sdk): define `FullBlock` trait
  crates/primitives-traits/src/block/mod.rs
  crates/primitives-traits/src/lib.rs
Labels: C-debt, A-sdk

#12327 chore(sdk): define `FullSignedTx` trait
  crates/primitives-traits/src/lib.rs
  crates/primitives-traits/src/transaction/signed.rs
Labels: C-debt, A-sdk

#12347 chore: misc trait bounds
  crates/payload/basic/src/lib.rs
Labels: C-debt

#12335 feat(engine): integrate executor with StateRootTask
  Cargo.lock
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/root.rs
Labels: C-perf, A-consensus, A-blockchain-tree, A-trie

#12356 feat: use 1559 functions directly
  Cargo.lock
  Cargo.toml
  crates/optimism/chainspec/src/lib.rs
  crates/optimism/node/src/engine.rs
  crates/optimism/payload/src/builder.rs
  crates/optimism/payload/src/error.rs
  crates/optimism/payload/src/payload.rs
  crates/optimism/rpc/src/eth/receipt.rs
Labels: A-op-reth

#12366 feat: add `PrimitiveSignature` to `test-vectors compact` tests
  crates/cli/commands/src/test_vectors/compact.rs
Labels: C-enhancement, C-test, A-ci

#12357 chore(sdk): Add `NodePrimitives::Receipt`
  crates/ethereum/node/src/node.rs
  crates/node/types/src/lib.rs
  crates/optimism/node/src/node.rs
Labels: C-debt, A-sdk

#12362 feat(rpc/admin): return deposit_contract_address for the admin_NodeInfo RPC
  crates/rpc/rpc/src/admin.rs
Labels: A-rpc

#12367 chore: move helper methods from `DatabaseProvider` to `DBProvider` as defaults
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/chain.rs
  crates/cli/commands/src/db/checksum.rs
  crates/storage/db-common/src/db_tool/mod.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/storage-api/src/database_provider.rs
Labels: A-db, A-sdk

#12376 chore: rm reth-provider dep
  Cargo.lock
  crates/payload/builder/Cargo.toml
  crates/payload/builder/src/service.rs
  crates/payload/builder/src/test_utils.rs
  crates/payload/builder/src/traits.rs
Labels: A-dependencies

#12145 feat(trie): reveal storage slots and calculate storage root in sparse trie
  crates/trie/sparse/src/state.rs
Labels: C-enhancement, A-trie

#11004 feat(payload): add support for stack of payload builders
  crates/payload/basic/src/lib.rs
  crates/payload/basic/src/stack.rs
Labels: A-block-building

#12374 chore: improve deps for payload prims
  .config/zepter.yaml
  Cargo.lock
  crates/consensus/beacon/Cargo.toml
  crates/optimism/payload/Cargo.toml
  crates/payload/primitives/Cargo.toml
  crates/payload/primitives/src/payload.rs
  crates/payload/primitives/src/traits.rs
Labels: A-dependencies

#12385 chore: remove auto-seal consensus
  .github/assets/check_wasm.sh
  Cargo.lock
  Cargo.toml
  crates/consensus/auto-seal/Cargo.toml
  crates/consensus/auto-seal/src/client.rs
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/auto-seal/src/mode.rs
  crates/consensus/auto-seal/src/task.rs
  crates/ethereum/node/Cargo.toml
  crates/ethereum/node/src/node.rs
  crates/ethereum/node/tests/e2e/dev.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/engine.rs
  crates/node/builder/src/launch/mod.rs
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/node.rs
  docs/repo/layout.md
Labels: C-enhancement, C-debt

#12387 fix: remove independent tx from all
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/pool/pending.rs
Labels: C-bug

#12382 fix: pending transaction ordering
  Cargo.lock
  crates/optimism/node/Cargo.toml
  crates/optimism/node/tests/e2e/p2p.rs
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-bug

#12320 feat(transaction-pool): chaining & static txs for best transactions trait
  Cargo.lock
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/lib.rs
  crates/optimism/node/src/utils.rs
  crates/optimism/node/tests/e2e/main.rs
  crates/optimism/node/tests/e2e/p2p.rs
  crates/optimism/node/tests/it/main.rs
  crates/optimism/node/tests/it/priority.rs
  crates/optimism/payload/src/builder.rs
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/traits.rs
Labels: C-enhancement, A-tx-pool

#12403 feat: introduce ParallelProof
  Cargo.lock
  crates/trie/parallel/Cargo.toml
  crates/trie/parallel/src/lib.rs
  crates/trie/parallel/src/parallel_proof.rs
Labels: C-enhancement, A-consensus, A-trie

#12408 chore(db): add log for read transaciton monitor sleep time
  crates/storage/libmdbx-rs/src/txn_manager.rs
Labels: A-db, A-observability

#12330 chore(sdk): Add `NodePrimitives::Transaction` and `NodePrimitives::SignedTx`
  Cargo.lock
  crates/ethereum/node/src/node.rs
  crates/node/types/Cargo.toml
  crates/node/types/src/lib.rs
  crates/optimism/node/src/node.rs
Labels: C-debt, A-sdk

#11529 chore(sdk): payload builder AT on `NodeComponents` and `FullNodeComponents`
  Cargo.lock
  crates/exex/exex/Cargo.toml
  crates/exex/exex/src/context.rs
  crates/node/api/Cargo.toml
  crates/node/api/src/node.rs
  crates/node/builder/src/builder/states.rs
  crates/node/builder/src/components/builder.rs
  crates/node/builder/src/components/mod.rs
  crates/node/builder/src/rpc.rs
  crates/optimism/node/src/node.rs
Labels: C-enhancement, A-sdk

#12423 chore: restrict payload builder error type
  crates/payload/primitives/src/traits.rs
Labels: A-block-building

#12428 chore: add PayloadBuilder to RpcNodeCore
  crates/optimism/rpc/src/eth/mod.rs
  crates/rpc/rpc-eth-api/src/node.rs
  crates/rpc/rpc/src/eth/core.rs
Labels: C-enhancement

#12398 chore(sdk): auto trait bounds `NodePrimitives`
  crates/ethereum/node/src/node.rs
  crates/node/types/src/lib.rs
  crates/optimism/node/src/node.rs
Labels: A-sdk

#12187 chore(sdk): impl `SignedTransaction` for `TransactionSigned`
  crates/primitives/src/transaction/mod.rs
Labels: A-sdk

#12439 chore: fix deny
  deny.toml
Labels: A-dependencies

#12435 feat: `NetworkPrimitives`
  crates/net/eth-wire-types/src/blocks.rs
  crates/net/eth-wire-types/src/broadcast.rs
  crates/net/eth-wire-types/src/lib.rs
  crates/net/eth-wire-types/src/message.rs
  crates/net/eth-wire-types/src/primitives.rs
  crates/net/eth-wire-types/src/transactions.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/tests/new_block.rs
  crates/net/eth-wire/tests/pooled_transactions.rs
  crates/primitives/src/transaction/pooled.rs
Labels: A-networking

#12444 chore(trie): rename reth-trie-parallel modules
  crates/blockchain-tree/src/chain.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/root.rs
  crates/trie/parallel/benches/root.rs
  crates/trie/parallel/src/lib.rs
  crates/trie/parallel/src/proof.rs
  crates/trie/parallel/src/root.rs
Labels: C-enhancement, A-trie

#12331 chore(sdk): define helper trait `FullNodePrimitives`
  Cargo.lock
  crates/node/types/Cargo.toml
  crates/node/types/src/lib.rs
  crates/primitives-traits/src/block/body.rs
  crates/primitives-traits/src/block/mod.rs
  crates/primitives-traits/src/lib.rs
  crates/primitives-traits/src/receipt.rs
  crates/primitives-traits/src/transaction/mod.rs
  crates/primitives-traits/src/transaction/signed.rs
  crates/primitives-traits/src/tx_type.rs
Labels: C-debt, A-sdk

#12446 chore(sdk): impl `Receipt` for `reth_primitives::Receipt`
  Cargo.lock
  crates/primitives-traits/src/receipt.rs
  crates/primitives/src/receipt.rs
Labels: C-debt, A-sdk

#12453 feat(spec): Holocene activation time for {OP/Base} Sepolia
  crates/optimism/chainspec/src/lib.rs
  crates/optimism/hardforks/src/hardfork.rs
  crates/optimism/node/src/engine.rs
Labels: A-op-reth

#12452 chore(sdk): define new `BlockHeader` trait
  crates/evm/Cargo.toml
  crates/evm/src/lib.rs
  crates/primitives-traits/src/block/header.rs
  crates/primitives-traits/src/block/mod.rs
  crates/primitives-traits/src/lib.rs
Labels: C-debt, A-sdk

#12201 chore(reth_primitives): Use trait for `size` methods in primitive types
  Cargo.lock
  crates/net/downloaders/Cargo.toml
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/request.rs
  crates/net/p2p/Cargo.toml
  crates/net/p2p/src/bodies/response.rs
  crates/primitives-traits/src/header/sealed.rs
  crates/primitives-traits/src/lib.rs
  crates/primitives-traits/src/size.rs
  crates/primitives/src/block.rs
  crates/primitives/src/transaction/mod.rs
  crates/prune/prune/Cargo.toml
  crates/prune/prune/src/segments/user/receipts_by_logs.rs
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: C-enhancement

#12443 feat(op): define OpTxType
  Cargo.lock
  crates/optimism/primitives/Cargo.toml
  crates/optimism/primitives/src/lib.rs
  crates/optimism/primitives/src/op_tx_type.rs
  crates/primitives-traits/src/tx_type.rs
Labels: C-enhancement, A-op-reth, A-sdk

#12438 chore: move trie functions to alloy
  Cargo.lock
  crates/optimism/consensus/Cargo.toml
  crates/optimism/consensus/src/proof.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/proofs.rs
  crates/trie/common/src/proofs.rs
  crates/trie/common/src/root.rs
  crates/trie/trie/Cargo.toml
Labels: C-enhancement, A-sdk

#12448 chore(sdk): make `ExecutionOutcome` generic over receipt
  Cargo.lock
  crates/engine/util/src/reorg.rs
  crates/evm/execution-types/Cargo.toml
  crates/evm/execution-types/src/execution_outcome.rs
  crates/optimism/evm/src/lib.rs
  crates/primitives-traits/src/receipt.rs
  crates/storage/provider/src/writer/mod.rs
Labels: C-debt, A-execution, A-consensus, A-op-reth, A-sdk

#12465 chore(sdk): Add `InMemorySize` as super trait of data primitive traits
  crates/primitives-traits/src/block/body.rs
  crates/primitives-traits/src/block/mod.rs
  crates/primitives-traits/src/transaction/mod.rs
Labels: C-debt, A-sdk

#12332 chore(sdk): add `NodePrimitives::TxType`
  crates/ethereum/node/src/node.rs
  crates/optimism/node/src/node.rs
  crates/primitives-traits/src/lib.rs
  crates/primitives-traits/src/node.rs
  crates/primitives-traits/src/tx_type.rs
Labels: C-debt, A-sdk

#12413 test(trie): add ParallelProof unit test
  crates/trie/common/src/proofs.rs
  crates/trie/parallel/src/proof.rs
Labels: C-test, A-trie

#12468 chore(deps): bump alloy to 0.6.3
  Cargo.lock
  Cargo.toml
  crates/primitives/src/transaction/mod.rs
Labels: A-dependencies

#12472 chore(deps): Update op-alloy to 0.6.4 in manifest
  Cargo.toml
Labels: A-dependencies

#12469 feat: make downloaders and clients generic over block parts
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/engine/service/src/service.rs
  crates/engine/tree/src/download.rs
  crates/net/downloaders/Cargo.toml
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/noop.rs
  crates/net/downloaders/src/bodies/queue.rs
  crates/net/downloaders/src/bodies/request.rs
  crates/net/downloaders/src/bodies/task.rs
  crates/net/downloaders/src/file_client.rs
  crates/net/downloaders/src/headers/noop.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/downloaders/src/headers/task.rs
  crates/net/downloaders/src/test_utils/bodies_client.rs
  crates/net/eth-wire-types/Cargo.toml
  crates/net/eth-wire-types/src/message.rs
  crates/net/eth-wire-types/src/primitives.rs
  crates/net/eth-wire/src/capability.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/multiplex.rs
  crates/net/network-api/src/downloaders.rs
  crates/net/network-api/src/events.rs
  crates/net/network-api/src/lib.rs
  crates/net/network/Cargo.toml
  crates/net/network/src/fetch/client.rs
  crates/net/network/src/fetch/mod.rs
  crates/net/network/src/message.rs
  crates/net/network/src/network.rs
  crates/net/network/src/state.rs
  crates/net/p2p/Cargo.toml
  crates/net/p2p/src/bodies/client.rs
  crates/net/p2p/src/bodies/downloader.rs
  crates/net/p2p/src/bodies/response.rs
  crates/net/p2p/src/either.rs
  crates/net/p2p/src/error.rs
  crates/net/p2p/src/full_block.rs
  crates/net/p2p/src/headers/client.rs
  crates/net/p2p/src/headers/downloader.rs
  crates/net/p2p/src/headers/error.rs
  crates/net/p2p/src/lib.rs
  crates/net/p2p/src/test_utils/bodies.rs
  crates/net/p2p/src/test_utils/full_block.rs
  crates/net/p2p/src/test_utils/headers.rs
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/setup.rs
  crates/node/core/Cargo.toml
  crates/node/core/src/node_config.rs
  crates/node/core/src/utils.rs
  crates/primitives-traits/src/block/header.rs
  crates/primitives-traits/src/header/sealed.rs
  crates/primitives-traits/src/size.rs
  crates/primitives/src/block.rs
  crates/stages/stages/src/stages/bodies.rs
  crates/stages/stages/src/stages/headers.rs
Labels: C-enhancement, A-sdk

#12247 feat: add ovm `BlockFileCodec`
  Cargo.lock
  crates/consensus/beacon/Cargo.toml
  crates/net/downloaders/Cargo.toml
  crates/net/downloaders/src/file_client.rs
  crates/optimism/cli/Cargo.toml
  crates/optimism/cli/src/lib.rs
  crates/optimism/cli/src/ovm_file_codec.rs
  crates/primitives/src/transaction/mod.rs
Labels: D-good-first-issue, A-op-reth

#12481 feat: make more network components generic over primitives
  Cargo.lock
  crates/net/eth-wire-types/Cargo.toml
  crates/net/eth-wire-types/src/primitives.rs
  crates/net/network/Cargo.toml
  crates/net/network/src/import.rs
  crates/net/network/src/message.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/conn.rs
  crates/net/network/src/session/handle.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
  crates/primitives-traits/src/block/body.rs
  crates/primitives-traits/src/block/mod.rs
  crates/primitives/src/block.rs
Labels: A-networking

#12483 chore: move standalone types to types crate
  crates/static-file/static-file/src/lib.rs
  crates/static-file/static-file/src/static_file_producer.rs
  crates/static-file/types/src/event.rs
  crates/static-file/types/src/lib.rs
Labels: A-db

#12479 chore: Update Holocene timestamp for Sepolia
  crates/optimism/chainspec/src/lib.rs
  crates/optimism/hardforks/src/hardfork.rs
  crates/optimism/node/src/engine.rs
Labels: A-op-reth

#12352 feat(rpc): add compression to JSON-RPC
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-layer/Cargo.toml
  crates/rpc/rpc-layer/src/compression_layer.rs
  crates/rpc/rpc-layer/src/lib.rs
Labels: C-enhancement, C-perf, A-rpc

#12484 chore: introduce tuple type for pruned info
  crates/prune/prune/src/event.rs
  crates/prune/prune/src/pruner.rs
  crates/prune/types/src/lib.rs
  crates/prune/types/src/pruner.rs
Labels: C-debt

#12488 chore: bump alloy 064
  Cargo.lock
  Cargo.toml
  crates/optimism/cli/src/ovm_file_codec.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/signature.rs
Labels: C-bug, A-rpc

#12490 chore: import static file types directly
  Cargo.lock
  crates/node/events/Cargo.toml
  crates/node/events/src/node.rs
Labels: A-dependencies

#12497 chore: add SealedHeader::seal
  crates/primitives-traits/src/header/sealed.rs
Labels: C-enhancement

#12499 chore: rm unused error variants
  crates/payload/primitives/src/error.rs
Labels: C-debt

#12496 chore: only issue single header request
  crates/node/core/src/utils.rs
Labels: C-debt

#12494 chore: use let some notation
  crates/node/core/src/utils.rs
Labels: C-debt

#12500 feat: add support for `eth_signTransaction`
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-eth-api/src/core.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
Labels: C-enhancement

#12511 chore(dep): bump alloy-trie
  Cargo.lock
Labels: A-dependencies

#12507 primitives: use `SealedHeader::seal`
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/chain-state/src/test_utils.rs
  crates/consensus/beacon/src/engine/invalid_headers.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/consensus/common/src/validation.rs
  crates/engine/tree/src/backfill.rs
  crates/engine/tree/src/download.rs
  crates/engine/tree/src/test_utils.rs
  crates/engine/tree/src/tree/mod.rs
  crates/ethereum/consensus/src/lib.rs
  crates/net/downloaders/src/file_client.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/downloaders/src/headers/test_utils.rs
  crates/net/p2p/src/full_block.rs
  crates/net/p2p/src/test_utils/headers.rs
  crates/node/core/src/utils.rs
  crates/primitives-traits/src/header/sealed.rs
  crates/primitives/src/block.rs
  crates/rpc/rpc-engine-api/tests/it/payload.rs
  crates/stages/stages/benches/setup/mod.rs
  crates/stages/stages/src/stages/execution.rs
  crates/stages/stages/src/stages/headers.rs
  crates/stages/stages/src/stages/merkle.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/storage-api/src/block.rs
  crates/transaction-pool/src/maintain.rs
  examples/db-access/src/main.rs
  testing/testing-utils/src/generators.rs
Labels: C-debt

#12437 chore(sdk): improve usability tx primitive traits
  crates/primitives-traits/src/lib.rs
  crates/primitives-traits/src/transaction/mod.rs
  crates/primitives-traits/src/transaction/signed.rs
  crates/primitives-traits/src/tx_type.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/tx_type.rs
Labels: C-enhancement, A-sdk

#12501 chore(utils): Util function for headers request
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/p2p/src/full_block.rs
  crates/net/p2p/src/headers/client.rs
Labels: C-enhancement

#12523 chore: simplify import path
  crates/storage/libmdbx-rs/src/txn_manager.rs
Labels: C-debt

#12525 tx-pool: add `PoolUpdateKind` for `CanonicalStateUpdate`
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#12344 introduce standalone estimate gas type
  crates/optimism/rpc/src/eth/call.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-api/src/helpers/estimate.rs
  crates/rpc/rpc-eth-api/src/helpers/mod.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc/src/eth/helpers/call.rs
Labels: C-enhancement, A-rpc, A-sdk

#12538 feat: move body writing to `BlockWriter` trait
  crates/net/p2p/src/bodies/response.rs
  crates/stages/stages/src/stages/bodies.rs
  crates/storage/db-models/src/blocks.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/block.rs
Labels: A-staged-sync, A-db

#12542 chore: rm reth testing utils dep from reth-primitives-traits
  Cargo.lock
  crates/primitives-traits/Cargo.toml
  crates/primitives-traits/src/header/sealed.rs
Labels: C-test

#12534 chore(sdk): Add trait bound `Compact` on `<T as FullTransaction>::Type`
  crates/primitives-traits/src/transaction/mod.rs
Labels: C-debt, A-db, A-sdk

#12554 chore: use crates directly in eth-wire
  Cargo.lock
  crates/net/eth-wire/Cargo.toml
  crates/net/eth-wire/src/errors/eth.rs
  crates/net/eth-wire/src/errors/p2p.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/multiplex.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/eth-wire/src/test_utils.rs
Labels: A-dependencies

#12541 chore: move gas_spent_by_transactions to traits
  crates/primitives-traits/src/receipt.rs
  crates/primitives/src/receipt.rs
Labels: A-sdk

#12556 refactor: use `DBProvider` in `HistoricalStateProvider`
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/state/historical.rs
Labels: C-debt, A-db, A-sdk

#12555 feat: impl block for sealedblock
  crates/primitives-traits/src/block/body.rs
  crates/primitives-traits/src/block/header.rs
  crates/primitives/src/block.rs
Labels: A-sdk

#12557 refactor: use `DBProvider` in `LatestStateProvider`
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  crates/exex/exex/src/backfill/test_utils.rs
  crates/stages/stages/src/stages/execution.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/state/latest.rs
Labels: A-db, A-sdk

#12558 refactor: don't reference `StaticFileProvider` in `static_file::Segment`
  crates/consensus/beacon/src/engine/hooks/static_file.rs
  crates/stages/stages/src/stages/headers.rs
  crates/static-file/static-file/src/segments/headers.rs
  crates/static-file/static-file/src/segments/mod.rs
  crates/static-file/static-file/src/segments/receipts.rs
  crates/static-file/static-file/src/segments/transactions.rs
  crates/static-file/static-file/src/static_file_producer.rs
Labels: A-db, A-sdk

#12559 fix(rpc): remove reference to preimage bool in debug_executionWitness
  crates/rpc/rpc-api/src/debug.rs
Labels: C-bug, C-docs, A-rpc

#12560 engine-primitives: make engine-tree independent of beacon-consensus crate
  Cargo.lock
  crates/consensus/beacon/src/engine/error.rs
  crates/consensus/beacon/src/engine/event.rs
  crates/consensus/beacon/src/engine/handle.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/engine/local/src/miner.rs
  crates/engine/local/src/service.rs
  crates/engine/primitives/Cargo.toml
  crates/engine/primitives/src/error.rs
  crates/engine/primitives/src/forkchoice.rs
  crates/engine/primitives/src/lib.rs
  crates/engine/primitives/src/message.rs
  crates/engine/service/Cargo.toml
  crates/engine/service/src/service.rs
  crates/engine/tree/src/engine.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/util/Cargo.toml
  crates/engine/util/src/engine_store.rs
  crates/engine/util/src/lib.rs
  crates/engine/util/src/reorg.rs
  crates/engine/util/src/skip_fcu.rs
  crates/engine/util/src/skip_new_payload.rs
  crates/node/events/Cargo.toml
  crates/node/events/src/node.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/error.rs
Labels: A-dependencies

#12566 chore: extract witness recorder helper type
  crates/revm/Cargo.toml
  crates/revm/src/lib.rs
  crates/revm/src/witness.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/debug.rs
Labels: C-enhancement, A-execution

#12565 feat: make `StaticFileProvider` generic over `NodePrimitives`
  Cargo.lock
  crates/cli/commands/src/common.rs
  crates/cli/commands/src/db/stats.rs
  crates/cli/commands/src/init_state/mod.rs
  crates/cli/commands/src/init_state/without_evm.rs
  crates/cli/commands/src/stage/drop.rs
  crates/cli/commands/src/stage/run.rs
  crates/engine/tree/src/persistence.rs
  crates/node/builder/src/launch/common.rs
  crates/node/metrics/Cargo.toml
  crates/node/metrics/src/hooks.rs
  crates/optimism/cli/src/commands/import_receipts.rs
  crates/optimism/cli/src/commands/init_state.rs
  crates/primitives-traits/src/node.rs
  crates/prune/prune/src/builder.rs
  crates/prune/prune/src/segments/set.rs
  crates/prune/prune/src/segments/static_file/headers.rs
  crates/prune/prune/src/segments/static_file/receipts.rs
  crates/prune/prune/src/segments/static_file/transactions.rs
  crates/stages/api/src/pipeline/mod.rs
  crates/stages/stages/src/stages/bodies.rs
  crates/stages/stages/src/stages/execution.rs
  crates/stages/stages/src/stages/mod.rs
  crates/stages/stages/src/test_utils/test_db.rs
  crates/storage/db-common/src/init.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/static_file/jar.rs
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/storage/provider/src/providers/static_file/mod.rs
  crates/storage/provider/src/providers/static_file/writer.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/static_file_provider.rs
  crates/storage/provider/src/writer/mod.rs
  crates/storage/provider/src/writer/static_file.rs
Labels: A-static-files, A-sdk

#12567 feat: introduce debug witness api
  crates/rpc/rpc-api/src/debug.rs
  crates/rpc/rpc-api/src/lib.rs
Labels: A-rpc

#12568 ci: exclude more crates for op tests
  .github/workflows/unit.yml
Labels: A-ci

#12548 chore(sdk): improve usability `TxType` trait
  Cargo.lock
  crates/optimism/primitives/Cargo.toml
  crates/optimism/primitives/src/lib.rs
  crates/optimism/primitives/src/tx_type.rs
  crates/primitives-traits/src/tx_type.rs
  crates/primitives/src/transaction/tx_type.rs
Labels: C-debt, A-sdk

#12579 feat: add payload witness fn
  crates/optimism/payload/src/builder.rs
Labels: A-op-reth

#12583 feat: add op debug witness api
  Cargo.lock
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/lib.rs
  crates/optimism/rpc/src/witness.rs
  crates/rpc/rpc-api/src/debug.rs
Labels: A-op-reth

#12590 chore(util): Add reth payload util
  Cargo.lock
  Cargo.toml
  crates/optimism/node/Cargo.toml
  crates/optimism/node/tests/it/priority.rs
  crates/optimism/payload/Cargo.toml
  crates/optimism/payload/src/builder.rs
  crates/payload/util/Cargo.toml
  crates/payload/util/src/lib.rs
  crates/payload/util/src/traits.rs
  crates/payload/util/src/transaction.rs
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/traits.rs
Labels: A-block-building

#12581 rm generics when useless
  crates/cli/commands/src/db/checksum.rs
  crates/cli/commands/src/db/get.rs
  crates/cli/commands/src/db/tui.rs
  crates/cli/commands/src/import.rs
  crates/cli/util/src/load_secret_key.rs
  crates/cli/util/src/parsers.rs
Labels: C-debt

#12530 chore(sdk): add NetworkPrimitives for NetworkManager
  Cargo.lock
  crates/net/network/Cargo.toml
  crates/net/network/src/builder.rs
  crates/net/network/src/config.rs
  crates/net/network/src/eth_requests.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/transactions/mod.rs
  crates/net/network/tests/it/connect.rs
  crates/net/network/tests/it/startup.rs
  examples/bsc-p2p/src/main.rs
  examples/custom-rlpx-subprotocol/src/main.rs
  examples/network/src/main.rs
  examples/polygon-p2p/src/main.rs
Labels: A-networking

#12594 chore: make clippy happy
  crates/cli/commands/src/common.rs
  crates/engine/primitives/src/forkchoice.rs
  crates/net/eth-wire/tests/pooled_transactions.rs
  crates/node/builder/src/launch/common.rs
  crates/optimism/rpc/src/eth/call.rs
  crates/prune/prune/src/segments/static_file/headers.rs
  crates/prune/types/src/limiter.rs
  crates/revm/src/batch.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/stages/api/src/pipeline/mod.rs
  crates/storage/db/src/metrics.rs
  crates/storage/db/src/static_file/mod.rs
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
  crates/trie/trie/src/forward_cursor.rs
  crates/trie/trie/src/hashed_cursor/post_state.rs
  crates/trie/trie/src/node_iter.rs
  crates/trie/trie/src/trie_cursor/in_memory.rs
  crates/trie/trie/src/trie_cursor/subnode.rs
  crates/trie/trie/src/walker.rs
  crates/trie/trie/src/witness.rs
Labels: C-debt

#12584 chore(sdk): Remove duplicate trait `BlockHeader`
  crates/primitives-traits/src/header/mod.rs
  crates/primitives-traits/src/header/sealed.rs
Labels: C-debt, A-sdk

#12599 chore: remove revm-primitives re-export
  Cargo.lock
  bin/reth/src/commands/debug_cmd/build_block.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/ethereum/evm/src/lib.rs
  crates/ethereum/payload/Cargo.toml
  crates/ethereum/payload/src/lib.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/builder/mod.rs
  crates/optimism/evm/src/lib.rs
  crates/optimism/payload/src/builder.rs
  crates/optimism/rpc/src/error.rs
  crates/optimism/rpc/src/eth/call.rs
  crates/optimism/rpc/src/eth/pending_block.rs
  crates/payload/primitives/Cargo.toml
  crates/payload/primitives/src/error.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/receipt.rs
  crates/revm/src/cached.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-api/src/helpers/estimate.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/rpc/rpc-eth-types/src/error/mod.rs
  crates/rpc/rpc/src/eth/bundle.rs
  crates/rpc/rpc/src/eth/sim_bundle.rs
  crates/trie/db/src/state.rs
  examples/custom-beacon-withdrawals/src/main.rs
  examples/custom-evm/src/main.rs
  examples/stateful-precompile/src/main.rs
Labels: A-dependencies

#12604 chore(cli): unify trait bounds
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/debug_cmd/mod.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  crates/cli/commands/src/common.rs
  crates/cli/commands/src/db/checksum.rs
  crates/cli/commands/src/db/mod.rs
  crates/cli/commands/src/db/stats.rs
  crates/cli/commands/src/import.rs
  crates/cli/commands/src/init_cmd.rs
  crates/cli/commands/src/init_state/mod.rs
  crates/cli/commands/src/prune.rs
  crates/cli/commands/src/recover/mod.rs
  crates/cli/commands/src/recover/storage_tries.rs
  crates/cli/commands/src/stage/drop.rs
  crates/cli/commands/src/stage/dump/execution.rs
  crates/cli/commands/src/stage/dump/hashing_account.rs
  crates/cli/commands/src/stage/dump/hashing_storage.rs
  crates/cli/commands/src/stage/dump/merkle.rs
  crates/cli/commands/src/stage/dump/mod.rs
  crates/cli/commands/src/stage/mod.rs
  crates/cli/commands/src/stage/run.rs
  crates/cli/commands/src/stage/unwind.rs
  crates/optimism/cli/src/commands/build_pipeline.rs
  crates/optimism/cli/src/commands/import.rs
  crates/optimism/cli/src/commands/import_receipts.rs
  crates/optimism/cli/src/commands/init_state.rs
Labels: A-sdk

#12613 chore(sdk): Add blanket impls for refs to prim traits
  Cargo.lock
  crates/evm/execution-types/src/execution_outcome.rs
  crates/primitives-traits/Cargo.toml
  crates/primitives-traits/src/block/body.rs
  crates/primitives-traits/src/block/header.rs
  crates/primitives-traits/src/block/mod.rs
  crates/primitives-traits/src/receipt.rs
  crates/primitives-traits/src/size.rs
  crates/primitives-traits/src/transaction/mod.rs
  crates/primitives-traits/src/transaction/signed.rs
  crates/primitives/src/block.rs
  crates/primitives/src/receipt.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-debt, A-sdk

#12608 feat: add merge_if_module_configured
  crates/rpc/rpc-builder/src/lib.rs
Labels: A-rpc

#12612 fix(deps): Fix dev-deps for `reth-primitives`
  .github/assets/check_wasm.sh
  crates/primitives/Cargo.toml
  testing/testing-utils/Cargo.toml
Labels: C-bug, C-test, A-dependencies

#12622 feat: install op debug exeuction witness
  Cargo.lock
  crates/node/builder/src/rpc.rs
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/node.rs
  crates/optimism/rpc/src/witness.rs
Labels: A-rpc

#12623 fix: add additional op checks for chain specific check
  crates/node/builder/src/launch/common.rs
Labels: A-op-reth

#12618 feat: add EthereumEthApiTypes
  crates/rpc/rpc/src/eth/helpers/types.rs
  crates/rpc/rpc/src/eth/mod.rs
Labels: C-enhancement

#12627 chore: refactor `MockTransaction`
  crates/net/network/src/transactions/mod.rs
  crates/net/network/tests/it/big_pooled_txs_req.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/tests/it/blobs.rs
  crates/transaction-pool/tests/it/evict.rs
  crates/transaction-pool/tests/it/listeners.rs
  crates/transaction-pool/tests/it/pending.rs
Labels: C-debt

#12609 test: add tests for base l1 blockinfo
  crates/optimism/rpc/src/eth/receipt.rs
Labels: C-test, A-op-reth

#12577 chore(sdk): Define `MaybeSerde`
  Cargo.lock
  crates/evm/execution-types/Cargo.toml
  crates/exex/exex/Cargo.toml
  crates/net/eth-wire-types/Cargo.toml
  crates/net/eth-wire/Cargo.toml
  crates/net/network/Cargo.toml
  crates/optimism/cli/Cargo.toml
  crates/optimism/primitives/Cargo.toml
  crates/optimism/primitives/src/tx_type.rs
  crates/primitives-traits/Cargo.toml
  crates/primitives-traits/src/account.rs
  crates/primitives-traits/src/block/body.rs
  crates/primitives-traits/src/block/header.rs
  crates/primitives-traits/src/block/mod.rs
  crates/primitives-traits/src/lib.rs
  crates/primitives-traits/src/node.rs
  crates/primitives-traits/src/receipt.rs
  crates/primitives-traits/src/transaction/mod.rs
  crates/primitives-traits/src/transaction/signed.rs
  crates/primitives/Cargo.toml
  crates/revm/Cargo.toml
  crates/storage/codecs/Cargo.toml
  crates/storage/db-api/Cargo.toml
  crates/storage/db-models/Cargo.toml
  crates/storage/db/Cargo.toml
  crates/storage/provider/Cargo.toml
  crates/transaction-pool/Cargo.toml
  crates/trie/common/Cargo.toml
Labels: C-debt, A-sdk

#12467 feat(trie): add extend method to MultiProof
  crates/trie/common/Cargo.toml
  crates/trie/common/src/proofs.rs
Labels: C-enhancement, A-trie

#12378 feat(engine): introduce sync implementation of StateRootTask
  Cargo.lock
  crates/engine/tree/Cargo.toml
  crates/engine/tree/benches/channel_perf.rs
  crates/engine/tree/src/tree/root.rs
Labels: C-perf, A-blockchain-tree, A-trie

#12510 feat(trie): turn TrieWitness methods into public functions
  crates/trie/trie/src/witness.rs
Labels: C-enhancement, A-trie

#12636 fix(discv5): warning discv5 config socket override
  crates/net/discv5/src/config.rs
Labels: C-bug, A-observability, A-discv5

#12614 chore(sdk): limit `FillTxEnv` to super trait of `FullSignedTx`
  Cargo.lock
  crates/optimism/payload/src/payload.rs
  crates/primitives-traits/src/lib.rs
  crates/primitives-traits/src/transaction/execute.rs
  crates/primitives-traits/src/transaction/mod.rs
  crates/primitives-traits/src/transaction/signed.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-debt, A-execution, A-sdk

#12635 chore(sdk): make `Chain` generic over data primitives
  crates/ethereum/node/src/node.rs
  crates/evm/execution-types/src/chain.rs
  crates/optimism/evm/src/lib.rs
  crates/optimism/node/src/node.rs
  crates/primitives-traits/src/node.rs
  crates/primitives/src/lib.rs
  crates/transaction-pool/src/blobstore/tracker.rs
Labels: C-debt, A-execution, A-sdk

#12651 chore: bump version 1.1.2
  Cargo.lock
  Cargo.toml
Labels: A-meta

#12643 tx-pool: add `all` method for `AllPoolTransactions`
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#12650 fix: do not delegate is_optimism check for Ethereum ChainSpec
  crates/chainspec/src/api.rs
Labels: C-bug

#12664 fix: run upkeep manually
  crates/node/builder/src/launch/common.rs
  crates/node/metrics/src/recorder.rs
  crates/node/metrics/src/server.rs
Labels: C-bug, A-observability

#12616 feat: trait-based storage API
  Cargo.lock
  bin/reth/src/commands/debug_cmd/execution.rs
  crates/cli/commands/Cargo.toml
  crates/cli/commands/src/common.rs
  crates/cli/commands/src/import.rs
  crates/cli/commands/src/stage/unwind.rs
  crates/e2e-test-utils/Cargo.toml
  crates/e2e-test-utils/src/lib.rs
  crates/ethereum/node/src/node.rs
  crates/exex/test-utils/src/lib.rs
  crates/node/builder/src/builder/mod.rs
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/engine.rs
  crates/node/builder/src/launch/mod.rs
  crates/node/builder/src/node.rs
  crates/node/builder/src/setup.rs
  crates/node/types/src/lib.rs
  crates/optimism/cli/src/commands/build_pipeline.rs
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/node.rs
  crates/primitives-traits/src/block/mod.rs
  crates/primitives/src/lib.rs
  crates/stages/stages/src/stages/bodies.rs
  crates/stages/stages/src/test_utils/test_db.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/providers/database/chain.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/mod.rs
  crates/storage/provider/src/traits/block.rs
  crates/storage/storage-api/Cargo.toml
  crates/storage/storage-api/src/chain.rs
  crates/storage/storage-api/src/lib.rs
  examples/custom-engine-types/src/main.rs
Labels: A-db, A-sdk

#12663 feat(trie): short-circuit account/storage reveal in sparse trie
  crates/trie/sparse/src/state.rs
Labels: C-perf, A-trie

#12638 feat(trie): introduce `TRIE_ACCOUNT_RLP_MAX_SIZE` constant
  crates/trie/parallel/src/proof.rs
  crates/trie/parallel/src/root.rs
  crates/trie/trie/src/constants.rs
  crates/trie/trie/src/lib.rs
  crates/trie/trie/src/proof.rs
  crates/trie/trie/src/trie.rs
  crates/trie/trie/src/witness.rs
Labels: C-enhancement, A-trie

#12634 chore(exex): emit warn log when WAL grows beyond a certain number of blocks
  crates/exex/exex/src/manager.rs
  crates/exex/exex/src/wal/cache.rs
  crates/exex/exex/src/wal/mod.rs
Labels: C-enhancement, A-observability, A-exex

#12673 chore: use jsonrpsee server crate directly
  Cargo.lock
  Cargo.toml
  crates/node/metrics/Cargo.toml
  crates/node/metrics/src/server.rs
Labels: C-debt, A-observability

#12674 chore(sdk): Add adapter type for `NodePrimitives::Receipt`
  crates/primitives-traits/src/lib.rs
  crates/primitives-traits/src/node.rs
Labels: A-sdk

#12551 feat(executor): add init methods to set TxEnv overrides
  crates/ethereum/evm/src/execute.rs
  crates/evm/src/either.rs
  crates/evm/src/execute.rs
  crates/evm/src/lib.rs
  crates/optimism/evm/src/execute.rs
Labels: C-enhancement, A-execution

#12677 chore: genericify some net tx types
  crates/net/network/src/transactions/mod.rs
Labels: A-networking

#12679 chore: group tx manager functions
  crates/net/network/src/network.rs
  crates/net/network/src/transactions/mod.rs
Labels: A-sdk

#12685 Add SDK codeowners
  .github/CODEOWNERS
Labels: A-meta, A-sdk

#12689 tx-pool: impl `From<SubPool>` for `Destination`
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/pool/update.rs
Labels: C-enhancement, A-tx-pool
