Repository paradigmxyz/reth, pull requests merged in 2024-01, with the labels that each got.

#5665 feat: restore tx pool after reboot
  bin/reth/src/builder/mod.rs
  bin/reth/src/dirs.rs
  crates/primitives/src/fs.rs
  crates/tasks/src/lib.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/maintain.rs
Labels: C-enhancement, A-tx-pool

#5920 feat(tx-pool): refactor `PoolInner` implementation using `get_pool_data` util method
  crates/transaction-pool/src/pool/mod.rs
Labels: A-tx-pool

#5919 fix: use unchecked sender recovery when loading from disk
  crates/primitives/src/block.rs
  crates/primitives/src/transaction/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-bug, A-rpc

#5922 docs: improve rlp transaction encoding docs
  crates/net/eth-wire/src/disconnect.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/eth-wire/src/types/message.rs
  crates/primitives/src/transaction/eip1559.rs
  crates/primitives/src/transaction/eip2930.rs
  crates/primitives/src/transaction/eip4844.rs
  crates/primitives/src/transaction/legacy.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/rpc/rpc-types/src/eth/block.rs
  crates/rpc/rpc-types/src/eth/transaction/typed.rs
Labels: C-docs, C-enhancement

#5923 Update broken links to `docs/crates/discv4.md`
  docs/crates/network.md
Labels: C-docs, C-enhancement

#5929 chore(storage): warning log about long read db transaction
  crates/storage/db/src/implementation/mdbx/tx.rs
Labels: C-enhancement, A-db, A-observability

#5925 chore: improve forkchoiceUpdated doc comments
  crates/rpc/rpc-api/src/engine.rs
Labels: C-docs, C-enhancement, A-rpc, A-consensus

#5926 chore: update licenses to use 2024
  LICENSE-APACHE
  LICENSE-MIT
Labels: C-enhancement

#5921 fix(BlockchainTree): remove forked chain receipts/reverts
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/chain.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
Labels: C-bug, A-blockchain-tree

#5937 chore: move BeaconConsensus to its own crate
  Cargo.lock
  Cargo.toml
  crates/consensus/beacon-core/Cargo.toml
  crates/consensus/beacon-core/src/lib.rs
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/lib.rs
Labels: C-debt

#5946 add documentation for `SecretKeyError` to remove `#[allow(missing_docs)]`
  bin/reth/src/args/secret_key.rs
Labels: C-docs

#5940 chore: move OP payload builder error to OP crate
  Cargo.lock
  crates/payload/builder/src/error.rs
  crates/payload/optimism/Cargo.toml
  crates/payload/optimism/src/error.rs
  crates/payload/optimism/src/lib.rs
Labels: C-debt, A-op-reth

#5942 feat(cli): enable backtrace on panic by default
  bin/reth/src/main.rs
  bin/reth/src/optimism.rs
Labels: C-enhancement, A-observability, A-cli

#5951 chore: simplify Database impls
  crates/revm/src/database.rs
Labels: C-debt

#5955 Improve mapping of MDBX error codes to human-readable errors
  crates/storage/libmdbx-rs/src/error.rs
Labels: C-debt, A-db

#5957 chore: use available created_address fn
  crates/revm/revm-inspectors/src/tracing/js/mod.rs
  crates/revm/revm-inspectors/src/tracing/mod.rs
  crates/revm/revm-inspectors/src/tracing/utils.rs
Labels: C-debt

#5966 feat(header): add `is_zero_difficulty` util function for POS
  crates/consensus/beacon-core/src/lib.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/primitives/src/header.rs
Labels: C-debt

#5960 chore: cleanup max block fetching
  bin/reth/src/builder/mod.rs
Labels: C-debt

#5961 chore: use existing fn for loading network secret key
  bin/reth/src/builder/mod.rs
Labels: C-debt

#5962 chore: add non critical spawn with graceful shutdown signal fn
  crates/tasks/src/lib.rs
Labels: C-enhancement

#5969 refactor : Simplify is_some in Header
  crates/primitives/src/header.rs
Labels: C-debt

#5933 Update full node prune config docs
  book/run/pruning.md
Labels: C-docs

#5974 chore: update MSRV to 1.75
  .github/workflows/lint.yml
  Cargo.toml
  clippy.toml
Labels: C-docs, C-enhancement

#5941 feat(storage): handle-slow-readers callback for MDBX
  Cargo.lock
  crates/storage/db/Cargo.toml
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/libmdbx-rs/Cargo.toml
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/libmdbx-rs/src/lib.rs
Labels: C-enhancement, A-db, A-observability

#5871 perf(tree): cache canonical trie updates
  Cargo.lock
  crates/blockchain-tree/Cargo.toml
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/chain.rs
  crates/blockchain-tree/src/metrics.rs
  crates/consensus/auto-seal/src/task.rs
  crates/storage/provider/src/chain.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/trie/src/updates.rs
Labels: C-perf, A-blockchain-tree

#5973 feat(storage): log tx opening location
  bin/reth/src/cli/db_type.rs
  crates/storage/db/src/abstraction/database.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/provider/src/providers/database/mod.rs
Labels: C-enhancement, A-db, A-observability

#5976 chore: improve BLS constant documentation
  crates/rpc/rpc-types/src/beacon/constants.rs
Labels: C-docs, A-utils

#5981 docs: update MSRV to 1.75.0
  README.md
Labels: C-docs, A-meta

#5972 feat(cli): debug replay engine
  bin/reth/src/args/debug_args.rs
  bin/reth/src/builder/mod.rs
  bin/reth/src/commands/debug_cmd/mod.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  crates/rpc/rpc-types/src/eth/engine/cancun.rs
Labels: C-enhancement, A-cli

#5982 chore: add TracingInspector::config
  crates/revm/revm-inspectors/src/tracing/mod.rs
Labels: C-enhancement

#5971 feat: Support txpool.locals in txpool.cli
  bin/reth/src/args/txpool_args.rs
  crates/transaction-pool/src/config.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool

#5984 feat(storage): downgrade tx open log to trace
  crates/storage/db/src/implementation/mdbx/tx.rs
Labels: C-enhancement, A-db, A-observability

#5985 fix(bin): process metrics version mismatch
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/prometheus_exporter.rs
  crates/interfaces/src/test_utils/generators.rs
  crates/net/eth-wire/src/muxdemux.rs
  crates/net/eth-wire/src/types/blocks.rs
  crates/net/eth-wire/src/types/message.rs
  crates/net/eth-wire/src/types/receipts.rs
  crates/net/eth-wire/src/types/state.rs
  crates/net/eth-wire/src/types/transactions.rs
  crates/net/eth-wire/src/types/version.rs
  crates/net/network/src/cache.rs
  crates/net/network/src/peers/manager.rs
  crates/primitives/src/block.rs
  crates/primitives/src/integer_list.rs
  crates/primitives/src/serde_helper/prune.rs
  crates/rpc/rpc-types/src/serde_helpers/json_u256.rs
  crates/rpc/rpc/src/eth/signer.rs
  crates/storage/db/src/tables/models/accounts.rs
  crates/storage/db/src/tables/models/blocks.rs
  crates/storage/libmdbx-rs/src/error.rs
  crates/storage/provider/src/providers/snapshot/mod.rs
  testing/ef-tests/src/models.rs
Labels: C-bug, A-observability, A-cli

#5977 Use text instead of bash for CLI docs
  book/cli/reth/config.md
  book/cli/reth/db.md
  book/cli/reth/db/clear.md
  book/cli/reth/db/diff.md
  book/cli/reth/db/drop.md
  book/cli/reth/db/get.md
  book/cli/reth/db/list.md
  book/cli/reth/db/path.md
  book/cli/reth/db/snapshot.md
  book/cli/reth/db/stats.md
  book/cli/reth/db/version.md
  book/cli/reth/debug.md
  book/cli/reth/import.md
  book/cli/reth/init.md
  book/cli/reth/node.md
  book/cli/reth/p2p.md
  book/cli/reth/p2p/body.md
  book/cli/reth/p2p/header.md
  book/cli/reth/recover.md
  book/cli/reth/recover/storage-tries.md
  book/cli/reth/stage.md
  book/cli/reth/stage/drop.md
  book/cli/reth/stage/dump.md
  book/cli/reth/stage/dump/account-hashing.md
  book/cli/reth/stage/dump/execution.md
  book/cli/reth/stage/dump/merkle.md
  book/cli/reth/stage/dump/storage-hashing.md
  book/cli/reth/stage/run.md
  book/cli/reth/stage/unwind.md
  book/cli/reth/stage/unwind/num-blocks.md
  book/cli/reth/stage/unwind/to-block.md
  book/cli/reth/test-vectors.md
  book/cli/reth/test-vectors/tables.md
Labels: C-docs

#5978 add `ChainConfig` utils for block and timestamp comparisons
  crates/primitives/src/genesis.rs
Labels: C-enhancement

#5804 feat: preload cachedreads with tip state
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/cli/ext.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  crates/payload/basic/src/lib.rs
  crates/payload/builder/Cargo.toml
  crates/payload/builder/src/database.rs
  crates/payload/builder/src/service.rs
  crates/payload/builder/src/test_utils.rs
  crates/payload/builder/src/traits.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
Labels: C-perf, A-block-building

#5988 test(tracing): allow tracer init to fail
  crates/tracing/src/lib.rs
Labels: A-observability, C-test

#5987 release: v0.1.0-alpha.14
  Cargo.lock
  Cargo.toml
  book/cli/reth/node.md
  book/cli/reth/stage/run.md
Labels: A-meta

#5990 chore: move revm inspectors to alloy rpc types
  Cargo.lock
  crates/revm/revm-inspectors/Cargo.toml
  crates/revm/revm-inspectors/src/access_list.rs
  crates/revm/revm-inspectors/src/tracing/builder/geth.rs
  crates/revm/revm-inspectors/src/tracing/builder/parity.rs
  crates/revm/revm-inspectors/src/tracing/config.rs
  crates/revm/revm-inspectors/src/tracing/fourbyte.rs
  crates/revm/revm-inspectors/src/tracing/types.rs
Labels: A-rpc

#5991 fix(storage): disable MDBX HSR on Windows
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/libmdbx-rs/Cargo.toml
  crates/storage/libmdbx-rs/src/environment.rs
Labels: C-bug, C-enhancement, A-db

#5993 chore: remove unnecessary test-utils usage in reth cli
  bin/reth/Cargo.toml
Labels: C-debt, A-cli

#3819 docs: memory profiling and OOM debugging tutorial
  book/developers/profiling.md
Labels: C-docs, M-prevent-stale

#5999 fix: use cfg attributes over macro
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: C-bug

#6000 fix(storage): gate MDBX HSR with macro
  Cargo.lock
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: C-bug, A-db

#6003 chore: cleanup Cargo.lock
  Cargo.lock
Labels: A-meta

#6011 chore: move optimism payload attribute types to optimism.rs files
  crates/payload/builder/src/lib.rs
  crates/payload/builder/src/optimism.rs
  crates/payload/builder/src/payload.rs
  crates/rpc/rpc-types/src/eth/engine/mod.rs
  crates/rpc/rpc-types/src/eth/engine/optimism.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
Labels: C-enhancement, A-rpc, A-consensus

#5998 Move `FileClient` and `BlockFileCodec` out of test-utils
  bin/reth/Cargo.toml
  bin/reth/src/commands/import.rs
  crates/net/downloaders/Cargo.toml
  crates/net/downloaders/src/file_client.rs
  crates/net/downloaders/src/file_codec.rs
  crates/net/downloaders/src/lib.rs
  crates/net/downloaders/src/test_utils/mod.rs
Labels: C-debt

#6019 chore: remove empty EngineHookAction
  crates/consensus/beacon/src/engine/hooks/controller.rs
  crates/consensus/beacon/src/engine/hooks/mod.rs
  crates/consensus/beacon/src/engine/hooks/prune.rs
  crates/consensus/beacon/src/engine/hooks/snapshot.rs
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-enhancement, A-consensus

#6029 chore: remove redundant cfg_and_block_env method
  crates/payload/builder/src/payload.rs
Labels: C-debt, A-block-building

#6034 fix: Add canyon to `base mainnet`
  crates/primitives/src/chain/spec.rs
Labels: A-op-reth

#6033 chore: make clippy happy
  bin/reth/src/commands/debug_cmd/execution.rs
  crates/snapshot/src/snapshotter.rs
  crates/transaction-pool/src/lib.rs
Labels: C-enhancement

#6038 test: add base payload serde test
  crates/rpc/rpc-types/src/eth/engine/optimism.rs
Labels: C-test

#6035 fmt: run nightly-2023-10-15 and remove semicolons
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/net/eth-wire/src/test_utils.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/swarm.rs
  crates/net/network/tests/it/multiplex.rs
  crates/payload/validator/src/lib.rs
  crates/primitives/src/block.rs
  crates/primitives/src/header.rs
  crates/primitives/src/receipt.rs
  crates/revm/src/optimism/processor.rs
  crates/revm/src/processor.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/hashing_account.rs
  crates/storage/codecs/src/lib.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
  crates/storage/provider/src/test_utils/executor.rs
  crates/transaction-pool/src/pool/txpool.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: C-debt

#6039 chore(db): format backtrace
  crates/storage/db/src/implementation/mdbx/tx.rs
Labels: A-db, A-observability

#6027 resolve some missing doc and clippy
  crates/net/network/src/config.rs
  crates/rpc/ipc/src/server/mod.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/test_utils/mod.rs
Labels: C-docs

#6040 fix: Activate shanghai with `Canyon` on Base Mainnet
  crates/primitives/src/chain/spec.rs
Labels: A-op-reth

#6041 fix: path of rpc-db in README.md in examples
  examples/README.md
Labels: C-docs

#6046 fix: use proper decoding types in Header::decode
  crates/primitives/src/header.rs
Labels: C-bug, A-networking

#6047 fix: change vergen features to match foundry
  Cargo.lock
  bin/reth/Cargo.toml
  crates/storage/db/Cargo.toml
Labels: C-bug, A-db

#6048 chore: bump aquamarine
  Cargo.lock
  Cargo.toml
  crates/blockchain-tree/docs/mermaid/tree.mmd
  crates/net/network/docs/mermaid/fetch-client.mmd
  crates/net/network/docs/mermaid/network-manager.mmd
  crates/net/network/docs/mermaid/swarm.mmd
  crates/stages/docs/mermaid/pipeline.mmd
  crates/transaction-pool/docs/mermaid/txpool.mmd
Labels: C-bug, C-docs

#6042 fix(cli): snapshot up to the best block number, not last
  bin/reth/src/commands/db/snapshots/mod.rs
Labels: C-bug, A-cli, A-snapshots

#5723 feat: add `activation_block` method for Ethereum hardforks
  Cargo.lock
  crates/ethereum-forks/Cargo.toml
  crates/ethereum-forks/src/hardfork.rs
Labels: C-enhancement

#6043 some refactoring in `transaction-pool` mock utils
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/test_utils/pool.rs
Labels: A-tx-pool, C-test

#6025 feat: test tracer
  book/cli/reth/init.md
  crates/net/network/src/session/active.rs
  crates/net/network/src/transactions.rs
  crates/net/network/tests/it/big_pooled_txs_req.rs
  crates/net/network/tests/it/connect.rs
  crates/net/network/tests/it/geth.rs
  crates/net/network/tests/it/txgossip.rs
  crates/tracing/src/lib.rs
  crates/tracing/src/test_tracer.rs
Labels: A-observability, C-test

#6065 fix(op): activate node-api optimism feature
  bin/reth/Cargo.toml
  crates/node-api/Cargo.toml
  crates/payload/basic/src/lib.rs
  crates/payload/builder/src/optimism.rs
  crates/payload/optimism/src/lib.rs
Labels: C-bug, A-op-reth

#6064 update clippy commands in `CONTRIBUTING.md` file
  CONTRIBUTING.md
Labels: C-docs

#6067 ci: update aarch64 linux in release workflow
  .github/workflows/release.yml
  Makefile
  book/installation/source.md
Labels: A-meta

#6070 chore(db): skip serializing phantom data
  crates/storage/db/src/tables/raw.rs
Labels: C-debt, A-db

#6069 fix(cli): db tui serialization
  bin/reth/src/commands/db/tui.rs
Labels: C-bug, A-cli

#6066 refactor(trie): hashed post state
  Cargo.lock
  bin/reth/src/commands/debug_cmd/build_block.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/bundle_state/hashed_state_changes.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/traits/block.rs
  crates/trie/Cargo.toml
  crates/trie/src/hashed_cursor/post_state.rs
  crates/trie/src/lib.rs
  crates/trie/src/state.rs
Labels: C-debt, A-trie

#6016 improve usability of schnellru::LruMap and LruCache (LinkedHashSet cache)
  Cargo.lock
  Cargo.toml
  crates/net/network/Cargo.toml
  crates/net/network/src/cache.rs
Labels: C-enhancement, A-networking

#6068 chore: improve `HashedStorage`
  crates/trie/Cargo.toml
  crates/trie/src/hashed_cursor/post_state.rs
  crates/trie/src/prefix_set/mod.rs
  crates/trie/src/state.rs
Labels: C-debt, A-trie

#6060 Added extension support for auth rpc module
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/cli/components.rs
  crates/rpc/rpc-builder/src/auth.rs
  examples/additional-rpc-namespace-in-cli/src/main.rs
Labels: A-rpc, A-cli

#6028 feat: add BuiltPayload associated type to EngineTypes
  bin/reth/src/cli/ext.rs
  crates/node-api/src/engine/mod.rs
  crates/node-api/src/engine/traits.rs
  crates/node-api/src/lib.rs
  crates/node-builder/src/engine.rs
  crates/payload/basic/src/lib.rs
  crates/payload/builder/src/lib.rs
  crates/payload/builder/src/noop.rs
  crates/payload/builder/src/payload.rs
  crates/payload/builder/src/service.rs
  crates/payload/builder/src/test_utils.rs
  crates/payload/builder/src/traits.rs
  crates/payload/ethereum/src/lib.rs
  crates/payload/optimism/src/lib.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-enhancement, A-block-building

#6050 feat: add version_specific_fields method to EngineTypes
  bin/reth/Cargo.toml
  crates/node-api/Cargo.toml
  crates/node-api/src/engine/mod.rs
  crates/node-api/src/engine/traits.rs
  crates/node-api/src/lib.rs
  crates/node-builder/Cargo.toml
  crates/node-builder/src/engine.rs
  crates/node-builder/src/lib.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-enhancement, A-consensus

#6082 chore: add missing outgoing message check
  crates/net/eth-wire/src/p2pstream.rs
Labels: A-networking

#6084 chore: use diskfile blobstore
  bin/reth/src/builder/mod.rs
Labels: A-tx-pool, A-cli

#6096 fix(ci): conditional asm feature
  .github/workflows/release.yml
  Makefile
Labels: A-meta

#6097 feat(book): update CLI section
  book/SUMMARY.md
  book/cli/SUMMARY.md
  book/cli/help.py
  book/cli/reth.md
  book/cli/reth/config.md
  book/cli/reth/db.md
  book/cli/reth/db/clear.md
  book/cli/reth/db/diff.md
  book/cli/reth/db/drop.md
  book/cli/reth/db/get.md
  book/cli/reth/db/list.md
  book/cli/reth/db/path.md
  book/cli/reth/db/snapshot.md
  book/cli/reth/db/stats.md
  book/cli/reth/db/version.md
  book/cli/reth/debug.md
  book/cli/reth/import.md
  book/cli/reth/init.md
  book/cli/reth/node.md
  book/cli/reth/p2p.md
  book/cli/reth/p2p/body.md
  book/cli/reth/p2p/header.md
  book/cli/reth/recover.md
  book/cli/reth/recover/storage-tries.md
  book/cli/reth/stage.md
  book/cli/reth/stage/drop.md
  book/cli/reth/stage/dump.md
  book/cli/reth/stage/dump/account-hashing.md
  book/cli/reth/stage/dump/execution.md
  book/cli/reth/stage/dump/merkle.md
  book/cli/reth/stage/dump/storage-hashing.md
  book/cli/reth/stage/run.md
  book/cli/reth/stage/unwind.md
  book/cli/reth/stage/unwind/num-blocks.md
  book/cli/reth/stage/unwind/to-block.md
  book/cli/reth/test-vectors.md
  book/cli/reth/test-vectors/tables.md
Labels: C-docs

#6101 fix: return TaskManager in spawn_node
  bin/reth/src/builder/mod.rs
Labels: C-bug, C-test

#6073 feat(stages): duration threshold for `Execution` stage
  bin/reth/src/builder/mod.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/node/events.rs
  bin/reth/src/commands/stage/dump/merkle.rs
  bin/reth/src/commands/stage/run.rs
  book/run/config.md
  crates/config/src/config.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/mod.rs
Labels: C-enhancement, A-staged-sync, A-observability

#6107 feat: add optimism canyon engine tests
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/builder/mod.rs
  crates/rpc/rpc-types/src/eth/engine/optimism.rs
Labels: A-consensus, C-test, A-op-reth

#5897 refactor in trie crate
  crates/trie/src/trie_cursor/subnode.rs
  crates/trie/src/walker.rs
Labels: A-trie

#6072 feat(trie): construct `HashedPostState` from revert range
  crates/storage/provider/src/bundle_state/hashed_state_changes.rs
  crates/trie/src/hashed_cursor/post_state.rs
  crates/trie/src/state.rs
Labels: C-enhancement, A-trie

#6116 chore(deps): bump h2 dependency
  Cargo.lock
Labels: A-dependencies

#6120 fix: enable tls feature correctly
  Cargo.lock
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/api/mod.rs
Labels: C-bug, A-rpc

#6118 feat: add `HeadersTD` static file segment
  bin/reth/src/commands/db/snapshots/mod.rs
  crates/primitives/src/snapshot/mod.rs
  crates/primitives/src/snapshot/segment.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
Labels: A-snapshots

#5822 feat(snapshot, prune): transactions
  bin/reth/src/builder/mod.rs
  bin/reth/src/commands/db/snapshots/mod.rs
  crates/consensus/beacon/src/engine/hooks/controller.rs
  crates/consensus/beacon/src/engine/hooks/snapshot.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/primitives/src/prune/mode.rs
  crates/prune/src/builder.rs
  crates/prune/src/pruner.rs
  crates/prune/src/segments/set.rs
  crates/snapshot/src/lib.rs
  crates/snapshot/src/segments/headers.rs
  crates/snapshot/src/segments/mod.rs
  crates/snapshot/src/segments/receipts.rs
  crates/snapshot/src/segments/transactions.rs
  crates/snapshot/src/snapshotter.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/db/src/snapshot/mod.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
Labels: C-enhancement, A-pruning, A-snapshots

#6117 Cap max graceful disconnects
  crates/net/network/src/session/mod.rs
Labels: C-enhancement

#6124 test: add additional recover test
  crates/primitives/src/transaction/mod.rs
Labels: C-test

#6109 feat: add with_unused_ports method to rpc and network args
  bin/reth/src/args/network_args.rs
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/builder/mod.rs
Labels: C-enhancement, C-test, A-cli

#6123 chore: use alloy engine rpc type
  Cargo.lock
  Cargo.toml
  crates/node-api/src/engine/mod.rs
  crates/node-api/src/engine/payload.rs
  crates/node-api/src/engine/traits.rs
  crates/payload/builder/src/optimism.rs
  crates/payload/builder/src/payload.rs
  crates/primitives/src/transaction/sidecar.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/eth/engine/cancun.rs
  crates/rpc/rpc-types/src/eth/engine/forkchoice.rs
  crates/rpc/rpc-types/src/eth/engine/mod.rs
  crates/rpc/rpc-types/src/eth/engine/optimism.rs
  crates/rpc/rpc-types/src/eth/engine/payload.rs
  crates/rpc/rpc-types/src/eth/engine/transition.rs
  crates/rpc/rpc-types/src/eth/mod.rs
  crates/rpc/rpc-types/src/eth/transaction/request.rs
  crates/rpc/rpc-types/src/eth/transaction/typed.rs
  crates/rpc/rpc-types/src/lib.rs
Labels: A-rpc

#6134 chore: flip if else arms for eip155 check
  crates/primitives/src/transaction/signature.rs
Labels: C-debt

#6136 fix: use non-None enveloped tx for trace_call
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: C-bug, A-rpc, A-op-reth

#6139 Fix bug, buffered hashes of different eth versions from same peer
  crates/net/network/src/transactions/fetcher.rs
Labels: A-networking

#6135 feat: use alloy genesis now
  Cargo.lock
  Cargo.toml
  bin/reth/src/init.rs
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/engine/mod.rs
  crates/net/network/Cargo.toml
  crates/net/network/src/transactions/mod.rs
  crates/net/network/tests/it/clique/clique_middleware.rs
  crates/net/network/tests/it/clique/geth.rs
  crates/net/network/tests/it/connect.rs
  crates/net/network/tests/it/geth.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/account.rs
  crates/primitives/src/genesis.rs
  crates/primitives/src/lib.rs
  crates/trie/src/proof.rs
Labels: C-debt

#6149 feat(discv4): small improvements and documentation for discv4
  crates/net/discv4/src/config.rs
  crates/net/discv4/src/proto.rs
Labels: C-debt

#6142 improve documentation and refactor transaction-pool gen test utils
  crates/transaction-pool/src/test_utils/gen.rs
Labels: A-tx-pool, C-test

#6152 add missing documentation and minor refactor
  crates/consensus/auto-seal/tests/it/auto_mine.rs
  crates/consensus/beacon/src/engine/message.rs
  crates/net/discv4/src/proto.rs
  crates/net/discv4/src/test_utils.rs
  crates/net/dns/src/tree.rs
Labels: C-docs

#6144 feat(access-list): refactor and add some utils to `AccessList`
  crates/primitives/src/transaction/access_list.rs
Labels: C-enhancement

#6155 test: add sanity envelope encode test
  crates/primitives/src/transaction/mod.rs
Labels: C-test

#6156 chore: bump shlex; advisory RUSTSEC-2024-0006
  Cargo.lock
  crates/storage/libmdbx-rs/mdbx-sys/Cargo.toml
Labels: A-dependencies

#6161 chore(meta): require platform and version in bug reports
  .github/ISSUE_TEMPLATE/bug.yml
Labels: A-meta

#6162 meta: add @emhane as net codeowner
  CODEOWNERS
Labels: A-meta

#6164 remove unused consensus `full_validation` method
  crates/consensus/common/src/validation.rs
Labels: C-debt

#6163 add `ensure_transaction_root_valid` method for `SealedBlock`
  crates/consensus/common/src/validation.rs
  crates/primitives/src/block.rs
Labels: C-debt

#6150 Bug fix, tx fetcher `fill_request_for_peer`
  crates/net/network/src/cache.rs
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
Labels: C-bug, A-networking

#6169 chore: delete duplicated node args types
  bin/reth/src/args/database_args.rs
  bin/reth/src/args/debug_args.rs
  bin/reth/src/args/dev_args.rs
  bin/reth/src/args/gas_price_oracle_args.rs
  bin/reth/src/args/log_args.rs
  bin/reth/src/args/mod.rs
  bin/reth/src/args/network_args.rs
  bin/reth/src/args/payload_builder_args.rs
  bin/reth/src/args/pruning_args.rs
  bin/reth/src/args/rollup_args.rs
  bin/reth/src/args/rpc_server_args.rs
  bin/reth/src/args/rpc_state_cache_args.rs
  bin/reth/src/args/secret_key.rs
  bin/reth/src/args/stage_args.rs
  bin/reth/src/args/txpool_args.rs
  bin/reth/src/args/types.rs
  bin/reth/src/args/utils.rs
  bin/reth/src/cli/components.rs
  bin/reth/src/cli/config.rs
  bin/reth/src/cli/ext.rs
  bin/reth/src/cli/mod.rs
  bin/reth/src/dirs.rs
  bin/reth/src/init.rs
  bin/reth/src/lib.rs
  bin/reth/src/utils.rs
  bin/reth/src/version.rs
  crates/node-core/src/args/network_args.rs
  crates/node-core/src/args/rpc_server_args.rs
  crates/node-core/src/utils.rs
  crates/node-core/src/version.rs
Labels: C-enhancement, A-cli

#6167 fix(tree): reset cached trie updates on prepend
  crates/storage/provider/src/chain.rs
Labels: C-bug, A-blockchain-tree

#6090 Validation on decoding NewPooledTransactions68
  crates/net/eth-wire/src/types/broadcast.rs
Labels: A-networking

#6174 chore(deps): clean up new crate deps
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/builder/mod.rs
  bin/reth/src/lib.rs
  bin/reth/src/runner.rs
  crates/node-core/Cargo.toml
  crates/node-core/src/cli/mod.rs
  crates/node-core/src/lib.rs
  crates/node-core/src/utils.rs
Labels: A-dependencies

#6126 feat(storage, mdbx): transaction manager
  Cargo.lock
  bin/reth/src/cli/db_type.rs
  bin/reth/src/commands/db/diff.rs
  bin/reth/src/commands/db/mod.rs
  bin/reth/src/commands/db/snapshots/headers.rs
  bin/reth/src/commands/db/snapshots/mod.rs
  bin/reth/src/commands/db/snapshots/receipts.rs
  bin/reth/src/commands/db/snapshots/transactions.rs
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/init_cmd.rs
  bin/reth/src/commands/p2p/mod.rs
  bin/reth/src/commands/recover/storage_tries.rs
  bin/reth/src/commands/stage/drop.rs
  bin/reth/src/commands/stage/dump/mod.rs
  bin/reth/src/commands/stage/run.rs
  bin/reth/src/commands/stage/unwind.rs
  crates/storage/db/Cargo.toml
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/lib.rs
  crates/storage/libmdbx-rs/Cargo.toml
  crates/storage/libmdbx-rs/src/codec.rs
  crates/storage/libmdbx-rs/src/cursor.rs
  crates/storage/libmdbx-rs/src/database.rs
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/libmdbx-rs/src/error.rs
  crates/storage/libmdbx-rs/src/lib.rs
  crates/storage/libmdbx-rs/src/transaction.rs
  crates/storage/libmdbx-rs/src/txn_manager.rs
  crates/storage/provider/src/providers/database/mod.rs
  examples/db-access.rs
  examples/rpc-db/src/main.rs
Labels: C-enhancement, A-db

#6178 feat(ext): provide direct access to database tx
  bin/reth/src/builder/mod.rs
  crates/node-core/src/cli/components.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/traits/database_provider.rs
  crates/storage/provider/src/traits/mod.rs
Labels: C-enhancement, A-cli

#6181 feat(storage): make it possible to disable read tx timeout
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/storage/db/src/abstraction/mock.rs
  crates/storage/db/src/abstraction/transaction.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/libmdbx-rs/src/transaction.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-enhancement, A-db

#6182 release: v0.1.0-alpha.16
  Cargo.lock
  Cargo.toml
Labels: A-meta

#6188 feat(ci): add image and title to GH release draft
  .github/workflows/release.yml
Labels: A-meta

#6189 chore: node-core cleanup
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  bin/reth/build.rs
  bin/reth/src/cli/mod.rs
  bin/reth/src/commands/debug_cmd/mod.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  bin/reth/src/commands/node/mod.rs
  bin/reth/src/lib.rs
  bin/reth/src/utils.rs
  crates/node-core/Cargo.toml
  crates/node-core/src/cl_events.rs
  crates/node-core/src/cli/db_type.rs
  crates/node-core/src/cli/mod.rs
  crates/node-core/src/engine_api_store.rs
  crates/node-core/src/events.rs
  crates/node-core/src/lib.rs
  crates/node-core/src/node_config.rs
  crates/node-core/src/prometheus_exporter.rs
  crates/node-core/src/utils.rs
Labels: C-enhancement, A-cli

#6191 fix: ensure tokio rt is always dropped on separate task
  bin/reth/src/runner.rs
Labels: C-bug, A-cli

#6194 chore: remove node-api dependency from payload builder impls
  Cargo.lock
  crates/payload/ethereum/Cargo.toml
  crates/payload/ethereum/src/lib.rs
  crates/payload/optimism/Cargo.toml
  crates/payload/optimism/src/lib.rs
Labels: C-debt, A-block-building

#6198 chore: rm unused build.rs vergen
  crates/storage/db/Cargo.toml
  crates/storage/db/build.rs
Labels: C-debt

#6199 fix: include jemalloc-ctl only in node-core
  Cargo.lock
  bin/reth/Cargo.toml
  crates/node-core/Cargo.toml
Labels: C-debt

#6200 fix: pass down optimism feature in node-core
  crates/node-core/Cargo.toml
Labels: C-bug

#6204 add `is_post_merge` implementation for `Hardfork`
  crates/ethereum-forks/src/hardfork.rs
Labels: C-enhancement

#6206 chore(deps): remove unused deps
  Cargo.lock
  crates/storage/db/Cargo.toml
  crates/storage/db/benches/README.md
Labels: C-debt, A-dependencies

#6184 feat: Implement fixed vec arbitrary manually for NewPooledTransactions68
  crates/net/eth-wire/src/types/broadcast.rs
Labels: C-test, A-networking

#6092 feat: Support transaction context in trace_transaction
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: A-rpc

#6210 Revert "feat: add `HeadersTD` static file segment"
  bin/reth/src/commands/db/snapshots/mod.rs
  crates/primitives/src/snapshot/mod.rs
  crates/primitives/src/snapshot/segment.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
Labels: C-enhancement, A-snapshots

#6212 fix: ci will now fail if a hive test fails
  .github/workflows/hive.yml
Labels: A-meta

#6197 chore: bump igd dep
  Cargo.lock
  Cargo.toml
  crates/net/nat/Cargo.toml
  crates/net/nat/src/lib.rs
  crates/rpc/rpc-types-compat/src/transaction/mod.rs
  deny.toml
Labels: C-enhancement, A-networking

#6201 Make limit on tx packet size soft in tx fetcher
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
Labels: A-networking

#6166 feat: NodeExit future core implementation
  bin/reth/src/commands/node/mod.rs
  crates/node-core/src/node_config.rs
Labels: C-enhancement

#6225 fix(libmdbx): build without `read-tx-timeouts` feature
  crates/storage/libmdbx-rs/src/txn_manager.rs
Labels: C-bug, A-db

#6224 feat(cli): local tx propagation toggle
  crates/node-core/src/args/txpool_args.rs
  crates/transaction-pool/src/config.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool, A-cli

#6131 feat(trie): historical & sidechain state root
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/chain.rs
  crates/blockchain-tree/src/config.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/blockchain_tree/mod.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/trie/src/hashed_cursor/post_state.rs
  crates/trie/src/state.rs
  crates/trie/src/trie.rs
Labels: C-enhancement, A-blockchain-tree, A-trie

#6213 feat(storage): `SnapshotProviderRW::append_header`
  crates/storage/provider/src/providers/snapshot/writer.rs
Labels: C-enhancement, A-snapshots

#6231 feat: move NodeBuilderWithDatabase to reth bin
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/builder.rs
  bin/reth/src/commands/debug_cmd/engine_api_store.rs
  bin/reth/src/commands/debug_cmd/mod.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  bin/reth/src/commands/node/cl_events.rs
  bin/reth/src/commands/node/events.rs
  bin/reth/src/commands/node/mod.rs
  bin/reth/src/init.rs
  bin/reth/src/lib.rs
  crates/node-core/Cargo.toml
  crates/node-core/src/lib.rs
  crates/node-core/src/node_config.rs
Labels: C-debt, A-cli

#6235 fix(book): op-reth specs links
  book/run/optimism.md
Labels: C-docs, A-op-reth

#6233 small refactoring for transaction field length
  crates/primitives/src/transaction/eip1559.rs
  crates/primitives/src/transaction/eip2930.rs
  crates/primitives/src/transaction/eip4844.rs
  crates/primitives/src/transaction/legacy.rs
  crates/primitives/src/transaction/optimism.rs
Labels: C-debt

#6239 fix(tree): disable state trie caching
  crates/blockchain-tree/src/chain.rs
Labels: A-blockchain-tree

#6226 Hashed post state cursor works on top of a trait instead of &Tx.
  crates/trie/src/hashed_cursor/post_state.rs
  crates/trie/src/state.rs
Labels: A-trie

#6122 feat(snapshot, prune): transactions
  bin/reth/src/commands/db/snapshots/mod.rs
  crates/consensus/beacon/src/engine/hooks/controller.rs
  crates/consensus/beacon/src/engine/hooks/snapshot.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/node-core/src/node_config.rs
  crates/primitives/src/prune/mode.rs
  crates/prune/src/builder.rs
  crates/prune/src/pruner.rs
  crates/prune/src/segments/set.rs
  crates/snapshot/src/lib.rs
  crates/snapshot/src/segments/headers.rs
  crates/snapshot/src/segments/mod.rs
  crates/snapshot/src/segments/receipts.rs
  crates/snapshot/src/segments/transactions.rs
  crates/snapshot/src/snapshotter.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/db/src/snapshot/mod.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
Labels: C-enhancement, A-pruning, A-snapshots

#5733 feat(snapshots): write to snapshots during `BodyStage`
  Cargo.lock
  bin/reth/src/commands/db/snapshots/headers.rs
  bin/reth/src/commands/db/snapshots/mod.rs
  bin/reth/src/commands/db/snapshots/receipts.rs
  bin/reth/src/commands/db/snapshots/transactions.rs
  crates/consensus/beacon/src/engine/hooks/controller.rs
  crates/consensus/beacon/src/engine/hooks/snapshot.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/interfaces/src/provider.rs
  crates/node-core/src/node_config.rs
  crates/primitives/src/prune/mode.rs
  crates/primitives/src/snapshot/mod.rs
  crates/primitives/src/snapshot/segment.rs
  crates/prune/src/builder.rs
  crates/prune/src/pruner.rs
  crates/prune/src/segments/set.rs
  crates/snapshot/src/lib.rs
  crates/snapshot/src/segments/headers.rs
  crates/snapshot/src/segments/mod.rs
  crates/snapshot/src/segments/receipts.rs
  crates/snapshot/src/segments/transactions.rs
  crates/snapshot/src/snapshotter.rs
  crates/stages/Cargo.toml
  crates/stages/src/error.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/test_utils/test_db.rs
  crates/storage/db/src/lib.rs
  crates/storage/db/src/snapshot/mod.rs
  crates/storage/nippy-jar/src/lib.rs
  crates/storage/nippy-jar/src/writer.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/snapshot/manager.rs
  crates/storage/provider/src/providers/snapshot/mod.rs
  crates/storage/provider/src/providers/snapshot/writer.rs
Labels: C-enhancement, A-snapshots

#6242 chore: use Display instead of Debug when printing internal errors
  bin/reth/src/commands/stage/unwind.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/rpc/rpc-builder/tests/it/startup.rs
  crates/rpc/rpc-testing-util/tests/it/trace.rs
  crates/rpc/rpc/src/layers/auth_layer.rs
  crates/rpc/rpc/src/layers/jwt_secret.rs
  crates/rpc/rpc/src/result.rs
Labels: C-debt, A-observability

#6245 chore: use Display when formatting addresses and hashes
  crates/ethereum-forks/src/head.rs
  crates/interfaces/src/blockchain_tree/error.rs
  crates/net/network/src/transactions/mod.rs
  crates/rpc/rpc/src/admin.rs
  crates/transaction-pool/src/blobstore/disk.rs
  crates/transaction-pool/src/validate/mod.rs
  examples/trace-transaction-cli/src/main.rs
  testing/ef-tests/src/models.rs
Labels: C-debt

#6154 feat: add ETL and use it on `HeaderStage`
  Cargo.lock
  Cargo.toml
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/import.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/etl/Cargo.toml
  crates/etl/src/lib.rs
  crates/node-core/src/node_config.rs
  crates/primitives/src/header.rs
  crates/stages/Cargo.toml
  crates/stages/benches/criterion.rs
  crates/stages/src/error.rs
  crates/stages/src/lib.rs
  crates/stages/src/sets.rs
  crates/stages/src/stages/headers.rs
  crates/stages/src/stages/mod.rs
  crates/stages/src/stages/total_difficulty.rs
  crates/storage/codecs/derive/src/compact/generator.rs
  crates/storage/codecs/derive/src/compact/mod.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/db/src/tables/raw.rs
Labels: A-staged-sync

#6246 docs: add some notes about tracing
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: C-docs

#6257 add `mainnet_activation_timestamp` for `Hardfork`
  crates/ethereum-forks/src/hardfork.rs
Labels: C-enhancement

#6256 get queued and pending transactions by sender in tx pool
  crates/transaction-pool/src/identifier.rs
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: A-tx-pool

#6261 Separate `activation_timestamp` and `mainnet_activation_timestamp` methods
  crates/ethereum-forks/src/hardfork.rs
Labels: C-enhancement

#6259 add `ConsensusType` enum for `Hardfork`
  crates/ethereum-forks/src/hardfork.rs
Labels: C-enhancement
