Repository paradigmxyz/reth, pull requests merged in 2024-10, with the labels that each got.

#11254 fix: never ban trusted peers
  crates/net/network-types/src/peers/config.rs
  crates/net/network/src/peers.rs
Labels: C-bug, A-networking

#11353 feat(exex): use rmp-serde for WAL storage
  Cargo.lock
  crates/exex/exex/Cargo.toml
  crates/exex/exex/src/wal/storage.rs
  crates/primitives-traits/src/header/mod.rs
  crates/primitives-traits/src/header/sealed.rs
  crates/primitives-traits/src/lib.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-enhancement, A-exex

#11364 chore: log num hash
  crates/node/builder/src/launch/engine.rs
Labels: A-observability

#11365 docs: misc in memory docs
  crates/chain-state/src/in_memory.rs
Labels: C-docs

#11373 fix(evm): propagate optimism and test features correctly
  crates/evm/execution-types/Cargo.toml
Labels: C-test

#11363 dev: block_with_senders on BlockState
  crates/chain-state/src/in_memory.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-enhancement

#11378 test(engine): improve deep reorg test
  crates/engine/tree/src/tree/mod.rs
Labels: A-consensus, C-test

#11375 feat: add ReputationChangeWeights::zero
  crates/net/network-types/src/peers/reputation.rs
Labels: C-enhancement, A-networking

#11381 perf(engine): avoid unnecessary arc clones on new head
  crates/engine/tree/src/tree/mod.rs
Labels: C-perf, A-consensus

#11369 feat(trie): deserialize trie updates with serde as hex
  crates/trie/trie/src/updates.rs
Labels: C-enhancement, A-trie

#11372 fix(exex): set next file ID when creating WAL storage
  crates/exex/exex/src/wal/cache.rs
  crates/exex/exex/src/wal/mod.rs
  crates/exex/exex/src/wal/storage.rs
Labels: C-bug, A-exex

#11377 chore: limit tracing logs to debug by default
  Makefile
Labels: C-perf, A-observability

#11388 chore(deps): bump some breaking deps
  Cargo.lock
  Cargo.toml
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  crates/cli/commands/Cargo.toml
  crates/cli/commands/src/db/tui.rs
  crates/cli/commands/src/p2p/mod.rs
  crates/consensus/common/Cargo.toml
  crates/node/metrics/Cargo.toml
  crates/optimism/bin/src/main.rs
  crates/storage/db/Cargo.toml
  crates/storage/db/src/lockfile.rs
  crates/storage/libmdbx-rs/mdbx-sys/Cargo.toml
Labels: A-dependencies

#11390 chore: Remove redundant impl NetworkManager
  crates/net/network/src/manager.rs
Labels: C-debt, A-networking

#11380 fix(provider): handle race on `fn transaction_id`
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-bug, A-blockchain-tree

#11361 chore(db): simplify Compact for Vec
  crates/storage/codecs/src/lib.rs
Labels: C-debt, A-db

#11391 fix: use pending state if available
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-bug, A-db

#11395 fix: add tracing features to op binary
  Cargo.lock
  crates/optimism/bin/Cargo.toml
  crates/optimism/bin/src/main.rs
Labels: A-op-reth

#11394 feat(primitives): bincode compatibility for EIP-7702 transaction
  Cargo.lock
  Cargo.toml
  crates/evm/execution-types/src/lib.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-enhancement, A-sdk

#11368 fix(engine): `is_fork` header traversal
  crates/engine/tree/src/tree/mod.rs
Labels: C-bug, A-consensus

#11393 chore(Makefile): separate features by spaces only
  Makefile
Labels: C-enhancement, A-cli, A-ci

#11398 chore: rename default chainspec parser
  bin/reth/src/cli/mod.rs
  bin/reth/src/main.rs
  crates/cli/commands/src/db/mod.rs
  crates/cli/commands/src/dump_genesis.rs
  crates/cli/commands/src/import.rs
  crates/cli/commands/src/node.rs
  crates/cli/commands/src/stage/unwind.rs
  crates/node/core/src/args/utils.rs
  examples/beacon-api-sidecar-fetcher/src/main.rs
  examples/beacon-api-sse/src/main.rs
  examples/custom-inspector/src/main.rs
  examples/node-custom-rpc/src/main.rs
  examples/txpool-tracing/src/main.rs
Labels: C-debt, A-sdk

#11401 ci: pin clippy to working version
  .github/workflows/lint.yml
Labels: C-debt

#11407 fix: fetch header by hash
  crates/engine/tree/src/tree/mod.rs
  crates/storage/storage-api/src/header.rs
Labels: C-bug

#11406 chore: add metric and trace for already executed blocks
  crates/engine/tree/src/tree/metrics.rs
  crates/engine/tree/src/tree/mod.rs
Labels: A-observability

#11408 chore: make clippy happy
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/storage/provider/src/writer/mod.rs
  crates/storage/storage-api/src/transactions.rs
Labels: C-debt

#11405 dev: swap_remove
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/payload/builder/src/service.rs
Labels: C-perf

#11413 fix(stages): call post execute/unwind commit hooks
  crates/stages/api/src/pipeline/mod.rs
  crates/stages/api/src/test_utils.rs
Labels: C-bug, A-staged-sync

#11410 fix(exex): check exex head against node head to determine canonical
  crates/exex/exex/src/notifications.rs
Labels: C-bug, A-exex

#11409 feat(trie): bincode compatibility for trie updates
  Cargo.lock
  crates/evm/execution-types/Cargo.toml
  crates/evm/execution-types/src/chain.rs
  crates/trie/trie/Cargo.toml
  crates/trie/trie/src/lib.rs
  crates/trie/trie/src/updates.rs
Labels: C-enhancement, A-trie

#11417 fix: apply 4788 system call in tracing
  crates/rpc/rpc-eth-api/src/helpers/trace.rs
Labels: C-bug, A-rpc

#11418 feat(stages): fail Execution if post execute commit input isn't consumed
  crates/stages/api/src/error.rs
  crates/stages/stages/src/stages/execution.rs
Labels: C-enhancement, A-staged-sync

#11383 feat(chain-state): notify about new safe/finalized only if modified
  crates/chain-state/src/chain_info.rs
Labels: C-enhancement

#11420 fix(exex): do not finalize WAL with a block higher than finalized header
  crates/exex/exex/src/manager.rs
Labels: C-bug, A-exex

#11411 chore(sdk): define traits for primitives `Block` and `BlockBody`
  crates/primitives/src/traits/block/body.rs
  crates/primitives/src/traits/block/mod.rs
  crates/primitives/src/traits/mod.rs
Labels: C-debt, A-sdk

#11431 feat(exex): WAL metrics
  crates/exex/exex/src/manager.rs
  crates/exex/exex/src/wal/cache.rs
  crates/exex/exex/src/wal/metrics.rs
  crates/exex/exex/src/wal/mod.rs
  crates/exex/exex/src/wal/storage.rs
Labels: C-enhancement, A-observability, A-exex

#11435 Fix: Reorder all serde_bincode_compat module definitions
  crates/evm/execution-types/src/chain.rs
  crates/primitives/src/block.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-debt

#11354 feat(exex): commit notifications to WAL before sending to ExExes
  crates/exex/exex/src/manager.rs
  crates/exex/exex/src/notifications.rs
  crates/exex/exex/src/wal/mod.rs
  crates/exex/exex/src/wal/storage.rs
Labels: C-enhancement, A-exex

#11150 fix: reset pruned sender numbers on stage drop
  crates/cli/commands/src/stage/drop.rs
Labels: C-bug, A-staged-sync, A-pruning

#11414 feat: add `get_in_memory_or_storage_by_tx_range`
  crates/chain-state/src/in_memory.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-enhancement, A-db

#11439 chore: make clippy happy
  crates/cli/commands/src/import.rs
  crates/cli/commands/src/recover/storage_tries.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/optimism/cli/src/commands/build_pipeline.rs
  crates/rpc/rpc-eth-types/src/logs_utils.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/stages/stages/src/stages/sender_recovery.rs
  crates/storage/db-common/src/init.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-debt

#11446 fix: env tempdir failure on WAL creation
  Cargo.lock
  crates/exex/test-utils/Cargo.toml
  crates/exex/test-utils/src/lib.rs
Labels: C-bug, C-test, A-exex

#11438 primitives: remove optimism re-export in `reth-primitives`
  Cargo.lock
  crates/optimism/evm/Cargo.toml
  crates/optimism/evm/src/execute.rs
  crates/optimism/evm/src/lib.rs
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/txpool.rs
  crates/optimism/node/tests/it/builder.rs
  crates/primitives/src/alloy_compat.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/receipt.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-debt

#11448 fix(exex): WAL size metric
  crates/exex/exex/src/wal/mod.rs
Labels: C-bug, A-observability, A-exex

#11442 chore: replace `Compact` with `bincode` on `ETL` usage of `SealedHeader`
  Cargo.lock
  crates/optimism/storage/src/lib.rs
  crates/primitives-traits/src/header/sealed.rs
  crates/stages/stages/Cargo.toml
  crates/stages/stages/src/stages/headers.rs
  crates/storage/db-api/src/models/mod.rs
Labels: C-enhancement, A-staged-sync

#11450 fix(exex): limit the duration of a backfill job to 30 seconds
  crates/exex/exex/src/backfill/factory.rs
Labels: C-bug, C-enhancement, A-exex

#11455 chore(provider): find `last_database_block_number` with `BlockState` anchor instead
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-debt

#11456 feat: add metrics for failed deliveries
  crates/engine/tree/src/tree/metrics.rs
  crates/engine/tree/src/tree/mod.rs
Labels: A-observability

#11457 chore: release 1.0.8
  Cargo.lock
  Cargo.toml
Labels: A-meta

#11458 chore(provider): use `block_ref` instead on `BlockState`
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-debt

#11443 feat(rpc): Add codes in execution witness return
  crates/rpc/rpc/src/debug.rs
Labels: C-enhancement, A-rpc

#11461 feat(grafana): ExEx WAL
  etc/grafana/dashboards/overview.json
Labels: C-enhancement, A-observability

#11463 fix: use correct rpc errors
  crates/rpc/rpc-eth-types/src/error.rs
Labels: C-bug, A-rpc

#11459 chore(provider): clone after filtering on `sealed_headers_while`
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-debt

#11090 Map `TransferKind::EofCreate` => `OperationType::OpEofCreate`
  crates/rpc/rpc/src/otterscan.rs
Labels: S-blocked, A-rpc

#11465 fix: windows build
  crates/fs-util/src/lib.rs
Labels: C-debt

#11467 chore: use `block_ref` on `CanonicalInMemoryState`
  crates/chain-state/src/in_memory.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-debt

#11466 chore(rpc): remove include_preimage param on debug_execution_witness
  crates/engine/invalid-block-hooks/src/witness.rs
  crates/rpc/rpc-api/src/debug.rs
  crates/rpc/rpc/src/debug.rs
Labels: A-rpc

#11472 test: add unit tests for `CanonicalChain`
  crates/blockchain-tree/src/canonical_chain.rs
Labels: C-test

#11469 feat: cleaned up prepare_call_env()
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-debt, A-rpc

#11474 chore: use block.body directly
  crates/exex/exex/src/backfill/job.rs
Labels: C-debt

#11403 feat: Add metrics to track transactions by type in txpool
  crates/transaction-pool/src/metrics.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: A-tx-pool

#11476 chore(exex): more backfill debug logs
  crates/exex/exex/src/backfill/job.rs
  crates/exex/exex/src/backfill/stream.rs
Labels: C-enhancement, A-observability, A-exex

#11478 fix(exex): use thresholds in stream backfill
  crates/exex/exex/src/backfill/stream.rs
Labels: C-bug, A-exex

#11477 chore(db): capture tx opening backtrace in debug mode
  crates/storage/db/src/implementation/mdbx/tx.rs
Labels: C-enhancement, A-db, A-observability

#11429 chore(sdk): `SealedHeader` generic over header
  crates/primitives-traits/src/header/sealed.rs
Labels: C-debt, A-sdk

#11487 chore(lint): fix lint primitives
  crates/primitives-traits/src/header/sealed.rs
  crates/primitives/src/block.rs
  crates/primitives/src/receipt.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-debt

#11486 test: ensure default hash matches
  crates/primitives/src/block.rs
Labels: C-test

#11479 chore: rm deposit contract config for op
  crates/optimism/chainspec/src/constants.rs
  crates/optimism/chainspec/src/lib.rs
Labels: A-op-reth

#11485 chore(lint): fix lint storage
  crates/etl/src/lib.rs
  crates/storage/db-api/src/cursor.rs
  crates/storage/db/src/static_file/cursor.rs
  crates/storage/libmdbx-rs/src/codec.rs
  crates/storage/libmdbx-rs/src/cursor.rs
  crates/storage/nippy-jar/src/compression/zstd.rs
  crates/storage/nippy-jar/src/cursor.rs
  crates/trie/trie/src/forward_cursor.rs
  crates/trie/trie/src/hashed_cursor/post_state.rs
  crates/trie/trie/src/trie_cursor/in_memory.rs
  crates/trie/trie/src/updates.rs
Labels: C-debt

#11503 fix(rpc-eth-types): incorrect error msg(; -> :)
  crates/rpc/rpc-eth-types/src/error.rs
Labels: A-rpc

#11501 feat: rpc replace function created
  crates/rpc/rpc-builder/src/lib.rs
Labels: A-rpc

#11496 chore(lint): fix `clippy::needles_lifetimes`
  crates/blockchain-tree/src/bundle.rs
  crates/ethereum/engine-primitives/src/payload.rs
  crates/evm/execution-types/src/chain.rs
  crates/evm/src/system_calls/mod.rs
  crates/exex/types/src/notification.rs
  crates/net/network/src/peers.rs
  crates/node/builder/src/rpc.rs
  crates/optimism/payload/src/payload.rs
  crates/payload/builder/src/database.rs
  crates/prune/prune/src/segments/static_file/headers.rs
  crates/rpc/rpc-eth-types/src/cache/db.rs
  crates/rpc/rpc-layer/src/auth_layer.rs
  crates/rpc/rpc-testing-util/src/debug.rs
  crates/rpc/rpc-testing-util/src/trace.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/static_file/jar.rs
  crates/storage/provider/src/providers/static_file/writer.rs
  crates/storage/provider/src/writer/database.rs
  crates/storage/provider/src/writer/mod.rs
  crates/storage/provider/src/writer/static_file.rs
  crates/transaction-pool/src/traits.rs
  crates/trie/db/src/hashed_cursor.rs
  crates/trie/db/src/prefix_set.rs
  crates/trie/db/src/trie_cursor.rs
  crates/trie/trie/src/trie_cursor/in_memory.rs
Labels: C-debt

#11509 chore: rm from genesis impl
  crates/net/eth-wire-types/Cargo.toml
  crates/net/eth-wire-types/src/status.rs
Labels: C-debt, A-networking

#11505 fix: cap gas limit properly
  crates/rpc/rpc-eth-api/src/helpers/call.rs
Labels: C-bug

#11506 feat: expose Op node network_config helper
  crates/net/network/src/config.rs
  crates/optimism/node/src/node.rs
Labels: C-enhancement, A-op-reth

#11517 test: add unit tests for `PruneLimiter`
  crates/prune/types/src/limiter.rs
Labels: C-test

#11265 fix(tree): make state methods work for historical blocks
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/storage-api/src/storage.rs
Labels: C-bug, A-consensus

#11528 chore: delete rpc-types
  docs/repo/layout.md
Labels: C-docs

#11514 feat: add get_highest_tx_by_sender to pools
  crates/rpc/rpc-eth-api/src/helpers/state.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/traits.rs
Labels: A-rpc, A-tx-pool

#11537 fix: acquire permit first
  crates/rpc/rpc-eth-api/src/helpers/state.rs
Labels: A-rpc

#11539 chore: dont fail on ttd
  crates/rpc/rpc-eth-api/src/helpers/block.rs
Labels: A-rpc

#11500 feat(exex): subscribe to notifications with head using `ExExContext`
  crates/exex/exex/src/context.rs
  crates/exex/exex/src/manager.rs
  crates/exex/exex/src/notifications.rs
Labels: C-enhancement, A-exex

#11540 chore: enforce window
  crates/rpc/rpc-eth-api/src/helpers/state.rs
  crates/rpc/rpc/src/eth/helpers/state.rs
Labels: A-rpc

#11511 Refactor get_payload_bodies_by_hash_with to be non-blocking
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-perf, A-rpc

#11519 Introduce Eth PayloadTypes Impl
  crates/ethereum/engine-primitives/src/lib.rs
  crates/node/types/src/lib.rs
Labels: C-enhancement

#11543 fix(op-reth): add jemalloc feature to optimism-cli for version
  Cargo.lock
  crates/optimism/bin/Cargo.toml
  crates/optimism/cli/Cargo.toml
  crates/optimism/cli/src/lib.rs
Labels: C-bug, A-observability, A-op-reth

#11542 fix(grafana): remove rate function from panel "Transactions by Type in Pool"
  etc/grafana/dashboards/reth-mempool.json
Labels: A-observability

#11552 chore: move ethfiltererror
  crates/rpc/rpc-eth-types/src/lib.rs
  crates/rpc/rpc-eth-types/src/logs_utils.rs
  crates/rpc/rpc/src/eth/filter.rs
Labels: C-debt, A-rpc

#11557 chore: rm redundant type hint
  crates/rpc/rpc/src/eth/helpers/signer.rs
Labels: C-debt

#11538 chore: chain manual serialisation implementation
  crates/evm/execution-types/src/chain.rs
Labels: C-perf, A-sdk, A-exex

#11559 chore: rm unused optimism feature
  crates/node/core/Cargo.toml
  crates/optimism/rpc/Cargo.toml
  crates/rpc/rpc-eth-api/Cargo.toml
  crates/rpc/rpc/Cargo.toml
Labels: A-op-reth

#11550 feat(trie): expose storage proofs
  crates/chain-state/src/in_memory.rs
  crates/chain-state/src/memory_overlay.rs
  crates/revm/src/test_utils.rs
  crates/rpc/rpc-eth-types/src/cache/db.rs
  crates/storage/provider/src/providers/bundle_state_provider.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/macros.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/storage-api/src/trie.rs
  crates/trie/db/src/lib.rs
  crates/trie/db/src/proof.rs
  crates/trie/trie/src/proof.rs
  crates/trie/trie/src/witness.rs
Labels: C-enhancement, A-trie

#11560 chore: rm unused optimism feature from compat
  crates/node/core/Cargo.toml
  crates/optimism/node/Cargo.toml
  crates/optimism/payload/Cargo.toml
  crates/rpc/rpc-types-compat/Cargo.toml
  crates/rpc/rpc/Cargo.toml
Labels: A-op-reth

#11525 Added InternalBlockExecutionError to execute.rs exports
  crates/evm/src/execute.rs
Labels: A-execution

#11545 docs(exex): include code for ExEx book from real files
  .github/workflows/lint.yml
  .github/workflows/unit.yml
  .gitignore
  Cargo.toml
  book/developers/exex/hello-world.md
  book/sources/Cargo.toml
  book/sources/exex/hello-world/Cargo.toml
  book/sources/exex/hello-world/src/bin/1.rs
  book/sources/exex/hello-world/src/bin/2.rs
  book/sources/exex/hello-world/src/bin/3.rs
Labels: C-docs, A-exex, A-ci

#11565 fix: actually configure the custom gas limit
  crates/rpc/rpc-eth-api/src/helpers/call.rs
Labels: C-bug, A-rpc

#11571 chore: relax trait bound for `EthTransactions`
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
Labels: C-debt

#11569 feat: adding a new method to network config builder
  crates/exex/test-utils/src/lib.rs
  crates/net/network/src/config.rs
Labels: C-enhancement, C-test, A-networking

#11562 chore: rm bad cap function
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-types/src/revm_utils.rs
Labels: A-rpc

#11482 feat: impl `Encodable2718` and `Decodable2718` for `PooledTransactionsElement`
  Cargo.lock
  bin/reth/src/commands/debug_cmd/build_block.rs
  crates/net/eth-wire/Cargo.toml
  crates/net/eth-wire/tests/pooled_transactions.rs
  crates/primitives/src/transaction/pooled.rs
  crates/primitives/src/transaction/sidecar.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-types/src/utils.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: C-enhancement, A-sdk

#11578 fix(exex): exhaust backfill job when using a stream
  Cargo.lock
  crates/exex/exex/src/backfill/job.rs
  crates/exex/exex/src/backfill/stream.rs
  crates/exex/exex/src/notifications.rs
Labels: C-bug, A-exex

#11586 chore: bump alloy primitives 0 8 7
  Cargo.lock
  Cargo.toml
  crates/primitives-traits/src/withdrawal.rs
Labels: C-bug, A-rpc, A-dependencies

#11589 chore(ci): remove expected failures related to checksummed addresses
  .github/assets/hive/expected_failures.yaml
  .github/assets/hive/expected_failures_experimental.yaml
Labels: C-test

#11587 chore(rpc): use `block_hash` instead on fetching `debug_trace_block` block
  crates/rpc/rpc/src/debug.rs
Labels: A-rpc

#11588 chore: also derive arb for test
  crates/primitives-traits/src/storage.rs
Labels: C-test

#11591 feat: add mul support for SubPoolLimit
  crates/transaction-pool/src/config.rs
Labels: C-enhancement, A-tx-pool

#11592 fix: simplify reorg handling
  crates/engine/tree/src/tree/mod.rs
Labels: C-bug

#11593 fix: use original bytes for codes
  crates/rpc/rpc/src/debug.rs
Labels: C-bug, A-rpc

#11585 perf(rpc): use `Arc<BlockWithSenders` on `full_block_cache`
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-types/src/cache/mod.rs
Labels: C-enhancement, C-perf, A-rpc

#11598 fix: active inflight count
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
Labels: C-bug, A-networking

#11603 fix: set deposit gasprice correctly
  crates/optimism/rpc/src/eth/transaction.rs
Labels: C-bug, A-rpc, A-op-reth

#11601 fix: set system tx correctly
  crates/optimism/rpc/src/eth/transaction.rs
Labels: C-bug, A-op-reth

#11605 fix(trie): prefix set extension
  crates/trie/trie/src/prefix_set.rs
  crates/trie/trie/src/proof.rs
Labels: C-bug, A-trie

#11594 feat: add tx propagation mode
  crates/net/network/src/transactions/config.rs
  crates/net/network/src/transactions/mod.rs
  crates/node/core/src/args/network.rs
Labels: C-enhancement, A-networking

#11604 fix(net): construct `TransactionFetcher` with non-default bounds on maps
  crates/net/network/src/transactions/fetcher.rs
Labels: C-bug, A-networking

#11608 feat: add helper function to provde the tx manager config
  crates/node/builder/src/builder/mod.rs
Labels: C-enhancement

#11607 fix(grafana): set instance variable from `reth_info` metric
  etc/grafana/dashboards/reth-performance.json
Labels: A-observability

#11600 fix(net): add concurrency param from config to `TransactionFetcherInfo`
  crates/net/network/src/transactions/fetcher.rs
Labels: C-bug, C-enhancement, A-networking

#11595 chore(rpc): use `block_hash` as `BlockId` on `eth_callMany`
  crates/rpc/rpc-eth-api/src/helpers/call.rs
Labels: C-bug, A-rpc

#11596 fix(witness): destroyed slots as proof targets
  crates/trie/db/tests/witness.rs
  crates/trie/trie/src/witness.rs
Labels: C-bug, A-trie

#11617 chore: bump op-alloy
  Cargo.lock
  Cargo.toml
  crates/e2e-test-utils/src/traits.rs
  crates/optimism/chainspec/src/lib.rs
  crates/optimism/node/src/engine.rs
  crates/optimism/payload/src/lib.rs
  crates/optimism/payload/src/payload.rs
  crates/optimism/rpc/src/eth/receipt.rs
  crates/payload/primitives/src/traits.rs
  crates/primitives/src/alloy_compat.rs
Labels: A-op-reth

#11620 test: add sanity test for local txs args
  crates/node/core/src/args/txpool.rs
Labels: C-test

#11623 fix: persist finalized block
  crates/engine/tree/src/persistence.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-bug, A-op-reth

#11621 chore(metrics): remove redundant `starting metrics` log
  crates/node/metrics/src/server.rs
Labels: C-enhancement, A-observability

#11625 chore(ci): disable hive discord alerts
  .github/workflows/hive.yml
Labels: A-meta

#11613 feat(evm, trie): more metrics
  crates/engine/tree/src/tree/metrics.rs
  crates/engine/tree/src/tree/mod.rs
  crates/ethereum/evm/src/execute.rs
  crates/evm/src/either.rs
  crates/evm/src/execute.rs
  crates/evm/src/metrics.rs
  crates/evm/src/noop.rs
  crates/evm/src/test_utils.rs
  crates/optimism/evm/src/execute.rs
  crates/rpc/rpc/src/debug.rs
  crates/stages/stages/src/stages/execution.rs
Labels: C-enhancement, A-execution, A-observability, A-trie

#11629 fix: always handle payload building for opstack
  crates/chainspec/src/api.rs
  crates/engine/service/Cargo.toml
  crates/engine/service/src/service.rs
  crates/engine/tree/src/engine.rs
  crates/engine/tree/src/tree/mod.rs
  crates/optimism/chainspec/src/lib.rs
Labels: A-op-reth

#11628 chore(trie): make initialization of in-memory trie cursors `pub`
  crates/trie/trie/src/trie_cursor/in_memory.rs
Labels: C-debt, A-trie

#11627 feat(trie): noop hashed cursors
  crates/trie/trie/src/hashed_cursor/mod.rs
  crates/trie/trie/src/hashed_cursor/noop.rs
Labels: C-enhancement, A-trie

#11634 docs: clarify op-mainnet --debug.tip
  book/run/sync-op-mainnet.md
Labels: C-docs

#11615 feat(ci): add Kurtosis workflow
  .github/assets/kurtosis_network_params.yaml
  .github/workflows/kurtosis.yml
Labels: A-ci

#11638 feat(exex): commit only notifications with unfinalized blocks to WAL
  crates/exex/exex/src/manager.rs
  crates/node/builder/src/launch/exex.rs
  crates/stages/stages/src/stages/execution.rs
Labels: C-enhancement, A-exex

#11618 feat(ci): move book clippy and tests to matrix
  .github/workflows/lint.yml
  .github/workflows/unit.yml
Labels: C-enhancement, A-ci

#11612 feat(bin): make experimental engine default
  bin/reth/src/main.rs
  book/cli/reth/node.md
Labels: C-enhancement, A-cli

#11646 fix: don't unwrap missing requests
  crates/storage/codecs/src/alloy/header.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-bug

#11648 feat: store safe block num as well
  crates/blockchain-tree/src/externals.rs
  crates/chain-state/src/chain_info.rs
  crates/chain-state/src/in_memory.rs
  crates/cli/commands/src/stage/unwind.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/engine/tree/src/persistence.rs
  crates/engine/tree/src/tree/mod.rs
  crates/stages/api/src/pipeline/mod.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/traits/finalized_block.rs
  crates/storage/provider/src/traits/mod.rs
Labels: C-enhancement, A-op-reth

#11652 docs: `LoadFee::eip1559_fees` returns base fee, not max fee per gas
  crates/rpc/rpc-eth-api/src/helpers/fee.rs
Labels: C-docs

#11654 feat: propagate helper
  crates/net/network/src/transactions/mod.rs
Labels: A-networking

#11659 chore(net): log p2p stream flush error
  crates/net/eth-wire/src/p2pstream.rs
Labels: A-observability, A-networking

#11666 clippy: add `from_iter_instead_of_collect` warn
  Cargo.toml
  crates/evm/execution-types/src/chain.rs
  crates/rpc/rpc-builder/src/metrics.rs
  crates/rpc/rpc/src/debug.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/transaction-pool/benches/reorder.rs
  crates/transaction-pool/src/maintain.rs
  crates/trie/db/src/state.rs
  crates/trie/db/tests/post_state.rs
  crates/trie/trie/src/proof.rs
  crates/trie/trie/src/updates.rs
Labels: A-meta

#11664 tx-pool: simplify `FinalizedBlockTracker` update logic
  crates/transaction-pool/src/maintain.rs
Labels: A-tx-pool

#11642 test: add unit tests for `ChainInfoTracker`
  Cargo.lock
  crates/chain-state/Cargo.toml
  crates/chain-state/src/chain_info.rs
Labels: C-test

#11670 chore(examples): fix db-access example with RO provider
  examples/db-access/src/main.rs
Labels: C-debt

#11675 fix: always poll new pool imports
  crates/net/network/src/transactions/mod.rs
Labels: A-tx-pool

#11636 fix(net): decrease budget for header reqs to process before yielding thread
  crates/net/network/src/budget.rs
Labels: C-bug, C-perf, A-networking

#11683 fix: dont remove txs manually
  crates/consensus/auto-seal/src/task.rs
Labels: C-bug, A-rpc, A-tx-pool

#11680 fix: only +1 on the pool nonce
  crates/rpc/rpc-eth-api/src/helpers/state.rs
Labels: C-bug, A-rpc

#11663 test: more unit tests for `HashedPostState`
  crates/trie/trie/src/state.rs
Labels: C-test

#11685 docs: complete sentence
  crates/net/network/src/transactions/config.rs
Labels: C-docs
