Repository paradigmxyz/reth, pull requests merged in 2024-12, with the labels that each got.

#12930 feat: bump alloy
  Cargo.lock
  Cargo.toml
  bin/reth/src/commands/debug_cmd/build_block.rs
  crates/chain-state/src/in_memory.rs
  crates/consensus/common/src/validation.rs
  crates/engine/local/src/payload.rs
  crates/engine/util/Cargo.toml
  crates/engine/util/src/reorg.rs
  crates/ethereum/engine-primitives/src/payload.rs
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/node/tests/e2e/rpc.rs
  crates/ethereum/node/tests/e2e/utils.rs
  crates/ethereum/payload/src/lib.rs
  crates/evm/execution-types/src/execution_outcome.rs
  crates/evm/src/system_calls/mod.rs
  crates/net/eth-wire-types/src/blocks.rs
  crates/net/eth-wire-types/src/header.rs
  crates/optimism/evm/Cargo.toml
  crates/optimism/node/src/engine.rs
  crates/optimism/node/src/utils.rs
  crates/optimism/payload/src/builder.rs
  crates/optimism/payload/src/payload.rs
  crates/optimism/primitives/src/bedrock.rs
  crates/optimism/primitives/src/transaction/mod.rs
  crates/primitives-traits/src/receipt.rs
  crates/primitives/src/alloy_compat.rs
  crates/primitives/src/receipt.rs
  crates/primitives/src/traits.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/revm/src/batch.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-types/src/receipt.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/bundle.rs
  crates/rpc/rpc/src/validation.rs
  crates/storage/codecs/src/alloy/header.rs
  testing/ef-tests/src/models.rs
Labels: A-dependencies, E-prague

#13046 feat: add `Header` AT to `EthChainSpec`
  crates/chainspec/src/api.rs
  crates/cli/commands/src/common.rs
  crates/cli/commands/src/stage/drop.rs
  crates/exex/exex/src/dyn_context.rs
  crates/node/types/src/lib.rs
  crates/optimism/chainspec/src/lib.rs
  crates/storage/db-common/src/init.rs
Labels: A-sdk

#13033 feat: introduce EthMessage variant to NetworkHandleMessage
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
Labels: C-enhancement, A-networking

#12959 perf(trie): storage multiproof overallocation
  crates/trie/parallel/src/proof.rs
  crates/trie/trie/src/proof.rs
Labels: C-perf, A-trie

#13027 feat(trie): blinded node provider
  crates/trie/sparse/src/blinded.rs
  crates/trie/sparse/src/errors.rs
  crates/trie/sparse/src/lib.rs
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
Labels: C-enhancement, A-trie

#13053 chore: mark ethereum-forks as rv32imac
  .github/assets/check_rv32imac.sh
Labels: A-dependencies

#13056 docs(trie): duplicate comment in sparse trie
  crates/trie/sparse/src/trie.rs
Labels: C-docs, A-trie

#12790 feat(rpc): enhance `eth_getLogs` error handling with block range feedback
  crates/rpc/rpc/src/eth/filter.rs
Labels: A-rpc

#13057 chore(trie): remove infallible variant
  crates/trie/sparse/src/blinded.rs
  crates/trie/sparse/src/errors.rs
Labels: C-debt, A-trie

#13054 chore: disable reth-ethereum-forks default features in workspace
  Cargo.lock
  Cargo.toml
  crates/chainspec/Cargo.toml
  crates/ethereum/evm/Cargo.toml
  crates/evm/Cargo.toml
  crates/net/discv4/Cargo.toml
  crates/net/dns/Cargo.toml
  crates/net/eth-wire-types/Cargo.toml
  crates/net/eth-wire-types/src/status.rs
  crates/net/eth-wire/Cargo.toml
  crates/net/network-api/Cargo.toml
  crates/net/network-types/Cargo.toml
  crates/net/network/Cargo.toml
  crates/optimism/evm/Cargo.toml
  crates/optimism/hardforks/Cargo.toml
  crates/primitives/Cargo.toml
  crates/revm/Cargo.toml
Labels: A-dependencies

#13058 trie: init storage blinded provider with account
  crates/trie/sparse/src/blinded.rs
  crates/trie/sparse/src/state.rs
Labels: A-trie

#12715 chore: remove OpTxType new type
  Cargo.lock
  crates/optimism/primitives/Cargo.toml
  crates/optimism/primitives/src/transaction/tx_type.rs
  crates/primitives-traits/Cargo.toml
  crates/primitives-traits/src/size.rs
  crates/primitives-traits/src/transaction/tx_type.rs
  crates/storage/codecs/src/alloy/transaction/optimism.rs
Labels: A-op-reth

#13009 chore: add `OpEthApiBuilder` and `OpEthApiInner`
  Cargo.lock
  crates/optimism/bin/src/main.rs
  crates/optimism/node/src/node.rs
  crates/optimism/node/tests/it/builder.rs
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/eth/block.rs
  crates/optimism/rpc/src/eth/call.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/eth/pending_block.rs
  crates/optimism/rpc/src/eth/receipt.rs
  crates/optimism/rpc/src/eth/transaction.rs
Labels: A-rpc, A-op-reth

#13062 chore: move Integerlist to db-api
  Cargo.lock
  crates/net/ecies/Cargo.toml
  crates/primitives-traits/Cargo.toml
  crates/primitives-traits/src/integer_list.rs
  crates/primitives-traits/src/lib.rs
  crates/storage/db-api/Cargo.toml
  crates/storage/db-api/src/models/integer_list.rs
  crates/storage/db-api/src/models/mod.rs
  crates/storage/db-common/src/init.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/tables/codecs/fuzz/inputs.rs
  crates/storage/db/src/tables/codecs/fuzz/mod.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/libmdbx-rs/Cargo.toml
Labels: A-dependencies

#13065 chore: disable more default features
  .github/assets/check_rv32imac.sh
  Cargo.toml
  crates/chainspec/Cargo.toml
  crates/consensus/consensus/Cargo.toml
  crates/evm/execution-errors/Cargo.toml
  crates/net/p2p/Cargo.toml
  crates/optimism/chainspec/Cargo.toml
  crates/optimism/evm/Cargo.toml
  crates/optimism/primitives/Cargo.toml
  crates/primitives-traits/Cargo.toml
  crates/primitives/Cargo.toml
  crates/storage/errors/Cargo.toml
Labels: A-dependencies

#13059 add replace and remove methods
  crates/rpc/rpc-builder/src/auth.rs
Labels: C-enhancement

#13070 feat: bump alloy
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc/src/eth/bundle.rs
Labels: A-dependencies

#13067 chore: rename codecs optimism feature to op
  crates/consensus/beacon/Cargo.toml
  crates/optimism/primitives/Cargo.toml
  crates/optimism/storage/Cargo.toml
  crates/primitives/Cargo.toml
  crates/storage/codecs/Cargo.toml
  crates/storage/codecs/src/alloy/transaction/mod.rs
  crates/storage/db-api/Cargo.toml
  crates/storage/provider/Cargo.toml
Labels: C-enhancement, A-db, A-dependencies, A-op-reth

#13075 chore: add tx trait bounds to primitives
  crates/primitives-traits/src/node.rs
Labels: A-sdk

#13073 chore: disable default features op forks
  .github/assets/check_rv32imac.sh
  Cargo.toml
  crates/optimism/evm/Cargo.toml
  crates/optimism/hardforks/src/dev.rs
  crates/optimism/hardforks/src/lib.rs
Labels: A-dependencies

#13079 chore: misc direct imports
  crates/evm/execution-types/src/execution_outcome.rs
Labels: A-dependencies

#13078 feat: add std feature to network-peers
  .github/assets/check_wasm.sh
  crates/chainspec/Cargo.toml
  crates/net/p2p/Cargo.toml
  crates/net/peers/Cargo.toml
  crates/net/peers/src/bootnodes/mod.rs
  crates/net/peers/src/lib.rs
  crates/net/peers/src/node_record.rs
  crates/net/peers/src/trusted_peer.rs
  crates/optimism/chainspec/Cargo.toml
Labels: A-dependencies

#13068 feat(trie): `SparseStateTrie::new`
  crates/trie/sparse/src/state.rs
Labels: C-enhancement, A-trie

#13081 chore: disable nybbles default feature
  Cargo.toml
  crates/evm/execution-errors/Cargo.toml
Labels: A-dependencies

#13082 chore: flatten reth-primitives dep
  Cargo.lock
  crates/storage/errors/Cargo.toml
  crates/storage/errors/src/provider.rs
  crates/storage/errors/src/writer.rs
Labels: A-dependencies

#11433 chore(sdk): define `OpTransactionSigned`
  Cargo.lock
  crates/optimism/bin/Cargo.toml
  crates/optimism/cli/Cargo.toml
  crates/optimism/evm/Cargo.toml
  crates/optimism/node/Cargo.toml
  crates/optimism/primitives/Cargo.toml
  crates/optimism/primitives/src/lib.rs
  crates/optimism/primitives/src/transaction/mod.rs
  crates/optimism/primitives/src/transaction/signed.rs
  crates/optimism/rpc/Cargo.toml
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/util.rs
  crates/storage/provider/Cargo.toml
Labels: C-debt, A-op-reth, A-sdk

#13085 feat(trie): proof blinded providers
  Cargo.lock
  crates/trie/sparse/src/blinded.rs
  crates/trie/sparse/src/errors.rs
  crates/trie/trie/Cargo.toml
  crates/trie/trie/src/proof/blinded.rs
  crates/trie/trie/src/proof/mod.rs
Labels: C-enhancement, A-trie

#13087 feat: Use `PrimitiveSignature` instead of `Signature`
  crates/net/network/src/transactions/validation.rs
Labels: C-enhancement

#13029 feat: impl more noop functions
  crates/net/network/src/config.rs
  crates/storage/storage-api/src/noop.rs
Labels: C-enhancement, C-test, A-sdk

#13095 feat: add Op DA config
  crates/optimism/payload/src/config.rs
  crates/optimism/payload/src/lib.rs
Labels: A-op-reth

#13097 chore(evm): migrate execution errors back to `thiserror`
  Cargo.lock
  crates/evm/execution-errors/Cargo.toml
  crates/evm/execution-errors/src/lib.rs
  crates/evm/execution-errors/src/trie.rs
Labels: A-execution

#13099 feat: add miner rpc bindings
  crates/rpc/rpc-api/src/lib.rs
  crates/rpc/rpc-api/src/miner.rs
Labels: C-enhancement, A-rpc

#13061 perf(engine): do not clone proof targets
  crates/engine/tree/src/tree/root.rs
Labels: C-bug, A-trie

#12988 fix(trie): short circuit leaf removal if missing
  crates/trie/sparse/src/trie.rs
Labels: C-bug, A-trie

#13071 fix(trie): do not persist root branch nodes in sparse trie
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
Labels: C-bug, A-trie

#13102 feat: impl noop miner api endpoint
  book/cli/reth/node.md
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-server-types/src/module.rs
  crates/rpc/rpc/src/lib.rs
  crates/rpc/rpc/src/miner.rs
Labels: C-enhancement, A-rpc

#13101 chore: move sparse errors to `reth-execution-errors`
  Cargo.lock
  crates/engine/tree/src/tree/root.rs
  crates/evm/execution-errors/src/trie.rs
  crates/trie/sparse/Cargo.toml
  crates/trie/sparse/src/blinded.rs
  crates/trie/sparse/src/errors.rs
  crates/trie/sparse/src/lib.rs
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
  crates/trie/trie/src/proof/blinded.rs
Labels: A-trie

#13096 perf(validate-tx-pool): fast non-allocating `is_local`
  crates/primitives/src/transaction/mod.rs
  crates/transaction-pool/src/config.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/mod.rs
Labels: C-perf, A-tx-pool

#13105 feat: make InvalidBlockHook generic over NodePrimitives
  Cargo.lock
  crates/engine/invalid-block-hooks/src/witness.rs
  crates/engine/local/src/service.rs
  crates/engine/primitives/src/invalid_block_hook.rs
  crates/engine/service/src/service.rs
  crates/engine/tree/src/tree/invalid_block_hook.rs
  crates/engine/tree/src/tree/mod.rs
  crates/ethereum/evm/src/execute.rs
  crates/evm/src/state_change.rs
  crates/evm/src/system_calls/eip2935.rs
  crates/evm/src/system_calls/eip4788.rs
  crates/evm/src/system_calls/eip7002.rs
  crates/evm/src/system_calls/eip7251.rs
  crates/evm/src/system_calls/mod.rs
  crates/node/api/Cargo.toml
  crates/node/api/src/node.rs
  crates/node/builder/src/components/builder.rs
  crates/node/builder/src/components/execute.rs
  crates/node/builder/src/components/mod.rs
  crates/node/builder/src/launch/common.rs
  crates/optimism/evm/src/execute.rs
Labels: C-enhancement, A-sdk

#13084 chore: propagate network primitives to `on_command`, `on_network_event`
  crates/net/network/src/transactions/mod.rs
Labels: C-enhancement, A-tx-pool, A-sdk

#13106 feat: Add `Transaction` AT to `ConfigureEvm`
  Cargo.lock
  crates/engine/invalid-block-hooks/src/witness.rs
  crates/engine/util/src/reorg.rs
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/evm/src/lib.rs
  crates/ethereum/node/Cargo.toml
  crates/ethereum/node/src/node.rs
  crates/ethereum/payload/src/lib.rs
  crates/evm/src/lib.rs
  crates/node/api/src/node.rs
  crates/node/builder/src/components/builder.rs
  crates/node/builder/src/components/execute.rs
  crates/node/builder/src/components/mod.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/evm/src/lib.rs
  crates/optimism/node/src/node.rs
  crates/optimism/payload/src/builder.rs
  crates/optimism/rpc/src/eth/pending_block.rs
  crates/optimism/rpc/src/witness.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-eth-api/Cargo.toml
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/rpc/rpc/src/eth/helpers/pending_block.rs
  examples/custom-evm/src/main.rs
  examples/stateful-precompile/src/main.rs
Labels: C-enhancement, A-sdk

#13113 chore: remove redundant enum
  crates/rpc/rpc-engine-api/src/lib.rs
  crates/rpc/rpc-engine-api/src/message.rs
Labels: C-debt

#13115 feat: make TransactionsManager Future impl generic over NetworkPrimitives
  crates/net/eth-wire-types/src/primitives.rs
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
Labels: C-enhancement, A-networking, A-sdk

#13116 feat: use generic CapabilityMessage everywhere
  crates/net/network/src/manager.rs
  crates/net/network/src/session/handle.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/swarm.rs
Labels: C-enhancement, A-networking, A-sdk

#13117 chore: propagate network primitives generic to EthStream usages
  crates/net/network/src/session/active.rs
  examples/manual-p2p/src/main.rs
Labels: C-enhancement, A-networking, A-sdk

#13100 chore: relax rpc bounds
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-api/src/types.rs
Labels: A-rpc

#13119 chore: bound most NetworkBuilder methods by NetworkPrimitives generic
  crates/net/eth-wire/tests/pooled_transactions.rs
  crates/net/network/src/builder.rs
  crates/net/network/src/config.rs
Labels: C-enhancement, A-networking, A-sdk

#13123 chore(ci): fix hive patch
  .github/assets/hive/no_sim_build.diff
Labels: C-hivetest, A-ci

#13111 Extend revm spec tests for holocene
  crates/optimism/evm/src/config.rs
Labels: A-execution, C-test, A-op-reth

#13072 fix(witness): collect witness using sparse trie
  crates/evm/execution-errors/src/trie.rs
  crates/trie/sparse/src/state.rs
  crates/trie/trie/src/proof/blinded.rs
  crates/trie/trie/src/witness.rs
Labels: C-bug, A-trie

#12972 refactor: split `NetworkEventListenerProvider`
  Cargo.lock
  crates/e2e-test-utils/Cargo.toml
  crates/e2e-test-utils/src/network.rs
  crates/net/network-api/src/events.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/src/transactions/mod.rs
  crates/net/network/tests/it/connect.rs
  crates/net/network/tests/it/session.rs
  crates/net/network/tests/it/txgossip.rs
  docs/crates/network.md
  examples/bsc-p2p/src/main.rs
  examples/polygon-p2p/Cargo.toml
  examples/polygon-p2p/src/main.rs
Labels: A-networking

#13140 chore: add typed receipt for Receipt
  crates/primitives-traits/src/receipt.rs
  crates/primitives/src/receipt.rs
Labels: A-sdk

#13129 feat(trie): collect branch node hash masks when calculating a proof
  crates/trie/common/src/proofs.rs
  crates/trie/parallel/src/proof.rs
  crates/trie/trie/src/proof/mod.rs
Labels: C-enhancement, A-trie

#13132 feat: add OpBuilder config
  crates/optimism/payload/src/builder.rs
  crates/optimism/payload/src/config.rs
Labels: C-enhancement, A-op-reth

#13143 feat: wire network primitives to remaining components
  crates/net/eth-wire/src/ethstream.rs
  crates/net/network/src/builder.rs
  crates/net/network/src/config.rs
  crates/net/network/src/eth_requests.rs
  crates/net/network/src/fetch/mod.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/session/conn.rs
  crates/net/network/src/state.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/src/transactions/mod.rs
  crates/net/network/tests/it/connect.rs
  crates/node/core/src/cli/config.rs
  examples/network-txpool/src/main.rs
Labels: C-enhancement, A-networking, A-sdk

#13142 Bump `op-alloy`
  Cargo.lock
  Cargo.toml
Labels: A-op-reth

#13148 chore: bump pprof
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#13133 docs: add docker and error code 13 to troubleshooting chapter
  book/run/troubleshooting.md
Labels: C-docs

#13147 feat: install op miner endpoint
  Cargo.lock
  Cargo.toml
  crates/node/builder/src/rpc.rs
  crates/optimism/node/src/node.rs
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/lib.rs
  crates/optimism/rpc/src/miner.rs
Labels: C-enhancement, P-high, A-rpc, A-op-reth

#13150 chore: bump alloy 073
  Cargo.lock
  Cargo.toml
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/request.rs
  crates/net/downloaders/src/bodies/test_utils.rs
  crates/primitives-traits/src/block/header.rs
  crates/stages/stages/src/stages/bodies.rs
Labels: A-dependencies

#13091 chore: reuse alloy proof fns
  crates/primitives/src/proofs.rs
Labels: C-enhancement, A-sdk

#13152 feat: impl compact for alloy txtype
  Cargo.lock
  crates/storage/codecs/Cargo.toml
  crates/storage/codecs/src/alloy/transaction/mod.rs
  crates/storage/codecs/src/alloy/transaction/txtype.rs
Labels: A-sdk

#13146 feat: make RPC cache generic over primitives
  Cargo.lock
  crates/optimism/evm/Cargo.toml
  crates/optimism/evm/src/l1.rs
  crates/optimism/rpc/src/eth/block.rs
  crates/optimism/rpc/src/eth/call.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-api/src/node.rs
  crates/rpc/rpc-eth-types/src/builder/ctx.rs
  crates/rpc/rpc-eth-types/src/cache/mod.rs
  crates/rpc/rpc-eth-types/src/fee_history.rs
  crates/rpc/rpc-eth-types/src/gas_oracle.rs
  crates/rpc/rpc-eth-types/src/logs_utils.rs
  crates/rpc/rpc/src/eth/core.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/helpers/block.rs
  crates/rpc/rpc/src/eth/helpers/call.rs
  crates/rpc/rpc/src/eth/helpers/fees.rs
  crates/rpc/rpc/src/eth/helpers/pending_block.rs
  crates/rpc/rpc/src/eth/helpers/receipt.rs
  crates/rpc/rpc/src/eth/helpers/signer.rs
  crates/rpc/rpc/src/eth/helpers/spec.rs
  crates/rpc/rpc/src/eth/helpers/state.rs
  crates/rpc/rpc/src/eth/helpers/trace.rs
  crates/rpc/rpc/src/eth/helpers/transaction.rs
  crates/storage/storage-api/src/block.rs
  crates/storage/storage-api/src/receipts.rs
  crates/storage/storage-api/src/transactions.rs
Labels: C-enhancement, A-rpc

#13020 perf(trie): avoid (de)allocating an extra prefix set
  crates/trie/db/src/storage.rs
  crates/trie/parallel/src/root.rs
  crates/trie/trie/src/trie.rs
Labels: C-perf

#13076 chore: add typed2718 to txtype
  crates/primitives-traits/src/size.rs
  crates/primitives-traits/src/transaction/tx_type.rs
  crates/primitives/src/transaction/tx_type.rs
  crates/transaction-pool/src/blobstore/tracker.rs
Labels: A-sdk

#13161 Allow replacement txs with exactly price bump
  crates/transaction-pool/src/validate/mod.rs
Labels: A-tx-pool

#13159 feat: use network tx for `Pool::Pooled`
  crates/ethereum/node/src/node.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/src/transactions/mod.rs
  crates/node/builder/src/builder/mod.rs
  crates/optimism/node/src/node.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-types/src/utils.rs
  crates/rpc/rpc/src/eth/bundle.rs
  crates/rpc/rpc/src/eth/sim_bundle.rs
  crates/rpc/rpc/src/trace.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#13166 chore: make reth codec support optional
  crates/stages/types/Cargo.toml
  crates/stages/types/src/checkpoints.rs
  crates/stages/types/src/execution.rs
  crates/stages/types/src/lib.rs
  crates/storage/db-api/Cargo.toml
Labels: A-dependencies

#13167 feat: re-export used deps from reth-codecs
  crates/storage/codecs/Cargo.toml
  crates/storage/codecs/derive/src/compact/flags.rs
  crates/storage/codecs/derive/src/compact/generator.rs
  crates/storage/codecs/derive/src/compact/mod.rs
  crates/storage/codecs/src/lib.rs
  crates/storage/codecs/src/private.rs
Labels: A-db

#13135 feat(trie): use branch node hash masks in sparse trie
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
Labels: C-enhancement, A-trie

#12840 chore: Code Simplification and Optimization
  testing/ef-tests/src/models.rs
Labels: C-debt

#12975 perf: profile TransactionsManager::poll hash fetching
  crates/net/network/Cargo.toml
  crates/net/network/benches/broadcast.rs
  crates/net/network/benches/tx_manager_hash_fetching.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/tests/it/main.rs
  crates/net/network/tests/it/transaction_hash_fetching.rs
Labels: C-test, A-networking

#13177 fix: push job front of queue
  crates/exex/exex/src/backfill/job.rs
  crates/exex/exex/src/backfill/stream.rs
Labels: C-bug, A-exex

#13170 feat: EthApi traits abstraction
  Cargo.lock
  crates/e2e-test-utils/src/node.rs
  crates/e2e-test-utils/src/rpc.rs
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/rpc.rs
  crates/optimism/rpc/src/eth/block.rs
  crates/optimism/rpc/src/eth/call.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/eth/pending_block.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/primitives-traits/src/block/mod.rs
  crates/primitives/src/block.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/rpc/rpc-api/src/otterscan.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-builder/tests/it/middleware.rs
  crates/rpc/rpc-eth-api/Cargo.toml
  crates/rpc/rpc-eth-api/src/core.rs
  crates/rpc/rpc-eth-api/src/helpers/block.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-api/src/helpers/fee.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/rpc/rpc-eth-api/src/helpers/signer.rs
  crates/rpc/rpc-eth-api/src/helpers/spec.rs
  crates/rpc/rpc-eth-api/src/helpers/state.rs
  crates/rpc/rpc-eth-api/src/helpers/trace.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-api/src/lib.rs
  crates/rpc/rpc-eth-api/src/types.rs
  crates/rpc/rpc-eth-types/src/pending_block.rs
  crates/rpc/rpc-testing-util/src/debug.rs
  crates/rpc/rpc-testing-util/tests/it/trace.rs
  crates/rpc/rpc-types-compat/Cargo.toml
  crates/rpc/rpc-types-compat/src/block.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/engine.rs
  crates/rpc/rpc/src/eth/bundle.rs
  crates/rpc/rpc/src/eth/core.rs
  crates/rpc/rpc/src/eth/helpers/block.rs
  crates/rpc/rpc/src/eth/helpers/call.rs
  crates/rpc/rpc/src/eth/helpers/pending_block.rs
  crates/rpc/rpc/src/eth/helpers/signer.rs
  crates/rpc/rpc/src/eth/helpers/spec.rs
  crates/rpc/rpc/src/eth/helpers/trace.rs
  crates/rpc/rpc/src/eth/helpers/transaction.rs
  crates/rpc/rpc/src/eth/sim_bundle.rs
  crates/rpc/rpc/src/otterscan.rs
  crates/rpc/rpc/src/trace.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/storage-api/src/header.rs
  crates/transaction-pool/src/traits.rs
Labels: A-rpc

#13178 chore: use leaner NoopProvider in network
  crates/net/network/Cargo.toml
  crates/net/network/src/config.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/state.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/src/transactions/mod.rs
  crates/net/network/tests/it/connect.rs
  crates/net/network/tests/it/session.rs
  crates/net/network/tests/it/startup.rs
  crates/storage/storage-api/src/noop.rs
Labels: C-debt, C-test

#12806 perf(tx-pool): reuse write lock to insert txs batch
  crates/transaction-pool/src/pool/mod.rs
Labels: A-tx-pool

#13171 feat(`DbTx`): add `get_by_encoded_key`
  crates/storage/db-api/src/mock.rs
  crates/storage/db-api/src/transaction.rs
  crates/storage/db/Cargo.toml
  crates/storage/db/benches/get.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  testing/ef-tests/src/models.rs
Labels: A-db

#13168 fix(trie): delete self destructed accounts from sparse trie
  crates/engine/tree/src/tree/root.rs
Labels: C-bug, A-trie

#13176 chore: remove some excessive allocs in hot path
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
Labels: C-perf, A-tx-pool

#13181 chore: use slice arg for tx decoding
  crates/optimism/rpc/src/eth/transaction.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-types/src/utils.rs
  crates/rpc/rpc/src/eth/bundle.rs
  crates/rpc/rpc/src/eth/sim_bundle.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-perf

#13130 feat(db): initialize db with tables
  crates/storage/db-api/src/table.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/tables/mod.rs
Labels: A-db

#13184 chore: rm unused evm provider fn
  crates/evm/src/provider.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
Labels: C-debt

#13190 chore: rm validate delegate
  crates/primitives/src/transaction/sidecar.rs
  crates/rpc/rpc/src/eth/bundle.rs
Labels: C-debt, A-sdk

#13187 perf(`AllTransactions`-iter): do not clone all transactions by default
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-perf

#13188 perf: more `FxHashMap`s for `SenderId` key
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-perf, A-tx-pool

#13182 refactor(prune-types/prune): move PruneLimiter to `reth-prune`
  crates/prune/prune/src/db_ext.rs
  crates/prune/prune/src/lib.rs
  crates/prune/prune/src/limiter.rs
  crates/prune/prune/src/pruner.rs
  crates/prune/prune/src/segments/mod.rs
  crates/prune/prune/src/segments/receipts.rs
  crates/prune/prune/src/segments/static_file/headers.rs
  crates/prune/prune/src/segments/static_file/transactions.rs
  crates/prune/prune/src/segments/user/account_history.rs
  crates/prune/prune/src/segments/user/receipts_by_logs.rs
  crates/prune/prune/src/segments/user/sender_recovery.rs
  crates/prune/prune/src/segments/user/storage_history.rs
  crates/prune/prune/src/segments/user/transaction_lookup.rs
  crates/prune/types/src/lib.rs
  crates/prune/types/src/pruner.rs
Labels: C-debt

#13193 perf: call increment once
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-perf, A-tx-pool

#13195 feat: make BlockResponse generic over header
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/noop.rs
  crates/net/downloaders/src/bodies/queue.rs
  crates/net/downloaders/src/bodies/request.rs
  crates/net/p2p/src/bodies/downloader.rs
  crates/net/p2p/src/bodies/response.rs
  crates/primitives-traits/src/header/sealed.rs
  crates/stages/stages/src/stages/bodies.rs
Labels: C-enhancement, A-sdk

#13201 chore: remove unused trie-common alloy-serde dep
  crates/trie/common/Cargo.toml
Labels: C-enhancement, A-dependencies, A-trie

#13189 perf(txpool): remove more clones
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-perf

#13200 chore: fix `cargo check -p reth-stages --tests`
  crates/stages/stages/Cargo.toml
Labels: C-enhancement, C-test

#13112 Add placeholder `OpHardfork::Isthmus`
  crates/optimism/chainspec/src/lib.rs
  crates/optimism/evm/src/config.rs
  crates/optimism/hardforks/src/hardfork.rs
  crates/optimism/hardforks/src/lib.rs
Labels: A-execution, A-op-reth

#13199 chore: make zip_blocks generic over header
  crates/net/downloaders/src/bodies/test_utils.rs
Labels: C-test, A-sdk

#13209 chore: move calculate tx root to blockbody trait
  crates/consensus/common/src/validation.rs
  crates/primitives-traits/src/block/body.rs
  crates/primitives/src/traits.rs
Labels: A-sdk

#13207 chore(engine): refactor code to transform EvmState into HashedPostState
  crates/engine/tree/src/tree/root.rs
Labels: C-enhancement, A-blockchain-tree

#13210 chore: make reth-network-peers risc compatible
  .github/assets/check_rv32imac.sh
  Cargo.lock
  Cargo.toml
  crates/net/peers/Cargo.toml
  crates/net/peers/src/lib.rs
Labels: A-dependencies

#13208 chore: flip tx conversion impl
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/transaction-pool/src/traits.rs
Labels: A-sdk

#13215 chore: feature gate reth-codecs in trie-common
  crates/stages/types/Cargo.toml
  crates/trie/common/Cargo.toml
  crates/trie/common/src/hash_builder/state.rs
  crates/trie/common/src/nibbles.rs
  crates/trie/common/src/storage.rs
  crates/trie/common/src/subnode.rs
Labels: A-dependencies

#13221 test: add tracing test
  crates/rpc/rpc-testing-util/tests/it/trace.rs
Labels: C-test

#13213 chore(engine): simplify StateRootTask creation and hook management
  crates/engine/tree/src/tree/root.rs
Labels: C-enhancement, A-blockchain-tree

#13196 feat: bound NetworkPrimitives types by proper traits
  crates/net/eth-wire-types/src/primitives.rs
Labels: C-enhancement, A-networking, A-sdk

#13227 fix: deny advisory RUSTSEC-2024-0421
  Cargo.lock
  crates/net/dns/Cargo.toml
  crates/net/dns/src/resolver.rs
Labels: A-dependencies

#13229 chore: add default impls for withdrawals and ommers root
  crates/primitives-traits/src/block/body.rs
Labels: C-enhancement, A-sdk

#13183 fix(trie): reveal extension child in sparse trie when updating a leaf
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
Labels: C-bug, A-trie

#13234 fix(trie): retain updates only for sparse branch nodes in the prefix set
  crates/trie/sparse/src/trie.rs
Labels: C-bug, A-trie

#13240 perf(trie): use entry API in sparse trie
  crates/trie/sparse/src/trie.rs
Labels: C-perf, A-trie

#13212 perf(engine): add StateRootTask bench
  crates/engine/tree/Cargo.toml
  crates/engine/tree/benches/state_root_task.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/root.rs
Labels: C-perf, A-trie

#13246 chore: add blob_versioned_hashes_iter to block body
  crates/primitives-traits/src/block/body.rs
  crates/primitives/src/block.rs
Labels: A-sdk

#13245 Return a propoer error code for txpool is full error
  crates/rpc/rpc-eth-types/src/error/mod.rs
Labels: A-rpc

#13241 feat(rpc): relax `VaidationApi` and `EngineApi`
  Cargo.lock
  crates/engine/primitives/src/lib.rs
  crates/ethereum/engine-primitives/src/lib.rs
  crates/ethereum/node/src/node.rs
  crates/node/builder/src/rpc.rs
  crates/optimism/node/src/engine.rs
  crates/optimism/node/src/node.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/middleware.rs
  crates/rpc/rpc-builder/tests/it/startup.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/tests/it/payload.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/validation.rs
  examples/custom-engine-types/src/main.rs
  examples/rpc-db/src/main.rs
Labels: A-rpc, A-sdk

#13250 feat: extract zstd compressors
  Cargo.lock
  Cargo.toml
  crates/primitives/Cargo.toml
  crates/primitives/src/lib.rs
  crates/primitives/src/receipt.rs
  crates/primitives/src/transaction/mod.rs
  crates/storage/zstd-compressors/Cargo.toml
  crates/storage/zstd-compressors/receipt_dictionary.bin
  crates/storage/zstd-compressors/src/lib.rs
  crates/storage/zstd-compressors/transaction_dictionary.bin
Labels: C-enhancement, A-dependencies, A-sdk

#13198 chore: use `BlockWithParent` for `StageError`
  Cargo.lock
  crates/consensus/beacon/src/engine/invalid_headers.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/engine/tree/src/tree/mod.rs
  crates/primitives-traits/src/header/sealed.rs
  crates/stages/api/Cargo.toml
  crates/stages/api/src/error.rs
  crates/stages/api/src/pipeline/ctrl.rs
  crates/stages/api/src/pipeline/mod.rs
  crates/stages/stages/src/stages/execution.rs
  crates/stages/stages/src/stages/headers.rs
  crates/stages/stages/src/stages/merkle.rs
  crates/stages/stages/src/stages/sender_recovery.rs
  crates/stages/stages/src/stages/utils.rs
  testing/testing-utils/src/generators.rs
Labels: C-enhancement, A-staged-sync, A-sdk

#13256 chore: pass primiitves generic to `EngineApiTreeHandler` fields
  crates/blockchain-tree/Cargo.toml
  crates/blockchain-tree/src/block_buffer.rs
  crates/engine/local/src/service.rs
  crates/engine/service/src/service.rs
  crates/engine/tree/src/engine.rs
  crates/engine/tree/src/tree/mod.rs
Labels: A-consensus, A-sdk

#13258 feat: remove default types from headers stage
  crates/stages/stages/src/stages/headers.rs
Labels: A-staged-sync, A-networking, A-sdk

#13257 feat: relax bounds for `EngineApiTreeHandler`
  Cargo.lock
  crates/blockchain-tree-api/Cargo.toml
  crates/blockchain-tree-api/src/error.rs
  crates/consensus/beacon/src/engine/event.rs
  crates/engine/local/src/service.rs
  crates/engine/service/src/service.rs
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/engine.rs
  crates/engine/tree/src/tree/mod.rs
Labels: A-consensus, A-sdk

#13259 feat: make bodies downloader generic over header
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/noop.rs
  crates/net/downloaders/src/bodies/queue.rs
  crates/net/downloaders/src/bodies/request.rs
  crates/net/downloaders/src/bodies/task.rs
  crates/net/p2p/src/bodies/downloader.rs
  crates/net/p2p/src/bodies/response.rs
  crates/node/builder/src/setup.rs
  crates/stages/stages/src/stages/bodies.rs
  crates/stages/stages/src/stages/utils.rs
Labels: C-enhancement, A-networking, A-sdk

#13262 chore: release 1.1.3
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#13273 feat: make engine block downloaders generic over block
  crates/consensus/beacon/src/engine/mod.rs
  crates/engine/local/src/service.rs
  crates/engine/service/src/service.rs
  crates/engine/tree/src/download.rs
  crates/engine/tree/src/engine.rs
  crates/node/builder/src/launch/engine.rs
  crates/primitives-traits/src/block/header.rs
  crates/storage/provider/src/providers/mod.rs
Labels: A-consensus, A-sdk

#13269 feat(engine): parallel sparse storage roots
  crates/engine/tree/src/tree/root.rs
  crates/evm/execution-errors/src/trie.rs
  crates/trie/sparse/src/state.rs
Labels: C-enhancement, A-trie

#13272 chore: remove unused evm env provider fns
  crates/evm/src/provider.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
Labels: C-debt, A-execution

#13268 Bump alloy to 0.8.0
  Cargo.lock
  Cargo.toml
  crates/consensus/beacon/src/engine/invalid_headers.rs
  crates/net/eth-wire-types/src/broadcast.rs
  crates/optimism/primitives/src/transaction/mod.rs
  crates/optimism/primitives/src/transaction/signed.rs
  crates/primitives-traits/src/transaction/mod.rs
  crates/primitives/src/alloy_compat.rs
  crates/primitives/src/block.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/rpc/rpc-server-types/src/result.rs
  crates/rpc/rpc/src/otterscan.rs
  crates/storage/codecs/derive/src/arbitrary.rs
Labels: A-dependencies

#13169 feat: add NetworkPrimitives to NetworkBuilder
  Cargo.lock
  crates/e2e-test-utils/src/network.rs
  crates/ethereum/consensus/src/lib.rs
  crates/ethereum/consensus/src/validation.rs
  crates/ethereum/node/src/node.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/queue.rs
  crates/net/downloaders/src/bodies/request.rs
  crates/net/network-api/src/events.rs
  crates/net/network-api/src/lib.rs
  crates/net/network/src/network.rs
  crates/net/p2p/src/bodies/client.rs
  crates/net/p2p/src/bodies/downloader.rs
  crates/net/p2p/src/headers/client.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/builder/mod.rs
  crates/node/builder/src/components/builder.rs
  crates/node/builder/src/components/mod.rs
  crates/node/builder/src/components/network.rs
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/setup.rs
  crates/optimism/node/src/node.rs
  crates/stages/stages/src/sets.rs
  crates/stages/stages/src/stages/execution.rs
  crates/stages/stages/src/stages/merkle.rs
  crates/stages/stages/src/stages/sender_recovery.rs
Labels: C-enhancement, A-networking, A-sdk

#13276 chore: introduce receipts generic
  crates/net/eth-wire-types/src/receipts.rs
Labels: A-sdk

#13274 chore: reduce revm scope in txpool
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  bin/reth/src/commands/debug_cmd/build_block.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/builder/mod.rs
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool

#13289 fix: fromstr impl for miner variant
  crates/rpc/rpc-server-types/src/module.rs
Labels: A-cli

#13287 chore: cut down on tx_type usage
  crates/net/network/src/transactions/mod.rs
  crates/optimism/primitives/src/transaction/signed.rs
  crates/primitives/src/transaction/mod.rs
  crates/transaction-pool/src/blobstore/tracker.rs
  crates/transaction-pool/src/traits.rs
Labels: A-sdk

#13291 chore: bump version 1.1.4
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#13292 chore: rm associated type
  crates/net/network/src/transactions/mod.rs
  crates/optimism/primitives/src/transaction/signed.rs
  crates/primitives-traits/src/lib.rs
  crates/primitives-traits/src/node.rs
  crates/primitives-traits/src/transaction/mod.rs
  crates/primitives-traits/src/transaction/signed.rs
  crates/primitives-traits/src/transaction/tx_type.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/primitives/src/transaction/tx_type.rs
Labels: A-sdk

#13281 fix: only terminate the stream if range is empty
  crates/exex/exex/src/backfill/stream.rs
Labels: C-bug, A-exex

#13296 chore: rm receiptsext trait
  crates/engine/util/src/reorg.rs
  crates/ethereum/payload/src/lib.rs
  crates/evm/execution-types/src/execution_outcome.rs
  crates/primitives-traits/src/receipt.rs
  crates/primitives/src/receipt.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
Labels: A-sdk

#13300 fix(trie): parallel proof should return empty storage proofs
  crates/trie/parallel/src/proof.rs
Labels: C-bug, A-trie

#13295 feat: ethereum-specific receipt
  Cargo.lock
  crates/ethereum/primitives/Cargo.toml
  crates/ethereum/primitives/src/lib.rs
  crates/ethereum/primitives/src/receipt.rs
  crates/evm/execution-types/src/chain.rs
  crates/evm/execution-types/src/execution_outcome.rs
  crates/primitives-traits/src/receipt.rs
Labels: A-sdk

#13306 chore: use consistent naming for tx fns
  crates/payload/validator/src/lib.rs
  crates/primitives/src/block.rs
Labels: A-sdk

#13312 feat(op-isthmus): impl `Debug` for `BlockchainProvider`
  crates/storage/provider/src/providers/mod.rs
Labels: A-db, A-op-reth

#13316 chore(sdk): fix docs to match generic tx type
  crates/chain-state/src/in_memory.rs
Labels: C-docs, C-debt, A-sdk

#13315 feat(builder): ethereum builder config
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  crates/ethereum/node/Cargo.toml
  crates/ethereum/node/src/node.rs
  crates/ethereum/payload/src/config.rs
  crates/ethereum/payload/src/lib.rs
  crates/node/core/src/args/payload_builder.rs
  crates/node/core/src/version.rs
  crates/optimism/payload/src/builder.rs
  crates/payload/basic/src/lib.rs
  crates/payload/basic/src/stack.rs
  examples/custom-engine-types/src/main.rs
  examples/custom-payload-builder/src/generator.rs
  examples/custom-payload-builder/src/main.rs
Labels: C-enhancement, A-block-building

#13332 feat(blockchain-tree-api): remove manual implementations of core::error::Error
  crates/blockchain-tree-api/src/error.rs
Labels: C-debt

#13342 chore: impl evm env provider for noop
  Cargo.lock
  crates/evm/Cargo.toml
  crates/evm/src/test_utils.rs
  crates/storage/storage-api/src/noop.rs
Labels: C-test

#13341 chore: move secp256 crypto to primitive-traits
  Cargo.lock
  crates/primitives-traits/Cargo.toml
  crates/primitives-traits/src/crypto.rs
  crates/primitives-traits/src/lib.rs
  crates/primitives-traits/src/transaction/mod.rs
  crates/primitives-traits/src/transaction/signature.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/transaction/signature.rs
  crates/primitives/src/transaction/util.rs
Labels: A-sdk

#13271 chore: relax eth pooled tx
  crates/transaction-pool/src/traits.rs
Labels: A-sdk

#13303 feat(rpc): remove total difficulty
  crates/rpc/rpc-eth-api/src/helpers/block.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-types/src/simulate.rs
  crates/rpc/rpc-types-compat/src/block.rs
Labels: A-rpc

#13345 chore: unify noop provider impls
  crates/chain-state/src/lib.rs
  crates/chain-state/src/noop.rs
  crates/rpc/rpc/src/eth/helpers/transaction.rs
  crates/storage/provider/src/test_utils/noop.rs
Labels: C-debt

#13302 docs: inline mermaid diagrams while aquamarine is fixed
  crates/net/network/src/manager.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-docs

#13346 feat(trie): replace TrieInput by its components in ParallelProof
  crates/trie/parallel/src/proof.rs
Labels: C-enhancement, A-trie

#13333 chore: update gas limit on new head block
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool

#13348 chore: rm reth-provider dep from payload crate
  Cargo.lock
  crates/ethereum/payload/Cargo.toml
  crates/ethereum/payload/src/lib.rs
Labels: A-dependencies

#13356 fix(engine): return error on StateRootTask multiproof and root calculation failures
  Cargo.lock
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/tree/root.rs
Labels: C-bug, A-blockchain-tree, A-trie

#13310 perf(engine): cache proof targets in proof sequencer for state root task
  crates/engine/tree/src/tree/root.rs
  crates/trie/common/src/proofs.rs
  crates/trie/db/src/proof.rs
  crates/trie/db/tests/witness.rs
  crates/trie/sparse/src/state.rs
  crates/trie/trie/src/proof/blinded.rs
  crates/trie/trie/src/proof/mod.rs
  crates/trie/trie/src/witness.rs
Labels: C-perf, A-trie

#13351 fix(builder): desired block gas limit
  Cargo.lock
  book/cli/reth/node.md
  crates/ethereum/consensus/src/lib.rs
  crates/ethereum/evm/src/lib.rs
  crates/ethereum/node/Cargo.toml
  crates/ethereum/node/src/node.rs
  crates/ethereum/payload/Cargo.toml
  crates/ethereum/payload/src/config.rs
  crates/ethereum/payload/src/lib.rs
  crates/evm/src/lib.rs
  crates/node/core/src/args/payload_builder.rs
  crates/node/core/src/args/txpool.rs
  crates/node/core/src/cli/config.rs
  crates/optimism/evm/src/lib.rs
  crates/optimism/payload/src/builder.rs
  crates/primitives-traits/src/constants/mod.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/validation.rs
Labels: C-bug, C-enhancement, A-block-building, A-cli

#13349 feat: relax maintain
  crates/transaction-pool/src/maintain.rs
Labels: A-sdk
