Repository paradigmxyz/reth, pull requests merged in 2024-07, with the labels that each got.

#9205 refactor(net): some refactor in eth requests
  crates/net/network/src/eth_requests.rs
Labels: A-networking

#9206 refactor(revm): simplify `fill_tx_env`
  crates/primitives/src/revm/env.rs
Labels: C-debt

#9204 docs: fix the links to code in discv4 docs
  docs/crates/discv4.md
Labels: C-docs

#9208 refactor: small refactoring
  crates/consensus/common/src/validation.rs
  crates/net/downloaders/src/file_client.rs
Labels: C-debt

#9212 refactor: some simplifications around revm database
  crates/revm/src/database.rs
Labels: A-db

#9198 refactor(chainspec): simplify `genesis_header` using default pattern
  crates/chainspec/src/spec.rs
Labels: C-debt

#9216 fix: ambiguous deposit mint value in arbitrary
  crates/primitives/src/transaction/mod.rs
Labels: C-test, A-op-reth

#8559 feat: new engine API handler
  CODEOWNERS
  Cargo.lock
  Cargo.toml
  crates/consensus/beacon/src/engine/forkchoice.rs
  crates/consensus/beacon/src/engine/invalid_headers.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/backfill.rs
  crates/engine/tree/src/chain.rs
  crates/engine/tree/src/download.rs
  crates/engine/tree/src/engine.rs
  crates/engine/tree/src/lib.rs
  crates/engine/tree/src/metrics.rs
  crates/engine/tree/src/persistence.rs
  crates/engine/tree/src/test_utils.rs
  crates/engine/tree/src/tree/memory_overlay.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-debt, C-perf, A-consensus

#9211 chore: remove unused `MIN_LENGTH_EIPXXXX_ENCODED`
  crates/primitives/src/transaction/mod.rs
Labels: C-debt

#9202 chore(trie): clean up trie update operation matching
  crates/trie/trie/src/trie_cursor/in_memory.rs
  crates/trie/trie/src/updates.rs
Labels: C-debt, A-trie

#9218 chore: add builder with rng secret key fn
  crates/net/network/src/config.rs
Labels: A-networking

#9224 chore(execution): verify cumulative gas used before receipts root
  crates/ethereum/consensus/src/validation.rs
Labels: C-debt, A-execution

#8992 docs(book): remote ExEx chapter
  book/developers/exex/assets/remote_exex.png
  book/developers/exex/remote.md
Labels: C-docs, A-exex

#9226 chore(trie): store only deleted keys in `TrieWalker`
  crates/trie/parallel/src/async_root.rs
  crates/trie/parallel/src/parallel_root.rs
  crates/trie/trie/src/trie.rs
  crates/trie/trie/src/updates.rs
  crates/trie/trie/src/walker.rs
Labels: C-debt, A-trie

#9225 feat: implement write method on persistence task
  crates/engine/tree/src/persistence.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-consensus, A-blockchain-tree

#9217 chore: extract db commands
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/cli/mod.rs
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/import_op.rs
  bin/reth/src/commands/import_receipts_op.rs
  bin/reth/src/commands/init_cmd.rs
  bin/reth/src/commands/init_state.rs
  bin/reth/src/commands/mod.rs
  bin/reth/src/commands/prune.rs
  bin/reth/src/commands/recover/storage_tries.rs
  bin/reth/src/commands/stage/drop.rs
  bin/reth/src/commands/stage/dump/mod.rs
  bin/reth/src/commands/stage/run.rs
  bin/reth/src/commands/stage/unwind.rs
  crates/cli/commands/Cargo.toml
  crates/cli/commands/src/common.rs
  crates/cli/commands/src/db/checksum.rs
  crates/cli/commands/src/db/clear.rs
  crates/cli/commands/src/db/diff.rs
  crates/cli/commands/src/db/get.rs
  crates/cli/commands/src/db/list.rs
  crates/cli/commands/src/db/mod.rs
  crates/cli/commands/src/db/stats.rs
  crates/cli/commands/src/db/tui.rs
  crates/cli/commands/src/lib.rs
Labels: A-db

#9195 feat(clippy): add `iter_without_into_iter`
  Cargo.toml
  crates/primitives-traits/src/withdrawal.rs
  crates/trie/trie/src/prefix_set/mod.rs
Labels: C-enhancement

#9043 fix(rpc/admin): missing enode/enr in admin_peers endpoint
  crates/net/network-api/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/peers.rs
  crates/net/network/src/session/handle.rs
  crates/net/network/src/session/mod.rs
  crates/rpc/rpc-api/src/admin.rs
  crates/rpc/rpc/src/admin.rs
Labels: A-networking

#9227 chore(trie): return nibbles from `TrieCursor::current`
  crates/trie/trie/src/trie.rs
  crates/trie/trie/src/trie_cursor/database_cursors.rs
  crates/trie/trie/src/trie_cursor/in_memory.rs
  crates/trie/trie/src/trie_cursor/mod.rs
  crates/trie/trie/src/trie_cursor/noop.rs
  crates/trie/trie/src/updates.rs
  crates/trie/trie/src/walker.rs
Labels: C-debt, A-trie

#9229 chore: disable discovery for --dev
  crates/e2e-test-utils/src/lib.rs
  crates/node/core/src/node_config.rs
Labels: A-cli

#9232 feat: add pruning related persistence API
  crates/engine/tree/src/persistence.rs
Labels: C-enhancement, A-db, A-blockchain-tree

#9233 chore: add send_action method to persistence task
  crates/engine/tree/src/persistence.rs
Labels: C-enhancement, A-db, A-blockchain-tree

#9247 chore: use format_gas and format_gas_throughput for gas logs
  Cargo.lock
  crates/exex/exex/Cargo.toml
  crates/exex/exex/src/backfill.rs
  crates/node/events/Cargo.toml
  crates/node/events/src/node.rs
  crates/primitives-traits/src/constants/gas_units.rs
  crates/primitives-traits/src/constants/mod.rs
  crates/primitives-traits/src/lib.rs
  crates/stages/api/src/metrics/execution.rs
  crates/stages/api/src/metrics/listener.rs
  crates/stages/api/src/metrics/mod.rs
  crates/stages/stages/Cargo.toml
  crates/stages/stages/src/stages/execution.rs
Labels: C-enhancement, A-utils, A-cli

#9231 chore: remove prune_modes from BlockWriter
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/cli/commands/src/common.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/engine/tree/src/persistence.rs
  crates/exex/exex/src/backfill.rs
  crates/node/builder/src/launch/common.rs
  crates/stages/stages/src/stages/execution.rs
  crates/stages/stages/src/stages/hashing_account.rs
  crates/stages/stages/src/stages/headers.rs
  crates/stages/stages/src/stages/mod.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/block.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: C-enhancement, C-debt, A-db

#9250 chore: fix pruner exex height docs, add run docs
  crates/prune/prune/src/pruner.rs
Labels: C-docs, C-enhancement, A-pruning

#9176 refactor(evm): set prune modes optionally for the batch executor
  bin/reth/src/commands/debug_cmd/merkle.rs
  crates/ethereum/evm/src/execute.rs
  crates/evm/src/either.rs
  crates/evm/src/execute.rs
  crates/evm/src/noop.rs
  crates/evm/src/test_utils.rs
  crates/exex/exex/src/backfill.rs
  crates/optimism/evm/src/execute.rs
  crates/stages/stages/src/stages/execution.rs
Labels: C-debt, A-execution

#9259 feat: add ChainspecParser trait
  Cargo.lock
  crates/cli/cli/Cargo.toml
  crates/cli/cli/src/chainspec.rs
  crates/cli/cli/src/lib.rs
Labels: A-cli

#9251 feat: add pruner to persistence task
  crates/engine/tree/src/persistence.rs
Labels: C-enhancement, A-blockchain-tree, A-pruning

#9261 feat: add non feature gated noop block reader
  Cargo.lock
  crates/net/network/Cargo.toml
  crates/net/network/src/config.rs
  crates/net/network/src/eth_requests.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/storage/storage-api/src/lib.rs
  crates/storage/storage-api/src/noop.rs
Labels: C-enhancement, A-networking

#9134 refactor: move write_peers_to_file to NetworkManager impl
  Cargo.lock
  crates/net/network/Cargo.toml
  crates/net/network/src/manager.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/builder/mod.rs
  crates/node/core/src/utils.rs
Labels: C-debt, A-networking

#9239 trie: revamp trie updates
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  crates/engine/tree/src/persistence.rs
  crates/stages/stages/benches/setup/mod.rs
  crates/stages/stages/src/stages/merkle.rs
  crates/storage/db-common/src/init.rs
  crates/storage/provider/src/bundle_state/execution_outcome.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/trie/parallel/benches/root.rs
  crates/trie/parallel/src/async_root.rs
  crates/trie/parallel/src/parallel_root.rs
  crates/trie/trie/src/proof.rs
  crates/trie/trie/src/trie.rs
  crates/trie/trie/src/trie_cursor/in_memory.rs
  crates/trie/trie/src/updates.rs
  crates/trie/trie/src/walker.rs
Labels: C-debt, A-trie

#9242 feat: moved optimism commands to create and remove from bin
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/cli/mod.rs
  bin/reth/src/commands/mod.rs
  crates/optimism/cli/Cargo.toml
  crates/optimism/cli/src/commands/build_pipeline.rs
  crates/optimism/cli/src/commands/import.rs
  crates/optimism/cli/src/commands/import_receipts.rs
  crates/optimism/cli/src/commands/mod.rs
  crates/optimism/cli/src/lib.rs
Labels: A-cli, A-op-reth

#9241 feat: add ethereum engine chain orchestrator
  Cargo.lock
  Cargo.toml
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/backfill.rs
  crates/engine/tree/src/engine.rs
  crates/engine/tree/src/lib.rs
  crates/engine/tree/src/test_utils.rs
  crates/ethereum/engine/Cargo.toml
  crates/ethereum/engine/src/lib.rs
  crates/ethereum/engine/src/orchestrator.rs
Labels: C-enhancement

#9268 feat: add empty ethereum cli crate
  Cargo.lock
  Cargo.toml
  crates/ethereum/cli/Cargo.toml
  crates/ethereum/cli/src/lib.rs
Labels: C-enhancement, A-cli

#9041 chore(rpc): `EthApi` builder
  Cargo.lock
  crates/ethereum/node/tests/e2e/dev.rs
  crates/node/builder/src/launch/mod.rs
  crates/node/builder/src/rpc.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/config.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/startup.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc-eth-api/src/core.rs
  crates/rpc/rpc-eth-api/src/helpers/mod.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-api/src/lib.rs
  crates/rpc/rpc-eth-types/src/cache/config.rs
  crates/rpc/rpc-eth-types/src/fee_history.rs
  crates/rpc/rpc-eth-types/src/gas_oracle.rs
  crates/rpc/rpc-eth-types/src/lib.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/core.rs
  crates/storage/db-api/src/lib.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/full.rs
  crates/storage/provider/src/traits/mod.rs
  examples/custom-dev-node/src/main.rs
  examples/custom-inspector/src/main.rs
  examples/rpc-db/src/main.rs
  examples/txpool-tracing/src/main.rs
Labels: C-debt, A-rpc

#9258 feat: add resolve blocking for TrustedNode
  crates/net/peers/src/trusted_peer.rs
Labels: A-networking

#9274 test(transaction-pool): add unit tests for `BestTransactionsWithFees` `next`
  crates/transaction-pool/src/pool/best.rs
Labels: A-tx-pool

#9276 clippy: rm some `type_complexity`
  crates/consensus/beacon/src/engine/mod.rs
  crates/etl/src/lib.rs
  crates/storage/db/benches/hash_keys.rs
  crates/storage/db/src/static_file/cursor.rs
  examples/stateful-precompile/src/main.rs
Labels: C-debt

#9280 test: rm useless unit tests for `calc_next_block_base_fee`
  crates/chainspec/src/constants/mod.rs
  crates/chainspec/src/constants/optimism.rs
Labels: C-test

#9278 fix: always evaluate build_profile_name at compile time
  crates/node/core/src/metrics/version_metrics.rs
  crates/node/core/src/version.rs
Labels: A-cli

#9273 feat(rpc): enable historical proofs
  book/cli/reth/node.md
  crates/node/core/src/args/rpc_server.rs
  crates/rpc/rpc-builder/src/config.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-eth-api/src/core.rs
  crates/rpc/rpc-eth-api/src/helpers/state.rs
  crates/rpc/rpc-eth-types/src/error.rs
  crates/rpc/rpc-server-types/src/constants.rs
  crates/rpc/rpc/src/eth/core.rs
  crates/rpc/rpc/src/eth/helpers/state.rs
  crates/rpc/rpc/src/eth/helpers/transaction.rs
Labels: C-enhancement, A-rpc

#9284 chore: use direct link to threshold docs
  crates/stages/stages/src/stages/execution.rs
Labels: C-docs, A-staged-sync

#9283 chore(rpc): rm dup getters `EthApi`
  crates/rpc/rpc/src/eth/core.rs
Labels: C-debt, A-rpc

#9272 chore: move `withdrawal_requests_contract_call` to `reth-evm`
  Cargo.lock
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/payload/src/lib.rs
  crates/evm/src/system_calls.rs
  crates/payload/basic/src/lib.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/revm/env.rs
  crates/primitives/src/revm/mod.rs
  crates/revm/Cargo.toml
  crates/revm/src/state_change.rs
Labels: C-debt, A-execution

#9264 fix(cli): don't init datadir if it doesn't exist in db command
  crates/cli/commands/src/db/mod.rs
Labels: A-cli

#9288 chore: rename eth engine module orchestrator -> service
  crates/ethereum/engine/src/lib.rs
  crates/ethereum/engine/src/service.rs
Labels: A-blockchain-tree

#9287 chore(trie): revamp inner in-memory trie cursor representation
  crates/trie/trie/src/trie_cursor/in_memory.rs
  crates/trie/trie/src/updates.rs
Labels: A-trie

#9291 perf: resolve trusted nodes concurrently
  crates/node/builder/src/launch/common.rs
Labels: C-perf

#9293 perf: spawn eth proof on IO pool
  crates/rpc/rpc-eth-api/src/helpers/state.rs
Labels: C-perf, A-rpc

#9289 feat: feature gate tokio::net lookup
  crates/net/network/Cargo.toml
  crates/net/peers/Cargo.toml
  crates/net/peers/src/lib.rs
  crates/net/peers/src/trusted_peer.rs
Labels: A-networking

#9300 feat(rpc/ots): add rpc erigon_getHeaderByNumber
  crates/rpc/rpc-api/src/otterscan.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/otterscan.rs
Labels: A-rpc

#9297 chore(cli): move utils to `reth-cli-utils` crate
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  bin/reth/src/commands/node/mod.rs
  bin/reth/src/commands/p2p.rs
  bin/reth/src/commands/stage/run.rs
  crates/cli/util/Cargo.toml
  crates/cli/util/src/lib.rs
  crates/cli/util/src/load_secret_key.rs
  crates/cli/util/src/parsers.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/builder/mod.rs
  crates/node/core/Cargo.toml
  crates/node/core/src/args/mod.rs
  crates/node/core/src/args/payload_builder.rs
  crates/node/core/src/args/utils.rs
Labels: A-dependencies, A-cli

#9307 fix: remove useless arbitrary feature
  crates/storage/codecs/Cargo.toml
Labels: A-dependencies

#9302 fix(rpc/ots): set block_number as u64 instead of NumberOrTag
  crates/rpc/rpc-api/src/otterscan.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/otterscan.rs
Labels: C-bug, A-rpc

#9303 feat: extract proof generation into `StateProofProvider`
  crates/engine/tree/src/tree/memory_overlay.rs
  crates/revm/src/test_utils.rs
  crates/rpc/rpc-eth-types/src/cache/db.rs
  crates/storage/provider/src/providers/bundle_state_provider.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/macros.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/storage-api/src/state.rs
  crates/storage/storage-api/src/trie.rs
Labels: C-enhancement, A-trie

#9306 chore(trie): return mutable prefix sets from `HashedPostState::construct_prefix_sets`
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/trie/parallel/benches/root.rs
  crates/trie/parallel/src/async_root.rs
  crates/trie/parallel/src/parallel_root.rs
  crates/trie/trie/src/prefix_set/mod.rs
  crates/trie/trie/src/state.rs
Labels: C-enhancement, A-trie

#9237 Fix: fix the issue of not being able to specify bootnode through command parameters
  crates/node/core/src/args/network.rs
Labels: A-cli

#9304 feat(trie): allow setting hashed cursor factory on `Proof`
  crates/storage/provider/src/providers/state/latest.rs
  crates/trie/trie/src/proof.rs
Labels: C-enhancement, A-trie

#9245 feat: backfill job single block iterator
  crates/ethereum/evm/src/execute.rs
  crates/evm/src/execute.rs
  crates/exex/exex/src/backfill.rs
Labels: C-enhancement, A-exex

#9301 perf: resolve trusted peers
  bin/reth/src/commands/p2p.rs
  bin/reth/src/commands/stage/run.rs
  crates/node/core/src/args/network.rs
Labels: A-networking, A-cli

#9318 fix: holesky genesis hash
  crates/primitives-traits/src/constants/mod.rs
  crates/storage/db-common/src/init.rs
Labels: C-bug

#9317 feat(trie): allow supplying prefix sets to `Proof`
  crates/trie/trie/src/prefix_set/mod.rs
  crates/trie/trie/src/proof.rs
Labels: C-enhancement, A-trie

#9319 feat(trie): `HashedPostState::account_proof`
  crates/trie/trie/src/state.rs
Labels: C-enhancement, A-trie

#9316 github-workflows: delete the direction of dead(deleted) code
  docs/repo/ci.md
Labels: C-docs

#9313 fix: no_std build
  crates/chainspec/src/spec.rs
Labels: C-enhancement

#9292 use op-alloy genesis types for genesis parsing
  Cargo.lock
  Cargo.toml
  crates/chainspec/Cargo.toml
  crates/chainspec/src/spec.rs
Labels: C-debt, A-op-reth

#9321 chore(pruner): remove redundant code
  crates/prune/prune/src/segments/history.rs
Labels: C-debt, A-pruning

#9322 chore(evm): turn associated `ConfigureEvm` fns into methods
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/evm/src/lib.rs
  crates/ethereum/payload/src/lib.rs
  crates/evm/src/lib.rs
  crates/evm/src/system_calls.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/evm/src/lib.rs
  crates/optimism/payload/src/builder.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/storage/provider/src/providers/database/provider.rs
  examples/custom-evm/src/main.rs
  examples/exex/rollup/src/execution.rs
  examples/stateful-precompile/src/main.rs
Labels: C-debt, A-execution

#9310 qol: purge goerli
  book/cli/reth.md
  book/cli/reth/config.md
  book/cli/reth/db.md
  book/cli/reth/debug.md
  book/cli/reth/dump-genesis.md
  book/cli/reth/import.md
  book/cli/reth/init-state.md
  book/cli/reth/init.md
  book/cli/reth/node.md
  book/cli/reth/p2p.md
  book/cli/reth/prune.md
  book/cli/reth/recover.md
  book/cli/reth/recover/storage-tries.md
  book/cli/reth/stage.md
  book/cli/reth/stage/drop.md
  book/cli/reth/stage/dump.md
  book/cli/reth/stage/run.md
  book/cli/reth/stage/unwind.md
  book/cli/reth/test-vectors.md
  book/cli/reth/test-vectors/tables.md
  crates/chainspec/src/lib.rs
  crates/chainspec/src/spec.rs
  crates/consensus/common/src/calc.rs
  crates/ethereum-forks/src/hardfork/ethereum.rs
  crates/ethereum/consensus/src/lib.rs
  crates/evm/src/lib.rs
  crates/net/peers/src/bootnodes/ethereum.rs
  crates/net/peers/src/bootnodes/mod.rs
  crates/node/core/src/args/utils.rs
  crates/node/core/src/dirs.rs
  crates/primitives-traits/src/constants/mod.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/header.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/proofs.rs
  crates/rpc/rpc-eth-api/src/helpers/state.rs
  crates/storage/db-common/src/init.rs
Labels: C-debt

#9326 Remove fullprovider trait restriction in backfill impls
  crates/exex/exex/Cargo.toml
  crates/exex/exex/src/backfill.rs
Labels: C-debt, A-exex

#9324 feat: op eth api scaffolding
  Cargo.lock
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/lib.rs
  crates/rpc/rpc-eth-api/src/helpers/mod.rs
Labels: C-enhancement, A-op-reth

#9327 feat: implement `HistoricalStateProviderRef::proof`
  crates/storage/errors/src/provider.rs
  crates/storage/provider/src/providers/bundle_state_provider.rs
  crates/storage/provider/src/providers/state/historical.rs
Labels: C-enhancement, A-trie

#9253 feat: log throughput in execution stage
  crates/primitives-traits/src/constants/gas_units.rs
  crates/stages/stages/src/stages/execution.rs
Labels: A-observability

#9336 fix: format_gas show two decimal places
  crates/primitives-traits/src/constants/gas_units.rs
Labels: A-observability

#9343 chore(deps): trim tokio features in eth-wire
  crates/net/downloaders/Cargo.toml
  crates/net/eth-wire/Cargo.toml
Labels: A-dependencies

#9345 move header.rs to eth-wire-types
  Cargo.lock
  crates/consensus/auto-seal/src/client.rs
  crates/net/downloaders/src/file_client.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/eth-wire-types/Cargo.toml
  crates/net/eth-wire-types/src/blocks.rs
  crates/net/eth-wire-types/src/header.rs
  crates/net/eth-wire-types/src/lib.rs
  crates/net/network/src/eth_requests.rs
  crates/net/network/tests/it/connect.rs
  crates/net/network/tests/it/requests.rs
  crates/net/p2p/src/full_block.rs
  crates/net/p2p/src/headers/client.rs
  crates/net/p2p/src/test_utils/full_block.rs
  crates/net/p2p/src/test_utils/headers.rs
  crates/node/core/Cargo.toml
  crates/node/core/src/utils.rs
  crates/primitives/src/lib.rs
Labels: A-networking

#9333 chore: move featureless commands from `bin` to `reth-cli-commands`
  Cargo.lock
  bin/reth/src/cli/mod.rs
  bin/reth/src/commands/mod.rs
  crates/cli/commands/Cargo.toml
  crates/cli/commands/src/config_cmd.rs
  crates/cli/commands/src/dump_genesis.rs
  crates/cli/commands/src/init_cmd.rs
  crates/cli/commands/src/init_state.rs
  crates/cli/commands/src/lib.rs
  crates/cli/commands/src/p2p.rs
  crates/cli/commands/src/prune.rs
  crates/cli/commands/src/recover/mod.rs
  crates/cli/commands/src/recover/storage_tries.rs
Labels: A-dependencies

#9337 chore: use usize in internal functions
  crates/rpc/rpc-eth-api/src/core.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
Labels: C-debt, A-rpc

#9340 test: make eth-wire tests compile with --all-features
  Cargo.lock
  crates/net/eth-wire-types/Cargo.toml
  crates/net/eth-wire-types/src/status.rs
  crates/net/eth-wire/Cargo.toml
Labels: C-test

#9349 chore(meta): fix link in issue template config
  .github/ISSUE_TEMPLATE/config.yml
Labels: A-ci

#9344 chore(deps): rm discv4 dep from eth-wire
  Cargo.lock
  crates/net/downloaders/Cargo.toml
  crates/net/eth-wire/Cargo.toml
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/hello.rs
  crates/net/eth-wire/src/test_utils.rs
Labels: A-dependencies

#9339 chore: dont enable serde by default for eth-wire
  crates/net/eth-wire-types/Cargo.toml
  crates/net/eth-wire-types/src/header.rs
  crates/net/eth-wire/Cargo.toml
Labels: A-dependencies

#9350 chore(meta): remove security link from issue template config
  .github/ISSUE_TEMPLATE/config.yml
Labels: A-meta

#9352 chore: remove cfg'ed use serde
  crates/net/eth-wire-types/src/blocks.rs
  crates/net/eth-wire-types/src/broadcast.rs
  crates/net/eth-wire-types/src/message.rs
  crates/net/eth-wire-types/src/receipts.rs
  crates/net/eth-wire-types/src/state.rs
  crates/net/eth-wire-types/src/status.rs
  crates/net/eth-wire-types/src/transactions.rs
Labels: C-debt, A-networking

#9353 fix: encode block as is in debug_getRawBlock
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/debug.rs
Labels: C-bug, A-rpc

#9357 chore: remove unused private stream type
  crates/net/p2p/src/full_block.rs
Labels: A-networking

#9026 feat: adds eth request panels to grafana
  etc/grafana/dashboards/overview.json
Labels: A-observability

#9341 feat: Add required trait impls for OpEthApi
  Cargo.lock
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/lib.rs
Labels: C-enhancement, A-rpc

#9335 feat: eip-7251
  crates/ethereum/evm/src/execute.rs
  crates/evm/execution-errors/src/lib.rs
  crates/evm/src/system_calls.rs
Labels: C-enhancement, M-devnet, E-prague

#9367 replacing network_handle with peer_info trait object
  bin/reth/src/commands/debug_cmd/execution.rs
  crates/node/builder/src/launch/mod.rs
  crates/node/events/src/node.rs
Labels: C-enhancement

#9364 book: add troubleshooting commands to check disk and memory health and performance
  book/run/troubleshooting.md
Labels: C-docs, A-db

#9368 chore(deps): bump alloy 0.1.4
  Cargo.lock
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: A-dependencies

#9370 feat(pruner): log stats as an ordered list of segments
  crates/node/events/src/node.rs
  crates/prune/prune/src/event.rs
  crates/prune/prune/src/pruner.rs
Labels: C-enhancement, C-debt, A-observability, A-pruning

#9369 feat(tree): validate state root
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-blockchain-tree

#9379 docs: typos
  docs/crates/stages.md
  docs/design/review.md
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: C-docs

#9312 perf(pruner): delete history indices by changeset keys
  Cargo.lock
  crates/prune/prune/Cargo.toml
  crates/prune/prune/src/segments/account_history.rs
  crates/prune/prune/src/segments/history.rs
  crates/prune/prune/src/segments/storage_history.rs
Labels: C-perf, A-pruning

#9380 clippy: rm useless clippy statement
  crates/transaction-pool/src/lib.rs
Labels: A-tx-pool, A-meta

#9363 Integrate permits for getproof
  book/cli/reth/node.md
  crates/node/core/src/args/rpc_server.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/rpc/rpc-builder/src/config.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-eth-api/src/helpers/blocking_task.rs
  crates/rpc/rpc-eth-api/src/helpers/state.rs
  crates/rpc/rpc-server-types/src/constants.rs
  crates/rpc/rpc/src/eth/core.rs
  crates/rpc/rpc/src/eth/helpers/state.rs
  crates/rpc/rpc/src/eth/helpers/transaction.rs
Labels: A-rpc

#9378 feat: add support for payload bodies
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/metrics.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: A-rpc, M-devnet, E-prague

#9236 feat(rpc/ots): implement ots_getContractCreator
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/otterscan.rs
Labels: C-enhancement, S-blocked, A-rpc

#9387 chore: fix clippy warnings for needless_borrows_for_generic_args
  crates/e2e-test-utils/src/wallet.rs
  crates/rpc/rpc-layer/src/auth_layer.rs
Labels: C-debt

#9246 feat(rpc/ots): implement ots_traceTransaction RPC
  crates/rpc/rpc-api/src/otterscan.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/otterscan.rs
Labels: A-rpc

#9389 chore: update private-testnet.md
  book/run/private-testnet.md
Labels: C-docs

#9263 feat(rpc/ots): implement ots_getTransactionBySenderAndNonce
  crates/rpc/rpc-api/src/otterscan.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/otterscan.rs
Labels: C-enhancement, A-rpc

#9388 chore: release 1.0.1
  Cargo.lock
  Cargo.toml
Labels: A-meta

#9383 fix: support additional eth call bundle args
  crates/rpc/rpc/src/eth/bundle.rs
Labels: C-bug, A-rpc

#9391 chore(deps): bump revm 11
  Cargo.lock
  Cargo.toml
  crates/optimism/evm/src/lib.rs
  crates/payload/builder/src/database.rs
  crates/primitives/src/transaction/compat.rs
  crates/revm/src/database.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-types/src/cache/db.rs
  crates/rpc/rpc-eth-types/src/error.rs
  crates/rpc/rpc-eth-types/src/revm_utils.rs
  crates/transaction-pool/src/validate/eth.rs
  examples/exex/rollup/src/db.rs
Labels: A-dependencies

#9390 chore(deps): rm reth-codecs dep
  Cargo.lock
  crates/net/eth-wire-types/Cargo.toml
  crates/net/eth-wire-types/src/header.rs
Labels: A-dependencies

#9399 test: make test compile in reth-rpc
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/helpers/state.rs
Labels: A-rpc, C-test

#9397 chore: remove unused `chainspec` field from `OptimismPayloadBuilder`
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  crates/optimism/node/src/node.rs
  crates/optimism/payload/src/builder.rs
Labels: C-debt, A-block-building, A-op-reth

#9403 test: add serial lock for lockfile tests
  crates/storage/db/src/lockfile.rs
Labels: C-bug, C-test

#9377 fix(op): fixes impl of eth api for OP
  Cargo.lock
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/error.rs
  crates/optimism/rpc/src/eth/block.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/eth/pending_block.rs
  crates/optimism/rpc/src/eth/receipt.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/optimism/rpc/src/lib.rs
  crates/rpc/rpc-api/src/optimism.rs
  crates/rpc/rpc-eth-api/src/helpers/spec.rs
  crates/rpc/rpc/src/eth/helpers/spec.rs
Labels: C-bug, A-rpc, A-op-reth

#9404 feat: make unwind_table_by_walker take RangeBounds
  crates/stages/stages/src/stages/headers.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-enhancement, A-db

#9405 feat: add DatabaseProvider remove method
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-enhancement, A-db

#9406 feat: add `get` and `take` methods to db provider
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-enhancement, A-db

#9410 chore(deps): trim cli-util crate deps
  Cargo.lock
  crates/cli/util/Cargo.toml
  crates/cli/util/src/load_secret_key.rs
  crates/cli/util/src/parsers.rs
Labels: A-dependencies, A-cli

#9366 feat: parsers
  Cargo.lock
  Cargo.toml
  crates/cli/cli/Cargo.toml
  crates/cli/cli/src/chainspec.rs
  crates/cli/cli/src/lib.rs
  crates/ethereum/cli/Cargo.toml
  crates/ethereum/cli/src/chainspec.rs
  crates/ethereum/cli/src/lib.rs
  crates/node/core/Cargo.toml
  crates/optimism/cli/Cargo.toml
  crates/optimism/cli/src/chainspec.rs
  crates/optimism/cli/src/lib.rs
Labels: A-cli

#9415 chore: rm redundant clippy allow
  crates/net/eth-wire-types/src/lib.rs
Labels: C-debt

#9418 feat: add fs-util for reading, writing json files
  Cargo.lock
  crates/fs-util/Cargo.toml
  crates/fs-util/src/lib.rs
  crates/net/network/src/manager.rs
Labels: C-enhancement

#9412 feat: remove get or take usage
  crates/stages/stages/src/stages/execution.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/block.rs
Labels: C-enhancement, A-db

#9421 chore: move `sigsegv handler` to `reth-cli-util` crate
  Cargo.lock
  bin/reth/src/lib.rs
  bin/reth/src/main.rs
  bin/reth/src/optimism.rs
  crates/cli/util/Cargo.toml
  crates/cli/util/src/lib.rs
  crates/cli/util/src/sigsegv_handler.rs
Labels: A-cli, A-op-reth

#9423 docs: remove random pub from transaction docs
  crates/primitives/src/transaction/eip1559.rs
  crates/primitives/src/transaction/eip2930.rs
  crates/primitives/src/transaction/eip4844.rs
Labels: C-docs, C-enhancement

#9234 feat: introduce static file task
  Cargo.lock
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/lib.rs
  crates/engine/tree/src/persistence.rs
  crates/engine/tree/src/static_files.rs
Labels: C-enhancement, A-db, A-blockchain-tree, A-static-files

#9436 docs(node): replace the old --dicsv5.addr with --discovery.addr
  book/cli/reth/node.md
  book/cli/reth/p2p.md
  book/cli/reth/stage/run.md
  book/cli/reth/stage/unwind.md
  crates/net/discv5/src/config.rs
  crates/node/core/src/args/network.rs
Labels: C-docs, A-cli

#9214 feat: eip-7702
  Cargo.toml
  crates/chainspec/src/spec.rs
  crates/net/network/src/metrics.rs
  crates/net/network/src/transactions/validation.rs
  crates/primitives/src/alloy_compat.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/receipt.rs
  crates/primitives/src/transaction/compat.rs
  crates/primitives/src/transaction/eip7702.rs
  crates/primitives/src/transaction/error.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/primitives/src/transaction/signature.rs
  crates/primitives/src/transaction/tx_type.rs
  crates/rpc/rpc-eth-api/Cargo.toml
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-types/src/error.rs
  crates/rpc/rpc-types-compat/src/transaction/mod.rs
  crates/storage/codecs/Cargo.toml
  crates/storage/codecs/src/alloy/authorization_list.rs
  crates/storage/codecs/src/alloy/mod.rs
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: C-enhancement, E-prague

#9426 chore: remove node-core from CODEOWNERS
  CODEOWNERS
Labels: A-meta

#9438 chore: rm redundant is_optimism checks
  crates/ethereum/consensus/src/lib.rs
  crates/optimism/evm/src/l1.rs
  crates/optimism/payload/src/payload.rs
  crates/payload/primitives/src/traits.rs
Labels: C-debt

#9442 chore: use vec for encoding
  crates/primitives/src/transaction/eip7702.rs
Labels: C-debt

#9440 test: ensure block reader traits are object safe
  crates/storage/storage-api/src/block_id.rs
Labels: C-test

#9447 chore: resolve new clippy error w/ suggested fix part 2
  crates/primitives/src/transaction/compat.rs
Labels: C-debt

#9365 feat: tree hook for persisting blocks
  Cargo.lock
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/persistence.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-blockchain-tree

#9419 feat(prune, stages): prune pipeline stage
  Cargo.lock
  crates/cli/commands/src/prune.rs
  crates/config/src/config.rs
  crates/consensus/beacon/src/engine/hooks/prune.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/engine/tree/src/persistence.rs
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/mod.rs
  crates/prune/prune/src/builder.rs
  crates/prune/prune/src/pruner.rs
  crates/prune/types/src/target.rs
  crates/stages/api/src/error.rs
  crates/stages/api/src/pipeline/mod.rs
  crates/stages/api/src/pipeline/set.rs
  crates/stages/stages/Cargo.toml
  crates/stages/stages/src/sets.rs
  crates/stages/stages/src/stages/mod.rs
  crates/stages/stages/src/stages/prune.rs
  crates/stages/types/src/id.rs
Labels: C-enhancement, A-staged-sync, A-pruning

#9459 fix: accept concurrent prometheus connections
  crates/node/core/src/metrics/prometheus_exporter.rs
Labels: C-bug, C-enhancement, A-observability

#9446 chore(pruner): remove deletion limit per block, make it per run
  crates/chainspec/src/spec.rs
  crates/cli/commands/src/prune.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/engine/tree/src/persistence.rs
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/mod.rs
  crates/prune/prune/src/builder.rs
  crates/prune/prune/src/pruner.rs
  crates/prune/types/src/limiter.rs
  crates/stages/api/src/pipeline/mod.rs
  crates/stages/stages/src/stages/prune.rs
Labels: C-debt, A-pruning

#9437 chore: replace base fee constants with native const
  crates/chainspec/src/constants.rs
  crates/chainspec/src/constants/optimism.rs
  crates/chainspec/src/spec.rs
Labels: C-debt

#9432 feat: add remove_block_and_execution_range
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/block.rs
Labels: C-enhancement, A-db

#9469 feat(rpc/otterscan): change BlockId to u64 in has_code
  crates/rpc/rpc-api/src/otterscan.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/otterscan.rs
Labels: A-rpc

#9468 fix(chainspec): set dao_fork_support=true for mainnet,sepolia,holesky
  crates/chainspec/src/spec.rs
Labels: C-enhancement

#9463 chore: use create_test_provider_factory in more places
  crates/prune/prune/src/pruner.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: C-enhancement, A-db, C-test

#9471 feat(net/peer): simple support rank higher with static peer
  crates/net/network/src/peers.rs
Labels: C-enhancement, A-networking

#9194 test(revm): unit test `insert_post_block_withdrawals_balance_increments`
  Cargo.lock
  crates/revm/Cargo.toml
  crates/revm/src/state_change.rs
Labels: C-test

#9473 feat: add `max_gas_limit` to `ChainSpec`
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/chainspec/src/constants.rs
  crates/chainspec/src/spec.rs
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/engine/tree/src/backfill.rs
  crates/engine/tree/src/download.rs
  crates/ethereum/payload/src/lib.rs
  crates/optimism/payload/src/builder.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-api/src/helpers/state.rs
  crates/rpc/rpc/src/eth/core.rs
  crates/rpc/rpc/src/eth/helpers/state.rs
  crates/transaction-pool/src/validate/eth.rs
  examples/bsc-p2p/src/chainspec.rs
  examples/polygon-p2p/src/chain_cfg.rs
Labels: C-enhancement, A-consensus

#9443 replaced generic to box dyn
  crates/net/network/src/builder.rs
  crates/net/network/src/config.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/tests/it/connect.rs
  crates/node/builder/src/builder/mod.rs
  crates/node/core/src/cli/config.rs
Labels: A-networking

#9305 feat(trie): reimplement in-memory trie cursors
  crates/trie/trie/src/forward_cursor.rs
  crates/trie/trie/src/trie_cursor/database_cursors.rs
  crates/trie/trie/src/trie_cursor/in_memory.rs
  crates/trie/trie/src/trie_cursor/mod.rs
  crates/trie/trie/src/trie_cursor/noop.rs
Labels: C-enhancement, A-trie

#9480 chore: some no-std touchups
  crates/primitives/src/transaction/eip1559.rs
  crates/primitives/src/transaction/eip2930.rs
  crates/primitives/src/transaction/eip7702.rs
  crates/primitives/src/transaction/legacy.rs
Labels: C-debt

#9481 feat(primitives): re-export EIP-7702 types
  crates/primitives/src/eip7702.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/eip7702.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-enhancement, A-sdk

#9435 feat: route commands to correct persistence service
  crates/engine/tree/src/database.rs
  crates/engine/tree/src/lib.rs
  crates/engine/tree/src/persistence.rs
  crates/engine/tree/src/static_files.rs
  crates/engine/tree/src/test_utils.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-db, A-blockchain-tree

#9483 replace optimism error variant with Other
  crates/rpc/rpc-eth-types/src/error.rs
Labels: A-rpc

#9467 feat: OP: keep encoded txs in payload attributes
  crates/optimism/payload/src/builder.rs
  crates/optimism/payload/src/payload.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-enhancement, A-op-reth

#9489 chore: rm redundant optimism feature
  crates/primitives/Cargo.toml
  crates/storage/codecs/Cargo.toml
  crates/storage/codecs/derive/Cargo.toml
  crates/storage/codecs/src/alloy/withdrawal.rs
Labels: C-debt, A-op-reth
