Repository paradigmxyz/reth, pull requests merged in 2024-04, with the labels that each got.

#7409 chore(docs): fix database mermaid graph
  docs/design/database.md
Labels: C-docs, A-db

#7075 e2e eth node tests
  .github/workflows/integration.yml
  Cargo.lock
  crates/node-e2e-tests/Cargo.toml
  crates/node-e2e-tests/tests/it/dev.rs
  crates/node-e2e-tests/tests/it/eth.rs
  crates/node-e2e-tests/tests/it/main.rs
  crates/node-e2e-tests/tests/it/test_suite.rs
  crates/payload/builder/src/lib.rs
Labels: C-test

#7407 fix(grafana): time frame
  etc/grafana/dashboards/overview.json
  etc/grafana/dashboards/reth-mempool.json
Labels: A-observability

#7342 fix: shrink_to_fit PrefixSetMut on freeze
  crates/trie/src/prefix_set/mod.rs
Labels: C-bug, A-trie

#7413 feat: add helpers to obtain the engine API client
  crates/node-builder/src/node.rs
  crates/node-e2e-tests/tests/it/eth.rs
Labels: C-enhancement

#7412 fix: check finalized sync target is not zero
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
Labels: C-bug, A-consensus

#7423 chore: move FullProvider trait to reth-provider
  Cargo.lock
  crates/node-api/Cargo.toml
  crates/node-api/src/lib.rs
  crates/node-builder/src/lib.rs
  crates/node-builder/src/node.rs
  crates/storage/provider/src/traits/full.rs
  crates/storage/provider/src/traits/mod.rs
Labels: C-debt

#7422 fix: off by one trace_filter
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-bug, A-rpc

#7426 chore(node-core): unify stage progress log style
  crates/node-core/src/events/node.rs
Labels: C-enhancement, A-staged-sync, A-observability

#7424 fix(static-file): run producer only if passed non-empty targets
  crates/static-file/src/static_file_producer.rs
Labels: A-static-files

#7364 fix: reduce merkle clean_threshold to 5000
  book/run/config.md
  crates/config/src/config.rs
  crates/stages/src/stages/merkle.rs
Labels: C-bug, A-staged-sync, C-perf, A-trie

#7427 fix: use modify specid instead
  crates/revm/src/processor.rs
Labels: A-execution

#7085 feat: use pipeline for `reth stage unwind`
  bin/reth/src/commands/stage/unwind.rs
  crates/primitives/src/static_file/mod.rs
  crates/stages/src/pipeline/mod.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
Labels: C-enhancement, A-staged-sync, A-cli

#7336 feat(discv5): add crate for interfacing reth network and sigp/discv5
  Cargo.lock
  Cargo.toml
  crates/net/discv5/Cargo.toml
  crates/net/discv5/README.md
  crates/net/discv5/src/config.rs
  crates/net/discv5/src/enr.rs
  crates/net/discv5/src/error.rs
  crates/net/discv5/src/filter.rs
  crates/net/discv5/src/lib.rs
  crates/net/discv5/src/metrics.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/net.rs
  crates/rpc/rpc-types/src/net.rs
  crates/rpc/rpc-types/src/peer.rs
  deny.toml
Labels: A-networking, A-discv5

#7262 chore: update kurtosis config in assertoor and book (#7261)
  book/run/private-testnet.md
  etc/assertoor/assertoor-template.yaml
Labels: A-meta

#6958 feat(prune): timeout
  Cargo.lock
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/net/network/src/transactions/mod.rs
  crates/node-builder/src/builder.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/peer.rs
  crates/primitives/src/prune/limiter.rs
  crates/primitives/src/prune/mod.rs
  crates/prune/Cargo.toml
  crates/prune/src/builder.rs
  crates/prune/src/pruner.rs
  crates/prune/src/segments/account_history.rs
  crates/prune/src/segments/headers.rs
  crates/prune/src/segments/mod.rs
  crates/prune/src/segments/receipts.rs
  crates/prune/src/segments/receipts_by_logs.rs
  crates/prune/src/segments/sender_recovery.rs
  crates/prune/src/segments/storage_history.rs
  crates/prune/src/segments/transaction_lookup.rs
  crates/prune/src/segments/transactions.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-enhancement, A-pruning

#7432 perf: replace BytesMut with alloy_rlp::encode
  crates/primitives/src/transaction/mod.rs
  docs/crates/eth-wire.md
Labels: C-debt

#7433 docs: fix broken op spec link
  crates/primitives/src/transaction/optimism.rs
Labels: C-docs

#7337 feat: add dev suffix to version if not on a git tag
  crates/node-core/build.rs
  crates/node-core/src/version.rs
Labels: C-enhancement

#7439 feat: add helper functions to obtain a fully configured evm
  crates/evm/src/lib.rs
Labels: C-enhancement

#7429 fix: use provider for header range on fn block_range
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-bug, A-rpc

#7442 release: v0.2.0-beta.5
  Cargo.lock
  Cargo.toml
Labels: A-meta

#7447 chore: change README.md and release images to beta
  .github/workflows/release.yml
  README.md
  assets/reth-beta.png
Labels: A-meta

#7440 feat: add SequencerClient
  bin/reth/Cargo.toml
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc/src/eth/api/optimism.rs
  crates/rpc/rpc/src/eth/optimism.rs
Labels: C-enhancement, A-op-reth

#7438 feat: move transact and inspect calls to trait
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-enhancement, A-rpc

#7441 fix(pruner): highest pruned block metric
  crates/prune/src/pruner.rs
  etc/grafana/dashboards/overview.json
Labels: C-bug, A-observability, A-pruning

#7431 chore: bump revm+alloy
  Cargo.lock
  Cargo.toml
  crates/primitives/src/log.rs
  crates/rpc/rpc-api/src/eth.rs
  crates/rpc/rpc-api/src/otterscan.rs
  crates/rpc/rpc-types-compat/src/log.rs
  crates/rpc/rpc-types-compat/src/transaction/mod.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/admin.rs
  crates/rpc/rpc-types/src/eth/mod.rs
  crates/rpc/rpc-types/src/lib.rs
  crates/rpc/rpc-types/src/otterscan.rs
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/logs_utils.rs
  crates/rpc/rpc/src/otterscan.rs
Labels: C-debt, A-rpc

#7461 feat(discv5): Grafana panels
  etc/grafana/dashboards/reth-discovery.json
Labels: A-observability

#7377 fix: Add more observability on `stdout` during ETL stages execution
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/tx_lookup.rs
  crates/stages/src/stages/utils.rs
Labels: A-staged-sync, A-observability

#7458 feat(discv5): disable noisy logs
  crates/tracing/src/layers.rs
Labels: A-observability

#7455 chore: display total storage size in Grafana
  crates/node-core/src/metrics/prometheus_exporter.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  etc/grafana/dashboards/overview.json
Labels: A-observability

#7464 feat: add evm-ethereum crate
  Cargo.lock
  Cargo.toml
  crates/evm-ethereum/Cargo.toml
  crates/evm-ethereum/src/lib.rs
  crates/node-ethereum/Cargo.toml
  crates/node-ethereum/src/evm.rs
Labels: C-enhancement, A-execution

#7463 feat: change evm trait bound
  Cargo.lock
  crates/node-core/src/args/rpc_server_args.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/cache/mod.rs
  crates/rpc/rpc/src/lib.rs
Labels: C-enhancement, A-rpc

#7465 chore(tree): accept owned block hash in `make_canonical` instead of ref
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/noop.rs
  crates/blockchain-tree/src/shareable.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/blockchain_tree/mod.rs
  crates/storage/provider/src/providers/mod.rs
Labels: C-debt, A-blockchain-tree

#7467 chore(tree): remove useless oneline methods
  crates/blockchain-tree/src/blockchain_tree.rs
Labels: C-debt, A-blockchain-tree

#7469 chore(tree): refactor `make_canonical`
  crates/blockchain-tree/src/blockchain_tree.rs
Labels: C-debt, A-blockchain-tree

#7470 feat: integrate evm in rpc
  Cargo.lock
  crates/evm/src/lib.rs
  crates/node-optimism/src/evm.rs
  crates/revm/src/test_utils.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  examples/custom-evm/src/main.rs
Labels: C-enhancement, A-rpc

#7468 chore(tree): unify `remove_and_split_chain` method
  crates/blockchain-tree/src/blockchain_tree.rs
Labels: C-debt, A-blockchain-tree

#7462 fix(grafana): warning tx fetcher hashes panel
  etc/grafana/dashboards/reth-mempool.json
Labels: A-observability

#5894 chore(deps): migrate to jsonrpsee 0.22
  Cargo.lock
  Cargo.toml
  crates/node-core/src/args/rpc_server_args.rs
  crates/node-core/src/cli/config.rs
  crates/rpc/ipc/src/server/ipc.rs
  crates/rpc/ipc/src/server/mod.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/error.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/src/metrics.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-builder/tests/it/serde.rs
  crates/rpc/rpc-engine-api/src/error.rs
  crates/rpc/rpc-testing-util/src/debug.rs
  crates/rpc/rpc-testing-util/src/trace.rs
  crates/rpc/rpc-types-compat/src/block.rs
  crates/rpc/rpc-types-compat/src/transaction/mod.rs
  crates/rpc/rpc-types-compat/src/transaction/typed.rs
  crates/rpc/rpc-types/src/eth/transaction/typed.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/fee_history.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/rpc/rpc/src/eth/pubsub.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
  crates/rpc/rpc/src/layers/auth_layer.rs
Labels: A-dependencies

#7480 fix(grafana): reth-mempool
  etc/grafana/dashboards/reth-mempool.json
Labels: A-observability

#7453 E2e improvements
  Cargo.lock
  Cargo.toml
  crates/node-e2e-tests/Cargo.toml
  crates/node-e2e-tests/assets/genesis.json
  crates/node-e2e-tests/src/chain_spec_builder.rs
  crates/node-e2e-tests/src/lib.rs
  crates/node-e2e-tests/src/test_suite.rs
  crates/node-e2e-tests/src/wallet.rs
  crates/node-e2e-tests/tests/it/eth.rs
  crates/node-e2e-tests/tests/it/main.rs
  crates/node-e2e-tests/tests/it/test_suite.rs
Labels: C-enhancement, C-test

#7482 feat: extract optimism sequencer client to node-optimism
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/optimism.rs
  crates/net/network-api/Cargo.toml
  crates/net/network-api/src/lib.rs
  crates/net/network-api/src/noop.rs
  crates/net/network/Cargo.toml
  crates/net/network/src/config.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/node-core/Cargo.toml
  crates/node-optimism/Cargo.toml
  crates/node-optimism/src/lib.rs
  crates/node-optimism/src/node.rs
  crates/node-optimism/src/rpc.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/mod.rs
  crates/rpc/rpc/src/eth/optimism.rs
  crates/rpc/rpc/src/eth/traits.rs
  crates/rpc/rpc/src/layers/auth_layer.rs
Labels: C-debt, A-rpc

#7494 chore: allow transmute annotations
  bin/reth/src/commands/stage/run.rs
  crates/net/eth-wire-types/src/lib.rs
  crates/storage/libmdbx-rs/src/environment.rs
Labels: A-meta

#7502 chore: bump alloy
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc-types/src/lib.rs
  crates/rpc/rpc/src/otterscan.rs
Labels: A-dependencies

#7507 chore: set expiration duration properly
  crates/net/discv4/src/lib.rs
Labels: C-bug, A-networking, A-discv4

#7493 feat: add beacon api headers types
  crates/rpc/rpc-types/src/beacon/events/light_client_optimistic.rs
  crates/rpc/rpc-types/src/beacon/header.rs
  crates/rpc/rpc-types/src/beacon/mod.rs
  crates/rpc/rpc-types/src/beacon/payload.rs
Labels: C-enhancement, A-rpc

#7485 fix: ensure transfer gas estimation succeeds
  crates/rpc/rpc/src/eth/api/call.rs
Labels: C-bug, A-rpc

#7508 chore: remove ethers deps
  Cargo.lock
  Cargo.toml
  crates/net/network/Cargo.toml
  crates/net/network/tests/it/connect.rs
Labels: C-debt, C-test

#7510 chore: use `while` for all `poll_tick()` to make code consistent
  crates/net/discv4/src/lib.rs
Labels: C-debt, A-networking

#7511 feat(tree): disable long read transaction safety on `newPayload`
  crates/blockchain-tree/src/chain.rs
Labels: C-enhancement, A-db, A-blockchain-tree

#7514 feat(node-builder): add `install_exex` to `WithLaunchContext`
  crates/node-builder/src/builder.rs
Labels: C-enhancement, A-sdk, A-exex

#7513 chore: rm unused execute function
  crates/revm/src/optimism/processor.rs
  crates/revm/src/processor.rs
  crates/storage/provider/src/test_utils/executor.rs
  crates/storage/provider/src/traits/executor.rs
Labels: C-debt, A-execution

#7515 chore: fix some warnings
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  crates/net/dns/Cargo.toml
  crates/net/dns/src/lib.rs
  crates/net/eth-wire-types/Cargo.toml
  crates/net/eth-wire-types/src/status.rs
  crates/net/eth-wire/Cargo.toml
  crates/net/eth-wire/src/builder.rs
  crates/net/eth-wire/src/errors/eth.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/test_utils.rs
  crates/net/network-api/Cargo.toml
  crates/net/network-api/src/noop.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/revm/config.rs
  crates/revm/src/test_utils.rs
  crates/trie/Cargo.toml
  crates/trie/src/proof.rs
  examples/custom-evm/Cargo.toml
  examples/custom-evm/src/main.rs
  examples/custom-node/Cargo.toml
  examples/custom-node/src/main.rs
Labels: C-debt

#7517 feat(exex): use unbounded sender for events
  crates/exex/src/context.rs
Labels: C-enhancement, A-exex

#7518 chore: add `asm-keccak` to reth crate docs
  bin/reth/src/lib.rs
Labels: C-docs, A-cli

#7527 feat: integrate evm in OP payload builder
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  crates/node-builder/src/builder.rs
  crates/node-optimism/src/node.rs
  crates/payload/optimism/src/builder.rs
Labels: A-block-building, A-op-reth

#7522 chore: use builtin optimism fn
  crates/node-optimism/src/evm.rs
Labels: C-debt, A-op-reth

#7535 chore(stages): log hash insertion progress as Display string
  crates/stages/src/stages/hashing_account.rs
  crates/stages/src/stages/hashing_storage.rs
  crates/stages/src/stages/tx_lookup.rs
Labels: C-bug, A-staged-sync, A-observability

#7537 chore: bump sse example
  Cargo.lock
  examples/beacon-api-sse/Cargo.toml
Labels: A-dependencies

#7538 chore: bump jsonrpsee 0.22.4
  Cargo.lock
Labels: A-dependencies

#7533 refactor: launch disc services concurrently
  crates/net/network/src/discovery.rs
Labels: C-enhancement, A-networking

#7512 chore: use alloy nodeinfo
  Cargo.lock
  Cargo.toml
  crates/net/network-api/src/lib.rs
  crates/net/network-api/src/noop.rs
  crates/net/network/src/manager.rs
  crates/primitives/src/chain/spec.rs
  crates/rpc/rpc-api/src/admin.rs
  crates/rpc/rpc-types-compat/src/block.rs
  crates/rpc/rpc-types/src/lib.rs
  crates/rpc/rpc-types/src/net.rs
  crates/rpc/rpc/src/admin.rs
  crates/rpc/rpc/src/eth/api/optimism.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/otterscan.rs
Labels: C-enhancement, A-rpc

#7539 feat: add PeersInfo::local_enr
  Cargo.lock
  crates/net/network-api/Cargo.toml
  crates/net/network-api/src/lib.rs
  crates/net/network-api/src/noop.rs
  crates/net/network/src/network.rs
Labels: C-enhancement, A-networking

#7541 Update revm-inspectors link
  docs/repo/layout.md
Labels: C-docs

#7534 Update iai benchmarks to use iai-callgrind
  .github/workflows/bench.yml
  Cargo.lock
  crates/storage/db/Cargo.toml
  crates/storage/db/benches/iai.rs
Labels: C-benchmark

#7543 feat: set local enr in nodeInfo
  crates/rpc/rpc/src/admin.rs
Labels: C-enhancement, A-rpc

#7523 chore: reserve an upper bound in `ReusableDecompressor`
  crates/primitives/src/compression/mod.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-enhancement, A-db

#7545 perf(pool): send blob sidecars as `Arc` to listeners
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/traits.rs
Labels: C-perf, A-tx-pool

#7544 ci: fix iai job
  .github/scripts/compare_iai.sh
  .github/workflows/bench.yml
Labels: C-benchmark

#7428 Feat: support for engine api over ipc
  crates/node-builder/src/node.rs
  crates/node-builder/src/rpc.rs
  crates/node-core/src/args/rpc_server_args.rs
  crates/node-e2e-tests/tests/it/eth.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/constants.rs
Labels: A-rpc

#7257 feat: add `reth db checksum <TABLE>` command
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/commands/db/checksum.rs
  bin/reth/src/commands/db/mod.rs
Labels: C-enhancement, A-db, A-cli

#7562 ci: fix iai benches the sequel
  .github/workflows/bench.yml
Labels: C-bug, A-meta

#7563 chore: add `reth-exex` to CODEOWNERS
  CODEOWNERS
Labels: A-meta

#7566 feat(storage): non-optional committed chain in CanonStateNotification
  crates/payload/basic/src/lib.rs
  crates/rpc/rpc/src/eth/api/fee_history.rs
  crates/rpc/rpc/src/eth/cache/mod.rs
  crates/rpc/rpc/src/eth/pubsub.rs
  crates/storage/provider/src/traits/chain.rs
Labels: C-enhancement, A-db

#7567 chore: relax stateprovider db trait bound
  crates/revm/src/database.rs
Labels: A-db

#7568 chore: rm unused fn
  crates/revm/src/processor.rs
Labels: C-debt

#7569 chore: make EVM processor function private
  crates/revm/src/processor.rs
Labels: C-debt, A-execution

#7340 feat: exex manager
  Cargo.lock
  crates/exex/Cargo.toml
  crates/exex/src/lib.rs
  crates/exex/src/manager.rs
  crates/node-builder/Cargo.toml
  crates/node-builder/src/builder.rs
  crates/node-builder/src/exex.rs
  crates/node-ethereum/tests/it/exex.rs
Labels: C-enhancement, A-exex

#7556 feat(examples): OP Stack bridge stats ExEx
  Cargo.lock
  Cargo.toml
  crates/exex/src/event.rs
  crates/storage/provider/src/chain.rs
  examples/Cargo.toml
  examples/cli-extension-event-hooks/Cargo.toml
  examples/exex/op-bridge/Cargo.toml
  examples/exex/op-bridge/l1_standard_bridge_abi.json
  examples/exex/op-bridge/src/main.rs
Labels: A-exex, C-example

#7565 feat(examples): minimal viable ExEx
  Cargo.lock
  Cargo.toml
  examples/exex/minimal/Cargo.toml
  examples/exex/minimal/src/main.rs
Labels: A-exex, C-example

#7575 fix: disable long read transaction safety in db diff
  bin/reth/src/commands/db/diff.rs
Labels: C-bug, A-db, A-cli

#7577 chore: move tree setup to builder
  Cargo.lock
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/node-builder/src/builder.rs
  crates/node-core/Cargo.toml
  crates/node-core/src/node_config.rs
Labels: C-debt

#7583 chore(tasks): comment formatting
  crates/tasks/src/metrics.rs
Labels: C-debt

#7585 chore: clean up some errors
  crates/interfaces/src/provider.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/stages/src/stages/execution.rs
Labels: C-debt

#7555 feat(op): import below bedrock blocks
  bin/reth/Cargo.toml
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/mod.rs
  crates/net/downloaders/src/file_client.rs
  crates/node-core/src/args/utils.rs
  crates/primitives/res/genesis/optimism.json
  crates/primitives/src/chain/mod.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/signature.rs
Labels: C-enhancement, A-cli, A-op-reth

#7588 chore: move pipeline setup to node-builder
  Cargo.lock
  crates/node-builder/Cargo.toml
  crates/node-builder/src/builder.rs
  crates/node-builder/src/lib.rs
  crates/node-builder/src/setup.rs
  crates/node-core/Cargo.toml
  crates/node-core/src/node_config.rs
Labels: C-debt

#7581 feat: introduce reth db stats --checksum
  bin/reth/src/commands/db/checksum.rs
  bin/reth/src/commands/db/stats.rs
Labels: C-enhancement, A-db, A-cli

#7590 docs(docker): improper docker volume path causes data loss
  book/installation/docker.md
Labels: C-docs

#7591 fix(cmd): get tip block
  crates/net/downloaders/src/file_client.rs
Labels: C-bug, A-cli

#7593 chore: rm node api deps
  Cargo.lock
  crates/consensus/auto-seal/Cargo.toml
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/auto-seal/src/task.rs
  crates/revm/Cargo.toml
  crates/revm/src/factory.rs
  crates/revm/src/optimism/processor.rs
  crates/revm/src/processor.rs
  crates/revm/src/test_utils.rs
Labels: C-debt, A-sdk

#7597 chore(node-api): move `FullNodeComponents` from builder
  Cargo.lock
  bin/reth/src/lib.rs
  crates/node-api/Cargo.toml
  crates/node-api/src/node.rs
  crates/node-builder/src/builder.rs
  crates/node-builder/src/components/builder.rs
  crates/node-builder/src/components/mod.rs
  crates/node-builder/src/components/traits.rs
  crates/node-builder/src/handle.rs
  crates/node-builder/src/hooks.rs
  crates/node-builder/src/node.rs
  crates/node-builder/src/rpc.rs
  crates/node-e2e-tests/tests/it/dev.rs
  crates/node-ethereum/Cargo.toml
  crates/node-ethereum/tests/it/builder.rs
  crates/node-optimism/tests/it/builder.rs
Labels: C-debt, A-sdk

#7595 fix(test): add missing dep
  crates/net/downloaders/Cargo.toml
Labels: C-bug

#7592 fix(cli): import cmd logs
  bin/reth/src/commands/import.rs
Labels: C-enhancement, A-observability, A-cli

#7602 fix(cli): bug fix import cmd
  bin/reth/src/commands/import.rs
  crates/net/downloaders/src/file_client.rs
Labels: C-bug, A-cli

#7601 refactor(exex): use async fns in op bridge example
  examples/exex/op-bridge/src/main.rs
Labels: C-debt, A-exex, C-example

#7402 feat: Implement BlockReader::block_with_senders_range
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/block.rs
Labels: C-enhancement, A-db

#7573 feat(exex): add `Pool` to `ExExContext`
  crates/exex/src/context.rs
  crates/node-builder/src/builder.rs
  crates/node-builder/src/exex.rs
  crates/node-ethereum/tests/it/exex.rs
  examples/exex/minimal/src/main.rs
  examples/exex/op-bridge/src/main.rs
Labels: C-enhancement, A-exex

#7606 feat(rpc): add block timestamp to logs
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/logs_utils.rs
Labels: C-enhancement, A-rpc

#7616 chore(deps): bump alloy+evm inspectors
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: A-dependencies

#7495 feat(rpc): add anvil and hardhat and ganache trait bindings
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc-api/src/anvil.rs
  crates/rpc/rpc-api/src/ganache.rs
  crates/rpc/rpc-api/src/hardhat.rs
  crates/rpc/rpc-api/src/lib.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/lib.rs
Labels: A-rpc

#7554 Implement compact codec for alloy eip access_list
  Cargo.lock
  crates/primitives/src/transaction/access_list.rs
  crates/storage/codecs/Cargo.toml
  crates/storage/codecs/src/alloy/access_list.rs
  crates/storage/codecs/src/alloy/log.rs
  crates/storage/codecs/src/alloy/mod.rs
  crates/storage/codecs/testdata/access_list_compact.json
Labels: C-enhancement, C-debt

#7617 use alloy's BaseFeeParams (2)
  crates/primitives/src/basefee.rs
  crates/primitives/src/chain/mod.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/constants/mod.rs
  crates/primitives/src/header.rs
Labels: C-enhancement, C-debt

#7624 chore: simplify DisplayBlocksChain
  crates/net/downloaders/src/file_client.rs
  crates/storage/provider/src/chain.rs
Labels: A-observability

#7632 feat: add a metric for the number of ExEx's on a node
  crates/exex/src/manager.rs
Labels: A-observability, A-exex

#7633 fix: crash ExEx task when the ExEx future returns
  crates/node-builder/src/builder.rs
Labels: C-enhancement, A-exex

#7634 chore(discv5): add comments for op bootnodes
  crates/net/discv5/src/config.rs
Labels: C-docs

#7620 fix(cli): import cmd boundaries
  bin/reth/src/commands/import.rs
Labels: C-bug, A-cli

#7636 feat: replace reth native AccessList type
  crates/primitives/src/transaction/access_list.rs
  crates/primitives/src/transaction/mod.rs
  crates/rpc/rpc-types-compat/src/transaction/typed.rs
Labels: C-debt

#7638 docs(book): update node size numbers
  book/installation/installation.md
  book/run/pruning.md
Labels: C-docs

#7643 Implement `From<Block>` for `BlockBody`
  crates/primitives/src/block.rs
Labels: C-enhancement

#7622 fix(op): headers above merge
  crates/consensus/beacon-core/Cargo.toml
  crates/consensus/beacon-core/src/lib.rs
  crates/consensus/beacon/Cargo.toml
  crates/primitives/src/chain/spec.rs
Labels: C-bug, A-consensus, A-op-reth

#7613 ci: automatically set pr labels upon open
  .github/scripts/label_pr.js
  .github/workflows/label-pr.yml
Labels: A-meta

#7574 feat(op): chunked chain import
  Cargo.lock
  bin/reth/src/commands/import.rs
  crates/net/downloaders/Cargo.toml
  crates/net/downloaders/src/file_client.rs
  crates/net/downloaders/src/file_codec.rs
Labels: A-cli, A-op-reth

#7639 refactor: remove unused codecs
  crates/storage/codecs/Cargo.toml
  crates/storage/codecs/README.md
  crates/storage/codecs/derive/Cargo.toml
  crates/storage/codecs/derive/src/lib.rs
Labels: C-debt, A-db

#7652 refactor(exex): make finished height an enum
  crates/exex/src/manager.rs
Labels: C-enhancement, C-debt, A-exex

#7655 docs(discv5): additional info regarding requested enrs on bootstrap
  crates/net/discv5/src/lib.rs
Labels: C-docs, A-discv5

#7660 Convert `Header` and `Block` rpc to primitives
  Cargo.lock
  Cargo.toml
  crates/primitives/src/block.rs
  crates/primitives/src/header.rs
  crates/primitives/src/withdrawal.rs
  crates/rpc/rpc/src/txpool.rs
Labels: C-debt, A-rpc

#7654 fix: check if regexp match is null in label-pr script
  .github/scripts/label_pr.js
Labels: C-bug

#7641 refactor: replace ```calculate_next_block_base_fee``` with alloy's builtin function
  crates/primitives/src/basefee.rs
  crates/primitives/src/header.rs
  crates/rpc/rpc/src/eth/api/fee_history.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/api/server.rs
Labels: C-debt

#7663 feat(discv5): add tracing
  crates/net/discv5/src/lib.rs
Labels: A-observability, A-discv5

#7669 fix(tree): overlapping parent block hashes
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/storage/provider/src/test_utils/blocks.rs
Labels: C-bug, A-blockchain-tree

#7497 chore: convert FromRecoveredTransaction into TryFromRecoveredTransaction
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/error.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/tx_type.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/test_utils/gen.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
Labels: C-debt, A-tx-pool

#7670 refactor(exex, primitives): move finished exex height to primitives
  crates/exex/src/manager.rs
  crates/primitives/src/exex/mod.rs
  crates/primitives/src/lib.rs
Labels: C-debt, A-exex

#7671 chore: extract evm processor batch handling
  crates/revm/src/batch.rs
  crates/revm/src/lib.rs
  crates/revm/src/optimism/processor.rs
  crates/revm/src/processor.rs
Labels: C-debt, A-execution

#7672 chore: move BlockExecutorStats
  crates/revm/src/batch.rs
  crates/revm/src/processor.rs
  crates/storage/provider/src/traits/executor.rs
  crates/storage/provider/src/traits/mod.rs
Labels: C-debt

#7664 feat(discv5): add enr to tracing
  crates/net/discv5/src/lib.rs
Labels: A-observability, A-op-reth

#7665 chore: include block num and hash in bctree debug logs
  crates/blockchain-tree/src/blockchain_tree.rs
Labels: C-enhancement, A-observability, A-blockchain-tree

#7675 chore(tree): `CanonicalError::is_block_hash_not_found`
  crates/consensus/beacon/src/engine/mod.rs
  crates/interfaces/src/blockchain_tree/error.rs
Labels: C-debt, A-blockchain-tree

#7651 refactor: Drop reth_primitives::Log
  crates/interfaces/src/test_utils/generators.rs
  crates/net/eth-wire-types/src/receipts.rs
  crates/primitives/src/log.rs
  crates/primitives/src/proofs.rs
  crates/primitives/src/receipt.rs
  crates/primitives/src/revm/compat.rs
  crates/rpc/rpc-types-compat/src/log.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/logs_utils.rs
  crates/storage/provider/src/test_utils/blocks.rs
  examples/db-access.rs
  examples/exex/op-bridge/src/main.rs
Labels: C-debt

#7676 chore(engine): `BeaconConsensusEngine::current_engine_hook_context`
  crates/consensus/beacon/src/engine/hooks/controller.rs
  crates/consensus/beacon/src/engine/hooks/mod.rs
  crates/consensus/beacon/src/engine/hooks/prune.rs
  crates/consensus/beacon/src/engine/hooks/static_file.rs
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#7678 feat: add missing hardfork convenience fns
  crates/primitives/src/chain/spec.rs
Labels: C-enhancement

#7657 chore: move optimism bootnodes to `reth-primitives`
  crates/net/discv5/src/config.rs
  crates/net/network/src/config.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/net.rs
Labels: A-networking, A-op-reth

#7682 chore: flatten node-api dep
  Cargo.lock
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/engine/handle.rs
  crates/consensus/beacon/src/engine/message.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/node-core/Cargo.toml
  crates/node-core/src/args/rpc_server_args.rs
  crates/node-core/src/engine_api_store.rs
  crates/payload/basic/Cargo.toml
  crates/payload/basic/src/lib.rs
  crates/payload/optimism/Cargo.toml
  crates/payload/optimism/src/builder.rs
  crates/payload/optimism/src/payload.rs
  crates/rpc/rpc-api/Cargo.toml
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/error.rs
Labels: C-debt, A-dependencies

#7656 chore(node): unify the format of command args
  book/cli/reth/node.md
  crates/node-core/src/args/rpc_server_args.rs
  crates/node-core/src/args/txpool_args.rs
Labels: A-cli

#7685 chore: remove DOS line endings from basefee.rs
  crates/primitives/src/basefee.rs
Labels: A-utils

#7686 feat: add native compact impl for alloy TxKind
  crates/storage/codecs/src/alloy/log.rs
  crates/storage/codecs/src/alloy/mod.rs
  crates/storage/codecs/src/alloy/txkind.rs
Labels: C-enhancement, C-debt

#7688 fix: add enable missing arbitrary feature
  crates/primitives/Cargo.toml
Labels: C-test, A-meta

#7684 fix(discv5): remove todo
  crates/net/network/src/config.rs
Labels: C-debt

#7677 chore(engine): dedup consistent forkchoice state check
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#7646 storage: fixes behaviour of cursor delete_current on start item
  crates/storage/db/src/abstraction/cursor.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: C-bug, A-db

#7658 fix(docker): Add support for RUSTFLAGS and feature flags in Dockerfile
  Dockerfile
Labels: C-enhancement, O-docker

#7693 test: add `test_requests_timeout()` for disv4
  crates/net/discv4/src/lib.rs
Labels: C-test

#7694 feat: add Prague hardfork variant
  crates/ethereum-forks/src/hardfork.rs
Labels: C-enhancement

#7699 fix: check for genesis block on pool validator init
  crates/node-optimism/src/txpool.rs
  crates/revm/src/optimism/mod.rs
Labels: A-op-reth

#7692 chore(engine): refactor pipeline outcome processing
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#7701 chore: bump alloy
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: A-dependencies

#7703 chore(engine): inline `update_tree_on_finished_pipeline` method
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#7704 chore(engine): refactor sync target determination on failed fcu
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#7689 fix: disable read timeout for tx in db list
  bin/reth/src/commands/db/list.rs
Labels: C-bug, A-db, A-cli
