Repository paradigmxyz/reth, pull requests merged in 2024-08, with the labels that each got.

#9968 fix: also ignore nonce in eth_estimate
  crates/rpc/rpc-eth-api/src/helpers/call.rs
Labels: C-bug, A-rpc

#9967 fix: treat maxfeepergas 0 as missing
  crates/rpc/rpc-eth-types/src/revm_utils.rs
Labels: C-bug, A-rpc

#9973 doc: replace expired example
  docs/design/metrics.md
Labels: C-docs

#9969 fix: remove persisted blocks properly
  crates/engine/tree/src/tree/mod.rs
Labels: C-bug

#9971 feat: include block number in input
  bin/reth-bench/src/bench/new_payload_fcu.rs
  bin/reth-bench/src/bench/output.rs
Labels: C-enhancement, A-observability

#9938 feat: Add OP cli flag to opt-in into discv4 discovery
  book/run/optimism.md
  crates/optimism/node/src/args.rs
  crates/optimism/node/src/node.rs
Labels: A-op-reth

#9984 chore(net): Remove dependency `reth-network-p2p` -> `reth-network-types`
  Cargo.lock
  crates/net/network-types/Cargo.toml
  crates/net/network-types/src/lib.rs
  crates/net/network-types/src/peers/mod.rs
  crates/net/p2p/Cargo.toml
  crates/net/p2p/src/error.rs
  crates/net/p2p/src/lib.rs
  crates/net/p2p/src/reputation.rs
Labels: C-debt, A-networking

#9985 chore(trie): move `PrefixSetLoader` to db crate
  crates/trie/db/src/lib.rs
  crates/trie/db/src/prefix_set.rs
  crates/trie/db/src/state.rs
  crates/trie/trie/src/prefix_set.rs
Labels: C-debt, A-trie

#9915 feat(trie): expose trie witness on proof provider
  crates/chain-state/src/in_memory.rs
  crates/chain-state/src/memory_overlay.rs
  crates/evm/execution-errors/src/trie.rs
  crates/revm/src/test_utils.rs
  crates/rpc/rpc-eth-types/src/cache/db.rs
  crates/storage/errors/src/provider.rs
  crates/storage/provider/src/providers/bundle_state_provider.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/macros.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/storage-api/src/trie.rs
Labels: C-enhancement, A-trie

#9988 typo: fix typo in `best` tx pool doc
  crates/transaction-pool/src/pool/pending.rs
Labels: C-docs

#9990 feat(primitives): improve `no_std` with manual errors and `alloc::String`
  crates/primitives/Cargo.toml
  crates/primitives/src/constants/eip4844.rs
  crates/primitives/src/transaction/access_list.rs
  crates/primitives/src/transaction/error.rs
Labels: C-enhancement

#9943 test: add engine tree test, FCU triggers reorg with all the blocks present
  crates/chain-state/src/test_utils.rs
  crates/engine/tree/src/tree/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
Labels: C-enhancement, C-test

#9992 chore(net, primitives): use `derive_more::Display` more
  crates/net/eth-wire/src/disconnect.rs
  crates/primitives-traits/src/integer_list.rs
Labels: C-debt

#9986 fix: do not truncate blocks to persist
  crates/engine/tree/src/tree/mod.rs
Labels: C-perf

#9966 chore(net): extract `NetworkHandle` methods for launching node to traits
  Cargo.lock
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  crates/cli/commands/src/p2p.rs
  crates/cli/commands/src/stage/run.rs
  crates/e2e-test-utils/src/network.rs
  crates/ethereum/node/src/launch.rs
  crates/net/network-api/src/lib.rs
  crates/net/network-api/src/noop.rs
  crates/net/network-types/Cargo.toml
  crates/net/network-types/src/lib.rs
  crates/net/network-types/src/peers/addr.rs
  crates/net/network-types/src/peers/cmd.rs
  crates/net/network-types/src/peers/config.rs
  crates/net/network-types/src/peers/handle.rs
  crates/net/network-types/src/peers/kind.rs
  crates/net/network-types/src/peers/mod.rs
  crates/net/network-types/src/peers/state.rs
  crates/net/network/src/builder.rs
  crates/net/network/src/cache.rs
  crates/net/network/src/config.rs
  crates/net/network/src/discovery.rs
  crates/net/network/src/error.rs
  crates/net/network/src/eth_requests.rs
  crates/net/network/src/fetch/client.rs
  crates/net/network/src/fetch/mod.rs
  crates/net/network/src/flattened_response.rs
  crates/net/network/src/import.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/listener.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/message.rs
  crates/net/network/src/network.rs
  crates/net/network/src/peers.rs
  crates/net/network/src/protocol.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/conn.rs
  crates/net/network/src/session/handle.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
  crates/net/network/src/test_utils/init.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/src/transactions/config.rs
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
  crates/net/network/tests/it/connect.rs
  crates/net/network/tests/it/multiplex.rs
  crates/net/network/tests/it/requests.rs
  crates/net/network/tests/it/startup.rs
  crates/net/network/tests/it/txgossip.rs
  crates/net/p2p/src/reputation.rs
  crates/node/builder/src/launch/mod.rs
  examples/custom-rlpx-subprotocol/src/main.rs
Labels: C-debt, A-networking

#9996 feat: add has eip7702 transactions
  crates/primitives/src/block.rs
Labels: C-enhancement

#9982 feat(ci): `check_no_std` -> `check_wasm`
  .github/assets/check_no_std.sh
  .github/assets/check_wasm.sh
  .github/workflows/lint.yml
Labels: C-enhancement, A-ci

#9921 chore(sdk): enable referencing network type via `FullNodeComponents::Network`
  Cargo.lock
  bin/reth/src/lib.rs
  crates/cli/commands/src/p2p.rs
  crates/e2e-test-utils/src/lib.rs
  crates/e2e-test-utils/src/network.rs
  crates/e2e-test-utils/src/node.rs
  crates/exex/exex/Cargo.toml
  crates/exex/exex/src/context.rs
  crates/net/network-types/src/lib.rs
  crates/node/api/src/node.rs
  crates/node/builder/src/builder/states.rs
  crates/node/builder/src/components/mod.rs
  crates/node/builder/src/launch/mod.rs
  crates/node/builder/src/node.rs
  crates/node/builder/src/rpc.rs
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/eth/mod.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/admin.rs
  examples/custom-rlpx-subprotocol/src/main.rs
Labels: C-debt, A-sdk

#9249 feat(rpc): `debug_executionWitness`
  Cargo.lock
  crates/rpc/rpc-api/src/debug.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/debug.rs
Labels: C-enhancement, A-rpc, A-trie, S-feedback-wanted

#10008 refactor(trie): remove dependency on `reth-db` and `reth-db-api`
  Cargo.lock
  crates/trie/trie/Cargo.toml
  crates/trie/trie/src/hashed_cursor/mod.rs
Labels: C-debt

#10010 op-reth: Enable eth_getProof inside authrpc
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc/src/engine.rs
Labels: C-enhancement, A-rpc

#10012 chore: downgrade empty blocks to persist trace to debug
  crates/engine/tree/src/tree/mod.rs
Labels: A-observability

#10013 tx-pool: add `Default` impl for `TransactionOrigin`
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#10014 chore: better tree observability
  crates/engine/tree/src/tree/mod.rs
Labels: A-observability

#10001 feat: add tx-level subpool add and remove traces
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-enhancement, A-tx-pool, A-observability

#9722 fix(rpc/trace): trace_filter filting with trace's address
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc-eth-api/src/helpers/spec.rs
  crates/rpc/rpc-testing-util/src/debug.rs
  crates/rpc/rpc-types-compat/src/block.rs
  crates/rpc/rpc/src/trace.rs
Labels: S-blocked, A-rpc

#9989 feat(primitives): `k256` crate fallback for `secp256k1` module
  .github/assets/check_wasm.sh
  Cargo.lock
  Cargo.toml
  crates/ethereum/evm/Cargo.toml
  crates/exex/exex/Cargo.toml
  crates/net/network/Cargo.toml
  crates/primitives/Cargo.toml
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/util.rs
  crates/rpc/rpc-eth-types/Cargo.toml
  crates/rpc/rpc/Cargo.toml
  crates/stages/stages/Cargo.toml
  crates/storage/provider/Cargo.toml
  crates/transaction-pool/Cargo.toml
  testing/testing-utils/Cargo.toml
Labels: C-enhancement

#10020 feat: add method to check prague active at timestamp
  crates/payload/validator/src/lib.rs
Labels: C-enhancement

#10021 chore: use alloy AccessList result
  crates/primitives/src/transaction/access_list.rs
Labels: C-debt

#10022 chore: sort workspace Cargo.toml entries
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#10024 tx-pool: rm constraint for `PoolTransaction`
  crates/net/network/src/transactions/mod.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/ordering.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/mod.rs
Labels: A-tx-pool

#10006 chore(net): move `reth_eth_wire::DisconnectReason` to `reth-eth-wire-types`
  crates/net/eth-wire-types/src/disconnect_reason.rs
  crates/net/eth-wire-types/src/lib.rs
  crates/net/eth-wire/Cargo.toml
  crates/net/eth-wire/src/disconnect.rs
  crates/net/eth-wire/src/errors/p2p.rs
  crates/net/eth-wire/src/lib.rs
Labels: C-debt, A-networking

#10026 feat: add more granular tx propagation logs
  crates/net/network/src/transactions/mod.rs
Labels: C-enhancement, A-tx-pool, A-observability

#10032 deps: bump zstd
  .github/assets/check_wasm.sh
  Cargo.lock
Labels: A-dependencies

#10036 feat: add engine2 Dockerfile
  EngineTwoDockerfile
Labels: C-test, A-blockchain-tree

#10033 feat: add prague check in ExecutionPayloadValidator
  crates/payload/validator/src/lib.rs
Labels: C-enhancement, E-prague

#10040 feat: use BTreemap for block numbers in CanonicalInMemoryState
  crates/chain-state/src/in_memory.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement

#10031 chore: remove expects in persistence task
  Cargo.lock
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/persistence.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-db, A-blockchain-tree

#10042 Added sync stages status to eth_sync
  crates/optimism/rpc/src/eth/mod.rs
  crates/rpc/rpc-eth-api/src/helpers/spec.rs
  crates/rpc/rpc/src/eth/helpers/spec.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/traits/full.rs
Labels: C-enhancement, A-rpc

#9762 implement part of `reth p2p rlpx ping`
  Cargo.lock
  book/SUMMARY.md
  book/cli/SUMMARY.md
  book/cli/reth/p2p.md
  book/cli/reth/p2p/rlpx.md
  book/cli/reth/p2p/rlpx/ping.md
  crates/cli/commands/Cargo.toml
  crates/cli/commands/src/p2p/mod.rs
  crates/cli/commands/src/p2p/rlpx.rs
  crates/net/eth-wire/src/p2pstream.rs
Labels: A-cli

#10039 feat: improve download observability
  crates/engine/tree/src/chain.rs
  crates/engine/tree/src/download.rs
Labels: A-observability

#10049 chore: replace unreachable error variant
  crates/rpc/rpc-eth-types/src/error.rs
  crates/rpc/rpc-types/src/eth/error.rs
Labels: C-debt, A-rpc

#10003 chore(net): move `reth_network::BlockDownloaderProvider` to `reth-network-api`
  Cargo.lock
  crates/net/network-api/Cargo.toml
  crates/net/network-api/src/downloaders.rs
  crates/net/network-api/src/lib.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/network.rs
  crates/net/p2p/src/lib.rs
Labels: C-debt, A-networking

#10041 fix: start payload builder on already canon head
  crates/engine/tree/src/tree/mod.rs
Labels: C-bug, A-blockchain-tree

#10078 tx-pool: add unit tests for `FinalizedBlockTracker` `update`
  crates/transaction-pool/src/maintain.rs
Labels: A-tx-pool

#10060 Move `PeersHandleProvider` to new module `reth_network_api::test_utils`
  Cargo.lock
  bin/reth/src/lib.rs
  crates/net/network-api/Cargo.toml
  crates/net/network-api/src/lib.rs
  crates/net/network-api/src/test_utils/mod.rs
  crates/net/network-api/src/test_utils/peers_manager.rs
  crates/net/network-types/Cargo.toml
  crates/net/network-types/src/lib.rs
  crates/net/network-types/src/peers/cmd.rs
  crates/net/network-types/src/peers/mod.rs
  crates/net/network/src/builder.rs
  crates/net/network/src/eth_requests.rs
  crates/net/network/src/fetch/client.rs
  crates/net/network/src/fetch/mod.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/peers.rs
  crates/net/network/src/test_utils/testnet.rs
  examples/custom-rlpx-subprotocol/src/main.rs
Labels: C-debt, C-test, A-networking, A-sdk

#10077 workflows: don't run assertoor tests on forks
  .github/workflows/assertoor.yml
Labels: A-meta

#9720 chore: re-add derived 7702 arbitrary impl
  crates/primitives/src/transaction/eip7702.rs
Labels: C-enhancement, C-test

#10050 feat: add api bindings for eth_simulateV1
  crates/rpc/rpc-eth-api/src/core.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
Labels: C-enhancement, A-rpc

#10080 tx-pool: add unit tests for `EthPooledTransaction`
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#10069 fix: deadlock on StaticFileProvider::get_writer
  crates/engine/tree/src/persistence.rs
  crates/storage/provider/src/writer/mod.rs
Labels: C-bug, A-consensus

#10083 feat(evm): support `wasm32-wasip1`
  .github/assets/check_wasm.sh
  crates/evm/execution-types/Cargo.toml
  crates/evm/execution-types/src/chain.rs
  crates/evm/execution-types/src/lib.rs
  crates/evm/src/builder.rs
  crates/evm/src/either.rs
  crates/evm/src/execute.rs
  crates/evm/src/noop.rs
  crates/evm/src/system_calls.rs
Labels: C-enhancement, A-execution

#10087 fix: use recv timeout if persistence task is active
  crates/engine/tree/src/tree/mod.rs
Labels: C-debt

#10085 feat: add metrics for in-memory state
  Cargo.lock
  crates/chain-state/Cargo.toml
  crates/chain-state/src/in_memory.rs
Labels: C-enhancement, A-observability

#10090 chore(rpc): remove parent beacon root from conversion functions
  bin/reth-bench/src/bench/new_payload_fcu.rs
  bin/reth-bench/src/bench/new_payload_only.rs
  crates/ethereum/engine-primitives/src/payload.rs
  crates/optimism/payload/src/payload.rs
  crates/rpc/rpc-engine-api/tests/it/payload.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: C-debt, A-rpc

#10052 Add in-memory block TD lookup support
  crates/chain-state/src/in_memory.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-enhancement

#10092 chore: dont use tmp lock vars
  crates/transaction-pool/src/pool/mod.rs
Labels: C-debt

#10082 test: live sync transition, tree requests required blocks
  crates/engine/tree/src/tree/mod.rs
Labels: C-test

#10063 chore(net): move `FullNetwork` trait into `reth-network-api`
  Cargo.lock
  crates/net/network-api/src/lib.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/network.rs
  crates/node/api/Cargo.toml
  crates/node/api/src/node.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/components/mod.rs
Labels: C-debt, A-networking, A-sdk

#10095 fix: ensure we're skipping invalid tx kinds
  crates/optimism/payload/src/builder.rs
Labels: C-bug, A-op-reth

#10093 chore: add additional traces for promoted txs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: A-observability

#10062 chore(net): Move `reth_network::NetworkEvents` into `reth-network-api`
  Cargo.lock
  bin/reth/src/commands/debug_cmd/execution.rs
  crates/e2e-test-utils/src/network.rs
  crates/ethereum/node/src/launch.rs
  crates/net/network-api/Cargo.toml
  crates/net/network-api/src/events.rs
  crates/net/network-api/src/lib.rs
  crates/net/network/benches/bench.rs
  crates/net/network/src/discovery.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/message.rs
  crates/net/network/src/network.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
  crates/net/network/tests/it/big_pooled_txs_req.rs
  crates/net/network/tests/it/connect.rs
  crates/net/network/tests/it/requests.rs
  crates/net/network/tests/it/session.rs
  crates/net/network/tests/it/txgossip.rs
  crates/node/api/Cargo.toml
  crates/node/api/src/node.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/components/mod.rs
  crates/node/builder/src/launch/mod.rs
  crates/rpc/rpc/Cargo.toml
  examples/bsc-p2p/src/main.rs
  examples/network/src/main.rs
  examples/polygon-p2p/src/main.rs
Labels: C-debt, A-networking

#10101 feat: enable asm-keccak on more platforms
  Cargo.lock
  Makefile
Labels: C-perf, A-meta

#10105 fix: use in memory state for state_by_hash
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-bug, A-consensus, A-db, A-blockchain-tree

#10112 chore: rm redundant (
  crates/engine/tree/src/persistence.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-debt

#10113 perf: spawn eth orchestrator as regular task
  crates/ethereum/node/src/launch.rs
Labels: C-perf

#10099 dep: rm unused dependencies
  Cargo.lock
  crates/chainspec/Cargo.toml
  crates/consensus/beacon/Cargo.toml
  crates/net/discv4/Cargo.toml
  crates/optimism/evm/Cargo.toml
  crates/payload/builder/Cargo.toml
  crates/primitives/Cargo.toml
  crates/rpc/rpc-layer/Cargo.toml
  crates/rpc/rpc-types/Cargo.toml
  crates/storage/db-api/Cargo.toml
  crates/trie/common/Cargo.toml
Labels: A-dependencies

#10114 fix: validate header against parent in engine2
  crates/chain-state/src/test_utils.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-bug, A-consensus, A-blockchain-tree

#10117 feat: Support custom EvmConfig for ethereumpayload builder
  crates/ethereum/node/src/node.rs
  examples/custom-evm/src/main.rs
Labels: C-enhancement

#10119 update op-reth docs for discv4 option
  book/run/optimism.md
Labels: C-docs

#10120 chore(engine): enable clippy checks
  crates/engine/tree/src/download.rs
  crates/engine/tree/src/engine.rs
  crates/engine/tree/src/lib.rs
  crates/engine/tree/src/persistence.rs
  crates/engine/tree/src/test_utils.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-debt, A-ci

#10125 feat: add EngineApi metrics
  crates/engine/tree/src/tree/metrics.rs
  crates/engine/tree/src/tree/mod.rs
Labels: A-observability

#10074 remove pending block support from OpEthApi
  crates/optimism/rpc/src/eth/pending_block.rs
Labels: D-good-first-issue, A-rpc, A-op-reth

#10121 typo: replace [BlockId] by [`BlockId`]
  crates/storage/storage-api/src/block.rs
  crates/storage/storage-api/src/block_id.rs
  crates/storage/storage-api/src/state.rs
Labels: C-docs

#10128 feat: add EngineApiKind enum
  crates/engine/tree/src/engine.rs
Labels: C-enhancement

#10135 docs: misc engine docs
  crates/engine/tree/src/engine.rs
Labels: C-docs

#10122 chore: release 1.0.4
  Cargo.lock
  Cargo.toml
Labels: A-meta

#10136 chore: remove trait EngineApiTreeHandler
  crates/engine/tree/src/tree/mod.rs
Labels: C-debt

#10140 chore: rename EngineApiTreeHandler
  crates/engine/tree/src/tree/mod.rs
  crates/ethereum/engine/src/service.rs
Labels: C-debt

#10137 fix: use actual latest state for BlockchainProvider2
  crates/chain-state/src/memory_overlay.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-bug, A-consensus, A-db, A-blockchain-tree

#10133 chore: ensure persistence receiver is dropped
  crates/engine/tree/src/tree/mod.rs
Labels: C-bug

#10138 Check features powerset for `reth-primitives`
  Cargo.lock
  Makefile
  crates/primitives/Cargo.toml
  crates/primitives/src/alloy_compat.rs
  crates/primitives/src/constants/eip4844.rs
  crates/primitives/src/transaction/compat.rs
  crates/primitives/src/transaction/optimism.rs
Labels: C-enhancement

#10144 feat: ensure consistent forkchoice state always
  crates/engine/tree/src/tree/mod.rs
Labels: C-bug, A-consensus, A-blockchain-tree

#10146 chore: remove clippy::manual_unwarp_or_default
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
Labels: C-debt

#10127 feat: add header to stage command
  crates/cli/commands/src/stage/run.rs
Labels: C-enhancement

#10148 feat: keep sender in tree task
  crates/engine/tree/src/tree/mod.rs
  crates/ethereum/engine/src/service.rs
Labels: C-enhancement

#10051 feat: add `--engine.experimental` flag to enable engine2
  bin/reth/Cargo.toml
  bin/reth/src/engine2.rs
  bin/reth/src/main.rs
  book/cli/reth/node.md
Labels: C-enhancement, S-blocked

#10150 fix: only use tags if they have been set
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/externals.rs
  crates/chain-state/src/chain_info.rs
  crates/cli/commands/src/stage/unwind.rs
  crates/stages/api/src/pipeline/mod.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/traits/finalized_block.rs
Labels: C-bug, A-rpc, A-db, A-blockchain-tree

#10151 chore: remove EngineTwoDockerfile
  EngineTwoDockerfile
Labels: C-debt, A-blockchain-tree, O-docker

#10142 Add CI lint check using cargo hack for checking features powerset
  .github/workflows/lint.yml
Labels: A-meta

#10152 fix: use in memory state for state_by_block_number_or_tag
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/storage-api/src/state.rs
Labels: C-bug, A-rpc, A-db, A-blockchain-tree

#10147 feat: make EngineApiRequestHandler generic over request
  crates/engine/tree/src/engine.rs
  crates/ethereum/engine/src/service.rs
Labels: C-enhancement

#10161 feat: add executed block to built payload trait
  Cargo.lock
  crates/payload/primitives/Cargo.toml
  crates/payload/primitives/src/traits.rs
Labels: C-enhancement

#10163 feat: add stream helper types
  Cargo.lock
  crates/payload/builder/Cargo.toml
  crates/payload/builder/src/events.rs
Labels: C-enhancement

#10158 feat: introduce EngineApiRequest type
  crates/engine/tree/src/engine.rs
  crates/engine/tree/src/tree/mod.rs
  crates/ethereum/engine/src/service.rs
Labels: C-enhancement

#10162 feat: integrate executed block into OP built payload
  Cargo.lock
  crates/optimism/payload/Cargo.toml
  crates/optimism/payload/src/builder.rs
  crates/optimism/payload/src/payload.rs
Labels: C-enhancement

#10168 feat: support ms for --builder.interval
  book/cli/reth/node.md
  crates/cli/util/src/lib.rs
  crates/cli/util/src/parsers.rs
  crates/node/core/src/args/payload_builder.rs
Labels: C-enhancement, A-cli

#10166 fix: dont reset build interval when block finished
  crates/payload/basic/src/lib.rs
Labels: C-bug, C-enhancement, C-perf

#10171 docs: add spec docs and todo for OP
  crates/engine/tree/src/tree/mod.rs
Labels: C-docs

#10170 feat: add error tracing when persistence service fails
  crates/engine/tree/src/persistence.rs
Labels: C-enhancement, A-db, A-observability

#10177 fix: reset auth list in txenv on non-7702 txs
  crates/primitives/src/transaction/compat.rs
Labels: C-bug, E-prague

#10178 chore: build in --debug mode for update-book-cli
  Makefile
Labels: A-meta

#10175 chore: Replace `reth-provider` dependency for `reth-eth-types` with direct dependencies
  Cargo.lock
  crates/chainspec/Cargo.toml
  crates/chainspec/src/lib.rs
  crates/chainspec/src/spec.rs
  crates/rpc/rpc-eth-types/Cargo.toml
  crates/rpc/rpc-eth-types/src/builder/ctx.rs
  crates/rpc/rpc-eth-types/src/cache/db.rs
  crates/rpc/rpc-eth-types/src/cache/mod.rs
  crates/rpc/rpc-eth-types/src/fee_history.rs
  crates/rpc/rpc-eth-types/src/gas_oracle.rs
  crates/rpc/rpc-eth-types/src/logs_utils.rs
  crates/rpc/rpc-eth-types/src/pending_block.rs
  crates/storage/provider/src/traits/mod.rs
  crates/storage/provider/src/traits/spec.rs
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/blobstore/tracker.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/task.rs
Labels: C-debt

#10106 feat: add block_body_indices for BlockchainProvider2
  crates/chain-state/src/in_memory.rs
  crates/storage/errors/src/provider.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-bug, A-db, A-blockchain-tree

#10173 feat(engine-util): reorg interceptor
  Cargo.lock
  book/cli/reth/node.md
  crates/engine/util/Cargo.toml
  crates/engine/util/src/engine_store.rs
  crates/engine/util/src/lib.rs
  crates/engine/util/src/reorg.rs
  crates/engine/util/src/skip_fcu.rs
  crates/engine/util/src/skip_new_payload.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/mod.rs
  crates/node/core/src/args/debug.rs
Labels: A-consensus, C-test

#10188 feat: add basic engine2 exec and root perf logs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, C-perf, A-observability, A-blockchain-tree

#10189 feat: use in memory state for header_td
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-bug, A-db, A-blockchain-tree

#10193 chore: allocate for encoded txs
  crates/optimism/node/src/txpool.rs
Labels: C-perf

#10203 Convert pending block to a watch channel
  crates/chain-state/src/in_memory.rs
Labels: C-enhancement

#10196 chore: remove some outdated todos
  crates/net/network/src/config.rs
  crates/optimism/rpc/src/eth/call.rs
Labels: C-debt

#10197 fix: add requests root when converting alloy header
  crates/primitives-traits/src/alloy_compat.rs
Labels: A-rpc, E-prague

#10202 `reth-eth-types`: Do not import `JsInspectorError` by default
  Cargo.toml
  crates/rpc/rpc-eth-api/Cargo.toml
  crates/rpc/rpc-eth-types/Cargo.toml
  crates/rpc/rpc-eth-types/src/error.rs
  crates/rpc/rpc/Cargo.toml
Labels: A-dependencies

#10195 refactor: derive `PartialEq` for `CanonStateNotification`
  crates/chain-state/src/notifications.rs
Labels: C-docs, C-debt

#10190 fix: return only canonical blocks for history_by_* methods
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-bug, A-db, A-blockchain-tree

#10207 Bump tokio version to mitigate default error in `reth-chain-state`
  Cargo.toml
Labels: A-dependencies

#9844 refactor: replace once_cell Lazy with LazyLock
  .github/workflows/lint.yml
  Cargo.lock
  Cargo.toml
  README.md
  clippy.toml
  crates/ethereum-forks/Cargo.toml
  crates/metrics/metrics-derive/Cargo.toml
  crates/metrics/metrics-derive/src/expand.rs
  crates/metrics/metrics-derive/tests/metrics.rs
  crates/node/metrics/Cargo.toml
  crates/node/metrics/src/recorder.rs
  crates/primitives/Cargo.toml
  crates/trie/db/Cargo.toml
  crates/trie/db/tests/proof.rs
  crates/trie/trie/Cargo.toml
  examples/manual-p2p/Cargo.toml
  examples/manual-p2p/src/main.rs
Labels: C-debt

#10210 fix: properly modify spec id for evm
  crates/evm/src/lib.rs
Labels: C-bug

#10198 chore: derive serde traits
  crates/trie/common/src/proofs.rs
Labels: C-enhancement

#10217 fix: detect invalid buffered block when insert fails
  crates/engine/tree/src/tree/mod.rs
Labels: C-bug, A-consensus, A-blockchain-tree

#10218 feat: make Eth node launcher generic
  Cargo.lock
  bin/reth/src/main.rs
  crates/ethereum/node/Cargo.toml
  crates/ethereum/node/src/lib.rs
  crates/ethereum/node/tests/it/builder.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/engine.rs
  crates/node/builder/src/launch/mod.rs
  crates/node/builder/src/lib.rs
Labels: C-enhancement

#10216 feat: inject locally built payloads into the tree
  crates/engine/tree/src/engine.rs
  crates/node/builder/src/launch/engine.rs
Labels: C-enhancement, C-perf

#10222 feat: integrate engine2 for optimism
  bin/reth/src/optimism.rs
  crates/optimism/node/src/args.rs
Labels: C-enhancement

#10200 feat: make additional validation tasks size configurable
  book/cli/reth/node.md
  crates/ethereum/node/src/node.rs
  crates/node/core/src/args/txpool.rs
  crates/optimism/node/src/node.rs
  crates/transaction-pool/src/config.rs
  crates/transaction-pool/src/lib.rs
  examples/custom-node-components/src/main.rs
Labels: A-tx-pool, A-cli

#10224 docs: fix Common metrics types path
  docs/repo/layout.md
Labels: C-docs

#10229 deps: rm unused deps
  Cargo.lock
  crates/engine/util/Cargo.toml
  crates/net/network/Cargo.toml
  crates/rpc/rpc/Cargo.toml
  crates/storage/db-api/Cargo.toml
Labels: A-dependencies

#10230 evm: add unit tests for `ConfigureEvm` trait
  crates/ethereum/evm/src/lib.rs
Labels: C-test

#10225 feat: add metrics for dropped outgoing messages
  crates/net/network/src/metrics.rs
  crates/net/network/src/session/mod.rs
Labels: A-observability

#10234 fix: only mark propagated txs as seen
  crates/net/network/src/transactions/mod.rs
Labels: C-bug, A-tx-pool

#10228 chore: use exact max full peer count or round
  crates/net/network/src/transactions/mod.rs
Labels: C-bug

#10226 chore: add trace for when nothing to propagate
  crates/net/network/src/transactions/mod.rs
Labels: A-observability

#10233 feat: function-like macro for generating tests
  crates/storage/codecs/derive/src/arbitrary.rs
  crates/storage/codecs/derive/src/lib.rs
Labels: C-test

#10237 feat: add setting for how many blocks can be persisted
  crates/engine/tree/src/tree/config.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement

#10236 test: add test for prune.segments toml parsing
  crates/config/src/config.rs
Labels: C-test

#10239 chore: remove reference to EngineApiTreeHandlerImpl
  crates/engine/tree/src/tree/mod.rs
Labels: C-docs, A-blockchain-tree

#10242 chore: release 1.0.5
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#10241 chore: remove WriteTransactions from PersistenceAction
  crates/engine/tree/src/persistence.rs
Labels: C-debt, A-db, A-blockchain-tree

#10240 fix: make EvmEnvProvider methods aware of in-memory state
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-bug, C-enhancement, A-db, A-blockchain-tree

#10243 fix: use op-reth bin for unwind in op-sync CI
  .github/workflows/op-sync.yml
Labels: C-bug, C-test, A-op-reth, A-ci

#10244 fix: use --chain base for op-sync CI test
  .github/workflows/op-sync.yml
Labels: C-bug, C-test, A-op-reth, A-ci

#10245 fix: make WithdrawalsProvider methods aware of in-memory state
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-bug, C-enhancement, A-rpc, A-db, A-blockchain-tree

#10232 fix: TreeState::on_new_head fork and reorg handling
  Cargo.lock
  crates/chain-state/Cargo.toml
  crates/chain-state/src/test_utils.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-bug

#10249 Add generic BlockStateNotificationStream type for pending, safe, finalized watchers
  crates/chain-state/src/lib.rs
  crates/chain-state/src/notifications.rs
Labels: C-enhancement

#10231 feat: ForkChoiceNotifications for BlockchainProvider and NoopProvider
  crates/chain-state/src/chain_info.rs
  crates/chain-state/src/notifications.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/noop.rs
Labels: C-enhancement

#10261 chore(reth-engine-primitives): remove unused code
  crates/engine/primitives/src/error.rs
Labels: C-debt

#10260 chore: fix typos
  crates/storage/db/src/tables/mod.rs
Labels: C-debt

#10263 refactor: remove `#[reth_codec]` and `#[derive_arbitrary]` macros
  crates/net/eth-wire-types/src/blocks.rs
  crates/net/eth-wire-types/src/broadcast.rs
  crates/net/eth-wire-types/src/disconnect_reason.rs
  crates/net/eth-wire-types/src/header.rs
  crates/net/eth-wire-types/src/receipts.rs
  crates/net/eth-wire-types/src/state.rs
  crates/net/eth-wire-types/src/status.rs
  crates/net/eth-wire-types/src/transactions.rs
  crates/net/eth-wire-types/src/version.rs
  crates/net/eth-wire/src/hello.rs
  crates/net/eth-wire/src/p2pstream.rs
  crates/net/eth-wire/tests/fuzz_roundtrip.rs
  crates/primitives-traits/src/account.rs
  crates/primitives-traits/src/header/mod.rs
  crates/primitives-traits/src/header/sealed.rs
  crates/primitives-traits/src/log.rs
  crates/primitives-traits/src/request.rs
  crates/primitives-traits/src/storage.rs
  crates/primitives-traits/src/withdrawal.rs
  crates/primitives/src/block.rs
  crates/primitives/src/receipt.rs
  crates/primitives/src/transaction/access_list.rs
  crates/primitives/src/transaction/eip1559.rs
  crates/primitives/src/transaction/eip2930.rs
  crates/primitives/src/transaction/eip4844.rs
  crates/primitives/src/transaction/eip7702.rs
  crates/primitives/src/transaction/legacy.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/optimism.rs
  crates/primitives/src/transaction/signature.rs
  crates/primitives/src/transaction/tx_type.rs
  crates/prune/types/src/checkpoint.rs
  crates/prune/types/src/mode.rs
  crates/prune/types/src/segment.rs
  crates/stages/types/src/checkpoints.rs
  crates/storage/codecs/derive/src/lib.rs
  crates/storage/codecs/src/alloy/authorization_list.rs
  crates/storage/codecs/src/alloy/genesis_account.rs
  crates/storage/codecs/src/alloy/withdrawal.rs
  crates/storage/codecs/src/lib.rs
  crates/storage/db-api/src/models/accounts.rs
  crates/storage/db-api/src/models/blocks.rs
  crates/storage/db-api/src/models/client_version.rs
  crates/storage/db-api/src/models/mod.rs
  crates/trie/common/src/hash_builder/state.rs
Labels: C-debt, C-test

#10265 docs: delete interface
  docs/repo/layout.md
Labels: C-docs

#10251 fix: fix tx propagation when full
  crates/net/network/src/transactions/mod.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
Labels: C-bug, C-enhancement, A-tx-pool, A-networking

#10271 rpc: rm `PeerCount` usage
  crates/rpc/rpc-api/src/net.rs
  crates/rpc/rpc/src/net.rs
Labels: C-debt

#9663 chore(reth-consensus): `no_std` support
  Cargo.lock
  Cargo.toml
  crates/consensus/consensus/Cargo.toml
  crates/consensus/consensus/src/lib.rs
  crates/consensus/consensus/src/test_utils.rs
  crates/evm/execution-errors/Cargo.toml
  crates/net/p2p/Cargo.toml
Labels: S-blocked, C-debt, A-consensus
