Repository paradigmxyz/reth, pull requests merged in 2024-05, with the labels that each got.

#8011 fix(op): use canyon,ecotone fork timestamps for op mainnet
  crates/primitives/src/chain/spec.rs
Labels: C-bug, A-devp2p, A-op-reth

#7842 feat: introduce external context GAT in ConfigureEvm
  crates/ethereum/evm/src/lib.rs
  crates/evm/src/lib.rs
  crates/optimism/evm/src/lib.rs
  crates/revm/src/test_utils.rs
  examples/custom-evm/src/main.rs
Labels: C-enhancement, A-execution, A-sdk

#8019 chore: rm uneccessary trait bounds
  crates/rpc/rpc/src/layers/auth_layer.rs
Labels: C-debt, A-rpc

#7967 perf(build): make maxperf-op
  Makefile
Labels: A-meta, A-op-reth

#8020 fix(grafana): tx pool dashboard units
  etc/grafana/dashboards/reth-mempool.json
Labels: A-observability

#8025 chore: remove redundant suffix in ChainPath methods
  bin/reth/src/commands/db/mod.rs
  bin/reth/src/commands/db/static_files/mod.rs
  bin/reth/src/commands/db/stats.rs
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/import_op.rs
  bin/reth/src/commands/init_cmd.rs
  bin/reth/src/commands/init_state.rs
  bin/reth/src/commands/node/mod.rs
  bin/reth/src/commands/p2p/mod.rs
  bin/reth/src/commands/recover/storage_tries.rs
  bin/reth/src/commands/stage/drop.rs
  bin/reth/src/commands/stage/dump/execution.rs
  bin/reth/src/commands/stage/dump/hashing_account.rs
  bin/reth/src/commands/stage/dump/hashing_storage.rs
  bin/reth/src/commands/stage/dump/merkle.rs
  bin/reth/src/commands/stage/dump/mod.rs
  bin/reth/src/commands/stage/run.rs
  bin/reth/src/commands/stage/unwind.rs
  crates/node-core/src/dirs.rs
  crates/node-core/src/node_config.rs
  crates/node-ethereum/src/node.rs
  crates/node/builder/src/builder/mod.rs
  crates/node/builder/src/launch/common.rs
  crates/optimism/node/src/node.rs
  examples/custom-node-components/src/main.rs
Labels: C-debt

#8024 feat(node_builder): allow borrowing self in `ConfigureEvm::evm`
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/auto-seal/src/task.rs
  crates/ethereum/evm/src/execute.rs
  crates/evm/src/lib.rs
  crates/node/builder/src/builder/mod.rs
  crates/node/builder/src/components/execute.rs
  crates/optimism/evm/src/execute.rs
  crates/revm/src/factory.rs
  crates/revm/src/optimism/processor.rs
  crates/revm/src/processor.rs
  examples/exex/rollup/src/main.rs
Labels: C-enhancement, A-sdk

#8030 chore: reduce number of Evm monomorphizations
  crates/payload/builder/src/database.rs
  crates/payload/ethereum/src/lib.rs
  crates/payload/optimism/src/builder.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-debt

#8031 feat(pool): add `chain_id` to transaction mocks
  crates/transaction-pool/src/test_utils/mock.rs
Labels: C-enhancement, A-tx-pool, C-test

#8027 chore(engine): flatten fcu processing
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#8033 chore: cfg ImportOp behind optimism feature
  bin/reth/src/cli/mod.rs
Labels: C-debt, A-op-reth

#8010 feat(rpc-builder): add tower layer for updating bearer token in auth client
  crates/e2e-test-utils/src/engine_api.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc/src/layers/auth_client_layer.rs
  crates/rpc/rpc/src/layers/mod.rs
  crates/rpc/rpc/src/lib.rs
Labels: C-enhancement, A-rpc

#8038 chore: deduplicate fork timestamp configuration in `ChainSpec`
  crates/node-core/src/init.rs
  crates/primitives/src/chain/mod.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/lib.rs
  examples/polygon-p2p/src/chain_cfg.rs
Labels: C-debt

#8029 chore(engine): introduce blockchain tree action
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#7938 feat: write pruning config if --full is present
  Cargo.lock
  crates/config/Cargo.toml
  crates/config/src/config.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/common.rs
Labels: C-enhancement, A-cli

#8043 chore(deps): rm builder dep
  Cargo.lock
  crates/blockchain-tree/Cargo.toml
  crates/blockchain-tree/src/blockchain_tree.rs
Labels: C-debt

#8004 feat(discv5): bootstrap cli
  Cargo.lock
  bin/reth/src/commands/p2p/mod.rs
  crates/net/discv5/src/config.rs
  crates/net/discv5/src/lib.rs
  crates/node-core/Cargo.toml
  crates/node-core/src/args/network.rs
  crates/node-core/src/node_config.rs
Labels: A-cli, A-discv5

#8022 perf: add `ETL` to `init_from_state_dump`
  Cargo.lock
  bin/reth/src/commands/init_state.rs
  crates/node-core/Cargo.toml
  crates/node-core/src/init.rs
  crates/storage/codecs/Cargo.toml
  crates/storage/codecs/src/alloy/genesis_account.rs
  crates/storage/codecs/src/alloy/mod.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/provider/src/bundle_state/state_reverts.rs
Labels: C-perf, A-op-reth

#8037 fix: check for oob offset access in nippy jar
  crates/storage/nippy-jar/src/cursor.rs
  crates/storage/nippy-jar/src/error.rs
  crates/storage/nippy-jar/src/lib.rs
Labels: A-static-files

#8036 feat: add spawn_replay_transaction to EthTransactions
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/otterscan.rs
Labels: C-debt, A-rpc

#8047 docs(libmdbx): more `static_files` -> `snapshots`
  crates/storage/libmdbx-rs/src/environment.rs
Labels: C-docs, A-db

#8048 refactor: engine interceptors
  Cargo.lock
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/node-core/Cargo.toml
  crates/node-core/src/engine/engine_store.rs
  crates/node-core/src/engine/mod.rs
  crates/node-core/src/engine/skip_fcu.rs
  crates/node-core/src/engine_skip_fcu.rs
  crates/node-core/src/lib.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/mod.rs
Labels: A-consensus, A-cli

#8041 chore(engine): new payload blockchain tree action
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#8050 feat: new payload skipper
  crates/node-core/src/args/debug.rs
  crates/node-core/src/engine/mod.rs
  crates/node-core/src/engine/skip_fcu.rs
  crates/node-core/src/engine/skip_new_payload.rs
  crates/node/builder/src/launch/mod.rs
Labels: C-enhancement

#8042 feat(engine): make new payload canonical action
  crates/consensus/beacon/src/engine/mod.rs
Labels: C-debt, A-consensus

#7990 fix(op): bootnodes
  crates/primitives/src/lib.rs
  crates/primitives/src/net.rs
Labels: A-discv5, A-op-reth

#8051 integrate FullNodeComponents in exexcomponents
  Cargo.lock
  crates/exex/Cargo.toml
  crates/exex/src/context.rs
  crates/node/builder/src/launch/mod.rs
Labels: C-enhancement, A-exex

#7949 feat: remove field ```max_gas_limit``` from ```BasicPayloadJobGeneratorConfig```
  crates/node-ethereum/src/node.rs
  crates/optimism/node/src/node.rs
  crates/payload/basic/src/lib.rs
  examples/custom-engine-types/src/main.rs
  examples/custom-payload-builder/src/main.rs
Labels: C-enhancement, A-block-building

#8054 chore: drop ```RUST_LOG=info``` from recommended commands
  book/jsonrpc/intro.md
  book/run/mainnet.md
  book/run/observability.md
  book/run/pruning.md
Labels: C-docs

#8056 feat(cli): make `db stats` non-detailed by default
  bin/reth/src/commands/db/stats.rs
  book/SUMMARY.md
  book/cli/SUMMARY.md
  book/cli/reth.md
  book/cli/reth/db.md
  book/cli/reth/db/stats.md
  book/cli/reth/import.md
  book/cli/reth/node.md
  book/cli/reth/p2p.md
  book/cli/reth/stage/drop.md
  book/cli/reth/stage/run.md
  book/cli/reth/stage/unwind.md
  book/cli/reth/stage/unwind/num-blocks.md
  book/cli/reth/stage/unwind/to-block.md
Labels: C-enhancement, A-cli

#8028 feat(examples): add blob support to the rollup ExEx
  Cargo.lock
  crates/transaction-pool/src/test_utils/mock.rs
  deny.toml
  examples/exex/rollup/Cargo.toml
  examples/exex/rollup/rollup_abi.json
  examples/exex/rollup/src/execution.rs
  examples/exex/rollup/src/main.rs
Labels: C-enhancement, A-exex, C-example

#8057 chore(discv5): pub methods
  crates/net/discv5/src/config.rs
  crates/net/discv5/src/filter.rs
  crates/net/discv5/src/lib.rs
Labels: C-debt, A-discv5

#8068 chore: make clippy happy
  bin/reth/src/commands/db/mod.rs
  bin/reth/src/utils.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/beacon/src/engine/hooks/controller.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/exex/src/manager.rs
  crates/metrics/src/common/mpsc.rs
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/test_utils.rs
  crates/net/discv5/src/lib.rs
  crates/net/dns/src/lib.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/file_client.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/eth-wire/src/multiplex.rs
  crates/net/eth-wire/src/muxdemux.rs
  crates/net/network/src/budget.rs
  crates/net/network/src/eth_requests.rs
  crates/net/network/src/fetch/mod.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/state.rs
  crates/net/network/src/transactions/fetcher.rs
  crates/node/events/src/node.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/eth/api/sign.rs
  crates/stages-api/src/pipeline/mod.rs
  crates/stages/src/stages/merkle.rs
  crates/storage/libmdbx-rs/src/lib.rs
  crates/storage/nippy-jar/src/lib.rs
  crates/storage/nippy-jar/src/writer.rs
  crates/storage/provider/src/providers/static_file/writer.rs
  crates/storage/provider/src/test_utils/events.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-debt

#8069 chore: log only number & hash when skipping payload
  crates/node-core/src/engine/skip_new_payload.rs
Labels: C-debt, A-consensus

#8073 chore: remove InspectorStack
  Cargo.lock
  crates/ethereum/evm/src/execute.rs
  crates/node-core/src/args/debug.rs
  crates/node-ethereum/src/node.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/builder/mod.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/node/src/node.rs
  crates/revm/src/lib.rs
  crates/revm/src/stack.rs
Labels: C-enhancement, C-debt

#8065 debt(discv5): discv5 integration into network
  bin/reth/src/commands/p2p/mod.rs
  crates/net/discv4/src/lib.rs
  crates/net/discv5/src/config.rs
  crates/net/discv5/src/lib.rs
  crates/net/network/src/config.rs
  crates/node-core/src/args/network.rs
  crates/node-core/src/node_config.rs
Labels: C-debt, A-networking, A-cli, A-discv5

#8076 chore: move node-ethereum to ethereum/node
  Cargo.toml
  crates/ethereum/node/Cargo.toml
  crates/ethereum/node/src/evm.rs
  crates/ethereum/node/src/lib.rs
  crates/ethereum/node/src/node.rs
  crates/ethereum/node/tests/assets/genesis.json
  crates/ethereum/node/tests/e2e/blobs.rs
  crates/ethereum/node/tests/e2e/dev.rs
  crates/ethereum/node/tests/e2e/eth.rs
  crates/ethereum/node/tests/e2e/main.rs
  crates/ethereum/node/tests/e2e/p2p.rs
  crates/ethereum/node/tests/e2e/utils.rs
  crates/ethereum/node/tests/it/builder.rs
  crates/ethereum/node/tests/it/exex.rs
  crates/ethereum/node/tests/it/main.rs
Labels: C-debt, A-sdk

#8059 feat(op): pass unverifiable ENRs to rlpx
  crates/net/discv5/src/lib.rs
Labels: A-discv5, A-op-reth

#8077 chore(deps): bump alloy, evm-inspectors
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#8078 chore: move dao hardfork constants to evm-ethereum
  crates/ethereum/evm/src/dao_fork.rs
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/evm/src/lib.rs
  crates/revm/src/lib.rs
Labels: C-debt

#8067 fix(cli): debug merkle script
  bin/reth/src/commands/debug_cmd/merkle.rs
Labels: C-bug, A-cli

#8087 feat: add helper functions for batch executor
  crates/evm/src/execute.rs
Labels: A-execution

#8093 docs(book): update CLI
  book/cli/reth/db/checksum.md
  book/cli/reth/init-state.md
  book/cli/reth/node.md
Labels: C-docs

#8096 chore: rm unused file
  crates/rpc/rpc-types/src/admin.rs
Labels: C-debt

#8097 feat: rm reth-primitives dep
  Cargo.lock
  crates/net/types/Cargo.toml
  crates/net/types/src/lib.rs
Labels: C-debt

#8098 chore: rm leftover peer.rs file
  crates/primitives/src/peer.rs
Labels: C-debt

#8091 chore(cli): fix displayed block range in merkle debug script
  bin/reth/src/commands/debug_cmd/merkle.rs
Labels: C-debt, A-cli

#8099 replace U64 fields with primitive u64
  crates/rpc/rpc-types/src/mev.rs
  crates/rpc/rpc/src/eth/bundle.rs
Labels: C-debt, A-rpc

#8106 ci: remove check-cfg job
  .github/workflows/lint.yml
  crates/net/eth-wire/tests/fuzz_roundtrip.rs
  crates/net/network/tests/it/main.rs
Labels: A-meta

#8107 chore: bump alloy 0bb7604
  Cargo.lock
  Cargo.toml
  crates/e2e-test-utils/src/engine_api.rs
  crates/e2e-test-utils/src/node.rs
  crates/rpc/rpc-types-compat/src/block.rs
  examples/exex/rollup/src/execution.rs
Labels: A-dependencies

#8109 refactor: replace futures_util pin and tokio_pin with std pin
  Cargo.lock
  crates/cli/runner/Cargo.toml
  crates/cli/runner/src/lib.rs
  crates/net/eth-wire/src/multiplex.rs
  crates/net/network/src/listener.rs
  crates/net/network/src/manager.rs
  crates/rpc/ipc/src/server/mod.rs
  crates/tasks/src/lib.rs
Labels: C-debt

#8116 feat: improve exex examples' validation
  examples/exex/op-bridge/src/main.rs
  examples/exex/rollup/src/main.rs
Labels: A-exex, C-example

#8108 feat: add exex for in memory state
  Cargo.lock
  Cargo.toml
  examples/README.md
  examples/exex/in-memory-state/Cargo.toml
  examples/exex/in-memory-state/src/main.rs
Labels: A-exex, C-example

#8117 chore: remote `try_` prefix from block to payload conversion methods
  crates/consensus/beacon/src/engine/mod.rs
  crates/ethereum/engine-primitives/src/payload.rs
  crates/payload/optimism/src/payload.rs
  crates/rpc/rpc-builder/tests/it/auth.rs
  crates/rpc/rpc-engine-api/tests/it/payload.rs
  crates/rpc/rpc-types-compat/src/engine/mod.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: C-debt, A-consensus

#8100 convert ```OptimismBlockExecution``` error variant into a general purpose error variant
  Cargo.lock
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/ethereum/evm/src/execute.rs
  crates/interfaces/src/blockchain_tree/error.rs
  crates/interfaces/src/error.rs
  crates/interfaces/src/executor.rs
  crates/optimism/evm/Cargo.toml
  crates/optimism/evm/src/error.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/evm/src/l1.rs
  crates/optimism/evm/src/lib.rs
  crates/storage/provider/src/chain.rs
Labels: C-debt

#8121 chore: move NodeRecord type
  Cargo.lock
  Cargo.toml
  crates/net/types/Cargo.toml
  crates/net/types/src/lib.rs
  crates/net/types/src/node_record.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/net.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/lib.rs
  crates/rpc/rpc-types/src/net.rs
  crates/rpc/rpc-types/src/peer.rs
Labels: C-debt

#8075 fix(op): custom testinprod receipt encoding
  bin/reth/src/commands/import_receipts.rs
  crates/net/downloaders/src/file_codec_ovm_receipt.rs
  crates/net/downloaders/src/receipt_file_client.rs
Labels: A-op-reth

#8119 feat: prague engine api types
  Cargo.lock
  Cargo.toml
  crates/engine-primitives/src/lib.rs
  crates/optimism/node/src/engine.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
  crates/rpc/rpc-types/src/beacon/payload.rs
Labels: C-enhancement, E-prague

#8066 fix(receipts): write to static files properly, fix receipt file client
  bin/reth/src/commands/import_receipts.rs
  crates/net/downloaders/src/file_client.rs
  crates/net/downloaders/src/file_codec_ovm_receipt.rs
  crates/net/downloaders/src/receipt_file_client.rs
Labels: A-cli, A-op-reth

#8129 fix: set mainnet timestamps in op chainspecs for consensus checks
  crates/primitives/src/chain/spec.rs
Labels: C-bug, A-devp2p, A-networking

#8126 cli(op): simplify init-state cmd
  bin/reth/src/commands/init_state.rs
Labels: C-debt, A-cli, A-op-reth

#8130 fix(discv5): no address cli arg
  crates/net/network/src/config.rs
  crates/node-core/src/node_config.rs
Labels: C-bug, A-cli, A-discv5

#8125 chore: replace beacon types
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/beacon/constants.rs
  crates/rpc/rpc-types/src/beacon/events/attestation.rs
  crates/rpc/rpc-types/src/beacon/events/light_client_finality.rs
  crates/rpc/rpc-types/src/beacon/events/light_client_optimistic.rs
  crates/rpc/rpc-types/src/beacon/events/mod.rs
  crates/rpc/rpc-types/src/beacon/header.rs
  crates/rpc/rpc-types/src/beacon/mod.rs
  crates/rpc/rpc-types/src/beacon/payload.rs
  crates/rpc/rpc-types/src/beacon/withdrawals.rs
  crates/rpc/rpc-types/src/lib.rs
  crates/rpc/rpc-types/src/relay/mod.rs
  examples/beacon-api-sse/Cargo.toml
  examples/beacon-api-sse/src/main.rs
Labels: C-enhancement, C-debt, A-rpc

#8134 Add helpful text for tx pool flags in reth --help
  crates/node-core/src/args/network.rs
Labels: A-cli

#8021 fix(op): stages checkpoints init-state
  bin/reth/src/commands/import.rs
  crates/node-core/src/init.rs
  crates/primitives/src/stage/checkpoints.rs
  crates/primitives/src/stage/id.rs
Labels: A-op-reth

#8136 chore: rm redundant optimism feature
  crates/consensus/common/Cargo.toml
  crates/node-core/Cargo.toml
  crates/revm/Cargo.toml
Labels: C-debt

#8138 feat: rm txmeta associated type
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/evm/src/lib.rs
  crates/evm/src/lib.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/evm/src/lib.rs
  crates/revm/src/test_utils.rs
  examples/custom-evm/src/main.rs
Labels: C-debt

#8101 fix: ensures that pruning data from static files only happens on calling `commit()`
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/execution.rs
  crates/stages/src/stages/merkle.rs
  crates/static-file/src/static_file_producer.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/static_file/writer.rs
Labels: C-bug, A-db, A-static-files

#8141 chore: remove reth-revm optimism
  Cargo.lock
  bin/reth/Cargo.toml
  crates/blockchain-tree/Cargo.toml
  crates/consensus/beacon/Cargo.toml
  crates/optimism/evm/Cargo.toml
  crates/optimism/node/Cargo.toml
  crates/payload/optimism/Cargo.toml
  crates/revm/Cargo.toml
  crates/revm/src/lib.rs
  crates/revm/src/test_utils.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-debt, A-execution

#8140 Move and rename ```BeaconConsensus``` to ```EthBeaconConsensus```
  Cargo.lock
  Cargo.toml
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/import_op.rs
  bin/reth/src/commands/stage/run.rs
  bin/reth/src/commands/stage/unwind.rs
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/engine/sync.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/consensus/beacon/src/lib.rs
  crates/ethereum/consensus/Cargo.toml
  crates/ethereum/consensus/src/lib.rs
  crates/node/builder/src/launch/mod.rs
Labels: C-debt

#8139 fix(net): max inflight requests
  crates/net/network/src/transactions/fetcher.rs
Labels: C-bug, A-networking

#8142 perf(net): constraint algorithm fill request with hashes
  crates/net/network/src/transactions/constants.rs
Labels: C-perf, A-networking

#7552 fix: use `--syncmode=execution-layer` from `op-node` for optimistic pipeline sync
  bin/reth/src/optimism.rs
  crates/blockchain-tree/src/block_buffer.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/noop.rs
  crates/blockchain-tree/src/shareable.rs
  crates/consensus/beacon/src/engine/hooks/controller.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/e2e-test-utils/src/engine_api.rs
  crates/e2e-test-utils/src/node.rs
  crates/e2e-test-utils/src/wallet.rs
  crates/interfaces/src/blockchain_tree/error.rs
  crates/interfaces/src/blockchain_tree/mod.rs
  crates/optimism/node/tests/e2e/p2p.rs
  crates/optimism/node/tests/e2e/utils.rs
  crates/primitives/src/stage/mod.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/stages-api/src/pipeline/mod.rs
  crates/storage/provider/src/providers/mod.rs
Labels: C-bug, A-op-reth

#7914 feat(op): import receipts
  bin/reth/src/cli/mod.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/import_op.rs
  bin/reth/src/commands/import_receipts.rs
  bin/reth/src/commands/mod.rs
  crates/net/downloaders/src/file_client.rs
  crates/net/downloaders/src/file_codec_ovm_receipt.rs
  crates/net/downloaders/src/lib.rs
  crates/net/downloaders/src/receipt_file_client.rs
  crates/primitives/Cargo.toml
  crates/storage/provider/src/lib.rs
Labels: A-cli, A-op-reth

#8144 feat(grafana): State & History panel
  etc/grafana/dashboards/reth-state-growth.json
Labels: A-db, A-observability

#8148 chore(grafana): dashboard names like public
  etc/grafana/dashboards/overview.json
  etc/grafana/dashboards/reth-discovery.json
Labels: C-debt, A-observability

#8149 fix(discv5): update metrics wrt unverifiable enrs
  crates/net/discv5/src/lib.rs
  crates/net/discv5/src/metrics.rs
  etc/grafana/dashboards/reth-discovery.json
  etc/grafana/dashboards/reth-state-growth.json
Labels: C-bug, A-observability, A-discv5

#8153 chore: move dashmap to workspace dep
  Cargo.toml
  crates/storage/libmdbx-rs/Cargo.toml
  crates/storage/provider/Cargo.toml
Labels: A-dependencies

#8156 fix: prevents potential arithmetic underflow
  crates/blockchain-tree/src/chain.rs
  crates/interfaces/src/blockchain_tree/error.rs
Labels: C-debt

#8151 fix(examples): ExEx rollup reverts
  examples/exex/rollup/src/db.rs
Labels: C-bug, A-exex, C-example

#8132 feat(ci): add op-reth to release workflow
  .github/workflows/docker.yml
  .github/workflows/release.yml
  DockerfileOp.cross
  Makefile
Labels: C-enhancement, A-op-reth

#8146 chore(op): simplify op cli args
  bin/reth/src/commands/import_op.rs
  bin/reth/src/commands/import_receipts.rs
Labels: C-debt, A-cli, A-op-reth

#8160 feat: introduce statewriter trait
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/import_receipts.rs
  crates/node-core/src/init.rs
  crates/stages/src/stages/execution.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/mod.rs
  crates/storage/provider/src/traits/state.rs
Labels: C-enhancement, C-debt, C-discussion

#7963 feat: feature gate rpc-types import for alloy conversions
  Cargo.lock
  crates/primitives/Cargo.toml
  crates/primitives/src/block.rs
  crates/primitives/src/header.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/net.rs
  crates/primitives/src/serde_helper.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/withdrawal.rs
  crates/rpc/rpc-api/src/eth.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
Labels: S-blocked, C-debt, A-rpc

#8167 fix: use op-build instead of build-op in release workflow
  .github/workflows/release.yml
Labels: C-bug

#8179 fix: use configs object list in matrix to release all platforms
  .github/workflows/release.yml
Labels: C-bug

#8184 chore(deps): remove outdated dev dep and comment
  crates/primitives/Cargo.toml
Labels: A-dependencies

#8185 fix: use --show-sdk-platform-version instead of os-version
  .github/workflows/release.yml
Labels: C-bug

#8189 fix: do not use cross for x86_64 apple darwin
  Makefile
Labels: C-bug

#8194 avoid double function call in `validate_one`
  crates/transaction-pool/src/validate/eth.rs
Labels: C-debt

#8172 chore: implement traits directly for futures::Either
  crates/consensus/beacon/src/engine/sync.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/interfaces/src/p2p/either.rs
  crates/node/builder/src/launch/mod.rs
Labels: C-debt

#8195 chore: bump alloy 899fc51
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc-types/src/relay/mod.rs
  examples/beacon-api-sse/src/main.rs
Labels: C-debt

#8169 chore: move optimism payload crate to optimism folder
  Cargo.toml
  crates/optimism/payload/Cargo.toml
  crates/optimism/payload/src/builder.rs
  crates/optimism/payload/src/error.rs
  crates/optimism/payload/src/lib.rs
  crates/optimism/payload/src/payload.rs
Labels: A-op-reth

#8170 chore: use engine types crate for types
  Cargo.lock
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/traits/chain_info.rs
Labels: C-debt, A-dependencies

#8200 fix: skip s value check in trace_filter recovery
  crates/rpc/rpc/src/trace.rs
Labels: C-bug, A-rpc

#8163 Extract layers module from rpc crate
  Cargo.lock
  Cargo.toml
  crates/e2e-test-utils/Cargo.toml
  crates/e2e-test-utils/src/engine_api.rs
  crates/node-core/Cargo.toml
  crates/node-core/src/args/rpc_server.rs
  crates/node-core/src/cli/config.rs
  crates/node-core/src/utils.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/lib.rs
  crates/node/builder/src/rpc.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/auth.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc-layer/Cargo.toml
  crates/rpc/rpc-layer/src/auth_client_layer.rs
  crates/rpc/rpc-layer/src/auth_layer.rs
  crates/rpc/rpc-layer/src/jwt_secret.rs
  crates/rpc/rpc-layer/src/jwt_validator.rs
  crates/rpc/rpc-layer/src/lib.rs
  crates/rpc/rpc/src/lib.rs
Labels: C-debt

#8192 refactor: move all alloy-compat code to a standalone module
  crates/primitives/src/alloy_compat.rs
  crates/primitives/src/block.rs
  crates/primitives/src/header.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-debt

#8208 refactor(ethereum, primitives, evm): use Alloy EIP-4788 constants
  Cargo.lock
  Cargo.toml
  crates/ethereum/evm/Cargo.toml
  crates/ethereum/evm/src/execute.rs
  crates/primitives/src/constants/mod.rs
  crates/primitives/src/revm/env.rs
  crates/revm/Cargo.toml
  crates/revm/src/state_change.rs
Labels: C-debt, A-execution

#7765 chore: bump revm to latest with placeholders for EOF
  Cargo.lock
  Cargo.toml
  crates/primitives/src/account.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/revm/compat.rs
  crates/primitives/src/revm/env.rs
  crates/revm/src/state_change.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/error.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
  examples/exex/rollup/src/db.rs
Labels: S-blocked, A-execution, A-dependencies

#8215 chore: bump alloy dd7a999
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#8212 feat(evm): EIP-7002 withdrawal requests
  Cargo.lock
  bin/reth/src/commands/debug_cmd/merkle.rs
  crates/config/src/config.rs
  crates/e2e-test-utils/src/payload.rs
  crates/ethereum/evm/Cargo.toml
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/evm/src/instructions/eip3074.rs
  crates/evm/Cargo.toml
  crates/evm/src/execute.rs
  crates/evm/src/test_utils.rs
  crates/interfaces/src/executor.rs
  crates/net/discv4/src/lib.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/eth-wire/src/multiplex.rs
  crates/node-core/src/args/pruning.rs
  crates/node-core/src/init.rs
  crates/node-core/src/node_config.rs
  crates/optimism/evm/src/execute.rs
  crates/payload/validator/src/lib.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/compression/mod.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/receipt.rs
  crates/primitives/src/request.rs
  crates/primitives/src/revm/env.rs
  crates/primitives/src/transaction/mod.rs
  crates/revm/Cargo.toml
  crates/revm/src/batch.rs
  crates/revm/src/state_change.rs
  crates/rpc/ipc/src/server/ipc.rs
  crates/rpc/ipc/src/server/mod.rs
  crates/rpc/rpc-types/src/mev.rs
  crates/rpc/rpc/src/otterscan.rs
  crates/stages/src/stages/execution.rs
  crates/storage/nippy-jar/src/lib.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/providers/static_file/writer.rs
Labels: C-enhancement, A-execution, E-prague

#8053 feat: implement EIP-7685
  Cargo.lock
  Cargo.toml
  bin/reth/src/commands/db/diff.rs
  bin/reth/src/commands/db/stats.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/auto-seal/src/task.rs
  crates/consensus/common/src/validation.rs
  crates/ethereum/evm/src/execute.rs
  crates/evm/src/execute.rs
  crates/interfaces/src/test_utils/generators.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/test_utils.rs
  crates/net/downloaders/src/file_client.rs
  crates/net/downloaders/src/test_utils/mod.rs
  crates/net/eth-wire-types/src/blocks.rs
  crates/net/network/src/eth_requests.rs
  crates/net/network/tests/it/requests.rs
  crates/node-core/src/utils.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/evm/src/l1.rs
  crates/optimism/payload/src/builder.rs
  crates/payload/ethereum/src/lib.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/alloy_compat.rs
  crates/primitives/src/block.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/header.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/proofs.rs
  crates/primitives/src/request.rs
  crates/primitives/src/revm/mod.rs
  crates/primitives/src/transaction/mod.rs
  crates/revm/src/batch.rs
  crates/rpc/rpc-engine-api/tests/it/payload.rs
  crates/rpc/rpc-types-compat/src/block.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  crates/stages/src/stages/bodies.rs
  crates/stages/src/stages/merkle.rs
  crates/storage/codecs/Cargo.toml
  crates/storage/codecs/src/alloy/mod.rs
  crates/storage/codecs/src/alloy/request.rs
  crates/storage/db/src/tables/codecs/compact.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/block.rs
  crates/storage/provider/src/traits/mod.rs
  crates/storage/provider/src/traits/requests.rs
  testing/ef-tests/src/models.rs
Labels: C-enhancement, E-prague

#8218 fix(evm): EIP-7002 withdrawals decoding
  crates/ethereum/evm/Cargo.toml
  crates/ethereum/evm/src/execute.rs
  crates/revm/src/batch.rs
  crates/revm/src/state_change.rs
Labels: C-bug, A-execution, C-test, E-prague

#8225 feat: integrate v4 envelope type
  crates/engine-primitives/src/lib.rs
  crates/ethereum/engine-primitives/src/lib.rs
  crates/ethereum/engine-primitives/src/payload.rs
  crates/optimism/node/src/engine.rs
  crates/optimism/payload/src/payload.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
  examples/custom-engine-types/src/main.rs
Labels: A-rpc

#8224 chore: remove validate_block_regarding_chain
  crates/consensus/common/Cargo.toml
  crates/consensus/common/src/validation.rs
Labels: A-consensus, C-test

#8227 feat(payload): include EIP-7002 withdrawal requests
  crates/ethereum/evm/src/execute.rs
  crates/payload/basic/src/lib.rs
  crates/payload/ethereum/src/lib.rs
  crates/revm/src/state_change.rs
Labels: C-enhancement, A-block-building, E-prague

#8223 feat: validate headers/bodies for tree & downloader
  crates/consensus/common/src/validation.rs
  crates/consensus/consensus/src/lib.rs
  crates/interfaces/src/p2p/full_block.rs
  crates/primitives/src/block.rs
Labels: C-enhancement, E-prague

#8222 feat: impl `Compact` for `FixedBytes<N>`
  crates/storage/codecs/derive/src/compact/generator.rs
  crates/storage/codecs/src/lib.rs
Labels: A-db

#8229 feat(payload): include EIP-6110 deposit requests
  Cargo.lock
  crates/payload/basic/Cargo.toml
  crates/payload/ethereum/Cargo.toml
  crates/payload/ethereum/src/lib.rs
Labels: C-enhancement, A-block-building, E-prague

#8236 fix: use the default eth config for eth payload building
  Cargo.lock
  crates/ethereum/evm/src/lib.rs
  crates/optimism/payload/src/builder.rs
  crates/payload/ethereum/Cargo.toml
  crates/payload/ethereum/src/lib.rs
Labels: C-enhancement, A-block-building

#8243 fix(payload): calculate withdrawal requests in empty payload
  crates/payload/ethereum/src/lib.rs
Labels: C-bug, A-block-building, E-prague

#8244 feat: deposit contract address conversion for genesis
  crates/primitives/src/chain/mod.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/constants/mod.rs
  crates/primitives/src/lib.rs
Labels: C-enhancement, A-utils, E-prague

#8252 fix(revm): increment nonce of EIP-2935 account
  crates/revm/src/state_change.rs
Labels: C-bug, A-execution, E-prague

#8256 fix(evm): use chainspec deposit contract address
  crates/ethereum/evm/src/eip6110.rs
  crates/ethereum/evm/src/execute.rs
  crates/payload/ethereum/src/lib.rs
Labels: C-bug, A-execution, E-prague

#8250 fix: allow to call V1 methods post-Shanghai
  crates/engine-primitives/src/lib.rs
Labels: A-rpc, C-security

#8257 chore: add eip-2935 tests back
  crates/ethereum/evm/src/execute.rs
Labels: C-enhancement, E-cancun

#8267 fix: make payload to block fns sound
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: C-bug

#8197 chore: add alloy-compat for signature and transaction
  crates/primitives/src/alloy_compat.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-enhancement

#8262 chore: install apt-get deps before cargo deps
  Dockerfile
Labels: A-meta

#8271 fix: enc/dec rlp for `Requests`
  crates/primitives/src/request.rs
Labels: C-bug, E-prague

#8268 fix: Make L1 tx data fee calculation aware of Ecotone hardfork
  crates/optimism/evm/src/l1.rs
Labels: A-op-reth

#8274 chore(rpc): cleanup rpc-layer
  crates/rpc/rpc-layer/Cargo.toml
  crates/rpc/rpc-layer/src/lib.rs
Labels: C-debt, A-dependencies

#8275 chore: dont exclude crate
  crates/etl/Cargo.toml
Labels: C-debt

#8282 feat(storage): implement `BundleStateDataProvider` for `BundleStateWithReceipts`
  crates/blockchain-tree/src/bundle.rs
  crates/blockchain-tree/src/chain.rs
  crates/blockchain-tree/src/noop.rs
  crates/blockchain-tree/src/shareable.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/mod.rs
  crates/storage/provider/src/traits/state.rs
Labels: C-enhancement, A-db

#7484 wip: lru changes
  Cargo.lock
  crates/blockchain-tree/Cargo.toml
  crates/blockchain-tree/src/block_buffer.rs
  crates/blockchain-tree/src/config.rs
  crates/blockchain-tree/src/state.rs
  crates/net/network/src/cache.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/state.rs
  crates/net/network/src/transactions/constants.rs
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
Labels: C-bug, D-good-first-issue, C-debt, A-networking

#8237 feat(e2e): add helpers to TransactionTestContext
  crates/e2e-test-utils/src/transaction.rs
  crates/ethereum/node/tests/e2e/blobs.rs
  crates/ethereum/node/tests/e2e/eth.rs
  crates/ethereum/node/tests/e2e/p2p.rs
Labels: C-enhancement, C-test

#8286 Move reth-primitives::fs module to fs-utils crate
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  bin/reth/src/commands/db/stats.rs
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  bin/reth/src/commands/stage/drop.rs
  bin/reth/src/commands/test_vectors/tables.rs
  bin/reth/src/utils.rs
  crates/fs-util/Cargo.toml
  crates/fs-util/src/lib.rs
  crates/interfaces/Cargo.toml
  crates/interfaces/src/error.rs
  crates/interfaces/src/provider.rs
  crates/node-core/Cargo.toml
  crates/node-core/src/args/secret_key.rs
  crates/node-core/src/args/utils.rs
  crates/node-core/src/engine/engine_store.rs
  crates/node-core/src/utils.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/lib.rs
  crates/rpc/rpc-layer/Cargo.toml
  crates/rpc/rpc-layer/src/jwt_secret.rs
  crates/stages/benches/setup/account_hashing.rs
  crates/stages/benches/setup/mod.rs
  crates/storage/db/Cargo.toml
  crates/storage/db/benches/utils.rs
  crates/storage/db/src/lib.rs
  crates/storage/db/src/static_file/mod.rs
  crates/storage/nippy-jar/Cargo.toml
  crates/storage/nippy-jar/src/error.rs
  crates/storage/nippy-jar/src/lib.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/maintain.rs
Labels: C-enhancement

#8280 docs: add comment about potential overflow of base fee per gas
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: A-rpc, C-security

#8259 fix(make): use the default rust dir for build/build-op
  Makefile
Labels: A-meta

#8310 fix(op): reorder supported chain
  crates/node-core/src/args/utils.rs
Labels: A-cli, A-op-reth

#8302 fix: calculate parity of legacy EIP155 txs correctly in alloy compat
  crates/primitives/src/alloy_compat.rs
Labels: C-bug, C-security

#8312 chore: bump alloy
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#8314 feat: remove relay types
  Cargo.lock
  crates/rpc/rpc-api/src/validation.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/lib.rs
  crates/rpc/rpc-types/src/relay/error.rs
  crates/rpc/rpc-types/src/relay/mod.rs
  crates/rpc/rpc-types/test_data/relay/signed_bid_submission_capella.ssz
  crates/rpc/rpc-types/test_data/relay/single_payload.json
Labels: C-enhancement, C-debt

#8289 chore(net): integrate discv5 config builder
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/commands/p2p/mod.rs
  crates/net/network/src/config.rs
  crates/node-core/src/args/network.rs
  crates/node-core/src/node_config.rs
Labels: C-debt, A-networking

#7856 chore: integrate discv5 config builder in networkconfig builder
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/commands/p2p/mod.rs
  crates/net/discv5/src/config.rs
  crates/net/network/src/config.rs
  crates/node-core/src/args/network.rs
  crates/node-core/src/node_config.rs
Labels: A-networking, A-discv5

#8323 fix(txpool): local transaction configuration
  crates/ethereum/node/src/node.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: C-bug, A-tx-pool

#8327 chore: use with_chain_id for CfgEnv
  crates/ethereum/engine-primitives/src/payload.rs
  crates/optimism/payload/src/payload.rs
Labels: C-debt

#8291 fix: prevent CREATE tx for EIP-4844 types
  crates/consensus/common/src/validation.rs
  crates/primitives/src/alloy_compat.rs
  crates/primitives/src/revm/env.rs
  crates/primitives/src/transaction/eip4844.rs
  crates/primitives/src/transaction/mod.rs
  crates/rpc/rpc-types-compat/src/transaction/mod.rs
  crates/rpc/rpc-types-compat/src/transaction/typed.rs
  crates/rpc/rpc-types/src/eth/transaction/typed.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/storage/codecs/derive/src/compact/mod.rs
  crates/storage/codecs/src/lib.rs
  crates/transaction-pool/src/test_utils/gen.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: A-rpc, C-security

#8285 fix: Chain::split returns NoSplitPending for block number > tip
  crates/storage/provider/src/chain.rs
Labels: C-bug, A-blockchain-tree, C-security

#8297 fix(cli): tx fetcher args help
  crates/node-core/src/args/network.rs
Labels: A-networking, A-cli

#8329 fix(op): fix logs
  bin/reth/src/commands/import_op.rs
  bin/reth/src/commands/import_receipts.rs
  crates/net/downloaders/src/file_client.rs
  crates/net/downloaders/src/receipt_file_client.rs
Labels: A-observability, A-cli, A-op-reth

#8278 fix: remove some `expect` usage in blockchain_tree
  crates/blockchain-tree/src/blockchain_tree.rs
Labels: A-blockchain-tree, C-security

#8296 fix: reject trailing bytes when decoding transactions
  crates/primitives/src/transaction/mod.rs
Labels: A-rpc, C-security

#8316 fix(op): skip tx root validation for filtered out dup txns
  bin/reth/src/commands/import_op.rs
  crates/consensus/common/src/validation.rs
  crates/net/downloaders/src/file_client.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/op_mainnet.rs
Labels: C-bug, A-downloaders, A-op-reth

#8320 fix: disambiguate use of next when validating ForkId
  crates/ethereum-forks/src/forkid.rs
Labels: A-blockchain-tree, C-security

#8183 feat: add actions lint to pull request workflow
  .github/workflows/lint-actions.yml
Labels: C-enhancement

#8328 chore: rm leftover test assets
  crates/rpc/rpc-types/test_data/call_tracer/default.json
  crates/rpc/rpc-types/test_data/call_tracer/legacy.json
  crates/rpc/rpc-types/test_data/call_tracer/only_top_call.json
  crates/rpc/rpc-types/test_data/call_tracer/with_log.json
  crates/rpc/rpc-types/test_data/default/structlogs_01.json
  crates/rpc/rpc-types/test_data/pre_state_tracer/default.json
  crates/rpc/rpc-types/test_data/pre_state_tracer/diff_mode.json
  crates/rpc/rpc-types/test_data/pre_state_tracer/legacy.json
Labels: A-rpc, C-test

#8309 feat(op): docs sync op mainnet
  book/run/sync-op-mainnet.md
Labels: A-op-reth

#8317 fix(op): disable execution stage
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/import_op.rs
Labels: C-bug, A-cli, A-op-reth

#8324 fix: disable db shrinking
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: C-bug, A-db
