Repository paradigmxyz/reth, pull requests merged in 2024-09, with the labels that each got.

#10644 docs(NodeBuilder): fix broken link
  crates/node/builder/src/builder/mod.rs
Labels: C-docs

#10650 fix: clippy
  crates/transaction-pool/src/pool/txpool.rs
Labels: A-meta

#10647 [#10645] docs(prune): replace prune parts by segments
  book/run/config.md
  book/run/pruning.md
Labels: C-docs, A-pruning

#10646 chore(deps): bump op-alloy-rpc-types
  Cargo.lock
  Cargo.toml
  crates/optimism/rpc/src/eth/receipt.rs
Labels: A-dependencies, A-op-reth

#10456 feat(rpc): add preimages to execution witness response
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc-api/src/debug.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/lib.rs
  crates/rpc/rpc/src/debug.rs
Labels: C-enhancement, A-rpc

#10652 fix: dont use prune mode full
  crates/node/core/src/args/pruning.rs
Labels: C-bug, A-op-reth

#10653 chore: add debug log when new engine message
  crates/engine/tree/src/tree/mod.rs
Labels: A-observability

#10479 test(trie): improve in-memory nodes fuzz tests
  crates/trie/db/tests/fuzz_in_memory_nodes.rs
Labels: C-test, A-trie

#10656 fix(witness): allow no storage multiproof
  crates/evm/execution-errors/src/trie.rs
  crates/trie/trie/src/witness.rs
Labels: C-bug, A-trie

#10657 fix(witness): storage proof target on blinded
  crates/trie/trie/src/witness.rs
Labels: C-bug, A-trie

#10584 Use ByteCode::new_raw_checked and propagate error
  crates/primitives-traits/src/account.rs
  crates/storage/db-common/src/init.rs
Labels: C-enhancement

#10658 docs: remove outdated comment in cursor::Walker
  crates/storage/db-api/src/cursor.rs
Labels: C-docs

#10661 fix(`op-reth`): `--chain` help message
  bin/reth/src/cli/mod.rs
  crates/cli/cli/src/chainspec.rs
  crates/cli/commands/src/common.rs
  crates/cli/commands/src/dump_genesis.rs
  crates/cli/commands/src/node.rs
  crates/cli/commands/src/p2p/mod.rs
  crates/node/core/src/args/utils.rs
  crates/optimism/cli/src/lib.rs
Labels: A-op-reth

#10668 primitives: small refactor in `gas_limit` method
  crates/primitives/src/transaction/mod.rs
Labels: C-debt

#10579 feat(tree): cache trie updates for nonfinalized canonical blocks
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-blockchain-tree

#10671 chore(storage): remove unnecessary check empty vec
  crates/storage/provider/src/writer/database.rs
Labels: C-debt, A-db

#10640 fix(discv5): return discv5 local node record
  crates/net/network/src/discovery.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
Labels: C-bug, A-networking, A-discv5

#10669 Update generic name in payload crate
  crates/payload/builder/src/events.rs
  crates/payload/builder/src/noop.rs
  crates/payload/builder/src/service.rs
  crates/payload/builder/src/test_utils.rs
Labels: C-debt

#10665 node: revise `NodeTypes` trait
  crates/e2e-test-utils/src/lib.rs
  crates/e2e-test-utils/src/node.rs
  crates/ethereum/node/src/node.rs
  crates/exex/test-utils/src/lib.rs
  crates/node/api/src/node.rs
  crates/node/builder/src/builder/mod.rs
  crates/node/builder/src/builder/states.rs
  crates/node/builder/src/components/mod.rs
  crates/node/builder/src/node.rs
  crates/optimism/node/src/node.rs
  examples/custom-engine-types/src/main.rs
Labels: C-enhancement, S-breaking, A-sdk

#10432 feat: add invalid block hook field to tree
  Cargo.lock
  book/cli/reth/node.md
  crates/engine/service/src/service.rs
  crates/engine/tree/src/tree/invalid_block_hook.rs
  crates/engine/tree/src/tree/mod.rs
  crates/node/builder/src/launch/engine.rs
  crates/node/builder/src/launch/mod.rs
  crates/node/core/Cargo.toml
  crates/node/core/src/args/debug.rs
  crates/node/core/src/args/mod.rs
Labels: C-enhancement, A-consensus, A-blockchain-tree

#10629 feat(engine): invalid block hooks crate
  .github/assets/check_wasm.sh
  Cargo.lock
  Cargo.toml
  crates/engine/invalid-block-hooks/Cargo.toml
  crates/engine/invalid-block-hooks/src/lib.rs
  crates/engine/invalid-block-hooks/src/witness.rs
  crates/engine/tree/src/tree/invalid_block_hook.rs
  crates/engine/tree/src/tree/mod.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/engine.rs
  crates/node/core/src/args/debug.rs
Labels: C-enhancement, A-consensus

#10618 feat: impl StateReader for BlockchainProvider2
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/block.rs
Labels: C-enhancement, A-db, A-blockchain-tree

#10651 test (provider): receiptProvider impl of BlockchainProvider2<DB>
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: A-db, C-test, A-blockchain-tree

#10553 feat(tree): introduce executed_block_by_hash
  crates/engine/tree/src/tree/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
Labels: C-enhancement, A-blockchain-tree

#10426 refactor: move exec metrics into executor
  Cargo.lock
  crates/blockchain-tree/src/chain.rs
  crates/engine/tree/src/tree/metrics.rs
  crates/engine/tree/src/tree/mod.rs
  crates/evm/Cargo.toml
  crates/evm/src/lib.rs
  crates/evm/src/metrics.rs
  crates/node/builder/src/setup.rs
  crates/stages/api/src/metrics/listener.rs
  crates/stages/api/src/metrics/sync_metrics.rs
  crates/stages/stages/src/stages/execution.rs
  etc/grafana/dashboards/overview.json
Labels: C-enhancement, A-execution, A-observability

#10664 fix(op): parse l1 block info from l2 tx input
  crates/ethereum-forks/src/hardforks/optimism.rs
  crates/optimism/evm/src/l1.rs
Labels: C-bug, A-rpc, A-op-reth

#10690 Cargo update
  Cargo.lock
Labels: A-dependencies

#10692 primitives: simplify `generate_valid_header` logic
  crates/primitives-traits/src/header/test_utils.rs
Labels: C-test

#10695 chore: update wasm crate
  .github/assets/check_wasm.sh
Labels: C-enhancement, A-ci

#10694 chore(reth-evm): no-default optional crate
  crates/evm/Cargo.toml
Labels: A-dependencies

#10696 chore: more adjustments to grafana
  etc/grafana/dashboards/overview.json
Labels: C-enhancement

#10551 feat(tree): make on_new_head and is_fork aware of disk
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-blockchain-tree

#10702 fix: allow tx's from EIP-7702 delegated accounts
  crates/transaction-pool/src/validate/eth.rs
Labels: C-bug, A-tx-pool

#10704 rpc: small refactor in `TransactionSource` impl
  crates/rpc/rpc-eth-types/src/transaction.rs
Labels: C-debt

#10705 chore: relax txpool client trait bounds
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/task.rs
Labels: A-tx-pool

#10703 clippy: add `collection_is_never_read` clippy lint
  Cargo.toml
  crates/chainspec/src/spec.rs
  crates/rpc/rpc-testing-util/src/trace.rs
Labels: C-enhancement

#10603 feat(tree): schedule block removal on disk reorgs
  crates/engine/tree/src/persistence.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-blockchain-tree

#10520 chore: moved optimism_receiptfn and its tests
  Cargo.lock
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/ethereum-forks/src/hardfork/optimism.rs
  crates/optimism/consensus/Cargo.toml
  crates/optimism/consensus/src/lib.rs
  crates/optimism/consensus/src/proof.rs
  crates/optimism/consensus/src/validation.rs
  crates/optimism/primitives/Cargo.toml
  crates/primitives/src/proofs.rs
Labels: C-debt, A-op-reth

#10620 test(op): add test for assembling of op tx receipt RPC response
  Cargo.lock
  crates/ethereum-forks/src/hardforks/optimism.rs
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/eth/receipt.rs
  crates/primitives-traits/src/constants/mod.rs
Labels: C-debt, A-rpc, A-op-reth

#10709 fix: reject 7702 transactions with empty auth list
  crates/rpc/rpc-eth-types/src/error.rs
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: C-bug, A-tx-pool, E-prague

#10688 feat(engine): support `--debug.etherscan` on experimental engine
  crates/node/builder/src/launch/engine.rs
Labels: C-enhancement, A-consensus

#10710 chore(engine): track elapsed on fork block added
  crates/consensus/beacon/src/engine/event.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/engine/tree/src/tree/mod.rs
  crates/node/events/src/node.rs
Labels: A-consensus, A-observability

#10667 optimism: use op-alloy TxDeposit
  Cargo.lock
  Cargo.toml
  crates/optimism/node/src/txpool.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/alloy_compat.rs
  crates/primitives/src/transaction/compat.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/optimism.rs
  crates/storage/codecs/Cargo.toml
  crates/storage/codecs/src/alloy/transaction/mod.rs
  crates/storage/codecs/src/alloy/transaction/optimism.rs
Labels: C-debt, A-op-reth

#10712 ForkCondition: some small refactors
  crates/chainspec/src/spec.rs
  crates/ethereum-forks/src/hardforks/mod.rs
Labels: C-debt

#10707 ethereum-forks: add unit tests for `ForkCondition`
  crates/ethereum-forks/src/forkcondition.rs
Labels: C-test

#10723 fix: don't filter out hardforks
  crates/chainspec/src/spec.rs
Labels: C-bug

#10726 chore: bump example dep
  Cargo.lock
  examples/beacon-api-sse/Cargo.toml
Labels: A-dependencies

#10724 test: add hardfork parsing test
  crates/ethereum/cli/src/chainspec.rs
Labels: C-test

#10728 feat(tree): add block validation metrics
  crates/engine/tree/src/tree/metrics.rs
  crates/engine/tree/src/tree/mod.rs
  crates/evm/src/metrics.rs
Labels: C-enhancement, A-observability, A-blockchain-tree

#10619 chore(op): type safety in computation of op tx metadata
  Cargo.lock
  crates/ethereum-forks/src/hardforks/optimism.rs
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/error.rs
  crates/optimism/rpc/src/eth/block.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/eth/pending_block.rs
  crates/optimism/rpc/src/eth/receipt.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/optimism/rpc/src/lib.rs
  crates/primitives-traits/src/constants/mod.rs
Labels: C-debt, A-rpc, A-op-reth

#10735 chore: EvmStateProvider doc improvements
  crates/revm/src/database.rs
Labels: C-docs, C-enhancement, A-execution

#10731 chore(tree): make tree trace targets consistent
  crates/engine/tree/src/persistence.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-observability, A-blockchain-tree

#10734 chore(tree): propagate on_new_head error
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-blockchain-tree

#10639 chore: expose PruneConfig in CLI args
  Cargo.lock
  book/cli/reth/node.md
  crates/node/builder/src/launch/common.rs
  crates/node/core/Cargo.toml
  crates/node/core/src/args/error.rs
  crates/node/core/src/args/mod.rs
  crates/node/core/src/args/pruning.rs
  crates/node/core/src/node_config.rs
Labels: A-cli, A-pruning

#10739 Update layout doc
  docs/repo/layout.md
Labels: C-docs

#10685 feat(engine, tree): witness invalid block hook
  Cargo.lock
  crates/engine/invalid-block-hooks/Cargo.toml
  crates/engine/invalid-block-hooks/src/lib.rs
  crates/engine/invalid-block-hooks/src/witness.rs
  crates/engine/primitives/Cargo.toml
  crates/engine/primitives/src/invalid_block_hook.rs
  crates/engine/primitives/src/lib.rs
  crates/engine/tree/src/tree/invalid_block_hook.rs
  crates/engine/tree/src/tree/mod.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/engine.rs
  crates/node/builder/src/launch/mod.rs
  crates/node/core/src/dirs.rs
  crates/storage/storage-api/src/state.rs
Labels: C-enhancement, A-consensus, A-observability, A-trie

#10573 feat(exex): subscribe to notifications explicitly
  Cargo.lock
  book/developers/exex/hello-world.md
  book/developers/exex/remote.md
  book/developers/exex/tracking-state.md
  book/installation/source.md
  crates/exex/exex/Cargo.toml
  crates/exex/exex/src/context.rs
  crates/exex/exex/src/manager.rs
  crates/exex/test-utils/src/lib.rs
  crates/exex/types/Cargo.toml
  crates/exex/types/src/head.rs
  crates/exex/types/src/lib.rs
  crates/node/builder/src/launch/exex.rs
Labels: C-enhancement, S-blocked, M-changelog, A-exex

#10738 fix: unwind_to should be exclusive
  crates/stages/stages/src/stages/headers.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-bug, A-staged-sync

#10733 chore(tree): propagate on_new_persisted_block error
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-blockchain-tree

#10699 feat: test channel for pausing persistence receiver
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, C-test, A-blockchain-tree

#10680 Create CLI documentation with a Rust script (instead of Python) + style improvement
  .github/workflows/lint.yml
  book/cli/SUMMARY.md
  book/cli/help.py
  book/cli/help.rs
  book/cli/reth.md
  book/cli/reth/config.md
  book/cli/reth/db.md
  book/cli/reth/db/checksum.md
  book/cli/reth/db/clear.md
  book/cli/reth/db/clear/mdbx.md
  book/cli/reth/db/clear/static-file.md
  book/cli/reth/db/diff.md
  book/cli/reth/db/drop.md
  book/cli/reth/db/get.md
  book/cli/reth/db/get/mdbx.md
  book/cli/reth/db/get/static-file.md
  book/cli/reth/db/list.md
  book/cli/reth/db/path.md
  book/cli/reth/db/stats.md
  book/cli/reth/db/version.md
  book/cli/reth/debug.md
  book/cli/reth/debug/build-block.md
  book/cli/reth/debug/execution.md
  book/cli/reth/debug/in-memory-merkle.md
  book/cli/reth/debug/merkle.md
  book/cli/reth/debug/replay-engine.md
  book/cli/reth/dump-genesis.md
  book/cli/reth/import.md
  book/cli/reth/init-state.md
  book/cli/reth/init.md
  book/cli/reth/node.md
  book/cli/reth/p2p.md
  book/cli/reth/p2p/body.md
  book/cli/reth/p2p/header.md
  book/cli/reth/p2p/rlpx.md
  book/cli/reth/p2p/rlpx/ping.md
  book/cli/reth/prune.md
  book/cli/reth/recover.md
  book/cli/reth/recover/storage-tries.md
  book/cli/reth/stage.md
  book/cli/reth/stage/drop.md
  book/cli/reth/stage/dump.md
  book/cli/reth/stage/dump/account-hashing.md
  book/cli/reth/stage/dump/execution.md
  book/cli/reth/stage/dump/merkle.md
  book/cli/reth/stage/dump/storage-hashing.md
  book/cli/reth/stage/run.md
  book/cli/reth/stage/unwind.md
  book/cli/reth/stage/unwind/num-blocks.md
  book/cli/reth/stage/unwind/to-block.md
  book/cli/update.sh
Labels: C-docs, A-cli

#10765 chore(reth-primitives): clean unused file
  crates/primitives/src/transaction/eip1559.rs
  crates/primitives/src/transaction/eip2930.rs
  crates/primitives/src/transaction/eip4844.rs
  crates/primitives/src/transaction/eip7702.rs
  crates/primitives/src/transaction/legacy.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/optimism.rs
Labels: C-debt

#10760 testing: clean up reth-primitives import
  Cargo.lock
  testing/ef-tests/Cargo.toml
  testing/ef-tests/src/models.rs
  testing/testing-utils/Cargo.toml
  testing/testing-utils/src/generators.rs
  testing/testing-utils/src/genesis_allocator.rs
Labels: C-debt

#10761 storage: clean up reth-primitives import
  Cargo.lock
  crates/storage/db-common/Cargo.toml
  crates/storage/db-common/src/init.rs
  crates/storage/errors/Cargo.toml
  crates/storage/errors/src/provider.rs
  crates/storage/storage-api/Cargo.toml
  crates/storage/storage-api/src/account.rs
  crates/storage/storage-api/src/block.rs
  crates/storage/storage-api/src/block_hash.rs
  crates/storage/storage-api/src/block_id.rs
  crates/storage/storage-api/src/header.rs
  crates/storage/storage-api/src/noop.rs
  crates/storage/storage-api/src/receipts.rs
  crates/storage/storage-api/src/stage_checkpoint.rs
  crates/storage/storage-api/src/state.rs
  crates/storage/storage-api/src/storage.rs
  crates/storage/storage-api/src/transactions.rs
  crates/storage/storage-api/src/trie.rs
Labels: C-debt

#10766 transaction-pool: replace reth-primitive imports
  Cargo.lock
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/benches/truncate.rs
  crates/transaction-pool/src/blobstore/disk.rs
  crates/transaction-pool/src/blobstore/mem.rs
  crates/transaction-pool/src/blobstore/mod.rs
  crates/transaction-pool/src/blobstore/noop.rs
  crates/transaction-pool/src/blobstore/tracker.rs
  crates/transaction-pool/src/config.rs
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/identifier.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/ordering.rs
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/pool/events.rs
  crates/transaction-pool/src/pool/listener.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/pool/update.rs
  crates/transaction-pool/src/test_utils/gen.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/test_utils/pool.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/mod.rs
  crates/transaction-pool/tests/it/evict.rs
Labels: C-debt

#10717 feat: return executed block in eth payload builder
  Cargo.lock
  crates/ethereum/engine-primitives/Cargo.toml
  crates/ethereum/engine-primitives/src/payload.rs
  crates/ethereum/payload/Cargo.toml
  crates/ethereum/payload/src/lib.rs
  crates/payload/builder/src/lib.rs
  crates/payload/builder/src/test_utils.rs
Labels: A-block-building

#7416 feat: Include missing block id in error responses
  Cargo.lock
  crates/optimism/rpc/src/eth/pending_block.rs
  crates/optimism/rpc/src/eth/receipt.rs
  crates/rpc/rpc-api/src/debug.rs
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-api/src/otterscan.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-eth-api/src/helpers/block.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-api/src/helpers/fee.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/rpc/rpc-eth-api/src/helpers/receipt.rs
  crates/rpc/rpc-eth-api/src/helpers/state.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-types/src/error.rs
  crates/rpc/rpc-eth-types/src/gas_oracle.rs
  crates/rpc/rpc-eth-types/src/revm_utils.rs
  crates/rpc/rpc-server-types/src/result.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/engine.rs
  crates/rpc/rpc/src/eth/bundle.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/otterscan.rs
  crates/rpc/rpc/src/reth.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-bug, S-blocked, A-rpc

#10777 cli: replace reth-primitive imports
  Cargo.lock
  crates/cli/commands/Cargo.toml
  crates/cli/commands/src/common.rs
  crates/cli/commands/src/db/get.rs
  crates/cli/commands/src/db/list.rs
  crates/cli/commands/src/import.rs
  crates/cli/commands/src/init_state.rs
  crates/cli/commands/src/stage/dump/hashing_account.rs
  crates/cli/commands/src/stage/dump/merkle.rs
  crates/cli/commands/src/stage/unwind.rs
Labels: A-dependencies

#10768 consensus: replace reth-primitive imports
  Cargo.lock
  crates/consensus/auto-seal/Cargo.toml
  crates/consensus/auto-seal/src/client.rs
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/auto-seal/src/mode.rs
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/engine/event.rs
  crates/consensus/beacon/src/engine/forkchoice.rs
  crates/consensus/beacon/src/engine/hooks/mod.rs
  crates/consensus/beacon/src/engine/hooks/prune.rs
  crates/consensus/beacon/src/engine/hooks/static_file.rs
  crates/consensus/beacon/src/engine/invalid_headers.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/consensus/common/Cargo.toml
  crates/consensus/common/src/calc.rs
  crates/consensus/common/src/validation.rs
  crates/consensus/consensus/Cargo.toml
  crates/consensus/consensus/src/lib.rs
  crates/consensus/consensus/src/noop.rs
  crates/consensus/consensus/src/test_utils.rs
Labels: C-enhancement

#10782 chore: re-export reth-consensus
  bin/reth/src/lib.rs
Labels: C-enhancement

#10772 Remove receipts fn in BuiltPayload
  crates/ethereum/engine-primitives/src/payload.rs
  crates/ethereum/payload/src/lib.rs
  crates/optimism/payload/src/builder.rs
  crates/optimism/payload/src/payload.rs
  crates/payload/builder/src/lib.rs
  crates/payload/builder/src/test_utils.rs
  crates/payload/primitives/src/traits.rs
Labels: A-block-building

#10693 feat: remove constraint of concrete type AnyTransactionReceipt for EthApiTypes::NetworkType
  Cargo.lock
  crates/e2e-test-utils/src/lib.rs
  crates/e2e-test-utils/src/node.rs
  crates/e2e-test-utils/src/rpc.rs
  crates/node/builder/src/builder/mod.rs
  crates/node/builder/src/launch/engine.rs
  crates/node/builder/src/launch/mod.rs
  crates/node/builder/src/rpc.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-eth-api/src/core.rs
  crates/rpc/rpc-eth-api/src/types.rs
  crates/rpc/rpc/src/otterscan.rs
Labels: A-rpc

#10763 feat(db): move reth-storage-api::ClientVersion and StoredBlockWithdrawals to reth-db-models
  Cargo.lock
  crates/node/core/Cargo.toml
  crates/node/core/src/version.rs
  crates/storage/db-api/src/models/blocks.rs
  crates/storage/db-api/src/models/mod.rs
  crates/storage/db-models/src/blocks.rs
  crates/storage/db-models/src/client_version.rs
  crates/storage/db-models/src/lib.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/lib.rs
  crates/storage/db/src/tables/mod.rs
  examples/rpc-db/Cargo.toml
  examples/rpc-db/src/main.rs
Labels: A-db

#9723 Implement `engine_getBlobsV1`
  Cargo.lock
  crates/node/builder/src/launch/engine.rs
  crates/node/builder/src/launch/mod.rs
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-engine-api/src/capabilities.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/error.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/lib.rs
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/blobstore/disk.rs
  crates/transaction-pool/src/blobstore/mem.rs
  crates/transaction-pool/src/blobstore/mod.rs
  crates/transaction-pool/src/blobstore/noop.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/traits.rs
Labels: A-rpc, M-prevent-stale

#10790 chore: bump revm inspectors
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc/src/debug.rs
Labels: A-dependencies

#10791 node: replace reth-primitive imports
  Cargo.lock
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/common.rs
  crates/node/core/Cargo.toml
  crates/node/core/src/args/debug.rs
  crates/node/core/src/args/pruning.rs
  crates/node/core/src/args/txpool.rs
  crates/node/core/src/cli/config.rs
  crates/node/core/src/node_config.rs
  crates/node/events/Cargo.toml
  crates/node/events/src/node.rs
Labels: C-debt

#10796 chore: rm unused kzg settings fn
  crates/node/core/src/node_config.rs
Labels: C-debt

#10802 trie: add unit tests for `TrieAccount`
  crates/trie/common/src/account.rs
Labels: C-test

#10737 feat: expose `ChainSpec` metrics
  crates/cli/commands/src/stage/run.rs
  crates/node/builder/src/launch/common.rs
  crates/node/metrics/src/chain.rs
  crates/node/metrics/src/lib.rs
  crates/node/metrics/src/server.rs
  etc/grafana/dashboards/overview.json
Labels: C-enhancement, A-observability

#10804 feat: support custom chainspec parser for op
  crates/optimism/bin/src/main.rs
  crates/optimism/cli/src/lib.rs
Labels: A-op-reth

#10805 chore: fix typo in chainspec
  bin/reth/src/cli/mod.rs
  crates/cli/cli/src/chainspec.rs
  crates/cli/commands/src/common.rs
  crates/cli/commands/src/dump_genesis.rs
  crates/cli/commands/src/node.rs
  crates/cli/commands/src/p2p/mod.rs
  crates/optimism/cli/src/lib.rs
Labels: C-enhancement

#10806 chore: bump alloy 0.3.3
  Cargo.lock
  Cargo.toml
  crates/primitives/src/transaction/compat.rs
  crates/primitives/src/transaction/mod.rs
  crates/storage/codecs/src/alloy/transaction/eip7702.rs
Labels: A-dependencies

#10799 fix(metrics): set sync metrics when blocks are added
  crates/engine/service/src/service.rs
  crates/engine/tree/src/persistence.rs
  crates/node/builder/src/launch/engine.rs
Labels: C-enhancement, A-observability, A-blockchain-tree

#10807 chore: unify empty payload building
  crates/ethereum/payload/src/lib.rs
  crates/optimism/payload/src/builder.rs
  crates/payload/basic/src/lib.rs
  crates/transaction-pool/src/noop.rs
Labels: C-enhancement, C-debt, A-block-building

#10809 chore: remove optimism feature from reth docs
  bin/reth/src/lib.rs
Labels: C-debt

#10814 Add client() getter to OpTransactionValidator
  crates/optimism/node/src/txpool.rs
Labels: A-op-reth

#10815 chore: bump revm-inspectors
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#10798 refactor: reduce `ProviderFactory` usage
  Cargo.lock
  bin/reth/src/commands/debug_cmd/execution.rs
  crates/cli/commands/src/import.rs
  crates/consensus/beacon/src/engine/hooks/static_file.rs
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/setup.rs
  crates/node/core/Cargo.toml
  crates/node/core/src/node_config.rs
  crates/optimism/cli/src/commands/build_pipeline.rs
  crates/stages/api/src/pipeline/builder.rs
  crates/stages/api/src/pipeline/mod.rs
  crates/static-file/static-file/src/segments/headers.rs
  crates/static-file/static-file/src/segments/mod.rs
  crates/static-file/static-file/src/segments/receipts.rs
  crates/static-file/static-file/src/segments/transactions.rs
  crates/static-file/static-file/src/static_file_producer.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent_view.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/traits/database_provider.rs
  crates/storage/provider/src/traits/full.rs
  crates/storage/provider/src/traits/mod.rs
  crates/storage/storage-api/Cargo.toml
  crates/storage/storage-api/src/database_provider.rs
  crates/storage/storage-api/src/lib.rs
  crates/trie/parallel/src/async_root.rs
  crates/trie/parallel/src/parallel_root.rs
Labels: C-enhancement, A-sdk

#10824 fix: prevent panic during enr conversion
  crates/net/discv5/src/lib.rs
  crates/net/network/src/network.rs
  crates/net/peers/src/node_record.rs
  crates/rpc/rpc-testing-util/tests/it/trace.rs
Labels: C-bug, A-rpc

#10819 chore: Remove `rethdb` `op-node` build tag from book
  book/run/optimism.md
Labels: C-docs, A-op-reth

#10781 chore(op): define type `reth_optimism_rpc::OpReceiptBuilder`
  Cargo.lock
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/eth/receipt.rs
  crates/rpc/rpc-eth-types/src/receipt.rs
Labels: C-debt, A-rpc, A-op-reth, A-sdk

#10786 chore(rpc): `LoadReceipt::build_transaction_receipt` default impl to impl for `EthApi`
  crates/rpc/rpc-eth-api/src/helpers/receipt.rs
  crates/rpc/rpc/src/eth/helpers/receipt.rs
Labels: C-debt, A-rpc, A-op-reth, A-sdk

#10830 chore: missing features in optimsim crates
  crates/optimism/bin/Cargo.toml
  crates/optimism/cli/Cargo.toml
Labels: A-dependencies, A-op-reth

#10681 feat(net): IP resolution in docker
  Cargo.lock
  Cargo.toml
  book/cli/reth/debug/execution.md
  book/cli/reth/debug/in-memory-merkle.md
  book/cli/reth/debug/merkle.md
  book/cli/reth/debug/replay-engine.md
  book/cli/reth/node.md
  book/cli/reth/p2p.md
  book/cli/reth/stage/run.md
  book/cli/reth/stage/unwind.md
  crates/net/nat/Cargo.toml
  crates/net/nat/src/lib.rs
  crates/net/nat/src/net_if.rs
  crates/node/core/src/args/network.rs
Labels: A-networking, O-docker

#10831 chore: crates/consensus - Use derive_more::Error rather than impl std:error:Error
  crates/consensus/consensus/src/lib.rs
Labels: C-debt, A-consensus

#10833 chore: lower persistence threshold
  crates/engine/tree/src/tree/config.rs
Labels: A-consensus

#10836 perf: use last key value
  crates/chain-state/src/in_memory.rs
Labels: C-perf

#10785 Move `EthBlocks::block_receipts` default impl to impl for `EthApi`
  crates/rpc/rpc-eth-api/src/helpers/block.rs
  crates/rpc/rpc/src/eth/helpers/block.rs
Labels: C-debt, A-rpc, A-op-reth, A-sdk

#10838 fix(libmdbx): do not panic on timeout when closing cursor
  crates/storage/libmdbx-rs/src/cursor.rs
Labels: C-bug, A-db

#10840 fix(libmdbx): renew tx on timeout when dropping cursor
  crates/storage/libmdbx-rs/src/cursor.rs
  crates/storage/libmdbx-rs/src/transaction.rs
Labels: C-bug, A-db

#10843 fix(tree): avoid holding two locks simultaneously
  crates/chain-state/src/in_memory.rs
Labels: C-bug, A-consensus

#10846 feat(grafana): add stacked block processing latency graph
  etc/grafana/dashboards/overview.json
Labels: C-enhancement, A-observability, A-blockchain-tree

#10848 meta: add etc/ CODEOWNERS
  .github/CODEOWNERS
Labels: A-meta

#10852 Add pub visibility modifiers to some op executer types
  crates/optimism/evm/src/execute.rs
Labels: A-op-reth

#10857 chore: remove `prune_modes` arg from `BlockchainTree::new`
  Cargo.lock
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  crates/blockchain-tree/Cargo.toml
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/node/builder/src/launch/common.rs
Labels: C-debt

#10666 perf(engine): parallel storage roots
  Cargo.lock
  crates/blockchain-tree/src/chain.rs
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/tree/mod.rs
  crates/storage/provider/src/providers/consistent_view.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/trie/parallel/benches/root.rs
  crates/trie/parallel/src/parallel_root.rs
  crates/trie/trie/src/trie.rs
Labels: C-perf, A-consensus

#10862 chore(grafana): display empty string if no cargo features are available
  etc/grafana/dashboards/overview.json
Labels: A-observability

#10866 fix: revert header error message change
  crates/rpc/rpc-eth-types/src/error.rs
Labels: A-rpc

#10859 dev: test vectors seed
  crates/cli/commands/src/test_vectors/tables.rs
Labels: C-test, A-ci

#10867 docs: minor evm doc changes
  crates/ethereum/evm/src/config.rs
  crates/optimism/evm/src/config.rs
Labels: C-docs

#10876 fix: use configured chainspec parser for commands
  crates/optimism/cli/src/commands/mod.rs
  crates/optimism/cli/src/lib.rs
Labels: C-bug, A-op-reth

#10873 fix(reth): bin/reth missing help msg of segment
  crates/cli/commands/Cargo.toml
Labels: C-bug, A-cli

#10883 fix: don't validate requests in optimism
  crates/optimism/consensus/src/lib.rs
Labels: C-bug, A-consensus, A-op-reth

#10884 chore(op): Clean up module `reth_optimism_rpc::eth::sequencer`
  crates/optimism/bin/src/main.rs
  crates/optimism/rpc/src/error.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/optimism/rpc/src/lib.rs
  crates/optimism/rpc/src/sequencer.rs
Labels: C-debt, A-rpc, A-op-reth

#10885 chore(op): Use `tokio::sync::OnceCell` to set `SequencerClient`
  crates/optimism/bin/src/main.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/eth/transaction.rs
Labels: C-debt, A-rpc, A-op-reth

#10886 chore(op): Move imports in `reth_optimism_rpc::sequencer` to module prelude
  crates/optimism/rpc/src/sequencer.rs
Labels: C-debt, A-rpc, A-op-reth

#10891 chore: bump alloy 0.3.5
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc-layer/Cargo.toml
  crates/rpc/rpc-types/Cargo.toml
Labels: A-dependencies

#10849 feat(evm-ethereum): add BlockAccessListExecutor
  crates/ethereum/evm/src/execute.rs
Labels: C-enhancement, A-execution

#10893 Fix: Allow missing docs for test modules
  crates/metrics/metrics-derive/tests/metrics.rs
  crates/metrics/metrics-derive/tests/trybuild.rs
  crates/net/network/tests/it/main.rs
  crates/rpc/rpc-testing-util/tests/it/main.rs
  crates/storage/libmdbx-rs/tests/cursor.rs
  crates/storage/libmdbx-rs/tests/environment.rs
  crates/storage/libmdbx-rs/tests/transaction.rs
Labels: C-debt

#10878 perf: improve genesis handling
  crates/chainspec/src/api.rs
  crates/chainspec/src/lib.rs
  crates/chainspec/src/spec.rs
  crates/cli/commands/src/common.rs
  crates/cli/commands/src/stage/drop.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/engine/tree/src/tree/mod.rs
  crates/ethereum/engine-primitives/src/payload.rs
  crates/ethereum/evm/src/execute.rs
  crates/exex/exex/src/backfill/job.rs
  crates/exex/exex/src/backfill/stream.rs
  crates/exex/test-utils/src/lib.rs
  crates/node/builder/src/launch/common.rs
  crates/optimism/chainspec/src/base.rs
  crates/optimism/chainspec/src/base_sepolia.rs
  crates/optimism/chainspec/src/dev.rs
  crates/optimism/chainspec/src/op.rs
  crates/optimism/chainspec/src/op_sepolia.rs
  crates/optimism/cli/src/commands/import_receipts.rs
  crates/storage/db-common/src/init.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/history.rs
  examples/bsc-p2p/src/chainspec.rs
  examples/polygon-p2p/src/chain_cfg.rs
Labels: C-perf

#10895 feat(evm-optimism): add OpBlockAccessListExecutor
  crates/optimism/evm/src/execute.rs
Labels: C-enhancement, A-execution, A-op-reth

#10903 chore: fix ci
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc/src/otterscan.rs
Labels: A-dependencies

#10908 chore: add is granite active at timestamp
  crates/ethereum-forks/src/hardforks/optimism.rs
Labels: A-op-reth

#10918 feat(trie): `TrieInput`
  crates/chain-state/src/in_memory.rs
  crates/chain-state/src/memory_overlay.rs
  crates/revm/src/test_utils.rs
  crates/rpc/rpc-eth-types/src/cache/db.rs
  crates/storage/provider/src/providers/bundle_state_provider.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/macros.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/storage-api/src/trie.rs
  crates/trie/db/src/state.rs
  crates/trie/trie/src/input.rs
  crates/trie/trie/src/lib.rs
Labels: C-enhancement, A-trie

#10920 feat(trie): async root intermediate nodes
  crates/trie/parallel/benches/root.rs
  crates/trie/parallel/src/async_root.rs
Labels: C-enhancement, A-trie

#10929 feat(trie): integrate `TrieInput` into `StateProofProvider` methods
  crates/chain-state/src/in_memory.rs
  crates/chain-state/src/memory_overlay.rs
  crates/engine/invalid-block-hooks/src/witness.rs
  crates/revm/src/test_utils.rs
  crates/rpc/rpc-eth-types/src/cache/db.rs
  crates/rpc/rpc/src/debug.rs
  crates/storage/provider/src/providers/bundle_state_provider.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/macros.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/storage-api/src/trie.rs
  crates/trie/db/src/proof.rs
  crates/trie/db/src/witness.rs
  crates/trie/trie/src/input.rs
  crates/trie/trie/src/proof.rs
  crates/trie/trie/src/witness.rs
Labels: C-enhancement, C-perf, A-trie

#10930 feat(trie): integrate `TrieInput` into `ParallelStateRoot` & `AsyncStateRoot`
  crates/blockchain-tree/src/chain.rs
  crates/engine/tree/src/tree/mod.rs
  crates/trie/parallel/benches/root.rs
  crates/trie/parallel/src/async_root.rs
  crates/trie/parallel/src/parallel_root.rs
  crates/trie/trie/src/input.rs
Labels: C-enhancement, A-trie

#10844 feat(engine): compare invalid block witness against a healthy node
  Cargo.lock
  book/cli/reth/node.md
  crates/engine/invalid-block-hooks/Cargo.toml
  crates/engine/invalid-block-hooks/src/witness.rs
  crates/engine/tree/src/tree/mod.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/common.rs
  crates/node/core/src/args/debug.rs
  crates/node/core/src/args/mod.rs
Labels: C-enhancement, A-consensus, A-cli, A-trie

#10921 refactor: make `reth-prune` independent of concrete `DatabaseProvider`
  Cargo.lock
  crates/consensus/beacon/src/engine/hooks/prune.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/engine/service/src/service.rs
  crates/engine/tree/src/persistence.rs
  crates/prune/prune/Cargo.toml
  crates/prune/prune/src/builder.rs
  crates/prune/prune/src/db_ext.rs
  crates/prune/prune/src/lib.rs
  crates/prune/prune/src/pruner.rs
  crates/prune/prune/src/segments/mod.rs
  crates/prune/prune/src/segments/receipts.rs
  crates/prune/prune/src/segments/set.rs
  crates/prune/prune/src/segments/static_file/headers.rs
  crates/prune/prune/src/segments/static_file/receipts.rs
  crates/prune/prune/src/segments/static_file/transactions.rs
  crates/prune/prune/src/segments/user/account_history.rs
  crates/prune/prune/src/segments/user/history.rs
  crates/prune/prune/src/segments/user/receipts.rs
  crates/prune/prune/src/segments/user/receipts_by_logs.rs
  crates/prune/prune/src/segments/user/sender_recovery.rs
  crates/prune/prune/src/segments/user/storage_history.rs
  crates/prune/prune/src/segments/user/transaction_lookup.rs
  crates/stages/stages/src/stages/prune.rs
  crates/static-file/static-file/src/static_file_producer.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/storage-api/src/database_provider.rs
Labels: A-sdk

#10942 fix(exex): do not advance backfill range twice
  crates/exex/exex/src/backfill/stream.rs
Labels: C-bug, A-exex

#10944 chore(op): remove redundant op feature from `reth-optimism-consensus`
  crates/optimism/consensus/src/proof.rs
Labels: C-debt, A-op-reth

#10872 fix(rpc): add fee/value and balance to insufficient funds RPC error
  Cargo.lock
  crates/rpc/rpc-eth-types/src/error.rs
  crates/rpc/rpc-eth-types/src/revm_utils.rs
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-bug, A-rpc

#10841 error: use derive-more `Error` for deriving error
  crates/net/p2p/src/error.rs
  crates/net/p2p/src/headers/error.rs
  crates/primitives-traits/src/integer_list.rs
  crates/primitives/src/transaction/error.rs
  crates/storage/errors/src/writer.rs
Labels: C-debt

#10510 Move cfg_env and block_env configuration from PayloadBuilderAttributes into PayloadBuilder
  Cargo.lock
  crates/ethereum/engine-primitives/Cargo.toml
  crates/ethereum/engine-primitives/src/lib.rs
  crates/ethereum/engine-primitives/src/payload.rs
  crates/ethereum/payload/Cargo.toml
  crates/ethereum/payload/src/lib.rs
  crates/evm/src/lib.rs
  crates/optimism/payload/src/builder.rs
  crates/optimism/payload/src/payload.rs
  crates/payload/basic/src/lib.rs
  crates/payload/primitives/src/traits.rs
  examples/custom-engine-types/src/main.rs
Labels: C-debt, A-block-building

#10754 execution: add transaction and header AT to `ConfigureEvmEnv`
  crates/ethereum/evm/src/lib.rs
  crates/evm/src/lib.rs
  crates/optimism/evm/src/lib.rs
  examples/custom-evm/src/main.rs
  examples/stateful-precompile/src/main.rs
Labels: A-sdk

#10952 chore: include network primitives in workspace
  Cargo.toml
Labels: A-dependencies

#10787 feat(exex): backfill on subscription with head
  clippy.toml
  crates/exex/exex/Cargo.toml
  crates/exex/exex/src/context.rs
  crates/exex/exex/src/manager.rs
  crates/exex/test-utils/src/lib.rs
  crates/exex/types/src/head.rs
  crates/node/builder/src/launch/exex.rs
  crates/prune/prune/src/pruner.rs
Labels: C-enhancement, A-exex

#10954 chore: move eip2935 impl
  crates/evm/src/system_calls/eip2935.rs
  crates/evm/src/system_calls/mod.rs
Labels: A-execution

#10957 chore(trie): early return EMPTY_ROOT_HASH
  crates/rpc/rpc-types-compat/src/engine/payload.rs
  crates/trie/common/src/root.rs
Labels: C-perf

#10839 feat(cli): enable witness invalid block hook by default
  book/cli/reth/node.md
  crates/node/core/src/args/debug.rs
Labels: C-enhancement, A-cli

#10454 perf(rpc): use only Revm cache for execution witness
  crates/rpc/rpc/src/debug.rs
Labels: C-perf, A-rpc, S-stale

#10962 feat: move next block cfg and env to configureevm
  Cargo.lock
  crates/ethereum/evm/src/lib.rs
  crates/ethereum/payload/Cargo.toml
  crates/ethereum/payload/src/lib.rs
  crates/evm/src/lib.rs
  crates/node/api/src/lib.rs
  crates/optimism/evm/src/lib.rs
  crates/optimism/payload/src/builder.rs
  examples/custom-evm/src/main.rs
  examples/stateful-precompile/src/main.rs
Labels: A-execution

#10970 docs: add geth reference for call fee check
  crates/rpc/rpc-eth-types/src/revm_utils.rs
Labels: C-bug

#10973 fix(trie): remove `debug_assert` for storage root
  crates/trie/trie/src/witness.rs
Labels: C-bug, A-trie

#10982 chore: bump revm and inspectors
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#10969 chore: change `BlockAndProofV1` to use alloy_eips instead
  Cargo.lock
  crates/rpc/rpc-api/Cargo.toml
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/lib.rs
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/blobstore/disk.rs
  crates/transaction-pool/src/blobstore/mem.rs
  crates/transaction-pool/src/blobstore/mod.rs
  crates/transaction-pool/src/blobstore/noop.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/traits.rs
Labels: S-blocked

#10977 chore: move eip4788 impl
  crates/evm/src/system_calls/eip4788.rs
  crates/evm/src/system_calls/mod.rs
Labels: A-execution

#10985 feat: extend pool configuration
  book/cli/reth/node.md
  crates/node/core/src/args/txpool.rs
  crates/transaction-pool/src/config.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: A-tx-pool

#10988 chore: make error msg conform to normal usage
  crates/stages/stages/src/stages/sender_recovery.rs
Labels: A-observability

#10993 emv: add `BlockHeader` trait and default `fill_block_env`
  Cargo.lock
  crates/ethereum/evm/src/lib.rs
  crates/evm/Cargo.toml
  crates/evm/src/lib.rs
  crates/optimism/evm/src/lib.rs
  crates/primitives-traits/src/header/mod.rs
  crates/primitives-traits/src/lib.rs
  examples/custom-evm/src/main.rs
  examples/stateful-precompile/src/main.rs
Labels: A-execution
