Repository paradigmxyz/reth, pull requests merged in 2024-06, with the labels that each got.

#8533 fix: pruner config use toml over default
  crates/node/builder/src/launch/common.rs
Labels: C-bug

#8535 improve `estimate_gas_with`
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/storage/storage-api/src/block_id.rs
  crates/storage/storage-api/src/state.rs
Labels: C-debt, A-rpc

#8531 test(rpc): payload V4 decode hashing
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: C-test

#8551 add `unnecessary_struct_initialization` and `string_lit_as_bytes`
  Cargo.toml
  crates/net/network/src/discovery.rs
  crates/rpc/rpc/src/eth/api/server.rs
Labels: A-meta

#8548 fix auto-seal consensus duplicate notification
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/auto-seal/src/task.rs
  crates/node/builder/src/launch/mod.rs
Labels: C-bug, A-consensus

#8560 docs: mention beacon node API endpoint for ecotone
  book/run/optimism.md
Labels: C-docs, C-enhancement, A-op-reth

#8561 chore: downgrade error message
  crates/tokio-util/src/event_sender.rs
Labels: A-observability

#7212 feat(cli): override static files datadir
  bin/reth/src/commands/db/mod.rs
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/import_op.rs
  bin/reth/src/commands/import_receipts_op.rs
  bin/reth/src/commands/init_cmd.rs
  bin/reth/src/commands/init_state.rs
  bin/reth/src/commands/node/mod.rs
  bin/reth/src/commands/p2p/mod.rs
  bin/reth/src/commands/recover/storage_tries.rs
  bin/reth/src/commands/stage/drop.rs
  bin/reth/src/commands/stage/dump/mod.rs
  bin/reth/src/commands/stage/run.rs
  bin/reth/src/commands/stage/unwind.rs
  book/cli/reth/db.md
  book/cli/reth/db/checksum.md
  book/cli/reth/db/clear.md
  book/cli/reth/db/clear/mdbx.md
  book/cli/reth/db/clear/static-file.md
  book/cli/reth/db/diff.md
  book/cli/reth/db/drop.md
  book/cli/reth/db/get.md
  book/cli/reth/db/get/mdbx.md
  book/cli/reth/db/get/static-file.md
  book/cli/reth/db/list.md
  book/cli/reth/db/path.md
  book/cli/reth/db/stats.md
  book/cli/reth/db/version.md
  book/cli/reth/import.md
  book/cli/reth/init-state.md
  book/cli/reth/init.md
  book/cli/reth/node.md
  book/cli/reth/p2p.md
  book/cli/reth/recover/storage-tries.md
  book/cli/reth/stage/drop.md
  book/cli/reth/stage/dump.md
  book/cli/reth/stage/run.md
  book/cli/reth/stage/unwind.md
  book/cli/reth/stage/unwind/num-blocks.md
  book/cli/reth/stage/unwind/to-block.md
  crates/node-core/src/args/datadir_args.rs
  crates/node-core/src/args/mod.rs
  crates/node-core/src/dirs.rs
  crates/node-core/src/node_config.rs
  crates/node/builder/src/builder/mod.rs
  crates/node/builder/src/launch/common.rs
Labels: C-enhancement, A-cli, A-static-files

#7190 feat(trie): hash post state in parallel
  Cargo.lock
  Cargo.toml
  crates/trie/trie/Cargo.toml
  crates/trie/trie/benches/hash_post_state.rs
  crates/trie/trie/src/state.rs
Labels: C-perf, A-trie

#8566 release: 0.2.0-beta.8
  Cargo.lock
  Cargo.toml
Labels: A-meta

#8567 chore: log endpoint as path
  crates/node/builder/src/rpc.rs
Labels: A-observability

#8569 add `explicit_into_iter_loop` clippy lint
  Cargo.toml
  crates/blockchain-tree/src/block_indices.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/net/discv4/src/config.rs
  crates/net/discv4/src/lib.rs
  crates/net/network/src/cache.rs
  crates/net/network/src/state.rs
  crates/net/network/src/transactions/fetcher.rs
  crates/net/p2p/src/full_block.rs
  crates/primitives/src/stage/checkpoints.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/stages/stages/src/stages/hashing_account.rs
  crates/stages/stages/src/stages/hashing_storage.rs
  crates/stages/stages/src/stages/merkle.rs
  crates/storage/provider/src/bundle_state/state_changes.rs
  crates/storage/provider/src/bundle_state/state_reverts.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/trie/trie/benches/hash_post_state.rs
Labels: C-debt

#8488 feat: Support unnamed OP chains
  crates/net/discv5/src/network_stack_id.rs
  crates/primitives/src/chain/spec.rs
Labels: A-op-reth

#8570 add `explicit_iter_loop` clippy lint
  Cargo.toml
  bin/reth/src/commands/debug_cmd/build_block.rs
  crates/blockchain-tree/src/block_buffer.rs
  crates/blockchain-tree/src/block_indices.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/ethereum-forks/src/hardfork.rs
  crates/exex/src/manager.rs
  crates/metrics/metrics-derive/src/expand.rs
  crates/net/discv4/src/lib.rs
  crates/net/discv5/src/filter.rs
  crates/net/network/src/peers/manager.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/state.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
  crates/primitives/src/prune/mod.rs
  crates/primitives/src/request.rs
  crates/primitives/src/transaction/pooled.rs
  crates/primitives/src/trie/hash_builder/state.rs
  crates/prune/src/segments/headers.rs
  crates/revm/src/state_change.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/gas_oracle.rs
  crates/rpc/rpc/src/eth/logs_utils.rs
  crates/stages/stages/src/stages/hashing_account.rs
  crates/storage/db/src/static_file/mod.rs
  crates/storage/libmdbx-rs/benches/transaction.rs
  crates/storage/libmdbx-rs/src/txn_manager.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/transaction-pool/benches/reorder.rs
  crates/transaction-pool/benches/truncate.rs
  crates/transaction-pool/src/pool/blob.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/trie/parallel/src/async_root.rs
  crates/trie/parallel/src/parallel_root.rs
  crates/trie/trie/benches/prefix_set.rs
  crates/trie/trie/src/hashed_cursor/post_state.rs
  crates/trie/trie/src/proof.rs
  crates/trie/trie/src/state.rs
  testing/ef-tests/src/cases/blockchain_test.rs
  testing/ef-tests/src/models.rs
Labels: C-debt

#8574 add a few more lints
  Cargo.toml
  crates/net/network/src/peers/manager.rs
  crates/tracing/src/lib.rs
Labels: C-debt

#8571 feat: Add fjordTime to OP genesis config
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/revm/config.rs
Labels: A-op-reth

#8576 chore: rm println
  crates/node/builder/src/launch/common.rs
Labels: C-debt

#8584 feat(op): docs sync to tip
  book/run/sync-op-mainnet.md
Labels: C-docs, A-op-reth

#8585 impl. set_block_gas_limit for EthTransactionValidatorBuilder
  crates/transaction-pool/src/validate/eth.rs
Labels: C-enhancement, A-tx-pool

#8515 feat: move core rpc server types to standalone crate
  Cargo.lock
  Cargo.toml
  crates/node-core/Cargo.toml
  crates/node-core/src/args/gas_price_oracle.rs
  crates/node-core/src/args/rpc_server.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-server-types/Cargo.toml
  crates/rpc/rpc-server-types/src/constants.rs
  crates/rpc/rpc-server-types/src/lib.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/api/fee_history.rs
  crates/rpc/rpc/src/eth/gas_oracle.rs
Labels: A-rpc

#8583 chore: remove `StaticFileProvider` field from `StaticFileProducer`
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/import_op.rs
  bin/reth/src/commands/stage/unwind.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/node/builder/src/launch/common.rs
  crates/stages/api/src/pipeline/mod.rs
  crates/stages/stages/src/lib.rs
  crates/stages/stages/src/sets.rs
  crates/static-file/src/static_file_producer.rs
Labels: C-debt, A-static-files

#8593 fix: metrics typo
  crates/node-core/src/metrics/version_metrics.rs
Labels: A-observability

#8596 chore: bump alloy 5796024
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-debt, A-consensus

#8598 ci: only run action lint if action changed
  .github/workflows/lint-actions.yml
Labels: A-ci

#8597 feat: move RPC cache constants and type
  crates/node-core/src/args/rpc_state_cache.rs
  crates/rpc/rpc-server-types/src/constants.rs
  crates/rpc/rpc/src/eth/cache/config.rs
Labels: C-debt, A-rpc

#8508 chore(net): `get` and `peek` for `LruCache`
  crates/net/network/src/cache.rs
Labels: C-debt, A-networking

#8573 feature: loglevel value parser
  Cargo.lock
  crates/node-core/Cargo.toml
  crates/node-core/src/args/database.rs
  crates/storage/errors/Cargo.toml
  crates/storage/errors/src/db.rs
Labels: A-cli

#8476 chore: disable default feature for reth-db in workspace
  Cargo.toml
  crates/node/builder/Cargo.toml
  crates/storage/provider/Cargo.toml
Labels: C-debt

#8538 chore(rpc): trait for blocking task
  Cargo.lock
  crates/net/network/src/cache.rs
  crates/node-core/Cargo.toml
  crates/node-core/src/args/database.rs
  crates/optimism/rpc/src/transaction.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/traits/blocking_task.rs
  crates/rpc/rpc/src/eth/api/traits/mod.rs
  crates/rpc/rpc/src/eth/api/traits/transaction.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/storage/db-api/src/models/mod.rs
  crates/storage/errors/Cargo.toml
  crates/storage/errors/src/db.rs
  crates/tasks/src/pool.rs
Labels: A-rpc, A-op-reth

#8615 chore(node-builder): use datadir from config
  crates/node-core/src/node_config.rs
  crates/node/builder/src/builder/mod.rs
Labels: C-debt, A-sdk

#8617 feat(node-builder): expose block executor
  crates/node/builder/src/launch/mod.rs
  crates/node/builder/src/node.rs
Labels: C-enhancement, A-sdk

#8618 feat: add mgas per second log
  crates/node/events/src/node.rs
Labels: C-enhancement, A-observability

#8621 chore: add canonical cgroup docs in memory profiling docs
  book/developers/profiling.md
Labels: C-docs, C-enhancement, C-perf

#8600 fix: check for empty tx root in BlockTransactions::Uncle match
  crates/primitives/Cargo.toml
  crates/primitives/src/alloy_compat.rs
Labels: C-bug, A-utils

#8188 feat: resolve domains in enode strings
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  bin/reth/src/commands/p2p/mod.rs
  bin/reth/src/commands/stage/run.rs
  book/cli/reth/node.md
  book/cli/reth/p2p.md
  book/cli/reth/stage/run.md
  book/cli/reth/stage/unwind.md
  crates/net/common/src/lib.rs
  crates/net/network/src/config.rs
  crates/net/network/src/manager.rs
  crates/net/types/Cargo.toml
  crates/net/types/src/lib.rs
  crates/net/types/src/trusted_peer.rs
  crates/node-core/Cargo.toml
  crates/node-core/src/args/network.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/mod.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/net.rs
Labels: A-devp2p, A-cli, A-discv4, A-discv5

#8620 fix(op): fix import blocks benchmark
  book/run/sync-op-mainnet.md
Labels: C-docs, A-op-reth

#8634 Fix code spell lint in CI
  .github/workflows/lint.yml
  Makefile
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/metrics.rs
  crates/node/builder/src/components/builder.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
  crates/stages/stages/src/stages/headers.rs
  crates/storage/provider/src/providers/static_file/writer.rs
Labels: A-meta

#8636 test(exex): introduce utils for testing
  Cargo.lock
  Cargo.toml
  crates/exex/exex/Cargo.toml
  crates/exex/exex/src/context.rs
  crates/exex/exex/src/event.rs
  crates/exex/exex/src/lib.rs
  crates/exex/exex/src/manager.rs
  crates/exex/exex/src/notification.rs
  crates/exex/test-utils/Cargo.toml
  crates/exex/test-utils/src/lib.rs
  examples/exex/minimal/Cargo.toml
  examples/exex/minimal/src/main.rs
Labels: C-test, A-exex

#8601 chore: update CODEOWNERS for new crate structure
  CODEOWNERS
Labels: A-meta

#8473 fix: save last finalized block
  bin/reth/src/commands/stage/unwind.rs
  crates/blockchain-tree-api/src/lib.rs
  crates/blockchain-tree/Cargo.toml
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/externals.rs
  crates/blockchain-tree/src/noop.rs
  crates/blockchain-tree/src/shareable.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/stages/api/src/pipeline/mod.rs
  crates/storage/db/src/tables/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/traits/finalized_block.rs
  crates/storage/provider/src/traits/mod.rs
Labels: C-enhancement, A-staged-sync, A-blockchain-tree, C-security

#8646 chore: change build_empty_payload to require &self
  crates/optimism/payload/src/builder.rs
  crates/payload/basic/src/lib.rs
  crates/payload/ethereum/src/lib.rs
  examples/custom-engine-types/src/main.rs
  examples/custom-payload-builder/src/generator.rs
  examples/custom-payload-builder/src/job.rs
Labels: A-block-building

#8645 Add Fjord timestamp conditions to OP+Base Mainnet+Sepolia
  crates/primitives/src/chain/spec.rs
Labels: A-op-reth

#8649 feat: add missing payload behaviour
  crates/optimism/payload/src/builder.rs
  crates/payload/basic/src/lib.rs
Labels: C-enhancement, C-perf, A-block-building, A-op-reth

#8652 fix: do not calculate requests root pre-prague in dev mode
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/auto-seal/src/task.rs
Labels: C-bug, A-rpc, C-test

#8654 chore: Release 0.2.0-beta.9
  Cargo.lock
  Cargo.toml
Labels: A-meta

#8655 chore: add enum_glob_use warn lint
  Cargo.toml
Labels: A-utils

#8656 chore: bump revm-inspectors 53aa2b2
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#8648 feat(node-builder): move network setup to node-builder launch/ BuilderContext types
  Cargo.lock
  crates/node-core/Cargo.toml
  crates/node-core/src/node_config.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/builder/mod.rs
  crates/node/builder/src/launch/mod.rs
Labels: C-enhancement, A-sdk

#8662 chore: reintroduce receipts verification debug log
  Cargo.lock
  crates/ethereum/consensus/Cargo.toml
  crates/ethereum/consensus/src/validation.rs
  crates/optimism/consensus/Cargo.toml
  crates/optimism/consensus/src/validation.rs
Labels: A-observability

#8653 test(exex): improve `PollOnce` trait error handling
  Cargo.lock
  crates/exex/test-utils/Cargo.toml
  crates/exex/test-utils/src/lib.rs
  examples/exex/minimal/src/main.rs
Labels: C-test, A-exex

#8664 fix: ensure tx forwarder is set
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
Labels: C-bug, A-rpc, A-op-reth

#8660 refactor: extract trusted peer resolve into separate function
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/mod.rs
Labels: C-debt, A-cli

#8490 chore: move ethereum payload builder to ethereum
  Cargo.toml
  crates/ethereum/payload/Cargo.toml
  crates/ethereum/payload/src/lib.rs
Labels: S-blocked, A-meta

#8671 chore: move static file crates in static file folder
  CODEOWNERS
  Cargo.toml
  crates/static-file/static-file/Cargo.toml
  crates/static-file/static-file/README.md
  crates/static-file/static-file/src/event.rs
  crates/static-file/static-file/src/lib.rs
  crates/static-file/static-file/src/segments/headers.rs
  crates/static-file/static-file/src/segments/mod.rs
  crates/static-file/static-file/src/segments/receipts.rs
  crates/static-file/static-file/src/segments/transactions.rs
  crates/static-file/static-file/src/static_file_producer.rs
  crates/static-file/types/Cargo.toml
  crates/static-file/types/src/compression.rs
  crates/static-file/types/src/filters.rs
  crates/static-file/types/src/lib.rs
  crates/static-file/types/src/segment.rs
Labels: C-debt, A-static-files

#8675 fix: bad unwrap on resolve
  crates/payload/basic/src/lib.rs
  crates/payload/builder/src/error.rs
Labels: C-bug, A-op-reth

#8658 example(exex): tests for OP Bridge
  Cargo.lock
  crates/exex/test-utils/src/lib.rs
  examples/exex/op-bridge/Cargo.toml
  examples/exex/op-bridge/src/main.rs
  testing/testing-utils/src/generators.rs
Labels: C-test, A-exex, C-example

#8663 chore: rm unused launch functions
  crates/rpc/rpc-builder/src/auth.rs
Labels: C-debt, A-rpc

#8685 feat: add ExecutionPayloadV2 to ExecutionPayloadInputV2 conversion
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: C-enhancement, A-rpc, A-utils

#8686 chore: add link to new_payload_v4 docs
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-docs, A-consensus

#8689 fix: ensure jsonrpsee logs are off by default
  crates/tracing/src/layers.rs
Labels: C-enhancement, A-observability

#8639 chore(rpc): default trait methods `EthTransactions`
  Cargo.lock
  crates/evm/src/lib.rs
  crates/optimism/node/src/rpc.rs
  crates/optimism/rpc/src/block.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/traits/block.rs
  crates/rpc/rpc/src/eth/api/traits/blocking_task.rs
  crates/rpc/rpc/src/eth/api/traits/mod.rs
  crates/rpc/rpc/src/eth/api/traits/state.rs
  crates/rpc/rpc/src/eth/api/traits/transaction.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/bundle.rs
  crates/rpc/rpc/src/eth/mod.rs
  crates/rpc/rpc/src/eth/traits.rs
  crates/rpc/rpc/src/otterscan.rs
  crates/rpc/rpc/src/trace.rs
  crates/storage/storage-api/src/receipts.rs
  crates/tasks/Cargo.toml
  crates/tasks/src/lib.rs
  crates/transaction-pool/src/traits.rs
Labels: A-rpc, A-op-reth

#8640 chore(rpc): pending block helper trait
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  crates/rpc/rpc/src/eth/api/traits/mod.rs
  crates/rpc/rpc/src/eth/api/traits/pending_block.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/bundle.rs
Labels: S-blocked, A-rpc, A-op-reth

#8659 chore(rpc): `EthTransactions` default trait methods using pending block
  crates/rpc/rpc/Cargo.toml
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/traits/transaction.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/bundle.rs
  crates/rpc/rpc/src/otterscan.rs
  crates/rpc/rpc/src/trace.rs
Labels: A-rpc, A-op-reth

#8698 feat: remove Bandwidthmeter type
  Cargo.lock
  crates/net/common/Cargo.toml
  crates/net/common/src/bandwidth_meter.rs
  crates/net/common/src/lib.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/network.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/conn.rs
  crates/net/network/src/session/mod.rs
Labels: A-networking

#8701 chore: replace secp256k1 with fully qualified path
  crates/net/peers/src/lib.rs
  crates/net/peers/src/node_record.rs
  crates/net/peers/src/trusted_peer.rs
Labels: A-networking

#8703 docs: improve custom-evm example docs
  examples/custom-evm/src/main.rs
Labels: C-docs

#8691 chore: move workspace.package to top of Cargo.toml
  Cargo.toml
Labels: A-meta

#8694 feat: add launch_with_fn
  crates/node/builder/src/builder/states.rs
  crates/node/builder/src/launch/mod.rs
Labels: C-enhancement, A-sdk

#8693 feat: add ExExLauncher
  crates/node/builder/src/exex.rs
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/exex.rs
  crates/node/builder/src/launch/mod.rs
Labels: A-sdk, A-exex

#8712 feat: add secp256k1 feature in reth-network-peers
  Cargo.toml
  crates/net/discv4/Cargo.toml
  crates/net/discv5/Cargo.toml
  crates/net/dns/Cargo.toml
  crates/net/ecies/Cargo.toml
  crates/net/peers/Cargo.toml
  crates/net/peers/src/lib.rs
  crates/net/peers/src/node_record.rs
  crates/net/peers/src/trusted_peer.rs
Labels: C-enhancement, A-networking

#8719 chore(stages): remove `execute_inner` method
  crates/stages/stages/src/stages/execution.rs
Labels: A-staged-sync, C-debt

#8710 refactor: simplify `Receipts` implementation
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  crates/blockchain-tree/src/chain.rs
  crates/consensus/auto-seal/src/lib.rs
  crates/ethereum/payload/src/lib.rs
  crates/evm/execution-types/src/bundle.rs
  crates/evm/execution-types/src/chain.rs
  crates/net/downloaders/src/receipt_file_client.rs
  crates/optimism/payload/src/builder.rs
  crates/primitives/src/receipt.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  crates/storage/db-common/src/init.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/test_utils/blocks.rs
  examples/exex/op-bridge/src/main.rs
Labels: C-debt

#8082 feat: --debug.etherscan for fake consensus client
  Cargo.lock
  Cargo.toml
  book/cli/reth/node.md
  crates/consensus/debug-client/Cargo.toml
  crates/consensus/debug-client/src/client.rs
  crates/consensus/debug-client/src/lib.rs
  crates/consensus/debug-client/src/providers/etherscan.rs
  crates/consensus/debug-client/src/providers/mod.rs
  crates/consensus/debug-client/src/providers/rpc.rs
  crates/node-core/src/args/debug.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/mod.rs
Labels: C-enhancement, A-consensus

#8709 refactor: replace `BatchBlockExecutionOutput` by `BundleStateWithReceipts`
  Cargo.lock
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/import_receipts_op.rs
  crates/blockchain-tree/src/chain.rs
  crates/consensus/auto-seal/src/lib.rs
  crates/ethereum/evm/Cargo.toml
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/payload/src/lib.rs
  crates/evm/Cargo.toml
  crates/evm/execution-types/Cargo.toml
  crates/evm/execution-types/src/bundle.rs
  crates/evm/execution-types/src/chain.rs
  crates/evm/src/either.rs
  crates/evm/src/execute.rs
  crates/evm/src/noop.rs
  crates/evm/src/test_utils.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/payload/src/builder.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  crates/stages/stages/src/stages/execution.rs
  crates/storage/db-common/src/init.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/test_utils/blocks.rs
  examples/exex/op-bridge/src/main.rs
Labels: C-debt, A-execution

#8725 fix: dont panic on invalud fcu response
  crates/consensus/debug-client/src/client.rs
Labels: C-bug, A-consensus

#8684 feat: move `RethRpcConfig` to rpc-builder
  Cargo.lock
  crates/node-core/Cargo.toml
  crates/node-core/src/args/rpc_server.rs
  crates/node-core/src/cli/config.rs
  crates/node-core/src/lib.rs
  crates/node-core/src/node_config.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/lib.rs
  crates/node/builder/src/node.rs
  crates/node/builder/src/rpc.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/config.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-builder/tests/it/serde.rs
  crates/rpc/rpc-builder/tests/it/startup.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc-server-types/Cargo.toml
  crates/rpc/rpc-server-types/src/lib.rs
  crates/rpc/rpc-server-types/src/module.rs
Labels: C-debt, A-rpc

#8733 chore: disable currently failing engine hive tests with reasons
  .github/workflows/hive.yml
Labels: C-test, C-hivetest

#8720 feat(stages): send a notification to ExExes only when Execution stage commits
  crates/node/builder/src/launch/exex.rs
  crates/stages/api/src/pipeline/mod.rs
  crates/stages/api/src/stage.rs
  crates/stages/stages/src/stages/execution.rs
Labels: C-enhancement, A-staged-sync, A-exex

#8734 feat: add gas throughput debug log to execution progress
  crates/stages/stages/src/stages/execution.rs
Labels: C-enhancement, A-staged-sync, A-execution, A-observability

#8738 fix(db): format tracing log fields with Debug
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: C-bug, A-db

#8731 chore: add a few missing trait bounds
  crates/node/api/src/node.rs
  crates/node/builder/src/components/mod.rs
Labels: C-enhancement

#7018 chore(deps): bump http, hyper etc. to 1.0; jsonrpsee 0.23
  Cargo.lock
  Cargo.toml
  crates/consensus/debug-client/src/providers/rpc.rs
  crates/node-core/Cargo.toml
  crates/node-core/src/metrics/prometheus_exporter.rs
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/rpc.rs
  crates/rpc/ipc/src/server/mod.rs
  crates/rpc/ipc/src/server/rpc_service.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/cors.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-layer/Cargo.toml
  crates/rpc/rpc-layer/src/auth_client_layer.rs
  crates/rpc/rpc-layer/src/auth_layer.rs
  crates/rpc/rpc-layer/src/jwt_validator.rs
  crates/rpc/rpc-layer/src/lib.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/otterscan.rs
  crates/tasks/src/shutdown.rs
  deny.toml
  examples/beacon-api-sidecar-fetcher/Cargo.toml
  examples/beacon-api-sse/Cargo.toml
Labels: A-dependencies

#8690 refactor: move discv5 logic for op to reth-node-optimism
  Cargo.lock
  crates/node-core/src/args/network.rs
  crates/node/builder/src/builder/mod.rs
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/node.rs
Labels: A-op-reth

#8682 example(exex): tests for In Memory State
  Cargo.lock
  examples/exex/in-memory-state/Cargo.toml
  examples/exex/in-memory-state/src/main.rs
Labels: A-exex, C-example

#8730 refactor: rename `BundleStateWithReceipts` to `BlockExecutionOutcome`
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/import_receipts_op.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/bundle.rs
  crates/blockchain-tree/src/chain.rs
  crates/blockchain-tree/src/lib.rs
  crates/blockchain-tree/src/noop.rs
  crates/blockchain-tree/src/shareable.rs
  crates/consensus/auto-seal/src/lib.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/payload/src/lib.rs
  crates/evm/execution-types/src/bundle.rs
  crates/evm/execution-types/src/chain.rs
  crates/evm/src/either.rs
  crates/evm/src/execute.rs
  crates/evm/src/noop.rs
  crates/evm/src/test_utils.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/payload/src/builder.rs
  crates/payload/basic/src/lib.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  crates/stages/stages/src/stages/execution.rs
  crates/stages/stages/src/stages/headers.rs
  crates/storage/db-common/src/init.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/bundle_state/mod.rs
  crates/storage/provider/src/providers/bundle_state_provider.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/provider/src/traits/block.rs
  crates/storage/provider/src/traits/chain.rs
  crates/storage/provider/src/traits/state.rs
  crates/storage/storage-api/src/state.rs
  crates/transaction-pool/src/maintain.rs
  examples/exex/in-memory-state/src/main.rs
  examples/exex/minimal/src/main.rs
  examples/exex/op-bridge/src/main.rs
Labels: C-debt, A-execution

#8754 feat(engine): add payload conversion
  crates/consensus/beacon/src/engine/invalid_headers.rs
  crates/engine/tree/src/tree.rs
Labels: C-enhancement, A-consensus

#8487 fix: Use OptimismBeaconConsensus in the OptimismNode
  Cargo.lock
  crates/ethereum/node/Cargo.toml
  crates/ethereum/node/src/node.rs
  crates/exex/test-utils/Cargo.toml
  crates/exex/test-utils/src/lib.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/builder/mod.rs
  crates/node/builder/src/components/builder.rs
  crates/node/builder/src/components/consensus.rs
  crates/node/builder/src/components/mod.rs
  crates/node/builder/src/launch/mod.rs
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/node.rs
  examples/custom-engine-types/src/main.rs
Labels: A-op-reth

#8723 chore(rpc): `EthBlocks` default impl
  Cargo.lock
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/block.rs
  crates/optimism/rpc/src/lib.rs
  crates/optimism/rpc/src/receipt.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/fee_history.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/receipt.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/trace.rs
  crates/rpc/rpc/src/eth/api/traits/block.rs
  crates/rpc/rpc/src/eth/api/traits/call.rs
  crates/rpc/rpc/src/eth/api/traits/fee.rs
  crates/rpc/rpc/src/eth/api/traits/mod.rs
  crates/rpc/rpc/src/eth/api/traits/pending_block.rs
  crates/rpc/rpc/src/eth/api/traits/receipt.rs
  crates/rpc/rpc/src/eth/api/traits/state.rs
  crates/rpc/rpc/src/eth/api/traits/trace.rs
  crates/rpc/rpc/src/eth/api/traits/transaction.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/bundle.rs
Labels: S-blocked, C-debt, A-rpc, A-op-reth

#8761 fix: add `requests` in `ExecutionOutcome` extend
  crates/evm/execution-types/src/bundle.rs
Labels: C-bug, A-execution

#8756 feat: introduce payload types
  crates/e2e-test-utils/src/node.rs
  crates/engine-primitives/src/lib.rs
  crates/ethereum/engine-primitives/src/lib.rs
  crates/optimism/node/src/engine.rs
  crates/payload/primitives/src/lib.rs
  examples/custom-engine-types/src/main.rs
Labels: C-enhancement, A-block-building

#8762 chore: dont depend on reth-primitives
  Cargo.lock
  crates/evm/execution-errors/Cargo.toml
  crates/evm/execution-errors/src/lib.rs
Labels: A-dependencies

#8767 fix(rpc/trace): wrong calculate of block ommer rewards
  crates/rpc/rpc/src/trace.rs
Labels: C-bug, A-rpc

#8284 feat: introduce reth benchmark command
  Cargo.lock
  Cargo.toml
  bin/reth-bench/Cargo.toml
  bin/reth-bench/README.md
  bin/reth-bench/src/authenticated_transport.rs
  bin/reth-bench/src/bench/context.rs
  bin/reth-bench/src/bench/mod.rs
  bin/reth-bench/src/bench/new_payload_fcu.rs
  bin/reth-bench/src/bench/new_payload_only.rs
  bin/reth-bench/src/bench/output.rs
  bin/reth-bench/src/bench_mode.rs
  bin/reth-bench/src/main.rs
  bin/reth-bench/src/valid_payload.rs
  crates/node-core/src/args/benchmark_args.rs
  crates/node-core/src/args/mod.rs
Labels: C-enhancement, A-cli, C-benchmark

#8714 chore: remove HeaderSyncMode::Continuous & debug.continuous
  bin/reth/src/commands/common.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  bin/reth/src/commands/import.rs
  bin/reth/src/commands/stage/unwind.rs
  book/cli/reth/node.md
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/node-core/src/args/debug.rs
  crates/node-core/src/node_config.rs
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/mod.rs
  crates/node/builder/src/setup.rs
  crates/stages/stages/src/lib.rs
  crates/stages/stages/src/sets.rs
  crates/stages/stages/src/stages/headers.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/header_sync_gap.rs
  crates/storage/provider/src/traits/mod.rs
Labels: C-debt

#8784 fix: prometheus graceful shutdown
  crates/node-core/src/metrics/prometheus_exporter.rs
Labels: C-bug

#8771 fix: add a 5 second timeout for `tokio_runtime` shutdown
  crates/cli/runner/src/lib.rs
Labels: C-bug, A-cli

#8783 fix: disable sysinfo multithreading
  Cargo.lock
  crates/storage/db/Cargo.toml
Labels: C-bug

#8792 feat: support `no_std` for `reth-consensus`
  Cargo.lock
  crates/consensus/consensus/Cargo.toml
  crates/consensus/consensus/src/lib.rs
Labels: C-enhancement

#8790 feat: support `no_std` for `reth-storage-errors`
  Cargo.lock
  crates/storage/errors/Cargo.toml
  crates/storage/errors/src/db.rs
  crates/storage/errors/src/lib.rs
  crates/storage/errors/src/lockfile.rs
  crates/storage/errors/src/provider.rs
Labels: C-enhancement

#8757 feat: create init structure of tree state
  crates/engine/tree/src/tree.rs
Labels: C-enhancement, A-blockchain-tree

#8785 feat: log debug log directory on startup
  bin/reth/src/cli/mod.rs
  crates/node-core/src/args/log.rs
Labels: C-enhancement, A-observability

#8795 feat(tree-engine): invalid ancestor handling
  Cargo.lock
  crates/consensus/beacon/src/engine/invalid_headers.rs
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/tree.rs
Labels: A-consensus

#8797 fix: migration of ethereum-package to ethpandaops
  .github/workflows/assertoor.yml
  book/run/private-testnet.md
Labels: C-docs

#8779 docs(book): start documenting ExExes
  book/SUMMARY.md
  book/developers/developers.md
  book/developers/exex/exex.md
  book/developers/exex/hello-world.md
  book/developers/exex/how-it-works.md
Labels: C-docs, A-exex

#8768 refactor: disable default features for alloy workspace deps
  Cargo.toml
Labels: C-debt

#8718 feat: add append_receipts function
  crates/stages/stages/src/test_utils/test_db.rs
  crates/static-file/static-file/src/segments/receipts.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  crates/storage/provider/src/providers/static_file/metrics.rs
  crates/storage/provider/src/providers/static_file/writer.rs
Labels: C-perf, A-static-files

#8803 chore: bump inspectors and alloy
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc-types/src/lib.rs
Labels: A-dependencies

#8724 chore: move proof types and root functions from `primitives/proofs` into `reth-trie-common`
  Cargo.lock
  Cargo.toml
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/proofs.rs
  crates/primitives/src/proofs/traits.rs
  crates/revm/src/test_utils.rs
  crates/rpc/rpc-types-compat/Cargo.toml
  crates/rpc/rpc-types-compat/src/proof.rs
  crates/stages/types/Cargo.toml
  crates/stages/types/src/checkpoints.rs
  crates/storage/db-api/Cargo.toml
  crates/storage/db-api/src/models/mod.rs
  crates/storage/db/Cargo.toml
  crates/storage/db/src/tables/mod.rs
  crates/storage/provider/src/providers/bundle_state_provider.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/macros.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/test_utils/noop.rs
  crates/storage/storage-api/src/state.rs
  crates/trie/common/Cargo.toml
  crates/trie/common/src/account.rs
  crates/trie/common/src/hash_builder/mod.rs
  crates/trie/common/src/hash_builder/state.rs
  crates/trie/common/src/hash_builder/value.rs
  crates/trie/common/src/lib.rs
  crates/trie/common/src/mask.rs
  crates/trie/common/src/nibbles.rs
  crates/trie/common/src/nodes/branch.rs
  crates/trie/common/src/nodes/mod.rs
  crates/trie/common/src/proofs.rs
  crates/trie/common/src/root.rs
  crates/trie/common/src/storage.rs
  crates/trie/common/src/subnode.rs
  crates/trie/parallel/src/async_root.rs
  crates/trie/parallel/src/parallel_root.rs
  crates/trie/trie/Cargo.toml
  crates/trie/trie/benches/trie_root.rs
  crates/trie/trie/src/lib.rs
  crates/trie/trie/src/proof.rs
  crates/trie/trie/src/test_utils.rs
  crates/trie/trie/src/trie.rs
  crates/trie/types/src/account.rs
Labels: C-enhancement

#8799 chore(rpc): impl `EthApiServer` helper traits on type like `EthApi`
  Cargo.lock
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/block.rs
  crates/optimism/rpc/src/lib.rs
  crates/optimism/rpc/src/pending_block.rs
  crates/rpc/rpc/src/eth/api/block.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/fees.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/pending_block.rs
  crates/rpc/rpc/src/eth/api/state.rs
  crates/rpc/rpc/src/eth/api/trace.rs
  crates/rpc/rpc/src/eth/api/traits/pending_block.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/mod.rs
Labels: C-debt, A-rpc, A-op-reth

#8806 fix(grafana): fix broken panel
  etc/docker-compose.yml
  etc/grafana/dashboards/reth-mempool.json
Labels: C-bug, A-observability

#8807 fix: windows build
  crates/storage/db/src/implementation/mdbx/mod.rs
Labels: C-bug

#8808 fix: only check that base fee is not zero
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: A-rpc, A-consensus, A-utils

#8810 chore: remove educe dependency
  Cargo.lock
  crates/net/ecies/Cargo.toml
  crates/net/ecies/src/algorithm.rs
Labels: A-dependencies

#8809 chore: rm HasRemoteAddr trait
  Cargo.lock
  crates/net/common/Cargo.toml
  crates/net/common/src/lib.rs
  crates/net/common/src/stream.rs
  crates/net/ecies/Cargo.toml
  crates/net/ecies/src/stream.rs
  crates/net/network/src/session/mod.rs
Labels: C-debt, A-observability

#8811 chore: use sha2 from workspace
  crates/net/ecies/Cargo.toml
Labels: A-dependencies

#8813 chore(deps): replace reth-primitives in discv4
  Cargo.lock
  crates/net/discv4/Cargo.toml
  crates/net/discv4/src/config.rs
  crates/net/discv4/src/lib.rs
  crates/net/discv4/src/node.rs
  crates/net/discv4/src/proto.rs
  crates/net/discv4/src/test_utils.rs
Labels: A-dependencies

#8812 chore(ecies): replace reth-primitives with alloy-primitives
  Cargo.lock
  crates/net/ecies/Cargo.toml
  crates/net/ecies/src/algorithm.rs
  crates/net/ecies/src/codec.rs
  crates/net/ecies/src/lib.rs
  crates/net/ecies/src/mac.rs
  crates/net/ecies/src/stream.rs
  crates/net/ecies/src/util.rs
Labels: A-dependencies

#8814 chore(deps): replace reth-primitives in dns
  Cargo.lock
  crates/net/dns/Cargo.toml
  crates/net/dns/src/lib.rs
  crates/net/dns/src/tree.rs
Labels: A-dependencies

#8800 chore(rpc): remove `FillableTransaction`
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/evm/src/lib.rs
  crates/evm/src/lib.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/evm/src/lib.rs
  crates/optimism/rpc/Cargo.toml
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/eth/api/mod.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/traits/call.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/bundle.rs
  crates/rpc/rpc/src/eth/cache/mod.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
  examples/custom-evm/src/main.rs
Labels: C-debt, A-rpc, A-op-reth

#8824 chore(deps): use workspace deps
  Cargo.toml
  crates/blockchain-tree/Cargo.toml
  crates/net/dns/Cargo.toml
Labels: A-dependencies

#8816 feat: implement `deref` and `derefMut` for Requests
  crates/primitives/src/request.rs
Labels: C-enhancement

#8823 fix: split requests in `split_at` execution outcome
  crates/evm/execution-types/src/bundle.rs
Labels: C-bug

#8829 chore: bump rust version 1.79
  .github/workflows/lint.yml
  Cargo.toml
  README.md
  clippy.toml
Labels: C-enhancement

#8832 chore(evm): rename `bundle.rs` to `execution_outcome.rs`
  crates/evm/execution-types/src/execution_outcome.rs
  crates/evm/execution-types/src/lib.rs
Labels: C-debt, A-execution

#8833 chore: add address constants with 0x prefix
  crates/primitives/src/constants/mod.rs
Labels: C-docs

#8834 chore(primitives): use `derive_more` where possible
  crates/primitives/benches/integer_list.rs
  crates/primitives/src/account.rs
  crates/primitives/src/block.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/header.rs
  crates/primitives/src/integer_list.rs
  crates/primitives/src/receipt.rs
  crates/primitives/src/request.rs
  crates/primitives/src/withdrawal.rs
Labels: C-debt

#8805 docs(book): clarify what ExExes are not
  book/SUMMARY.md
  book/developers/exex/exex.md
  book/developers/exex/remote.md
Labels: C-docs, A-exex

#8839 chore(mbdx): use std::ffi, remove unused files
  Cargo.lock
  crates/storage/libmdbx-rs/Cargo.lock
  crates/storage/libmdbx-rs/Cargo.toml
  crates/storage/libmdbx-rs/LICENSE
  crates/storage/libmdbx-rs/benches/transaction.rs
  crates/storage/libmdbx-rs/mdbx-sys/Cargo.toml
  crates/storage/libmdbx-rs/mdbx-sys/build.rs
  crates/storage/libmdbx-rs/src/cursor.rs
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/libmdbx-rs/src/error.rs
  crates/storage/libmdbx-rs/src/transaction.rs
Labels: C-debt, A-db, A-dependencies

#8842 chore: move `primitives/constants` to `reth-primitives-traits`
  crates/primitives-traits/src/constants.rs
  crates/primitives-traits/src/lib.rs
  crates/primitives/src/constants/mod.rs
Labels: C-debt

#8841 chore: re-export payload types from engine types
  crates/engine-primitives/src/lib.rs
Labels: A-dependencies

#8843 chore: rm unused clap feature
  Cargo.lock
  bin/reth-bench/Cargo.toml
  bin/reth/Cargo.toml
  crates/primitives/Cargo.toml
Labels: A-dependencies

#8845 chore(rpc): use `TypedData` type in `eth_signTypedData` signature
  Cargo.lock
  crates/rpc/rpc-api/Cargo.toml
  crates/rpc/rpc-api/src/eth.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-testing-util/Cargo.toml
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/sign.rs
  crates/rpc/rpc/src/eth/signer.rs
Labels: A-rpc

#8846 chore(deps): rm unused arb feature
  bin/reth/Cargo.toml
Labels: A-dependencies

#8849 chore: move gas units to primitives constants
  bin/reth-bench/src/bench/output.rs
  crates/primitives/src/constants/gas_units.rs
  crates/primitives/src/constants/mod.rs
  crates/stages/stages/src/stages/execution.rs
Labels: C-enhancement, A-utils

#8852 chore: clean up reth-bench payload status checks
  bin/reth-bench/src/valid_payload.rs
Labels: C-debt, A-utils, A-cli

#8854 chore: remove reth-rpc-types dep in node-events
  Cargo.lock
  crates/node/events/Cargo.toml
  crates/node/events/src/node.rs
Labels: C-enhancement, A-rpc, A-consensus

#8855 chore: use new quantity mod
  crates/rpc/rpc-types/src/mev.rs
Labels: C-debt

#8853 fix(net): use real tcp port for local node record
  crates/net/network/src/discovery.rs
  crates/net/network/src/listener.rs
  crates/net/network/src/manager.rs
  crates/net/network/tests/it/startup.rs
  crates/net/peers/src/node_record.rs
Labels: C-bug, A-rpc, A-discv4

#8850 feat(primitives): gas limit setter
  crates/primitives/src/transaction/mod.rs
Labels: A-tx-pool

#8857 chore(deps): move futures-core to workspace
  Cargo.toml
  crates/payload/basic/Cargo.toml
Labels: A-dependencies

#8835 fix: re-add `validate_against_parent_4844` to optimism header validation
  crates/consensus/common/src/validation.rs
  crates/ethereum/consensus/src/lib.rs
  crates/optimism/consensus/src/lib.rs
Labels: C-bug, A-op-reth

#8860 rpc: make revm utils pub
  crates/rpc/rpc/src/eth/revm_utils.rs
Labels: A-rpc

#8870 chore: Upgrade revm
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc/src/eth/error.rs
  crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs
  examples/custom-evm/src/main.rs
Labels: A-dependencies

#8866 feat(rpc/block): simplify the block_receipts rpc
  crates/rpc/rpc/src/eth/api/block.rs
Labels: A-rpc

#8872 feat: add is paris active at block fn
  crates/primitives/src/chain/spec.rs
Labels: C-enhancement

#8874 fix: manually override certain chainconfig fields for adminNodeInfo
  crates/rpc/rpc/src/admin.rs
Labels: C-bug, A-rpc

#8817 feat: support `no_std` for `reth-primitives`
  Cargo.lock
  crates/primitives/Cargo.toml
  crates/primitives/benches/integer_list.rs
  crates/primitives/src/alloy_compat.rs
  crates/primitives/src/block.rs
  crates/primitives/src/chain/spec.rs
  crates/primitives/src/compression/mod.rs
  crates/primitives/src/constants/eip4844.rs
  crates/primitives/src/error.rs
  crates/primitives/src/integer_list.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/net.rs
  crates/primitives/src/proofs.rs
  crates/primitives/src/receipt.rs
  crates/primitives/src/request.rs
  crates/primitives/src/revm/compat.rs
  crates/primitives/src/revm/env.rs
  crates/primitives/src/transaction/eip1559.rs
  crates/primitives/src/transaction/eip2930.rs
  crates/primitives/src/transaction/eip4844.rs
  crates/primitives/src/transaction/error.rs
  crates/primitives/src/transaction/legacy.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/primitives/src/transaction/sidecar.rs
  crates/primitives/src/transaction/signature.rs
  crates/primitives/src/transaction/variant.rs
  crates/primitives/src/withdrawal.rs
Labels: C-enhancement

#8878 fix: division by zero when reading from nippy jar archive
  crates/storage/nippy-jar/src/error.rs
  crates/storage/nippy-jar/src/lib.rs
Labels: C-bug, A-static-files

#8880 chore(dep): bump secp256k1
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#8875 chore: bump alloy and rm `EvmOverrides`
  Cargo.lock
  Cargo.toml
  crates/e2e-test-utils/Cargo.toml
  crates/e2e-test-utils/src/transaction.rs
  crates/e2e-test-utils/src/wallet.rs
  crates/ethereum/evm/src/execute.rs
  crates/evm/execution-types/src/execution_outcome.rs
  crates/net/network/Cargo.toml
  crates/revm/src/state_change.rs
  crates/rpc/rpc-types/Cargo.toml
  crates/rpc/rpc-types/src/lib.rs
  crates/rpc/rpc-types/src/net.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/api/call.rs
  crates/rpc/rpc/src/eth/api/server.rs
  crates/rpc/rpc/src/eth/api/transactions.rs
  crates/rpc/rpc/src/eth/revm_utils.rs
  crates/rpc/rpc/src/trace.rs
  examples/custom-inspector/Cargo.toml
  examples/custom-inspector/src/main.rs
Labels: A-dependencies
