Repository paradigmxyz/reth, pull requests merged in 2025-05, with the labels that each got.

#15991 feat: Introducing support for configuring sequencer client headers
  crates/optimism/node/src/args.rs
  crates/optimism/rpc/src/sequencer.rs
Labels: A-op-reth

#16016 chore: used IsTyped2718 in ExtendedTxEnvelope
  examples/custom-node/src/primitives/extended_op_tx_envelope.rs
Labels: A-sdk

#16017 fix: Remove redundant article and add missing apostrophe
  crates/net/network/src/network.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/trie/db/tests/trie.rs
Labels: C-docs

#16015 chore: bumped core to 1.1.0 and alloy to 0.15.7
  Cargo.lock
  Cargo.toml
  crates/ethereum/consensus/src/validation.rs
  crates/optimism/consensus/src/validation/mod.rs
Labels: A-dependencies

#16019 chore: replace crypto
  Cargo.lock
  crates/primitives-traits/Cargo.toml
  crates/primitives-traits/src/crypto.rs
  crates/primitives-traits/src/transaction/signed.rs
Labels: C-enhancement, C-perf, A-dependencies

#15959 chore(sdk): impl `FullNetwork` for `NoopNetwork`
  Cargo.lock
  crates/net/network-api/Cargo.toml
  crates/net/network-api/src/lib.rs
  crates/net/network-api/src/noop.rs
  crates/net/p2p/Cargo.toml
  crates/net/p2p/src/full_block.rs
  crates/net/p2p/src/lib.rs
  crates/net/p2p/src/test_utils/full_block.rs
Labels: C-debt, A-networking, A-sdk

#16025 refactor: execute through `EvmConfig` in engine + `MockEvmConfig`
  Cargo.lock
  crates/engine/local/src/service.rs
  crates/engine/service/src/service.rs
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/tree/mod.rs
  crates/ethereum/evm/Cargo.toml
  crates/ethereum/evm/src/build.rs
  crates/ethereum/evm/src/lib.rs
  crates/ethereum/evm/src/test_utils.rs
  crates/ethereum/node/Cargo.toml
  crates/ethereum/reth/Cargo.toml
  crates/evm/evm/Cargo.toml
  crates/evm/evm/src/execute.rs
  crates/evm/evm/src/metrics.rs
  crates/evm/evm/src/test_utils.rs
  crates/exex/exex/src/manager.rs
  crates/exex/test-utils/Cargo.toml
  crates/exex/test-utils/src/lib.rs
  crates/node/builder/src/launch/engine.rs
  crates/stages/stages/Cargo.toml
Labels: A-sdk

#15891 feat(engine): add instrumented state provider
  book/cli/reth/node.md
  crates/engine/primitives/src/config.rs
  crates/engine/tree/src/tree/instrumented_state.rs
  crates/engine/tree/src/tree/mod.rs
  crates/node/core/src/args/engine.rs
Labels: C-enhancement, C-perf, A-observability

#16013 chore(trie): do not panic in trie cursor subnode `Debug` impl
  crates/trie/trie/src/trie_cursor/subnode.rs
Labels: C-enhancement, A-observability, A-trie

#16033 docs: Fix typos and grammar in documentation comments
  crates/engine/primitives/src/error.rs
  examples/bsc-p2p/src/main.rs
  examples/rpc-db/src/main.rs
Labels: C-docs

#15752 chore(op-sdk): Relax trait bounds on `TraceApi` methods not accessing mempool
  crates/optimism/rpc/src/eth/block.rs
  crates/rpc/rpc-eth-api/src/helpers/block.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/rpc/rpc/src/eth/helpers/block.rs
  crates/rpc/rpc/src/trace.rs
Labels: C-debt, A-tx-pool, A-op-reth, A-sdk

#16034 fix: for the priority of tx, Value has a higher priority than None
  crates/transaction-pool/src/ordering.rs
Labels: C-bug, A-tx-pool

#16035 feat(cli): no empty diffs, sort entries, and pretty print in `db diff`
  crates/cli/commands/src/db/diff.rs
Labels: C-enhancement, A-cli

#16038 chore: made `Envelope: FromTxCompact` public
  crates/storage/codecs/src/alloy/mod.rs
  crates/storage/codecs/src/alloy/transaction/ethereum.rs
  crates/storage/codecs/src/alloy/transaction/mod.rs
  crates/storage/codecs/src/alloy/transaction/optimism.rs
  crates/storage/codecs/src/lib.rs
Labels: A-sdk

#16042 feat(stage): add helpers for `StageSetBuilder`
  crates/stages/api/src/pipeline/set.rs
Labels: A-staged-sync

#15448 feat: Add ExEx example with sanity checks
  Cargo.lock
  Cargo.toml
  examples/exex-test/Cargo.toml
  examples/exex-test/src/main.rs
  examples/exex-test/src/wal_test.rs
Labels: D-good-first-issue, A-exex, C-example

#16056 refactor: move FullRpcProvider trait to storage-api crate
  crates/storage/provider/src/traits/full.rs
  crates/storage/provider/src/traits/mod.rs
  crates/storage/storage-api/src/full.rs
  crates/storage/storage-api/src/lib.rs
Labels: A-dependencies

#16060 chore: remove `NoopBlockExecutorProvider`
  crates/cli/commands/src/common.rs
  crates/cli/commands/src/import.rs
  crates/cli/commands/src/stage/dump/execution.rs
  crates/cli/commands/src/stage/dump/merkle.rs
  crates/cli/commands/src/stage/dump/mod.rs
  crates/cli/commands/src/stage/mod.rs
  crates/cli/commands/src/stage/unwind.rs
  crates/ethereum/cli/src/debug_cmd/execution.rs
  crates/evm/evm/src/noop.rs
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/engine.rs
Labels: A-sdk

#16055 chore: Remove `ForkSpec::Unknown` and Add `ForkSpec::Prague`
  testing/ef-tests/src/cases/blockchain_test.rs
  testing/ef-tests/src/models.rs
Labels: C-test

#16061 fix: invalid queued ord
  crates/transaction-pool/src/pool/parked.rs
Labels: C-bug, A-tx-pool

#16062 fix(op-rpc): l2 withdrawals root not included in debug exec witness
  crates/optimism/payload/src/builder.rs
Labels: C-bug, A-rpc, A-op-reth, OP-isthmus

#16064 fix: update metrics for download_block_range
  crates/engine/tree/src/download.rs
Labels: A-observability

#16063 fix(op): canyon check skipped unless cancun active
  crates/optimism/consensus/src/lib.rs
Labels: C-bug, A-consensus, A-op-reth

#16066 feat: add RpcStateCacheArgs::set_zero_lengths
  crates/node/core/src/args/rpc_state_cache.rs
Labels: A-cli

#16048 refactor(optimism): introduce OpNodeTypes trait to reduce generic repitition
  crates/optimism/node/src/node.rs
  crates/optimism/node/tests/it/priority.rs
Labels: A-sdk

#16068 feat(txpool): add authorization list setter to mock transaction
  crates/transaction-pool/src/test_utils/mock.rs
Labels: A-tx-pool

#16071 chore: update hive expected failures
  .github/assets/hive/expected_failures.yaml
Labels: C-hivetest, A-ci

#16076 chore: silence warnings
  crates/trie/sparse/src/state.rs
Labels: C-debt

#16078 chore: parse supervisor rpc error
  crates/optimism/txpool/src/supervisor/client.rs
Labels: A-tx-pool, A-op-reth, OP-interop

#16079 chore(op): Clean up `SupervisorClient`
  crates/optimism/node/src/node.rs
  crates/optimism/txpool/src/supervisor/client.rs
  crates/optimism/txpool/src/supervisor/mod.rs
Labels: C-debt, A-tx-pool, A-op-reth, OP-interop

#16085 chore: replace istyped2718
  crates/primitives-traits/src/lib.rs
  crates/primitives-traits/src/typed.rs
  examples/custom-node/src/primitives/extended_op_tx_envelope.rs
Labels: C-enhancement, A-sdk

#15989 chore: remove BlockExecutorProvider trait
  bin/reth/src/main.rs
  bin/reth/src/ress.rs
  crates/cli/commands/src/common.rs
  crates/cli/commands/src/import.rs
  crates/cli/commands/src/stage/dump/execution.rs
  crates/cli/commands/src/stage/dump/merkle.rs
  crates/cli/commands/src/stage/dump/mod.rs
  crates/cli/commands/src/stage/run.rs
  crates/cli/commands/src/stage/unwind.rs
  crates/engine/invalid-block-hooks/src/witness.rs
  crates/engine/tree/src/tree/mod.rs
  crates/ethereum/cli/src/debug_cmd/build_block.rs
  crates/ethereum/cli/src/debug_cmd/in_memory_merkle.rs
  crates/ethereum/cli/src/debug_cmd/merkle.rs
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/evm/src/test_utils.rs
  crates/ethereum/node/src/evm.rs
  crates/ethereum/node/src/lib.rs
  crates/ethereum/node/src/node.rs
  crates/evm/evm/src/either.rs
  crates/evm/evm/src/execute.rs
  crates/evm/evm/src/lib.rs
  crates/exex/exex/src/backfill/factory.rs
  crates/exex/exex/src/backfill/job.rs
  crates/exex/exex/src/backfill/stream.rs
  crates/exex/exex/src/backfill/test_utils.rs
  crates/exex/exex/src/context.rs
  crates/exex/exex/src/dyn_context.rs
  crates/exex/exex/src/manager.rs
  crates/exex/exex/src/notifications.rs
  crates/exex/test-utils/src/lib.rs
  crates/node/api/src/node.rs
  crates/node/builder/src/builder/states.rs
  crates/node/builder/src/components/builder.rs
  crates/node/builder/src/components/execute.rs
  crates/node/builder/src/components/mod.rs
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/engine.rs
  crates/node/builder/src/launch/exex.rs
  crates/node/builder/src/node.rs
  crates/node/builder/src/rpc.rs
  crates/node/builder/src/setup.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/node/src/node.rs
  crates/ress/provider/src/lib.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/validation.rs
  crates/stages/stages/src/sets.rs
  crates/stages/stages/src/stages/execution.rs
  examples/custom-beacon-withdrawals/src/main.rs
  examples/custom-evm/src/main.rs
  examples/precompile-cache/src/main.rs
  examples/rpc-db/src/main.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: C-enhancement, M-changelog, A-sdk

#15703 docs: add cross-platform Prometheus & Grafana installation guidance
  book/run/observability.md
Labels: C-docs, A-observability

#16087 chore: rm reth-provider from rpc-builder
  Cargo.lock
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/lib.rs
Labels: A-dependencies

#15591 feat: add stateless crate to expose stateless validation
  .github/assets/check_rv32imac.sh
  Cargo.lock
  Cargo.toml
  crates/stateless/Cargo.toml
  crates/stateless/src/execution_witness.rs
  crates/stateless/src/lib.rs
  crates/stateless/src/root.rs
  crates/stateless/src/validation.rs
  crates/stateless/src/witness_db.rs
  crates/trie/sparse/src/state.rs
  testing/ef-tests/Cargo.toml
  testing/ef-tests/src/cases/blockchain_test.rs
  testing/ef-tests/tests/tests.rs
Labels: C-enhancement, S-blocked

#16092 chore(meta): restrict mdbx vendored attribute
  .gitattributes
Labels: C-docs

#15750 chore: add more docs to SparseTrie
  crates/trie/sparse/src/trie.rs
Labels: C-docs, A-trie

#16094 chore: relaxed insp in trace rpc-eth-api
  crates/rpc/rpc-eth-api/src/helpers/trace.rs
Labels: C-enhancement, A-rpc

#16037 chore(sdk): allow `NoopNetwork` in `NodeAdapater`
  crates/ethereum/node/src/node.rs
  crates/net/eth-wire-types/src/primitives.rs
  crates/net/network-api/src/lib.rs
  crates/net/network/src/lib.rs
  crates/node/builder/src/components/builder.rs
  crates/node/builder/src/components/mod.rs
  crates/node/builder/src/components/network.rs
  crates/optimism/node/src/node.rs
  examples/custom-node/src/network.rs
Labels: A-networking, A-op-reth, A-sdk

#16097 feat: add with_disabled_rpc_cache to NodeConfig
  crates/node/core/src/node_config.rs
Labels: A-sdk

#16100 perf: check receiver count before clone
  crates/payload/builder/src/service.rs
Labels: C-perf

#16106 feat(trie): walker branch node seeks metric
  crates/trie/db/tests/walker.rs
  crates/trie/parallel/src/proof.rs
  crates/trie/parallel/src/root.rs
  crates/trie/sparse/benches/root.rs
  crates/trie/sparse/src/trie.rs
  crates/trie/trie/src/metrics.rs
  crates/trie/trie/src/node_iter.rs
  crates/trie/trie/src/proof/mod.rs
  crates/trie/trie/src/trie.rs
  crates/trie/trie/src/walker.rs
Labels: C-enhancement, A-observability, A-trie

#16105 chore(op-sdk): Move `OpPayloadTypes` to `reth-optimism-payload-builder`
  Cargo.lock
  crates/optimism/node/src/engine.rs
  crates/optimism/payload/Cargo.toml
  crates/optimism/payload/src/lib.rs
Labels: C-debt, A-block-building, A-op-reth, A-sdk

#16084 feat: add noop engine Api builder
  crates/node/builder/src/rpc.rs
Labels: C-enhancement, A-sdk

#16109 fix: skip nonce check in simulate v1 if no validation
  crates/rpc/rpc-eth-api/src/helpers/call.rs
Labels: C-bug, A-rpc

#16114 refactor: added input_mut for otterscan_api_truncate_input
  crates/optimism/rpc/src/eth/transaction.rs
Labels: C-debt, A-rpc

#16054 feat: use custom tx in custom-node
  Cargo.lock
  examples/custom-node/Cargo.toml
  examples/custom-node/src/consensus.rs
  examples/custom-node/src/lib.rs
  examples/custom-node/src/network.rs
  examples/custom-node/src/pool.rs
  examples/custom-node/src/primitives/block.rs
  examples/custom-node/src/primitives/extended_op_tx_envelope.rs
  examples/custom-node/src/primitives/mod.rs
  examples/custom-node/src/primitives/tx.rs
Labels: C-enhancement, A-sdk

#16101 chore: skip inserting older blocks
  crates/engine/tree/src/tree/mod.rs
Labels: A-engine, A-op-reth

#16102 refactor: move ExtendedTxEnvelope to reth-primitives-traits
  crates/primitives-traits/src/extended.rs
  crates/primitives-traits/src/lib.rs
  examples/custom-node/src/network.rs
  examples/custom-node/src/pool.rs
  examples/custom-node/src/primitives/block.rs
  examples/custom-node/src/primitives/mod.rs
  examples/custom-node/src/primitives/tx.rs
Labels: C-enhancement, A-sdk

#16129 chore: add link to SHA256 article
  crates/net/ecies/src/util.rs
Labels: C-docs

#15928 feat: add precompile cache for execution
  Cargo.lock
  Cargo.toml
  book/cli/reth/node.md
  crates/engine/primitives/src/config.rs
  crates/engine/tree/Cargo.toml
  crates/engine/tree/benches/state_root_task.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/payload_processor/mod.rs
  crates/engine/tree/src/tree/payload_processor/prewarm.rs
  crates/engine/tree/src/tree/precompile_cache.rs
  crates/ethereum/evm/src/lib.rs
  crates/ethereum/evm/src/test_utils.rs
  crates/evm/evm/Cargo.toml
  crates/evm/evm/src/lib.rs
  crates/node/core/src/args/engine.rs
  crates/optimism/rpc/src/eth/call.rs
  crates/primitives-traits/src/account.rs
  crates/rpc/rpc-eth-types/src/error/mod.rs
  crates/rpc/rpc/src/eth/helpers/call.rs
  deny.toml
  examples/custom-beacon-withdrawals/src/main.rs
  examples/custom-evm/src/main.rs
  examples/custom-node/src/evm.rs
  examples/precompile-cache/src/main.rs
Labels: C-perf

#16115 feat: Introducing handler for eth_getAccountInfo
  crates/rpc/rpc-eth-api/src/core.rs
  crates/rpc/rpc-eth-api/src/helpers/state.rs
Labels: C-enhancement, A-rpc

#16125 test: handle commit event properly by pool maintaining
  Cargo.lock
  crates/ethereum/node/Cargo.toml
  crates/ethereum/node/tests/e2e/main.rs
  crates/ethereum/node/tests/e2e/pool.rs
Labels: A-tx-pool, C-test

#16144 chore: moved OkValidator into txpool behind test-utils feature gate
  Cargo.lock
  crates/ethereum/node/tests/e2e/pool.rs
  crates/transaction-pool/src/test_utils/mod.rs
  crates/transaction-pool/src/test_utils/okvalidator.rs
  examples/network-txpool/Cargo.toml
  examples/network-txpool/src/main.rs
Labels: A-tx-pool, C-test

#16136 perf: perform contains check without alloc
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-perf

#16156 feat(`OpReceipt`): add `into_receipt`
  crates/optimism/primitives/src/receipt.rs
Labels: A-op-reth

#16153 perf: use estimated_compressed_size for DA limiter
  crates/optimism/payload/src/builder.rs
  crates/optimism/txpool/src/estimated_da_size.rs
  crates/optimism/txpool/src/lib.rs
  crates/optimism/txpool/src/transaction.rs
Labels: A-op-reth

#16160 chore: remove redundant NodeTypes bounds
  crates/cli/commands/src/common.rs
  crates/e2e-test-utils/src/lib.rs
  crates/node/builder/src/builder/mod.rs
Labels: C-enhancement, A-sdk

#16135 perf: dont alloc on delegation limit check
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-perf

#16134 perf: batch create sender ids
  crates/transaction-pool/src/identifier.rs
  crates/transaction-pool/src/pool/mod.rs
Labels: C-perf

#16077 chore: replace filteredParams with Filterset
  Cargo.lock
  Cargo.toml
  crates/rpc/rpc-eth-types/src/logs_utils.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/pubsub.rs
  examples/db-access/src/main.rs
Labels: A-rpc

#16157 fix: prevent memory bloat during extended finalization periods
  crates/engine/tree/src/tree/mod.rs
Labels: C-bug, A-block-building, A-engine

#16162 feat(engine): set keep alive for Tokio threads
  crates/engine/tree/src/tree/payload_processor/executor.rs
Labels: C-enhancement, A-engine

#16155 test: handle reorg event properly by pool maintaining
  crates/ethereum/node/tests/assets/genesis.json
  crates/ethereum/node/tests/e2e/pool.rs
Labels: A-tx-pool, C-test

#16127 feat(trie): instrument `TrieNodeIter::try_next`
  crates/trie/trie/src/node_iter.rs
Labels: C-enhancement, A-observability, A-trie

#15412 deps: bump libmdbx to 0.13.6
  .github/workflows/pr-title.yml
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/CMakeLists.txt
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/GNUmakefile
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/LICENSE
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/Makefile
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/NOTICE
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/VERSION.json
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/VERSION.txt
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/cmake/compiler.cmake
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/cmake/profile.cmake
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/cmake/utils.cmake
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/config.h.in
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_chk.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_copy.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_drop.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_dump.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_load.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_stat.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c++
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h++
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_chk.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_copy.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_drop.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_dump.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_load.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_stat.c
  crates/storage/libmdbx-rs/tests/cursor.rs
Labels: A-db, A-dependencies

#16172 chore: extract TreeState to separate submodule
  crates/engine/tree/src/lib.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/state.rs
Labels: C-debt, A-block-building, A-engine

#16183 chore(txpool): activate prague by default
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool, E-prague

#16184 feat(txpool): track osaka activation
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool, E-osaka

#16185 chore(txpool): update comments about prague activation
  crates/transaction-pool/src/validate/eth.rs
Labels: C-docs, A-tx-pool, E-prague

#16191 fix: use different cache instance per precompile
  crates/engine/tree/benches/state_root_task.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/payload_processor/mod.rs
  crates/engine/tree/src/tree/payload_processor/prewarm.rs
  crates/engine/tree/src/tree/precompile_cache.rs
Labels: C-bug, C-perf, A-engine

#16196 chore: bump log GetPayload events to debug level
  crates/optimism/rpc/src/engine.rs
  crates/payload/builder/src/service.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: A-observability

#16197 feat: add PrecompileCacheMap::cache_for_address and test
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/payload_processor/prewarm.rs
  crates/engine/tree/src/tree/precompile_cache.rs
Labels: C-perf, C-test, A-engine

#16210 feat: add func gas_limit_for PayloadConfig
  crates/ethereum/node/src/payload.rs
  crates/node/core/src/cli/config.rs
Labels: M-changelog, A-cli

#15956 chore(deps): migrate to jsonrpsee 0.25
  Cargo.lock
  Cargo.toml
  book/sources/Cargo.toml
  crates/chainspec/src/spec.rs
  crates/consensus/debug-client/src/providers/rpc.rs
  crates/e2e-test-utils/src/node.rs
  crates/e2e-test-utils/src/testsuite/mod.rs
  crates/primitives-traits/src/block/error.rs
  crates/primitives-traits/src/lib.rs
  crates/primitives-traits/src/transaction/mod.rs
  crates/rpc/ipc/Cargo.toml
  crates/rpc/ipc/src/client/mod.rs
  crates/rpc/ipc/src/server/ipc.rs
  crates/rpc/ipc/src/server/mod.rs
  crates/rpc/ipc/src/server/rpc_service.rs
  crates/rpc/rpc-builder/src/auth.rs
  crates/rpc/rpc-builder/src/config.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/src/metrics.rs
  crates/rpc/rpc-builder/src/rate_limiter.rs
  crates/rpc/rpc-builder/tests/it/middleware.rs
  crates/rpc/rpc-layer/src/auth_layer.rs
  crates/rpc/rpc-testing-util/src/debug.rs
  crates/rpc/rpc/src/eth/pubsub.rs
  crates/transaction-pool/src/validate/eth.rs
  deny.toml
  examples/exex-subscription/Cargo.toml
  examples/exex-subscription/src/main.rs
  examples/node-custom-rpc/Cargo.toml
  examples/node-custom-rpc/src/main.rs
Labels: S-blocked, A-rpc

#16209 feat: impl of bad_blocks handler
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc/src/debug.rs
Labels: A-rpc

#16215 fix: handle ForkChoiceUpdate errors with proper rpc error mapping
  crates/rpc/rpc-engine-api/src/error.rs
Labels: A-rpc

#16219 feat: Integrate Osaka in blob_max_and_target_count_by_hardfork
  crates/ethereum/evm/src/lib.rs
Labels: C-enhancement, E-osaka

#16225 docs: clarify unit of txfeecap
  book/cli/reth/node.md
  crates/node/core/src/args/rpc_server.rs
Labels: C-docs

#16227 feat: simplify choosing txtype for tx request using .has methods
  crates/optimism/rpc/src/eth/call.rs
  crates/rpc/rpc/src/eth/helpers/call.rs
Labels: C-debt, A-rpc

#16222 fix(trie): do not panic when logging the current hash of `TrieWalker`
  crates/trie/trie/src/node_iter.rs
  crates/trie/trie/src/trie_cursor/subnode.rs
  crates/trie/trie/src/walker.rs
Labels: C-bug, A-trie

#16220 test(e2e): add CheckPayloadAccepted action
  crates/e2e-test-utils/src/testsuite/actions.rs
Labels: C-enhancement, C-test, A-sdk

#16230 chore: Replace `try_clone_into_recovered` with `try_into_recovered` to avoid unnecessary clone
  crates/engine/util/src/reorg.rs
  crates/ethereum/cli/src/debug_cmd/build_block.rs
Labels: C-debt

#16235 feat: Introduce with_signer_ref helper
  crates/primitives-traits/src/transaction/signed.rs
Labels: A-sdk

#16074 chore: de duplicate mainnet deposit contract
  crates/chainspec/src/spec.rs
Labels: C-debt

#16218 feat(engine): add conversions for `ExecutionPayloadEnvelopeV5`
  Cargo.lock
  bin/reth-bench/src/valid_payload.rs
  crates/engine/primitives/src/lib.rs
  crates/ethereum/engine-primitives/Cargo.toml
  crates/ethereum/engine-primitives/src/error.rs
  crates/ethereum/engine-primitives/src/lib.rs
  crates/ethereum/engine-primitives/src/payload.rs
  crates/ethereum/payload/src/lib.rs
  crates/optimism/node/src/engine.rs
  crates/payload/primitives/src/lib.rs
  examples/custom-engine-types/src/main.rs
Labels: C-enhancement, M-changelog, E-osaka

#16251 chore: rm jsonrpsee patch
  Cargo.lock
  Cargo.toml
  book/sources/Cargo.toml
  crates/e2e-test-utils/Cargo.toml
  crates/e2e-test-utils/src/node.rs
  crates/e2e-test-utils/src/testsuite/actions.rs
  crates/e2e-test-utils/src/testsuite/mod.rs
  crates/e2e-test-utils/src/testsuite/setup.rs
  crates/rpc/rpc-builder/src/auth.rs
Labels: C-bug, A-dependencies, A-sdk

#16240 fix: receipts logs arg parsing
  book/cli/reth/node.md
  crates/node/builder/src/launch/common.rs
  crates/node/core/src/args/pruning.rs
  crates/node/core/src/node_config.rs
Labels: C-bug, A-cli

#16268 feat(engine): respond unsupported for payload v5 pre-osaka
  crates/payload/primitives/src/lib.rs
Labels: A-engine, E-osaka

#16270 feat(engine): add `engine_getPayloadV5` skeleton
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: A-engine, E-osaka

#16266 docs: Fix typos in `static-file` crate README
  crates/static-file/static-file/README.md
Labels: C-docs

#16271 feat(txpool): add methods for retrieving `BlobsAndProofsV2`
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/transaction-pool/src/blobstore/disk.rs
  crates/transaction-pool/src/blobstore/mem.rs
  crates/transaction-pool/src/blobstore/mod.rs
  crates/transaction-pool/src/blobstore/noop.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool, E-osaka

#16274 feat: implement get payload v5
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/metrics.rs
Labels: A-engine, E-osaka

#16277 chore: bump alloy 1.0.3
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#16279 feat(engine): implement `engine_getBlobsV2`
  Cargo.lock
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/metrics.rs
Labels: A-engine, E-osaka

#16284 chore: upstream tx_type derive to alloy::TransactionRequest
  crates/optimism/rpc/src/eth/call.rs
  crates/rpc/rpc/src/eth/helpers/call.rs
Labels: A-rpc

#16285 chore: Construct a SubscriptionMessage with the sink's properties
  crates/rpc/rpc/src/eth/pubsub.rs
Labels: C-perf, A-rpc

#16280 ci: fix Windows build in `release.yml`
  Cross.toml
  Dockerfile.x86_64-pc-windows-gnu
Labels: A-ci

#16294 ci: deduplicate changelog in release notes
  .github/workflows/release.yml
Labels: A-ci

#16297 refactor(rpc-builder): Use Box<dyn TaskSpawner> for RPC task handling
  crates/node/builder/src/rpc.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  examples/rpc-db/src/main.rs
Labels: C-debt, A-rpc

#16299 ci: separate workflow for reproducible release
  .github/workflows/release-reproducible.yml
  .github/workflows/release.yml
Labels: A-ci

#16287 ci: release dry run
  .github/workflows/release.yml
Labels: A-ci

#16238 feat: added TransactionValidator::validate_transactions_with_origin
  crates/optimism/txpool/src/validator.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/mod.rs
Labels: A-tx-pool

#16302 ci: use `GITHUB_REF_NAME` env var in release.yml
  .github/workflows/release.yml
Labels: A-ci

#16303 feat: introduce PoolTransaction::into_consensus_with2718
  crates/optimism/txpool/src/transaction.rs
  crates/transaction-pool/src/traits.rs
Labels: A-tx-pool

#16311 chore: bump inspectors 0.22.2
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#16189 refactor(mempool): Refactor transaction validation to use batch interface
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/validate/task.rs
Labels: C-perf, A-tx-pool

#16312 chore: add 7702 to announced
  etc/grafana/dashboards/reth-mempool.json
Labels: A-observability

#16314 chore: rm jsonrpsee features
  Cargo.lock
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc/Cargo.toml
Labels: A-dependencies

#16315 chore: flatten deps
  Cargo.lock
  crates/ress/provider/Cargo.toml
  crates/ress/provider/src/lib.rs
  crates/ress/provider/src/pending_state.rs
Labels: A-dependencies

#16325 feat: implement IsTyped2781 for reth types
  crates/ethereum/primitives/src/receipt.rs
  crates/optimism/primitives/src/receipt.rs
Labels: A-sdk

#16327 docs: add some docs about TaskExecutor
  crates/node/api/src/node.rs
  crates/tasks/src/lib.rs
Labels: C-docs

#16322 chore: Replace reth-provider with reth-storage-api in reth-rpc-api
  Cargo.lock
  crates/rpc/rpc-eth-api/Cargo.toml
  crates/rpc/rpc-eth-api/src/helpers/block.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-api/src/helpers/estimate.rs
  crates/rpc/rpc-eth-api/src/helpers/fee.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/rpc/rpc-eth-api/src/helpers/receipt.rs
  crates/rpc/rpc-eth-api/src/helpers/spec.rs
  crates/rpc/rpc-eth-api/src/helpers/state.rs
  crates/rpc/rpc-eth-api/src/helpers/trace.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-api/src/node.rs
  crates/rpc/rpc-eth-api/src/types.rs
Labels: C-debt, A-dependencies

#16241 feat: include SpecId in PrecompileCache keys
  Cargo.lock
  Cargo.toml
  book/cli/reth/node.md
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/payload_processor/mod.rs
  crates/engine/tree/src/tree/payload_processor/prewarm.rs
  crates/engine/tree/src/tree/precompile_cache.rs
Labels: C-enhancement, C-perf, A-engine

#15827 feat: introduce Receipt69 variant
  crates/net/eth-wire-types/src/message.rs
  crates/net/eth-wire-types/src/primitives.rs
  crates/net/eth-wire-types/src/receipts.rs
  crates/net/network/src/message.rs
  crates/net/network/src/session/active.rs
Labels: C-enhancement, A-networking

#16345 chore: bump alloy 1.0.4
  Cargo.lock
  Cargo.toml
  book/cli/reth/node.md
  crates/prune/prune/src/segments/user/sender_recovery.rs
  crates/stages/stages/src/stages/prune.rs
  crates/stages/stages/src/stages/sender_recovery.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/test_utils/mock.rs
  testing/testing-utils/src/generators.rs
Labels: A-dependencies

#16349 feat(primitive-traits): relax mem size implementations for 4844 txs with sidecars
  crates/primitives-traits/src/size.rs
Labels: C-enhancement, E-osaka

#16352 chore: add `clippy-op-dev` make script
  Makefile
Labels: A-meta

#16357 chore: bump version 1.4.2
  Cargo.lock
  Cargo.toml
Labels: A-meta

#16358 ci: do not dry run by default in `release.yml`
  .github/workflows/release.yml
Labels: A-ci

#16361 ci: do not trigger release workflow on `dry_run*` branches
  .github/workflows/release.yml
Labels: A-ci

#16290 feat(stages): reduce index history progress logging frequency
  crates/stages/stages/src/stages/utils.rs
Labels: A-observability

#16363 chore: re-export node-builder as builder
  Cargo.lock
  crates/ethereum/reth/Cargo.toml
  crates/ethereum/reth/src/lib.rs
  crates/optimism/reth/Cargo.toml
  crates/optimism/reth/src/lib.rs
Labels: A-dependencies

#16366 feat: Implement conversion from built-in transaction envelopes into `Extended`
  crates/primitives-traits/src/extended.rs
Labels: A-sdk

#16367 refactor(examples): Replace redundant type definitions with a `CustomTransaction` alias in the `custom_node` example
  examples/custom-node/src/network.rs
  examples/custom-node/src/primitives/block.rs
  examples/custom-node/src/primitives/mod.rs
  examples/custom-node/src/primitives/tx.rs
Labels: C-enhancement, A-sdk

#16371 feat(txpool): activate osaka in tx validator
  crates/transaction-pool/src/validate/eth.rs
Labels: C-enhancement, A-tx-pool, E-osaka

#16379 feat(node): bump Hoodi gas limit to 60M
  crates/node/core/src/cli/config.rs
Labels: C-enhancement, A-execution

#16383 chore: Move subscription_task_spawner into EthPubSubInner
  crates/rpc/rpc/src/eth/pubsub.rs
Labels: C-debt, A-rpc

#16387 feat: relax OpNetworkBuilder type constraints
  crates/optimism/node/src/node.rs
  crates/optimism/node/tests/it/priority.rs
Labels: C-enhancement, A-op-reth, A-sdk

#16372 fix(ipc): Improve server code correctness, logging, and doc comments
  crates/rpc/ipc/src/server/mod.rs
  crates/rpc/ipc/src/server/rpc_service.rs
Labels: C-docs

#16392 chore: Refactoring manual clone for opPoolBuilder
  crates/optimism/node/src/node.rs
Labels: C-debt

#16395 fix: `InvalidTimestamp` display
  crates/payload/primitives/src/error.rs
Labels: A-rpc, A-observability

#16394 feat(examples): Add `CustomEvm` for the execution of `CustomTransaction` in the `custom_node` example
  examples/custom-node/src/evm/alloy.rs
  examples/custom-node/src/evm/env.rs
  examples/custom-node/src/evm/mod.rs
Labels: A-sdk

#16300 chore(book): Bump `alloy-hardforks` and `alloy-op-harfroks`
  Cargo.toml
Labels: A-dependencies

#16401 fix: forward sequencer error
  crates/optimism/rpc/src/error.rs
Labels: C-bug, A-rpc

#16126 feat: configure tracing layers
  .github/assets/check_wasm.sh
  Cargo.lock
  Cargo.toml
  crates/cli/commands/src/launcher.rs
  crates/cli/commands/src/lib.rs
  crates/cli/commands/src/node.rs
  crates/ethereum/cli/src/interface.rs
  crates/node/core/src/args/log.rs
  crates/optimism/cli/src/app.rs
  crates/optimism/cli/src/lib.rs
  crates/tracing-otlp/Cargo.toml
  crates/tracing-otlp/src/lib.rs
  crates/tracing/src/layers.rs
  crates/tracing/src/lib.rs
  crates/tracing/src/test_tracer.rs
Labels: C-enhancement, A-cli, A-sdk

#16099 chore: eth69 status message support
  crates/net/eth-wire-types/src/lib.rs
  crates/net/eth-wire-types/src/status.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/handshake.rs
  crates/net/eth-wire/src/multiplex.rs
  crates/net/eth-wire/src/test_utils.rs
  crates/net/network-api/src/events.rs
  crates/net/network-api/src/lib.rs
  crates/net/network/src/config.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/handle.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/state.rs
  crates/net/network/src/swarm.rs
  examples/bsc-p2p/src/handshake.rs
  examples/manual-p2p/src/main.rs
Labels: C-enhancement, A-networking

#16404 feat(examples): Implement `EvmFactory` for `CustomEvm` in `custom_node` example
  examples/custom-node/src/evm/alloy.rs
  examples/custom-node/src/evm/env.rs
Labels: A-sdk

#16407 fix(RPC): Ensure `eth_getTransactionCount` returns correct nonce for 'pending' tag
  crates/rpc/rpc-eth-api/src/helpers/state.rs
Labels: A-rpc

#16386 feat(tasks): enable graceful shutdown request via TaskExecutor
  crates/cli/runner/src/lib.rs
  crates/tasks/src/lib.rs
Labels: C-enhancement

#16410 feat: relax OpEthApiBuilder type constraints
  Cargo.lock
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/node.rs
  crates/optimism/rpc/src/eth/mod.rs
Labels: C-enhancement, A-op-reth, A-sdk

#16320 chore: Add `ClientInput` struct to `reth-stateless`
  Cargo.lock
  crates/stateless/Cargo.toml
  crates/stateless/src/lib.rs
Labels: C-enhancement

#16406 feat: fix tasks metrics
  crates/tasks/src/lib.rs
Labels: A-observability

#16403 fix: grammar in multiple files
  book/intro.md
  docs/crates/db.md
  docs/release.md
  docs/workflow.md
Labels: C-docs

#16408 refactor: use `impl IntoIterator` for transaction batches and streamline validation calls
  crates/optimism/txpool/src/validator.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/mod.rs
Labels: M-changelog, A-tx-pool

#16413 fix: rewrite estimate loop condition
  crates/rpc/rpc-eth-api/src/helpers/estimate.rs
Labels: A-rpc

#16420 ci: fix system icons width in release.yml
  .github/workflows/release.yml
Labels: A-ci

#16423 feat: relax OpExecutorBuilder type constraints
  crates/optimism/node/src/node.rs
Labels: C-enhancement, A-op-reth, A-sdk

#16405 feat: make max EthMessageID dependent on the EthVersion
  crates/net/eth-wire-types/src/message.rs
  crates/net/eth-wire-types/src/version.rs
  crates/net/eth-wire/src/capability.rs
  crates/net/eth-wire/src/eth_snap_stream.rs
  crates/net/eth-wire/src/protocol.rs
Labels: A-devp2p

#16432 ci: run op-kurtosis every 6hrs
  .github/workflows/kurtosis-op.yml
Labels: A-ci
