Repository paradigmxyz/reth, pull requests merged in 2025-03, with the labels that each got.

#13946 Add pools evicted transactions metrics
  crates/transaction-pool/src/metrics.rs
  crates/transaction-pool/src/pool/txpool.rs
  etc/grafana/dashboards/reth-mempool.json
Labels: A-tx-pool, A-observability

#14442 chore(sdk): Use `EthApiBuilder` instead of `FnOnce` trait
  crates/ethereum/node/src/lib.rs
  crates/ethereum/node/src/node.rs
  crates/node/builder/src/launch/mod.rs
  crates/node/builder/src/rpc.rs
  crates/optimism/node/src/node.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/primitives/src/lib.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/middleware.rs
  crates/rpc/rpc-builder/tests/it/startup.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc-eth-api/src/node.rs
  crates/rpc/rpc-eth-types/src/builder/ctx.rs
  crates/rpc/rpc-eth-types/src/builder/mod.rs
  crates/rpc/rpc-eth-types/src/lib.rs
  crates/rpc/rpc/src/eth/builder.rs
  crates/rpc/rpc/src/eth/core.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/traits/full.rs
  examples/custom-engine-types/src/main.rs
  examples/rpc-db/src/main.rs
Labels: C-debt, A-rpc, A-op-reth, A-sdk

#14647 feat: Feature gate traits inside storage-api that still depend on db-api
  crates/node/core/Cargo.toml
  crates/optimism/storage/Cargo.toml
  crates/storage/provider/Cargo.toml
  crates/storage/storage-api/Cargo.toml
  crates/storage/storage-api/src/lib.rs
  crates/storage/storage-api/src/stats.rs
  crates/storage/storage-api/src/storage.rs
Labels: A-db

#14782 chore: use interop timestamp
  crates/optimism/chainspec/src/lib.rs
Labels: A-op-reth

#14788 feat(reth-ipc): add request_timeout to client builder
  crates/rpc/ipc/src/client/mod.rs
Labels: A-rpc

#14729 fix(tree): use only in-memory blocks when constructing trie input
  crates/engine/tree/src/tree/mod.rs
  crates/ethereum/node/tests/e2e/p2p.rs
  crates/storage/provider/src/providers/consistent_view.rs
Labels: C-enhancement, C-perf, A-engine, A-trie

#14787 Feat: add a `discv4` test to verify the bootnode event behaviour
  crates/net/discv4/src/lib.rs
Labels: C-test

#14812 fix: correctly prune `HeaderNumbers`
  crates/stages/stages/src/stages/headers.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-bug

#14811 refactor: move isthmus helpers to reth-optimism-consensus
  Cargo.lock
  crates/optimism/consensus/Cargo.toml
  crates/optimism/consensus/src/validation/isthmus.rs
  crates/optimism/payload/Cargo.toml
  crates/optimism/payload/src/builder.rs
  crates/optimism/storage/src/lib.rs
  crates/optimism/storage/src/predeploys.rs
Labels: A-op-reth

#14687 feat(net): `ress` subprotocol
  .github/assets/check_wasm.sh
  Cargo.lock
  Cargo.toml
  crates/net/network/src/eth_requests.rs
  crates/net/ress/Cargo.toml
  crates/net/ress/README.md
  crates/net/ress/src/connection.rs
  crates/net/ress/src/handlers.rs
  crates/net/ress/src/lib.rs
  crates/net/ress/src/message.rs
  crates/net/ress/src/provider.rs
  crates/net/ress/src/test_utils.rs
  crates/net/ress/src/types.rs
  crates/net/ress/tests/it/e2e.rs
  crates/net/ress/tests/it/main.rs
Labels: C-enhancement, A-networking

#14822 fix: only check for best block number
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-perf, A-db

#14773 feat: e2e testsuite actions
  Cargo.lock
  crates/e2e-test-utils/Cargo.toml
  crates/e2e-test-utils/src/lib.rs
  crates/e2e-test-utils/src/testsuite/actions.rs
  crates/e2e-test-utils/src/testsuite/examples.rs
  crates/e2e-test-utils/src/testsuite/mod.rs
  crates/e2e-test-utils/src/testsuite/setup.rs
Labels: C-test

#14826 chore(hive): run devp2p/eth tests
  .github/workflows/hive.yml
Labels: A-devp2p, C-test, A-discv5

#14830 Fix: Increase gas limit in chain config
  examples/custom-dev-node/src/main.rs
Labels: C-bug

#14819 feat(tree): multiproof manager metrics
  crates/engine/tree/src/tree/payload_processor/multiproof.rs
Labels: C-bug, C-enhancement, A-observability, A-engine

#14839 fix(l2-withdrawals-root): Compute op devnet genesis hash from genesis header
  crates/optimism/chainspec/src/dev.rs
Labels: C-bug, A-op-reth

#14838 refactor: use tokio to fetch storage proofs
  Cargo.lock
  crates/engine/tree/src/tree/payload_processor/executor.rs
  crates/engine/tree/src/tree/payload_processor/multiproof.rs
  crates/trie/parallel/Cargo.toml
  crates/trie/parallel/src/proof.rs
Labels: C-perf, A-engine, A-trie

#14845 fix(l2-withdrawals-root): Fix genesis hash for custom op chain
  crates/optimism/chainspec/src/lib.rs
Labels: C-bug, A-op-reth

#14411 invoke on_unsupported_by_peer of ConnectionHandler
  crates/net/eth-wire/src/capability.rs
  crates/net/network/src/error.rs
  crates/net/network/src/protocol.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/tests/it/multiplex.rs
Labels: C-bug, A-networking

#14817 test: partially tx response for tx fetcher
  Cargo.lock
  crates/net/network/Cargo.toml
  crates/net/network/src/transactions/mod.rs
Labels: A-networking

#14837 feat: configuration of the tokio runtime
  bin/reth-bench/src/main.rs
  bin/reth/src/cli/mod.rs
  crates/cli/cli/src/lib.rs
  crates/cli/runner/src/lib.rs
  crates/optimism/cli/src/lib.rs
Labels: A-cli

#14856 chore: auto_impl TrieCursorFactory for reference
  crates/trie/trie/src/trie_cursor/mod.rs
Labels: A-trie

#14857 refactor: prepare BlockExecutionError for move to alloy-evm
  Cargo.lock
  crates/errors/src/error.rs
  crates/evm/execution-errors/Cargo.toml
  crates/evm/execution-errors/src/lib.rs
  crates/evm/execution-types/Cargo.toml
  crates/evm/execution-types/src/chain.rs
Labels: A-execution

#14858 chore: remove StateRoot variant from BlockValidationError
  Cargo.lock
  crates/evm/execution-errors/Cargo.toml
  crates/evm/execution-errors/src/lib.rs
  crates/evm/src/execute.rs
  crates/stages/api/src/error.rs
Labels: A-execution

#14871 chore: add 0x prefix to `b256!` and `address!` calls
  crates/ethereum/evm/src/dao_fork.rs
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/node/tests/e2e/dev.rs
  crates/ethereum/primitives/src/receipt.rs
  crates/ethereum/primitives/src/transaction.rs
  crates/evm/src/execute.rs
  crates/net/eth-wire-types/src/broadcast.rs
  crates/net/eth-wire-types/src/header.rs
  crates/optimism/chainspec/src/base.rs
  crates/optimism/chainspec/src/base_sepolia.rs
  crates/optimism/chainspec/src/lib.rs
  crates/optimism/chainspec/src/op.rs
  crates/optimism/chainspec/src/op_sepolia.rs
  crates/optimism/cli/src/ovm_file_codec.rs
  crates/optimism/consensus/src/proof.rs
  crates/optimism/consensus/src/validation/isthmus.rs
  crates/optimism/evm/src/l1.rs
  crates/optimism/payload/src/payload.rs
  crates/optimism/primitives/src/bedrock.rs
  crates/optimism/primitives/src/predeploys.rs
  crates/optimism/primitives/src/receipt.rs
  crates/primitives-traits/src/proofs.rs
  crates/stages/stages/src/stages/execution.rs
  crates/stages/stages/src/stages/index_account_history.rs
  crates/stages/stages/src/stages/index_storage_history.rs
  crates/stages/stages/src/stages/mod.rs
  crates/stages/stages/src/stages/s3/downloader/fetch.rs
  crates/storage/codecs/src/alloy/authorization_list.rs
  crates/storage/codecs/src/alloy/header.rs
  crates/storage/codecs/src/alloy/transaction/eip4844.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/trie/sparse/src/state.rs
  examples/custom-beacon-withdrawals/src/main.rs
  examples/custom-dev-node/src/main.rs
  examples/custom-evm/src/main.rs
Labels: C-debt

#14864 feat: add helper for eth body conversion
  crates/primitives-traits/src/block/body.rs
Labels: A-rpc

#14875 fix(l2-withdrawals-root): isthmus header custom genesis
  crates/optimism/chainspec/src/lib.rs
Labels: C-bug, A-op-reth

#14876 changed sealed_block_with_senders_range() into recovered_block_range()
  crates/rpc/rpc/src/trace.rs
  crates/stages/stages/src/stages/execution.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/storage-api/src/block.rs
  crates/storage/storage-api/src/noop.rs
Labels: C-debt

#14882 chore(deps): Bump op-alloy
  Cargo.lock
  Cargo.toml
Labels: A-dependencies, A-op-reth

#14800 perf(tree): chunk multiproofs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/payload_processor/multiproof.rs
  crates/trie/common/src/hashed_state.rs
  crates/trie/common/src/proofs.rs
Labels: C-perf, A-engine

#14880 feat: don't include operator fee params in receipts when both zero
  crates/optimism/rpc/src/eth/receipt.rs
Labels: A-op-reth

#14889 chore: update advisories
  Cargo.lock
  deny.toml
Labels: A-dependencies

#14874 feat(trie): update sparse trie storage roots independently
  crates/engine/tree/src/tree/payload_processor/sparse_trie.rs
  crates/trie/sparse/src/state.rs
Labels: C-enhancement, C-debt, A-engine, A-trie

#14306 replace reth-primitives deps in txpool with reth-primitives-traits
  Cargo.lock
  Cargo.toml
  bin/reth/src/commands/debug_cmd/build_block.rs
  crates/primitives-traits/src/lib.rs
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/blobstore/tracker.rs
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/test_utils/gen.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/mod.rs
  crates/transaction-pool/src/validate/task.rs
Labels: S-blocked, A-tx-pool, A-dependencies

#14909 chore: add FactoryTx<F> for getting tx associated types
  crates/storage/storage-api/src/database_provider.rs
Labels: A-db

#14912 chore: remove reth-primitives dep from consensus-common
  Cargo.lock
  crates/consensus/common/Cargo.toml
  crates/consensus/common/src/validation.rs
Labels: A-dependencies

#14915 chore: remove reth-primitives dep from op rpc
  Cargo.lock
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/eth/pending_block.rs
  crates/optimism/rpc/src/eth/receipt.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/optimism/rpc/src/witness.rs
Labels: A-dependencies

#14920 refactor: unify EVM traits
  crates/engine/local/src/service.rs
  crates/engine/service/src/service.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/payload_processor/mod.rs
  crates/engine/tree/src/tree/payload_processor/prewarm.rs
  crates/engine/util/src/reorg.rs
  crates/ethereum/evm/src/build.rs
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/evm/src/lib.rs
  crates/ethereum/node/src/node.rs
  crates/ethereum/node/src/payload.rs
  crates/ethereum/payload/src/lib.rs
  crates/evm/src/aliases.rs
  crates/evm/src/execute.rs
  crates/evm/src/lib.rs
  crates/node/api/src/lib.rs
  crates/node/api/src/node.rs
  crates/node/builder/src/components/builder.rs
  crates/node/builder/src/components/execute.rs
  crates/node/builder/src/components/mod.rs
  crates/optimism/evm/src/build.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/evm/src/lib.rs
  crates/optimism/node/src/node.rs
  crates/optimism/payload/src/builder.rs
  crates/optimism/rpc/src/eth/call.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/eth/pending_block.rs
  crates/optimism/rpc/src/witness.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-api/src/helpers/estimate.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/rpc/rpc-eth-api/src/helpers/state.rs
  crates/rpc/rpc-eth-api/src/helpers/trace.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/bundle.rs
  crates/rpc/rpc/src/eth/helpers/call.rs
  crates/rpc/rpc/src/eth/helpers/pending_block.rs
  crates/rpc/rpc/src/eth/helpers/trace.rs
  crates/rpc/rpc/src/eth/sim_bundle.rs
  crates/rpc/rpc/src/trace.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  examples/custom-beacon-withdrawals/src/main.rs
Labels: M-changelog, A-execution

#14914 chore: remove reth-primitives dep from chain-state
  Cargo.lock
  crates/chain-state/Cargo.toml
  crates/chain-state/src/chain_info.rs
  crates/chain-state/src/in_memory.rs
  crates/chain-state/src/lib.rs
  crates/chain-state/src/memory_overlay.rs
  crates/chain-state/src/notifications.rs
  crates/chain-state/src/test_utils.rs
Labels: A-dependencies

#14919 chore: remove reth-primitives dep from commands
  Cargo.lock
  crates/cli/commands/Cargo.toml
  crates/cli/commands/src/init_state/mod.rs
  crates/cli/commands/src/init_state/without_evm.rs
  crates/cli/commands/src/test_vectors/compact.rs
  crates/cli/commands/src/test_vectors/tables.rs
Labels: A-dependencies

#14872 feat: add bincode support to opreceipt
  Cargo.lock
  crates/optimism/primitives/Cargo.toml
  crates/optimism/primitives/src/lib.rs
  crates/optimism/primitives/src/receipt.rs
Labels: A-op-reth, A-exex

#14866 fix: clear tree state on unwind
  crates/engine/tree/src/tree/mod.rs
  crates/stages/api/src/pipeline/ctrl.rs
  crates/stages/api/src/pipeline/mod.rs
Labels: C-bug

#14926 feat(op, txpool): introduce OpPooledTx trait
  Cargo.lock
  crates/optimism/node/src/node.rs
  crates/optimism/payload/Cargo.toml
  crates/optimism/payload/src/builder.rs
  crates/optimism/rpc/src/witness.rs
  crates/optimism/txpool/src/lib.rs
  crates/optimism/txpool/src/transaction.rs
Labels: A-block-building, A-tx-pool, A-op-reth

#14923 feat/emit better payload events
  crates/payload/basic/src/better_payload_emitter.rs
  crates/payload/basic/src/lib.rs
Labels: A-block-building

#14908 feat: implement compact for alloy ethereum transaction
  Cargo.toml
  crates/storage/codecs/src/alloy/transaction/mod.rs
Labels: A-db

#14001 fix: exex head ahead of host
  crates/exex/exex/src/notifications.rs
Labels: C-bug, A-exex

#14928 feat(ress): limit active connections
  crates/net/ress/src/connection.rs
  crates/net/ress/src/handlers.rs
  crates/net/ress/tests/it/e2e.rs
Labels: C-enhancement, A-networking

#14934 add nightly builds
  .github/workflows/docker-nightly.yml
  Makefile
Labels: A-meta, A-ci

#14869 Parse L1 block values in Interop fork
  crates/optimism/evm/src/l1.rs
Labels: A-op-reth

#14942 chore: rm rpc conversion types
  Cargo.lock
  bin/reth-bench/Cargo.toml
  bin/reth-bench/src/bench/mod.rs
  bin/reth-bench/src/bench/new_payload_fcu.rs
  bin/reth-bench/src/bench/new_payload_only.rs
  bin/reth-bench/src/bench/rpc_transaction.rs
Labels: C-debt

#14946 chore: remove commented SparseTrieEvent
  crates/engine/tree/src/tree/payload_processor/multiproof.rs
  crates/engine/tree/src/tree/payload_processor/sparse_trie.rs
Labels: A-trie

#14849 test: complete mine block test in e2e testsuite
  Cargo.lock
  crates/e2e-test-utils/Cargo.toml
  crates/e2e-test-utils/src/lib.rs
  crates/e2e-test-utils/src/node.rs
  crates/e2e-test-utils/src/payload.rs
  crates/e2e-test-utils/src/testsuite/actions.rs
  crates/e2e-test-utils/src/testsuite/assets/genesis.json
  crates/e2e-test-utils/src/testsuite/examples.rs
  crates/e2e-test-utils/src/testsuite/mod.rs
  crates/e2e-test-utils/src/testsuite/setup.rs
  crates/optimism/chainspec/src/lib.rs
  crates/optimism/payload/src/payload.rs
Labels: C-test

#14932 fix: call validate_execution_requests from validate_version_specific_fields for ethereum engine validator
  Cargo.lock
  crates/engine/primitives/Cargo.toml
  crates/engine/primitives/src/lib.rs
  crates/ethereum/node/src/engine.rs
  crates/optimism/node/src/engine.rs
  crates/payload/primitives/src/payload.rs
Labels: A-engine, C-hivetest, A-ci

#14813 Update metrics.md
  book/run/observability.md
  docs/design/metrics.md
Labels: C-docs

#14954 chore: bump revm
  Cargo.lock
  Cargo.toml
  book/sources/Cargo.toml
  examples/custom-evm/src/main.rs
  examples/stateful-precompile/src/main.rs
Labels: A-execution

#14966 chore: rm reth-prmitives from rpc builder
  Cargo.lock
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/tests/it/auth.rs
  crates/rpc/rpc-builder/tests/it/http.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
Labels: C-debt

#14965 chore: rm reth-prmitives from rpc compat
  Cargo.lock
  crates/rpc/rpc-types-compat/Cargo.toml
  crates/rpc/rpc-types-compat/src/block.rs
  crates/rpc/rpc-types-compat/src/transaction.rs
  crates/rpc/rpc/src/eth/helpers/types.rs
Labels: A-dependencies

#14967 chore: add sparse trie logs with time elapsed
  crates/engine/tree/src/tree/payload_processor/sparse_trie.rs
Labels: A-observability

#14971 chore: rm reth-prmitives from e2eutils
  Cargo.lock
  crates/e2e-test-utils/Cargo.toml
  crates/e2e-test-utils/src/testsuite/setup.rs
Labels: A-dependencies

#14970 chore: rm reth-prmitives from stages
  Cargo.lock
  crates/stages/stages/Cargo.toml
  crates/stages/stages/benches/setup/mod.rs
  crates/stages/stages/src/lib.rs
  crates/stages/stages/src/sets.rs
  crates/stages/stages/src/stages/bodies.rs
  crates/stages/stages/src/stages/execution.rs
  crates/stages/stages/src/stages/finish.rs
  crates/stages/stages/src/stages/hashing_account.rs
  crates/stages/stages/src/stages/hashing_storage.rs
  crates/stages/stages/src/stages/headers.rs
  crates/stages/stages/src/stages/index_storage_history.rs
  crates/stages/stages/src/stages/merkle.rs
  crates/stages/stages/src/stages/mod.rs
  crates/stages/stages/src/stages/prune.rs
  crates/stages/stages/src/stages/s3/mod.rs
  crates/stages/stages/src/stages/sender_recovery.rs
  crates/stages/stages/src/stages/tx_lookup.rs
  crates/stages/stages/src/stages/utils.rs
  crates/stages/stages/src/test_utils/test_db.rs
Labels: A-dependencies

#14959 feat: integrate ress
  .github/assets/check_wasm.sh
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  bin/reth/src/lib.rs
  bin/reth/src/main.rs
  bin/reth/src/ress.rs
  book/cli/reth/node.md
  crates/net/network-api/src/lib.rs
  crates/node/core/src/args/mod.rs
  crates/node/core/src/args/ress_args.rs
  crates/ress/protocol/Cargo.toml
  crates/ress/protocol/README.md
  crates/ress/protocol/src/connection.rs
  crates/ress/protocol/src/handlers.rs
  crates/ress/protocol/src/lib.rs
  crates/ress/protocol/src/message.rs
  crates/ress/protocol/src/provider.rs
  crates/ress/protocol/src/test_utils.rs
  crates/ress/protocol/src/types.rs
  crates/ress/protocol/tests/it/e2e.rs
  crates/ress/protocol/tests/it/main.rs
  crates/ress/provider/Cargo.toml
  crates/ress/provider/src/lib.rs
  crates/ress/provider/src/pending_state.rs
  crates/ress/provider/src/recorder.rs
Labels: C-enhancement

#14976 chore: bump alloy 0.12.5
  Cargo.lock
  Cargo.toml
  crates/ethereum/primitives/src/transaction.rs
Labels: A-dependencies

#14940 Bump vergen to 9.0 #14904
  Cargo.lock
  Cargo.toml
  crates/node/core/Cargo.toml
  crates/node/core/build.rs
Labels: A-dependencies

#14985 chore: add ress code owner
  .github/CODEOWNERS
Labels: A-meta

#14890 Chore: move tree config from engine-tree to engine-primitives
  Cargo.lock
  crates/engine/primitives/src/config.rs
  crates/engine/primitives/src/lib.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/payload_processor/executor.rs
  crates/node/builder/src/builder/mod.rs
  crates/node/builder/src/lib.rs
  crates/node/core/Cargo.toml
  crates/node/core/src/args/engine.rs
  crates/node/core/src/node_config.rs
Labels: C-debt, A-engine

#14996 deps: downgrade cc to 1.2.15
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#14999 chore: add workflow for building binaries
  .github/workflows/build-release-binaries.yml
Labels: A-ci

#14969 chore: add metrics on redundant proof nodes
  Cargo.lock
  crates/trie/sparse/Cargo.toml
  crates/trie/sparse/src/lib.rs
  crates/trie/sparse/src/metrics.rs
  crates/trie/sparse/src/state.rs
Labels: C-perf, A-observability, A-trie

#15016 chore(cli): fix clap deprecated warnings
  crates/cli/commands/src/p2p/rlpx.rs
Labels: C-debt, A-cli

#15017 fix: add bincode compat for eth receipt
  Cargo.lock
  Cargo.toml
  crates/ethereum/primitives/Cargo.toml
  crates/ethereum/primitives/src/lib.rs
  crates/ethereum/primitives/src/receipt.rs
  crates/ethereum/primitives/src/transaction.rs
  crates/exex/exex/src/wal/storage.rs
  crates/exex/exex/test-data/28.wal
  examples/exex-hello-world/Cargo.toml
  examples/exex-hello-world/src/main.rs
Labels: C-bug, A-exex

#14993 Fix: help merging `CachedReads` across blocks
  crates/revm/src/cached.rs
Labels: A-execution

#15009 check not only 1559 but also 4844 and 7702 for min_priority_fee checking in txpool validation
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool

#15006 optimize txpool component doc comment
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/mod.rs
  crates/transaction-pool/src/validate/task.rs
Labels: C-docs

#14892 chore(trie): simplify hashed post state partitioning
  crates/engine/tree/src/tree/payload_processor/multiproof.rs
  crates/trie/common/src/hashed_state.rs
  crates/trie/sparse/src/state.rs
Labels: C-debt, A-trie

#15029 feat(ress): max witness window
  bin/reth/src/ress.rs
  book/cli/reth/node.md
  crates/node/core/src/args/ress_args.rs
  crates/ress/provider/src/lib.rs
Labels: C-enhancement

#15027 feat: add redundant / total multiproof node graphs
  etc/grafana/dashboards/overview.json
Labels: C-enhancement, C-perf, A-observability

#15028 chore: use Histogram for trie input duration
  crates/engine/tree/src/tree/metrics.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, C-perf, A-observability

#15031 feat: track time since first state update in metrics
  crates/engine/tree/src/tree/payload_processor/multiproof.rs
Labels: C-enhancement, C-perf, A-observability

#15032 chore: add profiling-op target to Makefile
  Makefile
Labels: C-enhancement, A-utils

#15022 feat:added peer-kind to SessionInfo
  crates/net/network-api/src/events.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/transactions/mod.rs
Labels: A-networking

#15024 Fix: Update commet about Eip7702 transaction type
  crates/ethereum/primitives/src/transaction.rs
Labels: C-docs

#15037 fix(ci): update limit to match fixture types in hive eest tests
  .github/workflows/hive.yml
Labels: C-hivetest, A-ci

#15021 feat(test, e2e): mutable environment for actions
  crates/e2e-test-utils/src/testsuite/actions.rs
  crates/e2e-test-utils/src/testsuite/mod.rs
Labels: C-test

#14939 feat: make trace_filter block range configurable
  book/cli/reth/node.md
  crates/node/core/src/args/rpc_server.rs
  crates/rpc/rpc-builder/src/config.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-eth-types/src/builder/config.rs
  crates/rpc/rpc-server-types/src/constants.rs
  crates/rpc/rpc/src/trace.rs
Labels: A-rpc

#14776 chore: invoke invalid block hook for new invalid blocks
  crates/engine/tree/src/tree/mod.rs
Labels: A-engine

#15034 feat: add total multiproof task duration grafana
  etc/grafana/dashboards/overview.json
Labels: C-perf, A-observability, A-trie

#15048 fix: add debug namespace to auth module in op-reth
  Cargo.lock
  crates/ethereum/node/src/node.rs
  crates/node/builder/src/rpc.rs
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/node.rs
Labels: A-rpc, A-op-reth

#15052 fix: increment in_progress when we spawn a prewarm transaction
  crates/engine/tree/src/tree/payload_processor/prewarm.rs
Labels: C-bug, C-perf, A-execution

#15051 chore: add serde feature to db-models
  crates/storage/db-api/Cargo.toml
  crates/storage/db-models/Cargo.toml
  crates/storage/db-models/src/accounts.rs
  crates/storage/db-models/src/blocks.rs
  crates/storage/db-models/src/client_version.rs
Labels: A-dependencies

#14960 test for handling incoming_transactions_hashes
  crates/net/network/src/transactions/mod.rs
Labels: C-test, A-networking

#15056 chore: rm reth-primitives from payload basic
  Cargo.lock
  crates/payload/basic/Cargo.toml
  crates/payload/basic/src/lib.rs
  crates/payload/basic/src/stack.rs
Labels: A-dependencies

#15062 chore: rm reth-primitives from eth wire
  Cargo.lock
  crates/net/eth-wire/Cargo.toml
  crates/net/eth-wire/tests/fuzz_roundtrip.rs
  crates/net/eth-wire/tests/pooled_transactions.rs
Labels: A-dependencies

#15064 chore: rm reth-primitives from optimism
  Cargo.lock
  crates/optimism/cli/Cargo.toml
  crates/optimism/cli/src/commands/import_receipts.rs
  crates/optimism/cli/src/commands/init_state.rs
  crates/optimism/cli/src/receipt_file_codec.rs
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/engine.rs
  crates/optimism/node/src/node.rs
  crates/optimism/node/tests/it/priority.rs
  crates/optimism/payload/Cargo.toml
  crates/optimism/payload/src/builder.rs
  crates/optimism/payload/src/error.rs
  crates/optimism/payload/src/payload.rs
  crates/optimism/payload/src/traits.rs
  crates/optimism/payload/src/validator.rs
Labels: A-dependencies

#15063 chore: rm reth-primitives from network
  Cargo.lock
  crates/net/network/Cargo.toml
  crates/net/network/src/config.rs
  crates/net/network/src/import.rs
  crates/net/network/src/message.rs
  crates/net/network/src/metrics.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/state.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
  crates/net/network/src/transactions/validation.rs
  crates/net/network/tests/it/big_pooled_txs_req.rs
  crates/net/network/tests/it/requests.rs
  crates/net/network/tests/it/txgossip.rs
Labels: A-dependencies

#15066 chore: rm reth-primitives from exex crates
  Cargo.lock
  crates/evm/execution-types/src/chain.rs
  crates/evm/execution-types/src/execution_outcome.rs
  crates/exex/exex/Cargo.toml
  crates/exex/exex/src/backfill/job.rs
  crates/exex/exex/src/backfill/stream.rs
  crates/exex/exex/src/backfill/test_utils.rs
  crates/exex/exex/src/dyn_context.rs
  crates/exex/exex/src/manager.rs
  crates/exex/exex/src/notifications.rs
  crates/exex/exex/src/wal/mod.rs
  crates/exex/exex/src/wal/storage.rs
  crates/exex/test-utils/Cargo.toml
  crates/exex/test-utils/src/lib.rs
  crates/exex/types/Cargo.toml
  crates/exex/types/src/notification.rs
Labels: A-dependencies

#15069 chore: rm reth-primitives from node crates
  Cargo.lock
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/engine.rs
  crates/node/builder/src/launch/exex.rs
  crates/node/core/Cargo.toml
  crates/node/core/src/utils.rs
Labels: A-dependencies

#15045 feat: add wait_time optional argument to reth-bench
  Cargo.lock
  bin/reth-bench/Cargo.toml
  bin/reth-bench/src/bench/new_payload_fcu.rs
Labels: C-enhancement, C-benchmark

#15070 chore: rm reth-primitives from trie
  Cargo.lock
  crates/trie/parallel/Cargo.toml
  crates/trie/parallel/benches/root.rs
  crates/trie/parallel/src/lib.rs
  crates/trie/parallel/src/proof.rs
  crates/trie/parallel/src/root.rs
Labels: A-dependencies

#15092 perf(tree): do not wait for the sparse trie to drop
  crates/engine/tree/src/tree/payload_processor/sparse_trie.rs
Labels: C-perf, A-engine, A-trie

#15065 chore: fix dead link in `example/README.md`
  examples/README.md
Labels: C-docs, C-example

#14784 Bsc block import
  Cargo.lock
  crates/net/network/Cargo.toml
  crates/net/network/src/import.rs
  examples/bsc-p2p/Cargo.toml
  examples/bsc-p2p/src/block_import/handle.rs
  examples/bsc-p2p/src/block_import/mod.rs
  examples/bsc-p2p/src/block_import/parlia.rs
  examples/bsc-p2p/src/block_import/service.rs
  examples/bsc-p2p/src/lib.rs
  examples/bsc-p2p/src/main.rs
Labels: A-networking, C-example

#14980 feat(op-interop): Uncomment interop activation checks
  crates/optimism/evm/src/config.rs
Labels: A-op-reth

#15042 Build and push images in parallel
  .github/workflows/docker-git.yml
  .github/workflows/docker-nightly.yml
  .github/workflows/docker.yml
Labels: A-meta

#15102 chore: remove layer of blocking task calls
  crates/engine/tree/src/tree/payload_processor/multiproof.rs
  crates/trie/parallel/src/proof.rs
  crates/trie/parallel/src/proof_task.rs
Labels: A-trie

#15082 fix windows msvc build
  crates/storage/libmdbx-rs/src/environment.rs
Labels: C-bug, A-db, A-ci

#15060 ExecutionData moved to PayloadTypes
  crates/engine/primitives/src/lib.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/util/src/engine_store.rs
  crates/ethereum/engine-primitives/src/lib.rs
  crates/optimism/node/src/engine.rs
  crates/payload/primitives/src/lib.rs
  examples/custom-engine-types/src/main.rs
Labels: M-changelog, A-engine

#15113 Refactor generic type to use `PayloadTypes`
  crates/engine/primitives/src/message.rs
Labels: A-sdk

#15116 chore(trie): do not take self by mutable ref for blinded provider
  crates/trie/sparse/src/blinded.rs
  crates/trie/trie/src/proof/blinded.rs
  crates/trie/trie/src/witness.rs
Labels: C-debt, A-trie

#14662 refactor(trie): invert provider access in sparse trie
  crates/engine/tree/src/tree/payload_processor/sparse_trie.rs
  crates/trie/sparse/benches/rlp_node.rs
  crates/trie/sparse/benches/root.rs
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
  crates/trie/trie/src/proof/blinded.rs
  crates/trie/trie/src/witness.rs
Labels: C-enhancement, A-db, A-trie

#15120 refactor(trie): pass blinded provider factory to sparse trie methods
  crates/engine/tree/src/tree/payload_processor/sparse_trie.rs
  crates/trie/sparse/src/state.rs
  crates/trie/trie/src/witness.rs
Labels: C-enhancement, A-db, A-trie

#15121 chore: add evm_for_ctx in prewarming ctx
  crates/engine/tree/src/tree/payload_processor/prewarm.rs
Labels: C-enhancement, A-execution

#15127 feat(reth-bench): support engine_newPayloadV4
  bin/reth-bench/src/bench/new_payload_fcu.rs
  bin/reth-bench/src/bench/new_payload_only.rs
  bin/reth-bench/src/valid_payload.rs
Labels: C-enhancement, A-cli, C-benchmark

#15123 feat(rpc): accept requests hash in engine_newPayloadV4
  Cargo.lock
  book/cli/reth/node.md
  crates/node/builder/src/rpc.rs
  crates/node/core/src/args/engine.rs
  crates/optimism/node/src/rpc.rs
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-builder/tests/it/utils.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/error.rs
Labels: C-enhancement, A-rpc, A-cli, A-engine

#15139 chore: turn multiproof from state into pure fn
  crates/engine/tree/src/tree/payload_processor/prewarm.rs
Labels: A-execution

#15141 chore(trie): rename from_provider_and_root to from_root_node
  crates/trie/sparse/src/trie.rs
Labels: A-trie

#13995 Added custom headers to NodePrimitives
  Cargo.lock
  Cargo.toml
  crates/engine/primitives/src/lib.rs
  crates/optimism/evm/src/lib.rs
  crates/optimism/node/src/lib.rs
  crates/optimism/payload/src/builder.rs
  crates/optimism/payload/src/payload.rs
  crates/primitives-traits/src/size.rs
  examples/custom-node/Cargo.toml
  examples/custom-node/src/chainspec.rs
  examples/custom-node/src/engine.rs
  examples/custom-node/src/lib.rs
  examples/custom-node/src/primitives/block.rs
  examples/custom-node/src/primitives/header.rs
  examples/custom-node/src/primitives/mod.rs
Labels: S-blocked, A-sdk

#15148 converted EngineTypes to PayloadTypes
  examples/bsc-p2p/src/block_import/handle.rs
  examples/bsc-p2p/src/block_import/mod.rs
  examples/bsc-p2p/src/block_import/service.rs
Labels: C-debt

#15137 chore(trie): make rlp_node take external rlp_buf
  crates/trie/sparse/src/trie.rs
Labels: A-trie

#15133 feat: add new `NewBlockEvent` enum for different types of block announcement events
  crates/net/network/src/import.rs
  crates/net/network/src/manager.rs
  examples/bsc-p2p/src/block_import/mod.rs
  examples/bsc-p2p/src/block_import/service.rs
Labels: A-networking

#15158 feat: add inverse conversion for rpc proof types
  crates/trie/common/src/proofs.rs
Labels: C-enhancement, A-rpc

#15152 perf(engine): use proof task as blinded node provider for sparse trie
  Cargo.lock
  crates/engine/tree/src/tree/payload_processor/mod.rs
  crates/engine/tree/src/tree/payload_processor/multiproof.rs
  crates/engine/tree/src/tree/payload_processor/sparse_trie.rs
  crates/trie/parallel/Cargo.toml
  crates/trie/parallel/src/proof.rs
  crates/trie/parallel/src/proof_task.rs
Labels: C-perf, A-engine

#15169 chore(op): remove unused DepositTransaction impl
  crates/optimism/primitives/src/transaction/signed.rs
Labels: A-op-reth

#15173 test(trie): mock trie cursor factory
  Cargo.lock
  crates/trie/trie/Cargo.toml
  crates/trie/trie/src/trie_cursor/mock.rs
  crates/trie/trie/src/trie_cursor/mod.rs
Labels: C-test, A-trie

#15161 feat: make MissingPayloadBehaviour configurable in EthereumPayloadBuilder
  crates/ethereum/payload/src/config.rs
  crates/ethereum/payload/src/lib.rs
Labels: C-enhancement, A-block-building, A-sdk

#15177 chore: bump alloy-evm alpha2
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#15172 chore(ci): update hive eest limits
  .github/workflows/hive.yml
Labels: C-debt, C-hivetest, A-ci

#15176 test(trie): trie node iter
  Cargo.lock
  crates/trie/trie/Cargo.toml
  crates/trie/trie/src/hashed_cursor/mock.rs
  crates/trie/trie/src/lib.rs
  crates/trie/trie/src/mock.rs
  crates/trie/trie/src/node_iter.rs
  crates/trie/trie/src/trie_cursor/mock.rs
Labels: C-test, A-trie

#15184 chore: remove reth-provider dep
  Cargo.lock
  crates/optimism/payload/Cargo.toml
  crates/optimism/payload/src/builder.rs
Labels: A-dependencies

#15191 chore: remove reth-provider dep
  Cargo.lock
  crates/engine/util/Cargo.toml
  crates/engine/util/src/reorg.rs
Labels: A-dependencies

#15188 chore: remove serde default
  crates/net/network/Cargo.toml
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/test_utils/pool.rs
Labels: A-dependencies

#15193 chore: bump version 1.3.3
  Cargo.lock
  Cargo.toml
Labels: A-meta

#15187 Use of payload type instead of EngineTypes
  crates/engine/primitives/src/lib.rs
Labels: C-debt

#15072 docs: edited by badge lint
  README.md
Labels: C-docs

#15194 chore: remove serde from reth-provider
  Cargo.lock
  crates/exex/exex/Cargo.toml
  crates/net/network/Cargo.toml
  crates/optimism/cli/Cargo.toml
  crates/storage/provider/Cargo.toml
  crates/transaction-pool/Cargo.toml
  crates/trie/db/Cargo.toml
  examples/bsc-p2p/Cargo.toml
Labels: A-dependencies

#15195 test(trie): fix the trie node iterator test and use hash builder for correctness
  crates/trie/trie/src/node_iter.rs
  crates/trie/trie/src/walker.rs
Labels: C-test, A-trie

#15186 chore: remove serde default
  crates/net/network/Cargo.toml
  examples/bsc-p2p/Cargo.toml
Labels: A-dependencies

#15199 refactor(trie): initialize sparse trie with the provider
  Cargo.lock
  crates/engine/tree/src/tree/payload_processor/sparse_trie.rs
  crates/trie/sparse/Cargo.toml
  crates/trie/sparse/benches/rlp_node.rs
  crates/trie/sparse/benches/root.rs
  crates/trie/sparse/src/blinded.rs
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
  crates/trie/trie/src/witness.rs
Labels: C-debt, A-trie

#15205 chore: release 1.3.4
  Cargo.lock
  Cargo.toml
Labels: A-meta

#15183 feat: add dedicated storage proof method to ParallelProof
  crates/trie/parallel/src/proof.rs
Labels: A-trie

#15178 chore: change default for await_payload_on_missing
  crates/ethereum/payload/src/config.rs
Labels: A-block-building

#15122 feat(storage): Implement `Compact` for `EthereumTxEnvelope` from `alloy`
  Cargo.lock
  crates/ethereum/primitives/src/transaction.rs
  crates/storage/codecs/Cargo.toml
  crates/storage/codecs/src/alloy/transaction/ethereum.rs
  crates/storage/codecs/src/alloy/transaction/mod.rs
Labels: A-db

#15189 Derive blobstore cache size from configured blobtargets
  crates/ethereum/node/Cargo.toml
  crates/ethereum/node/src/node.rs
Labels: A-tx-pool

#15216 Remove ethereum-fork-dependency
  Cargo.lock
  crates/net/eth-wire-types/Cargo.toml
  crates/net/eth-wire-types/src/status.rs
Labels: A-dependencies

#15215 chore: remove usused file
  crates/payload/builder/src/error.rs
Labels: C-debt

#15217 added engine_getBlobsV2 endpoint
  Cargo.lock
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-enhancement, A-rpc

#15213 Allow `blob_cache_size` to be configured via CLI
  book/cli/reth/node.md
  crates/ethereum/node/src/node.rs
  crates/node/core/src/args/txpool.rs
  crates/transaction-pool/src/config.rs
Labels: A-cli

#15226 Remove default serde feature from reth-network-api
  crates/net/network-api/Cargo.toml
  crates/net/network/Cargo.toml
  examples/bsc-p2p/Cargo.toml
Labels: A-dependencies

#15232 test: remove redundant clone
  crates/rpc/rpc-testing-util/src/debug.rs
Labels: C-debt

#15039 test(op): add Op e2e testsuite example
  crates/e2e-test-utils/src/testsuite/actions.rs
  crates/e2e-test-utils/src/testsuite/examples.rs
  crates/optimism/node/tests/e2e/main.rs
  crates/optimism/node/tests/e2e/testsuite.rs
Labels: C-enhancement, C-test, A-op-reth

#15230 feat(storage): Implement `Compact` for `OpTxEnvelope` from `op_alloy` using blanket impl
  crates/optimism/primitives/src/transaction/signed.rs
  crates/storage/codecs/src/alloy/transaction/ethereum.rs
  crates/storage/codecs/src/alloy/transaction/optimism.rs
Labels: C-enhancement, A-sdk
