Repository paradigmxyz/reth, pull requests merged in 2025-01, with the labels that each got.

#13620 fix: implement `StateCommitmentProvider` for `BlockchainProvider`
  crates/storage/provider/src/providers/mod.rs
Labels: C-debt

#13608 chore: use native conversions for payload to block
  Cargo.lock
  crates/payload/validator/Cargo.toml
  crates/payload/validator/src/lib.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/tests/it/payload.rs
  crates/rpc/rpc-types-compat/Cargo.toml
  crates/rpc/rpc-types-compat/src/engine/mod.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: A-sdk

#13623 chore: bump alloy 0.9.2
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#13624 chore: remove redundant payload fn
  crates/rpc/rpc-builder/tests/it/auth.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: C-debt

#13629 chore: use alloy-eip2124 code
  Cargo.lock
  Cargo.toml
  crates/ethereum-forks/Cargo.toml
  crates/ethereum-forks/src/forkid.rs
  crates/ethereum-forks/src/head.rs
  crates/ethereum-forks/src/lib.rs
Labels: A-dependencies

#13632 chore: use alloy TransactionMeta
  crates/chain-state/src/in_memory.rs
  crates/optimism/rpc/src/eth/block.rs
  crates/optimism/rpc/src/eth/receipt.rs
  crates/primitives-traits/src/transaction/mod.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/meta.rs
  crates/primitives/src/transaction/mod.rs
  crates/rpc/rpc-eth-api/src/helpers/receipt.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-types/src/receipt.rs
  crates/rpc/rpc/src/eth/helpers/block.rs
  crates/rpc/rpc/src/eth/helpers/receipt.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/static_file/jar.rs
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/storage-api/src/noop.rs
  crates/storage/storage-api/src/transactions.rs
Labels: A-sdk

#13613 feat: merge BlockBodyTxExt trait into BlockBody
  Cargo.lock
  crates/node/core/Cargo.toml
  crates/primitives-traits/Cargo.toml
  crates/primitives-traits/src/block/body.rs
  crates/primitives/src/block.rs
  crates/primitives/src/traits.rs
Labels: A-sdk

#13633 chore: rm some direct header access
  crates/chain-state/src/in_memory.rs
  crates/consensus/common/src/validation.rs
  crates/evm/execution-types/src/chain.rs
  crates/net/p2p/src/full_block.rs
  crates/optimism/consensus/src/lib.rs
  crates/optimism/evm/src/lib.rs
  crates/payload/validator/src/lib.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
  testing/testing-utils/src/generators.rs
Labels: A-sdk

#13634 chore: rm unused recovery fns
  crates/primitives/src/transaction/mod.rs
Labels: C-debt

#13636 test: move tests out of reth-primitives
  crates/ethereum/primitives/src/transaction.rs
  crates/primitives-traits/src/transaction/signature.rs
  crates/primitives/src/transaction/signature.rs
Labels: C-test, A-sdk

#13638 feat: add helper iter for tx hashes
  crates/primitives-traits/src/block/body.rs
  crates/rpc/rpc-types-compat/src/block.rs
Labels: C-enhancement

#13617 fix: no_std case hashmap imports
  crates/evm/execution-types/src/execution_outcome.rs
  crates/optimism/evm/src/lib.rs
  crates/storage/db-common/src/init.rs
  crates/storage/provider/src/providers/consistent.rs
Labels: C-debt

#13592 feat: remove PartialEq+Eq from ProviderError and all others affected
  crates/blockchain-tree-api/src/error.rs
  crates/ethereum/evm/src/execute.rs
  crates/evm/execution-errors/src/lib.rs
  crates/net/p2p/src/error.rs
  crates/stages/stages/src/stages/execution.rs
  crates/stages/stages/src/stages/mod.rs
  crates/storage/db-common/src/init.rs
  crates/storage/errors/src/provider.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/writer/mod.rs
Labels: C-debt

#13650 chore: use generics for RecoveredTx
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/chain-state/src/test_utils.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/rpc/rpc/src/eth/helpers/types.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
Labels: A-sdk

#13605 integrate EIP-7840 in chainspec
  crates/chainspec/src/spec.rs
  examples/bsc-p2p/src/chainspec.rs
  examples/polygon-p2p/src/chain_cfg.rs
Labels: C-enhancement, M-devnet

#13645 docs(ci): remove moved deny workflow
  docs/repo/ci.md
Labels: A-ci

#13652 chore: replace trie-common dep with alloy-trie
  Cargo.lock
  crates/chainspec/Cargo.toml
  crates/chainspec/src/spec.rs
  crates/optimism/consensus/Cargo.toml
Labels: A-dependencies

#13663 feat: rename reth_primitives::RecoveredTx functions to match alloy::Recovered
  bin/reth/src/commands/debug_cmd/build_block.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/chain-state/src/test_utils.rs
  crates/ethereum/payload/src/lib.rs
  crates/net/network/benches/broadcast.rs
  crates/net/network/src/transactions/mod.rs
  crates/net/network/tests/it/txgossip.rs
  crates/optimism/node/src/txpool.rs
  crates/optimism/payload/src/builder.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/payload/util/src/transaction.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/rpc/rpc-eth-api/src/helpers/trace.rs
  crates/rpc/rpc-types-compat/src/transaction.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/helpers/types.rs
  crates/rpc/rpc/src/eth/sim_bundle.rs
  crates/rpc/rpc/src/trace.rs
  crates/rpc/rpc/src/txpool.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
  docs/crates/network.md
Labels: A-sdk

#13659 chore(consensus): Cut down on reth-primitives::TransactionSigned usage
  Cargo.lock
  crates/consensus/common/Cargo.toml
  crates/consensus/common/src/validation.rs
  crates/ethereum/primitives/src/transaction.rs
Labels: A-sdk

#13653 refactor: Remove standalone from_recovered functions and make part of TransactionCompat trait
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-types/src/transaction.rs
  crates/rpc/rpc-types-compat/src/block.rs
  crates/rpc/rpc-types-compat/src/transaction.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/pubsub.rs
  crates/rpc/rpc/src/txpool.rs
Labels: C-debt, A-rpc

#13671 chore: remove unused `WithdrawalsProvider::latest_withdrawal`
  Cargo.lock
  crates/consensus/common/Cargo.toml
  crates/consensus/common/src/validation.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/storage-api/src/noop.rs
  crates/storage/storage-api/src/withdrawals.rs
Labels: C-debt, A-db

#13667 chore: bump revm 19.2
  Cargo.lock
  Cargo.toml
  crates/optimism/evm/src/l1.rs
  crates/optimism/node/src/txpool.rs
  crates/optimism/rpc/src/eth/receipt.rs
Labels: A-dependencies, A-op-reth

#13673 chore(root): log multiproof calculation
  crates/engine/tree/src/tree/root.rs
Labels: C-enhancement, A-observability, A-trie

#13670 feat(primitives): re-export alloy Recovered
  crates/optimism/node/src/txpool.rs
  crates/optimism/node/tests/it/priority.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
Labels: M-changelog, A-sdk

#13675 chore: use secp fns directly
  crates/ethereum/evm/src/execute.rs
  crates/exex/exex/src/backfill/job.rs
  crates/exex/exex/src/backfill/stream.rs
  crates/optimism/primitives/src/transaction/signed.rs
  crates/primitives/src/transaction/mod.rs
  crates/transaction-pool/src/test_utils/gen.rs
  testing/testing-utils/Cargo.toml
  testing/testing-utils/src/generators.rs
  testing/testing-utils/src/genesis_allocator.rs
Labels: A-sdk

#13679 chore: remove duplicated compact consts
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/tx_type.rs
Labels: C-debt

#13681 chore: rm uneccessary serde mod
  crates/ethereum/primitives/src/receipt.rs
Labels: C-debt

#13676 chore: remove optimism feature from execution-types tests
  Cargo.lock
  crates/evm/execution-types/Cargo.toml
  crates/evm/execution-types/src/chain.rs
  crates/evm/execution-types/src/execution_outcome.rs
Labels: C-enhancement, C-test, A-sdk

#13674 fix(tree): do not reveal nodes twice in sparse trie
  crates/trie/sparse/src/trie.rs
Labels: C-bug, A-trie

#13677 chore: move signedtx ext trait
  crates/primitives-traits/src/transaction/signed.rs
  crates/primitives/src/transaction/mod.rs
Labels: A-sdk

#13684 feat(no-std): enable `no_std` support for op consensus rules
  crates/optimism/consensus/Cargo.toml
  crates/optimism/consensus/src/beacon.rs
  crates/optimism/consensus/src/lib.rs
  crates/optimism/consensus/src/proof.rs
  crates/optimism/consensus/src/validation.rs
Labels: A-consensus, A-dependencies, A-op-reth

#13686 chore: no-std consensus common
  Cargo.toml
  crates/consensus/common/Cargo.toml
  crates/consensus/common/src/lib.rs
  crates/evm/Cargo.toml
  crates/optimism/evm/Cargo.toml
Labels: A-consensus

#13687 chore: disable reth-primitives std default feature
  Cargo.toml
Labels: A-dependencies

#13690 chore: rm usage of PooledTransactionsElementEcRecovered alias
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
Labels: A-dependencies, A-sdk

#13691 chore: relax tryfrom impl
  crates/primitives/src/alloy_compat.rs
Labels: C-debt

#13700 chore: release 1.1.5
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#12639 feat(engine): wire StateRootTask in EngineApiTreeHandler
  bin/reth/src/main.rs
  book/cli/reth/node.md
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/tree/config.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-perf, A-blockchain-tree, A-trie

#13699 chore: remove reth-primitives dep from op-primitives
  Cargo.lock
  crates/e2e-test-utils/Cargo.toml
  crates/optimism/primitives/Cargo.toml
  crates/optimism/primitives/src/lib.rs
  crates/optimism/primitives/src/transaction/signed.rs
Labels: A-dependencies, A-op-reth

#13706 docs: add additional BasicPayloadJob docs
  crates/payload/basic/src/lib.rs
  crates/payload/builder/src/traits.rs
Labels: C-docs, A-block-building

#13702 chore: reduce blockchaintree usage
  Cargo.lock
  crates/exex/exex/Cargo.toml
  crates/exex/exex/src/backfill/job.rs
  crates/exex/exex/src/backfill/stream.rs
  crates/exex/test-utils/Cargo.toml
  crates/exex/test-utils/src/lib.rs
  crates/node/builder/src/builder/mod.rs
Labels: C-debt

#13705 chore: make engine-tree independent of blockchaintree
  Cargo.lock
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/tree/block_buffer.rs
  crates/engine/tree/src/tree/metrics.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-dependencies

#13693 fix(ci): Enable wasm check for `reth-optimism-primitives`
  .github/assets/check_wasm.sh
Labels: A-dependencies, A-op-reth, A-ci

#13709 feat: use engine launcher as default
  Cargo.lock
  crates/e2e-test-utils/src/lib.rs
  crates/engine/local/src/payload.rs
  crates/exex/test-utils/src/lib.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/docs/mermaid/builder.mmd
  crates/node/builder/src/builder/mod.rs
  crates/node/builder/src/launch/mod.rs
  examples/custom-engine-types/Cargo.toml
  examples/custom-engine-types/src/main.rs
Labels: A-sdk

#13672 Discussion draft: change DB Writer to take value references
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/exex/exex/src/backfill/test_utils.rs
  crates/optimism/cli/src/commands/import_receipts.rs
  crates/prune/prune/src/segments/user/history.rs
  crates/stages/stages/src/stages/execution.rs
  crates/stages/stages/src/stages/hashing_account.rs
  crates/stages/stages/src/stages/hashing_storage.rs
  crates/stages/stages/src/stages/headers.rs
  crates/stages/stages/src/stages/merkle.rs
  crates/stages/stages/src/stages/mod.rs
  crates/stages/stages/src/stages/sender_recovery.rs
  crates/stages/stages/src/stages/tx_lookup.rs
  crates/stages/stages/src/stages/utils.rs
  crates/stages/stages/src/test_utils/test_db.rs
  crates/storage/db-api/src/cursor.rs
  crates/storage/db-api/src/mock.rs
  crates/storage/db-api/src/models/integer_list.rs
  crates/storage/db-api/src/models/mod.rs
  crates/storage/db-api/src/scale.rs
  crates/storage/db-api/src/table.rs
  crates/storage/db-common/src/init.rs
  crates/storage/db/benches/criterion.rs
  crates/storage/db/benches/hash_keys.rs
  crates/storage/db/src/implementation/mdbx/cursor.rs
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/tables/raw.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/block.rs
  crates/storage/provider/src/traits/state.rs
  crates/storage/provider/src/writer/mod.rs
  crates/storage/storage-api/src/chain.rs
  crates/trie/db/src/trie_cursor.rs
  crates/trie/db/tests/fuzz_in_memory_nodes.rs
  crates/trie/db/tests/trie.rs
  crates/trie/db/tests/walker.rs
  crates/trie/db/tests/witness.rs
Labels: A-db

#13646 chore!: make SealedBlock.header field private
  bin/reth-bench/src/bench/new_payload_fcu.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/shareable.rs
  crates/blockchain-tree/src/state.rs
  crates/chain-state/src/in_memory.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/engine/tree/src/tree/mod.rs
  crates/ethereum/payload/src/lib.rs
  crates/evm/execution-types/src/chain.rs
  crates/exex/exex/src/manager.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/bodies/request.rs
  crates/net/downloaders/src/test_utils/mod.rs
  crates/net/p2p/src/bodies/response.rs
  crates/node/events/src/node.rs
  crates/optimism/payload/src/builder.rs
  crates/primitives/src/block.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-api/src/helpers/trace.rs
  crates/rpc/rpc/src/trace.rs
  crates/rpc/rpc/src/validation.rs
  crates/stages/stages/benches/setup/mod.rs
  crates/stages/stages/src/stages/bodies.rs
  crates/stages/stages/src/stages/hashing_storage.rs
  crates/stages/stages/src/test_utils/test_db.rs
  crates/static-file/static-file/src/static_file_producer.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/test_utils/blocks.rs
Labels: M-changelog, A-sdk

#13710 feat: add standalone rayon recovery functions
  crates/primitives-traits/src/block/body.rs
  crates/primitives-traits/src/lib.rs
  crates/primitives-traits/src/transaction/mod.rs
  crates/primitives-traits/src/transaction/recover.rs
Labels: A-sdk

#13711 chore: remove rayon from reth primitives
  Cargo.lock
  crates/primitives/Cargo.toml
  crates/primitives/src/transaction/mod.rs
  crates/storage/provider/src/providers/static_file/jar.rs
  crates/storage/provider/src/providers/static_file/manager.rs
Labels: A-sdk

#13712 chore: remove blockchaintree dep from reth bin
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/mod.rs
  bin/reth/src/commands/debug_cmd/replay_engine.rs
  bin/reth/src/lib.rs
  book/SUMMARY.md
  book/cli/SUMMARY.md
  book/cli/reth/debug.md
  examples/rpc-db/src/main.rs
Labels: A-sdk

#13714 chore: move beacon handle type
  crates/consensus/beacon/src/engine/error.rs
  crates/consensus/beacon/src/engine/handle.rs
  crates/engine/primitives/src/error.rs
  crates/engine/primitives/src/lib.rs
  crates/engine/primitives/src/message.rs
Labels: A-consensus, A-sdk

#13715 chore: relax arb for sealedwithsenders
  crates/primitives/src/block.rs
Labels: A-sdk

#13692 feat(no-std): add `no_std` support for `reth-optimism-consensus`
  crates/optimism/consensus/Cargo.toml
  crates/optimism/consensus/src/lib.rs
  crates/optimism/consensus/src/proof.rs
  crates/optimism/consensus/src/validation.rs
  crates/optimism/evm/Cargo.toml
Labels: A-consensus, A-dependencies, A-op-reth

#13718 chore: move beacon consensus engine event
  crates/consensus/beacon/src/engine/mod.rs
  crates/engine/primitives/src/event.rs
  crates/engine/primitives/src/lib.rs
Labels: A-sdk

#13719 feat: `SparseStateTrie::reveal_witness`
  crates/trie/sparse/src/state.rs
Labels: C-enhancement, A-trie

#13720 chore: rm beacon consensus dep from engine-tree
  Cargo.lock
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/download.rs
  crates/engine/tree/src/engine.rs
  crates/engine/tree/src/tree/config.rs
  crates/engine/tree/src/tree/invalid_headers.rs
  crates/engine/tree/src/tree/mod.rs
Labels: A-sdk

#13722 chore: rm beacon consensus deps everywhere
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/lib.rs
  crates/engine/local/Cargo.toml
  crates/engine/local/src/service.rs
  crates/engine/service/Cargo.toml
  crates/engine/service/src/service.rs
  crates/ethereum/node/src/lib.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/engine.rs
  crates/node/events/Cargo.toml
  crates/node/events/src/node.rs
  crates/optimism/node/Cargo.toml
  crates/storage/provider/src/providers/mod.rs
Labels: A-sdk

#13723 chore!:rm beacon consensus crate
  Cargo.lock
  Cargo.toml
  crates/consensus/beacon/Cargo.toml
  crates/consensus/beacon/src/engine/error.rs
  crates/consensus/beacon/src/engine/handle.rs
  crates/consensus/beacon/src/engine/hooks/controller.rs
  crates/consensus/beacon/src/engine/hooks/mod.rs
  crates/consensus/beacon/src/engine/hooks/prune.rs
  crates/consensus/beacon/src/engine/hooks/static_file.rs
  crates/consensus/beacon/src/engine/invalid_headers.rs
  crates/consensus/beacon/src/engine/metrics.rs
  crates/consensus/beacon/src/engine/mod.rs
  crates/consensus/beacon/src/engine/sync.rs
  crates/consensus/beacon/src/engine/test_utils.rs
  crates/consensus/beacon/src/lib.rs
Labels: M-changelog

#13725 chore!: rm legacy blockchain provider
  Cargo.lock
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/providers/mod.rs
  crates/storage/provider/src/traits/mod.rs
  crates/storage/provider/src/traits/tree_viewer.rs
Labels: M-changelog

#13726 chore!: rm legacy blockchain tree crate
  Cargo.lock
  Cargo.toml
  crates/blockchain-tree/Cargo.toml
  crates/blockchain-tree/docs/mermaid/tree.mmd
  crates/blockchain-tree/src/block_buffer.rs
  crates/blockchain-tree/src/block_indices.rs
  crates/blockchain-tree/src/blockchain_tree.rs
  crates/blockchain-tree/src/bundle.rs
  crates/blockchain-tree/src/canonical_chain.rs
  crates/blockchain-tree/src/chain.rs
  crates/blockchain-tree/src/config.rs
  crates/blockchain-tree/src/externals.rs
  crates/blockchain-tree/src/lib.rs
  crates/blockchain-tree/src/metrics.rs
  crates/blockchain-tree/src/noop.rs
  crates/blockchain-tree/src/shareable.rs
  crates/blockchain-tree/src/state.rs
Labels: M-changelog

#13727 chore!: rename blockchainprovider2
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/main.rs
  crates/e2e-test-utils/src/lib.rs
  crates/engine/local/src/service.rs
  crates/engine/service/src/service.rs
  crates/ethereum/node/tests/e2e/dev.rs
  crates/ethereum/node/tests/it/builder.rs
  crates/exex/exex/src/backfill/job.rs
  crates/exex/exex/src/backfill/stream.rs
  crates/exex/exex/src/manager.rs
  crates/exex/exex/src/notifications.rs
  crates/exex/test-utils/src/lib.rs
  crates/node/builder/src/builder/mod.rs
  crates/node/builder/src/launch/engine.rs
  crates/optimism/bin/src/main.rs
  crates/optimism/node/src/utils.rs
  crates/optimism/node/tests/it/builder.rs
  crates/optimism/node/tests/it/priority.rs
  crates/prune/prune/src/segments/mod.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/providers/mod.rs
  examples/rpc-db/src/main.rs
Labels: M-changelog

#13724 perf(trie): set trie mask bits directly
  crates/trie/sparse/src/trie.rs
Labels: C-perf, A-trie

#13729 chore: rm blockchaintree dep from engine-tree
  Cargo.lock
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/lib.rs
  crates/engine/tree/src/tree/error.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-debt

#13730 chore: rm blockchaintree dep from errors
  Cargo.lock
  crates/errors/Cargo.toml
  crates/errors/src/error.rs
  crates/errors/src/lib.rs
Labels: C-debt

#13731 chore: rm blockchaintree api crate
  Cargo.lock
  Cargo.toml
  crates/blockchain-tree-api/Cargo.toml
  crates/blockchain-tree-api/src/error.rs
  crates/blockchain-tree-api/src/lib.rs
Labels: M-changelog

#13732 chore: rename error types
  crates/engine/tree/src/tree/error.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-debt

#13733 chore: rm redundant std cfgs
  crates/evm/execution-errors/src/lib.rs
Labels: C-debt

#13736 chore: misc SealedBlock prep
  crates/chain-state/src/in_memory.rs
  crates/exex/exex/src/backfill/job.rs
  crates/net/p2p/src/full_block.rs
  crates/primitives/src/block.rs
  crates/stages/stages/src/stages/merkle.rs
  crates/storage/provider/src/test_utils/blocks.rs
Labels: A-sdk

#13737 chore: add `Hardfork::boxed`
  crates/ethereum-forks/src/hardfork/dev.rs
  crates/ethereum-forks/src/hardfork/macros.rs
  crates/ethereum-forks/src/hardfork/mod.rs
  crates/optimism/chainspec/src/base.rs
  crates/optimism/chainspec/src/base_sepolia.rs
  crates/optimism/chainspec/src/op.rs
  crates/optimism/chainspec/src/op_sepolia.rs
  crates/optimism/hardforks/src/dev.rs
  crates/optimism/hardforks/src/hardfork.rs
  examples/bsc-p2p/src/chainspec.rs
  examples/polygon-p2p/src/chain_cfg.rs
Labels: C-enhancement

#12214 perf: introduce moka cached state provider
  Cargo.lock
  Cargo.toml
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/tree/cached_state.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, C-perf, A-db

#13739 feat: add SealedBlock::clone_sealed_header
  crates/chain-state/src/in_memory.rs
  crates/engine/tree/src/tree/mod.rs
  crates/evm/execution-types/src/chain.rs
  crates/exex/exex/src/manager.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/test_utils/mod.rs
  crates/primitives/src/block.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: A-sdk

#13741 feat: add Test traits for Header and Block
  crates/primitives-traits/src/block/mod.rs
  crates/primitives-traits/src/header/sealed.rs
  crates/primitives-traits/src/header/test_utils.rs
  crates/primitives-traits/src/lib.rs
Labels: A-sdk

#13622 perf(persistence): reuse cursor for updating history indices
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-perf, A-db

#13743 chore: remove Block generic from apply_pre_execution_changes
  crates/engine/invalid-block-hooks/src/witness.rs
  crates/ethereum/evm/src/execute.rs
  crates/evm/src/system_calls/mod.rs
Labels: C-enhancement, A-execution, A-sdk

#13744 chore: remove outdated `as _;` imports
  crates/evm/src/execute.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
Labels: C-enhancement, A-sdk

#13746 chore: integrate Test trait for sealed types
  bin/reth/src/commands/debug_cmd/build_block.rs
  crates/consensus/common/src/validation.rs
  crates/engine/tree/src/tree/mod.rs
  crates/primitives-traits/src/block/mod.rs
  crates/primitives-traits/src/header/sealed.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/block.rs
Labels: A-sdk

#13750 feat(trie): add leaf value retrieval methods to `SparseStateTrie`
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
Labels: C-enhancement, A-trie

#13753 chore(trie): simplify blinded provider
  crates/engine/tree/src/tree/root.rs
  crates/trie/sparse/src/blinded.rs
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
  crates/trie/trie/src/proof/blinded.rs
  crates/trie/trie/src/witness.rs
Labels: C-debt, A-trie

#13752 chore!: make senders fields private
  crates/chain-state/src/in_memory.rs
  crates/chain-state/src/test_utils.rs
  crates/engine/tree/src/download.rs
  crates/engine/tree/src/tree/mod.rs
  crates/evm/execution-types/src/chain.rs
  crates/exex/exex/src/backfill/job.rs
  crates/optimism/evm/src/execute.rs
  crates/primitives/src/block.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/rpc/rpc-types-compat/src/block.rs
  crates/rpc/rpc/src/validation.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/transaction-pool/src/blobstore/tracker.rs
Labels: A-sdk

#13755 chore(engine): use Arc<rayon::ThreadPool> for StateRootTask
  crates/engine/tree/benches/state_root_task.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/root.rs
  crates/trie/parallel/src/proof.rs
Labels: C-debt, A-blockchain-tree

#13751 chore(trie): reveal witness by ref
  crates/trie/sparse/src/state.rs
Labels: A-trie

#13717 chore(tree): use MultiProofTargets for PrefetchProofs
  crates/engine/tree/src/tree/root.rs
Labels: C-enhancement, A-trie

#13760 fix(trie): sparse trie tree masks
  crates/engine/tree/src/tree/root.rs
  crates/engine/tree/src/tree/trie_updates.rs
  crates/trie/common/src/proofs.rs
  crates/trie/parallel/src/proof.rs
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
  crates/trie/trie/src/proof/mod.rs
Labels: C-bug, A-trie

#13763 feat(tree): --engine.state-root-task-compare-updates
  bin/reth/src/main.rs
  book/cli/reth/node.md
  crates/engine/tree/src/tree/config.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-cli, A-trie

#13772 chore: make clippy happy
  crates/chain-state/src/notifications.rs
  crates/chainspec/src/spec.rs
  crates/e2e-test-utils/src/network.rs
  crates/engine/tree/src/chain.rs
  crates/ethereum-forks/src/display.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/src/transactions/mod.rs
  crates/net/p2p/src/test_utils/headers.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-types/src/fee_history.rs
  crates/rpc/rpc-testing-util/src/debug.rs
  crates/rpc/rpc-testing-util/src/trace.rs
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/tokio-util/src/event_stream.rs
  crates/transaction-pool/src/pool/best.rs
  crates/trie/sparse/src/trie.rs
Labels: C-debt

#13773 feat(rpc): setters for `TransportRpcModules`
  crates/rpc/rpc-builder/src/lib.rs
Labels: C-enhancement, A-rpc

#13771 feat: add snmalloc support
  Cargo.lock
  Cargo.toml
  bin/reth/Cargo.toml
  crates/cli/util/Cargo.toml
  crates/cli/util/src/allocator.rs
Labels: C-enhancement, C-perf

#13781 perf(op-receipts): reuse `l1_block_info` for multiple receipts
  crates/optimism/rpc/src/eth/block.rs
  crates/optimism/rpc/src/eth/receipt.rs
Labels: A-rpc, A-op-reth

#13685 feat(engine): validate execution requests
  Cargo.lock
  crates/payload/primitives/Cargo.toml
  crates/payload/primitives/src/lib.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-enhancement, E-prague

#13786 feat(trie): blinded providers trace logs
  crates/trie/trie/src/proof/blinded.rs
Labels: C-enhancement, A-observability, A-trie

#13791 fix(cmd): initialize `StaticFileProducer` with config `PruneModes` unwind command
  crates/cli/commands/src/stage/unwind.rs
Labels: C-bug, A-cli

#13789 fix(tree): use in memory trie cursor for trie updates comparison in tree
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/trie_updates.rs
Labels: C-bug, A-observability, A-trie

#13768 fix: track local senders better during truncation
  crates/transaction-pool/src/pool/pending.rs
Labels: C-enhancement, A-tx-pool

#13801 fix: correct trusted peer excemptions
  crates/net/network/src/peers.rs
Labels: C-bug, A-networking

#13810 fix(builder): prague blob params activation
  crates/ethereum/payload/src/lib.rs
Labels: C-bug, A-block-building, E-prague

#13808 fix(trie): remove branch nodes in sparse trie that shouldn't be stored
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
Labels: C-bug, A-trie

#13813 fix(trie): remove branch nodes from updates if it was deleted
  crates/trie/sparse/src/trie.rs
Labels: C-bug, A-trie

#13822 fix(trie): delete removed node from updated nodes in sparse trie
  crates/trie/sparse/src/trie.rs
Labels: C-bug, A-trie

#13825 fix(trie): empty sparse trie branch node masks
  crates/trie/sparse/src/trie.rs
Labels: C-bug, A-trie

#13804 Nit: replace block and sender with RecoveredBlock in ExecutedBlock
  crates/chain-state/src/in_memory.rs
  crates/chain-state/src/memory_overlay.rs
  crates/chain-state/src/test_utils.rs
  crates/engine/tree/src/engine.rs
  crates/engine/tree/src/persistence.rs
  crates/engine/tree/src/tree/mod.rs
  crates/ethereum/payload/src/lib.rs
  crates/node/builder/src/launch/engine.rs
  crates/optimism/payload/src/builder.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/writer/mod.rs
Labels: C-debt, A-sdk

#13824 ci: use reusable cargo update workflow
  .github/workflows/dependencies.yml
Labels: A-ci

#13836 chore(trie): branch node has only one child log
  crates/trie/sparse/src/trie.rs
Labels: C-bug, A-observability, A-trie

#13839 fix: pin clippy to nightly-2025-01-16
  .github/workflows/lint.yml
Labels: C-bug, A-ci

#13840 chore(trie): derive `Clone` on noop cursor factories
  crates/trie/trie/src/hashed_cursor/noop.rs
  crates/trie/trie/src/trie_cursor/noop.rs
Labels: C-debt, C-test, A-trie

#13827 fix(trie): reveal blinded node along with masks in sparse trie
  crates/trie/sparse/src/blinded.rs
  crates/trie/sparse/src/trie.rs
  crates/trie/trie/src/proof/blinded.rs
  crates/trie/trie/src/witness.rs
Labels: C-bug, A-trie

#13842 ci: install mold as the linker
  .github/workflows/book.yml
  .github/workflows/compact.yml
  .github/workflows/docker-git.yml
  .github/workflows/docker.yml
  .github/workflows/integration.yml
  .github/workflows/lint.yml
  .github/workflows/prepare-reth.yml
  .github/workflows/release.yml
  .github/workflows/stage.yml
  .github/workflows/sync.yml
  .github/workflows/unit.yml
  .github/workflows/windows.yml
Labels: C-enhancement, A-ci

#13828 fix(trie): check branch node masks if `store_in_db_trie` is `None`
  crates/trie/sparse/src/trie.rs
Labels: C-bug, A-trie

#13837 feat: expose additional eth functions on engine api
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc/src/engine.rs
Labels: A-op-reth

#13838 chore: remove redundant strategy fn impls
  crates/evm/src/execute.rs
Labels: C-enhancement, A-execution

#13806 feat: Track DA cost in Op Pooled transactions
  crates/optimism/node/src/txpool.rs
Labels: A-op-reth

#13852 test: move reth-primitives tx tests
  crates/ethereum/primitives/src/transaction.rs
  crates/primitives/src/transaction/mod.rs
Labels: C-test

#13855 chore: phase out reth-primitives from eth-wire
  Cargo.lock
  crates/ethereum/primitives/src/lib.rs
  crates/ethereum/primitives/src/transaction.rs
  crates/net/eth-wire-types/Cargo.toml
  crates/net/eth-wire-types/src/blocks.rs
  crates/net/eth-wire-types/src/broadcast.rs
  crates/net/eth-wire-types/src/primitives.rs
  crates/net/eth-wire-types/src/receipts.rs
  crates/net/eth-wire-types/src/status.rs
  crates/net/eth-wire-types/src/transactions.rs
Labels: A-sdk

#13850 test: rm reth-pirmitives block tests
  crates/ethereum/primitives/src/transaction.rs
  crates/primitives/src/block.rs
Labels: C-test

#13823 feat: add `Evm` trait
  Cargo.lock
  crates/engine/invalid-block-hooks/src/witness.rs
  crates/engine/util/src/reorg.rs
  crates/ethereum/evm/Cargo.toml
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/evm/src/lib.rs
  crates/ethereum/node/src/evm.rs
  crates/ethereum/payload/src/lib.rs
  crates/evm/src/lib.rs
  crates/evm/src/system_calls/eip2935.rs
  crates/evm/src/system_calls/eip4788.rs
  crates/evm/src/system_calls/eip7002.rs
  crates/evm/src/system_calls/eip7251.rs
  crates/evm/src/system_calls/mod.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/evm/src/lib.rs
  crates/optimism/payload/src/builder.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/rpc/rpc-eth-api/src/helpers/trace.rs
  crates/rpc/rpc/src/eth/bundle.rs
  crates/rpc/rpc/src/eth/sim_bundle.rs
  examples/custom-beacon-withdrawals/src/main.rs
  examples/custom-evm/src/main.rs
  examples/stateful-precompile/src/main.rs
Labels: A-execution

#13859 chore: use exported oncelock
  .github/assets/check_rv32imac.sh
  Cargo.lock
  crates/optimism/primitives/Cargo.toml
  crates/optimism/primitives/src/lib.rs
  crates/optimism/primitives/src/transaction/signed.rs
Labels: C-debt, A-op-reth

#13860 chore: rm pooled transaction tests
  Cargo.lock
  crates/primitives/Cargo.toml
  crates/primitives/src/transaction/pooled.rs
Labels: C-test

#13863 fix(net): increment in counter after peer's state is marked as in
  crates/net/network/src/peers.rs
Labels: C-bug, A-networking

#13871 refactor: mv proofs mod to reth-primitives-traits and split tests
  Cargo.lock
  crates/ethereum/primitives/src/receipt.rs
  crates/evm/execution-types/src/execution_outcome.rs
  crates/primitives-traits/Cargo.toml
  crates/primitives-traits/src/lib.rs
  crates/primitives-traits/src/proofs.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/proofs.rs
  crates/rpc/rpc/src/eth/helpers/pending_block.rs
Labels: A-sdk

#13876 chore: use correct compressed size estimation fn
  Cargo.lock
  Cargo.toml
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/txpool.rs
Labels: A-op-reth

#13880 chore(ci): add failing rpc-compat test to hive expected failures
  .github/assets/hive/expected_failures.yaml
Labels: C-hivetest, A-ci

#13883 chore: move node builder trait helpers to separate module
  crates/node/builder/src/aliases.rs
  crates/node/builder/src/lib.rs
  crates/node/builder/src/node.rs
Labels: C-enhancement, A-sdk

#13885 feat: add state_hook_sender fn on StateRootTask
  crates/engine/tree/src/tree/root.rs
Labels: C-enhancement, A-trie

#13887 chore: deprecate recoveredtx alias
  crates/chain-state/src/test_utils.rs
  crates/evm/execution-types/src/chain.rs
  crates/optimism/node/src/txpool.rs
  crates/optimism/node/tests/it/priority.rs
  crates/optimism/payload/src/error.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/payload/util/src/traits.rs
  crates/payload/util/src/transaction.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/transaction/mod.rs
  crates/primitives/src/transaction/pooled.rs
  crates/rpc/rpc-eth-types/src/transaction.rs
  crates/rpc/rpc-eth-types/src/utils.rs
  crates/rpc/rpc-types-compat/src/transaction.rs
  crates/rpc/rpc/src/eth/helpers/types.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/mod.rs
Labels: A-sdk

#13890 perf: check block cache for requested header
  crates/rpc/rpc-eth-types/src/cache/mod.rs
Labels: C-perf, A-rpc

#13895 chore: rm legacy helper traits
  crates/e2e-test-utils/src/lib.rs
  crates/node/builder/src/builder/mod.rs
  crates/storage/provider/src/providers/mod.rs
Labels: A-sdk

#13892 chore: move state root task result handling to fn
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-blockchain-tree, A-trie

#13903 feat: add transactions_recovered iter
  crates/primitives-traits/src/block/recovered.rs
  crates/rpc/rpc/src/debug.rs
Labels: A-sdk

#13904 chore: move SealedHeader::cloned to &H
  crates/primitives-traits/src/header/sealed.rs
Labels: A-sdk

#13900 chore: use builtin launch fn for opnode
  crates/optimism/bin/src/main.rs
Labels: A-cli, A-op-reth, A-sdk

#13896 chore: move and integrate ConfigureEvmFor
  crates/engine/invalid-block-hooks/src/witness.rs
  crates/ethereum/node/src/payload.rs
  crates/evm/src/aliases.rs
  crates/evm/src/lib.rs
  crates/node/api/src/node.rs
  crates/node/builder/src/aliases.rs
  crates/node/builder/src/components/builder.rs
  crates/node/builder/src/components/execute.rs
  crates/node/builder/src/components/mod.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/node/src/node.rs
Labels: C-enhancement, A-sdk

#13898 perf(root): untangle the state root task
  crates/engine/tree/benches/state_root_task.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/root.rs
  crates/exex/exex/src/context.rs
  crates/exex/exex/src/dyn_context.rs
  crates/storage/storage-api/src/trie.rs
  crates/trie/sparse/src/trie.rs
Labels: C-debt, C-perf, A-trie

#13906 feat: restore custom build profiles in RETH_BUILD_PROFILE
  crates/node/core/build.rs
Labels: C-enhancement, C-regression, A-cli

#13910 feat: add transactions_iter helper
  crates/chain-state/src/in_memory.rs
  crates/evm/execution-types/src/chain.rs
  crates/primitives-traits/src/block/body.rs
  crates/rpc/rpc-eth-types/src/gas_oracle.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: A-sdk

#13916 chore(ci): set --rpc.eth-proof-window for kurtosis-op
  .github/assets/kurtosis_op_network_params.yaml
Labels: A-ci

#13897 feat: unify recover fn result type
  bin/reth/src/commands/debug_cmd/build_block.rs
  crates/engine/invalid-block-hooks/src/witness.rs
  crates/ethereum/primitives/src/transaction.rs
  crates/optimism/primitives/src/transaction/signed.rs
  crates/primitives-traits/src/block/body.rs
  crates/primitives-traits/src/block/mod.rs
  crates/primitives-traits/src/block/sealed.rs
  crates/primitives-traits/src/crypto.rs
  crates/primitives-traits/src/transaction/recover.rs
  crates/primitives-traits/src/transaction/signed.rs
  crates/primitives/benches/recover_ecdsa_crit.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-types/src/error/mod.rs
  crates/rpc/rpc-eth-types/src/gas_oracle.rs
  crates/rpc/rpc-eth-types/src/receipt.rs
  crates/rpc/rpc/src/debug.rs
  crates/stages/stages/src/stages/sender_recovery.rs
  crates/storage/errors/src/provider.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/static_file/jar.rs
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/transaction-pool/src/maintain.rs
Labels: A-sdk

#13930 chore: use flz estimate
  crates/optimism/node/src/txpool.rs
Labels: C-enhancement, A-op-reth

#13923 chore: retry empty responses
  crates/cli/commands/src/stage/run.rs
  crates/net/p2p/src/headers/client.rs
Labels: A-cli

#13921 chore: remove network dep from tree
  Cargo.lock
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/tree/block_buffer.rs
Labels: C-debt

#13924 feat(no_std): Add `no_std` support for `reth-engine-primitives`
  crates/engine/primitives/Cargo.toml
  crates/engine/primitives/src/error.rs
  crates/engine/primitives/src/event.rs
  crates/engine/primitives/src/lib.rs
  crates/engine/primitives/src/message.rs
Labels: A-consensus, A-dependencies

#13931 feat(no_std): Add `no_std` support for `reth-ethereum-engine-primitives`
  crates/ethereum/engine-primitives/Cargo.toml
  crates/ethereum/engine-primitives/src/lib.rs
  crates/ethereum/engine-primitives/src/payload.rs
Labels: A-consensus, A-dependencies

#13922 feat(no_std): Add `no_std` support for `reth-payload-primitives`
  Cargo.lock
  crates/payload/primitives/Cargo.toml
  crates/payload/primitives/src/error.rs
  crates/payload/primitives/src/lib.rs
  crates/payload/primitives/src/payload.rs
  crates/payload/primitives/src/traits.rs
Labels: A-block-building, A-dependencies

#13932 chore(ci): Exclude `reth-payload-builder` from wasm check
  .github/assets/check_wasm.sh
Labels: A-dependencies, A-ci

#13875 refactor: finalize proofs mod move from `reth-primitives` to `reth-primitives-traits`
  Cargo.lock
  crates/chain-state/src/test_utils.rs
  crates/consensus/common/src/validation.rs
  crates/engine/util/src/reorg.rs
  crates/ethereum/consensus/src/lib.rs
  crates/ethereum/payload/src/lib.rs
  crates/optimism/payload/src/builder.rs
  crates/payload/basic/Cargo.toml
  crates/payload/basic/src/lib.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/lib.rs
  crates/primitives/src/proofs.rs
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-engine-api/tests/it/payload.rs
  crates/rpc/rpc/src/eth/helpers/pending_block.rs
  testing/testing-utils/src/generators.rs
Labels: A-sdk

#13934 chore: remove some unnecessary direct imports
  crates/net/network/src/eth_requests.rs
  crates/net/p2p/src/test_utils/bodies.rs
  crates/node/builder/src/components/execute.rs
  crates/optimism/node/src/engine.rs
  crates/revm/src/database.rs
  crates/storage/provider/src/traits/block.rs
Labels: C-enhancement, C-debt

#13938 fix: temporarily pin crunchy
  Cargo.lock
  Cargo.toml
Labels: C-bug, A-ci

#13933 feat(sdk): introduce PrimitivesTy helper type
  crates/e2e-test-utils/src/node.rs
  crates/ethereum/node/src/payload.rs
  crates/exex/exex/src/context.rs
  crates/exex/exex/src/dyn_context.rs
  crates/node/builder/src/components/builder.rs
  crates/node/builder/src/components/consensus.rs
  crates/node/builder/src/components/execute.rs
  crates/node/builder/src/components/mod.rs
  crates/node/builder/src/launch/exex.rs
  crates/node/types/src/lib.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/node/src/node.rs
Labels: C-enhancement, A-sdk

#13936 feat: add NetworkManager::eth
  crates/net/network/src/manager.rs
  examples/bsc-p2p/src/main.rs
  examples/custom-rlpx-subprotocol/src/main.rs
  examples/network/src/main.rs
  examples/polygon-p2p/src/main.rs
Labels: A-networking

#13939 chore: disable default features for engine primitives
  Cargo.toml
  crates/ethereum/engine-primitives/Cargo.toml
  crates/node/types/Cargo.toml
Labels: A-dependencies

#13941 chore: use alloy-eip2124 directly
  Cargo.lock
  crates/net/network-types/Cargo.toml
  crates/net/network-types/src/peers/mod.rs
Labels: A-dependencies

#13935 chore: rm unused capabilities code
  crates/net/eth-wire/src/capability.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/message.rs
  crates/net/network/src/network.rs
  crates/net/network/src/session/handle.rs
  crates/net/network/src/session/mod.rs
  crates/net/network/src/swarm.rs
Labels: C-debt, A-networking

#13853 feat(test-utils): Make MockEthProvider generic over Transaction
  crates/storage/provider/src/test_utils/mock.rs
Labels: C-test

#13944 chore: do not clone already recovered block
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-blockchain-tree
