Repository paradigmxyz/reth, pull requests merged in 2025-10, with the labels that each got.

#18721 feat(op-reth): add optional state root calc for flashblocks
  Cargo.lock
  crates/optimism/flashblocks/Cargo.toml
  crates/optimism/flashblocks/src/consensus.rs
  crates/optimism/flashblocks/src/payload.rs
  crates/optimism/flashblocks/src/sequence.rs
  crates/optimism/flashblocks/src/service.rs
  crates/optimism/flashblocks/src/worker.rs
Labels: C-enhancement, A-op-reth

#18659 refactor(engine): simplify validate_block_with_state
  crates/engine/tree/src/tree/payload_processor/mod.rs
  crates/engine/tree/src/tree/payload_validator.rs
  crates/engine/tree/src/tree/tests.rs
Labels: C-debt, A-engine

#18819 fix: Add eth69 status validation
  crates/net/eth-wire/src/errors/eth.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/handshake.rs
Labels: A-devp2p

#18796 fix(ress): avoid panic on Missing trie updates in ress provider witness construction
  crates/ress/provider/src/lib.rs
Labels: C-debt, A-trie

#18836 docs: apply spelling and grammar fixes
  .github/assets/hive/expected_failures.yaml
  README.md
  crates/chainspec/src/spec.rs
  crates/engine/tree/src/persistence.rs
  crates/engine/tree/src/tree/state.rs
  crates/era/src/era1_types.rs
  crates/evm/execution-errors/src/trie.rs
  crates/net/eth-wire/src/pinger.rs
  crates/net/eth-wire/src/test_utils.rs
  crates/net/eth-wire/tests/fuzz_roundtrip.rs
  crates/rpc/rpc-eth-types/src/error/mod.rs
  crates/static-file/static-file/src/static_file_producer.rs
  crates/storage/db-api/src/models/mod.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/transaction-pool/src/blobstore/disk.rs
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/pool/blob.rs
  crates/trie/trie/src/forward_cursor.rs
  crates/trie/trie/src/hashed_cursor/mod.rs
  crates/trie/trie/src/node_iter.rs
  crates/trie/trie/src/proof/mod.rs
  crates/trie/trie/src/trie_cursor/depth_first.rs
  crates/trie/trie/src/verify.rs
  crates/trie/trie/src/walker.rs
  crates/trie/trie/src/witness.rs
  docs/crates/db.md
  docs/design/README.md
  docs/vocs/docs/pages/introduction/why-reth.mdx
  docs/vocs/docs/pages/jsonrpc/trace.mdx
  docs/vocs/docs/pages/run/system-requirements.mdx
  docs/vocs/docs/pages/sdk/node-components/network.mdx
  examples/beacon-api-sidecar-fetcher/src/main.rs
Labels: C-docs

#18825 perf: optimize account cache updates to reduce duplicate lookups
  crates/engine/tree/src/tree/cached_state.rs
Labels: C-perf

#18886 refactor: eliminate redundant allocation in precompile cache example
  examples/precompile-cache/src/main.rs
Labels: C-example
