Repository paradigmxyz/reth, pull requests merged in 2025-04, with the labels that each got.

#15429 chore: remove unused deps
  crates/node/builder/Cargo.toml
  crates/optimism/cli/Cargo.toml
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/lib.rs
Labels: C-debt, A-dependencies, A-meta

#15346 refactor(optimism/rpc): Use alloy RpcClient in SequencerClient
  Cargo.lock
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/error.rs
  crates/optimism/rpc/src/sequencer.rs
Labels: A-rpc, A-op-reth

#15444 fix: always set empty request hash after isthmus
  crates/optimism/evm/src/build.rs
Labels: C-bug, A-op-reth

#15446 chore: add more logs to init-state, improve errors
  crates/cli/commands/src/init_state/without_evm.rs
Labels: C-enhancement, A-observability, A-cli

#15336 perf(trie): reduce hashed seeks in `TrieNodeIter`
  crates/trie/trie/src/node_iter.rs
  crates/trie/trie/src/walker.rs
Labels: C-perf, A-trie

#15449 feat: add Client trait for snap sync downloader client
  crates/net/eth-wire-types/src/lib.rs
  crates/net/p2p/src/lib.rs
  crates/net/p2p/src/snap/client.rs
  crates/net/p2p/src/snap/mod.rs
Labels: A-networking

#15436 feat(examples): add custom engine API to custom-node example
  Cargo.lock
  examples/custom-node/Cargo.toml
  examples/custom-node/src/engine.rs
  examples/custom-node/src/engine_api.rs
  examples/custom-node/src/lib.rs
Labels: C-enhancement, A-sdk, C-example

#15456 feat(tree): set multiproof task concurrency independent of Rayon thread pool
  crates/engine/tree/src/tree/payload_processor/executor.rs
  crates/engine/tree/src/tree/payload_processor/mod.rs
  crates/engine/tree/src/tree/payload_processor/multiproof.rs
Labels: C-enhancement, A-engine

#15458 feat(examples): route engine messages from custom engine api in custom-node example
  Cargo.lock
  examples/custom-node/Cargo.toml
  examples/custom-node/src/engine_api.rs
Labels: C-enhancement, A-sdk, C-example

#15465 chore(op-txpool): Update `ExecutingDescriptor` serialization
  Cargo.lock
  crates/optimism/txpool/Cargo.toml
  crates/optimism/txpool/src/supervisor/message.rs
Labels: C-enhancement, A-op-reth, OP-interop

#15466 feat(tx): Implement `FromTxWithEncoded<TransactionSigned>` for `TxEnv`
  Cargo.lock
  Cargo.toml
  crates/ethereum/evm/src/lib.rs
  crates/ethereum/primitives/src/transaction.rs
  crates/evm/src/lib.rs
  crates/optimism/evm/src/lib.rs
  crates/optimism/primitives/src/transaction/signed.rs
Labels: C-enhancement, A-sdk

#15467 fix(op-interop): don't down score peers for invalid interop txns
  crates/optimism/txpool/src/error.rs
Labels: C-bug, A-tx-pool, A-op-reth, OP-interop

#15438 feat(trie): node iter metrics
  crates/trie/db/src/storage.rs
  crates/trie/parallel/src/metrics.rs
  crates/trie/parallel/src/proof.rs
  crates/trie/parallel/src/root.rs
  crates/trie/sparse/benches/root.rs
  crates/trie/sparse/src/trie.rs
  crates/trie/trie/src/lib.rs
  crates/trie/trie/src/metrics.rs
  crates/trie/trie/src/node_iter.rs
  crates/trie/trie/src/proof/mod.rs
  crates/trie/trie/src/trie.rs
Labels: C-enhancement, A-observability, A-trie

#15470 feat: support simulation in blockbuilder
  Cargo.lock
  Cargo.toml
  crates/evm/src/execute.rs
  crates/evm/src/lib.rs
  crates/rpc/rpc-eth-types/src/simulate.rs
Labels: C-enhancement, A-rpc, A-op-reth

#15469 chore: bump version 1.3.5
  Cargo.lock
  Cargo.toml
Labels: A-meta

#15482 fix: actually override simulated
  crates/evm/src/execute.rs
Labels: C-bug, A-rpc

#15484 fix: set None storage lookup to NotCached
  crates/engine/tree/src/tree/cached_state.rs
Labels: C-bug

#15352 feat(engine): parallel state root fallback metric
  crates/engine/tree/src/tree/metrics.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-observability, A-engine

#15420 refactor(trie): introduce `SubNodePosition` enum
  crates/trie/trie/src/trie_cursor/mod.rs
  crates/trie/trie/src/trie_cursor/subnode.rs
  crates/trie/trie/src/walker.rs
Labels: C-debt, A-trie

#15471 perf(trie): cache last hashed entry seek in trie node iter
  crates/trie/trie/src/metrics.rs
  crates/trie/trie/src/node_iter.rs
Labels: C-bug, C-perf, A-trie

#15450 feat: handle unknown eth message
  crates/net/eth-wire-types/src/capability.rs
  crates/net/eth-wire-types/src/message.rs
  crates/net/eth-wire/src/capability.rs
  crates/net/eth-wire/src/errors/eth.rs
  crates/net/eth-wire/src/ethstream.rs
  crates/net/network/src/message.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/conn.rs
Labels: C-enhancement, D-good-first-issue, A-networking

#15512 chore: add conversion helper for eth69
  crates/net/eth-wire-types/src/status.rs
Labels: A-networking

#15514 fix: incorrect `derive_more` import
  crates/net/eth-wire/src/handshake.rs
  examples/bsc-p2p/src/handshake.rs
Labels: C-debt

#15504 fix: remove global instance
  bin/reth/src/cli/mod.rs
  book/cli/reth.md
  book/cli/reth/config.md
  book/cli/reth/db.md
  book/cli/reth/db/checksum.md
  book/cli/reth/db/clear.md
  book/cli/reth/db/clear/mdbx.md
  book/cli/reth/db/clear/static-file.md
  book/cli/reth/db/diff.md
  book/cli/reth/db/drop.md
  book/cli/reth/db/get.md
  book/cli/reth/db/get/mdbx.md
  book/cli/reth/db/get/static-file.md
  book/cli/reth/db/list.md
  book/cli/reth/db/path.md
  book/cli/reth/db/stats.md
  book/cli/reth/db/version.md
  book/cli/reth/debug.md
  book/cli/reth/debug/build-block.md
  book/cli/reth/debug/execution.md
  book/cli/reth/debug/in-memory-merkle.md
  book/cli/reth/debug/merkle.md
  book/cli/reth/dump-genesis.md
  book/cli/reth/import.md
  book/cli/reth/init-state.md
  book/cli/reth/init.md
  book/cli/reth/p2p.md
  book/cli/reth/p2p/body.md
  book/cli/reth/p2p/header.md
  book/cli/reth/p2p/rlpx.md
  book/cli/reth/p2p/rlpx/ping.md
  book/cli/reth/prune.md
  book/cli/reth/recover.md
  book/cli/reth/recover/storage-tries.md
  book/cli/reth/stage.md
  book/cli/reth/stage/drop.md
  book/cli/reth/stage/dump.md
  book/cli/reth/stage/dump/account-hashing.md
  book/cli/reth/stage/dump/execution.md
  book/cli/reth/stage/dump/merkle.md
  book/cli/reth/stage/dump/storage-hashing.md
  book/cli/reth/stage/run.md
  book/cli/reth/stage/unwind.md
  book/cli/reth/stage/unwind/num-blocks.md
  book/cli/reth/stage/unwind/to-block.md
  crates/optimism/cli/src/lib.rs
Labels: C-bug, A-cli

#15519 refactor(net): add ` EthStreamInner` for `EthStream`
  crates/net/eth-wire/src/ethstream.rs
  crates/net/eth-wire/src/lib.rs
Labels: C-debt, A-networking

#15526 fix: add fcu v1 for op engine
  crates/optimism/rpc/src/engine.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: C-bug, A-op-reth

#15532 chore: return invalid reward percentiles as invalid params
  crates/rpc/rpc-eth-types/src/error/mod.rs
Labels: C-bug, A-rpc

#15530 chore(lint): Replace allow with expect for `dead_code` and rm unfullfilled lints
  bin/reth-bench/src/bench/output.rs
  crates/chain-state/src/chain_info.rs
  crates/chain-state/src/in_memory.rs
  crates/engine/primitives/src/forkchoice.rs
  crates/engine/tree/src/test_utils.rs
  crates/engine/tree/src/tree/mod.rs
  crates/net/network/src/cache.rs
  crates/net/network/src/fetch/mod.rs
  crates/net/network/src/peers.rs
  crates/optimism/rpc/src/eth/ext.rs
  crates/rpc/rpc/src/eth/helpers/signer.rs
  crates/rpc/rpc/src/eth/sim_bundle.rs
  crates/storage/codecs/src/lib.rs
  crates/storage/db-api/src/tables/codecs/fuzz/mod.rs
  crates/storage/errors/src/provider.rs
  crates/storage/nippy-jar/src/compression/zstd.rs
  crates/storage/nippy-jar/src/lib.rs
  crates/transaction-pool/src/identifier.rs
  crates/transaction-pool/src/pool/blob.rs
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-debt

#15535 fix: blob params parsing and configuring
  crates/chainspec/src/spec.rs
  crates/ethereum/evm/src/lib.rs
Labels: C-bug

#15520 feat(examples): add ConfigureEvm impl for custom-node example
  Cargo.lock
  examples/custom-node/Cargo.toml
  examples/custom-node/src/evm.rs
  examples/custom-node/src/lib.rs
Labels: C-enhancement, A-sdk, C-example

#15487 chore: add test for CachedState and ProviderCaches storage values
  crates/engine/tree/src/tree/cached_state.rs
Labels: C-test, A-engine

#15396 feat: introduce `reth-era` crate with `era1` file types
  .github/CODEOWNERS
  Cargo.lock
  Cargo.toml
  crates/era/Cargo.toml
  crates/era/src/e2s_file.rs
  crates/era/src/e2s_types.rs
  crates/era/src/era1_file.rs
  crates/era/src/era1_types.rs
  crates/era/src/execution_types.rs
  crates/era/src/lib.rs
Labels: C-enhancement, A-networking

#15538 chore: silence warnings
  crates/trie/trie/src/node_iter.rs
  crates/trie/trie/src/trie.rs
Labels: C-debt

#15397 Test Cases cut down on reth_ethereum_primitives::Transaction usage
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/traits.rs
Labels: D-good-first-issue, A-sdk

#15553 docs: Update installation.md hardware requirements
  book/installation/installation.md
Labels: C-docs

#15557 chore: clean unused deps
  Cargo.lock
  crates/ethereum/evm/Cargo.toml
  crates/primitives/Cargo.toml
  crates/trie/trie/Cargo.toml
Labels: A-dependencies

#15561 chore:added revm re-export for reth-ethereum and reth-op
  Cargo.lock
  crates/ethereum/reth/Cargo.toml
  crates/ethereum/reth/src/lib.rs
  crates/optimism/reth/Cargo.toml
  crates/optimism/reth/src/lib.rs
  examples/custom-beacon-withdrawals/Cargo.toml
  examples/custom-beacon-withdrawals/src/main.rs
Labels: A-dependencies

#15563 chore: correct typo of `set_interop_deadline` method in transaction handling
  crates/optimism/txpool/src/interop.rs
  crates/optimism/txpool/src/maintain.rs
  crates/optimism/txpool/src/transaction.rs
  crates/optimism/txpool/src/validator.rs
Labels: A-op-reth

#15552 fix: config defaults for eth components
  crates/ethereum/node/src/node.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/rpc/rpc/src/eth/builder.rs
Labels: C-bug, A-rpc

#15543 chore: add status enum for handshake to support status69 decoding
  crates/net/eth-wire-types/src/lib.rs
  crates/net/eth-wire-types/src/message.rs
  crates/net/eth-wire-types/src/status.rs
  crates/net/eth-wire/src/handshake.rs
Labels: C-enhancement, A-networking

#15572 chore:changed import for custom-evm
  Cargo.lock
  examples/custom-evm/Cargo.toml
  examples/custom-evm/src/main.rs
Labels: A-dependencies

#15521 chore: set prewarm concurrency to 64
  crates/engine/tree/src/tree/payload_processor/prewarm.rs
Labels: C-enhancement, A-execution

#15582 feat: `Prague` mainnet timestamp
  Cargo.lock
  Cargo.toml
  crates/chainspec/src/spec.rs
Labels: E-prague

#15503 chore: fix doc comment on `get_storage`
  crates/engine/tree/src/tree/cached_state.rs
Labels: C-docs

#15357 chore: Add pull request title lint
  .github/workflows/pr-title.yml
Labels: A-meta

#15524 feat(evm): Accept executable transaction as the input for block builder
  crates/evm/src/execute.rs
  crates/evm/src/lib.rs
  crates/rpc/rpc-eth-types/src/simulate.rs
Labels: C-enhancement, A-execution, A-sdk

#15578 fix: typo
  crates/optimism/rpc/src/engine.rs
  crates/trie/trie/src/node_iter.rs
Labels: C-docs

#15605 fix: pick 1559 fees correctly for dynamic fee
  Cargo.lock
  Cargo.toml
  crates/evm/src/execute.rs
  crates/rpc/rpc-eth-types/src/simulate.rs
  crates/rpc/rpc/src/eth/helpers/types.rs
  examples/custom-beacon-withdrawals/src/main.rs
  examples/custom-node/src/evm.rs
Labels: C-bug, C-enhancement, A-rpc

#15529 chore: release 1.3.8
  Cargo.lock
  Cargo.toml
Labels: A-meta

#15252 feat: add ability to handle dedicated storage proof result
  crates/engine/tree/src/tree/payload_processor/multiproof.rs
  crates/trie/common/src/proofs.rs
Labels: A-trie

#15620 fix: use `--http.corsdomain` for http rpc server
  crates/rpc/rpc-builder/src/lib.rs
Labels: C-bug, M-changelog, A-rpc

#15607 chore: rm bundlestateprovider
  crates/storage/provider/src/providers/bundle_state_provider.rs
  crates/storage/provider/src/providers/mod.rs
Labels: C-debt

#15622 fix!(rpc): wrap call many response in vec
  crates/rpc/rpc-eth-api/src/core.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
Labels: M-changelog, A-rpc

#15626 chore: bump op-alloy
  Cargo.lock
  Cargo.toml
Labels: A-sdk

#15611 test: activate holocene and isthmus in kurtosis-op
  .github/assets/kurtosis_op_network_params.yaml
Labels: C-test, A-op-reth, A-ci

#15629 chore: add serdebincodecompat to optxenvelope
  Cargo.lock
  Cargo.toml
  crates/primitives-traits/Cargo.toml
  crates/primitives-traits/src/serde_bincode_compat.rs
Labels: A-op-reth

#15628 chore: prep alloy TxEnvelope transition
  crates/optimism/payload/src/builder.rs
  crates/optimism/payload/src/traits.rs
  crates/optimism/primitives/src/transaction/mod.rs
  crates/optimism/primitives/src/transaction/signed.rs
Labels: A-op-reth, A-sdk

#15531 chore(lint): Remove redundant lint attributes
  crates/engine/tree/src/tree/payload_processor/executor.rs
  crates/ethereum/primitives/src/transaction.rs
  crates/evm/execution-types/src/chain.rs
  crates/evm/src/execute.rs
  crates/net/discv5/src/lib.rs
  crates/net/network/src/budget.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/transactions/validation.rs
  crates/net/peers/src/lib.rs
  crates/optimism/primitives/src/transaction/signed.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/primitives-traits/src/crypto.rs
  crates/rpc/rpc-builder/src/eth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-builder/src/metrics.rs
  crates/rpc/rpc-engine-api/src/lib.rs
  crates/rpc/rpc-eth-api/src/helpers/block.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/storage/db-api/src/cursor.rs
  crates/storage/db-api/src/tables/codecs/fuzz/mod.rs
  crates/storage/libmdbx-rs/src/environment.rs
  crates/storage/libmdbx-rs/src/txn_manager.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/trie/sparse/src/trie.rs
  testing/ef-tests/tests/tests.rs
Labels: C-debt

#15630 feat(engine): enable prewarming & caching by default
  book/cli/reth/node.md
  crates/engine/primitives/src/config.rs
  crates/engine/tree/src/tree/payload_processor/mod.rs
  crates/node/core/src/args/engine.rs
Labels: C-perf, A-cli

#15636 chore: make build eth api async
  Cargo.lock
  crates/ethereum/node/src/node.rs
  crates/node/builder/src/rpc.rs
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/eth/mod.rs
Labels: A-sdk

#15642 chore: changed import for network(examples)
  Cargo.lock
  examples/network/Cargo.toml
  examples/network/src/main.rs
Labels: A-sdk

#15644 chore: changed imports in network-proxy (examples)
  Cargo.lock
  examples/network-proxy/Cargo.toml
  examples/network-proxy/src/main.rs
Labels: A-sdk

#15645 chore: changed import for node-event-hooks(example)
  Cargo.lock
  examples/node-event-hooks/Cargo.toml
  examples/node-event-hooks/src/main.rs
Labels: A-sdk

#15647 chore: changed import for precompile-cache(examples)
  Cargo.lock
  examples/precompile-cache/Cargo.toml
  examples/precompile-cache/src/main.rs
Labels: A-sdk

#15650 chore: changed import for txpool-tracing(examples)
  Cargo.lock
  examples/txpool-tracing/Cargo.toml
  examples/txpool-tracing/src/main.rs
Labels: A-sdk

#15652 fix(era1): use framed snap encoding/decoding instead of raw one
  crates/era/src/execution_types.rs
Labels: C-enhancement

#15651 feat: add no-local-exemptions settings to MaintainPoolConfig
  crates/ethereum/node/src/node.rs
  crates/optimism/node/src/node.rs
  crates/transaction-pool/src/maintain.rs
Labels: A-tx-pool

#15660 chore: remove unused evm_config field in EngineApiTreeHandler
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-engine

#15667 ci: add `revert` to allowed PR titles
  .github/workflows/pr-title.yml
Labels: A-ci

#15637 perf(trie): reserve space for new proof nodes ahead of time
  crates/trie/sparse/src/metrics.rs
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
Labels: C-perf, A-trie

#15685 fix: op isthmus activation timestamps
  crates/optimism/chainspec/src/lib.rs
  crates/optimism/hardforks/src/lib.rs
Labels: A-op-reth

#15691 chore(trie): make `RevealedNode` usable externally
  crates/trie/sparse/src/blinded.rs
Labels: C-enhancement, A-trie

#15687 docs: add op-reth to hardfork checklist
  HARDFORK-CHECKLIST.md
Labels: C-docs, A-op-reth

#15686 feat: add bincode compat to ethereum tx envelope
  crates/primitives-traits/src/serde_bincode_compat.rs
Labels: A-sdk

#15267 perf(discv5): Relax peer filter, fallback on source socket for enr missing tcp port
  crates/net/discv5/src/error.rs
  crates/net/discv5/src/lib.rs
  crates/net/network/tests/it/startup.rs
Labels: C-perf, A-discv5

#15341 feat(net): add transaction gossip policy
  book/cli/reth/debug/execution.md
  book/cli/reth/debug/in-memory-merkle.md
  book/cli/reth/debug/merkle.md
  book/cli/reth/node.md
  book/cli/reth/p2p.md
  book/cli/reth/stage/run.md
  crates/net/network/src/builder.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/src/transactions/config.rs
  crates/net/network/src/transactions/mod.rs
  crates/net/network/tests/it/txgossip.rs
  crates/node/builder/src/builder/mod.rs
  crates/node/core/src/args/network.rs
Labels: C-enhancement, D-good-first-issue, A-networking, A-sdk

#15706 chore: Remove TODO
  bin/reth-bench/src/bench/new_payload_only.rs
Labels: C-debt

#15709 feat: added getter functions for PeerMetadata
  crates/net/network/src/transactions/mod.rs
Labels: A-networking

#15713 chore: bump ssz
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#15574 test: benchmark for fetch pending hashes
  crates/net/network/benches/tx_manager_hash_fetching.rs
  crates/net/network/src/test_utils/mod.rs
  crates/net/network/src/test_utils/transactions.rs
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
Labels: A-networking

#15683 feat: use L2 timestamps for mapped L1
  crates/optimism/chainspec/src/lib.rs
Labels: A-op-reth

#15670 fix(op-interop): incorrect parsing of `supervisor_checkAccessList` error
  crates/optimism/txpool/src/error.rs
  crates/optimism/txpool/src/supervisor/client.rs
  crates/optimism/txpool/src/supervisor/errors.rs
  crates/optimism/txpool/src/supervisor/mod.rs
Labels: C-bug, A-tx-pool, A-op-reth, OP-interop

#15717 chore: bump alloy-trie
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#15676 fix(engine): update cached bytecodes with bundle state
  crates/engine/tree/src/tree/cached_state.rs
Labels: C-bug, C-perf, A-engine

#15714 chore: bump op-revm
  Cargo.lock
  Cargo.toml
Labels: A-dependencies, A-op-reth

#15718 chore(op-consensus): Remove redundant module
  crates/optimism/consensus/src/lib.rs
  crates/optimism/consensus/src/validation/canyon.rs
  crates/optimism/consensus/src/validation/mod.rs
  crates/optimism/consensus/src/validation/shanghai.rs
Labels: C-debt, A-consensus, A-op-reth

#15570 Add metric for supervisor RPC latency
  crates/optimism/txpool/src/supervisor/client.rs
  crates/optimism/txpool/src/supervisor/metrics.rs
  crates/optimism/txpool/src/supervisor/mod.rs
Labels: D-good-first-issue, A-tx-pool, A-observability, A-op-reth, OP-interop

#15723 chore: rm lifetime
  crates/optimism/txpool/src/supervisor/client.rs
Labels: A-op-reth

#15634 feat!: replace OpTransactionSigned with alloys
  Cargo.lock
  crates/optimism/evm/src/execute.rs
  crates/optimism/node/src/node.rs
  crates/optimism/node/tests/it/priority.rs
  crates/optimism/primitives/Cargo.toml
  crates/optimism/primitives/src/alloy_compat.rs
  crates/optimism/primitives/src/lib.rs
  crates/optimism/primitives/src/transaction/mod.rs
  crates/optimism/primitives/src/transaction/signed.rs
  crates/optimism/primitives/src/transaction/tx_type.rs
  crates/optimism/rpc/src/eth/block.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/optimism/txpool/src/transaction.rs
  examples/custom-node/src/primitives/tx.rs
Labels: C-enhancement, A-op-reth, A-sdk

#15413 deps: bump libmdbx to 0.12.13
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/VERSION.txt
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_chk.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c++
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h++
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_chk.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_copy.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_drop.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_dump.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_load.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_stat.c
Labels: A-db, A-dependencies

#15731 fix: make CompactEnvelope equivalent
  crates/storage/codecs/src/alloy/transaction/ethereum.rs
Labels: A-db

#15735 chore: bump revm
  Cargo.toml
Labels: A-dependencies

#15736 fix: to_compact for CompactEnvelope
  crates/ethereum/primitives/src/transaction.rs
  crates/optimism/primitives/src/transaction/signed.rs
  crates/storage/codecs/src/alloy/transaction/ethereum.rs
Labels: C-bug, A-db

#15732 chore: exempt static peers from removal
  crates/net/network/src/peers.rs
Labels: A-networking

#15710 feat: add config for reserved CPU cores Resolves paradigmxyz/reth#15633
  book/cli/reth/node.md
  crates/engine/primitives/src/config.rs
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/engine.rs
  crates/node/core/src/args/engine.rs
  crates/node/core/src/node_config.rs
Labels: C-enhancement, A-cli

#15654 feat: adding cli --rpc.txfeecap flag
  book/cli/reth/node.md
  crates/cli/util/src/lib.rs
  crates/cli/util/src/parsers.rs
  crates/ethereum/node/src/node.rs
  crates/node/core/src/args/rpc_server.rs
  crates/optimism/node/src/node.rs
  crates/rpc/rpc-eth-types/src/error/mod.rs
  crates/rpc/rpc-server-types/src/constants.rs
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool, A-cli

#15756 chore: bump version 1.3.10
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#15763 feat: disable EIP-3607 for `eth_createAccessList`
  crates/rpc/rpc-eth-api/src/helpers/call.rs
Labels: A-rpc

#15761 refactor: simplify announcement filter
  crates/net/network/src/lib.rs
  crates/net/network/src/transactions/validation.rs
Labels: A-networking

#15536 feat: add precompile cache for execution
  Cargo.lock
  book/cli/reth/node.md
  crates/ethereum/evm/src/factory.rs
  crates/ethereum/evm/src/lib.rs
  crates/ethereum/node/src/node.rs
  crates/evm/Cargo.toml
  crates/evm/src/lib.rs
  crates/evm/src/precompile_cache.rs
  crates/node/core/src/args/engine.rs
Labels: C-perf

#15733 feat!: replace OpTransactionSigned with alloys
  Cargo.lock
  crates/optimism/evm/src/execute.rs
  crates/optimism/node/src/node.rs
  crates/optimism/node/tests/it/priority.rs
  crates/optimism/primitives/Cargo.toml
  crates/optimism/primitives/src/alloy_compat.rs
  crates/optimism/primitives/src/lib.rs
  crates/optimism/primitives/src/transaction/mod.rs
  crates/optimism/primitives/src/transaction/signed.rs
  crates/optimism/primitives/src/transaction/tx_type.rs
  crates/optimism/rpc/src/eth/block.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/optimism/txpool/src/transaction.rs
  examples/custom-node/src/primitives/tx.rs
Labels: A-sdk

#15766 feat(op-isthmus): Add isthmus mainnet timestamps to op hardforks
  crates/optimism/chainspec/src/lib.rs
  crates/optimism/hardforks/src/lib.rs
Labels: A-op-reth, OP-isthmus

#15773 fix: relax body against validation for isthmus
  Cargo.lock
  crates/optimism/consensus/Cargo.toml
  crates/optimism/consensus/src/lib.rs
  crates/optimism/consensus/src/validation/mod.rs
Labels: C-bug, C-enhancement, P-high, A-op-reth

#15769 fix(discv5): `ForkId` set to head block
  Cargo.lock
  crates/ethereum-forks/src/hardforks/mod.rs
  crates/net/network/Cargo.toml
  crates/net/network/src/config.rs
Labels: C-bug, A-op-reth

#15780 chore: bump inspectors 0.19.1
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#15781 chore: Relax the bounds on `DBProvider`
  crates/storage/storage-api/src/account.rs
  crates/storage/storage-api/src/database_provider.rs
Labels: A-sdk

#15564 chore: enable `invalid_blocks` tests in EF
  testing/ef-tests/src/cases/blockchain_test.rs
  testing/ef-tests/src/models.rs
  testing/ef-tests/tests/tests.rs
Labels: C-test

#15694 feat: MockEthProvider generic over NodePrimitives
  crates/storage/provider/src/test_utils/mock.rs
Labels: D-good-first-issue, C-test

#15796 fix: skip isthmus root validation if we dont have the parent state
  crates/optimism/node/src/engine.rs
Labels: A-op-reth, OP-isthmus

#15788 refactor(block): Inline `from_block_with_transaction` fn
  crates/rpc/rpc-types-compat/src/block.rs
Labels: C-perf

#15797 chore: release 1.3.12
  Cargo.lock
  Cargo.toml
Labels: A-op-reth, OP-isthmus

#15225 feat(transaction-pool): check on disk store in case of blob cache misses
  crates/transaction-pool/src/blobstore/disk.rs
Labels: A-tx-pool, E-osaka

#15347 feat(cli): add bootnode command
  Cargo.lock
  crates/cli/commands/Cargo.toml
  crates/cli/commands/src/p2p/bootnode.rs
  crates/cli/commands/src/p2p/mod.rs
Labels: D-good-first-issue, A-networking

#15804 chore: removed deprecated endpoint
  crates/optimism/rpc/src/engine.rs
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-builder/tests/it/auth.rs
  crates/rpc/rpc-engine-api/src/capabilities.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-engine-api/src/metrics.rs
Labels: C-debt, A-rpc

#15690 chore(trie): `trie_type` behind flag
  crates/trie/parallel/src/proof.rs
  crates/trie/parallel/src/root.rs
  crates/trie/sparse/benches/root.rs
  crates/trie/sparse/src/trie.rs
  crates/trie/trie/src/node_iter.rs
  crates/trie/trie/src/proof/mod.rs
  crates/trie/trie/src/trie.rs
Labels: A-trie

#15679 feat(witness): `always_include_root_node` flag
  crates/trie/trie/src/witness.rs
Labels: C-enhancement, A-trie

#15598 fix(evm): custom blob params
  crates/ethereum/evm/src/lib.rs
Labels: C-bug, S-blocked, A-execution

#15619 feat: add support for Eth69 receipts representation
  crates/ethereum/primitives/src/receipt.rs
  crates/optimism/primitives/Cargo.toml
  crates/optimism/primitives/src/receipt.rs
Labels: C-enhancement, A-networking

#15808 chore: removed TransitionConfigurationExchanged event variant
  crates/chain-state/src/chain_info.rs
  crates/chain-state/src/in_memory.rs
  crates/engine/primitives/src/message.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/util/src/engine_store.rs
  crates/node/events/src/cl.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/storage-api/src/chain_info.rs
Labels: C-debt

#15805 fix: pin teku image
  .github/assets/kurtosis_op_network_params.yaml
Labels: A-ci

#15811 chore: improve etherscan debug error reporting
  Cargo.lock
  crates/consensus/debug-client/Cargo.toml
  crates/consensus/debug-client/src/providers/etherscan.rs
Labels: A-observability

#15809 chore: Update execution spec tests to v17.0
  .github/workflows/unit.yml
  Makefile
Labels: C-test

#15798 feat(storage-api): move BlockExecutionWriter trait from provider to storage-api
  crates/storage/provider/src/traits/block.rs
  crates/storage/storage-api/src/block_writer.rs
  crates/storage/storage-api/src/lib.rs
Labels: A-dependencies

#15817 docs: some docs on sync gap channel
  crates/stages/api/src/pipeline/mod.rs
  crates/stages/stages/src/stages/headers.rs
Labels: C-docs

#15816 docs: Fix missing escaped newline
  book/run/optimism.md
Labels: C-docs

#15799 chore(all): remove duplicate words
  crates/net/eth-wire-types/src/message.rs
  crates/net/eth-wire/src/errors/eth.rs
  crates/net/network/src/transactions/mod.rs
  crates/payload/builder-primitives/src/events.rs
  crates/rpc/ipc/src/server/mod.rs
  crates/transaction-pool/src/test_utils/gen.rs
  crates/trie/trie/src/metrics.rs
  testing/testing-utils/src/generators.rs
Labels: C-docs

#15828 test(e2e): add `BroadcastNextNewPayload` action
  crates/e2e-test-utils/src/testsuite/actions.rs
  crates/e2e-test-utils/src/testsuite/mod.rs
Labels: C-test

#15838 fix: ignore engine-auth failures
  .github/assets/hive/expected_failures.yaml
Labels: C-hivetest, A-ci

#15839 fix: kurtosis-op job
  .github/assets/kurtosis_op_network_params.yaml
  .github/workflows/kurtosis-op.yml
Labels: C-bug, A-ci

#15836 docs: Update witness.rs
  crates/revm/src/witness.rs
Labels: C-docs

#15819 refactor: Simplify HeaderSyncGapProvider trait
  crates/stages/stages/src/stages/headers.rs
  crates/storage/provider/Cargo.toml
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/traits/header_sync_gap.rs
Labels: C-debt

#15824 docs: correct indentation in rpc.rs
  crates/node/builder/src/rpc.rs
Labels: A-observability

#15842 test(crates): add comprehensive tests for mock transaction factory and modifications
  crates/transaction-pool/src/test_utils/mock.rs
Labels: A-tx-pool

#15360 feat: task executor accessible globally
  crates/tasks/src/lib.rs
Labels: D-good-first-issue, C-debt, A-sdk

#15689 feat(engine): Compare sorted bundle states in witness invalid block hook
  Cargo.lock
  crates/engine/invalid-block-hooks/Cargo.toml
  crates/engine/invalid-block-hooks/src/witness.rs
Labels: C-enhancement, A-observability, A-engine

#15737 feat(era): Add history import
  .github/assets/check_wasm.sh
  Cargo.lock
  Cargo.toml
  crates/era-downloader/Cargo.toml
  crates/era-downloader/src/client.rs
  crates/era-downloader/src/stream.rs
  crates/era-downloader/tests/it/main.rs
  crates/era-import/Cargo.toml
  crates/era-import/src/history.rs
  crates/era-import/src/lib.rs
  crates/era-import/tests/it/history.rs
  crates/era-import/tests/it/main.rs
  crates/era/src/era1_file.rs
Labels: C-enhancement, A-db

#15846 chore: re-pin crunchy to 0.2.2 after weekly `cargo update`
  .github/workflows/dependencies.yml
Labels: A-ci

#15849 chore: rename `send_rpc_call` into `request` with `pub`
  crates/optimism/rpc/src/sequencer.rs
Labels: A-op-reth

#15764 feat(engine): enable prewarming & caching by default
  book/cli/reth/node.md
  crates/engine/primitives/src/config.rs
  crates/engine/tree/src/tree/payload_processor/mod.rs
  crates/node/core/src/args/engine.rs
Labels: C-perf, A-cli

#15857 refactor(reth): Extract `Cli` into `ethereum-cli` crate
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/cli/mod.rs
  bin/reth/src/commands/mod.rs
  bin/reth/src/lib.rs
  crates/ethereum/cli/Cargo.toml
  crates/ethereum/cli/src/debug_cmd/build_block.rs
  crates/ethereum/cli/src/debug_cmd/execution.rs
  crates/ethereum/cli/src/debug_cmd/in_memory_merkle.rs
  crates/ethereum/cli/src/debug_cmd/merkle.rs
  crates/ethereum/cli/src/debug_cmd/mod.rs
  crates/ethereum/cli/src/interface.rs
  crates/ethereum/cli/src/lib.rs
Labels: C-enhancement, A-cli

#15871 fix(cli): drop ExEx WAL only if it exists
  crates/storage/db-common/src/db_tool/mod.rs
Labels: C-bug, A-cli

#15867 fix: fail send_raw_transaction if forwarding fails
  crates/optimism/rpc/src/eth/transaction.rs
Labels: C-bug, A-op-reth

#15874 chore: bump alloy 0.15
  Cargo.lock
  Cargo.toml
  crates/ethereum/node/tests/e2e/p2p.rs
  crates/ethereum/node/tests/e2e/rpc.rs
  crates/ethereum/node/tests/e2e/utils.rs
  crates/net/network/tests/it/connect.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/otterscan.rs
Labels: A-dependencies

#15875 fix: correctly set `extra_data` for eth payload builder
  crates/ethereum/node/src/payload.rs
Labels: C-bug

#15879 chore: relax default constraints
  crates/storage/db/benches/criterion.rs
  crates/storage/db/benches/utils.rs
Labels: C-debt

#15880 chore: relax more default
  crates/net/eth-wire/tests/fuzz_roundtrip.rs
Labels: C-test

#15858 feat: added support for --debug.rpc-consensus-ws
  Cargo.lock
  crates/node/builder/Cargo.toml
  crates/node/builder/src/launch/debug.rs
Labels: C-enhancement, A-cli

#15884 chore(metrics): summable reth_info value
  crates/node/metrics/src/version.rs
Labels: A-observability

#15885 chore: add update_db_with_and_check
  crates/stages/stages/src/stages/mod.rs
Labels: A-db, C-test

#15888 chore: simplify op chainspec parser
  crates/optimism/chainspec/src/superchain/chain_spec_macro.rs
  crates/optimism/cli/build.rs
  crates/optimism/cli/src/chainspec.rs
Labels: A-cli, A-op-reth
