Repository paradigmxyz/reth, pull requests merged in 2025-08, with the labels that each got.

#17698 test(op-chainspec): add isthmus checks
  crates/optimism/chainspec/src/lib.rs
  crates/optimism/chainspec/src/superchain/chain_metadata.rs
Labels: C-test, A-op-reth

#17664 refactor: move BasicEngineValidator creation into EngineApiValidatorBuilder trait
  Cargo.lock
  crates/engine/primitives/src/lib.rs
  crates/engine/tree/src/tree/tests.rs
  crates/engine/util/Cargo.toml
  crates/engine/util/src/lib.rs
  crates/engine/util/src/reorg.rs
  crates/ethereum/node/src/engine.rs
  crates/ethereum/node/src/node.rs
  crates/node/builder/src/launch/engine.rs
  crates/node/builder/src/rpc.rs
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/engine.rs
  crates/optimism/node/src/node.rs
  crates/optimism/node/src/rpc.rs
  crates/optimism/node/tests/it/priority.rs
  crates/optimism/rpc/src/engine.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/storage/provider/src/traits/full.rs
  crates/storage/storage-api/src/noop.rs
  examples/custom-engine-types/src/main.rs
  examples/custom-node/Cargo.toml
  examples/custom-node/src/engine.rs
  examples/custom-node/src/engine_api.rs
  examples/engine-api-access/src/main.rs
Labels: C-enhancement, M-changelog, A-sdk

#17706 fix: feature-gate std-only methods in sparse trie
  crates/trie/sparse/src/state.rs
Labels: C-debt, A-trie

#17709 fix: forward unknown hashes pre bedrock
  crates/optimism/rpc/src/historical.rs
Labels: A-rpc, A-op-reth

#17726 chore: fix clippy docs
  crates/engine/tree/src/tree/mod.rs
  crates/net/downloaders/src/bodies/bodies.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/node/core/src/args/pruning.rs
  crates/prune/types/src/target.rs
  crates/rpc/rpc-e2e-tests/src/rpc_compat.rs
  crates/storage/db/src/lib.rs
  crates/trie/db/src/lib.rs
  docs/vocs/docs/pages/cli/reth/node.mdx
Labels: C-debt

#17727 deps: bump libmdbx to 0.13.7
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/VERSION.json
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/man1/mdbx_chk.1
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.c++
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h++
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_chk.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_copy.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_drop.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_dump.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_load.c
  crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx_stat.c
Labels: A-db, dependencies

#17745 feat(grafana): add state root duration histogram graph
  etc/grafana/dashboards/overview.json
Labels: C-perf, A-observability, A-trie

#17781 docs: remove deprecated difficulty check comment
  crates/ethereum/consensus/src/lib.rs
Labels: C-docs

#17766 fix(network): push header before next header check in `get_headers_response`
  crates/net/network/src/eth_requests.rs
Labels: A-networking

#17776 chore: replace ~/.cargo with $CARGO_HOME
  Makefile
Labels: C-docs

#17796 feat: add op db access example
  Cargo.lock
  Cargo.toml
  examples/op-db-access/Cargo.toml
  examples/op-db-access/src/main.rs
Labels: A-op-reth

#17823 fix: storage lock race condition
  crates/storage/db/src/lockfile.rs
Labels: C-debt

#17840 chore(deps): bump revm 28.0.1, inspectors, alloy-evm
  Cargo.lock
  Cargo.toml
Labels: A-execution, A-dependencies

#17797 feat(examples): Add custom header extensions to payload attributes in `custom_node` example
  crates/optimism/evm/src/build.rs
  examples/custom-node/src/engine.rs
  examples/custom-node/src/engine_api.rs
  examples/custom-node/src/evm/assembler.rs
  examples/custom-node/src/evm/config.rs
  examples/custom-node/src/evm/executor.rs
Labels: C-enhancement

#17842 fix(db): make db get --raw work with DupSort tables
  crates/cli/commands/src/db/get.rs
Labels: C-bug, A-db, A-cli

#17711 feat: introduced configurable version globals
  crates/cli/commands/src/import.rs
  crates/cli/commands/src/import_era.rs
  crates/cli/commands/src/node.rs
  crates/cli/commands/src/stage/run.rs
  crates/ethereum/cli/src/interface.rs
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/rpc.rs
  crates/node/core/src/args/network.rs
  crates/node/core/src/version.rs
  crates/optimism/cli/src/commands/import.rs
  crates/optimism/cli/src/commands/import_receipts.rs
  crates/optimism/cli/src/lib.rs
  crates/optimism/node/src/rpc.rs
Labels: A-cli, A-sdk

#17770 test(chain-state): opt unit test
  crates/chain-state/src/test_utils.rs
Labels: C-test

#17864 fix: box some more futures
  crates/e2e-test-utils/src/testsuite/setup.rs
Labels: C-test

#17670 feat(txpool): Batch insertions into the Tx Pool
  Cargo.lock
  crates/node/builder/src/rpc.rs
  crates/node/core/src/args/txpool.rs
  crates/node/core/src/cli/config.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/rpc/rpc-eth-types/src/builder/config.rs
  crates/rpc/rpc-eth-types/src/error/mod.rs
  crates/rpc/rpc/src/eth/builder.rs
  crates/rpc/rpc/src/eth/core.rs
  crates/rpc/rpc/src/eth/helpers/transaction.rs
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/benches/insertion.rs
  crates/transaction-pool/src/batcher.rs
  crates/transaction-pool/src/lib.rs
  docs/vocs/docs/pages/cli/reth/node.mdx
Labels: C-perf, A-rpc

#16634 feat: custom instance label and configurable datasource for mempool dash
  etc/grafana/dashboards/reth-mempool.json
Labels: A-observability, M-prevent-stale

#17867 fix: replace unsafe unwrap with proper error handling
  crates/storage/db-common/src/init.rs
Labels: C-debt

#17627 fix: critical error handling in ExEx launcher
  crates/node/builder/src/launch/exex.rs
Labels: C-debt

#17881 chore: remove the deprecated ganache api
  crates/rpc/rpc-api/src/ganache.rs
  crates/rpc/rpc-api/src/lib.rs
Labels: C-debt, A-rpc

#17893 test: add tests for fetching header,body ranges
  crates/net/network/tests/it/requests.rs
Labels: C-test, A-networking

#17953 feat(rpc): Add `spawn_blocking_io_fut` that accepts a future
  crates/rpc/rpc-eth-api/src/helpers/blocking_task.rs
Labels: C-enhancement, A-rpc

#17961 chore: rm redundant runtime
  crates/cli/runner/src/lib.rs
Labels: C-debt

#17956 perf(trie): default ParallelSparseTrie to enabled (accounts only still)
  crates/engine/primitives/src/config.rs
  crates/engine/tree/src/tree/payload_processor/mod.rs
  crates/engine/tree/tests/e2e-testsuite/main.rs
  crates/node/core/src/args/engine.rs
  docs/cli/help.rs
  docs/vocs/docs/pages/cli/reth/node.mdx
Labels: C-perf, A-trie

#17955 fix: ParallelSparseTrie::update_leaf edge-case, and not correctly clearing all fields for re-use
  crates/trie/sparse-parallel/src/trie.rs
Labels: C-perf, A-trie

#17879 docs(sdk): Add guide for custom transaction envelope macro usage
  docs/vocs/docs/pages/sdk/custom-node/transactions.mdx
Labels: C-docs, C-enhancement, A-sdk

#17971 fix(optimism): add debug_traceTransaction support for pre-bedrock blocks
  crates/optimism/rpc/src/historical.rs
Labels: C-bug, A-rpc, A-op-reth

#17969 docs(net): add Rreceipts69 document
  crates/net/network/src/message.rs
Labels: C-docs

#17924 feat(rpc): Use pool-based pending block for pending state over latest
  crates/optimism/rpc/src/eth/mod.rs
  crates/rpc/rpc-eth-api/src/helpers/state.rs
  crates/rpc/rpc/src/eth/helpers/state.rs
Labels: C-enhancement, A-rpc, A-sdk

#17980 chore(cli): add log about state root computation for init-state
  crates/storage/db-common/src/init.rs
Labels: A-db, A-observability

#17643 chore(trie): fully reveal sparse tries prior to leaf updates/removals
  Cargo.lock
  Cargo.toml
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/tree/payload_processor/multiproof.rs
  crates/engine/tree/src/tree/payload_processor/sparse_trie.rs
  crates/trie/common/src/added_removed_keys.rs
  crates/trie/common/src/hashed_state.rs
  crates/trie/common/src/lib.rs
  crates/trie/db/tests/walker.rs
  crates/trie/parallel/src/proof.rs
  crates/trie/parallel/src/proof_task.rs
  crates/trie/parallel/src/root.rs
  crates/trie/sparse-parallel/src/trie.rs
  crates/trie/sparse/benches/root.rs
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
  crates/trie/trie/src/node_iter.rs
  crates/trie/trie/src/proof/mod.rs
  crates/trie/trie/src/trie.rs
  crates/trie/trie/src/trie_cursor/subnode.rs
  crates/trie/trie/src/walker.rs
Labels: C-perf, A-trie

#18003 fix: rlp encoding for sealedblock
  crates/primitives-traits/src/block/sealed.rs
Labels: C-bug

#18004 test(engine): add e2e tests for forkchoice update with finalized blocks
  crates/e2e-test-utils/src/testsuite/actions/custom_fcu.rs
  crates/e2e-test-utils/src/testsuite/actions/mod.rs
  crates/engine/tree/tests/e2e-testsuite/fcu_finalized_blocks.rs
  crates/engine/tree/tests/e2e-testsuite/main.rs
Labels: C-test, A-engine

#18007 feat: add helper for setting tx propagation mode
  crates/net/network/src/config.rs
Labels: C-enhancement, A-cli

#17996 feat(reth-bench): add --advance option for relative block ranges
  bin/reth-bench/README.md
  bin/reth-bench/src/bench/context.rs
  crates/node/core/src/args/benchmark_args.rs
Labels: C-enhancement, A-cli

#18009 feat(optimism): Add `FlashBlockService` that builds blocks from `FlashBlock`s
  Cargo.lock
  crates/chain-state/src/in_memory.rs
  crates/optimism/flashblocks/Cargo.toml
  crates/optimism/flashblocks/src/lib.rs
  crates/optimism/flashblocks/src/service.rs
Labels: A-rpc, A-op-reth, A-sdk

#18053 fix(node/builder): correct left_mut() method implementation and docs
  crates/node/builder/src/launch/common.rs
Labels: A-sdk

#18067 feat(optimism): Add `launch_wss_flashblocks_service` function spawning a task sending last pending block
  crates/optimism/flashblocks/src/app.rs
  crates/optimism/flashblocks/src/lib.rs
Labels: C-enhancement, A-op-reth

#17928 feat: support importing multi files
  crates/cli/commands/src/import.rs
  crates/ethereum/cli/src/interface.rs
  docs/vocs/docs/pages/cli/reth.mdx
  docs/vocs/docs/pages/cli/reth/import.mdx
Labels: C-enhancement, A-cli

#18081 fix: clarify locking behavior comment in InMemoryState
  crates/chain-state/src/in_memory.rs
Labels: C-docs

#18086 feat: optionally disable balance check for `EthTransactionValidator`
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool, A-sdk

#18117 chore: add prewarm traces
  crates/engine/tree/src/tree/payload_processor/prewarm.rs
Labels: A-observability

#18116 perf(engine): only clone headers instead of full blocks for tree tasks
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/payload_validator.rs
  crates/engine/tree/src/tree/state.rs
  crates/engine/tree/src/tree/tests.rs
Labels: C-perf, A-engine

#18123 fix(optimism): Verify that flashblocks are not old according to canon state
  crates/chain-state/src/notifications.rs
  crates/optimism/flashblocks/src/app.rs
  crates/optimism/flashblocks/src/service.rs
  crates/rpc/rpc-eth-types/src/pending_block.rs
Labels: C-bug, C-enhancement, A-op-reth

#17819 fix: import should count on the delta
  crates/cli/commands/src/import_core.rs
  crates/e2e-test-utils/src/setup_import.rs
Labels: C-debt

#18137 fix(txpool): ensure fee changes are updated
  crates/transaction-pool/src/pool/txpool.rs
Labels: C-bug, A-tx-pool

#18148 perf(engine): pre-allocate Vec capacity in payload processor
  crates/engine/tree/benches/state_root_task.rs
  crates/engine/tree/src/tree/payload_processor/mod.rs
Labels: C-perf, A-engine

#18147 perf(engine): pre-allocate channel handles in prewarm task
  crates/engine/tree/src/tree/payload_processor/prewarm.rs
Labels: C-perf, A-engine

#18104 chore(reth-optimism-storage): small refactor code
  crates/optimism/storage/src/chain.rs
Labels: C-debt, A-op-reth

#18161 perf(optimism): Pass noop provider to skip state root calculations for flashblocks
  crates/optimism/flashblocks/src/service.rs
Labels: C-enhancement, C-perf, A-rpc, A-op-reth

#18156 chore: Add 0x prefix and use macro
  crates/net/eth-wire-types/src/header.rs
  crates/net/eth-wire-types/src/status.rs
  crates/optimism/cli/src/receipt_file_codec.rs
  crates/primitives-traits/src/transaction/signature.rs
  crates/storage/db-api/src/models/accounts.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/trie/db/tests/trie.rs
  crates/trie/sparse-parallel/src/trie.rs
Labels: C-debt

#18031 fix: correct logical error in delete_outside_range error message
  crates/era-downloader/src/client.rs
Labels: A-observability

#18171 chore: simplify dev signed tx conversions
  crates/rpc/rpc-convert/src/rpc.rs
Labels: C-debt, A-rpc
