Repository paradigmxyz/reth, pull requests merged in 2025-09, with the labels that each got.

#18201 perf: prepare flashblock txs
  crates/optimism/flashblocks/src/service.rs
Labels: C-enhancement, C-perf, A-op-reth

#18215 revert: "perf(txpool): eliminate allocations in basefee enforcement"
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/txpool.rs
Labels: A-tx-pool

#18216 fix: incorrect blob fee comparison
  crates/transaction-pool/src/pool/pending.rs
Labels: A-tx-pool

#18232 chore: improve flashblock logs
  crates/optimism/flashblocks/src/service.rs
Labels: A-observability

#18236 fix(download): use updated merkle base URL
  crates/cli/commands/src/download.rs
Labels: C-bug, A-cli

#18239 chore(trie): use instrument instead of manual span
  crates/trie/trie/src/trie.rs
Labels: A-observability

#18240 chore(engine): add better logs and spans for execution
  crates/engine/tree/src/tree/metrics.rs
  crates/engine/tree/src/tree/payload_validator.rs
Labels: C-enhancement, A-observability

#18245 docs: update urls in docs
  crates/cli/commands/src/download.rs
  docs/vocs/docs/pages/cli/reth/download.mdx
Labels: C-docs

#18212 feat(optimism): Respond to ping messages with pong in `WsFlashBlockStream`
  crates/optimism/flashblocks/src/ws/stream.rs
Labels: C-enhancement, A-op-reth

#18248 chore: unify engine downloader targets
  crates/engine/tree/src/download.rs
Labels: A-observability

#18238 fix(optimism): Compare parent hash and latest hash to invalidate cached flashblock
  crates/optimism/flashblocks/src/service.rs
Labels: C-enhancement, A-rpc, A-op-reth

#18277 chore: extract `validate_against_parent_gas_limit` into separate fn
  crates/consensus/common/src/validation.rs
  crates/ethereum/consensus/src/lib.rs
Labels: C-enhancement

#18271 perf: build local pending block without updates
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
Labels: C-perf, A-rpc

#18284 perf(db): do not heap-allocate the stage key per query
  crates/stages/types/src/id.rs
  crates/storage/provider/src/providers/database/provider.rs
Labels: C-perf

#18307 perf: specialize len 1
  crates/transaction-pool/src/lib.rs
Labels: C-perf, A-tx-pool

#18260 feat: introduce maybe_pending method to StateProviderFactory
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/rpc-provider/src/lib.rs
  crates/storage/storage-api/src/noop.rs
  crates/storage/storage-api/src/state.rs
Labels: C-enhancement

#18237 feat(download): support zst archives in reth download
  Cargo.lock
  crates/cli/commands/Cargo.toml
  crates/cli/commands/src/download.rs
Labels: C-enhancement, A-cli

#18317 chore(trie): dont warn on blinded node reveals
  crates/trie/sparse-parallel/src/trie.rs
  crates/trie/sparse/src/trie.rs
Labels: A-trie

#18328 chore(trie): use read-only db handle during repair-trie dry-runs
  crates/cli/commands/src/db/mod.rs
  crates/cli/commands/src/db/repair_trie.rs
Labels: A-cli, A-trie

#18324 feat: cache latest built payload
  crates/payload/builder/Cargo.toml
  crates/payload/builder/src/service.rs
Labels: C-enhancement, A-sdk

#18339 perf(merkle-stage): only fetch checkpoint in the branch that needs it
  crates/stages/stages/src/stages/merkle.rs
Labels: A-staged-sync, C-perf

#18300 fix: properly compute genesis hash
  crates/chainspec/src/spec.rs
Labels: C-bug

#18276 feat(op-reth/flashblocks): subscribe to the flashblock sequences produced
  crates/optimism/flashblocks/src/lib.rs
  crates/optimism/flashblocks/src/sequence.rs
  crates/optimism/flashblocks/src/service.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/historical.rs
Labels: A-op-reth

#18345 fix(ci): pin teku image to fix kurtosis-op build
  .github/assets/kurtosis_op_network_params.yaml
Labels: C-bug, C-test, A-ci

#18363 fix(docs): include .vocs to retain search-index
  docs/vocs/docs/public/_config.yml
Labels: C-docs

#18370 fix: check payload id
  crates/payload/builder/src/service.rs
Labels: C-bug

#18423 feat: add helper to PendingBlockAndReceipts
  crates/rpc/rpc-eth-types/src/pending_block.rs
Labels: C-enhancement, A-sdk

#18422 chore: add state and response to miner error
  crates/engine/local/src/miner.rs
Labels: A-observability

#18426 chore: clean up TS warnings in search index & file finder
  docs/vocs/scripts/fix-search-index.ts
Labels: C-docs

#18430 chore: move and rename PendingBlockAndReceipts to BlockAndReceipts
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/eth/pending_block.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/rpc/rpc-eth-types/src/block.rs
  crates/rpc/rpc-eth-types/src/lib.rs
  crates/rpc/rpc-eth-types/src/pending_block.rs
Labels: C-debt

#18434 docs: multiple small textual defects
  CONTRIBUTING.md
  examples/bsc-p2p/src/block_import/parlia.rs
  examples/bsc-p2p/src/upgrade_status.rs
  examples/custom-node/src/evm/config.rs
  examples/custom-node/src/lib.rs
  examples/custom-payload-builder/src/main.rs
  testing/ef-tests/src/cases/blockchain_test.rs
  testing/testing-utils/src/generators.rs
Labels: spelling

#18439 perf: Enforce EIP-7825 transaction gas limit for Osaka
  crates/consensus/common/src/validation.rs
  crates/consensus/consensus/src/lib.rs
Labels: A-consensus, E-osaka

#18424 perf(db): open MDBX DBIs only once at startup
  Cargo.lock
  crates/storage/db/Cargo.toml
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/mdbx.rs
Labels: C-perf, A-db

#18374 feat(op-reth): specialize get_transaction_receipt to check pending flashblocks
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/eth/transaction.rs
Labels: C-enhancement, A-op-reth, A-sdk

#18478 docs(engine): fix LiveSync target doc and clarify disable-parallel-sparse-trie semantics
  crates/engine/primitives/src/config.rs
  crates/engine/primitives/src/event.rs
  crates/engine/tree/src/tree/payload_processor/mod.rs
Labels: A-observability

#18502 chore(engine): avoid panic on mpsc send in sparse trie worker
  crates/engine/tree/src/tree/payload_processor/sparse_trie.rs
Labels: C-debt

#18511 fix: don't override existing tables in `create_tables_for`
  crates/storage/db/src/implementation/mdbx/mod.rs
  crates/storage/db/src/mdbx.rs
Labels: M-changelog, A-db

#18510 fix(docs): correct BlockBody root docs and RecoveredBlock “safer variant” references
  crates/primitives-traits/src/block/body.rs
  crates/primitives-traits/src/block/recovered.rs
Labels: C-docs

#18518 feat(optimism): Implement `local_pending_state` for RPC that uses `pending_flashblock`
  Cargo.lock
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/eth/pending_block.rs
  crates/optimism/rpc/src/eth/transaction.rs
Labels: C-bug, C-enhancement, A-rpc, A-op-reth

#18520 feat: relax `OpEngineValidatorBuilder` for more custom payload types
  crates/optimism/node/src/node.rs
Labels: A-op-reth, A-sdk

#18457 docs(engine): improve cache naming and documentation
  crates/engine/tree/src/tree/cached_state.rs
  crates/engine/tree/src/tree/payload_processor/mod.rs
  crates/engine/tree/src/tree/payload_processor/prewarm.rs
  crates/engine/tree/src/tree/persistence_state.rs
Labels: C-docs, C-debt, A-engine

#18523 fix: use noopprovider for pending block state root
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
Labels: C-perf, A-rpc

#18528 chore(ci): bump hive eest tests to v5.1.0
  .github/assets/hive/build_simulators.sh
Labels: C-hivetest, A-ci

#18508 refactor: EmptyBodyStorage block reader logic
  Cargo.lock
  crates/optimism/storage/Cargo.toml
  crates/optimism/storage/src/chain.rs
  crates/optimism/storage/src/lib.rs
  crates/storage/provider/src/providers/database/chain.rs
  crates/storage/storage-api/Cargo.toml
  crates/storage/storage-api/src/chain.rs
Labels: C-enhancement, A-sdk

#18443 feat(op-reth): initial setup FlashBlockConsensusClient engine sidecar
  Cargo.lock
  crates/optimism/flashblocks/Cargo.toml
  crates/optimism/flashblocks/src/consensus.rs
  crates/optimism/flashblocks/src/lib.rs
  crates/optimism/flashblocks/src/sequence.rs
  crates/optimism/flashblocks/src/service.rs
Labels: C-enhancement, A-op-reth

#18539 feat(rpc): add admin_clearTxpool api
  crates/rpc/rpc-api/src/admin.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/admin.rs
Labels: C-enhancement, A-rpc

#18489 chore(docker): add FEATURES for op dockerfile
  DockerfileOp
Labels: A-observability

#18549 chore(consensus): update EIP-7825 error message format
  crates/consensus/consensus/src/lib.rs
Labels: C-test, C-hivetest, A-ci

#18560 chore: map NaN to 0.0
  crates/node/events/src/node.rs
Labels: A-observability

#18570 fix(reth-bench): do not panic on empty results
  bin/reth-bench/src/bench/new_payload_fcu.rs
  bin/reth-bench/src/bench/new_payload_only.rs
  bin/reth-bench/src/bench/output.rs
Labels: C-bug, A-cli

#18479 chore(trie): Use Vec<Option<...>> in InMemoryTrieCursor
  crates/trie/common/src/updates.rs
  crates/trie/db/tests/trie.rs
  crates/trie/sparse/benches/root.rs
  crates/trie/trie/src/trie_cursor/in_memory.rs
  crates/trie/trie/src/trie_cursor/mock.rs
Labels: C-enhancement, C-perf, A-db, A-engine, A-trie

#18590 fix: use timestamp derived max blob count on launch
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool, E-osaka

#18558 feat(rpc): make send_raw_transaction_sync timeout configurable
  crates/node/core/src/args/rpc_server.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-types/src/builder/config.rs
  crates/rpc/rpc-server-types/src/constants.rs
  crates/rpc/rpc/src/eth/builder.rs
  crates/rpc/rpc/src/eth/core.rs
  crates/rpc/rpc/src/eth/helpers/transaction.rs
  docs/vocs/docs/pages/cli/reth/node.mdx
Labels: M-changelog, A-rpc

#18588 perf(persistence): lookup segment operation once
  crates/storage/provider/src/providers/static_file/metrics.rs
Labels: C-perf

#18564 fix(cache): Ensure execution cache remains locked until updated
  crates/engine/tree/src/tree/cached_state.rs
  crates/engine/tree/src/tree/payload_processor/mod.rs
  crates/engine/tree/src/tree/payload_processor/prewarm.rs
Labels: C-enhancement, C-perf, A-execution

#18581 test: add test case for op tx env conversion
  Cargo.lock
  crates/rpc/rpc-convert/Cargo.toml
  crates/rpc/rpc-convert/src/transaction.rs
Labels: C-test, A-op-reth

#18602 fix: avoid panic in new-payload-fcu benchmark
  bin/reth-bench/src/bench/new_payload_fcu.rs
Labels: C-debt

#18603 feat(db): add MDBX put-append for fast ordered puts
  crates/storage/db-api/src/transaction.rs
  crates/storage/db/Cargo.toml
  crates/storage/db/benches/put.rs
  crates/storage/db/src/implementation/mdbx/tx.rs
  crates/storage/db/src/metrics.rs
  crates/storage/errors/src/db.rs
Labels: C-perf, A-db

#18674 refactor: simplify `EthApiSpeс` trait
  crates/optimism/rpc/src/eth/mod.rs
  crates/rpc/rpc-eth-api/src/core.rs
  crates/rpc/rpc-eth-api/src/helpers/spec.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc/src/eth/helpers/spec.rs
Labels: C-enhancement

#18601 docs: some fixes on discv4 docs
  crates/net/discv4/README.md
  crates/net/discv4/src/lib.rs
Labels: C-docs

#18695 feat(net): added check for non zero latest_hash in BlockRangeUpdate
  crates/net/network/src/session/active.rs
Labels: A-devp2p, A-networking

#18712 fix: Bearer token parsing vulnerability
  crates/rpc/rpc-layer/src/jwt_validator.rs
Labels: C-bug

#18733 fix: increase backoff timeout
  crates/net/network/src/peers.rs
  crates/net/network/tests/it/connect.rs
Labels: C-bug, A-devp2p

#18729 fix: Apply WS CORS regardless of HTTP being enabled
  crates/rpc/rpc-builder/src/config.rs
Labels: C-bug, M-changelog

#18669 fix(rpc/engine): check osaka in getBlobsV1
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: E-osaka

#18710 fix(chain-state): remove redundant transaction clone in test utils
  crates/chain-state/src/test_utils.rs
Labels: C-debt

#18722 feat: keep track of most recently emitted range update and change int…
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/mod.rs
Labels: A-devp2p

#18681 feat(storage): write headers and transactions only to static files
  crates/cli/commands/src/init_state/mod.rs
  crates/cli/commands/src/init_state/without_evm.rs
  crates/cli/commands/src/stage/drop.rs
  crates/cli/commands/src/stage/run.rs
  crates/cli/commands/src/stage/unwind.rs
  crates/engine/tree/src/persistence.rs
  crates/era-utils/src/history.rs
  crates/exex/exex/src/manager.rs
  crates/exex/exex/src/notifications.rs
  crates/optimism/cli/src/commands/import_receipts.rs
  crates/optimism/cli/src/commands/init_state.rs
  crates/prune/prune/src/segments/mod.rs
  crates/prune/prune/src/segments/receipts.rs
  crates/prune/prune/src/segments/static_file/headers.rs
  crates/prune/prune/src/segments/static_file/transactions.rs
  crates/prune/prune/src/segments/user/account_history.rs
  crates/prune/prune/src/segments/user/receipts_by_logs.rs
  crates/prune/prune/src/segments/user/sender_recovery.rs
  crates/prune/prune/src/segments/user/storage_history.rs
  crates/prune/prune/src/segments/user/transaction_lookup.rs
  crates/stages/api/src/pipeline/mod.rs
  crates/stages/stages/benches/criterion.rs
  crates/stages/stages/benches/setup/mod.rs
  crates/stages/stages/src/stages/bodies.rs
  crates/stages/stages/src/stages/execution.rs
  crates/stages/stages/src/stages/hashing_account.rs
  crates/stages/stages/src/stages/headers.rs
  crates/stages/stages/src/stages/mod.rs
  crates/static-file/static-file/src/static_file_producer.rs
  crates/storage/db-common/src/init.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/providers/consistent_view.rs
  crates/storage/provider/src/providers/database/metrics.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/storage/provider/src/providers/static_file/writer.rs
  crates/storage/provider/src/test_utils/blocks.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/provider/src/writer/mod.rs
  crates/storage/rpc-provider/src/lib.rs
  crates/storage/storage-api/src/block_writer.rs
  crates/storage/storage-api/src/chain.rs
  crates/storage/storage-api/src/database_provider.rs
  crates/storage/storage-api/src/noop.rs
  crates/storage/storage-api/src/state_writer.rs
  crates/storage/storage-api/src/storage.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: C-enhancement, A-static-files

#18776 feat(flashblocks): additional pending flashblock data
  Cargo.lock
  crates/optimism/flashblocks/Cargo.toml
  crates/optimism/flashblocks/src/lib.rs
  crates/optimism/flashblocks/src/payload.rs
  crates/optimism/flashblocks/src/sequence.rs
  crates/optimism/flashblocks/src/service.rs
  crates/optimism/flashblocks/src/worker.rs
  crates/optimism/rpc/src/eth/mod.rs
Labels: A-op-reth

#18784 fix(op-reth): forward pre-bedrock transaction RPC calls to historical endpoint
  crates/optimism/rpc/src/historical.rs
Labels: C-bug, A-rpc, A-op-reth
