Repository paradigmxyz/reth, pull requests merged in 2025-06, with the labels that each got.

#16588 chore: rm some clones
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-types/src/simulate.rs
Labels: C-perf, A-rpc

#16556 chore: simplify `NetworkPrimitives`
  crates/net/eth-wire-types/src/primitives.rs
  crates/optimism/node/src/node.rs
  crates/primitives-traits/src/receipt.rs
  examples/custom-node/src/lib.rs
Labels: A-sdk

#16573 test(e2e): set test_state_root_fallback for deep reorg test
  crates/e2e-test-utils/src/testsuite/examples.rs
Labels: C-enhancement, C-test

#16614 feat: :bug: fix using latest header
  crates/rpc/rpc-eth-api/src/helpers/fee.rs
Labels: A-rpc

#16616 fix: wrap forkid entry for eth key
  crates/net/network/src/manager.rs
Labels: C-bug, A-devp2p

#16615 feat(`OpAddOns`): relax trait bounds for generic engine validators
  crates/optimism/node/src/node.rs
Labels: C-enhancement, A-op-reth

#16607 refactor: extract common pool setup logic for Eth and Op nodes
  crates/ethereum/node/src/node.rs
  crates/node/builder/src/components/pool.rs
  crates/optimism/node/src/node.rs
Labels: C-enhancement, A-sdk

#16627 feat: make `NewBlock` message generic
  crates/net/eth-wire-types/src/broadcast.rs
  crates/net/eth-wire-types/src/message.rs
  crates/net/eth-wire-types/src/primitives.rs
  crates/net/network/src/config.rs
  crates/net/network/src/import.rs
  crates/net/network/src/manager.rs
  crates/net/network/src/message.rs
  crates/net/network/src/network.rs
  crates/net/network/src/session/active.rs
  crates/net/network/src/state.rs
  examples/bsc-p2p/src/block_import/mod.rs
  examples/bsc-p2p/src/block_import/service.rs
  examples/custom-node/src/lib.rs
  examples/custom-node/src/network.rs
Labels: C-enhancement, A-sdk

#16638 feat(`OpEngineValidator`): `pub` `chain_spec`
  crates/optimism/node/src/engine.rs
Labels: C-enhancement, A-op-reth

#16643 fix: check additional settings when enabling discv5
  crates/node/core/src/args/network.rs
Labels: A-cli

#16568 fix(engine): recompute trie updates for forked blocks
  crates/chain-state/src/in_memory.rs
  crates/chain-state/src/memory_overlay.rs
  crates/chain-state/src/test_utils.rs
  crates/engine/tree/src/tree/error.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/state.rs
  crates/optimism/payload/src/builder.rs
  crates/ress/provider/src/lib.rs
  crates/storage/errors/src/provider.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/writer/mod.rs
  crates/trie/common/Cargo.toml
  crates/trie/common/src/input.rs
  crates/trie/trie/src/trie.rs
Labels: C-bug, A-engine, A-trie

#16644 feat: json ChainNotification subscription endpoint
  Cargo.lock
  crates/chain-state/src/notifications.rs
  crates/rpc/rpc-api/Cargo.toml
  crates/rpc/rpc-api/src/reth.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc/src/reth.rs
Labels: A-rpc

#16648 feat(txpool): EIP-7825 max gas limit check
  crates/primitives-traits/src/constants/mod.rs
  crates/primitives-traits/src/transaction/error.rs
  crates/rpc/rpc-eth-types/src/error/mod.rs
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: C-enhancement, A-tx-pool, E-osaka

#16647 feat: configure interval for trusted peer DNS resolution
  crates/net/network-types/src/peers/config.rs
  crates/net/network/src/peers.rs
  crates/net/network/src/trusted_peers_resolver.rs
Labels: A-networking

#16650 chore: bump default gas limit 60M mainnet
  crates/node/core/src/cli/config.rs
Labels: A-cli

#16649 chore: downgrade warn log
  crates/net/discv5/src/config.rs
Labels: A-observability

#16596 refactor: unify pending_block fn
  crates/rpc/rpc-eth-api/src/helpers/block.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/storage/provider/src/providers/blockchain_provider.rs
  crates/storage/provider/src/providers/consistent.rs
  crates/storage/provider/src/providers/database/mod.rs
  crates/storage/provider/src/providers/database/provider.rs
  crates/storage/provider/src/providers/static_file/manager.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/storage-api/src/block.rs
  crates/storage/storage-api/src/noop.rs
Labels: C-enhancement

#16495 feat(txns): Implement flexible TxType filtering policy in TransactionManager
  crates/net/network/src/builder.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/net/network/src/transactions/config.rs
  crates/net/network/src/transactions/mod.rs
  crates/net/network/src/transactions/policy.rs
  crates/net/network/src/transactions/validation.rs
  crates/node/builder/src/builder/mod.rs
Labels: A-networking

#16657 ci: check Cargo version against Git tag in release.yml
  .github/workflows/release.yml
Labels: A-ci

#16658 ci: remove build-release-binaries.yml workflow
  .github/workflows/build-release-binaries.yml
Labels: A-ci

#16663 chore: relax primtives types bound
  crates/optimism/node/src/node.rs
Labels: A-op-reth, A-sdk

#16668 refactor(txns): inline validation logic and remove validation.rs
  crates/net/network/src/lib.rs
  crates/net/network/src/transactions/fetcher.rs
  crates/net/network/src/transactions/mod.rs
  crates/net/network/src/transactions/validation.rs
Labels: C-debt, A-networking

#16679 ci: do not check version for release dry runs
  .github/workflows/release.yml
Labels: A-ci

#16678 feat(test): rewrite test_engine_tree_fcu_canon_chain_insertion using e2e framework
  Cargo.lock
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/tree/e2e_tests.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/tests.rs
Labels: C-test, A-engine

#16326 refactor: replace unbounded HashMap with LruMap in precompile cache
  crates/engine/tree/src/tree/precompile_cache.rs
Labels: C-perf, A-execution

#16695 fix: correctly set sync gap
  crates/stages/stages/src/stages/headers.rs
Labels: C-bug

#16692 feat(test): rewrite test_engine_tree_fcu_reorg_with_all_blocks using e2e framework
  crates/e2e-test-utils/src/testsuite/actions/fork.rs
  crates/e2e-test-utils/src/testsuite/actions/mod.rs
  crates/e2e-test-utils/src/testsuite/actions/produce_blocks.rs
  crates/e2e-test-utils/src/testsuite/actions/reorg.rs
  crates/e2e-test-utils/src/testsuite/mod.rs
  crates/e2e-test-utils/src/testsuite/setup.rs
  crates/engine/tree/src/tree/e2e_tests.rs
  crates/engine/tree/src/tree/tests.rs
Labels: C-test, A-engine

#16676 feat: add always-process-payload-attributes-on-canonical-head config
  book/cli/reth/node.md
  crates/engine/primitives/src/config.rs
  crates/engine/tree/src/tree/mod.rs
  crates/node/core/src/args/engine.rs
Labels: A-cli, A-engine

#16699 feat(test): rewrite test_engine_tree_valid_forks_with_older_canonical_head using e2e framework
  crates/e2e-test-utils/src/testsuite/actions/fork.rs
  crates/e2e-test-utils/src/testsuite/actions/mod.rs
  crates/engine/tree/src/tree/e2e_tests.rs
  crates/engine/tree/src/tree/tests.rs
Labels: C-test, A-engine

#16008 feat(stages): Add ERA pre-merge history import stage
  Cargo.lock
  book/cli/reth/node.md
  bootnodes-execution.txt
  crates/cli/commands/src/common.rs
  crates/cli/commands/src/import.rs
  crates/cli/commands/src/import_era.rs
  crates/cli/commands/src/node.rs
  crates/cli/commands/src/stage/unwind.rs
  crates/config/Cargo.toml
  crates/config/src/config.rs
  crates/era-downloader/src/client.rs
  crates/era-downloader/src/fs.rs
  crates/era-downloader/src/lib.rs
  crates/era-downloader/src/stream.rs
  crates/era-downloader/tests/it/fs.rs
  crates/era-utils/src/history.rs
  crates/era-utils/src/lib.rs
  crates/era-utils/tests/it/history.rs
  crates/era/src/era1_file.rs
  crates/era/tests/it/dd.rs
  crates/era/tests/it/roundtrip.rs
  crates/ethereum/cli/src/debug_cmd/execution.rs
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/engine.rs
  crates/node/builder/src/setup.rs
  crates/node/core/Cargo.toml
  crates/node/core/src/args/era.rs
  crates/node/core/src/args/mod.rs
  crates/node/core/src/node_config.rs
  crates/stages/api/src/stage.rs
  crates/stages/stages/Cargo.toml
  crates/stages/stages/src/lib.rs
  crates/stages/stages/src/sets.rs
  crates/stages/stages/src/stages/bodies.rs
  crates/stages/stages/src/stages/era.rs
  crates/stages/stages/src/stages/mod.rs
  crates/stages/types/src/id.rs
  crates/storage/provider/src/providers/static_file/writer.rs
  genesis.json
Labels: C-enhancement, A-sdk, epic-coredev

#16703 feat: add block range hint to BlockBodies download request
  crates/net/downloaders/src/file_client.rs
  crates/net/downloaders/src/test_utils/bodies_client.rs
  crates/net/network/src/fetch/client.rs
  crates/net/network/src/fetch/mod.rs
  crates/net/p2p/src/bodies/client.rs
  crates/net/p2p/src/either.rs
  crates/net/p2p/src/full_block.rs
  crates/net/p2p/src/test_utils/bodies.rs
  crates/net/p2p/src/test_utils/full_block.rs
Labels: C-enhancement, A-devp2p, A-networking

#16709 chore: depreacte ethexecutorbuilder
  crates/ethereum/cli/src/debug_cmd/execution.rs
  crates/ethereum/cli/src/debug_cmd/merkle.rs
  crates/ethereum/cli/src/interface.rs
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/evm/src/lib.rs
  crates/ethereum/evm/tests/execute.rs
  crates/ethereum/node/src/evm.rs
  crates/ethereum/node/src/lib.rs
  crates/exex/exex/src/backfill/job.rs
  crates/exex/exex/src/backfill/stream.rs
  crates/exex/exex/src/backfill/test_utils.rs
  crates/exex/exex/src/manager.rs
  crates/exex/exex/src/notifications.rs
  crates/stages/stages/src/lib.rs
  crates/stages/stages/src/stages/mod.rs
  testing/ef-tests/src/cases/blockchain_test.rs
Labels: A-sdk

#16710 chore: re-export all types in node mod
  crates/ethereum/node/src/lib.rs
  crates/optimism/node/src/lib.rs
Labels: A-sdk

#16711 chore: re-export cli-util crate
  Cargo.lock
  crates/ethereum/reth/Cargo.toml
  crates/ethereum/reth/src/lib.rs
  crates/optimism/reth/Cargo.toml
  crates/optimism/reth/src/lib.rs
Labels: A-sdk

#16715 feat: added Body::contains_transaction(&TxHash)
  crates/primitives-traits/src/block/body.rs
Labels: A-sdk

#16716 perf: remove redundant clones
  crates/rpc/rpc-eth-types/src/fee_history.rs
Labels: C-perf, A-rpc

#16694 feat(rpc): Implement `TransactionCompat` for generic RPC response builder
  Cargo.lock
  crates/chain-state/Cargo.toml
  crates/net/network/Cargo.toml
  crates/optimism/rpc/src/error.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/revm/Cargo.toml
  crates/rpc/rpc-eth-api/src/lib.rs
  crates/rpc/rpc-eth-types/src/error/mod.rs
  crates/rpc/rpc-types-compat/Cargo.toml
  crates/rpc/rpc-types-compat/src/lib.rs
  crates/rpc/rpc-types-compat/src/transaction.rs
  crates/rpc/rpc/src/eth/builder.rs
  crates/rpc/rpc/src/eth/core.rs
  crates/rpc/rpc/src/eth/helpers/types.rs
  crates/rpc/rpc/src/eth/mod.rs
  crates/storage/storage-api/Cargo.toml
  crates/transaction-pool/Cargo.toml
Labels: C-enhancement, A-sdk

#16737 chore(ci): update hive expected failures
  .github/assets/hive/expected_failures.yaml
Labels: C-hivetest, A-ci

#16733 chore: keep .git folder in docker
  Dockerfile
Labels: C-bug, C-enhancement, A-ci

#16713 chore: make ethpool alias generic over tx
  crates/transaction-pool/src/lib.rs
Labels: A-sdk

#16714 chore: relax eth network builder
  crates/ethereum/node/src/node.rs
Labels: A-sdk

#16463 feat: Add info logs for beginning of newPayload requests
  Cargo.lock
  crates/engine/primitives/Cargo.toml
  crates/engine/primitives/src/event.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/tree/src/tree/tests.rs
  crates/node/events/src/node.rs
  crates/ress/provider/src/pending_state.rs
Labels: C-enhancement, A-observability, A-engine

#16741 feat: reintroduce generic executors
  crates/ethereum/evm/tests/execute.rs
  crates/evm/evm/src/lib.rs
  crates/optimism/evm/src/execute.rs
Labels: C-enhancement, A-sdk

#16742 fix: small networking fixes
  crates/net/network-types/src/peers/mod.rs
  crates/net/network/src/peers.rs
  crates/net/network/src/session/active.rs
  crates/node/builder/src/launch/engine.rs
Labels: C-bug, A-networking

#16754 ci(sync): Change schedule to run once every 6 hours
  .github/workflows/sync.yml
Labels: A-devp2p, C-test, A-ci

#16763 feat: add shared local block range info between SessionManager and ActiveSession
  crates/net/network/src/session/active.rs
  crates/net/network/src/session/mod.rs
Labels: A-networking

#16759 test: improve ETH69 protocol test coverage
  crates/net/network/tests/it/session.rs
Labels: C-test, A-networking

#16767 fix: set parent beacon block to zero hash if parent's beacon block is Some
  crates/rpc/rpc/src/eth/helpers/pending_block.rs
Labels: C-bug, A-rpc

#16769 test(trie): fix stored nibbles tests
  crates/trie/common/src/nibbles.rs
Labels: C-test, A-trie

#16758 feat: make EthEvmConfig generic over chainSpec
  crates/ethereum/evm/src/config.rs
  crates/ethereum/evm/src/lib.rs
  examples/custom-evm/src/main.rs
  examples/precompile-cache/src/main.rs
Labels: A-sdk

#16782 chore: fix hive unexpected test filter
  .github/assets/hive/expected_failures.yaml
Labels: C-hivetest, A-ci

#16780 feat: introduce RPC error for pruned history
  crates/rpc/rpc-eth-types/src/error/mod.rs
Labels: A-rpc

#16778 feat: add to_message convenience method to BlockRangeInfo
  crates/net/network/src/session/types.rs
Labels: A-networking

#16812 feat: make `EthereumEngineValidator` generic over `ChainSpec`
  crates/ethereum/node/src/engine.rs
Labels: A-sdk

#16777 docs: document transaction flow into the pool
  crates/net/network/src/transactions/mod.rs
  crates/transaction-pool/src/lib.rs
Labels: C-docs

#16794 feat(gas_oracle): implement median-based priority fee suggestion for Optimism
  crates/optimism/rpc/src/eth/mod.rs
  crates/rpc/rpc-eth-types/src/gas_oracle.rs
Labels: A-op-reth

#16817 chore: removed legacy.rs
  crates/storage/storage-api/src/legacy.rs
  crates/storage/storage-api/src/lib.rs
Labels: C-debt

#16815 feat(op): export OpEthApiBuilder from reth-optimism-rpc
  crates/optimism/rpc/src/lib.rs
Labels: A-rpc, A-op-reth

#16820 feat(stateless): simplify `Database` implementation for `WitnessDatabase`
  crates/stateless/src/witness_db.rs
Labels: C-debt

#16814 feat: re-export MerklePatriciaTrie from reth-ethereum and reth-op
  Cargo.lock
  crates/ethereum/reth/Cargo.toml
  crates/ethereum/reth/src/lib.rs
  crates/optimism/reth/Cargo.toml
  crates/optimism/reth/src/lib.rs
Labels: A-dependencies, A-sdk

#16801 refactor(era): Remove `start_from` from `EraClient` and use it instead of last file index
  crates/era-downloader/src/client.rs
  crates/era-downloader/src/fs.rs
  crates/era-downloader/src/lib.rs
  crates/era-downloader/src/stream.rs
  crates/stages/stages/src/stages/era.rs
Labels: A-staged-sync

#16816 feat: relax EthereumAddons trait bounds to support generic validators
  crates/ethereum/node/Cargo.toml
  crates/ethereum/node/src/node.rs
  crates/exex/test-utils/src/lib.rs
Labels: A-sdk

#16824 chore(op/cli): Rm unused cli arg `rollup.enable-genesis-walkback`
  book/run/optimism.md
  crates/optimism/node/src/args.rs
Labels: C-bug, C-debt, A-cli, A-op-reth

#16823 fix: make `EthPubSub` pub to allow composition and fallback overrides
  crates/rpc/rpc/src/eth/pubsub.rs
Labels: A-rpc

#16827 chore: update op-alloy deps to 0.18.2
  Cargo.lock
  Cargo.toml
  crates/optimism/primitives/src/transaction/mod.rs
  crates/primitives-traits/src/extended.rs
  examples/custom-node/src/primitives/tx.rs
Labels: A-dependencies, A-op-reth

#16840 refactor: replaced update_status with update_block_range
  crates/node/builder/src/launch/engine.rs
Labels: A-devp2p

#16842 chore(ci): pin kurtosis-op optimism package
  .github/workflows/kurtosis-op.yml
Labels: C-debt, C-test, A-op-reth, A-ci

#16846 perf: avoid duplicate peer lookup
  crates/net/network/src/transactions/mod.rs
Labels: A-networking

#16633 feat: use configurable instance label for overview dashboard
  etc/grafana/dashboards/overview.json
Labels: A-observability

#16864 feat: add CLAUDE.md
  CLAUDE.md
Labels: A-meta

#16593 fix(pipeline): prevent unwind beyond history limits
  crates/prune/types/src/lib.rs
  crates/prune/types/src/target.rs
  crates/stages/api/src/error.rs
  crates/stages/api/src/pipeline/mod.rs
Labels: A-staged-sync, A-db

#16178 feat: introduced loop with range of chunks in the incremental root stage
  crates/cli/commands/src/stage/dump/merkle.rs
  crates/cli/commands/src/stage/run.rs
  crates/config/src/config.rs
  crates/stages/stages/benches/criterion.rs
  crates/stages/stages/src/sets.rs
  crates/stages/stages/src/stages/execution.rs
  crates/stages/stages/src/stages/merkle.rs
  crates/stages/stages/src/stages/mod.rs
Labels: M-changelog, A-staged-sync

#16879 fix(op-reth, rpc): eth_getBlockReceipts err for genesis block in op-reth
  crates/optimism/rpc/src/eth/block.rs
Labels: C-bug, A-rpc, A-op-reth

#16887 ci: pin nextest version
  .github/workflows/integration.yml
  .github/workflows/unit.yml
Labels: A-ci

#16683 feat: added experimental eth_sendrawtransaction endpoint (wip)
  Cargo.lock
  crates/rpc/rpc-eth-api/Cargo.toml
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-api/src/types.rs
  crates/rpc/rpc-eth-types/src/error/mod.rs
Labels: A-rpc

#16886 fix: move `bytecode_by_hash` from `StateProvider` to a dedicated `BytecodeReader`
  crates/alloy-provider/src/lib.rs
  crates/chain-state/src/in_memory.rs
  crates/chain-state/src/memory_overlay.rs
  crates/engine/tree/src/tree/cached_state.rs
  crates/engine/tree/src/tree/instrumented_state.rs
  crates/revm/src/database.rs
  crates/revm/src/test_utils.rs
  crates/rpc/rpc-eth-types/src/cache/db.rs
  crates/rpc/rpc/src/debug.rs
  crates/storage/provider/src/providers/state/historical.rs
  crates/storage/provider/src/providers/state/latest.rs
  crates/storage/provider/src/providers/state/macros.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/storage/storage-api/src/noop.rs
  crates/storage/storage-api/src/state.rs
Labels: A-db, A-sdk

#16865 feat: add from_root for ParallelSparseTrie
  crates/trie/sparse/src/parallel_trie.rs
Labels: C-enhancement, A-trie

#16903 perf(trie): sparse subtrie type
  crates/trie/sparse/src/parallel_trie.rs
Labels: C-perf, A-trie

#16870 docs: improve reth-primitives-traits documentation
  crates/primitives-traits/src/block/mod.rs
  crates/primitives-traits/src/block/recovered.rs
  crates/primitives-traits/src/header/error.rs
  crates/primitives-traits/src/header/mod.rs
  crates/primitives-traits/src/lib.rs
  crates/primitives-traits/src/serde_bincode_compat.rs
  crates/primitives-traits/src/transaction/mod.rs
  crates/primitives-traits/src/transaction/signed.rs
  crates/primitives/src/lib.rs
Labels: C-docs

#16905 feat(trie): Embed a SparseSubtrie into the ParallelSparseTrie as its upper trie
  crates/trie/sparse/src/parallel_trie.rs
Labels: C-perf, A-trie

#16910 fix: prevent invalid range in fee_history when newest_block is pending
  crates/rpc/rpc-eth-api/src/helpers/fee.rs
  crates/rpc/rpc-eth-types/src/fee_history.rs
Labels: C-bug, A-rpc

#16889 feat: load KZG settings on EthTransactionValidator startup
  crates/transaction-pool/src/validate/eth.rs
Labels: C-perf, A-tx-pool

#16915 fix: allow eth69 block propagation
  crates/net/eth-wire-types/src/message.rs
Labels: A-networking

#16919 feat(alloy-provider): stub out required trait implementations
  crates/alloy-provider/src/lib.rs
Labels: A-db

#16920 docs: improve transaction-related trait documentation
  crates/net/eth-wire-types/src/primitives.rs
  crates/primitives-traits/src/node.rs
  crates/transaction-pool/src/traits.rs
Labels: C-docs

#16924 chore(engine): add log showing which root algorithm is being used
  crates/engine/tree/src/tree/mod.rs
Labels: A-observability, A-trie

#16907 chore: remove unused approx_capacity_get_pooled_transactions_req
  crates/net/network/src/transactions/constants.rs
  crates/net/network/src/transactions/fetcher.rs
Labels: A-networking

#16908 perf(trie): `ParallelSparseTrie::get_changed_subtries` method
  crates/trie/common/src/prefix_set.rs
  crates/trie/sparse/src/parallel_trie.rs
Labels: C-enhancement, C-perf, A-trie

#16933 chore: add type alias for PayloadAttributes
  crates/node/types/src/lib.rs
Labels: A-sdk

#16931 chore: Expose payload_id
  crates/ethereum/engine-primitives/src/lib.rs
  crates/ethereum/engine-primitives/src/payload.rs
  crates/optimism/payload/src/lib.rs
  crates/optimism/payload/src/payload.rs
Labels: A-block-building

#16894 perf(trie): `ParallelSparseTrie::reveal_node`
  crates/trie/sparse/src/parallel_trie.rs
Labels: C-perf, A-trie

#16928 chore: add node synced helper
  crates/rpc/rpc/src/eth/helpers/mod.rs
  crates/rpc/rpc/src/eth/helpers/sync_listener.rs
  crates/rpc/rpc/src/eth/mod.rs
  crates/rpc/rpc/src/lib.rs
Labels: C-enhancement, A-rpc

#16948 perf(trie): `ParallelSparseTrie::update_subtrie_hashes` boilerplate
  Cargo.lock
  crates/trie/sparse-parallel/Cargo.toml
  crates/trie/sparse-parallel/src/trie.rs
  crates/trie/sparse/src/trie.rs
Labels: C-perf, A-trie

#16949 feat(test): rewrite test_engine_tree_live_sync_fcu_extends_canon_chain using e2e framework
  crates/engine/tree/src/tree/e2e_tests.rs
  crates/engine/tree/src/tree/tests.rs
Labels: C-enhancement, C-test

#16957 chore: update codeowners
  .github/CODEOWNERS
Labels: A-meta

#16961 chore: use revm tx trait directly
  crates/rpc/rpc-eth-types/src/revm_utils.rs
Labels: A-rpc

#16960 chore(trie): Replace magic numbers in ParallelSparseTrie code
  crates/trie/sparse-parallel/src/trie.rs
Labels: A-trie

#16976 fix: add missing historical RPC endpoints for Optimism pre-bedrock
  crates/optimism/rpc/src/historical.rs
Labels: A-op-reth

#16974 feat(era): Attach file name and path to checksum error
  crates/era-downloader/src/client.rs
  crates/era-downloader/tests/it/checksums.rs
Labels: A-observability

#16958 perf(rpc): optimize EVM reuse in `eth_estimateGas`
  crates/rpc/rpc-eth-api/src/helpers/estimate.rs
Labels: C-perf, A-rpc

#16967 feat(transaction-pool): enforce EIP-2681
  crates/rpc/rpc-eth-types/src/error/mod.rs
  crates/transaction-pool/src/error.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool

#16570 chore(sdk): Add default for noop component
  crates/payload/builder/src/noop.rs
Labels: C-debt, C-test, A-sdk

#16981 refactor: remove CallFees re-export and relocate tests
  crates/rpc/rpc-eth-types/src/revm_utils.rs
  crates/rpc/rpc-types-compat/src/fees.rs
Labels: C-debt, A-rpc

#16983 feat: add From impl for RecoveredBlock from blocks with recovered transactions
  crates/primitives-traits/src/block/recovered.rs
Labels: A-sdk

#16979 chore: relax localpending block bounds
  crates/optimism/rpc/src/eth/pending_block.rs
  crates/rpc/rpc/src/eth/helpers/pending_block.rs
Labels: A-sdk

#16988 feat: add rpc header compat
  crates/primitives-traits/src/header/sealed.rs
Labels: A-sdk

#16990 chore: use from conversion for txkind
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-types/src/simulate.rs
Labels: C-debt, A-rpc

#16989 docs: fix error in HARDFORK-CHECKLIST.md
  HARDFORK-CHECKLIST.md
Labels: C-docs

#16972 feat(test): rewrite test_engine_tree_live_sync_transition_eventually_canonical using e2e framework
  crates/e2e-test-utils/src/testsuite/actions/mod.rs
  crates/e2e-test-utils/src/testsuite/actions/node_ops.rs
  crates/engine/tree/src/tree/e2e_tests.rs
  crates/engine/tree/src/tree/tests.rs
Labels: C-enhancement, C-test, A-engine

#16986 docs: improve payload primitives documentation
  crates/payload/primitives/src/error.rs
  crates/payload/primitives/src/lib.rs
  crates/payload/primitives/src/payload.rs
  crates/payload/primitives/src/traits.rs
Labels: C-docs

#16937 docs: improve ConfigureEvm trait documentation
  crates/evm/evm/src/execute.rs
  crates/evm/evm/src/lib.rs
Labels: C-docs

#17002 chore: simplify `RpcConverter`
  crates/optimism/rpc/src/eth/mod.rs
  crates/rpc/rpc-types-compat/src/transaction.rs
  crates/rpc/rpc/src/eth/helpers/types.rs
Labels: A-sdk

#17006 test: special case for nibbles implementations of `Compact`
  crates/cli/commands/src/test_vectors/compact.rs
Labels: C-test, A-trie

#17005 docs: rephrase RpcNodeCore docs
  crates/rpc/rpc-eth-api/src/node.rs
Labels: C-docs

#17009 refactor(rpc): Rename `TransactionCompat` => `RpcConvert`
  crates/optimism/rpc/src/eth/call.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/optimism/rpc/src/eth/pending_block.rs
  crates/rpc/rpc-eth-api/src/helpers/block.rs
  crates/rpc/rpc-eth-api/src/helpers/call.rs
  crates/rpc/rpc-eth-api/src/helpers/pending_block.rs
  crates/rpc/rpc-eth-api/src/helpers/transaction.rs
  crates/rpc/rpc-eth-api/src/types.rs
  crates/rpc/rpc-eth-types/src/simulate.rs
  crates/rpc/rpc-eth-types/src/transaction.rs
  crates/rpc/rpc-types-compat/src/lib.rs
  crates/rpc/rpc-types-compat/src/transaction.rs
  crates/rpc/rpc/src/eth/core.rs
  crates/rpc/rpc/src/eth/filter.rs
  crates/rpc/rpc/src/eth/helpers/block.rs
  crates/rpc/rpc/src/eth/helpers/call.rs
  crates/rpc/rpc/src/eth/helpers/pending_block.rs
  crates/rpc/rpc/src/eth/pubsub.rs
  crates/rpc/rpc/src/txpool.rs
Labels: C-debt, A-rpc, A-sdk

#17011 perf(trie): Place the root nodes of the lower SparseSubtries in those tries
  crates/trie/sparse-parallel/src/trie.rs
Labels: C-perf, A-trie

#17021 feat: allow access to db via NodeBuilder
  crates/ethereum/node/tests/it/builder.rs
  crates/node/builder/src/builder/mod.rs
Labels: A-sdk

#16943 perf(trie): `SparseSubtrie::update_hashes`
  Cargo.lock
  crates/trie/sparse-parallel/Cargo.toml
  crates/trie/sparse-parallel/src/trie.rs
  crates/trie/sparse/src/trie.rs
Labels: C-perf, A-trie

#17026 chore: remove unused for<'a>
  crates/rpc/rpc-builder/src/lib.rs
Labels: A-rpc

#17027 docs: update outdated validtor docs
  crates/transaction-pool/src/validate/eth.rs
Labels: C-docs, A-tx-pool

#17022 feat(tx-pool): add getter methods for `EthTransactionValidator` internal fields
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool

#17032 chore(trie): rephrase the log about storage proof task result sending
  crates/trie/parallel/src/proof_task.rs
Labels: C-enhancement, A-observability, A-trie

#17037 docs: fix typo in transaction expiration comment
  crates/storage/provider/src/providers/static_file/manager.rs
Labels: C-docs, A-db

#15909 feat: introduce reth era export
  Cargo.lock
  crates/era-utils/Cargo.toml
  crates/era-utils/src/export.rs
  crates/era-utils/src/lib.rs
  crates/era-utils/tests/it/genesis.rs
  crates/era-utils/tests/it/history.rs
  crates/era-utils/tests/it/main.rs
  crates/era/Cargo.toml
  crates/era/src/execution_types.rs
Labels: M-prevent-stale

#17030 perf(trie): implement `ParallelSparseTrie::root` method
  crates/trie/sparse-parallel/Cargo.toml
  crates/trie/sparse-parallel/src/trie.rs
  crates/trie/sparse/src/trie.rs
Labels: C-enhancement, C-perf, A-trie

#17067 chore: bump alloy patches
  Cargo.lock
  Cargo.toml
Labels: dependencies

#17066 fix(cli): propagate max-tx-input-bytes setting
  crates/ethereum/node/src/node.rs
  crates/optimism/node/src/node.rs
Labels: C-bug, A-tx-pool, A-cli

#17062 docs: error fixes for clarity
  crates/engine/invalid-block-hooks/src/witness.rs
Labels: C-docs

#17083 chore: bump version 1.5.0
  Cargo.lock
  Cargo.toml
Labels: A-meta

#17091 docs: error fixes for clarity
  crates/engine/primitives/src/config.rs
  docs/repo/layout.md
Labels: C-docs

#17093 fix: use safe conversions for number and timestamps
  crates/ethereum/evm/src/build.rs
  crates/optimism/evm/src/build.rs
  crates/rpc/rpc-eth-api/src/helpers/trace.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/eth/bundle.rs
Labels: A-rpc

#17100 docs: debug clarify healtyh node rpc url setting
  crates/node/core/src/args/debug.rs
  docs/vocs/docs/pages/cli/reth/node.mdx
Labels: C-docs

#17103 deps: Upgrade `alloy` and `op-alloy` versions `1.0.13` => `0.18.7` and `0.18.9`
  Cargo.lock
  crates/rpc/rpc-engine-api/tests/it/payload.rs
Labels: dependencies

#17101 feat: use Header AT in `EthChainSpec::next_block_base_fee`
  Cargo.lock
  crates/chainspec/src/api.rs
  crates/consensus/common/src/validation.rs
  crates/ethereum/consensus/src/lib.rs
  crates/ethereum/evm/src/lib.rs
  crates/optimism/consensus/src/lib.rs
  crates/optimism/consensus/src/validation/mod.rs
  crates/optimism/evm/src/lib.rs
  crates/optimism/rpc/src/eth/mod.rs
  crates/rpc/rpc-eth-api/src/helpers/fee.rs
  crates/rpc/rpc/src/eth/helpers/fees.rs
  crates/stateless/src/validation.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/maintain.rs
Labels: M-changelog, A-sdk

#17102 docs: fix typos across documentation
  docs/crates/db.md
  docs/crates/eth-wire.md
  docs/design/database.md
  docs/design/goals.md
  docs/design/review.md
  docs/repo/layout.md
  docs/vocs/docs/pages/introduction/contributing.mdx
  docs/vocs/docs/pages/run/faq/troubleshooting.mdx
Labels: C-docs

#17112 refactor: simplify handling of `NetworkPrimitives` in CLI
  crates/cli/commands/src/common.rs
  crates/cli/commands/src/import.rs
  crates/cli/commands/src/p2p/mod.rs
  crates/cli/commands/src/stage/mod.rs
  crates/cli/commands/src/stage/run.rs
  crates/ethereum/cli/src/interface.rs
  crates/optimism/cli/src/app.rs
Labels: A-cli

#17114 refactor: move ExEx launching to LaunchContext method
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/engine.rs
Labels: C-debt

#17118 chore: tell claude to run fmt before opening a pr
  CLAUDE.md
Labels: A-meta

#17119 refactor: make get_healthy_node_client async
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/engine.rs
Labels: C-debt

#17115 refactor: move ERA import source creation to LaunchContext
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/engine.rs
Labels: C-debt

#17117 refactor: move consensus layer events to launch context
  crates/node/builder/src/launch/common.rs
  crates/node/builder/src/launch/engine.rs
Labels: C-debt

#17105 docs: fix typo in section of node-components.mdx
  docs/vocs/docs/pages/sdk/node-components.mdx
Labels: C-docs

#16934 feat(alloy-provider): implement fetch block
  Cargo.lock
  crates/alloy-provider/Cargo.toml
  crates/alloy-provider/src/lib.rs
  crates/rpc/rpc-convert/src/block.rs
  crates/rpc/rpc-convert/src/lib.rs
Labels: C-enhancement, A-rpc

#17127 docs: fix broken tutorial link
  docs/vocs/docs/pages/exex/remote.mdx
Labels: C-docs

#17130 docs: remove reference to ContextStatefulPrecompile in precompile cache example
  examples/precompile-cache/src/main.rs
Labels: C-docs

#17128 docs: fix installation source URL in ARM devices guide
  docs/vocs/docs/pages/installation/build-for-arm-devices.mdx
Labels: C-docs

#17120 docs: add comprehensive documentation for LaunchContext type system
  crates/node/builder/src/launch/common.rs
Labels: C-docs

#17137 docs: update Engine API link in ethereum.mdx
  docs/vocs/docs/pages/run/ethereum.mdx
Labels: C-docs

#17133 feat(optimism): add debug namespace endpoints to historical RPC forwarding
  crates/optimism/rpc/src/historical.rs
Labels: C-bug, A-rpc

#17099 chore: pass provider into SparseTrie and SparseStateTrie via impl argument in update/remove_leaf
  crates/engine/tree/src/tree/payload_processor/sparse_trie.rs
  crates/stateless/src/trie.rs
  crates/trie/sparse/benches/rlp_node.rs
  crates/trie/sparse/benches/root.rs
  crates/trie/sparse/benches/update.rs
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
  crates/trie/trie/src/witness.rs
Labels: C-debt, A-trie
