Repository paradigmxyz/reth, pull requests merged in 2025-02, with the labels that each got.

#14140 chore: phase out `block_to_payload_v3`
  crates/engine/tree/src/tree/mod.rs
  crates/ethereum/engine-primitives/src/payload.rs
  crates/ethereum/node/tests/e2e/rpc.rs
  crates/optimism/payload/src/payload.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: A-rpc

#14121 [wip] feat: alloy tx type conversions back to OpTransactionSigned
  crates/optimism/primitives/src/transaction/signed.rs
Labels: A-op-reth, A-sdk

#14141 chore: rm Once-cell dep
  Cargo.lock
  crates/ethereum/primitives/Cargo.toml
  crates/ethereum/primitives/src/transaction.rs
Labels: A-dependencies

#14142 chore: remove block_to_payload_v2
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: A-rpc

#14143 chore: remove block_to_payload_v1
  Cargo.lock
  crates/engine/tree/src/tree/mod.rs
  crates/engine/util/Cargo.toml
  crates/ethereum/engine-primitives/Cargo.toml
  crates/ethereum/engine-primitives/src/payload.rs
  crates/optimism/payload/Cargo.toml
  crates/optimism/payload/src/payload.rs
  crates/rpc/rpc-builder/tests/it/auth.rs
  crates/rpc/rpc-engine-api/tests/it/payload.rs
  crates/rpc/rpc-types-compat/src/engine/mod.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
Labels: A-rpc

#14147 meta: temporarily allow missing const for fn
  Cargo.toml
Labels: A-meta

#14146 feat: simplify envelope conversion
  crates/ethereum/primitives/src/transaction.rs
  crates/optimism/primitives/src/transaction/signed.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/rpc/rpc/src/eth/helpers/types.rs
Labels: A-rpc, A-sdk

#14144 chore: use rlp_length_for
  crates/primitives-traits/src/block/mod.rs
  crates/rpc/rpc-types-compat/src/block.rs
Labels: A-sdk

#14135 feat(grafana): add cache hitrate panel
  etc/grafana/dashboards/overview.json
Labels: C-enhancement, C-perf, A-observability

#14134 perf: add more granular newPayload metrics
  crates/engine/tree/src/tree/metrics.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, C-perf, A-observability

#14148 fix: rename variables and fix typos in tables.rs, execution.rs, and mdbx code
  crates/cli/commands/src/test_vectors/tables.rs
  crates/stages/stages/src/stages/execution.rs
Labels: C-docs

#14167 chore(ci): unpin clippy
  .github/workflows/lint.yml
  crates/net/network/src/peers.rs
Labels: A-ci

#14162 feat: abstract `EthTransactionValidator` over `ChainSpec`
  bin/reth/src/commands/debug_cmd/build_block.rs
  crates/ethereum/node/src/node.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/optimism/evm/src/l1.rs
  crates/optimism/node/src/node.rs
  crates/optimism/node/src/txpool.rs
  crates/optimism/rpc/src/eth/receipt.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/transaction-pool/src/lib.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/task.rs
  examples/custom-node-components/src/main.rs
Labels: A-sdk

#14172 refactor: couple ExecutionPayload and ExecutionPayloadSidecar
  Cargo.lock
  crates/engine/local/src/miner.rs
  crates/engine/primitives/src/lib.rs
  crates/engine/primitives/src/message.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/util/src/engine_store.rs
  crates/engine/util/src/reorg.rs
  crates/engine/util/src/skip_new_payload.rs
  crates/ethereum/engine-primitives/src/lib.rs
  crates/optimism/node/src/engine.rs
  crates/payload/validator/Cargo.toml
  crates/payload/validator/src/lib.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc/src/validation.rs
  examples/custom-engine-types/src/main.rs
Labels: A-rpc

#14173 feat: add dedicated blobpool args to cli
  book/cli/reth/node.md
  crates/node/core/src/args/txpool.rs
Labels: C-enhancement, A-cli

#14168 chore: convert_to_payload_body_v1
  Cargo.lock
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc-types-compat/Cargo.toml
  crates/rpc/rpc-types-compat/src/engine/mod.rs
  crates/rpc/rpc-types-compat/src/engine/payload.rs
  crates/rpc/rpc-types-compat/src/lib.rs
Labels: A-rpc

#14183 chore: rm unused error variants
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  crates/engine/tree/src/tree/error.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/util/src/reorg.rs
  crates/evm/execution-errors/src/lib.rs
  crates/stages/stages/src/stages/execution.rs
Labels: C-debt, A-observability

#14180 feat: add helpers for handling other errors
  crates/evm/execution-errors/src/lib.rs
Labels: A-sdk

#14182 chore: rm unused rpc_types_compat import from reth-bench
  Cargo.lock
  bin/reth-bench/Cargo.toml
Labels: C-debt

#14184 ci: enable getreceipts hive test again
  .github/assets/hive/expected_failures.yaml
Labels: C-hivetest

#14185 chore: rm unused prune error variant
  Cargo.lock
  crates/evm/execution-errors/Cargo.toml
  crates/evm/execution-errors/src/lib.rs
Labels: C-debt

#14186 ci: ensure consensus crates remain riscv compatible
  .github/assets/check_rv32imac.sh
Labels: A-ci

#14179 feat: add `ExecutionData` AT
  Cargo.lock
  crates/engine/primitives/Cargo.toml
  crates/engine/primitives/src/lib.rs
  crates/engine/primitives/src/message.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/util/src/engine_store.rs
  crates/engine/util/src/reorg.rs
  crates/engine/util/src/skip_new_payload.rs
  crates/ethereum/engine-primitives/src/lib.rs
  crates/node/builder/src/rpc.rs
  crates/optimism/node/src/engine.rs
  crates/payload/validator/src/lib.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc/src/validation.rs
  examples/custom-engine-types/src/main.rs
Labels: A-rpc, A-sdk

#14187 feat(no_std): Add `no_std` support for `reth-storage-api`
  Cargo.lock
  crates/optimism/primitives/src/transaction/signed.rs
  crates/optimism/rpc/src/eth/transaction.rs
  crates/storage/storage-api/Cargo.toml
  crates/storage/storage-api/src/account.rs
  crates/storage/storage-api/src/block.rs
  crates/storage/storage-api/src/block_hash.rs
  crates/storage/storage-api/src/block_indices.rs
  crates/storage/storage-api/src/chain.rs
  crates/storage/storage-api/src/chain_info.rs
  crates/storage/storage-api/src/database_provider.rs
  crates/storage/storage-api/src/hashing.rs
  crates/storage/storage-api/src/header.rs
  crates/storage/storage-api/src/history.rs
  crates/storage/storage-api/src/legacy.rs
  crates/storage/storage-api/src/lib.rs
  crates/storage/storage-api/src/noop.rs
  crates/storage/storage-api/src/ommers.rs
  crates/storage/storage-api/src/prune_checkpoint.rs
  crates/storage/storage-api/src/receipts.rs
  crates/storage/storage-api/src/stage_checkpoint.rs
  crates/storage/storage-api/src/state.rs
  crates/storage/storage-api/src/storage.rs
  crates/storage/storage-api/src/transactions.rs
Labels: A-db, A-dependencies

#14171 feat: abstract `OpBeaconConsensus` over primitives and chainspec
  crates/optimism/chainspec/src/lib.rs
  crates/optimism/consensus/Cargo.toml
  crates/optimism/consensus/src/lib.rs
  crates/optimism/consensus/src/proof.rs
  crates/optimism/consensus/src/validation.rs
  crates/optimism/evm/src/config.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/evm/src/lib.rs
  crates/optimism/node/src/node.rs
Labels: A-op-reth, A-sdk

#14204 feat: type erase concrete engine server trait
  crates/rpc/rpc-api/src/engine.rs
  crates/rpc/rpc-api/src/lib.rs
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
Labels: A-rpc, A-op-reth

#14205 feat: expose blob_store fn on top level pool type
  crates/transaction-pool/src/lib.rs
Labels: C-enhancement, A-tx-pool

#14198 fix(reth-bench): return error on invalid range
  bin/reth-bench/src/bench/new_payload_fcu.rs
  bin/reth-bench/src/bench/new_payload_only.rs
  bin/reth-bench/src/valid_payload.rs
Labels: C-enhancement, C-perf, C-benchmark

#14009 ci(hive): add `ethereum/eest` simulator
  .github/assets/hive/build_simulators.sh
  .github/assets/hive/expected_failures.yaml
  .github/assets/hive/load_images.sh
  .github/assets/hive/run_simulator.sh
  .github/workflows/hive.yml
Labels: C-hivetest, A-ci

#14215 fix: rm redundant revert in error message
  crates/rpc/rpc-eth-types/src/error/mod.rs
Labels: C-bug, A-rpc

#14209 feat(isthmus): withdrawals root in block building
  crates/optimism/payload/src/builder.rs
  crates/optimism/primitives/src/lib.rs
  crates/optimism/primitives/src/predeploys.rs
Labels: A-block-building, A-op-reth

#14221 fix: use different cancel wrapper for prewarm tasks
  bin/reth/src/commands/debug_cmd/build_block.rs
  crates/engine/tree/src/tree/mod.rs
  crates/optimism/payload/src/builder.rs
  crates/payload/basic/src/lib.rs
  crates/revm/src/cancelled.rs
Labels: C-perf, A-execution, A-blockchain-tree

#14224 docs: add docs for instantiating EthFilter
  crates/ethereum/evm/src/lib.rs
  crates/rpc/rpc-eth-api/src/types.rs
  crates/rpc/rpc/src/eth/core.rs
  crates/rpc/rpc/src/eth/filter.rs
Labels: C-docs, C-enhancement

#14228 chore: use alloy traits for `PoolTransaction`
  Cargo.lock
  crates/net/network/src/transactions/mod.rs
  crates/optimism/node/src/txpool.rs
  crates/transaction-pool/benches/reorder.rs
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/pool/blob.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/parked.rs
  crates/transaction-pool/src/pool/pending.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/mod.rs
  crates/transaction-pool/tests/it/evict.rs
  examples/network-txpool/Cargo.toml
  examples/network-txpool/src/main.rs
Labels: A-tx-pool

#14225 chore: simplify rpc block compat
  crates/rpc/rpc-types-compat/src/block.rs
Labels: C-debt, A-rpc

#14234 chore: enable rand in test utils
  crates/net/p2p/Cargo.toml
Labels: A-dependencies

#14217 fix: use blob params in payload building
  crates/ethereum/payload/src/lib.rs
Labels: A-block-building, E-prague

#14239 chore(ci): update hive expected failures
  .github/assets/hive/expected_failures.yaml
Labels: C-hivetest

#14046 refactor: Adds type downcasting helpers for `InvalidPoolTransactionError`
  crates/transaction-pool/src/error.rs
Labels: A-op-reth, A-sdk

#14222 fix: use proofs from prefetch and updates for root completion
  crates/engine/tree/src/tree/root.rs
Labels: C-bug, A-trie

#14218 chore: move `Transaction lock acquired` mdbx log to trace
  crates/storage/libmdbx-rs/src/transaction.rs
Labels: C-perf, A-observability

#14232 feat: add exceeds allowance error message
  crates/rpc/rpc-eth-api/src/helpers/estimate.rs
  crates/rpc/rpc-eth-types/src/error/mod.rs
Labels: C-bug, A-rpc, A-observability

#14231 feat: track max blobcount in forktracker
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool, E-prague

#14223 perf(trie): deduplicate already fetched prefetch targets
  crates/engine/tree/src/tree/root.rs
Labels: C-perf, A-trie

#14246 chore: simplify `PayloadBuilder` trait
  Cargo.lock
  bin/reth/src/commands/debug_cmd/build_block.rs
  crates/ethereum/node/src/payload.rs
  crates/ethereum/payload/src/lib.rs
  crates/optimism/node/src/node.rs
  crates/optimism/payload/src/builder.rs
  crates/optimism/rpc/src/witness.rs
  crates/payload/basic/Cargo.toml
  crates/payload/basic/src/lib.rs
  crates/payload/basic/src/stack.rs
  examples/custom-engine-types/src/main.rs
  examples/custom-payload-builder/src/generator.rs
  examples/custom-payload-builder/src/job.rs
  examples/custom-payload-builder/src/main.rs
Labels: M-changelog, A-block-building

#14252 chore: remove usages of reth_primitives from reth bin
  Cargo.lock
  bin/reth/Cargo.toml
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/execution.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  bin/reth/src/commands/debug_cmd/mod.rs
Labels: C-enhancement, C-debt, A-cli, A-sdk

#14253 fix: use correct default for get_local_pending_transactions
  crates/transaction-pool/src/traits.rs
Labels: C-bug, A-tx-pool

#14249 feat: expose pool transaction in `PayloadTransactions`
  .github/assets/check_wasm.sh
  Cargo.lock
  crates/optimism/node/src/node.rs
  crates/optimism/node/tests/it/priority.rs
  crates/optimism/payload/src/builder.rs
  crates/optimism/rpc/src/witness.rs
  crates/payload/util/Cargo.toml
  crates/payload/util/src/lib.rs
  crates/payload/util/src/traits.rs
  crates/payload/util/src/transaction.rs
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/pool/best.rs
  crates/transaction-pool/src/pool/mod.rs
  crates/transaction-pool/src/pool/pending.rs
Labels: C-enhancement, A-block-building, A-tx-pool, A-op-reth

#14258 chore: rm reth_primitives from reth_net_p2p
  Cargo.lock
  crates/net/p2p/Cargo.toml
  crates/net/p2p/src/bodies/client.rs
  crates/net/p2p/src/bodies/response.rs
  crates/net/p2p/src/error.rs
  crates/net/p2p/src/full_block.rs
  crates/net/p2p/src/headers/error.rs
  crates/net/p2p/src/lib.rs
  crates/net/p2p/src/sync.rs
  crates/net/p2p/src/test_utils/bodies.rs
  crates/net/p2p/src/test_utils/full_block.rs
  crates/net/p2p/src/test_utils/headers.rs
Labels: C-debt, A-sdk

#14243 feat: handle Isthmus operator fee params
  crates/optimism/evm/src/l1.rs
Labels: A-op-reth

#14242 [Feature]: added max lifetime setting for queued transactions
  crates/transaction-pool/src/maintain.rs
Labels: A-tx-pool

#14256 feat: abstract `OpPooledTransaction` and `OpPool` over consensus tx
  crates/optimism/node/src/node.rs
  crates/optimism/node/src/txpool.rs
  crates/optimism/node/tests/it/priority.rs
  crates/rpc/rpc/src/eth/bundle.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/test_utils/gen.rs
  crates/transaction-pool/src/test_utils/mock.rs
  crates/transaction-pool/src/traits.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: A-sdk

#14264 feat(op, txpool): add conditionals to op pooled tx
  Cargo.lock
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/txpool.rs
Labels: A-block-building, A-tx-pool, A-op-reth

#14261 Avoiding infinite recursion in trait implementation
  crates/node/core/src/cli/config.rs
Labels: C-bug, A-cli

#14272 chore: use recovered api for prewarm
  crates/engine/tree/src/tree/mod.rs
Labels: C-debt, A-engine

#13769 perf(tree): add cross-block caching
  Cargo.lock
  Cargo.toml
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/tree/cached_state.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, C-perf, A-execution

#14276 feat: simplify PayloadBuilder setup
  Cargo.lock
  crates/e2e-test-utils/src/node.rs
  crates/e2e-test-utils/src/payload.rs
  crates/engine/local/Cargo.toml
  crates/engine/local/src/miner.rs
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/tree/mod.rs
  crates/ethereum/node/Cargo.toml
  crates/ethereum/node/src/payload.rs
  crates/ethereum/node/tests/e2e/utils.rs
  crates/exex/test-utils/Cargo.toml
  crates/exex/test-utils/src/lib.rs
  crates/node/api/Cargo.toml
  crates/node/api/src/node.rs
  crates/node/builder/Cargo.toml
  crates/node/builder/src/builder/states.rs
  crates/node/builder/src/components/builder.rs
  crates/node/builder/src/components/mod.rs
  crates/node/builder/src/components/payload.rs
  crates/node/builder/src/launch/engine.rs
  crates/node/builder/src/node.rs
  crates/node/builder/src/rpc.rs
  crates/optimism/node/src/node.rs
  crates/payload/builder-primitives/Cargo.toml
  crates/payload/builder-primitives/src/lib.rs
  crates/payload/builder-primitives/src/traits.rs
  crates/payload/builder/Cargo.toml
  crates/payload/builder/src/service.rs
  examples/custom-engine-types/src/main.rs
  examples/custom-evm/Cargo.toml
  examples/custom-evm/src/main.rs
  examples/custom-payload-builder/src/main.rs
Labels: C-enhancement, S-blocked, A-sdk

#14287 feat: add newPayload latency gauge metric
  crates/rpc/rpc-engine-api/src/metrics.rs
Labels: C-perf, A-observability

#14285 feat: abstract op executor over chainspec
  crates/optimism/evm/src/execute.rs
  crates/optimism/evm/src/l1.rs
Labels: A-op-reth, A-sdk

#14289 chore: rm todo
  crates/stages/api/src/pipeline/mod.rs
Labels: C-debt

#14291 feat: remove from fspath conversion for storagelockerr
  Cargo.lock
  crates/storage/db/src/lockfile.rs
  crates/storage/errors/Cargo.toml
  crates/storage/errors/src/lockfile.rs
Labels: C-enhancement

#14290 chore(txpool): explicity drift txpool on first event
  crates/transaction-pool/src/maintain.rs
Labels: C-enhancement, A-tx-pool

#14295 chore: rm unused cli args
  bin/reth/src/cli/mod.rs
  book/cli/reth/stage/unwind.md
  crates/cli/commands/src/stage/mod.rs
  crates/cli/commands/src/stage/unwind.rs
Labels: A-cli

#14265 perf(tree): short-circuit multiproof computation on empty targets
  crates/engine/tree/src/tree/root.rs
Labels: C-enhancement, C-perf, A-trie

#14297 chore(engine): make invalid headers cache pub
  crates/engine/tree/src/tree/invalid_headers.rs
  crates/engine/tree/src/tree/mod.rs
Labels: A-engine

#14294 Introduce AnyError
  crates/storage/errors/src/any.rs
  crates/storage/errors/src/lib.rs
  crates/storage/errors/src/provider.rs
Labels: C-enhancement

#14303 fix(provider): fix pending block retrieval in `find_block_by_hash`
  crates/storage/provider/src/providers/consistent.rs
Labels: C-bug, A-db

#14302 docs(tree): state root task lifecycle
  crates/engine/tree/src/tree/root.rs
Labels: C-docs, A-engine

#14281 feat: record save_cache duration metrics
  crates/engine/tree/src/tree/metrics.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-perf, A-observability

#14282 feat: add granular prewarm metrics
  crates/engine/tree/src/tree/metrics.rs
  crates/engine/tree/src/tree/mod.rs
Labels: C-perf, A-execution, A-observability

#14304 integration test for capability version mismatch
  crates/net/network/tests/it/session.rs
Labels: C-test, A-networking

#14309 feat: add standalone DockerfileOp for local building
  DockerfileOp
Labels: C-enhancement, O-docker

#14318 chore: bump alloy-trie to 0.7.9
  Cargo.lock
Labels: A-trie

#14317 chore: rm reth_primitives from reth_revm
  Cargo.lock
  crates/revm/Cargo.toml
  crates/revm/src/batch.rs
  crates/revm/src/database.rs
  crates/revm/src/test_utils.rs
Labels: C-debt, A-sdk

#14322 feat: add providerfactory builder to OpNode
  crates/ethereum/node/src/node.rs
  crates/optimism/node/src/node.rs
Labels: A-sdk

#14323 feat: Add `is_vx` helpers for EngineApiMessageVersion
  crates/payload/primitives/src/lib.rs
Labels: A-rpc

#14329 chore: add serde feature to stages types
  crates/config/Cargo.toml
  crates/stages/types/Cargo.toml
  crates/stages/types/src/checkpoints.rs
  crates/storage/db-api/Cargo.toml
  crates/storage/provider/Cargo.toml
  crates/trie/trie/Cargo.toml
Labels: A-dependencies

#14330 chore: typos
  examples/custom-payload-builder/src/job.rs
  examples/custom-rlpx-subprotocol/src/subprotocol/protocol/proto.rs
Labels: C-docs

#14327 chore: add codec and serde features to prune types
  crates/config/Cargo.toml
  crates/exex/exex/Cargo.toml
  crates/prune/types/Cargo.toml
  crates/prune/types/src/checkpoint.rs
  crates/prune/types/src/lib.rs
  crates/prune/types/src/mode.rs
  crates/prune/types/src/segment.rs
  crates/prune/types/src/target.rs
  crates/storage/db-api/Cargo.toml
  crates/storage/db/Cargo.toml
  crates/storage/provider/Cargo.toml
Labels: A-dependencies

#14325 feat: add other helpers for ProviderError
  crates/storage/errors/src/provider.rs
Labels: C-enhancement

#14336 fix: update --rpc-cache.headers name
  book/cli/reth/node.md
  crates/node/core/src/args/rpc_state_cache.rs
Labels: A-rpc, A-cli

#14334 chore: make stages types no-std
  Cargo.toml
  crates/stages/types/Cargo.toml
  crates/stages/types/src/checkpoints.rs
  crates/stages/types/src/id.rs
  crates/stages/types/src/lib.rs
  crates/storage/storage-api/Cargo.toml
Labels: A-dependencies

#14288 test: add a test for devnet failure
  crates/e2e-test-utils/src/node.rs
  crates/ethereum/node/tests/e2e/p2p.rs
  crates/net/downloaders/src/headers/reverse_headers.rs
  crates/net/downloaders/src/headers/task.rs
  crates/net/p2p/src/headers/downloader.rs
Labels: C-bug, A-staged-sync

#14341 feat(engine): emit events with executed blocks
  Cargo.lock
  crates/engine/primitives/Cargo.toml
  crates/engine/primitives/src/event.rs
  crates/engine/primitives/src/lib.rs
  crates/engine/tree/src/tree/mod.rs
  crates/node/events/src/node.rs
Labels: C-enhancement, A-engine

#14343 chore(ci): pin op-node image for kurtosis-op
  .github/assets/kurtosis_op_network_params.yaml
Labels: A-ci

#14268 added EventSender to FullNode type
  Cargo.lock
  crates/node/api/Cargo.toml
  crates/node/api/src/node.rs
  crates/node/builder/src/launch/engine.rs
  crates/node/builder/src/rpc.rs
  crates/tokio-util/src/event_sender.rs
Labels: C-enhancement, A-sdk

#14326 added helper error enums for L1BlockInfoError
  crates/net/network/src/peers.rs
  crates/net/network/src/test_utils/testnet.rs
  crates/optimism/evm/src/error.rs
  crates/optimism/evm/src/l1.rs
Labels: C-debt, A-op-reth

#14346 add debug_chainConfig endpoint
  Cargo.lock
  crates/rpc/rpc-api/Cargo.toml
  crates/rpc/rpc-api/src/debug.rs
  crates/rpc/rpc/src/debug.rs
Labels: A-rpc

#14270 prague: testnet timestamps
  crates/chainspec/src/spec.rs
  crates/ethereum-forks/src/hardfork/ethereum.rs
Labels: E-prague

#14353 Fix: Correct functionality of `get_queued_transactions_by_sender` and `get_pending_transactions_by_sender`
  crates/transaction-pool/src/pool/mod.rs
Labels: C-bug, A-tx-pool

#14357 chore: rm reth-primitives from eth payload
  Cargo.lock
  crates/ethereum/payload/Cargo.toml
  crates/ethereum/payload/src/lib.rs
Labels: A-dependencies

#14356 feat: avoid zstd dependency in reth-evm, reth-evm-ethereum and reth-optimism-evm
  Cargo.lock
  crates/ethereum/evm/Cargo.toml
  crates/ethereum/evm/src/execute.rs
  crates/ethereum/evm/src/lib.rs
  crates/evm/Cargo.toml
  crates/evm/src/batch.rs
  crates/evm/src/execute.rs
  crates/evm/src/lib.rs
  crates/optimism/evm/Cargo.toml
  crates/optimism/evm/src/execute.rs
  crates/optimism/evm/src/lib.rs
  crates/revm/Cargo.toml
  crates/revm/src/lib.rs
Labels: A-dependencies

#14363 feat(tree): enter tracing span for each storage trie in state root task
  crates/engine/tree/src/tree/root.rs
Labels: C-enhancement, A-observability, A-engine

#14369 feat(engine): emit invalid block on invalid ancestor
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-engine

#14367 chore: remove code snippets from stages.md
  docs/crates/stages.md
Labels: C-docs

#14359 feat(l2-withdrawals): Declare `OpEngineApiServer` and `OpEngineApiClient`
  Cargo.lock
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/engine.rs
  crates/optimism/rpc/src/lib.rs
Labels: C-enhancement, A-rpc, A-op-reth

#14361 feat: add reth-eth meta crate
  Cargo.lock
  Cargo.toml
  crates/ethereum/reth/Cargo.toml
  crates/ethereum/reth/src/lib.rs
Labels: A-meta

#14370 fix(trie): do not reveal same node twice in sparse trie
  crates/engine/tree/src/tree/root.rs
  crates/trie/sparse/src/state.rs
  crates/trie/trie/src/witness.rs
Labels: C-bug, A-trie

#14350 Added from<alloy_rpc_types_eth::Transaction> for TransactionSigned
  Cargo.lock
  crates/ethereum/primitives/Cargo.toml
  crates/ethereum/primitives/src/alloy_compat.rs
  crates/ethereum/primitives/src/lib.rs
  crates/rpc/rpc-types-compat/Cargo.toml
Labels: A-rpc

#14374 chore: abstract `OpPayloadBuilder` over `ChainSpec`
  Cargo.lock
  crates/optimism/payload/Cargo.toml
  crates/optimism/payload/src/builder.rs
Labels: A-sdk

#14381 chore: re-export rpc types
  Cargo.lock
  crates/ethereum/reth/Cargo.toml
  crates/ethereum/reth/src/lib.rs
Labels: A-meta

#14339 chore: correct the comments
  crates/node/core/src/utils.rs
  crates/optimism/bin/src/lib.rs
  crates/optimism/cli/src/commands/init_state.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/node/tests/e2e/p2p.rs
  crates/payload/primitives/src/payload.rs
  crates/primitives-traits/src/log.rs
Labels: C-docs

#14305 feat: add cross-block cache size cli arg
  book/cli/reth/node.md
  crates/engine/tree/src/tree/cached_state.rs
  crates/engine/tree/src/tree/config.rs
  crates/engine/tree/src/tree/mod.rs
  crates/node/builder/src/builder/mod.rs
  crates/node/core/src/args/engine.rs
  crates/node/core/src/node_config.rs
Labels: C-enhancement, C-perf, A-cli, A-engine

#14292 Introduce StatusEth69 for `eth/69` status messages
  crates/net/eth-wire-types/src/lib.rs
  crates/net/eth-wire-types/src/status.rs
Labels: A-networking

#14273 feat: Add cli arg for pool lifetime
  book/cli/reth/node.md
  crates/node/core/src/args/txpool.rs
  crates/transaction-pool/src/config.rs
  crates/transaction-pool/src/maintain.rs
Labels: A-cli

#14390 fix: bytecode override
  crates/rpc/rpc-eth-types/src/error/mod.rs
  crates/rpc/rpc-eth-types/src/revm_utils.rs
Labels: C-bug, A-rpc

#14396 chore: rm unused dependencies from optimism crates
  Cargo.lock
  crates/optimism/bin/Cargo.toml
  crates/optimism/evm/Cargo.toml
  crates/optimism/node/Cargo.toml
  crates/rpc/rpc-eth-types/src/error/mod.rs
Labels: A-dependencies

#14392 chore: remove unused arbitrary dep from optimism-primitives
  crates/optimism/primitives/Cargo.toml
Labels: A-cli

#14401 feat: add reth-op crate
  .config/zepter.yaml
  Cargo.lock
  Cargo.toml
  crates/engine/local/Cargo.toml
  crates/optimism/reth/Cargo.toml
  crates/optimism/reth/src/lib.rs
  crates/primitives-traits/Cargo.toml
  crates/storage/db-api/Cargo.toml
  crates/storage/db/Cargo.toml
Labels: A-meta

#14387 feat(engine): use Hash Builder as a fallback to the Sparse Trie on newPayload
  crates/engine/tree/src/tree/mod.rs
Labels: C-enhancement, A-engine, A-trie

#14371 feat(bin, engine): make state root task default
  book/cli/reth/node.md
  crates/e2e-test-utils/src/node.rs
  crates/engine/tree/src/tree/config.rs
  crates/engine/tree/src/tree/mod.rs
  crates/node/builder/src/builder/mod.rs
  crates/node/core/src/args/engine.rs
Labels: A-cli, A-engine

#14405 fix(validation-rpc): validate against parent, not latest
  crates/rpc/rpc/src/validation.rs
Labels: C-bug, A-rpc

#14408 chore: bump revm 19.5
  Cargo.lock
  Cargo.toml
Labels: A-dependencies, A-op-reth

#14393 chore: add root_with_updates method to sparse trie
  crates/engine/tree/src/tree/root.rs
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
Labels: C-enhancement, A-trie

#14402 fix(ci): changes in kurtosis-op network config latest optimism package
  .github/assets/kurtosis_op_network_params.yaml
Labels: A-ci

#14413 fix: use generic table types
  crates/storage/provider/src/providers/static_file/manager.rs
Labels: C-bug, A-db, A-op-reth

#14412 perf: only fetch parent if not latest
  crates/rpc/rpc/src/validation.rs
Labels: C-perf, A-rpc

#14418 fix(tree): state root task finished log
  crates/engine/tree/src/tree/mod.rs
Labels: C-bug, A-observability, A-engine

#14419 chore(tree): expect message on state root handle unwrap
  crates/engine/tree/src/tree/mod.rs
Labels: C-debt, A-engine

#14414 feat(l2-withdrawals): Define `OpEngineApi`
  Cargo.lock
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/engine.rs
  crates/optimism/rpc/src/lib.rs
Labels: A-rpc, A-op-reth

#14403 feat: append tx conditional to pooled tx
  Cargo.lock
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/eth/ext.rs
Labels: A-op-reth, A-sdk

#14422 feat: impl serde for OpPrimitives
  crates/optimism/primitives/src/lib.rs
Labels: A-op-reth

#14427 chore: rm unused err variant
  crates/storage/errors/src/provider.rs
Labels: C-debt

#14428 chore: phase out reth-primitives from op-evm
  Cargo.lock
  crates/optimism/evm/Cargo.toml
  crates/optimism/evm/src/execute.rs
  crates/optimism/evm/src/l1.rs
  crates/optimism/evm/src/lib.rs
Labels: A-dependencies

#14426 feat(l2-withdrawals): Define `OpEngineApiBuilder`
  Cargo.lock
  crates/optimism/node/src/lib.rs
  crates/optimism/node/src/node.rs
  crates/optimism/node/src/rpc.rs
  crates/optimism/rpc/Cargo.toml
  crates/optimism/rpc/src/engine.rs
Labels: A-rpc, A-op-reth, A-sdk

#14409 chore: use reth-ethereum in example
  Cargo.lock
  crates/ethereum/reth/Cargo.toml
  crates/ethereum/reth/src/lib.rs
  crates/primitives-traits/src/block/header.rs
  crates/primitives-traits/src/lib.rs
  examples/db-access/Cargo.toml
  examples/db-access/src/main.rs
Labels: A-dependencies

#14333 feat: Return root result without blocking due to sparse trie Drop
  crates/engine/tree/src/tree/root.rs
Labels: C-perf, A-trie

#14439 chore: bump alloy 0.11.1
  Cargo.lock
  Cargo.toml
  crates/chain-state/src/test_utils.rs
  crates/engine/tree/src/backfill.rs
  crates/engine/tree/src/download.rs
  crates/ethereum/payload/src/config.rs
  crates/node/core/src/args/payload_builder.rs
  crates/node/core/src/args/txpool.rs
  crates/rpc/rpc-builder/tests/it/auth.rs
  crates/rpc/rpc-server-types/src/constants.rs
  crates/rpc/rpc/src/eth/helpers/state.rs
  crates/rpc/rpc/src/eth/helpers/transaction.rs
  crates/transaction-pool/src/config.rs
  crates/transaction-pool/src/noop.rs
  crates/transaction-pool/src/pool/txpool.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/tests/it/evict.rs
Labels: A-dependencies

#14440 refactor: Add more low-level methods to `Executor`
  crates/ethereum/evm/src/execute.rs
  crates/evm/execution-types/src/execute.rs
  crates/evm/src/either.rs
  crates/evm/src/execute.rs
  crates/evm/src/metrics.rs
  crates/evm/src/noop.rs
  crates/evm/src/test_utils.rs
  crates/optimism/evm/src/execute.rs
  examples/custom-beacon-withdrawals/src/main.rs
Labels: A-sdk

#14443 chore: export exex
  Cargo.lock
  crates/ethereum/reth/Cargo.toml
  crates/ethereum/reth/src/lib.rs
Labels: A-meta

#13318 Increase default gas limit from 30M to 36M
  book/cli/reth/node.md
  crates/node/core/src/args/payload_builder.rs
Labels: A-execution

#14446 feat(optimism): disable state root task by default
  crates/node/core/src/args/engine.rs
  crates/optimism/cli/src/lib.rs
Labels: C-enhancement, A-cli, A-engine, A-op-reth

#14400 docs(tree): state root task
  crates/engine/tree/docs/mermaid/engine.mmd
  crates/engine/tree/docs/mermaid/engine.mmd.png
  crates/engine/tree/docs/mermaid/multiproof-manager.mmd
  crates/engine/tree/docs/mermaid/multiproof-manager.mmd.png
  crates/engine/tree/docs/mermaid/sparse-trie-task.mmd
  crates/engine/tree/docs/mermaid/sparse-trie-task.mmd.png
  crates/engine/tree/docs/mermaid/sparse-trie.mmd
  crates/engine/tree/docs/mermaid/sparse-trie.mmd.png
  crates/engine/tree/docs/mermaid/state-root-task.mmd
  crates/engine/tree/docs/mermaid/state-root-task.mmd.png
  crates/engine/tree/docs/root.md
Labels: C-docs, A-engine

#14444 chore: export cli from reth ethereum
  Cargo.lock
  crates/ethereum/reth/Cargo.toml
  crates/ethereum/reth/src/lib.rs
Labels: A-dependencies, A-meta

#14432 fix(grafana): use correct datasource for all metrics
  etc/grafana/dashboards/overview.json
Labels: C-bug, A-observability

#14449 fix(trie): reveal blinded sparse trie when calculating root
  crates/engine/tree/src/tree/root.rs
  crates/trie/common/src/proofs.rs
  crates/trie/sparse/src/state.rs
  crates/trie/sparse/src/trie.rs
Labels: C-bug, A-engine, A-trie

#14451 feat: add Block::seal
  crates/primitives-traits/src/block/mod.rs
Labels: C-enhancement

#14438 chore: release v1.2.0
  Cargo.lock
  Cargo.toml
Labels: A-dependencies

#14454 chore(ci): update hive expected failures
  .github/assets/hive/expected_failures.yaml
Labels: C-hivetest, A-ci

#14458 fix(ci): docker release
  .github/workflows/release.yml
Labels: C-bug, A-ci

#14456 chore: fix
  crates/payload/builder-primitives/src/events.rs
  crates/payload/primitives/src/traits.rs
  crates/payload/validator/src/lib.rs
Labels: C-docs, A-observability

#14463 chore: rm comment about hardfork
  crates/chainspec/src/api.rs
Labels: C-debt

#14188 Upstream ExecutionData to alloy
  Cargo.lock
  crates/engine/primitives/src/lib.rs
  crates/engine/tree/src/tree/mod.rs
  crates/engine/util/src/reorg.rs
  crates/ethereum/engine-primitives/src/lib.rs
  crates/node/builder/src/rpc.rs
  crates/optimism/node/src/engine.rs
  crates/optimism/node/src/rpc.rs
  crates/optimism/rpc/src/engine.rs
  crates/payload/validator/Cargo.toml
  crates/payload/validator/src/lib.rs
  crates/rpc/rpc-builder/Cargo.toml
  crates/rpc/rpc-builder/src/lib.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc/src/validation.rs
  examples/custom-engine-types/src/main.rs
Labels: C-debt, A-dependencies

#14462 chore: phase out reth-primitives from storage-api
  Cargo.lock
  crates/storage/storage-api/Cargo.toml
  crates/storage/storage-api/src/block.rs
  crates/storage/storage-api/src/chain.rs
  crates/storage/storage-api/src/hashing.rs
  crates/storage/storage-api/src/noop.rs
Labels: A-dependencies

#14260 [Feature]: Add Opstack superchain registry support for genesis files
  .github/assets/check_wasm.sh
  Cargo.lock
  Cargo.toml
  crates/optimism/chain-registry/Cargo.toml
  crates/optimism/chain-registry/src/client.rs
  crates/optimism/chain-registry/src/lib.rs
Labels: A-cli, A-op-reth

#14386 Simplified the sequencer forwarding RPC calls
  crates/optimism/rpc/src/sequencer.rs
Labels: C-enhancement, A-op-reth

#11855 feat: drop ExEx WAL on `reth db drop`
  crates/cli/commands/src/db/mod.rs
  crates/storage/db-common/src/db_tool/mod.rs
Labels: C-enhancement, A-db, A-cli, A-exex

#14466 Disable default features for `reth-storage-api` in workspace manifest
  Cargo.lock
  Cargo.toml
  crates/chain-state/Cargo.toml
  crates/ethereum/payload/Cargo.toml
  crates/ethereum/reth/Cargo.toml
  crates/net/downloaders/Cargo.toml
  crates/net/network/Cargo.toml
  crates/node/core/Cargo.toml
  crates/node/events/Cargo.toml
  crates/optimism/reth/Cargo.toml
  crates/optimism/txpool/Cargo.toml
  crates/revm/Cargo.toml
  crates/rpc/rpc-engine-api/Cargo.toml
  crates/rpc/rpc-eth-types/Cargo.toml
  crates/storage/provider/Cargo.toml
  crates/storage/storage-api/Cargo.toml
  crates/storage/storage-api/src/chain_info.rs
  crates/transaction-pool/Cargo.toml
  crates/trie/sparse/Cargo.toml
Labels: C-debt, A-dependencies

#14473 fix static file derive
  crates/storage/provider/src/providers/database/builder.rs
  examples/db-access/src/main.rs
Labels: C-bug, A-db

#14467 Disable default features for optimism crates in workspace manifest
  Cargo.toml
  crates/optimism/evm/Cargo.toml
  crates/optimism/primitives/Cargo.toml
  crates/optimism/reth/Cargo.toml
  crates/revm/Cargo.toml
Labels: C-debt, A-dependencies
